import {guide,phase,step,photos,collection,reddit,illustrated} from './bo2-common.mjs'
const m='mob-of-the-dead',pics=(...ids)=>photos(m,...ids),set=prefix=>collection(m,prefix)
export const mobGuide=guide(m,'Mob of the Dead','Use Afterlife to power Alcatraz, build the escape plane and break the cycle. Setup, the plane, Hell’s Retriever, Acid Gat, Redeemer and Golden Spork can be done solo; the Pop Goes the Weasel ending needs 2–4 players, including Albert “Weasel” Arlington, on Original difficulty. This is BO2 Mob, not BO4 Blood of the Dead.',[
 phase('setup','Afterlife, power and the Warden’s Key',[
  step('setup-afterlife','At the start, revive your body to leave Afterlife. Later, use the red electrical boxes to enter it deliberately. Your ghost can jump through blue doorways, shock power meters and return to revive your body before the timer empties. Plan two nearby tasks per trip but leave time for the return. Solo can bank up to three charges; co-op players normally have one, replenished each round. Do not spend the last charge immediately before a risky fight.','Use electrical boxes for Afterlife; shock meters and return before the timer ends.',{images:pics('afterlife_mode/electrical_box','power/perk_voltmeter')}),
  step('setup-key','Look for the hanging Warden’s Key above either the Cafeteria/Showers approach or the Warden’s Office approach. Enter Afterlife, jump through the nearby blue doorway and shock the generator controlling its hook. Revive, then collect the lowered key. One pickup supplies the team’s key doors. While near Warden’s Office, use the ghost passage and shock its door meter to open it.','Lower the hanging key in Afterlife and collect it as a human.',{images:pics('wardens_key/key_cafeteria','wardens_key/key_ghostdoor_cafeteria','wardens_key/hanging_key','wardens_key/key_generator_wardens')}),
  step('setup-perks','Shock the small meter by each perk to activate it: Jugger-Nog at Docks, Electric Cherry by the upper Cell Block workbench, Speed Cola in Warden’s Office, Double Tap on the Citadel route and Deadshot in Infirmary. Power the gondola for travel between Cell Block and Docks. There is no Quick Revive machine; Afterlife is your recovery system.','Power perks individually; prioritize Docks Jugger-Nog and the gondola.'),
  step('setup-brutus','Brutus can lock perks, benches and the Box; pay the displayed unlock fee when safe. Remove his helmet with controlled headshots and keep moving while the screen shakes. Avoid reviving or buying while he is next to the interaction. Repeated Box use can bring him into the match, so keep a route out of its room.','Clear Brutus before shopping or reviving.')
 ],{group:'Key Features'}),
 phase('shield','Build the Zombie Shield',[
  step('shield-parts','Collect a trolley at Docks near the tank cage, stacked crates or watchtower base; a clamp in the Generator Room on either shelf or beside the MP5 generator; and a cell door on the Citadel spiral’s third level, outside Generator Room, or in the rigging corridor. Build at Docks, Cafeteria or behind Electric Cherry. Pick a bench on your normal route so replacements are nearby.','Find a Docks trolley, Generator Room clamp and Citadel cell door.',{images:set('zombie_shield/')}),
  step('shield-use','Wear the shield on your back for rear protection, or hold it to block the front. Check its condition regularly and replace it when broken. It does not prevent fall damage or make a trapped revive safe.','Replace the shield at its bench when it breaks.')
 ]),
 phase('plane','Five plane parts and Pack-a-Punch',[
  step('plane-roof','Use Afterlife in Infirmary, pass through the blue opening and jump up to the roof. Shock the roof-door meter so humans can reach the plane frame. Each player carries one plane part at a time in co-op; solo can collect the complete set. Add parts at the frame when convenient.','Open the roof door in Afterlife.',{images:pics('pap/roof_doorway','pap/roof_voltmeter','pap/plane_skeleton')}),
  step('plane-laundry','Uniforms: unlock the Showers gate with the key. Enter Afterlife, shock the washer’s meter, revive and start the laundry cycle. Survive the lockdown and take the clean uniforms when the machine finishes. The washer running is the cue to defend; shocking its meter alone is not the full step.','Power and run the Showers washer; survive and take the uniforms.',{images:pics('pap/laundry/showers_voltmeter','pap/laundry/laundry_machine','pap/laundry/finished_laundry')}),
  step('plane-rigging','Rigging: unlock the Citadel spiral’s number-panel cage. Enter Afterlife at the top and read the three glowing wall digits while descending in top-to-bottom order. Shock the panel to enter that match’s code. Revive immediately and run down to the rigging cage before its short opening window expires. If it closes, repeat the panel attempt.','Read the Afterlife staircase code, enter it and run for the opened rigging cage.',{images:pics('pap/rigging/afterlife_number','number_pad','pap/rigging/rigging_gate')}),
  step('plane-engines','Engine: in the Generator Room, shock all three generators in Afterlife. Two are in the physical room and the third is behind its ghost doorway. Each starts smoking; this disables the electrified gate in Warden’s Office. Revive, go there and unlock the gate with the key to collect the engine.','Shock all three Generator Room generators; collect the Office engine.',{images:pics('pap/engines/generator_citadel_tunnels','pap/engines/generator_behind_mp5','pap/engines/generator_ghostly_doorway','pap/engines/locked_gate_engines')}),
  step('plane-tanks','Oxygen tanks: at Docks, unlock the outer cage. In co-op, one player enters Afterlife and shocks the meter so the other can enter the small enclosure and collect the tanks; shock it again to reopen the exit before reviving. In solo, the key opens the required route without a second human operator. Do not leave a teammate trapped inside while your Afterlife expires.','Unlock the Docks cage; coordinate the two-player electrical gate.',{images:pics('pap/tanks/tanks_gate','pap/tanks/tanks_voltmeter','pap/tanks/tanks')}),
  step('plane-valve','Control valve: use the Warden’s Key on the cage in Infirmary near the roof stairs and pick it up. Fit all five parts to the roof frame. Gather the team and interact with the plane to fly to the Golden Gate Bridge.','Take the Infirmary valve and finish the roof plane.',{images:pics('pap/valves/valves')}),
  step('plane-bridge','Pack-a-Punch is on the bridge and costs 5,000. Survive the zombies and Brutus while upgrading. The electric chairs appear for the return trip; use them, then revive your bodies back in the prison. On later trips collect fuel cans from the five original part locations and refuel the plane. Wait for the next round if replacement fuel has not appeared.','Upgrade on the bridge; return by electric chair and refuel for later flights.',{images:pics('pap/pap_machine','pap/electric_chairs','pap/gas_cans')})
 ]),
 phase('retriever','Hell’s Retriever and the free Blundergat',[
  step('retriever-dogs','Wake and feed each red dog head with nearby zombie corpses: Cell Block beneath Electric Cherry, Infirmary near the roof stairs, and Docks beneath Jugger-Nog. Wait for each chewing animation before the next kill so the corpse counts. When all three heads disappear, claim Hell’s Retriever in the opened three-dog alcove on the Citadel/Showers route.','Feed the three dogs one corpse at a time, then claim the Retriever.',{images:pics('hells_retriever/dog_b23r','hells_retriever/dog_infirmary','hells_retriever/dog_docks','hells_retriever/hells_retriver_pickup')}),
  step('blundergat-skulls','Throw the Retriever at five invisible blue skulls. You can locate them while in Afterlife, then throw as a human: toilet in the spawn-side cell; electrical pole outside Warden’s Office; wooden dock post beyond the water-side fence; lamp above the Jugger-Nog/gondola area; and corner of the roof opposite the plane. Confirm the returning skull effect before moving to another. The photographs give the exact sightlines.','Retriever-collect all five hidden skulls.',{images:pics('blundergat/skull_toilet','blundergat/skull_wardens_office','blundergat/skull_dock','blundergat/skull_lamp','blundergat/skull_roof')}),
  step('blundergat-claim','When the five skulls are collected, take the free Blundergat from Warden’s desk. There is one free reward for the team. For the main quest, perform the skull collection even if someone obtained a Blundergat from the Mystery Box. The quest checks the secret, not merely whether you own the weapon.','Claim the desk Blundergat; the skull secret is required for the quest.',{images:pics('blundergat/blundergat_pickup')})
 ]),
 phase('acidgat','Acid Gat and Vitriolic Withering',[
  step('acid-parts','The motor is in Warden’s Office by the Uzi, Box or fireplace/Speed Cola. The case is in Cell Block on a desk near spawn, by the Cafeteria/Showers electrical box or beneath the Office stairs. The acid bottle is in Infirmary on a table by the bloody bath, floor corner of the bath room or trolley in the tiled hall. Assemble the kit at an unused bench.','Find Office motor, Cell Block case and Infirmary acid.',{images:set('blundergat/acidgat/')}),
  step('acid-upgrade','Hold the Blundergat and interact with the Acid Gat kit to convert it. Pack-a-Punch the Acid Gat on the bridge for Vitriolic Withering, whose projectiles attract zombies before exploding. Converting an already upgraded Sweeper also produces the upgraded acid version. Keep your own blast away from your feet.','Convert the Blundergat; upgrade to Vitriolic Withering on the bridge.')
 ]),
 phase('spoon','The spoon required by the main quest',[
  step('spoon-poster','After visiting the bridge at least once and obtaining the Retriever, remove the poster in the cell beside Warden’s Office with a Retriever throw. Enter Afterlife and pass through the newly visible doorway opposite the Office. Shock the spoon on the floor beside the crack until the laugh plays, then revive.','Remove the Office-cell poster; shock the spoon through its ghost passage.',{images:pics('spoon/poster','spoon/new_ghost_door','spoon/spoon_behind_poster')}),
  step('spoon-pickup','As a human, look through the back Cafeteria window beside the workbench and throw the Retriever at the spoon on the table. A voice cue confirms collection. The poster/shock stage is shared; each player wanting their own melee spoon collects this Cafeteria spoon. The ordinary spoon is sufficient for the main quest; the Golden Spork below is optional.','Retriever-collect the Cafeteria spoon.',{images:pics('spoon/spoon_window_cafe','spoon/spoon_pickup')})
 ]),
 phase('quest','Pop Goes the Weasel — three cycles, codes and recordings',[
  step('quest-ready','Play on Original with at least two players, one controlling Weasel. Complete the Retriever, five-skull free-Blundergat secret and spoon steps. Fly to the bridge and return via electric chairs three times in total, refuelling from the five part positions between trips. The rapidly cycling Citadel number panel confirms the quest code stage is available.','2–4 players including Weasel; three bridge cycles plus skull and spoon secrets.'),
  step('quest-codes','In Afterlife, enter 101, 872, 386 and 481 on the Citadel number panel, allowing each to be accepted before the next. These are the four prisoner numbers; their order is not a randomized puzzle. The panel shuffles after an accepted entry and Brutus speaks. Use another Afterlife charge if necessary; do not sacrifice your body trying to fit everything into one timer.','Enter prisoner numbers 101, 872, 386 and 481.',{images:pics('number_pad')}),
  step('quest-recordings','Listen to the narration, then collect five headphone/audio pickups in sequence: stairs out of the number-panel area, by Double Tap, walkway between Office and Cafeteria, stairs toward Infirmary, and stairs to the roof. Let each recording finish before looking for the next. The black-and-white effect and final laugh confirm the story sequence.','Follow the five recordings from Citadel to the roof.',{images:set('main_ee/headphones_')})
 ],{group:'Main Quest'}),
 phase('finale','The final flight and breaking the cycle',[
  step('finale-flight','Return to the completed plane after the last recording. Enter Afterlife and interact with it for the special final flight; all players travel in Afterlife. If boarding does not trigger, check that the last recording finished and all prerequisites were accepted. At the bridge, revive your physical bodies in the electric chairs.','Board the final plane in Afterlife; revive at the bridge chairs.',{images:pics('pap/plane_skeleton','pap/electric_chairs')}),
  step('finale-choice','Weasel becomes hostile to the other prisoners. To break the cycle and earn Pop Goes the Weasel, let Weasel kill the other players. If the others kill Weasel, the cycle continues. Both choices end the match. Agree the intended result before reviving so nobody accidentally chooses the other ending.','For the achievement, Weasel must kill the other prisoners; the match ends.')
 ])
],[
 phase('redeemer','Upgrade to Hell’s Redeemer',[
  step('redeemer-prison','On Original difficulty, earn fifteen kills with your Retriever in the prison and listen for the cue. Each player must do their own upgrade. Go to the bridge and, at round 10 or later, survive a complete round with the Retriever as your only source of kills. Ensure you personally kill with it and wait for the completion sound before using a chair.','Earn prison Retriever kills; complete a round 10+ bridge round using only it.'),
  step('redeemer-pit','Back at the prison, throw the Retriever into the lava pit beneath the first Cell Block dog. If accepted, it does not return. Finish the round. During the next round enter Afterlife and collect the blue Hell’s Redeemer from the original Retriever alcove, then revive. If it returns from the pit, your earlier requirement was not accepted; revisit the bridge trial.','Throw it into the Cell Block lava; next round claim the blue axe in Afterlife.',{images:pics('hells_retriever/hells_redeemer/lava_pit','hells_retriever/hells_redeemer/blue_glow')})
 ],{group:'Side Quests'}),
 phase('golden-spork','Golden Spork upgrade',[
  step('spork-bath','After obtaining your spoon, interact with the blood-filled bathtub in Infirmary’s Box room. The spoon stirs the blood. Use an Acid Gat or Vitriolic Withering to earn acid-explosion kills in Showers until the laugh confirms the charge; aim for roughly fifty, but use the cue because direct-projectile kills do not all count.','Stir the Infirmary bath; earn acid-explosion kills in Showers.',{images:pics('spoon/golden_spork/tub')}),
  step('spork-claim','Return to the same bathtub and interact. A hand raises the Golden Spork; interact again to collect it. Each player wanting the upgrade needs their spoon preparation. Its strong melee damage is a useful reward, not a required Pop Goes the Weasel step.','Interact twice at the bath to take the Golden Spork.',{images:pics('spoon/golden_spork/golden_spork')})
 ]),
 phase('music','Songs, Brutus code and the roof jumpscare',[
  step('music-bottles','For Rusty Cage, interact with the three whiskey bottles: Library shelf near Olympia, Docks corner by a crate/fence, and Infirmary bathroom table beside the wheelchair. For Where Are We Going, enter 935 at the Citadel panel in Afterlife. These are independent music interactions.','Three whiskey bottles play Rusty Cage; panel code 935 plays Where Are We Going.',{images:set('rusty_cage_song/')}),
  step('music-115','Enter 115 at the unlocked Citadel number panel in Afterlife for Brutus’s response and the display changing to 666. This is not one of the four prisoner numbers. In solo, letting the opening Afterlife expire without moving triggers another music variation and ends the attempt; keep that novelty separate from a serious run.','115 triggers Brutus’s panel secret; it is not a quest code.'),
  step('music-scare','For the optional jumpscare, use a scoped DSR-50 or Barrett on the roof. Face the rear of the plane and aim toward the distant fireworks off the left side. Expect a sudden face and loud sound. It has no equipment or quest reward.','Scope the distant fireworks from the roof for the optional jumpscare.',{images:pics('jumpscare/fireworks')})
 ])
],[reddit(m),illustrated(m),'https://mmmrkennedy.com/games/BO2/mob_of_the_dead/mob_of_the_dead_guide','https://steamcommunity.com/sharedfiles/filedetails/?id=748241987'])
