// Independent BO2 edition. Shared photographs depict the same Origins puzzle geometry.
import {phase,step,photos,reddit} from './chronicles-common.mjs'
import {guide as bo2Guide} from './bo2-common.mjs'
const guide=(map,name,intro,cover,phases,sidePhases,sources)=>bo2Guide(map,name,intro,phases,sidePhases,sources,{image:photos(map,cover)[0].src})
const m='origins'
const pics=(...ids)=>photos(m,...ids.map(id=>id.startsWith('origins-')?id:`origins-${id}`))
export const bo2OriginsGuide=guide(m,'Origins','Build and upgrade all four elemental staffs, prepare G-Strikes and the Maxis Drone, then free Samantha. This original Black Ops II guide works solo or with a team on Original and includes the shield, digging rewards, extra perk slots, free weapons and all three songs. The final interaction ends the match. This is separate from the Zombies Chronicles edition. Start useful preparation early: dig during snow, collect records while opening the map and fill soul chests just after a robot passes.','origins',[
 phase('setup','Generators, shovel, shield and gramophone',[
  step('setup-1','Activate all six generators by paying at the console and staying inside the capture area while fighting the Templar zombies. Their locations are Spawn (1), Tank Station (2), the other trench route (3), Jugger-Nog (4), Stamin-Up (5) and behind the Church (6). All six must be powered to use Pack-a-Punch at the top of Excavation. Retake generators when the Templar squad disables them.','Power all six generators for Pack-a-Punch.'),
  step('setup-2','Take a shovel from spawn before leaving; extras can appear in the elemental tunnels and Church. Build the shield from one part in each region: the Generator 2/Tank Station route, the Generator 3/Fire Tunnel route, and the three middle robot footprints around Excavation/Generator 4. Each part has three possible spots shown in the reference. Assemble at the Wind Tunnel, Lightning Tunnel or Church workbench.','Take a shovel and collect the three shield parts.',{images:photos(m,'shield-locations')}),
  step('setup-3','Pick up the gramophone beside the table inside Excavation. Find the black record around the mound: by the engine at the ramp, on the Church-facing low wall, or in the wheelbarrow by Pack-a-Punch. Place the gramophone on the Excavation table to open the spiral staircase, then retrieve it.','Use the black record and gramophone to open the lower Excavation.',{images:pics('gramophone-spawn','black-disc-engine-spawn','black-disc-wall-spawn','black-disc-wheelbarrow-spawn')}),
  step('setup-4','Every staff needs three physical pieces, its coloured record and its crystal from the Crazy Place. Carry the gramophone to that element’s tunnel table to open its portal, take the matching crystal, return through the portal and retrieve the gramophone. Wind is by Generator 4, Lightning by Generator 5, Ice behind Church/Generator 6, Fire between Spawn and Generator 3.','Use each coloured record at its matching tunnel.',{images:pics('wind-tunnel','lightning-tunnel','ice-tunnel','fire-tunnel')})
 ],{group:'Key Features'}),
 phase('staff-build','Build the four staffs',[
  step('staff-build-1','Ice: dig ordinary bone piles while it is snowing. Find one piece in the Spawn/Generators 2–3 region, one in the middle/Generators 4–5 region and one at Church/Generator 6. Snow controls whether parts can drop; glowing red dig sites are a different perk secret. The blue record is inside Tank Station: front table, shelf near the Box, or shelf by the back entrance. Take its crystal through the Ice Tunnel.','Ice: three snowy dig regions, blue Tank Station record, Ice crystal.',{images:pics('gen-2-and-3-ice-staff-part','gen-4-and-5-ice-staff-part','church-and-gen-6-ice-staff-part','ice-disc-table-near-entrnace','ice-disc-near-mystery-box','ice-disc-near-back-exit')}),
  step('staff-build-2','Fire: collect the Generator 6 reward-chest piece, kill the first Panzer Soldat (normally round 8) for its piece, and shoot down the glowing plane with a bullet weapon. Pick the plane’s piece up between the middle footprints below Excavation. The red record can be on the upstairs Church pews, boxes by Generator 6 or boxes between the tank and stairs. Use the Fire Tunnel for its crystal.','Fire: Generator 6, first Panzer, glowing plane; red record and Fire crystal.',{images:pics('fire-staff-gen-6-part','fire-staff-panzer-part','fire-staff-glowing-plane','fire-staff-part-between-gen-4-and-excavation','fire-disc-benches-spawn','fire-disc-gen-6-spawn','fire-disc-tank-spawn')}),
  step('staff-build-3','Wind: each of the three giant robots contains one piece. Thor walks at Spawn, Odin through the middle, Freya by Church. Shoot the yellow-lit underside of an approaching foot with a bullet weapon, then let that opened foot step on you to enter the head. An unlit foot will crush you. Collect the piece before being ejected. Find the yellow record at Generator 5 (Stamin-Up wall, boxes outside Lightning Tunnel, or its entrance table) and collect the Wind crystal at Generator 4.','Wind: enter all three robots; yellow Generator 5 record and Wind crystal.',{images:pics('giant-yellow-light','wind-staff-part','wind-disc-stamin-up-spawn','wind-disc-boxes-spawn','wind-disc-lightning-tunnel-spawn')}),
  step('staff-build-4','Lightning: ride the tank from Church toward Tank Station. Jump right onto the raised wooden steps near Generator 3 for the first part. On the return journey, jump left onto the Excavation scaffolding near Generator 5 for the second, and right onto the Church approach for the third. Plan separate rides if needed. The purple record is by Generator 4 (cart, table near Wunderfizz or the end of Wind Tunnel); use it at Lightning Tunnel.','Lightning: three tank jumps, purple Generator 4 record, Lightning crystal.',{images:pics('lightning-part-1-jump','lightning-part-1','lightning-part-2-jump','lightning-part-2','lightning-part-3-jump','lightning-part-3','lightning-disc-chariot-spawn','lightning-disc-table-spawn','lightning-disc-tunnel-spawn')}),
  step('staff-build-5','With an element’s three pieces and crystal collected, use its pedestal at the bottom of Excavation to build that staff. Repeat for all four; a solo player can swap between staffs there. Building is only the first stage—each still needs its own elemental trial and the common charging step.','Assemble all four staffs at their Excavation pedestals.',{images:pics('hall-of-the-ancients')})
 ]),
 phase('upgrades','Complete the four elemental trials',[
  step('upgrades-1','Ice: in the Crazy Place, read the blue tablet beside the Ice portal, then shoot the matching overhead rune with the Ice Staff. Use the photographed matcher below for each new tablet until the puzzle finishes. Back outside, freeze each of three tombstones with the staff, then shatter it with a bullet weapon: by Excavation’s footprint, near Generator 4, and outside Generator 2 by the fallen robot.','Ice: match the tablet, then freeze and shatter three tombstones.',{images:pics('ice-symbol-tile','ice-floating-tiles','ice-tombstone-near-excavation','ice-tombstone-near-gen-4','ice-tombstone-near-gen-2')}),
  step('upgrades-2','Fire: kill zombies with the Fire Staff while they are over the metal grates in the Crazy Place’s Fire area. Continue until all four cauldrons burn. Upstairs at Church, read the glowing dot patterns; select them in the decoder below. Downstairs, shoot the four corresponding torches quickly with the staff. They need to burn together; their order does not matter. The blood-marked torch represents 4.','Fire: light four cauldrons, decode Church symbols, ignite four torches.',{images:pics('fire-jars','fire-puzzle')}),
  step('upgrades-3','Wind: shoot the four ceiling rings above the Wind portal until their symbols match the pictured solution. Align your viewing position with the reference before comparing the row. Outside, shoot the three smoking stone chimneys with Wind so their smoke blows toward Excavation: near Generator 4, outside the Stamin-Up window and beside the tank’s return path toward Church. Listen for the completion cue.','Wind: match the ceiling rings; blow three chimneys toward Excavation.',{images:pics('wind-puzzle','wind-chimney-near-gen-4','wind-chimney-near-gen-5','wind-chimney-near-tank-path')}),
  step('upgrades-4','Lightning: number only the lower purple keyboard triangles 1–7 from left to right. Shoot 1–3–6, wait until the sparks clear; shoot 3–5–7, wait; shoot 2–4–6. Then set the long handle of each of the seven outside electrical dials to the position listed below. A dial that still sparks is not finished. These positions can be prepared before the keyboard step.','Lightning: play 136 / 357 / 246; set all seven electrical dials.',{images:pics('lightning-puzzle','lightning-panel','lightning-dials'),bullets:['Generator 5, opposite Stamin-Up: long handle down.','Church downstairs, behind the tank: right.','Church upstairs, by the window: up.','Right of Wind Tunnel entrance: up.','Spawn by the stairs: left.','Tank Station back door: down.','Behind Excavation, near the Church steps: up.']}),
  step('upgrades-5','After an element’s trial, use the four levers under Excavation to make all four ring lights its colour: Ice blue, Fire red, Wind yellow, Lightning purple. Shoot the matching coloured orb below the rings with that staff. Put the staff into its Crazy Place pedestal and kill nearby zombies until it stops collecting souls and can be taken as the upgraded version. Repeat for every staff.','For each staff: align rings, shoot orb, charge in the Crazy Place.',{images:pics('underground-levers','colored-ball','staff-podium')})
 ],{tools:['bo2-origins-ice','bo2-origins-fire']}),
 phase('equipment','Thunder Fists, G-Strikes and the Maxis Drone',[
  step('equipment-1','Fill the four soul chests inside robot footprints: near Generator 4, near Generator 5, beside Excavation and on the Church approach. Kill zombies inside each footprint until its chest disappears. A robot stepping on an unfinished chest resets that chest’s souls, so start just after it passes. Claim One Inch Punch/Thunder Fists from the reward chest at Spawn or Generator 6.','Fill four footprint chests and collect Thunder Fists.',{images:pics('gen-4-soul-chest','gen-5-soul-chest','excavation-site-soul-chest','church-soul-chest')}),
  step('equipment-2','Take a stone tablet from the Tank Station table and put it in the upstairs Church basin. Earn nearby melee kills until the tablet is clean and the soul effect stops. Take it back to Tank Station without touching mud: follow the boards out of Church, around Excavation and through the Workshop to Generator 2. If it becomes dirty, wash it in the basin again and retry the walk.','Clean a tablet with melee kills, then carry it back without mud.',{images:pics('stone-tablet-table','stone-tablet-basin')}),
  step('equipment-3','Replace the clean tablet on the Tank Station table and earn another set of nearby melee kills. Pick up the glowing G-Strikes. This reward is per player; at least the player throwing at the seal needs them. Build the Maxis Drone from its three parts listed next before starting Rain Fire.','Finish the tablet kills for G-Strikes and build the drone.',{images:pics('g-strikes')}),
  step('equipment-drone','Collect Maxis’s brain from the spawn table. Find a rotor at Excavation: near Pack-a-Punch, beside the gramophone area or on the lower wooden platform by a lantern. Find its frame along either muddy Church tank path or at the bottom of Ice Tunnel. Assemble at a workbench; collect it when ready to use.','Collect the brain, rotor and frame; assemble the Maxis Drone.',{images:pics('maxis-drone-brain','maxis-drone-rotor-first-spawn','maxis-drone-rotor-second-spawn','maxis-drone-rotor-final-spawn','maxis-drone-frame-first-spawn','maxis-drone-frame-second-spawn','maxis-drone-frame-final-spawn')})
 ]),
 phase('seal','Robot pedestals, Rain Fire and the Panzer wave',[
  step('seal-1','With all four staffs upgraded and all six generators active, put each into its quest pedestal: Ice in Freya (Church robot), Wind in Odin (middle), Lightning in Thor (Spawn), Fire in the new pedestal below Excavation. Use the lit-foot entry method. Once all are accepted, the staffs return to their original Excavation holders. This is the standard placement method; it does not require the BO2 repeated-Fire-Staff shortcut.','Place Ice/Freya, Wind/Odin, Lightning/Thor, Fire/Excavation.',{images:pics('ice-staff-pedestal','wind-staff-pedestal','lightning-staff-pedestal','fire-staff-pedestal')}),
  step('seal-2','Retrieve a staff. Press the red button inside a robot head, then land a G-Strike on the stone seal outside Generator 5 within the brief window. In co-op, put the thrower at the seal before a teammate presses. Solo, enter Odin’s foot nearest the Generator 5 exit; wait until the ejection countdown is nearly finished, press the button and immediately run to throw. A correctly hit, opened seal confirms success; otherwise repeat the button and throw.','Press the robot button and quickly G-Strike the Generator 5 seal.',{images:pics('alarm-button','rain-fire-seal')}),
  step('seal-3','Release the Maxis Drone beside the opened seal. It flies inside and releases the Panzer wave. Keep space to dodge claws/flamethrowers and destroy the entire wave with upgraded weapons before continuing.','Send the drone into the opened seal and defeat the Panzers.')
 ],{group:'Main Quest'}),
 phase('finale','The hidden pilot, Iron Fists and the Crazy Place',[
  step('finale-1','While Zombie Blood is active, look up and shoot the newly glowing plane. Find its otherwise-invisible pilot running clockwise around Excavation; running counter-clockwise helps intercept him. Kill him while Zombie Blood is active and collect the Maxis Drone he drops. You can use another Zombie Blood if the first expires.','In Zombie Blood, down the plane and kill its pilot; recover the drone.',{images:pics('pilot-maxis-drone')}),
  step('finale-2','Return below Excavation with Thunder Fists already claimed. Melee the special Templar zombies with mist around their fists until your reward tablet drops; collect it to upgrade your fists. Each player must earn and collect their own tablet. Staff melee can help, but every player still needs One Inch Punch.','Every player earns and collects an Iron Fist tablet.',{images:pics('mist-templar-zombie','stone-tablet-power-up')}),
  step('finale-3','Place all four upgraded staffs into their Crazy Place pedestals. Kill roughly 100 zombies in the centre until the screen flashes and the overhead rift opens. You can retrieve the staffs afterwards. To trigger the ending, deploy the recovered Maxis Drone in the centre, then have everyone stand on the central blue circle and interact. This last interaction ends the match.','Charge the rift; deploy the drone; interact together to end the match.',{images:pics('raise-hell','freedom')})
 ])
],[
 phase('digging','Golden Shovel, Golden Helmet and extra perk slots',[
  step('dig-shovel','Keep digging ordinary bone piles with your shovel. After enough digs it becomes gold; use the gold icon/appearance as confirmation rather than assuming an exact count. Continue digging for the random Golden Helmet drop. The helmet protects against giant-robot stomps; it is not required for normal lit-foot entry.','Dig until the shovel turns gold; continue for the helmet.'),
  step('dig-slots','With the Golden Shovel, collect Zombie Blood and search the sixteen marked positions for a glowing red dig pile. Dig the active pile for an empty perk bottle: it grants an extra purchase slot, not a free perk. Buy the extra perk afterwards. Repeat with fresh Zombie Blood to find further bottles. Only the active location appears, so search another region if a marked spot is empty.','Search the sixteen red dig spots during Zombie Blood.',{images:photos(m,'red-dig-map')})
 ],{group:'Side Quests'}),
 phase('free-blood','Create a Zombie Blood drop',[
  step('blood-carts','Shoot three burning carts around Excavation with the Ice Staff to extinguish them: opposite the weapon wall on the Workshop approach, in the footprint toward Generator 4 and on the left path toward Generator 5. A Zombie Blood appears beside Pack-a-Punch; collect it promptly. This is available once per round when the carts are burning, and rain can delay their relighting.','Extinguish the three carts and collect Zombie Blood at Pack-a-Punch.',{images:pics('flaming-chariot-opposite-mp40','flaming-chariot-near-gen-4','flaming-chariot-near-stamin-up')})
 ]),
 phase('rewards','Challenge chests and free Magna Collider',[
  step('rewards-challenges','Check the tablets at the Spawn or Generator 6 reward chest. Claim each completed reward there: 115 ordinary-zombie headshots gives an upgraded rifle; personal participation in six generator captures gives Max Ammo; spending 30,000 points gives Double Tap; all four soul chests give Thunder Fists. A teammate capturing a generator without you does not count as your participation.','Claim headshot, generator, spending and soul-chest rewards.'),
  step('rewards-drone','Deploy the Maxis Drone near each of four yellow discs and aim toward it so the drone collects it: Church roof above the tank exit, Excavation scaffolding facing Generator 5, the Generator 5 roof/plank, and burning debris on the Spawn-to-Generator 2 route. Let the drone recharge as needed. After all four, take the free Pack-a-Punched MG08/15 (Magna Collider) in front of Pack-a-Punch.','Use the drone to collect four discs for a free upgraded MG08.',{images:photos(m,'drone-discs')})
 ]),
 phase('music','Three songs and the Church jumpscare',[
  step('origins-archangel','For Archangel, interact with three green rocks: beside the spawn reward chest/bunk bed, under a bed upstairs in the Workshop, and on Excavation’s outer wooden scaffolding near a crate on the Spawn-facing side.','Activate the three green Archangel rocks.'),
  step('origins-shepherd','For Shepherd of Fire, interact with three small red radios: inside Freya’s head opposite the audio log, on the inner Excavation scaffold, and at the edge of the Fire area in the Crazy Place.','Activate the Freya, Excavation and Crazy Place radios.'),
  step('origins-aether','With the relevant generators powered, go prone and interact with the two separate “1” floor panels at Generator 1, then the “5” panel at Generator 5. The 1–1–5 sequence starts Aether.','Prone-interact with 1, 1, then 5.'),
  step('origins-jumpscare','For the optional jumpscare, take a scoped sniper to the top of Excavation and keep aiming at the fire on the Church tower. Expect a sudden image and loud sound in the scope; it has no quest reward.','Scope the burning Church tower from Excavation.')
 ])
],[reddit(m),'https://www.codzombiesguides.com/main-quests/black-ops-2/origins/','https://www.glitchingqueen.com/origins.html'])
