import {guide,phase,step,photos,reddit,illustrated,joker} from './bo2-common.mjs'
const pics=(...ids)=>photos('buried',...ids)
export const buriedGuide=guide('buried','Buried','Free Arthur, set up the underground town and cross the mansion to Pack-a-Punch. Mined Games has separate Richtofen and Maxis routes; plan a four-player Original-difficulty match for either complete route. The guide includes the mine cipher, both wisps, Round Infinity, bells, sharpshooter, free perks, Arthur’s jobs and the three-map endgame.',[
 phase('setup','Arthur, weapon chalk and the town',[
  step('setup-drop','Before dropping from the starting processing platform, decide whether to save 2,000 points for the LSAT above spawn. Jump and climb onto its short ledge to buy it before the platform gives way. Once below, take Quick Revive if playing solo, use the tunnels to reach town and look for the jail beside the initial Mystery Box. The LSAT is optional; falling into town does not block the quest.','Decide on the starting LSAT, then drop into town.'),
  step('setup-arthur','Enter the jail from above and take the key on the wall to open Arthur’s cell. Give him the bottle of booze from inside. He charges away from the player who hands it over, so position his back toward the barrier you want broken. Free the Jugger-Nog alley and the approach to the mansion early. If you shoot him, he retreats to his cell; search the jail, courthouse judge’s bench, upstairs saloon or bank for the key to release him again.','Free Arthur; stand opposite a barrier before giving him booze.'),
  step('setup-chalk','Take a chalk weapon outline from the gunsmith and draw it at a question-mark wall. Each placement awards points, with a larger reward for the last one. Put a weapon you can refill on a route you actually use, such as the AN-94 near the main street. Chalk, booze and candy share a carried-item slot; finish a delivery before collecting another item.','Move gunsmith chalk to question marks for weapons and setup points.'),
  step('setup-perks','There is no central power switch. Jugger-Nog is at the end of the blocked alley by the jail; Speed Cola is upstairs in General Store; Mule Kick is upstairs in the gunsmith; Stamin-Up is in the courthouse; Double Tap is at the mansion entrance; Vulture Aid is in Church; Quick Revive is near the starting drop. Vulture Aid highlights useful objects and creates occasional ammunition/point drops and green hiding clouds.','Open Jugger-Nog and Church; use Vulture Aid for the Richtofen wisp.')
 ],{group:'Key Features'}),
 phase('pack-a-punch','Mansion, maze and Pack-a-Punch',[
  step('pap-mansion','Have Arthur break the mansion barrier, then enter with a loaded weapon. Ghost women take 2,000 points per hit, so move together, check behind you and kill them before contact. Follow the entry rooms through the moving bookcase, upstairs and out the rear into the maze. Do not stop at the entrance to fight an endless flow while teammates remain in the house.','Cross the mansion without letting ghosts touch you.'),
  step('pap-maze','Navigate the hedge maze from the mansion’s rear to the gazebo, checking the metal gates for the current route. Its configuration can change between rounds. At the gazebo, descend the spiral stairway for Pack-a-Punch and pay 5,000 points. Stop on each stair segment: there are gaps that can kill you if you rush or backpedal. Keep a teammate watching the approach while a weapon is inside the machine.','Find the gazebo; descend carefully and upgrade for 5,000.',{images:pics('maze')}),
  step('pap-return','For a shortcut back to the surface starting area, first have Arthur smash the town fountain and destroy the maze fountain with explosives. Only jump into the maze fountain when the portal is visibly active. An unprepared fountain is a lethal hole. The return route lets you revisit upper processing; it does not give a second chance at the collapsed LSAT ledge.','Prepare both fountains before using the maze’s return portal.',{images:pics('fountain')})
 ]),
 phase('equipment','Buildables, Paralyzer and Time Bomb',[
  step('store-parts','Use the General Store’s ground floor and upstairs landing to collect the trap parts. Deliver each piece before picking up another; a character can carry only one buildable part. If you want Arthur to help, install the first piece of the desired device at the chosen bench before giving him candy there.','Search both General Store floors and carry one part at a time.',{bullets:['Turbine: tail fin on the ground-floor corner bookshelf; mannequin in the back-room corner; fan on an upstairs shelf.','Resonator: roulette wheel/speaker by the weapon-locker counter; turntable on the ground floor near the locker; wooden base at the rear passage; motor at the top of the stairs.','Head Chopper: crank on the centre shelf; hinge on the front counter’s right; saw in the barrel behind the counter’s left; stand in the rear room.','Trample Steam: collect the mesh screen, motor, bellows and flag from the General Store; its workbench does not supply parts from Die Rise.'] }),
  step('buildables','All ordinary buildable parts are in the General Store. Carry one at a time to a bench in the courthouse, saloon, upstairs building beside the jail or Church. Turbine: mannequin, fan and tail; Trample Steam: mesh, flag, compressor and bellows; Head Chopper: saw, crank, hinge and stand; Subsurface Resonator: roulette wheel/speaker, turntable, wooden mount and motor. Decide the first item at a bench before adding an incompatible part.','Use General Store parts at the town’s four benches.'),
  step('resonator','A Subsurface Resonator fires only while a Turbine powers it; face its dish at the target and keep the Turbine nearby. Maxis needs this pair to destroy the four crystal orbs. A Trample Steam offers roof access without needing the Paralyzer. Replace broken equipment at its original bench.','Power the Resonator with a Turbine; face it toward the orb or horde.'),
  step('paralyzer','The Paralyzer and Time Bomb come from the Mystery Box. The Paralyzer has a heat meter instead of ammunition; let it cool when near its limit. Aim at the ground while jumping to lift yourself, then feather the beam on descent to avoid falling damage. Pack-a-Punch turns it into the slower-heating Petrifier. The Time Bomb records the match at placement and rewinds when triggered; tell your team before using it because it can undo purchases and positions.','Roll for quest equipment; coordinate every Time Bomb rewind.')
 ]),
 phase('choose-route','Mined Games — choose a route and charge the lantern',[
  step('quest-requirements','Use four players and Original difficulty. Richtofen requires a Paralyzer, Vulture Aid, Time Bomb and Bowie Knife or Galvaknuckles. Maxis requires a Turbine/Resonator pair, Time Bomb and Bowie Knife or Galvaknuckles; the Paralyzer is useful for travel but is not his orb weapon. Choose your structure before building: the two branches share the wire and antenna.','Choose Richtofen’s Guillotine or Maxis’s Gallows before spending shared parts.'),
  step('quest-structure','Richtofen: build the Guillotine beside the saloon using the dish on its upstairs balcony, wire spool downstairs in the gunsmith, crystal in the upper tunnels near Lunger Undermines and antenna in the barn’s lower stable. Maxis: build the Gallows near the courthouse with that wire and antenna, the bulb above the jail and the battery behind Church’s pulpit.','Build the chosen branch structure from its four parts.',{images:pics('satellite-dish-top-balcony-of-saloon','spool-of-wire-corner-of-the-gunsmith','crystal-near-lunger-undermines','antennae-bottom-of-the-barn-in-a-far-stable-on-the-right','bulbs-above-jail-cell','battery-behind-chruch-podium')}),
  step('quest-orbs','Find the four red orbs: saloon/candy-store alley, rock left of Church, upper tunnels near Lunger Undermines, and foliage at the mansion’s rear maze entrance. For Richtofen, hold the Paralyzer on each until it turns white and chimes. For Maxis, destroy each with a Turbine-powered Subsurface Resonator. Confirm all four before looking for the lantern.','Richtofen: whiten all orbs with Paralyzer. Maxis: destroy them with Resonator.',{images:pics('orb-between-candy-store-and-saloon','orb-graveyard-left-of-church','orb-near-lunger-undermines','orb-behind-the-witches-mansion')}),
  step('quest-lantern','After the dialogue, knock down the floating purple lantern with a cooked grenade or explosive and collect it. Richtofen: its carrier kills ghost women in the mansion until the charge cue. Maxis: keep the carrier near zombies killed by Arthur, traps or a Nuke until charged; ordinary gun kills do not substitute. Let Maxis finish speaking before picking it up. If downed, recover the lantern where you lost it.','Knock down the lantern; charge it using the method for your chosen voice.',{images:pics('glowing-lantern')}),
  step('quest-roof','Reach the gunsmith roof by Paralyzer, Trample Steam or the connected roof route and place the charged lantern on its chalk mark. Three encoded lines appear on the wall. The following sign helper applies to both branches; the wisp behavior afterwards is different.','Place the charged lantern on the gunsmith roof.',{images:pics('lantern-symbol-atop-the-gunsmith-roof')})
 ],{group:'Main Quest'}),
 phase('cipher','Read the three mine signs',[
  step('cipher-read','Each wall line names one mine sign. Match its first two shapes in the helper, preserving both the white outline and which side contains the red stroke. Confirm against the full pictured line if two corners look alike. The five names are Dry Gulcher Shaft, Bone Orchard Vein, Lunger Undermines, Ground Biter Pits and Consumption Cross. You need three distinct names, not every sign.','Match three encoded lines to three distinct mine signs.',{images:pics('cipher-key')}),
  step('cipher-melee','Find the named wooden signs along the upper mine tunnels and strike only those three with the Bowie Knife or Galvaknuckles. There is no universal wall-line strike order; the last sign struck determines where the wisp begins. Before the final hit, position the team for the correct branch below. For Maxis, place your Time Bomb first.','Melee the three decoded signs; prepare the wisp route before the final hit.')
 ],{tools:['bo2-buried-signs']}),
 phase('richtofen-wisp','Richtofen — wisp and Round Infinity',[
  step('richtofen-wisp','A player with Vulture Aid must touch the newly spawned wisp and follow its hops toward the Guillotine. Look along the barn upper floor, jail upper floor, General Store upper floor and candy store as it moves. A roughly fifteen-second gap without contact makes it disappear; hit the same three signs again to restart. Other players should hold zombies away from the runner.','With Vulture Aid, touch every wisp hop quickly until it reaches the Guillotine.',{images:pics('richtofen-wisp')}),
  step('richtofen-souls','At the Guillotine, let the wisp enter nearby zombies, then kill those glowing zombies near the structure one at a time. Continue until Richtofen requests the Time Bomb. Normal zombies killed before receiving the glow do not count.','Kill five wisp-charged zombies by the Guillotine.',{images:pics('glowing-zombie')}),
  step('richtofen-infinity','Put a Time Bomb on the Guillotine bench. Gather all four players around it and detonate to enter Round Infinity. Zombies are invulnerable here; avoid fighting and split the search for four fallen crew bodies. Interact with each body to find the switch. Search the main streets around the saloon/Guillotine, gunsmith and barn gap, jail, General Store/Box, candy-store entrance and arrow sign, Church rock/workbench and mansion barrier.','Rewind at the Guillotine with all four players; search bodies for the switch.',{note:'The search window is brief. Sources disagree on its exact duration, so follow the in-game transition and do not rely on a web timer.'}),
  step('richtofen-switch','After the game automatically returns to your original round, fit the recovered switch to the Guillotine. If you ran out of time without finding it, obtain another Time Bomb and repeat the search. Protect the carrier until the part is installed. Now continue to the maze levers.','Return from Round Infinity and install the switch.')
 ]),
 phase('levers','Richtofen — solve the maze lever order',[
  step('lever-test','Locate the red, green, blue and yellow levers on the maze gates. Flip each once in a chosen order, then inspect all four: feedback appears after the fourth lever. A spark means that colour was in its correct position in the sequence. A non-sparking lever was in the wrong position. Record both observations in the helper after every complete attempt.','Flip all four, then record which levers sparked.',{images:pics('maze')}),
  step('lever-repeat','Everyone must leave the maze to reset the levers after an unsuccessful attempt. Return and try the helper’s suggested order; the helper retains positions proved right and eliminates positions proved wrong. If it reports no possible order, correct the recorded attempt or spark feedback rather than forcing another guess. Candy jar colours are not a reliable solution.','Leave together to reset; use spark feedback to narrow the next order.'),
  step('lever-finish','All four levers sparkling in the same attempt completes this branch. Continue to the shared sharpshooter finale. You do not need the Maxis bell step.','All four sparks: move to the fountain finale.')
 ],{tools:['bo2-buried-levers']}),
 phase('maxis-wisp','Maxis — escort the wisp twice',[
  step('maxis-prep','Place a Time Bomb before hitting the final decoded sign. Leave enough live zombies positioned along the wisp’s path: it must pass near them to stay alive. Its path depends on the last sign hit. If Consumption Cross is in your set, hit it last for a route via the barn and saloon; put at least two zombies upstairs in the barn and three in front of the saloon before starting.','Place a Time Bomb and prepare live zombies before spawning the wisp.'),
  step('maxis-escort','Follow the orange wisp to the Gallows, keeping zombies close enough for it to draw energy. Do not clear the entire route with weapons. If it fades, strike your sign set again and reposition the zombies. Once it reaches the Gallows, detonate the previously placed Time Bomb. Hit the signs again as needed to respawn it, then escort it successfully a second time. Maxis’s next instruction confirms acceptance.','Feed the wisp live zombies, deliver it, rewind, then deliver it again.',{images:pics('maxis-wisp')})
 ]),
 phase('bells','Maxis — the mansion’s nine-light bell puzzle',[
  step('bells-calibrate','Put one player at the switchboard on the mansion couch beyond the moving bookcase. Put the other three at the upstairs candy-store bells, upstairs barn bells and downstairs courthouse bells. Facing the board, its columns are Candy Store, Barn, Courthouse from left to right. Before activating the sequence, ring each bell and let the board player report which row lights. Save those observed correspondences in the helper.','Test each bell and map it to a row in its board column.',{images:pics('switchboard')}),
  step('bells-locations','Candy Store: square table by the wall, table with two pots by the couch barrier, and chair beside the stair doorway. Barn: hay bale by the wall opening, hay bale by the railing gap, and hay bale near the drop toward jail. Courthouse: corner just inside the entrance, judge’s bench, and table to the right of the bench. These landmark names are the helper’s callouts.','Locate three bells in each of the three rooms.'),
  step('bells-play','When everyone is ready, the mansion player interacts with the board. Select the currently lit bulb in the helper and call its displayed room and landmark; the assigned teammate rings that bell immediately. Continue following the live board until the bulbs are green and it shuts off. A wrong bell or slow response resets the sequence; restart at the board using the same tested mapping.','Follow the live bulb one at a time; ring its mapped bell before the timeout.',{note:'The helper does not run the game timer or invent a sequence. Test the mapping before starting the timed puzzle.'})
 ],{tools:['bo2-buried-bells']}),
 phase('sharpshooter','Both routes — Make a Wish and shoot the targets',[
  step('targets-prep','Have Arthur break the fountain outside the mansion if it is still covered. Assign one player to each target area: candy store/courthouse street, mansion windows, saloon interior and jail street. Use a full magazine, fast reload and a weapon whose shots you can place accurately. Walk the lanes together before triggering the challenge.','Assign the four lanes and reload before touching the fountain.',{images:pics('fountain','cowboy-target')}),
  step('targets-fire','Interact with the fountain to Make a Wish. Shoot every cowboy target in your lane before it disappears; they arrive in waves, so keep sweeping the entire view. One missed target anywhere fails the attempt. Practice the missed lane, reload and trigger the fountain again. All perks and the quest completion cue confirm success. Optional three-map activation below is separate from Mined Games.','Shoot every target; retry the whole challenge if any lane misses.')
 ])
],[
 phase('arthur','Arthur’s candy jobs and the bank',[
  step('arthur-candy','Free candy appears in the candy shop each round; extra candy or booze costs 1,000 at the appropriate shop counter. Give candy near a crawler so Arthur carries it while you solve puzzles. Do not hit him while he holds it. At a workbench, candy makes him gather parts and finish a buildable; place one desired part first to choose what he builds.','Use candy for crawler holding and building assistance.'),
  step('arthur-box','Candy by an idle Mystery Box makes Arthur lock it at that location; candy while a rolled weapon is still offered rerolls it; candy at an empty Box spawn can make him fetch it. A locked Box cannot be moved this way. Candy near a power-up changes the drop. Keep these jobs distinct from giving candy with no nearby object, which sends him after zombies.','Use the right nearby object to select Arthur’s Box or power-up job.'),
  step('bank','Deposit/withdraw with the bank keys and use the General Store weapon locker to share eligible saved equipment with TranZit and Die Rise on supported profiles. Withdrawals cost a fee. Avoid activating a casual Time Bomb while teammates spend saved funds; agree on the rewind before purchases.','Coordinate bank spending and Time Bomb rewinds.')
 ],{group:'Side Quests'}),
 phase('free-perks','Ghost rewards, double bottles and the piano',[
  step('perks-mansion','When the mansion’s lights are on, cross it, get everyone out and kill the pursuing ghosts. The last ghost drops a team perk bottle. The reward recharges after several rounds; lights are the practical availability cue. A dark-house trip still risks losing points without granting another bottle.','Cross while the house is lit and finish the ghost wave for a perk.'),
  step('perks-bomb','For the Time Bomb double-bottle trick, place a bomb before killing the final reward ghost. Kill her but leave the bottle on the ground, then rewind. Collect the retained bottle and kill the restored final ghost for the second drop. Coordinate before anyone picks up the first bottle; taking it before the rewind spoils this method.','Bomb before the final ghost; leave its bottle, rewind, then claim both.'),
  step('perks-piano','Obtain the Ballistic Knife from the Box. Stand behind the white floor line in the saloon and fire a blade into the dartboard bullseye. The saloon piano starts playing. Travel through the mansion to the maze, then promptly re-enter from the rear to find a ghost playing the piano. Interact and pay 10 points for a random perk. This is separate from the nine-bell Maxis puzzle.','Ballistic-Knife the saloon bullseye; re-enter the mansion from the maze and tip the pianist.')
 ]),
 phase('persistent','Hidden PhD and sniper point bonuses',[
  step('persistent-phd','Buried’s persistent PhD is earned by repeatedly taking survivable fall damage. Use a short ledge near the jail stairs and recover fully between falls until the green flash. Once acquired, dolphin-diving from a height creates an explosion and protects that dive; an ordinary fall that deals damage removes it. It is a hidden bonus, not a purchasable machine, and belongs to supported persistent-profile modes.','Take small, survivable falls for the green flash; use dolphin dives afterwards.'),
  step('persistent-sniper','Long-range sniper kills can award a green-flash bonus that adds points to later sniper kills. The SVU-AS is convenient for earning money while keeping a refillable weapon. Maintain accuracy: repeated missed shots can remove the bonus. Persistent upgrades can carry between supported TranZit, Die Rise and Buried matches, but are not available in Borough.','Earn accurate long-range sniper kills for bonus points; avoid repeated misses.',{links:[{href:'https://www.reddit.com/r/CODZombies/comments/1i19a7/official_permapersistent_perks_thread/',label:'Community persistent-upgrade research and loss conditions'}]})
 ]),
 phase('music','Always Running and the saloon piano',[
  step('music-bears','Interact with three teddy bears: beside Quick Revive after the initial drop, inside a barrel in the candy shop, and beside the bookcase in the mansion’s Double Tap entry room. The third starts Always Running. Use a loaded weapon before entering the house to reach its bear.','Activate the Quick Revive, candy barrel and mansion bears.'),
  step('music-piano','After the dartboard/piano secret, interact with the saloon piano to play it. The mansion also contains a Michael Faraday portrait, and books throughout town reference other works. These are optional environmental details, separate from Mined Games.','Play the saloon piano after the dartboard secret and explore the story details.')
 ]),
 phase('endgame','Navcards and the optional Victis endgame',[
  step('endgame-nav','Build Buried’s Navcard table back at upper Processing. Take the board, radio and electrical box from the passage beside the barn, carrying each through the mansion and prepared maze-fountain portal to Processing. The purple meteorite is already beside the table’s build location there. Insert Die Rise’s card. Buried’s card is on a small piece of furniture just outside the mansion’s rear exit and belongs in TranZit. The cycle is TranZit card → Die Rise, Die Rise card → Buried, Buried card → TranZit.','Carry the barn-passage parts through the fountain portal; build the table at Processing.'),
  step('endgame-grid','For the final activation, all four players must have all three Victis quests saved for the same allegiance and all tables/card links must be complete. Check the 3-by-4 light display at the back of the courthouse: each player’s row should show the same colour for TranZit, Die Rise and Buried. Blue is Richtofen; orange is Maxis. Mob of the Dead and Origins do not contribute.','Confirm all twelve courthouse lights match the chosen allegiance.'),
  step('endgame-button','When the team is ready, shoot/open the courthouse box and interact with its revealed button. This consumes/resets the saved Victis quest progress. Richtofen’s ending supplies permanent Fire Sale and a four-weapon bonus for that match; Maxis changes control of the zombies and introduces the blue-eyed Richtofen zombie. The story choice is optional after completing the map.','Activate the courthouse button only when ready to reset the three-map progress.',{note:'This is an in-game irreversible choice for your saved quest flags. Completing Mined Games does not require pressing it.'})
 ])
],[reddit('buried'),illustrated('buried'),joker('buried'),'https://www.reddit.com/r/CODZombies/comments/1i19a7/official_permapersistent_perks_thread/','https://margwa.net/buried','https://www.playstationtrophies.org/forum/topic/192628-call-of-duty-black-ops-ii-vengeance-dlc-trophy-guide-and-road-map/','https://steamcommunity.com/sharedfiles/filedetails/?id=269864761','https://www.callofdutyzombies.com/zombie-library/zombies-library/black-ops_ii/buried/nav-card-nav-card-table-r374/'])
