import {guide,phase,step,photos,collection,reddit,illustrated,joker} from './bo2-common.mjs'
const t=(...ids)=>photos('tranzit',...ids)
const d=(...ids)=>photos('die-rise',...ids)
export const tranzitGuide=guide('tranzit','TranZit','Ride the Green Run loop, build power and Pack-a-Punch, then choose Maxis or Richtofen for Tower of Babble. Play on Original. Both routes have a practical two-player method; four players make the final coordination easier. This guide covers the original BO2 Jet Gun, equipment, transport, persistent storage, music and the Navcard connection to Die Rise and Buried.',[
 phase('setup','First circuit: Turbine, power and perks',[
  step('setup-turbine','Before leaving Bus Depot, take the mannequin beside the central sign, the fan on the seats and the model-plane tail near the payphones. Carry one part at a time to the workbench in the starting room. Everyone can take a Turbine from the finished bench. Deploy it at the side door to leave without buying the main door; pick it back up after passing through. A broken Turbine can be replaced at this bench.','Build a Turbine in Bus Depot; take one before boarding.',{images:t('reference-tranzit-turbine-1','reference-tranzit-turbine-2','reference-tranzit-turbine-3')}),
  step('setup-route','The bus travels Bus Depot → Diner → Farm → Power Station → Town → Bus Depot. It does not wait for your setup to finish. At Diner, the MP5 is a dependable refillable weapon and the first Mystery Box is outside. At Farm, open the farmhouse for the weapon fridge and reach the barn for Double Tap. Save enough for the Power Station shed and Town’s Jugger-Nog building.','Follow the five-stop loop; buy a reliable wall weapon at Diner.'),
  step('setup-power','At the fourth stop, buy the small shed door and drop through its floor. In the white underground room, collect the electrical panel, switch handle and severed hand from the floor/railings and assemble them at the workbench. Turn the completed switch on. Wait for the electrical sequence and dialogue before leaving via the upper catwalk; a Turbine can open the exit gate. Avoid the open pit. For Maxis, wait for his instruction, then switch power off. For Richtofen or ordinary setup, leave it on.','Build power in the white underground room; choose whether to leave it on.',{images:t('reference-tranzit-power-1','reference-tranzit-power-2','reference-tranzit-power-3')}),
  step('setup-perks','Perks by stop: Quick Revive at Bus Depot; Speed Cola inside Diner; Double Tap upstairs in Farm’s barn; Tombstone upstairs beyond Power in co-op; Jugger-Nog upstairs in Town’s damaged building; Stamin-Up in Town’s bar. A Turbine can temporarily supply a machine when the main power is off. Do not expect that temporary supply to last after the Turbine is removed or breaks.','Jugger-Nog is in Town; perk access follows the power supply.')
 ],{group:'Key Features'}),
 phase('pack-a-punch','Open and build Pack-a-Punch',[
  step('pap-door','With power on, put a fresh Turbine directly against the lightning-marked metal door behind the drop into the white Power Station room. This opens the separate underground entrance in Town. In co-op, leave someone near the Turbine to protect it while the other player goes to the bank. Solo, prepare the bank doors first and travel promptly; the Turbine can break before you arrive.','Power the lightning door at the Power Station with a fresh Turbine.',{images:t('reference-tranzit-pack-a-punch-1')}),
  step('pap-bank','In Town’s bank, use explosives to open both vault doors. The passage beyond the second vault should lead downstairs. A closed metal wall means the Power Station Turbine is not supplying the door: return and replace it. Downstairs, find the machine casing, battery and stool/table in the corridors and carry them to the far workbench one at a time.','Blast both bank vault doors; build Pack-a-Punch in the open basement.',{images:t('reference-tranzit-pack-a-punch-1','reference-tranzit-pack-a-punch-2','reference-tranzit-pack-a-punch-3')}),
  step('pap-use','Pack-a-Punch costs 5,000 points. Bring the weapon and money before making the journey. Some compatible BO2 bullet weapons can be repacked for 2,000 to change attachments; this is not a BO3 alternate-ammo upgrade. If access closes after everyone leaves the basement, repeat the Turbine supply step.','Upgrade for 5,000; repeat the Turbine step if the basement closes.')
 ]),
 phase('equipment','Shield, traps, bus upgrades and the Jet Gun',[
  step('equipment-shield','Build the Zombie Shield at Diner’s garage bench: the car door is in the garage and the hand trolley is inside the diner. It protects your back when stowed and your front when held; return for a replacement when it breaks. Your carried buildable slot is shared with the Turbine, so plan which one you need before leaving a stop.','Combine the garage door and diner trolley at the garage bench.',{images:t('reference-tranzit-shield-1','reference-tranzit-shield-2')}),
  step('equipment-bus','Use a Turbine to open the utility rooms at Bus Depot, Diner, Farm and Town. Three of them contain the bus ladder, front plow/cow catcher and hatch, with one empty room. Attach the ladder to the rear-left side and the plow to the front. Choose the hatch placement: the bus ceiling gives an internal roof route, while Diner’s ceiling opening gives access to the 6,000-point Galvaknuckles. There is only one hatch, so decide before installing it.','Search four Turbine rooms; reserve the hatch for Diner if you want Galvaknuckles.',{images:t('reference-tranzit-bus-1','reference-tranzit-bus-2','reference-tranzit-bus-3')}),
  step('equipment-traps','Farm’s turret uses a lawnmower, gun and ammunition box scattered around the farm; assemble it at the farm bench. The Electric Trap uses a battery, metal rod and glass/insulator pieces around the Power Station’s upper ruined room; assemble there. Both require a nearby Turbine to operate. Keep their firing/electrical area away from teammates and replace the supply when it fails.','Turret at Farm; Electric Trap at Power; both need a Turbine.',{images:t('reference-tranzit-electric-trap-1','reference-tranzit-electric-trap-2','reference-tranzit-electric-trap-3')}),
  step('equipment-jet','The BO2 Jet Gun is assembled at Town’s bar workbench. Find the jet engine in the tunnel between Depot and Diner; the handle inside Nacht in the cornfield between Farm and Power; the gauge in the hunter’s cabin between Power and Town; and the wires around the Power Station’s ruined upper room. Search the floor and furniture in each small area, taking one part back to the bar at a time. It uses heat rather than ammunition. Release the trigger and allow it to cool for ordinary use; overheating breaks it and forces a rebuild. The Richtofen quest deliberately breaks a fully cooled gun at the tower.','Build the Jet Gun from tunnel, Nacht, cabin and Power Station parts.',{images:t('reference-tranzit-jet-gun-1','reference-tranzit-jet-gun-2','reference-tranzit-jet-gun-3')})
 ]),
 phase('maxis','Tower of Babble — Maxis route',[
  step('maxis-ready','Use Original difficulty and at least two players. Get EMP Grenades from the Mystery Box and carry two fresh Turbines. Turn power on, let Maxis finish speaking, then switch it off and leave it off. Reach the metal pylon in the cornfield between Farm and Power; a Navcard table is not needed for this individual quest.','Original, 2+ players, EMPs, two fresh Turbines; turn power off after Maxis speaks.'),
  step('maxis-avogadro','Keep the final zombie alive until the overhead electrical storm is above your area, then finish the round to encourage the Avogadro to spawn there. Lure the electrical enemy underneath the pylon without killing him on the way. Place both Turbines under the tower and wait for Maxis to request the kill. Throw an EMP close enough to destroy the Avogadro under the pylon while protecting the Turbines from the blast. Guns do not kill him.','Lure the Avogadro under the powered pylon and EMP him on Maxis’s cue.',{images:t('avogadro-being-killed'),note:'If Maxis reports drained power, replace the Turbines and repeat the attempt. A kill away from the pylon does not count.'}),
  step('maxis-lamps','After the accepted Avogadro kill, put Turbines beneath two different streetlamps at the same time; the safe lamps by Bus Depot and Diner are convenient. Two players can pick up and reuse their pylon Turbines for this last step. In a four-player run the other two can leave theirs at the pylon. Orange energy travelling to the tower and the achievement confirm completion. Do not require four Turbines for the two-player method.','Power two separate streetlamps; look for orange energy and the achievement.',{images:t('maxis-side-complete')})
 ],{group:'Main Quest'}),
 phase('richtofen','Tower of Babble — Richtofen route',[
  step('richtofen-ready','Leave main power on. Samuel Stuhlinger hears Richtofen’s instructions; have that player relay the dialogue. Assemble the Jet Gun and let it cool fully. Stand under the cornfield pylon, aim into its structure and hold the trigger until the gun breaks. Wait for Richtofen’s response before moving on. If there is no response, rebuild, cool fully and repeat at the tower.','Power on; fully cool the Jet Gun, then break it while firing into the pylon.',{images:t('fence-to-shoot-jet-gun')}),
  step('richtofen-kills','Gather zombies underneath the tower and kill them with explosives, such as grenades, the RPG or the original Ray Gun, until Richtofen complains about excess power. Keep the kills inside the pylon footprint. Ordinary bullet kills elsewhere do not advance this charge.','Earn explosive kills directly beneath the pylon until the dialogue changes.'),
  step('richtofen-emps','Four green streetlamps must be disabled within the same short window. The straightforward method is four EMP-equipped players, each at a different lamp, throwing on a countdown. With two players, each needs both EMPs and a prepared Denizen portal: throw at the starting lamp, immediately jump through the portal and EMP the destination lamp. The destinations are random; duplicate or already-disabled lamps mean retrying with replenished EMPs.','EMP four distinct green lamps together; use two portal hops for a two-player attempt.',{images:t('green-light-post','teleporter')}),
  step('richtofen-complete','Watch for blue energy at the pylon and Tower of Babble completion. If the timing fails, replenish equipment and retry the lamps; do not redo accepted charging steps without a reason. Agree the route before the match: Maxis and Richtofen are alternative outcomes, not consecutive phases to complete in one run.','Blue tower energy confirms Richtofen’s completion.')
 ])
],[
 phase('transport','Fog travel and Denizen portals',[
  step('transport-portals','When a Denizen grabs your face in the fog, walk underneath a powered green streetlamp without killing it. It burrows into the ground to make a portal. Jump into the opening to travel to a random other lamp. This is useful for returning to a missed bus stop, but it is not a destination selector. If you need a predictable journey, follow the road or wait for the bus.','Lead a live Denizen to a green lamp and jump into its portal.',{images:t('teleporter','green-light-post')}),
  step('transport-hazards','Listen for a Denizen’s screech and melee it off promptly. Cross lava in short jumps and allow health to recover before another crossing. Do not melee a burning zombie at low health: its death explosion can finish you. The tunnel, cabin, Nacht and pylon are useful fog refuges. Repeatedly attacking the bus driver can get you ejected and locked out temporarily.','Use fog refuges, manage lava damage and avoid provoking the driver.')
 ],{group:'Side Quests'}),
 phase('storage','Bank, weapon fridge and persistent upgrades',[
  step('storage-bank','Inside Town’s first bank vault, the two key prompts deposit or withdraw points in 1,000-point transactions; withdrawals charge 100 points. Supported online profiles share this bank between TranZit, Die Rise and Buried. Galvaknuckles on the keys behind the outer bank counter enables a point-transfer pickup for teammates. Test deposits on your mode/profile before relying on an old balance.','Use the bank keys for shared Victis storage and teammate point transfers.'),
  step('storage-fridge','Interact with Farm’s kitchen fridge while holding an eligible weapon to store it. Returning with another weapon swaps them. Wonder weapons and the starting pistol are excluded. This is distinct from the small standalone Farm Survival map, which does not provide the TranZit storage route.','Store an eligible weapon in the Farm kitchen fridge.'),
  step('storage-upgrades','Victis persistent upgrades are hidden bonuses, confirmed by a green flash, rather than inventory perks you can buy. Examples include faster revives from successful revives and the red Insta-Kill effect after letting two Insta-Kills expire without kills. Their loss conditions and mode/profile support vary. They are optional: none is a prerequisite for the routes above. Use the linked dedicated reference if deliberately farming them.','Treat green-flash persistent bonuses as optional.',{links:[{href:'https://www.reddit.com/r/CODZombies/comments/1i19a7/official_permapersistent_perks_thread/',label:'Persistent upgrades: acquisition and loss conditions'}]})
 ]),
 phase('navcards','Navcard table and the three-map connection',[
  step('navcard-parts','Build beneath the cornfield pylon: meteorite in the wall hole immediately outside Bus Depot; wooden plank in the road tunnel or below Power’s upper catwalk; radio in Nacht or on the Diner garage cabinet; electrical box by Farm’s fridge or Town’s outside Box spot. Carry these special parts to the fence underneath the pylon and find the build prompt.','Build the four-part Navcard table under the pylon.',{images:t('reference-tranzit-nav-card-table-1')}),
  step('navcard-loop','Pick up TranZit’s card behind the Bus Depot building. It is accepted by Die Rise, whose card goes to Buried; Buried’s card goes to TranZit. Your own map’s card is meant to be rejected by its reader. Card/table progress contributes to the later Buried endgame, not ordinary Tower of Babble.','Card loop: TranZit → Die Rise → Buried → TranZit.',{links:[{href:'/guides/bo2-buried#details-endgame',label:'Three-map endgame requirements'}]})
 ]),
 phase('music','Carrion, radios and hidden landmarks',[
  step('music-bears','Hold interact on three teddy bears to play Carrion: the bench outside Bus Depot toward the Diner road; the bed upstairs in Farm’s house; and the booth downstairs in Town’s bar. Listen for each activation before leaving. This is a music secret and does not charge the tower.','Activate the Depot, Farm bedroom and Town bar teddy bears.'),
  step('music-radio','The television downstairs in Farm’s house carries Maxis’s broadcasts. Interact before power, then return with power active and interact to hear its messages. Explore the cornfield’s Nacht building and the road signs for story references; they do not reveal another required tower step.','Listen to Farm’s TV and visit the cornfield Nacht landmark.',{images:t('reference-tranzit-tv-1')})
 ])
],[reddit('tranzit'),illustrated('tranzit'),joker('tranzit'),'https://www.callofdutyzombies.com/easteregg/guides/call_of_duty_black_ops_ii_zombies/451_main-easter-eggs/tranzit/maxis_steps_the_tower_of_babble/use-the-turbines-r65/'])

export const dieRiseGuide=guide('die-rise','Die Rise','A vertical map where knowing your return route matters as much as your weapon. Build the Trample Steam and Sliquifier, use the moving perk elevators safely, then complete either High Maintenance branch. The original quest needs four players on Original; it is separate from community BO3 remakes and their added quests.',[
 phase('setup','Power, elevators and a safe return route',[
  step('setup-power','From spawn, the broken starting elevator drops you toward the lower floor. Cross to the power building using the broken passages and mattress landing, then turn on the switch beside the sewing machines. Its elevators now move and carry perks or Pack-a-Punch between floors. Ride upward to reach the dragon roof. Before any drop, identify a visible landing and how you will get back; an arbitrary long fall kills you.','Reach the sewing-machine power room, turn on power and ride to the roof.'),
  step('setup-elevators','Read which machine is in each elevator rather than assuming a fixed shaft. Spawn-side elevators carry Quick Revive, Speed Cola and Who’s Who; the power-building group carries Jugger-Nog, Double Tap, Mule Kick and Pack-a-Punch. Buy or upgrade when it has just arrived and remains stationary, then step clear. Bells and closing doors warn it is about to move; staying on its roof at the top of a shaft crushes you.','Wait for an elevator to stop before buying; step off before its top stop.',{images:d('reference-jugger-nog-elevator-1','reference-pack-a-punch-elevator-1')}),
  step('setup-key','A key from the bottom of the starting elevator can call a lift at a floor switch; it is consumed when used. The starting elevator control panel can return that lift once the players who dropped with it are back aboard. Keep the AN-94 near the lower route or PDW on the spawn-building route as an ammunition plan before spending heavily at the Box. Who’s Who creates a vulnerable double that must revive your body to recover your equipment; it does not make falls safe.','Use elevator keys carefully and retain a refillable weapon.',{images:d('reference-die-rise-elevator-key-1','reference-die-rise-elevator-switch-1','reference-die-rise-elevator-spawn-room-control-panel-1')})
 ],{group:'Key Features'}),
 phase('buildables','Trample Steam and Sliquifier',[
  step('build-trample','Gather the mesh screen, motor/compressor, bellows and flag from spawn and the adjacent lobby: by the front door/wall, desk or collapsed stairs, stairway/wall, and chair/railing respectively. Carry them one at a time to the Trample Steam bench in the room reached by dropping from the lobby, beside the perk elevators. Place the device on level ground and let it reset before stepping on it. Each teammate takes their own from the completed bench.','Carry the four spawn/lobby parts to the Trample Steam bench.',{images:d('reference-trample-steam-pump-1','reference-trample-steam-power-supply-1','reference-trample-steam-flag-1')}),
  step('build-sliq','At the workbench beneath the power room, assemble four Sliquifier parts. The foot is on the floor between the couch and TV near the stairs. The trigger/handle is on a Power-room desk by the elevators or the lower kitchen counter. The bottle is on the desk opposite power or the bottom shelf right of the build bench. The round canister/gauge is on a desk in the upper entry room or a barrel opposite the lower bench. Check both possible spots for each variable part.','Find foot, canister, bottle and trigger around the power-building workshop.',{images:d('reference-sliquifier-handle-1','reference-sliquifier-gage-1','reference-sliquifier-bottle-1')}),
  step('build-sliq-use','Shoot a gathered group to start a Sliquifier chain reaction; leave space so another zombie steps into the effect. The purple puddle also makes players slip, so keep it away from narrow ledges and jump takeoffs. The original weapon has no Pack-a-Punch upgrade. Keep one available for Richtofen’s branch. A broken Trample Steam is replaced at its bench, not repaired by firing the Sliquifier.','Use Sliquifier chains on open ground; keep puddles away from drops.')
 ]),
 phase('shared','High Maintenance — shared opening',[
  step('quest-ready','Bring four players on Original, build the rooftop Navcard table, turn on power, and let everyone take a Trample Steam. Both branches use a sniper and Galvaknuckles later. Richtofen needs the Sliquifier; Maxis needs a Pack-a-Punched Ballistic Knife. For Maxis, reserve a player who has not bought a Bowie Knife or Galvaknuckles and has not bled out to operate the Ballistic Knife.','Four players; power, rooftop table, Trample Steams and branch equipment.'),
  step('quest-elevators','Stand simultaneously on the four golden symbols atop elevators: Quick Revive outside spawn, the elevator left of the Trample Steam bench, the one beside power, and the one near the MP5. Coordinate while the lifts are low enough to stand on safely. All four symbols light and dialogue confirms the step; get off before being crushed.','Stand on the four elevator-roof symbols together.',{images:d('symbol-above-quick-revive-elevator','symbol-above-the-elevator-left-of-the-trample-steam-buildable','symbol-above-power-switch-elevator','symbol-above-elevator-near-the-mp5-wall-buy')}),
  step('quest-floor','Now test the four floor symbols one at a time: outside spawn’s Quick Revive lift; roof near the drop from the power building; upside-down cafeteria; roof outside the bank/shower area. A correct next tile stays illuminated. After a wrong tile, replay the accepted prefix before trying another. Keep someone at each tile; if repeated failures change the sequence, discard the old assumptions and retest.','Find the floor-symbol order by testing and watching which symbols stay lit.',{images:d('floor-symbol-in-front-of-the-quick-revive-elevator-outside-of-spawn','floor-symbol-atop-the-power-building-near-the-drop-down','floor-symbol-inside-of-the-cafeteria','floor-symbol-on-the-rooftop-of-the-building-outside-the-bank-shower-area')}),
  step('quest-balls','Buy the SVU-AS or obtain another sniper. From the roof, shoot the ball inside each dragon’s mouth. Confirm both have moved to the paws of the lion statues back in spawn. Choose one branch below; do not mix the lion and zombie Trample Steam positions.','Sniper-shoot both dragon-mouth balls; choose Maxis or Richtofen.',{images:d('first-dragon-mouth','second-dragon-mouth','ball-under-lion-statue-paw')})
 ],{group:'Main Quest'}),
 phase('maxis','Maxis — Buddha room and lion launchers',[
  step('maxis-buddha','Kill zombies continuously on the lower floor of the red Buddha room until Maxis talks about reincarnation. Keep the team’s kills inside this room; kills outside interrupt the sequence. Bring sufficient ammunition and leave the special Ballistic Knife player free to prepare.','Earn the Buddha-room kills until Maxis’s reincarnation cue.',{images:d('buddha-room')}),
  step('maxis-knife','The player reserved earlier must Pack-a-Punch a Ballistic Knife into the Krauss Refibrillator and fire it inside the Buddha room. Listen for Maxis’s acceptance before progressing; try a shot into a zombie there if a shot at the floor does not trigger it. Reviving a deliberately downed teammate is not a universal requirement. A prior melee-weapon purchase or bleed-out can invalidate the operator, so use the reserved player.','Fire the upgraded Ballistic Knife in the Buddha room; listen for acceptance.'),
  step('maxis-launch','Place four Trample Steams on the lion symbols, facing along the lion’s head: spawn, bottom of the spawn escalators, roof by the Box, and roof by the two elevators. Correctly aligned devices lock into position. Two players collect the spawn balls and put one on the spawn launcher and one on the escalator launcher. Their repeated flights feed the tower. Wait for the orange glow before the Mahjong finale.','Align the four lion launchers; launch both balls until the tower glows orange.',{images:d('lion-symbol-in-the-spawn-room','lion-symbol-in-the-spawn-building-bottom-of-escalators','lion-symbol-atop-the-power-building-near-the-box-location','lion-symbol-outside-of-the-two-elevators-atop-the-power-building')})
 ]),
 phase('richtofen','Richtofen — Sliquifier and zombie launchers',[
  step('richtofen-balls','Shoot each spawn lion ball repeatedly with the Sliquifier until it spins; allow roughly twenty direct hits per ball and watch the result instead of counting blindly. Stuhlinger hears the next blood-sacrifice instruction. Do not take the balls for the Maxis launcher route.','Sliquifier-shoot both spawn balls until they spin.',{images:d('ball-under-lion-statue-paw')}),
  step('richtofen-launch','Place four Trample Steams on the golden zombie silhouettes facing toward the pylon: outside spawn’s Quick Revive, the Semtex balcony, and the two roof marks by the slope down from the power roof. Feed zombies into the launchers until blue energy lights the tower. If a device is destroyed, replace it in the same orientation and continue.','Launch zombies from the four zombie symbols until the tower glows blue.',{images:d('zombie-symbol-outside-the-quick-revive-elevator','zombie-symbol-on-the-balcony-near-semtex-wall-buy','two-zombie-symbols-next-to-pathway-leading-down-from-power-roof')})
 ]),
 phase('mahjong','Both routes — decode the tiles and strike the tower',[
  step('mahjong-read','Find eight Mahjong tiles among the eleven photographed spawn points. Four tiles mean compass directions and four represent strike numbers 1–4. Match a direction tile and a number tile by their shared red, green, blue or black colour. The colour pairing changes each game. Enter the observed colours beside the photographed shapes in the helper; do not treat a tile’s picture alone as a permanent strike order.','Pair number and direction tiles by colour; use the visual decoder.',{images:d('mahjong-tiles')}),
  step('mahjong-locations','Search the roof pylon corner and lawn chair; spawn desk, escalator bottom and broken stairs; the upside-down couch; the lowest safe ledge of the shaft below Galvaknuckles; upper Buddha room ledge; power room sewing table; shelf by the AK74u; and kitchen counter near the MP5. Only eight positions contain a tile. The helper’s reference gallery shows all eleven.','Search all eleven possible tile positions for eight actual clues.'),
  step('mahjong-strike','The pylon leg beside the photographed tile spawn is North (the side facing away from the Power Building), even if that spawn is empty. Orient yourself from that fixed anchor; screen-left and screen-right change when you walk around the tower. With Galvaknuckles, strike the four legs once each in the decoded 1–4 order. A wrong attempt extinguishes the glow and requires the next round before retrying. Electricity over the whole tower, the achievement and all perks confirm the selected route.','Strike North/East/South/West legs in your decoded order with Galvaknuckles.',{images:d('corner-of-the-pylon-tile-spawn'),note:'The decoder rejects repeated colours. Recheck a misread black/blue tile before spending a once-per-round attempt.'})
 ],{tools:['bo2-die-rise-mahjong']})
],[
 phase('free-perks','Jumping Jacks and free perk bottles',[
  step('jacks-perfect','On a Jumping Jack round, kill every crawler without missing a fired bullet to earn the bonus perk bottle. The dependable approach is melee and correctly placed Trample Steams, with nobody firing. One teammate firing a missed shot can spoil the bonus for the round. Finish the last crawler and collect the perk and Max Ammo after reloading.','Use melee/Trample Steams and no missed shots for the special-round perk.'),
  step('jacks-use','Bonus bottles can take you above the four purchased-perk limit. Buy essential perks before collecting a bottle to reduce the chance it fills an ordinary purchase slot. Keep space around the launcher so a crawler cannot push you off a ledge. The PhD machine seen through the starting shaft is a tease, not an accessible BO2 perk purchase.','Buy essentials before free bottles; the shaft’s PhD machine is inaccessible.')
 ],{group:'Side Quests'}),
 phase('navcards','Rooftop Navcard table, bank and locker',[
  step('navcard-table','All four Navcard table parts are on the dragon roof: plank under the metal walkway by an air vent, radio to the right of the stairs down, meteorite in debris by Claymores, and electrical box beside the elevator/window in the small roof Box area. Build beneath the pylon. Insert the card from TranZit. Die Rise’s own card is in the first tower near the PDW wallbuy and belongs in Buried.','Build the rooftop table; insert TranZit’s card and take Die Rise’s to Buried.'),
  step('storage','The shower fixtures just outside the Power room act as the bank: the left deposits points and the right withdraws them. The weapon locker is beside these showers. They share supported online-profile storage with TranZit and Buried. Deposits do not replace the four-player quest requirement. Refill ammunition and retrieve a Trample Steam before leaving this lower route.','Use the shower bank and nearby weapon fridge between rooftop trips.')
 ]),
 phase('music','We All Fall Down and small secrets',[
  step('music-bears','Interact with all three teddy bears: shelves beside the SVU-AS in the spawn building; the upper ledge of the Buddha room near its window barrier; and the sewing-machine table in the power room. Each makes a cue, and the third starts We All Fall Down.','Activate the SVU shelf, Buddha ledge and power-table bears.'),
  step('music-details','The inaccessible PhD room, distant groans and skyline details are environmental secrets. They do not unlock PhD or a second wonder-weapon upgrade in the original game. Green-flash persistent bonuses can carry between supported Victis matches; the main quest above does not depend on them.','Explore the environmental details after securing a safe elevator route.')
 ])
],[reddit('die-rise'),illustrated('die-rise'),joker('die-rise'),'https://discover.hubpages.com/games-hobbies/How-to-Build-The-Sliquifier-in-Die-Rise-Call-of-Duty-Black-ops-2-Zombies','https://steamcommunity.com/sharedfiles/filedetails/?id=130456538'])
