import { guide, phase as p, step as s, image, reddit, illustrated } from './bo3-common.mjs'
const im = (file, alt) => image('gorod-krovi', `gk-${file}`, alt)
export const gorod = guide('gorod-krovi', 'Gorod Krovi', 'A complete Love and War route for 1–4 players: dragon travel, shield and Gauntlet, all trophies and challenges, the two-part boss fight, equipment upgrades and optional rewards. The valve helper calculates settings from your two observations; the bomb helper records SOPHIA’s actual order with location photographs. They solve different tasks.', 'gorod-krovi', [
  p('setup', 'Power, dragon travel and Pack-a-Punch', [
    s('setup-1', 'Reach Dragon Command, turn on power and interact with SOPHIA. Enemies can now drop colored Code Cylinders. Insert each cylinder in its matching terminal: blue at Dragon Command, yellow at Supply Depot, red at Tank Factory. Follow the green beam to its Groph Module and protect it with nearby kills until it opens. Collect the Network Circuit and repeat for all three colors. If a module is destroyed, obtain another cylinder and retry.', 'Power → three colored cylinders → defend three modules → collect their circuits.', { images: [im('power-generator', 'Power switch in Dragon Command.'), im('supply-depot-terminal', 'Yellow cylinder: Supply Depot terminal.'), im('tank-factory-terminal', 'Red cylinder: Tank Factory terminal.'), im('dragon-command-terminal', 'Blue cylinder: Dragon Command terminal.')] }),
    s('setup-2', 'Install the three circuits in the Dragon Network Controller in Operations Bunker. Pay 2,000 points at an active dragon platform to ride to the Hatchery, where Pack-a-Punch is available. The stations are Dragon Command, Supply Depot and Tank Factory. Leave through the Hatchery’s lower sewer chute when finished.', 'Install circuits in Operations Bunker → dragon ride → Hatchery Pack-a-Punch.', { images: [im('dragon-network-controller', 'Fit the three circuits into this controller.')] }),
    s('setup-3', 'Collect one shield piece from each group, then build at the Operations Bunker bench. Hold the shield in front of you during dragon fire; wearing it on your back does not protect your exposed front. Its fire blast is also needed for a trophy.', 'Collect three shield pieces → build in Operations Bunker.', { bullets: ['Visage: Infirmary shelf near the middle-floor stairs, rubble by the broken Operations walkway, or upper floor beside Stamin-Up.', 'Core: chair beside Juggernog in Department Store, the truck toward Operations Bunker, or a shelf inside Operations Bunker.', 'Maw: Armory ground-floor rubble by Wunderfizz, the middle-floor wall beside the crashed-bus walkway, or upper-floor wall by the bridge.'], images: [im('shield-visage-first-spawn', 'Visage: search the Infirmary group.'), im('shield-core-first-spawn', 'Core: search Department Store and Operations.'), im('shield-maw-first-spawn', 'Maw: search the Armory group.')] })
  ], { group: 'Key Features' }),
  p('equipment', 'Dragon Strike and Gauntlet of Siegfried', [
    s('equipment-1', 'At the Hatchery’s upper floor, have every player interact with the crystal to begin a lockdown. Defend the windows through four waves; the last wave opens several directions. Collect the Dragon Strike controller from the crystal afterward. A strike attracts enemies and calls in dragon fire. Keep one available for the Supply Depot trophy.', 'All players activate Hatchery crystal → survive four waves → collect Dragon Strike.', { images: [im('dragon-strike-crystal', 'The upper-floor crystal starts the lockdown and gives its reward.')] }),
    s('equipment-2', 'Shoot down the dragon egg above the Hatchery sewer exit and collect it. Put it in a nest, such as the one below Dragon Command’s stairs, and let a dragon’s breath heat it. Wait a round for it to cool before collecting it. Read your spawn trial gravestone for the next requirement and complete them in sequence: napalm-zombie kills, penetration multikills, then melee kills. Use a penetrating bullet weapon to kill several zombies with one shot; explosive multikills do not substitute.', 'Collect egg → heat in dragon fire → cool → napalm, penetration and melee trials.', { images: [im('dragon-egg', 'Shoot this egg down above the Hatchery sewer exit.'), im('dragon-egg-nest', 'Heat the egg in a nest beneath a dragon’s fire.')] }),
    s('equipment-3', 'Place the completed egg in the Hatchery basement incubator and survive its defense. Let it cool for a round, collect it and claim the Gauntlet of Siegfried at your spawn gravestone. The Gauntlet has a flamethrower, a deployable dragon whelp and a punch; several quest objects specifically need the whelp or punch rather than ordinary gunfire.', 'Incubate and defend egg → cool → collect → claim Gauntlet at spawn.', { images: [im('dragon-egg-incubation', 'Incubate the egg in the Hatchery basement.'), im('gauntlet-of-siegfried', 'Claim the completed specialist at your trial gravestone.')] })
  ]),
  p('valves', 'Airflow valves and SOPHIA’s password', [
    s('valves-1', 'In the Hatchery basement, expose the generator and use a Valkyrie drone’s electricity or explosion near it to start the airflow system. It runs for a limited window; if it stops, return and restart it. Visit the six valve stations and identify the green light and the station containing a pink cylinder. These are your start and endpoint, not two valve settings.', 'Power Hatchery generator → find green-light room and pink-cylinder room.', { note: 'The cylinder room is the endpoint. Leave its valve alone. Record both clues before changing the other five.' }),
    s('valves-2', 'Choose those two rooms in the helper. Set each of the other five valves to the displayed number and recheck the actual pointer after turning it. The helper routes airflow through all six rooms. Once all settings are correct and the generator is running, take the pink cylinder from its endpoint. If it does not release, inspect the five pointers and generator before changing your clue selections.', 'Use the calculated five settings → collect cylinder at the unchanged endpoint.', { images: [im('pink-code-cylinder', 'The pink cylinder becomes collectible after the air path is correct.')] }),
    s('valves-3', 'Insert the cylinder into SOPHIA. Shoot her letter wheels to spell KRONOS from top to bottom, then interact to submit it. A rejected entry requires waiting for the next round; check the full word before submitting.', 'Insert cylinder → spell KRONOS top to bottom → submit.', { images: [im('password', 'Set the vertical password to KRONOS.')] })
  ], { group: 'Main Quest', tools: ['bo3-gorod-valves'] }),
  p('trophies', 'Collect and install all six trophies', [
    s('trophies-1', 'Collect the first three trophies: shoot the hand of the statue outside Dragon Command; use a shield blast on the pipe visible through the left-side window at Tank Factory near Double Tap; activate Supply Depot’s laser trap and pick up the trophy from the floor beneath it.', 'Statue hand + shield-blasted pipe + Supply Depot laser trap.', { images: [im('gersh-trophy', 'Shoot the statue’s hand outside Dragon Command.'), im('valkryie-drone-trophy', 'Shield-blast the pipe through the Tank Factory window.'), im('mangler-trophy', 'Use the Supply Depot laser trap, then collect its trophy.')] }),
    s('trophies-2', 'Collect the remaining three: use Dragon Strike on the Supply Depot puddle beneath the overhead Armory connection; release the Gauntlet’s whelp and punch the safe in Operations Bunker beside the workbench; ride the Hatchery sewer and shoot the red ceiling light as you pass so it turns green, then return to the Hatchery and collect the trophy from the toilet.', 'Dragon Strike puddle + Gauntlet-punch safe + sewer red light / Hatchery toilet.', { images: [im('bomb-trophy', 'Dragon Strike exposes this trophy in the puddle.'), im('groph-pod-trophy', 'Use the Gauntlet punch on the Operations safe.'), im('sewage-pipe-button', 'Shoot this red light during the sewer ride.'), im('group-935-trophy', 'Return for the toilet trophy after the light turns green.')] }),
    s('trophies-3', 'Install all six trophies around the monitor in front of SOPHIA. Press its button to select a challenge. The first five arrive in random order; the information download is last. A failed challenge normally becomes available again next round. Avoid starting a challenge during a Valkyrie special round, and let SOPHIA finish speaking before assuming it has started.', 'Install trophies → activate monitor → complete five random challenges, then download.', { images: [im('main-monitor', 'This monitor selects challenges and flashes the bomb sequence.')] })
  ]),
  p('challenges', 'The six SOPHIA challenges', [
    s('challenges-bombs', 'Bomb defusal: ignore the monitor’s initial rapid shuffle, then record its six deliberate location flashes in order. Use the bomb photographs below to locate each device and interact in exactly that order. Agree who takes each bomb before starting and call out each successful defusal. The challenge is timed, with different solo/co-op windows; rely on the match’s timer rather than a web timer.', 'Bombs: record the six real flashes → defuse exactly in that order.', { note: 'A wrong bomb or an expired timer can end the run. Do not reorder the sequence to shorten travel, and do not use the valve route as a bomb order.' }),
    s('challenges-gersh', 'Gersh: search for a small yellow orb and listen for its sound. Shoot it with a Pack-a-Punched weapon until it turns purple and stops. Listen to its dialogue, then follow it to the next position. Repeat three stops until it returns to Dragon Command. Ordinary unupgraded shots do not provide the required damage.', 'Gersh: find yellow orb → Pack-a-Punched damage → listen → follow and repeat.', { images: [im('gersh-challenge', 'The target is the glowing moving orb.')] }),
    s('challenges-valkyrie', 'Valkyrie escort: find the special green-eyed, damaged drone at spawn. Stay near it to move it toward Dragon Command; it stops when nobody is nearby. Clear the route ahead without hitting it. Explosives, traps and the Mark III’s combined black hole can destroy it. Keep your team’s firing direction away from the drone.', 'Escort green-eyed drone from spawn to SOPHIA without damaging it.', { images: [im('valkyrie-drone-challenge', 'Escort this damaged green-eyed drone.')] }),
    s('challenges-mangler', 'Mangler escort: locate the green-eyed Mangler in the surrounding buildings and lure it to Dragon Command while keeping line of sight. Carefully shooting off its arm cannon can make it run, but killing it fails the task. Use controlled, low-damage shots if doing this. Do not turn invisible when you are its only target.', 'Find green-eyed Mangler → maintain its attention → lure it to Dragon Command.', { images: [im('mangler-challenge', 'The green-eyed Mangler must arrive alive.')] }),
    s('challenges-pod', 'Groph Module: locate the green beam outside the playable area and defend the module from zombies using ranged weapons. Once it is complete, release the Gauntlet’s dragon whelp toward its cargo. Wait for the whelp to bring it back, collect it, then deliver it to SOPHIA. This module is separate from the earlier dragon-network modules.', 'Protect distant module → send whelp for cargo → return cargo to SOPHIA.', { images: [im('groph-pod-challenge', 'Protect the module outside the normal paths.'), im('groph-pod-challenge-cargo', 'The whelp retrieves the completed module’s cargo.')] }),
    s('challenges-download', 'Download: take the keycard from SOPHIA’s drawer and ride to the Hatchery. Insert it in the computer on the Pack-a-Punch floor, start the lockdown and survive the Manglers while the download completes. Retrieve the card afterward and return it to SOPHIA; surviving without taking the card does not finish the challenge.', 'Take keycard → Hatchery computer / lockdown → retrieve downloaded card → SOPHIA.', { images: [im('information-download', 'Start and finish the download at this computer.')] })
  ], { tools: ['bo3-gorod-bombs'] }),
  p('boss', 'Deliver the power core and fight the dragon / Nikolai', [
    s('boss-1', 'Take SOPHIA’s power core to spawn and deploy the Gauntlet’s whelp toward Nikolai’s mech to deliver it. Return to Dragon Command. When SOPHIA leaves and the floor opens, prepare fresh shields, perks, ammunition and strong Pack-a-Punched weapons. Gather everyone on the exposed grate to descend. Press the arena button to free Nikolai and start the fight.', 'Whelp delivers core to Nikolai → SOPHIA leaves → all players enter grate → arena button.', { images: [im('power-core', 'Take the core from SOPHIA.'), im('entrance-to-boss-arena', 'All players must be ready before entering.'), im('free-nikolai-button', 'Press the arena button to begin.')] }),
    s('boss-2', 'Keep moving around the arena edge and hold the shield toward dragon fire. Wait for Nikolai to harpoon the dragon and expose a glowing orange weak point. Shoot only that point during the damage window. Survive the enemy waves between openings and repeat for the different exposed areas until the dragon dies. Save shield durability and collect ammunition drops between phases.', 'Dragon: survive fire → shoot each exposed orange weak point → repeat.', { images: [im('dragon-weak-point', 'Only the exposed orange area accepts damage.')] }),
    s('boss-3', 'After the short scene, fight Nikolai’s mech. Shoot the two yellow front panels and the two upper power cores when its attacks expose them. Avoid its rockets and keep the team spread out. Once the outer points are destroyed, damage the central glowing core to finish. Wait for the ending and reward before leaving the game.', 'Nikolai: destroy four exposed outer weak points → central core → ending.', { images: [im('nikolai-weak-points', 'Damage the exposed front and upper weak points.'), im('nikolai-final-weak-point', 'Finish with the central core.')] })
  ])
], [
  p('upgrades', 'Upgraded shield and Dragon Strike', [
    s('shield-upgrade', 'Get about 50 kills with the shield, then blast the three glowing lines of symbols: left of Dragon Command’s exterior platform, on Supply Depot’s broken roof, and on the giant robot’s arm at Tank Factory. A successful hit makes that line disappear. Hold your shield out in dragon fire until the confirmation sound, then interact with the blood inside the dead dragon at spawn to upgrade it. If no prompt appears, absorb more fire until the sound; you do not need to repeat all the kills.'),
    s('strike-upgrade', 'Earn Dragon Strike kills until the confirmation cue. Red flags appear around the map: near the spawn sewer and at the three dragon stations. The active flags depend on player count; hit every visible flag with a Dragon Strike. Return to the Hatchery and repeat the crystal lockdown, then collect the upgraded Draconite controller. This improves the strike and gives additional charges.')
  ], { group: 'Side Quests' }),
  p('helmets', 'Helmets, wings and timed melee rewards', [
    s('dragon-wings', 'After obtaining the Gauntlet, ride a dragon from each of the three stations. Claim the Dragon Wings from the mannequin upstairs in Department Store. They make future dragon travel free and speed up departure.'),
    s('mangler-helmet', 'Shoot off five Mangler helmets and destroy five arm cannons. Claim the helmet from its Department Store mannequin once the completion cue sounds. For the Valkyrie helmet, destroy six drone cameras and remove all the tentacles from six drones; then claim its mannequin reward near Juggernog. These are separate requirements, so a simple kill total is not enough.'),
    s('time-attacks', 'Finish round 5 before 5:00 for the Wrench; round 10 before 13:00 for the Malice; round 15 before 24:00 for Slash N’ Burn; and round 20 before 32:00 for Fury’s Song. The deadline is for completing the round. A qualifying weapon appears on the board at the Operations Bunker entrance, priced 100, 200, 300 and 500 points respectively. Plan these as an early speed run rather than interrupting a careful late quest setup.')
  ]),
  p('monkeys', 'Upgraded Monkey Bombs', [
    s('monkey-items', 'Obtain Monkey Bombs. Find your flowerpot: check Dragon Command’s office desk, Supply Depot’s upper desk after the train, Supply Depot’s ground-floor desk, and Department Store’s L-CAR 9 table. A pot can be visible only to its assigned player. Light a candle with the shield and collect it: check Department Store’s upper shelf, beneath a Supply Depot desk, the Tank Factory table near Double Tap, and an Infirmary bunk.'),
    s('monkey-finish', 'Get Monkey Bomb kills until a blue flask drops and collect it. Take your pot, candle and flask to your trial gravestone at spawn, throw a Monkey Bomb beside it and interact with the green flame. Collect the upgraded bomb from the skeleton. The flask drop is the useful confirmation; do not assume that a guessed kill count guarantees it. Crate Power used when taking Monkeys from the box is an alternative upgrade route.')
  ]),
  p('music-lore', 'Music, Samantha’s challenge and lore', [
    s('dead-ended', 'For Dead Ended, interact with the vodka bottles on the Department Store’s first-floor couch just past spawn, beside the dead soldier and burning truck outside Operations Bunker, and on the Supply Depot entrance shelf beside the medical crate. Any order works.'),
    s('ace-of-spades', 'For Ace of Spades, interact with three playing cards: the bottom-left corner of the chalkboard beside Double Tap in Tank Factory, the upstairs Dragon Command office desk beside the telephone, and between the books on the desk to the right of Hatchery Pack-a-Punch.'),
    s('samantha-start', 'For Samantha’s Sorrow, throw a Monkey Bomb into dragon fire in each of the three dragon-station districts. Interact with the small Samantha doll at spawn by the fountain/gravestones, then shoot the musical dolls that appear one after another. Follow the music quickly; the sequence is timed. Return to the starting doll for the reward after five successful targets.'),
    s('samantha-locations', 'Search upward as well as at ground level: dolls can appear around the spawn fountain and street, the ruined church, Department Store windows and roof, Operations Bunker, the giant robot, Infirmary, Armory, Supply Depot and Dragon Command. Use the linked illustrated side-quest reference for the exact sightlines before starting the timed attempt.', null, { links: [{ href: 'https://steamcommunity.com/sharedfiles/filedetails/?id=724585259', label: 'Samantha target photographs and music-object locations' }] }),
    s('gorod-lore', 'The music bottles, radios and ciphers are independent of Love and War. Their recordings and decoded story messages are catalogued in the community guide. Personal gravestone trials also award ammunition, weapons and perks; claim a ready reward before spending points on a replacement.', null, { links: [{ href: reddit('gorod-krovi'), label: 'Music, radio and cipher reference' }] })
  ])
], [reddit('gorod-krovi'), illustrated('gorod-krovi'), 'https://steamcommunity.com/sharedfiles/filedetails/?id=724585259', 'https://www.reddit.com/r/CODZombies/comments/1d4d2ga/the_gorod_krovi_valve_step_demystified/'])
