import { rooms, shadowGlyphs, voidGlyphs, voidNames, terminalGlyphs, plantRecipes } from './bo3-references.mjs'
const f = (id, label, options = null, extra = {}) => ({ id, label, options, ...extra })
const slots = (n, prefix, options = null) => Array.from({ length:n }, (_,i) => f(`${prefix}-${i}`, `${prefix} ${i+1}`, options))
const checks = n => slots(n,'check').map(f => ({...f,type:'check'}))
const t = (id,map,name,help,fields,kind='reference',extra={}) => ({id:`bo3-${id}`,map:`bo3-${map}`,name,help,fields,kind,version:1,ui:'bo3',...extra})
export const bo3Tools = [
  t('shadows-glyphs','shadows-of-evil','Train symbol matcher','Match the three red symbols seen through train windows. Select them from the sword wall below; the wall needs the collected set, not a special input order.',[...slots(3,'slot'),...slots(3,'glyph',shadowGlyphs.map(g=>g.id))],'recorder'),
  t('de-void','der-eisendrache','Void Bow name → symbol matcher','Record the three spoken names, then inspect those knights and select the symbol each actually reveals. Name-to-symbol pairings change every match.',[...slots(3,'name',voidNames),...slots(3,'glyph'),...slots(3,'symbol',voidGlyphs.map(g=>g.id))],'recorder'),
  t('de-terminals','der-eisendrache','Safe code & terminal memory','Keep the safe’s top-to-bottom code separate from the four-screen memory boards. At each station, record the small screens from left to right, then match the requested symbol.',[...['0','1'].flatMap(n=>slots(4,`station-${n}`)),...slots(3,'safe',terminalGlyphs.map(g=>g.id)),...['0','1'].flatMap(n=>slots(4,`board-${n}`,terminalGlyphs.map(g=>g.id)))],'recorder'),
  t('zetsubou-plants','zetsubou-no-shima','Plant recipes & water locations','Choose what you need to grow. Find the right water in the photos, follow the three-round recipe, then record what you did in your match.',[f('goal','Wanted reward',Object.keys(plantRecipes)),f('planted','Planting round',null,{maxLength:3,inputmode:'numeric',pattern:'^\\d{1,3}$'}),...[0,1,2].flatMap(i=>[f(`water-${i}`,`Water round ${i+1}`,['Blue','Green','Purple','Rainbow']),f(`shot-${i}`,`KT-4 round ${i+1}`,null,{type:'check'})])]),
  t('gorod-valves','gorod-krovi','Valve solver with room photos','Find the green light and the pink cylinder. Set the other five valves as shown; leave the cylinder valve untouched. Restart the Hatchery generator if airflow expires.',[f('start','Green light room',rooms),f('end','Cylinder room',rooms)],'solver',{evaluate:'valves'}),
  t('gorod-bombs','gorod-krovi','Bomb order & location cards','Ignore SOPHIA’s initial fast shuffle. Record the six deliberate flashes in order, then defuse in exactly that order. Wrong input or timeout can end the run.',slots(6,'slot',rooms),'recorder',{evaluate:'unique-order'}),
  t('revelations-runes','revelations','Kronorium order recorder','Read your scoreboard’s four collected runes from left to right as 1–4. Record which position matches each page of the book. Use your own scoreboard, not the example photograph.',[...slots(4,'slot'),...slots(4,'rune',['1','2','3','4'])],'recorder'),
  t('revelations-collections','revelations','Egg, rune, bone & relic finder','Choose your current collection and region for exact photographs, sightlines and the required action.',[...checks(20),f('collection','Collection',['egg','rune','bone','relic']),f('region','Region',['All regions','Spawn / Shangri-La','Kino / Der Eisendrache','Origins / Mob','Verrückt','Nacht'])])
]
