import {protocolWords, chalkboardPositions, samFiles} from '../app/utils/bo6Dlc.mjs'
const reddit = map => `https://www.reddit.com/r/CODZombies/wiki/${map}/`
const illustrated = map => `https://www.codzombiesguides.com/main-quests/black-ops-6/${map}/`
const img = (map, name, alt) => ({src:`/images/bo6-${map}/${map}-${name}.webp`,alt})
const s = (name,alt) => img('shattered-veil',name,alt)
const r = (name,alt) => img('reckoning',name,alt)
const step = (id,text,quick,extra={}) => ({id,text,quick,...extra})
const phase = (id,title,steps,extra={}) => ({id,title,steps,tools:[],...extra})
const reviewNote = 'Original route synthesis reviewed on 2026-10-02 against community research and illustrated walkthroughs. Screenshots credit COD Zombies Guides and r/CODZombies contributors; game imagery belongs to Activision / Treyarch. Match clues take precedence over example images. This revision has not been verified in a complete in-game run.'

export const guides = [
  {
    id:'bo6-shattered-veil',gameId:'bo6',name:'Shattered Veil',reviewed:'2026-10-02',image:'/images/bo6-shattered-veil/shattered-veil.webp',reviewNote,
    intro:'This complete route assumes Standard mode. Repair the mansion’s elevator, obtain all three Ray Gun Mark II variants and free the spirits in three painting rituals before facing Z-Rex. Solo players can swap one Mark II between completed workbenches. The route below keeps each variant beside its matching ritual, with the Nursery cipher helper, equipment locations, optional rewards and recovery notes along the way.',
    sources:[reddit('shattered-veil'),illustrated('shattered-veil'),'https://www.reddit.com/r/CODZombies/comments/1jqgm62/shattered_veil_easter_egg_guide/','https://www.reddit.com/r/CODZombies/comments/1jqcwa8/','https://www.pcgamer.com/games/fps/call-of-duty-black-ops-6-shattered-veil-easter-egg/','https://www.dexerto.com/call-of-duty/shattered-veil-main-story-easter-egg-guide-black-ops-6-zombies-3175322/','https://gameranx.com/features/id/534161/article/black-ops-6-zombies-how-to-get-all-ray-gun-mark-ii-variants-on-shattered-veil/','https://gameranx.com/features/id/534194/article/black-ops-6-zombies-shattered-veil-main-quest-easter-egg-guide/','https://steamcommunity.com/sharedfiles/filedetails/?id=3457623351','https://detonated.com/all-shattered-veil-side-easter-eggs-in-black-ops-6-zombies-rewards-season-3/','https://codzombiesguides.com/side-quests/black-ops-6/shattered-veil/free-wunderwaffe-dg-2','https://thebasedotaku.com/guides/black-ops-6-shattered-veil-jason-blundell-fog-rolling-in-easter-egg-walkthrough/'],
    phases:[
      phase('setup','Repair the elevator & prepare your route',[
        step('sv-elevator','Open the mansion and reach Library Upstairs. Kill the trapped zombie in its corner for a Fuse. In Director’s Quarters, destroy the computer and collect its Circuit Board. Install both at the Banquet Hall elevator, finish its repair sequence and descend through Security Overlook to the Mainframe Chamber and Pack-a-Punch.','Library zombie → Fuse; Director’s computer → Circuit Board; repair Banquet Hall elevator.',{images:[s('elevator-repair','The elevator repair panel in Banquet Hall')]}),
        step('sv-gear','Keep a normal gun for Brain Rot and equip Aether Shroud for the Library ritual. Collect the free Kazimir from the corpse on the rubble in Service Tunnel. Combat Axes are available on the Garden Pond log, in Nursery under the bed and on a Security Overlook tray. Save at least two axes and one explosive for the gas canister.','Equip Aether Shroud; reserve Brain Rot, a Kazimir, Combat Axes and an explosive.',{note:'Quick Revive is in Conservatory; Juggernog in Grand Foyer; Speed Cola at Shem’s Henge; PhD Flopper in Nursery; Stamin-Up in East Foyer; Double Tap on Rear Patio; Elemental Pop at East Balcony; Death Perception in West Hallways. Visit an Arsenal for Brain Rot and weapon rarity upgrades.'})
      ],{group:'Key Features'}),
      phase('mark-ii','The free Mark II & Nursery cipher',[
        step('sv-floppy','From round 10 onward, watch Mainframe Chamber and the underground approach for the named Lab Technician zombie. Kill it and collect the glowing Floppy Disk. Insert it into the East Foyer computer near Stamin-Up, survive the enemies and read the printed fax. Record its capitalized protocol: CRAB, YETI, MOTH or WORM.','Round 10+: Lab Technician → disk → East Foyer computer → printed protocol.',{images:[s('fax-machine','Insert the disk into this East Foyer computer and read the adjacent printer')],note:'A nuke can kill the technician out of sight. Search the underground floor for its disk before assuming it never appeared.'}),
        step('sv-cipher','Find Nursery’s chalkboard beside PhD Flopper. For each protocol letter, count every letter in the same cluster, including the letter itself. Read those four counts in protocol order. Enter the result at the Service Tunnel cell keypad, defeat the released HVT Doppelghast and collect its Severed Arm. Use the arm on the Armory scanner to open the Mark II case.','Count each protocol letter’s full cluster → cell keypad → Doppelghast arm → Armory Mark II.',{images:[s('chalkboard','Nursery board example; use your current match’s clusters'),s('keypad','Enter the four-digit code beside the underground Doppelghast cell')],note:'The code changes with both the word and the chalkboard. A code from a screenshot is only an example. The helper explains each count so a transcription mistake is visible.'})
      ],{group:'Main Quest',tools:['bo6-shattered-cipher']}),
      phase('canisters','Three empty canisters',[
        step('sv-canister-crystals','With the base Mark II, shoot the blue crystals until one drops a canister. Check Conservatory’s ceiling left of Quick Revive; the wall above East Foyer’s stairs; above a mansion doorway on South West Balcony; and Service Tunnel’s ceiling before Supply Depot. Collect the actual dropped canister.','Base Mark II → four blue-crystal locations → collect one empty canister.'),
        step('sv-canister-kazimir','Throw a Kazimir on the playable floor in front of the Rear Patio window below/behind Double Tap. Its pull extracts another canister from behind the barrier. Wait for the effect to end and pick it up.','Kazimir in front of the Rear Patio window → collect extracted canister.',{images:[s('second-canister-location','Rear Patio: the canister sits behind the barrier near Double Tap')]}),
        step('sv-canister-gas','Read A or B beside the large Mainframe Chamber gas tube. At the Service Tunnel pipework, outside the barrier beside the former Doppelghast cell, throw an axe at the closed valve beside the leaking one, then at the valve feeding your recorded letter. Confirm the tube has filled with gas; destroy it with an explosive and collect the third canister.','Read tube letter → axe the closed feed valve and matching A/B valve → explode filled tube.',{images:[s('large-canister','Read the letter beside the Mainframe Chamber tube'),s('pipes','Combat Axes must hit the pipe valves precisely')],note:'Empty canisters are interchangeable. You may begin a variant after obtaining one; each completed station becomes a permanent place to swap your Mark II variant.'})
      ]),
      phase('wraith-fire','Mark II-W & the Distillery spirit',[
        step('sv-w-charge','Insert a canister in Shem’s Henge’s yellow station opposite Speed Cola. Keep the spawned Abomination alive. Bait its lightning into each of the three small stones; when a stone glows, bait a charge into it to lift it. With all three floating, protect the central siphon from Vermin. Retrieve the Explosive Canister and craft Mark II-W at Supply Depot.','Henge: beam then charge three rocks → defend siphon → Supply Depot Mark II-W.',{images:[s('glowing-rock','A stone must glow before an Abomination charge will lift it')],note:'Stand with the target rock between you and the Abomination, then sidestep its charge. If the Vermin defense fails, reactivate the station next round.'}),
        step('sv-w-portal','Take the Sconce from the cardboard box on the Banquet Hall table. Install it beside the other lamp near Grand Foyer’s Juggernog and repeat the flashing lamps through all three Simon Says rounds. Enter the revealed Distillery, activate its computer and get Mark II-W kills nearby to charge the painting. Step inside the opened portal at least once.','Banquet Hall Sconce → Juggernog lamp sequence → Distillery computer → W kills → enter painting.',{images:[s('simon-says','The two wall lamps open the hidden Distillery')]}),
        step('sv-w-flask','Find the Bell in Study: break the glass cabinets on either side of the SWAT wall-buy and check the floor beside the opposite display. Place it on Overlook’s bar at the service sign. Brain Rot a zombie beside the bar and ring the bell until it serves a drink. Collect the Metal Hip Flask, bring it into the Distillery painting and place it on the pedestal while holding Mark II-W.','Study Bell → Overlook bar → Brain Rot zombie + ring → Flask → Distillery ritual.',{images:[s('bar-bell-location','Place and ring the bell at Overlook’s bar')]}),
        step('sv-w-ritual','Defeat the ritual’s HVT Mangler. Break its returning shield with Mark II-W, then damage its exposed body. After it falls, hold interact on the Sentinel Artifact to finish the ritual. Confirm the artifact interaction before swapping variants.','W breaks the Mangler shield; defeat it and reclaim the Sentinel Artifact.',{note:'If the correct item and gun do not start a ritual, leave and advance a round before trying again. Entering the portal earlier is essential for spawning its quest items.'})
      ]),
      phase('preservation','Mark II-P & the Banquet Hall spirit',[
        step('sv-p-charge','Break white Project Janus crates until the Essence Bomb drops; the community route records the eighth destroyed crate. Take the two Reflectors from the Conservatory and South West Balcony fountains. Bomb the rubble beside Service Tunnel’s Tier III armor to open Serpent Mound. Insert a canister into its yellow station.','Janus crates → Essence Bomb; two fountain Reflectors → bomb armor-side rubble → Serpent Mound.'),
        step('sv-p-mirrors','Place Reflectors on the lower stands and melee them to route the crystal’s beam into a Doppelghast statue. Melee the source crystal to launch a pulse, then kill the awakened enemy. Re-aim for the other statues, moving a Reflector to the upper stand when needed. Finish all three, including the HVT, collect the Light Canister and craft Mark II-P in Director’s Quarters.','Reflect beam → strike source crystal → kill statue; repeat three times → Director’s Mark II-P.',{images:[s('reflector-stand','Rotate the lower Reflector to aim the beam'),s('passage-reflector-stand','The upper stand is needed to reach another statue')]}),
        step('sv-p-chalices','Activate the Banquet Hall computer and fill the painting with Mark II-P kills. Enter, take the Ritual Elixir, then pour it into the chalices on Bottlery’s wine table, Overlook’s bench right of the bar and Garden Pond’s stone bench beside the bridge. Defeat the Elder Disciple summoned at each cup.','P kills → Banquet painting → Elixir → Bottlery, Overlook and Garden Pond chalices.',{images:[s('banquet-hall-computer','Start the Preservation painting from this Banquet Hall console')]}),
        step('sv-p-safe','Return to Banquet Hall and read the three pairs of wall digits from left to right. Use that order at the West Hallways safe near Death Perception and collect the Antler Carving. Take it into the Banquet painting, place it on the pedestal, break the HVT Elder Disciple’s shield with Mark II-P and defeat it. Reclaim the Sentinel Artifact.','Wall pairs left to right → West Hallways safe → Antler → P ritual → reclaim Artifact.',{images:[s('safe-numbers','Read the three digit pairs in their wall order; this pictured code is an example')],note:'Preserve leading zeros. Record each pair separately so a two-digit safe setting does not get confused with the earlier four-digit cell code.'})
      ]),
      phase('rot-blight','Mark II-R & the Library spirit',[
        step('sv-r-seeds','Burn or explode outdoor spore growths until you have four Plant Seeds. A scream and seed drop confirm success. Check Garden Pond by the bridge and stone bench; Conservatory’s fountain; Shem’s Henge; both Motor Court crafting-table/front-entrance sides; West Balcony; South West Balcony; and Rear Patio beside its ammo box.','Burn/explode outdoor growths → collect four seeds.',{images:[s('plant','A mature outdoor growth yields a seed when destroyed with fire or explosives')]}),
        step('sv-r-charge','Insert a canister into Conservatory’s yellow machine. Plant one seed in a propagator and stay to defend it until growth completes; repeat for all four propagators. Retrieve the Toxic Canister and craft Mark II-R at Garden Pond. Activate the Library computer, fill the painting with R kills and enter its portal.','Conservatory: four seed defenses → Toxic Canister → Garden Pond R → Library portal.',{images:[s('seed-propagator','Defend each planted seed until it finishes growing')],note:'If a defense fails, look for the dropped seed and replant it; if it disappeared, harvest another. Do not leave an active plant unprotected.'}),
        step('sv-r-items','While using Aether Shroud, collect the Audio Log, Ledger and Nuclear Plant ID Badge. Search the alternatives below. During this ritual, a small Mainframe Chamber canister supplies a free Shroud charge each round; check the desk opposite Pack-a-Punch and the tray beneath a monitor near the crafting table.','Aether Shroud → collect Audio Log, Ledger and ID Badge.',{bullets:['Audio Log: Overlook desk left of the bar, or Library couch opposite the painting; check East Foyer desks as an additional community-reported spawn.','Ledger: Study desk on the right when entering from East Balcony, or East Foyer upstairs desk beside the couch and briefcase.','ID Badge: fireplaces in East Foyer beside Stamin-Up, Banquet Hall left of the elevator, or Study.'],images:[s('audio-log-overlook-location','Audio Log: Overlook desk'),s('ledger-study-location','Ledger: Study desk'),s('badge-east-foyer-location','ID Badge: East Foyer fireplace')]}),
        step('sv-r-books','Find the three glowing books opposite the Library painting. Interact with a book and look for the blue confirmation glow. Find the first correct book, then the second, then the remaining third; if a wrong input clears progress, repeat your known prefix. Collect the Inspection Report from the opened compartment. Offer it inside the Library painting, use Mark II-R on the HVT Amalgam’s shield, defeat it and reclaim the Artifact.','Three glowing books in confirmed order → Inspection Report → R ritual → reclaim Artifact.',{images:[s('white-books','The three highlighted Library books; use the confirmation glow to establish their order')]})
      ]),
      phase('z-rex','Z-Rex — four phases',[
        step('sv-boss-ready','Finish all three rituals, then resupply before the Mainframe Chamber console. Upgrade a strong normal gun and Mark II-W, fill armor, and bring healing/crowd control. Aether Shroud gives brief breathing room; a support streak is a useful emergency reserve. Interact with the console in front of S.A.M. to commit to the final encounter.','All three Artifacts reclaimed → upgrade, refill and activate S.A.M.’s console.'),
        step('sv-boss-fight','Keep ruined walls between you and Z-Rex while clearing zombies for ammunition. Shoot the glowing eyes and exposed glowing flank after it eats Toxic Zombies; use the open mouth during its vomit animation when safe. Avoid poison puddles, which slow you into its charge. Sidestep leap landings and stay away from its jaws and tail.','Use walls, avoid poison, kill adds for ammo; punish glowing eyes/flanks and safe mouth openings.',{images:[s('phase-1','Z-Rex’s glowing flank is a major damage opportunity')],note:'There are four increasingly fast phases. Do not depend on a Max Ammo between phases: keep a normal weapon to harvest the adds’ drops.'}),
        step('sv-boss-final','As it speeds up, shorten firing windows and change direction around cover rather than racing in a straight line. In the last phase, attack during feeding/vomit pauses or from the far side of the arena; spend your saved Shroud or support when movement becomes unsafe. Deplete its final health segment to trigger the ending.','Later phases: brief damage windows, move around walls, preserve an escape; finish Z-Rex.',{note:'Starting the fight after round 100 activates a harder version. Complete an ordinary clear first if your goal is the main quest.'})
      ])
    ],
    sidePhases:[
      phase('wunderwaffe','Free Wunderwaffe DG-2',[
        step('sv-side-waffe','After fully completing any painting ritual, shoot the purple-glowing laundry under Nursery’s bed. Then clear the floating objects in order: book on East Balcony’s chair, basketball on Garden Pond’s rocks opposite the workbench, and family portrait near Grand Foyer’s Juggernog. Shoot the orbiting debris/protectors, then the main object until each disappears. Descend the elevator shaft, look up and shoot the purple orb to drop the Wunderwaffe.','One ritual complete → laundry → book → basketball → portrait → elevator orb → Wunderwaffe.',{note:'Opening a painting alone is insufficient: finish its HVT and reclaim the Artifact first. Clear each object’s surrounding debris before spending ammunition on its center.'})
      ],{group:'Side Quests'}),
      phase('donut','Donut companion & bell perk',[
        step('sv-side-donut','Collect six Mister Peeks pieces: Bottlery wine rack; Garden Pond’s tree beside the bridge/Rampage Inducer; Conservatory wall in front of Quick Revive; ledge at Lower Terrace’s Shem’s Henge entrance; Library floor behind a frame; and Rear Patio bucket near the ammo box. Assemble them on Motor Court’s sandbags. The plush enters the doghouse and releases Donut, which evolves from Vermin to Parasite to Doppelghast by killing enemies.','Six Peeks parts → Motor Court sandbags → evolving Donut ally.',{note:'The companion is temporary and can die. Let it get kills if you want to see its later forms.'}),
        step('sv-side-bell','After obtaining the Metal Hip Flask, ring Overlook’s bar bell 115 times for a random perk. It uses the same bell placed for the W ritual; count interactions consistently and stop when the reward appears.','Flask obtained → 115 bar-bell rings → random perk.')
      ]),
      phase('marine','Marine SP upgrade wall',[
        step('sv-side-marine','Bring a Rare/blue or better Marine SP and Death Perception to Banquet Hall. Place the shotgun under the mounted deer heads. Watch where the upper head turns and shoot that lower head to reveal the required Field Upgrade. Equip/charge it, activate it and get kills near the heads; clear the special enemies. Retrieve your improved shotgun, advance a round and repeat.','Rare Marine SP + Death Perception → deer wall → shown Field Upgrade kills → recover weapon.',{note:'The ordinary sequence improves rarity, then Pack-a-Punch. Community references disagree on the final Pack-a-Punch tier and describe old save/reload workarounds; the guide does not promise a Tier III reward or require a glitch. Follow the upgrade the wall actually offers.'})
      ]),
      phase('laser','S.A.M. L4Z3R.EXE trap',[
        step('sv-side-laser','Boot the computer by Pack-a-Punch/Security Overlook, then test the Study, Overlook and West Hallways computers across rounds. Watch the on-screen status: a clean reboot means continue testing; a red infected screen lets you collect a floppy disk from its computer case. Put that disk in the Pack-a-Punch computer, advance a round and interact through cleaning/reboot until the S.A.M. icon appears.','Boot Pack-a-Punch PC → find infected upstairs PC → disk back → round/reboot → trap.',{note:'Use the actual status messages rather than assuming every terminal finishes in one round. Once installed, the Mainframe trap can be bought for 2,000 Essence per round.'})
      ]),
      phase('fog','Fog Rolling In — Vermin experiment',[
        step('sv-side-fog','Obtain the Wunderwaffe and a Chopper Gunner. Take the small Vermin body from Supply Depot’s open vent and place it on Mainframe Chamber’s tray. Shoot the nearby chemicals in order: small bottle (purple), blue-lid bottle group (yellow), then the larger bottle beside the small one (green). The Vermin should glow yellow.','Vermin from Supply Depot vent → tray → purple, yellow, green chemicals.'),
        step('sv-side-fog-finish','Put the treated Vermin in a microwave in Overlook or West Hallways and retrieve it when the smoke turns red. Place it in the blood on the stairs left of Pack-a-Punch, then shoot the overhead fan with the Wunderwaffe. Use the Chopper Gunner to destroy every red-smoking mansion chimney. During the resulting fog, break the spawned Aether crystals for loot before they disappear.','Microwave until red → Pack-a-Punch blood → Wunderwaffe fan → Chopper chimneys → loot crystals.')
      ]),
      phase('secrets','Sleepwalking, thermal ghost & music',[
        step('sv-side-sleep','On round 11, interact with Study’s grandfather clock until its hands spin. Lie prone on the bed in Director’s Quarters as the round changes to 12. In the dream, crouch along the footprints without waking the zombies. Take the key beside the sleeper with colored Zs and open the chest at the path’s end.','Round 11 clock → prone on bed into round 12 → quiet footprint route → key and chest.',{note:'This is a specific early-round opportunity. Plan it before advancing past round 11.'}),
        step('sv-side-ghost','From round 13, use a thermal optic to spot the ghost in exterior mansion windows. Check the front, east and west approaches; it relocates after a sighting. After three sightings, check the South West Balcony window beside Nursery. Interact with Nursery’s vanity/makeup mirror for the jumpscare and loot.','Round 13+ thermal ghost sightings → final Nursery-side window → vanity reward.'),
        step('sv-side-song','Interact with the three Mister Peeks headphones: Conservatory crate under the stairs, Banquet Hall shelf behind the elevator area, and Service Tunnel box by the burned corpse. The third triggers “Falling to Pieces.”','Headphones: Conservatory stairs, Banquet Hall shelf, Service Tunnel corpse.')
      ]),
      phase('power-ups','Eight hidden power-ups',[
        step('sv-side-powerups','Shoot each small hidden power-up model when you want its drop. Leave Max Ammo or Full Power available until useful. Fire Sale appears only after the other seven have been activated.','Shoot hidden models; the chandelier Fire Sale unlocks after the other seven.',{bullets:['Double Points — fallen wooden log beyond West Balcony. Bonus Points — opening above East Foyer stairs.','Insta-Kill — inside the elevator shaft. Full Power — inside Study’s wall/vent panel.','Max Ammo — stone balcony/railing visible from Shem’s Henge. Max Armor — behind Motor Court’s shed.','Nuke — white trailer beneath the blue tarp in Service Tunnel. Fire Sale — lower ring of Grand Foyer’s chandelier.']})
      ])
    ]
  },
  {
    id:'bo6-reckoning',gameId:'bo6',name:'Reckoning',reviewed:'2026-10-02',image:'/images/bo6-reckoning/reckoning.webp',reviewNote,
    intro:'This complete route assumes Standard mode, solo or co-op. Restore Project Janus, grow the Gorgofex, rebuild Franken-Klaus and make the Bio-Aetheric Portal safe before choosing a final opponent. Use the monitor and archive helpers for match-dependent codes, then choose the Gorgofex upgrade and boss route deliberately. T1 and T2 are tower names; the on-screen room label is your best navigation reference.',
    sources:[reddit('reckoning'),illustrated('reckoning'),'https://www.reddit.com/r/CODZombies/comments/1mmzzy3/i_made_a_fairly_easy_to_understand_guide_for_the/','https://www.reddit.com/r/CODZombies/comments/1mi7kg4/reckoning_easter_egg_hunt_general_map_discussion/','https://game8.co/games/Call-of-Duty-Black-Ops-6/archives/542978','https://steamcommunity.com/sharedfiles/filedetails/?id=3544165787','https://steamcommunity.com/sharedfiles/filedetails/?id=3764532618','https://detonated.com/all-reckoning-side-easter-eggs-and-rewards-in-black-ops-6-zombies/','https://margwa.net/reckoning','https://gameranx.com/features/id/547560/article/black-ops-6-zombies-how-to-complete-the-aetherella-easter-egg-on-reckoning/','https://www.codzombieguides.com/reckoning','https://callofduty.fandom.com/wiki/Reckoning_(Zombies)'],
    phases:[
      phase('setup','Power, Pack-a-Punch & early collection',[
        step('rec-power','Follow the opening objectives through the two towers to T1 Executive Office. Interact with the snow globe to open the route to T2 Sublevel 10. Restart its Particle Accelerator, then destroy every purple crystal around the chamber until Pack-a-Punch appears. Scan above and below the walkways for the last crystal.','Executive Office snow globe → Sublevel 10 accelerator → break all crystals → Pack-a-Punch.'),
        step('rec-early','In the first Kommando Klaus special round, shoot robot arms and pick up the quest arm that drops; you need both sides eventually. Keep an explosive for the later smoke detector and buy Melee Macchiato before the brain carry. At spawn, you can melee the mop bucket under a ceiling sprinkler now, saving work later.','Save dropped Klaus arms; keep an explosive; plan Melee Macchiato and the spawn bucket.',{note:'Useful landmarks: Quick Revive in T1 Reception; Juggernog in Executive Suite; Melee Macchiato in Quantum Computing Core; Speed Cola in Quantum Computing Lab; Deadshot in Mutant Research Lab; PhD in its Test Area; Double Tap and Wunderfizz in T2 Android Assembly; Stamin-Up in Dark Entity Containment; Vulture Aid in Sublevel 10.'})
      ],{group:'Key Features'}),
      phase('fowler','DNA, Fowler & Teleportation Lab access',[
        step('rec-dna','After Pack-a-Punch opens, kill the named Geneticist in T1 Mutant Research Lab and take its Keycard. Open the refrigerator in the adjacent Mutant Research Test Area and collect the DNA vial. Take the Syringe from the genome-sequencer/centrifuge in Mutant Research Lab.','Geneticist keycard → Test Area fridge DNA; take the Lab’s syringe.',{images:[r('dna-vial','The refrigerator contains the DNA vial'),r('syringe-centrifuge','Take and later replace the Syringe at this machine')]}),
        step('rec-fowler','At Sublevel 10, jump into the accelerator beam and collide with the suspended body to knock it down. Interact with the fallen body to draw blood. Return the filled Syringe to the Lab machine and defeat Fowler’s Mangler plus the enemies released from the tanks. Take the special Fowler Mutant Injection.','Beam knocks body down → draw blood → Syringe back → defeat Fowler → special Injection.'),
        step('rec-scan','Carry the Injection to the upper scanner in T2 Dark Entity Containment. Activate the scan and transform in front of it so it recognizes Fowler. Use the newly opened teleporter to reach T2 Teleportation Lab.','Fowler Injection at Containment scanner → access Teleportation Lab.',{images:[r('scanner','Use Fowler’s transformation at this scanner')],note:'This requires Fowler’s quest Injection. If the transformation expires or the scan fails, buy another at the genome sequencer for 1,500 Salvage and return to the scanner before activating it.'})
      ],{group:'Main Quest'}),
      phase('gorgofex','Grow the Gorgofex',[
        step('rec-element','Read the flashing word beside Deadshot Daiquiri first, then the monitor behind Richtofen’s family tank if it also has a word. Combine their first letters into an element symbol. Find its atomic number on the Test Area periodic table and enter it as three digits at the upstairs Bioweapons Lab keypad: Cu is 029.','Deadshot initial + family-tank initial → element atomic number → three-digit keypad.',{note:'Sometimes only the first monitor has a word. Both readings must come from the same round because the words change. Use the atomic number, not the decimal atomic mass.'}),
        step('rec-cyst','Inside Bioweapons Lab, feed the exposed Cyst three weakened Vermin, then three weakened zombies. Bring them close enough for its tendrils to absorb them; confirm each absorption instead of killing enemies far from the container. Pick up the Cyst and stand beneath the three yellow Aetheric Flora around Quantum Computing Core and Lab until each drains.','Cyst absorbs 3 Vermin then 3 zombies → collect → drain 3 yellow Flora.',{images:[r('cyst','The Cyst absorbs the ordered enemy types at this container'),r('aetheric-flora','Stand under each glowing yellow Flora until it drains')],note:'Fowler’s Elder Disciple can help provide Vermin. Watch your health under Flora: the draining plants spill damaging acid.'}),
        step('rec-surge','In T2 Dark Entity Containment, locate the green-text power-surge computer and activate it, then promptly activate the other three matching terminals. When the floor panel in front of the Forsaken chamber is electrified, break the spawned Uber Klaus’s shoulder generators and lure it onto that panel alive.','Activate four surge terminals quickly → break Uber Klaus shoulders → lure onto energized panel.',{images:[r('charged-panel','Lure the weakened Uber Klaus over the active floor panel')],note:'Find all terminal positions before starting. If the timed sequence dissipates, restart it. Do not kill the original Uber Klaus before the transfer.'}),
        step('rec-forge','Defeat the Forsaken-controlled robot and its released core. Interact with the remaining energy orb while carrying the charged Cyst to create the Gorgofex. The base weapon is enough for the portal tasks; choose one of the optional C/N upgrades below if you want to Pack-a-Punch it.','Defeat possessed robot and core → Cyst into orb → Gorgofex.',{links:[{href:'#details-gorgofex-upgrades',label:'Choose a Gorgofex upgrade'}]})
      ],{tools:['bo6-reckoning-element']}),
      phase('klaus','Build Franken-Klaus & let him work',[
        step('rec-parts','Collect a left and right arm by shooting Kommando Klaus arms. The first special round supplies only one; continue collecting from later robots. Find both legs in Android Assembly: check the shelf near the line, scrap pile, floor by shelving and behind the broken TV/mirror. Install all four limbs on the suspended Franken-Klaus.','Two robot arms + two Android Assembly legs → install on hanging Franken-Klaus.',{images:[r('klaus-leg-behind-broken-tv','Leg spawn behind the broken display'),r('klaus-leg-on-pile-of-scrap','Leg spawn atop the scrap pile'),r('klaus-leg-on-the-ground-neare-shelves','Leg spawn on the floor by shelving'),r('klaus-leg-on-the-shelf','Leg spawn on the assembly shelf')]}),
        step('rec-klaus-power','Bait an Uber Klaus electrical attack into the suspended body to energize it. If available earlier, the Gorgofex quest’s robot can do this before its Forsaken transfer; otherwise use a later Uber Klaus. Franken-Klaus works at his first terminal until the next round. Escort him toward Dark Entity Containment; activate the S.A.M. Trial machine beneath the Forsaken chamber and complete its nearby-kills trial. Then escort him to the Teleportation Lab terminal.','Uber Klaus electricity → Franken-Klaus terminal → next round → finish S.A.M. trial → Teleportation Lab.',{images:[r('fully-assembled-franken-klaus','The assembled body must also receive an electrical attack')],note:'If the S.A.M. machine is absent, wait for its spawn instead of abandoning the escort. His pauses are part of the sequence; complete the trial rather than only activating its screen.'})
      ]),
      phase('files','Four S.A.M. files → chronological code',[
        step('rec-files','Read the four S.A.M. folders that appear across Executive Suite, Director’s Office and Teleportation Lab. Check coffee tables and desks upstairs, the credenza beside the lamp, and the Lab’s trolley and terminals. Each folder shows one belonging, a file number and a date. Sort only your four documents from oldest to newest; their file numbers form the code.','Find four folders → sort dates oldest to newest → read their four file numbers.'),
        step('rec-file-code','Enter the four-digit result into Teleportation Lab’s computer and wait for access granted and the facility reboot. Use the visual helper to select actual found documents and verify the chronological sequence.','Enter chronological file code at Teleportation Lab computer.',{note:'Dates use month/day/year. The complete reference sequence is Badge 6, Collar 1, Scarf 3, Watch 4, Goggles 5, Katana 2; your match uses only four of them.'})
      ],{tools:['bo6-reckoning-files']}),
      phase('brain','Timed brain delivery & portal crystal removal',[
        step('rec-brain','With Melee Macchiato, punch the metal brain container in Quantum Computing Core. Rehearse the route to the Teleportation Lab first, then lift the purple brain and move immediately. Install it in the receiving chamber beside Franken-Klaus. Carrying it disables weapons and the delivery is timed.','Melee Macchiato brain container → carry quickly to chamber beside Klaus.',{images:[r('brain','Punch this Quantum Computing Core container to release the brain')],note:'Use the already opened tower route and let a teammate clear ahead. If the carry fails, return to the original container for another attempt.'}),
        step('rec-orb','At Sublevel 10, press the red boost button and kill five blue Quantum Vermin with the Gorgofex during the accelerator overcharge. Interact with the resulting blue orb above the terminal to empower the weapon. Carry that charge to Teleportation Lab and fire one charged shot at the portal’s blocking crystals.','Boost accelerator → Gorgofex kills on 5 Quantum Vermin → absorb orb → charged portal shot.',{note:'Do not fire away the special charge on the journey. Removing the crystals does not make the portal safe: wait until the head, vacuum captures and lockdown are complete before entering.'})
      ]),
      phase('head','Cleanse & feed Mortimer’s head',[
        step('rec-head','In Quantum Computing Core, shoot a charged Gorgofex shot into the high square opening opposite Melee Macchiato, right of the C.A.S.T.E.R. turret. Collect the fallen Fungal Head. Find a mop bucket in Reception, Executive Suite or Android Assembly, melee it under its ceiling sprinkler and trigger the nearby smoke detector with an explosive.','Charged shot at Core wall opening → head → bucket under sprinkler → explosive smoke detector.',{images:[r('hole-in-the-wall','Aim a charged shot into this high opening'),r('mop-bucket-correct-position','Position the bucket beneath the sprinkler'),r('smoke-detector','Trigger the nearby smoke detector to fill the bucket')]}),
        step('rec-head-feed','Put the head in the filled bucket to wash it. Kill enemies near it until its eyes and collection effect turn purple; carrying it also lets you gather souls but slows your movement and attracts a damaging shadow. Bring the fully charged head to Teleportation Lab and interact with the center of the portal to install it. Confirm fungal growth around the frame.','Wash head → collect souls until purple → install in portal → confirm fungal growth.',{note:'Keep collecting if the head is not fully charged. Do not walk through an unfinished portal: premature travel can kill you or drop you into a dangerous fall.'})
      ]),
      phase('portal','Four vacuum captures & the last lockdown',[
        step('rec-vacuum','After the brain delivery unlocks the blue Janus containers, take their special Vacuum-Seal Devices. Containers are in Reception, Mutant Research Test Area, Android Assembly, Dark Entity Containment and Teleportation Lab. Find a floating purple-glowing object, throw a device at it and retrieve the captured result. Repeat with fresh devices until four captures are confirmed.','Janus containers → special devices → capture and collect 4 floating purple objects.',{images:[r('vacuum-seal-device','The quest’s Vacuum-Seal Device comes from a blue Janus box'),r('purple-glowing-item','A floating purple object is a capture target')],note:'Search Reception, outside Quantum Computing Lab, Mutant Research and Director’s Office. Ordinary Kazimirs are not substitutes for these compact quest devices.'}),
        step('rec-lockdown','Install the four captures at the console facing the Bio-Aetheric Portal, then interact again to begin the defense. Search the room for the currently red lever, turn it green and move to the next newly red lever. Continue until the lockdown’s completion flash and the enemies clear.','Insert 4 captures → start defense → turn each active red lever green until complete.',{images:[r('portal-lockdown-red-switch','Only operate the currently red switch; the sequence advances around the room')],note:'Published guides disagree on a fixed lever count. Follow the active lights and confirmed completion instead of stopping after a memorized number.'}),
        step('rec-final-prep','Finish purchases before taking the now-safe portal to Tower 3; this trip has no return. Bring strong upgraded weapons, Tier III armor, useful perks, Self-Revive, healing and ammunition. A precision weapon helps against distant Richtofen; the Gorgofex helps clear crowds. Decide your alliance: help Richtofen to fight S.A.M.; help S.A.M. to fight Richtofen.','Resupply before Tower 3. Help Richtofen → fight S.A.M.; help S.A.M. → fight Richtofen.',{note:'If Richtofen keeps directing you back to Mutant Research instead of admitting you, collect the DNA vial from the Geneticist-keycard refrigerator. It is required for the final encounter.'})
      ]),
      phase('tower-three','Tower 3 ascent & both boss endings',[
        step('rec-ascent','Enter Tower 3, attune the Sentinel Artifact at the lift and select your ally. At Vault 1, charge three LTG canisters with nearby kills; purple-eyed enemies are in range. At Vault 2, shoot every Aether crystal. Return to the lift after each objective to reach the roof. The first stop has an Arsenal; the second has Wunderfizz and crafting.','Attune and choose → Vault 1 three soul canisters → Vault 2 all crystals → roof.'),
        step('rec-sam','Against S.A.M., stay near cover and evade purple barrages, the red tracking beam and spinning electrical volleys. After the red beam, shoot the four exposed glowing vents around her eye, then attack the red central eye. When she leaves and starts a S.A.M. Trial, prioritize its stated task and reach Legendary to earn a perk rather than a penalty. Repeat the vulnerability windows until she is defeated.','S.A.M.: dodge beam → break glowing vents → red eye damage; complete intermission trials.',{images:[r('sam-exposed-weak-points','S.A.M.’s opened vents surround the central eye')],note:'Read each trial instead of continuing ordinary kills. Lower rewards can impose ammo or weapon penalties. Replenish during intermissions and stay mobile when her later volleys travel around the arena.'}),
        step('rec-richtofen','Against Uber Richtofen, break shoulder generators and focus the exposed head/core while clearing robot adds. Keep clear of his leap and electrical attacks. After the mech breaks, he fights from a jetpack with the Wunderwaffe. Use cover, sidestep bolts and leave marked missile zones immediately. Smoke or Aether Shroud creates brief firing windows; watch his aerial attacks instead of standing still to reload.','Richtofen: shoulders → exposed core/head; then cover, smoke/Shroud and dodge jetpack attacks.',{images:[r('uber-richtofen-weak-points','First phase: shoulder generators open the damage opportunity')],note:'Both routes complete the main quest. Do not build your plan around a Chopper Gunner: these bosses can destroy it. Round 100+ also has a harder encounter variant.'})
      ])
    ],
    sidePhases:[
      phase('gorgofex-upgrades','Choose Gorgofex C or N',[
        step('rec-upgrade-choice','With Gorgofex, speak through Blanchard’s Executive Office door. Choose your quest before starting: beginning one upgrade locks the other quest for this match. Either upgrade permits Pack-a-Punch. This choice is separate from the final S.A.M./Richtofen boss alliance.','Speak to Blanchard; choose C or N before committing. Both enable Pack-a-Punch.'),
        step('rec-upgrade-c','For Corpsloder, press Reception’s red button and protect Maintenance Klaus until it shuts off an elevator. Use the working shaft to reach Quantum Computing Core. Jump into the disabled shaft with your parachute and interact with all three red buttons on the descent. Back at Core, kill the blue-effect zombies using Gorgofex, then interact with Panos to receive Gorgofex C.','C: Reception defense → 3 disabled-shaft buttons → Gorgofex blue-zombie kills → Panos.',{images:[r('gorgofex-c-elevator-buttons','Use the parachute to reach each red shaft button')]}),
        step('rec-upgrade-n','For Necrodystonia, collect the Strauss Counter from Quantum Computing Core’s terminal. Follow its rising reading to a Life Drain vial; out of range means search the other tower. Shoot the out-of-bounds vial with a charged Gorgofex shot and retrieve it. Also collect Clean Hood in Bioweapons Lab, PC Fan left of Containment’s Arsenal and Tubing outside Quantum Computing Lab.','N: Counter finds vial → charged shot; collect Hood, Fan and Tubing.',{images:[r('gorgofex-n-life-drain-serum','The Strauss Counter leads to a vial outside the playable floor')]}),
        step('rec-upgrade-n-finish','Build the Essence Extractor beside Blanchard’s door and insert the vial. Survive the approximately 90-second lockdown, collect Blanchard’s Life Essence and immediately carry it to Bioweapons Lab. Place the Gorgofex and essence in the left hood and hold interact to infuse Gorgofex N.','Build extractor → survive defense → Life Essence to Bioweapons hood → infuse N.',{note:'The essence carry drains health. Clear the route beforehand and avoid losing the vial; if you set it down, mark its exact position and recover it before leaving.'})
      ],{group:'Side Quests'}),
      phase('aether-blade','Paintings & the Aether Blade safe',[
        step('rec-paintings','Return three loose paintings to the wall beside Director’s Office’s Arsenal. Carry one at a time: Reception’s small red teleporter side room (right wall slot), Sublevel 10 upper walkway near the small stairs/crate (middle), and Android Assembly’s outer balcony pillar beside the janitor cart (left). Each placement drops 500 Essence.','Return Reception, Sublevel 10 and Assembly paintings → 1,500 total Essence.'),
        step('rec-blade','After Pack-a-Punch, drive an ARC-XD through the small wall opening beneath the Forsaken chamber in Dark Entity Containment. Follow it to the hidden crystal and detonate. Shoot the crystals that appear around the chamber and collect the Safe Key from the last. With all paintings returned, deploy Mister Peeks Field Upgrade in front of the portrait behind Richtofen’s desk. Interact with the exposed safe, defeat the ambush and HVT Elder Disciple, then open it with the key for the Aether Blade and intel.','ARC-XD hidden crystal → chamber crystals/key → Peeks at portrait → safe ambush → Aether Blade.',{note:'The key may not appear in the inventory display. Use the quest pickup confirmation rather than discarding the attempt.'})
      ]),
      phase('companions','Aetherella & upgraded C.A.S.T.E.R. turrets',[
        step('rec-aetherella','At Reception’s bathroom spawn barrier beside Rampage Inducer, use an emote-wheel spray on the nearest/left stall door. Fire a charged Gorgofex shot at the exposed Aetherella figure. Lead it to Sublevel 10 and jump into the accelerator beam; exit, then enter again and collide with the figure in the beam. It follows you and fires lasers for a limited time.','Spray bathroom stall → charged Gorgofex toy → beam twice, collide with figure → laser ally.',{note:'Later community references describe recharging it when the toy reappears in the beam. Look for the returned figure rather than assuming a fixed round duration.'}),
        step('rec-turrets','Use a C.A.S.T.E.R. turret until its memory-full announcement. Kill the marked zombie for its Hard Drive, place the drive in Quantum Computing Core’s brain-container device and defend the upload. Repeat the process to raise turret level from 1.0 through 4.0. Each level increases effectiveness and activation price.','Turret kills → memory-full zombie drive → Core device defense → repeat upgrades.')
      ]),
      phase('free-rewards','Perks, Self-Revive & shooting rewards',[
        step('rec-rings','Look down Executive Suite’s central opening and shoot Mister Peeks on the structure below. Interact when he rises to your floor, then parachute after him through every ring down to Reception. Completing the descent awards a random perk.','Shoot Peeks below Executive Suite → interact → parachute every ring → perk.'),
        step('rec-accelerator-perk','During the accelerator boost event, keep killing after the five quest Vermin. Quantum Vermin score 200 and ordinary zombies 10; push the displayed score beyond 2,000 before the timer ends for a random perk.','Boost event: Quantum Vermin 200, zombies 10; exceed 2,000 before time expires.'),
        step('rec-self-revive','At the Director’s Office wall ball rack, shoot the TOP yellow 1, then the other yellow 1 directly below, then the red 5. Collect the Self-Revive from the pool table. Shooting the lower 1 first can lock this reward for the match. Shoot the separate table balls for a small Essence bonus.','Wall rack: TOP 1 → LOWER 1 → 5; collect Self-Revive.',{note:'The two 1 balls are distinct targets. The reward also triggers the “Samantha’s Soul” remix.'}),
        step('rec-deadshot','Outside Mutant Research Test Area, stand beside the white crates near the family tanks and aim at the training dummies by the launcher until you hear a confirmation. Turn toward the crane and shoot all five revealed cans without missing to receive Deadshot Daiquiri.','Aim at Test Area dummies → crane cans → five accurate hits → Deadshot.'),
        step('rec-shooting','After opening Pack-a-Punch, stand on Reception’s floor logo and shoot the Janus logo on the broken TV. Complete the short target sets for an Ammo Mod, then on later rounds an Aether Tool and an Aetherium Crystal. Shoot the final target on the desk to release each reward. One gallery can be completed per round; retry a failed gallery next round. Later rounds improve the upgrade rewards.','Reception floor logo → shoot TV logo → timed targets; repeat over 3 rounds.'),
        step('rec-basketball','In Sublevel 10, look up from the GobbleGum-machine side for a basketball lodged near the ceiling. Shoot it down during low gravity, then nudge/kick it up the steps into the zombie-spawn opening near that machine, beneath the accelerator-control area. Shoot the ball once it is inside to claim an Aetherium Crystal.','Low gravity: shoot ceiling basketball down → kick into GobbleGum-side opening → shoot for crystal.',{note:'This later-discovered secret is separate from Reception’s three-round shooting gallery. Make small adjustments behind the ball so it travels toward the opening.'}),
        step('rec-kazimirs','Throw an LT-53 Kazimir toward the central sphere of Executive Suite’s Project Janus statue from the opposite balcony; aim slightly above the large circle, near its upward spike. When the sphere glows purple, kill enemies close to the statue until it drops a replacement Kazimir. Repeat on later rounds when you need another.','Kazimir into Janus sphere → purple soul collector → nearby kills → replacement Kazimir.',{note:'The first throw costs a Kazimir. Confirm the purple glow before spending a horde, and expect later rounds to require more souls.'})
      ]),
      phase('loot-music','Trash loot, vending, songs & small secrets',[
        step('rec-trash','Search bins in Reception, Executive Suite and Director’s Office. Four give loot; after finding those four, return to the gold-glowing spawn bin for its larger reward and “I’m a Real Girl” intel. Melee Android Assembly’s vending machine opposite Franken-Klaus for extra loot; a Melee Macchiato punch gives a larger payout but breaks it.','Loot bins until spawn bin turns gold; Assembly vending machine gives melee loot.'),
        step('rec-song','Activate Mister Peeks headphones in Mutant Research Lab’s dead zombie hand, on the corpse beneath the Forsaken chamber in Dark Entity Containment, and inside the Director’s Office cupboard. All three trigger “Remember Us.” After Pack-a-Punch, run Reception’s metal detectors left → right → middle twice for “Samantha’s Peace”; repeat the phrase if the cue has not fired.','Headphones in Lab, Containment and Office; detectors L–R–M twice for second song.'),
        step('rec-cosmetics','For the chicken-bucket hat, grenade the bucket in Executive Office, collect all six scattered wings and interact with the fallen bucket. For Samuel’s jumpscare, use a magnified scope from Executive Suite’s launcher-side opening and aim at the distant picnic blanket beneath the hilltop trees.','Office bucket grenade → 6 wings → bucket hat; scope the distant picnic blanket for jumpscare.')
      ]),
      phase('power-ups','Eight hidden power-ups',[
        step('rec-powerups','Shoot the small power-up models to spawn their rewards. Save useful drops until needed. The Fire Sale model only appears after all other seven have been activated.','Find and shoot 7 power-up models; then claim Reception’s Fire Sale.',{bullets:['Max Armor — rightmost armored vehicle’s turret outside Reception. Full Power — above Mutant Research Lab when looking from Deadshot.','Double Points — rack above Quantum Computing Core’s central structure, viewed from its turret. Bonus Points — distant radio tower above Executive Suite’s launcher view.','Max Ammo — cabinet top near Android Assembly’s ceiling, left of its launcher toward T1. Insta-Kill — servers inside Containment’s Employees Only window, right after the elevator.','Nuke — above Sublevel 10’s blue pipe left of the crafting table. Fire Sale — Reception’s burning window left of Quick Revive.']})
      ])
    ]
  }
]

const field = (id,label,extra={})=>({id,label,...extra})
export const tools = [
  {id:'bo6-shattered-cipher',map:'bo6-shattered-veil',name:'Nursery cipher decoder',kind:'solver',custom:true,version:1,help:'Choose the printed protocol and copy its complete letter clusters from your current board. See every letter-to-count conversion before entering the cell code.',reference:reddit('shattered-veil'),fields:[field('word','Fax protocol',{options:protocolWords}),...chalkboardPositions.map((name,i)=>field(`group-${i}`,`${name} cluster`,{maxLength:20}))]},
  {id:'bo6-reckoning-element',map:'bo6-reckoning',name:'Gorgofex monitor code',kind:'solver',custom:true,version:1,help:'Record the ordered monitor words, or just their initials. Confirm whether one or two monitors are active; the helper returns the atomic number with its required leading zeros.',reference:reddit('reckoning'),fields:[field('screens','Active word monitors',{options:['One word','Two words']}),field('first','Deadshot monitor',{maxLength:30}),field('second','Family-tank monitor',{maxLength:30})]},
  {id:'bo6-reckoning-files',map:'bo6-reckoning',name:'S.A.M. archive order',kind:'solver',custom:true,version:1,help:'Select exactly the four belongings in this match’s folders. See their real reference photos, chronological order and the resulting four-digit computer code.',reference:reddit('reckoning'),fields:samFiles.map(row=>field(row.id,row.name,{type:'check'}))}
]
