import {guide,phase,step,photos,collection,reddit,kennedy} from './chronicles-common.mjs'
const a='ascension',s='shangri-la'
export const jungleGuides=[
 guide(a,'Ascension','A complete Chronicles route through power, the landers, Casimir Mechanism and the optional Samantha hunt. The main quest requires four players in an unmodified game. Solo players can still unlock Pack-a-Punch, earn monkey-round rewards and complete the side secrets.','power/power_switch',[
  phase('setup','Power, landers and Pack-a-Punch',[
   step('setup-1','Climb from spawn to the upper power platform and flip the switch. Colour returns to the map. Buy survival perks, then locate the three lunar landers at Widow’s Wine, Stamin-Up and Speed Cola. BO1 references call Widow’s Wine “PhD Flopper”; use the same physical location in BO3.','Turn on power and find the three landers.',{images:photos(a,'power/power_switch','pap/station_phd','pap/station_staminup','pap/station_speed_cola')}),
   step('setup-2','At each of the three outer stations, call the lander and ride it back to spawn. Once the launch panel shows all routes complete, press the launch button beside power. Wait for the rocket to leave, enter its launch area and use Pack-a-Punch in the side room below the pad.','Ride all three landers to spawn, launch the rocket, enter Pack-a-Punch.',{images:photos(a,'pap/lander_control_panel','pap/rocket_launch_button','pap/pap_room')})
  ],{group:'Key Features'}),
  phase('nodes','Casimir Mechanism: activate the first three nodes',[
   step('nodes-1','Prepare four players, Gersh Devices, Matryoshka Dolls, a Thundergun and a Ray Gun or Ray Gun Mark II. Pack-a-Punch the damage weapons before the finale. Throw a Gersh beside the sparking generator beyond the Widow’s Wine lander so it is sucked in. Then activate the small television under the stairs in the flooded area toward Stamin-Up; its eye lights up.','Gersh the generator, then activate the Stamin-Up television.',{images:photos(a,'main_ee/gersh_generator','main_ee/tv')}),
   step('nodes-2','During a Space Monkey round, station one player at each button beside Jugger-Nog, Widow’s Wine, Speed Cola and Stamin-Up. On a shared countdown, press all four together. Listen for the completion cue before leaving. These buttons are a quest step, separate from defending perk machines.','Press the four perk-area buttons together during monkeys.',{images:photos(a,'main_ee/jug_button','main_ee/phd_button','main_ee/speed_cola_button','main_ee/staminup_button')}),
   step('nodes-3','All four players stand within the circular pressure plate under the rocket. Remain inside for about two minutes while the wall clock completes a full turn. You may shoot and move within the circle; stepping off interrupts the attempt. The reward/cue confirms the node is finished.','Keep all four players on the rocket-pad plate until the clock finishes.',{images:photos(a,'main_ee/pressure_plate','main_ee/clock')})
  ],{group:'Main Quest'}),
  phase('luna','Spell LUNA with the lander',[
   step('luna-1','Choose one rider; teammates call the lander from the destination controls. Collect the floating letters with these four journeys in order: Spawn → Stamin-Up (L), Stamin-Up → Spawn (U), Spawn → Speed Cola (N), Speed Cola → Stamin-Up (A). The rider stays aboard for each letter.','Ride Spawn → Stamin → Spawn → Speed → Stamin.',{images:photos(a,'main_ee/letter_in_sky'),bullets:['L: a teammate at Stamin-Up calls the rider from Spawn.','U: a teammate at Spawn calls the rider back.','N: a teammate at Speed Cola calls the rider from Spawn.','A: a teammate at Stamin-Up calls the rider from Speed Cola.']}),
   step('luna-2','Check the crashed rocket module near Stamin-Up after the letters. All four indicators should now be lit. If one is missing, review the corresponding node before spending your finale ammunition.','Confirm all four module indicators.',{images:photos(a,'main_ee/rocket_module')})
  ]),
  phase('orb','Free Gersh',[
   step('orb-1','Find the white light on the ground near the crashed rocket module. Throw a Gersh Device onto it, then have the team fire the upgraded Thundergun and upgraded Ray Gun/Mark II into the trapped light while detonating Matryoshka Dolls there. Coordinate the damage inside the same Gersh window.','Gersh the white light and concentrate upgraded weapons plus Matryoshkas.',{images:photos(a,'main_ee/white_orb')}),
   step('orb-2','If Gersh says he needs more power, repeat with fresh equipment. When the light rises away and his dialogue confirms freedom, the quest is complete. In Chronicles the team receives the perk reward as well as the temporary Death Machines.','Repeat if needed until Gersh is freed.')
  ])
 ],[
  phase('monkeys','Space Monkeys and the launch bonus',[
   step('monkeys-perks','After perks have been purchased, Space Monkey rounds can attack those machines. Defend them before the monkeys reach them. Finishing a monkey round without any machine being touched earns a random perk bottle along with the Max Ammo; merely preventing a perk loss is not enough.','Defend every owned perk machine without a touch.'),
   step('rocket-bonus','When launching the rocket for Pack-a-Punch, destroy it with sufficient weapon damage while it rises to reveal a Double Points pickup at the launch area. This is an optional launch bonus, not a required quest node.','Destroy the launching rocket for Double Points.')
  ],{group:'Side Quests'}),
  phase('samantha','Samantha: capture three dolls, shoot five in order',[
   step('ascension-sam-capture','Unlock Pack-a-Punch and obtain Gersh Devices. Use a Gersh to capture each of three distant dolls: the pipe beneath the Pack-a-Punch walkway, the railing beside Widow’s Wine, and the high beam near Stamin-Up. Use the close and wide photographs in the finder to line up the throws.','Capture the three distant dolls with Gersh Devices.'),
   step('ascension-sam-start','Interact with the doll in the bush behind the Mystery Box spot in the Pack-a-Punch area. Shoot the next five dolls in the fixed order shown in the finder: Kuda debris, Wunderfizz barrel, the other Stamin-Up beam, ground in front of the rocket module, then directly above that spot.','Start at the bush and follow the five target order.',{images:photos(a,'free_max_ammo/doll_bush_zoomed_out')}),
   step('ascension-sam-finish','Return to the bush doll and interact again for a Max Ammo and Samantha’s Sorrow. If a failed timer stops the sequence, restart at that doll.','Return to the bush for the reward.')
  ],{tools:['bo3-ascension-dolls']}),
  phase('music','Abracadavre and the character dolls',[
   step('ascension-song','Interact with three teddy bears: upstairs in spawn by the RK5, on the wall beside the Speed Cola lander hallway, and behind the fence left of the Stamin-Up lander. The third starts Abracadavre.','Activate the three Abracadavre bears.',{images:collection(a,'song_ee/bear_')}),
   step('ascension-characters','Interact with the four small character dolls for character dialogue. Find Takeo near Widow’s Wine, Richtofen on the desk above Jugger-Nog, Nikolai beside Speed Cola and Dempsey near the Trip Mine wall buy by Stamin-Up.','Listen to the four character dolls.',{images:collection(a,'ultimis_dolls/')})
  ])
 ],[reddit(a),kennedy(a)+'?version=bo3','https://www.codzombieguides.com/ascension-remastered']),
 guide(s,'Shangri-La','A four-player time-travel quest built around communication, matching symbols and careful timing. This Chronicles guide explains every crystal, the Focusing Stone and the side rewards. The tile helper stores your match’s observations; the photographed gong notes are useful for both the main quest and Samantha.','power/power',[
  phase('setup','Power, Pack-a-Punch and the eclipse',[
   step('setup-1','Reach the underground power room and activate both switches. For Pack-a-Punch, find the raised pressure plates in front of the four-section statues: Spawn, bottom of Rope Bridge, between the power switches and the Minecart tunnel. One plate is required per player; everyone stands on their raised plate simultaneously to stop the rotating statue sections and raise the spawn stairs. Upgrade promptly before the stairs close.','Activate both power switches; stand on the raised Pack-a-Punch plates.',{images:photos(s,'power/power','pap/statue_spawn','pap/statue_rope_bridge','pap/statue_power','pap/statue_tunnel','pap/pap_stairs')}),
   step('setup-2','The main quest needs four players. Press the four small buttons around Quick Revive together to enter an eclipse. Start a fresh eclipse for each crystal trial below. A successful trial returns daylight; a failed or expired attempt can be retried with the buttons. Obtain the 31-79 JGb215 (“Baby Gun”) from the Box and keep it for the shrinking steps.','Use four players to trigger an eclipse before each trial.',{images:photos(s,'main_ee/buttons_to_enter_eclipse','main_ee/horizontal_pillar')})
  ],{group:'Key Features'}),
  phase('tiles','Crystal 1: match the twelve tile pairs',[
   step('tiles-1','During the eclipse, press the button on the brick structure by the Pharo/Minecart side. Twelve floor tiles appear here and twelve near Rope Bridge. Each tile reveals its symbol when stood on; every symbol has one matching partner on the other side. Assign a player to each side and keep the other two off the tiles.','Activate the brick button and assign one caller per tile area.',{images:photos(s,'main_ee/button_mpl','main_ee/tiles_minecart','main_ee/tiles_rope_bridge')}),
   step('tiles-2','Explore one side at a time while the other player stands clear. Agree on a landmark name for each tile and record the revealed symbol with the helper. Once a pair is found, stand on both matching tiles together to remove them. A mismatched pair resets the tiles. Repeat until all twelve pairs disappear and daylight returns.','Discover and stand on all twelve matching pairs.',{images:photos(s,'main_ee/shangri_la_symbols')})
  ],{group:'Main Quest',tools:['bo3-shang-tiles']}),
  phase('trials','Crystals 2–4: slide, shrinking ball and gas',[
   step('trials-1','Enter an eclipse. Put three players on the metal grate at the bottom of the water slide. The fourth slides down and holds interact at the lever on the right-hand wall on the way past. Keep the three players on the grate until the success cue returns daylight.','Three wait on the grate; the fourth uses the slide lever.',{images:photos(s,'main_ee/slide_grate','main_ee/water_slide_lever')}),
   step('trials-2','Enter an eclipse. Use an explosive to knock down the crystal above the water slide, shoot it with the Baby Gun to shrink it, and melee it down the slide. Follow it to the geyser at the bottom and stand there to launch it into place.','Explode, shrink and knife the slide crystal into the geyser.',{images:photos(s,'main_ee/ball_above_slide','main_ee/ball_in_geyser')}),
   step('trials-3','Enter an eclipse and turn the Minecart-side tunnel valve four times. Escort a live Napalm Zombie through the three leaking gas pipes: beside the valve, above the Box location near Kuda, and above the KN-44 underground. Stay far enough away that it does not detonate prematurely. Once all three leaks burn, pull the lever beside the valve.','Turn the valve four times; ignite all three leaks with a Napalm Zombie.',{images:photos(s,'main_ee/valve','main_ee/gas_pipe_valve','main_ee/gas_pipe_mystery_box','main_ee/gas_pipe_m16','main_ee/gas_lever')})
  ]),
  phase('holes','Crystal 5: plug the four tunnel holes',[
   step('holes-mines','Buy Trip Mines from the power-room wall buy (Spikemores in BO1 guides). During an eclipse, place and detonate mines directly in front of each of the four holes along the left wall of the tunnel descending toward the Waterfall. Lure zombies over the mines; check the hole is visibly plugged before moving on.','Plug all four tunnel holes with detonated Trip Mines.',{images:photos(s,'main_ee/spikemore','main_ee/hole')}),
   step('holes-brick','When all four holes are plugged, press the protruding brick in the wall at the pool below the Waterfall. Daylight and the next crystal confirm completion.','Press the pool-wall brick.',{images:photos(s,'main_ee/brick_to_push')})
  ]),
  phase('dials','Crystal 6: wall tiles, teepee and mud-room dials',[
   step('dials-tiles','In an eclipse, melee all twelve symbol tiles on walls until they glow. Sweep the Minecart start and spikes, both sides behind Quick Revive, the Pack-a-Punch stairs, Mud Room, Waterfall stairway and power room. The photographs show every tile; these are different from the floor tiles used for matching.','Melee the twelve wall tiles.',{images:collection(s,'main_ee/tile_')}),
   step('dials-teepee','Shoot the distant teepee visible from the Minecart area with an explosive. Its destruction ends this eclipse. Start a fresh eclipse for the dials.','Explode the distant teepee, then enter another eclipse.',{images:photos(s,'main_ee/teepee')}),
   step('dials-code','Enter the Mud Room from Spawn. Start with the dial immediately on your left and work clockwise. Set the top faces to 4, 3, 16, 1. Read dots as one, a line as five and the bracket shape as ten; the chart shows the exact faces. Wait for confirmation before continuing.','Set the mud-room dials clockwise to 4, 3, 16, 1.',{images:photos(s,'main_ee/first_dial','main_ee/shang_dials_cheat_sheet')})
  ]),
  phase('stone','Charge the crystals and claim the Focusing Stone',[
   step('stone-1','Pack-a-Punch the Baby Gun into the Fractalizer. During an eclipse, test the eight gongs to identify the four correct ones. A wrong gong flashes the crystals red and cancels the current ringing; it does not change which four are correct. Record the results below, then ring only the four correct gongs so all are sounding together and the crystals glow yellow.','Find and ring the four correct gongs during the eclipse.'),
   step('stone-dynamite','With the crystals charged, shoot the crystal above the Minecart geyser using the Fractalizer. Stand directly under the falling dynamite to catch it; no interact press is needed. If you miss it, recharge the correct gongs and try again.','Shoot the geyser crystal and catch the dynamite.',{images:photos(s,'main_ee/crystal_with_dynamite','main_ee/dynamite')}),
   step('stone-meteor','Recharge the four correct gongs if necessary, then shoot the crystal above the Mud Room with the Fractalizer. Its beam travels around the crystals and shrinks the meteor above Pack-a-Punch. The unupgraded Baby Gun cannot complete this step.','Shoot the charged Mud Room crystal to shrink the meteor.',{images:photos(s,'main_ee/crystal_to_shoot','main_ee/big_meteor')}),
   step('stone-2','Raise the Pack-a-Punch stairs with the team. Interact at the holed brick wall, let Brock finish speaking, and give him the dynamite through the opening. Everyone leaves the upper area so the eclipse ends. Raise the stairs again in daylight and take the Focusing Stone from the altar. Only the player collecting it gets permanent perks; repeat the quest for additional players.','Give Brock the dynamite; return in daylight for the Focusing Stone.',{images:photos(s,'main_ee/wall_with_hole','main_ee/stone_on_altar')})
  ],{tools:['bo3-shang-gongs']})
 ],[
  phase('samantha','Samantha’s Sorrow and Max Ammo',[
   step('shang-sam-pans','Keep your starting pistol. Ring the four correct gongs (the same set used by the main quest). Within the resulting window, go to the five pans at the bottom of the water slide: shoot the leftmost pan twice, then the fifth/rightmost pan once with that pistol.','Ring four correct gongs; shoot pan 1 twice, pan 5 once.',{images:photos(s,'free_max_ammo/wall_with_pans')}),
   step('shang-sam-targets','Interact with the doll beside the Danger sign at the Minecart start. Shoot the five targets in this order: first Minecart-tunnel crossbeam; lantern behind/left of the power-room Box spot; first crossbeam leaving power; last crossbeam near the Waterfall; wall at the Waterfall base. You can use the pictured sightlines from the ground.','Start at the Danger sign; shoot the five targets in order.',{images:photos(s,'free_max_ammo/doll_laying_down','free_max_ammo/doll_1','free_max_ammo/doll_2_zoomed_out','free_max_ammo/doll_3_zoomed_out','free_max_ammo/doll_4','free_max_ammo/doll_5')}),
   step('shang-sam-finish','Return to the now-standing starter doll and interact for the Max Ammo and Samantha’s Sorrow. If the timed sequence fails, restart from that doll.','Return to the Minecart doll for the reward.')
  ],{group:'Side Quests'}),
  phase('music-perks','Pareidolia and monkey power-up cycling',[
   step('shang-song','Interact with the red meteor pieces in Spawn, underground beside the minecart tracks/barbed wire, and at the top of Rope Bridge on the left when facing the Waterfall. Use the BO3 Spawn photograph: that meteor moved in the remaster.','Activate the three Pareidolia meteors.',{images:photos(s,'song_ee/meteor_spawn_bo3','song_ee/meteor_underground','song_ee/meteor_rope_bridge')}),
   step('shang-monkey-perk','Let a monkey pick up an uncollected power-up and watch the icon change as it runs. Kill it while the desired icon is displayed to drop that reward. A stolen Max Ammo can cycle through a very brief perk-bottle icon, allowing a free perk. Plan the shot before it reaches the temple and escapes.','Shoot a power-up-carrying monkey at the desired icon.')
  ])
 ],[reddit(s),kennedy(s)+'?version=bo3','https://www.accelerated-ideas.com/news/shangrila-easter-egg-steps-zombies-chronicles-dlc-5.aspx'])
]
