import {guide,phase,step,photos,reddit} from './chronicles-common.mjs'
const m='moon'
export const moonGuide=guide(m,'Moon','A full BO3 route from No Man’s Land to the destruction of Earth, plus Hacker uses, music, Samantha and Space Dog. The complete Chronicles quest supports 1–4 players with Richtofen in the match; the BO1 requirement to finish Call of the Dead and Shangri-La first does not apply.','moon',[
 phase('setup','Survive Area 51 and equip your P.E.S.',[
  step('setup-1','At Area 51, the alarm opens the teleporter cage. Move all players onto the pad to escape. On arrival at Griffin Station, immediately take a P.E.S. from the locker and equip it before going outside. Open either Tunnel 6 or Tunnel 11 to reach the pyramid room and flip the power switch.','Escape Area 51, equip P.E.S., reach the MPD power switch.',{images:photos(m,'moon-power-switch-next-to-mpd')}),
  step('setup-2','Open the laboratories and outside teleporter route. All players stand on the Moon teleporter when its lights are green to revisit Area 51 for Pack-a-Punch. Jugger-Nog and Speed Cola alternate there between visits. Obtain the Wave Gun, Gersh Devices and Q.E.D.s from the Box for the quest; Gersh and Q.E.D. occupy the same slot, so plan to obtain Gersh again for the ending.','Open the return teleporter and gather Wave Gun, Gersh and Q.E.D.')
 ],{group:'Key Features'}),
 phase('hacker','Find the Hacker and protect your air',[
  step('hacker-find','The Hacker is a small brown device on a yellow pad in the three-floor laboratory. Search two spots per floor. Picking it up replaces your P.E.S.; swapping back to P.E.S. drops the Hacker. Use pressurised routes and return for a suit before a long trip through a breached area.','Search the six laboratory Hacker spots.',{images:photos(m,'hacker-reference'),bullets:['Floor 1: shelf near the stairs; shelf near the doorway from the MPD room.','Floor 2: electrical box beside the stairs; blue structural railing on the opposite side.','Floor 3: metal tanks beside Deadshot; shelf left of the Biodome doorway.']}),
  step('hacker-excavators','Listen to the excavator announcement: Pi breaches Tunnel 6, Omicron Tunnel 11, Epsilon the Biodome. Hack the matching active console in the Receiving Bay to stop/retract it. For the main quest, Pi must actually breach Tunnel 6 once before you retract it. Retraction clears the machinery but does not restore the lost atmosphere.','Allow the required Pi breach; stop other excavators when possible.',{images:photos(m,'moon-excavator-pi-breaching-tunnel-6')})
 ]),
 phase('simon','Samantha Says and the timed laboratory panels',[
  step('simon-1','After power is on, interact with the four computers outside the Receiving Bay near Tunnel 6. Facing them, the physical order from left to right is Red, Green, Blue, Yellow. Watch the flashing sequence, then interact with the matching computers in that order. Complete the initial set of increasingly long sequences. Red failure feedback means replay the attempt.','Repeat the first Samantha Says sequences.',{images:photos(m,'moon-simon-says-computers')}),
  step('simon-2','Take the Hacker to floor 2 of the laboratories. Hack the far-left button on the four-button wall for 500 points. A roughly 60-second timer starts: locate and hack the four green-lit panel boxes among the eight possible boxes across the three floors. Ordinary unlit boxes do not count.','Hack the starting button, then the four green panel boxes.',{images:photos(m,'moon-button-wall')}),
  step('simon-3','Return to the four-button wall and quickly interact with all four buttons normally, rather than hacking them. The illuminated wall confirms success. If the timed attempt failed, restart at the initial button and search again; the selected green boxes may differ.','Press all four wall buttons and confirm they light.',{images:photos(m,'moon-glowing-button-wall')})
 ],{group:'Main Quest',tools:['bo3-moon-simon','bo3-moon-labs']}),
 phase('sphere','Tunnel 6, the sphere and the first soul tube',[
  step('sphere-1','Wait for Excavator Pi to breach Tunnel 6, then retract it with the Hacker at the Receiving Bay. Equip a P.E.S. for the now-depressurised tunnel. Find the black Vril Sphere on the Tunnel 6 floor and melee it to start it moving toward spawn.','After Pi breaches, retract it and move the Tunnel 6 sphere.',{images:photos(m,'moon-vril-sphere')}),
  step('sphere-2','Follow the sphere. When it lodges on the satellite dish above the Receiving Bay, shoot it with the Wave Gun in its combined mode. Follow it into Tunnel 11, opening doors and shooting or using an explosive when it sticks out of reach near the ceiling. Guide it to the socket in front of the pyramid.','Wave Gun the satellite sphere, then escort it through Tunnel 11.',{images:photos(m,'moon-satellite-dish-above-spawn','moon-vril-sphere-entering-vril-interface')}),
  step('sphere-3','Kill 25 zombies close to the newly exposed MPD tube so their souls enter it. When it is full, use the nearby lever to open the pyramid and reveal Samantha. Cryogenic Slumber Party and its temporary Death Machine mark the first milestone; continue below for the full ending.','Fill the first tube and open the MPD.',{images:photos(m,'moon-power-switch-next-to-mpd')})
 ]),
 phase('device','Bring back the plates and charge the Golden Rod',[
  step('device-plates','Bring a Gersh Device to Area 51. Throw a grenade at the hexagonal plates on the shelf to the right of the teleporter, knocking them down. Throw a Gersh close enough to pull the plates onto the teleporter, then return to the Moon.','Grenade and Gersh the Area 51 plates onto the pad.',{images:photos(m,'moon-hex-plates-shelf')}),
  step('device-qed','The plates now lie beside Quick Revive. Throw a Q.E.D. at them to move them to the computer in the opposite corner of the Receiving Bay. Keep Q.E.D.s until the later sphere-transfer step.','Q.E.D. the plates beside Quick Revive.',{images:photos(m,'moon-hex-plates-near-quick-revive','moon-computer-in-spawn')}),
  step('device-cable','Pick up the silver S-shaped cable in or just outside the laboratories. Sweep shelves, floors and corners on all three levels, then the outside area near Mule Kick. The photographs show its appearance and outside search area, not every possible spawn. Connect it between the Receiving Bay computer and plates.','Find and connect the S-shaped cable.',{images:photos(m,'moon-s-cable','moon-s-cables-outside-spawn','moon-s-cable-connected-to-machine')}),
  step('device-charge','Richtofen places his Golden Rod/Vril Device between the plates. Keep interacting with the computer through Maxis’s dialogue until the charge completes and the device glows. Pick the charged device back up before leaving.','Richtofen charges and retrieves the Vril Device.',{images:photos(m,'moon-vril-device-glowing')})
 ]),
 phase('rockets','Soul transfer and Earth’s destruction',[
  step('rockets-1','At the MPD, fill all four exposed tubes with 25 nearby zombie souls apiece. Richtofen inserts the charged device at the front of the pyramid, triggering the body swap and his permanent perks. After the dialogue, throw a Q.E.D. at the sphere in front of the MPD to send it back toward the computers.','Fill four tubes, perform the body swap and Q.E.D. the sphere.',{images:photos(m,'moon-filled-soul-containers')}),
  step('rockets-2','Complete three more Samantha Says games at the outside computers. Replace Q.E.D.s with Gersh Devices and throw a Gersh beside the sphere lying to the right of the computers. The countdown and three rockets striking Earth confirm the full ending. BO3 includes this ending even though its BO1 “Big Bang Theory” achievement is absent.','Complete three final computer games, then Gersh the sphere.',{images:photos(m,'moon-vril-sphere-next-to-computers','moon-earth-destroyed')})
 ])
],[
 phase('hacker-uses','Useful Hacker interactions',[
  step('hack-powerups','Hack a power-up for 5,000 points to convert it into Max Ammo. Protect the player while the hack completes; do not pick up the drop first.','Convert a spare power-up into Max Ammo.'),
  step('hack-box','Hack an unclaimed Box weapon to reroll it for 600 points. Hacking the rerolled result lets a teammate take it and refunds points to the hacker. Hacking a perk machine for a perk you own removes that perk and refunds its purchase price.','Reroll Box weapons or refund an unwanted perk.'),
  step('hack-sharing','Hack a teammate to transfer 500 of your points to them. This is useful when a teammate needs a door or perk; it does not generate free points.','Transfer points to a teammate.')
 ],{group:'Side Quests'}),
 phase('samantha','Samantha side quest: the fifteen speaker presses',[
  step('moon-sam-code','In the power/MPD room, face the back-to-back computer bank exactly as in the photo. Label its positions near-left, far-left, near-right and far-right. Press: far-right, near-left, near-left, near-right, near-right, near-left, near-right, far-left, near-right, far-left, near-right, near-left, near-left, far-left, far-right. These are fifteen interactions, independent of the outside colour computers.','Enter the photographed fifteen-press power-room code.',{images:photos(m,'samantha-code')}),
  step('moon-sam-dolls','Interact with the doll left of the MPD. Shoot the dolls that appear in front of the pyramid with a bullet weapon, then interact with the original doll again after the sequence. This awards Max Ammo and the Chronicles Samantha theme.','Shoot the MPD dolls and return to the starter.')
 ]),
 phase('space-dog','Space Dog',[
  step('space-dog-items','Using the combined Wave Gun, shoot three hidden objects: the dog toy near a truck tyre at Area 51, the teddy on the outer Biodome ledge, and the bone among the rocks near the Moon teleporter. Each collected object appears by the dog bowls on laboratory floor 2.','Wave Gun the dog toy, Biodome teddy and teleporter bone.',{images:photos(m,'space-dog-toy','space-dog-teddy')}),
  step('space-dog-souls','Hack the dog bowls on lab floor 2, then kill 50 zombies close to them. A bark confirms completion. From the outside teleporter area, look toward the landscape in the direction of spawn for the dog bounding in space. Its route can vary.','Hack the bowls and supply fifty nearby kills.')
 ]),
 phase('music','Coming Home, electronic songs and Nightmare',[
  step('moon-coming-home','Interact with three helmet-wearing teddy bears: on the crates below the Receiving Bay, in the airlock between Tunnel 6 and power, and in the broken wall near Stamin-Up. The third starts Coming Home.','Find the three astronaut teddy bears.'),
  step('moon-electronic','For the short electronic tracks, interact with the lab computers by the upper-floor weapon wall/Deadshot (Damned), the consoles by the Tunnel 11 door to power (Coming Home), and the floor-2 lab computers by the window crates (Pareidolia). These do not advance the main quest.','Try the three electronic computer songs.'),
  step('moon-nightmare','Nightmare is tied to the One Giant Leap setup in co-op: both tunnels must be breached, one player on the Receiving Bay side bleeds out, and the surviving player across the blocked routes finishes the round to respawn them. This deliberately costs a life; attempt it only when the team is ready for that optional challenge.','Complete the co-op One Giant Leap setup for Nightmare.')
 ])
],[reddit(m),'https://www.codzombiesguides.com/main-quests/black-ops-1/moon/','https://steamcommunity.com/sharedfiles/filedetails/?id=2373011651'])
