import {guide,phase,step,photos,reddit,kennedy} from './classic-common.mjs'
const k='kino-der-toten',f='five'
export const classicLaunchGuides=[
 guide('bo1',k,'Kino der Toten','Open the theatre, link the teleporter and unlock Pack-a-Punch, then explore 115, the film reels, radios and rocket model. Original Kino has no multi-stage main Easter Egg or boss ending. Its secrets reward exploration and story audio.','power/power',[
  phase('setup','Power and the stage route',[
   step('kino-power','From the lobby, buy the upstairs route through the rooms, Speed Cola area and Dressing Room to the stage, or take the lower Alley route around the other side. Switch on power at the side of the stage to lift the curtain and open the central theatre loop.','Reach the stage and activate power.',{images:photos(k,'power/power')}),
   step('kino-perks','Jugger-Nog is beside the theatre’s rear seating; Quick Revive is in the lobby, Speed Cola on the upper indoor route and Double Tap in the Alley. In solo, Quick Revive provides up to three self-revives. Updated BO1 also adds Mule Kick, but no Wunderfizz. Double Tap is the original fire-rate version.','Buy Jugger-Nog and appropriate survival perks.'),
   step('kino-kit','The Mystery Box can give the Thundergun, Ray Gun and Monkey Bombs. Save the Thundergun for clearing a blocked route; it does not refill from ordinary wall ammunition. Use a replenishable wall gun to earn points, and keep explosive Ray Gun shots away from your feet because this map has no PhD Flopper.','Use a wall gun for points and the Thundergun for escapes.')
  ],{group:'Key Features'}),
  phase('pap','Link the teleporter and use Pack-a-Punch',[
   step('kino-link','Interact with the teleporter pad on the stage to begin a link. Run to the circular mainframe pad in the lobby and interact again to finish it. Gather everyone who wants to upgrade inside the stage teleporter before activating it.','Link stage → lobby; activate the stage teleporter.',{images:photos(k,'pap/teleporter_pad','pap/mainframe')}),
   step('kino-upgrade','The teleporter sends its occupants to the projection booth for about 30 seconds. Pack-a-Punch costs 5,000 points. Retrieve your gun before the forced return; the clock over the machine shows the remaining window. A random intermission room may appear before you return to the lobby.','Upgrade and collect the weapon before the booth timer ends.'),
   step('kino-relink','Wait about a minute for the teleporter to cool down, then repeat the stage-to-lobby link for another trip. Use a final zombie to make film-reel trips safer. You cannot stay in the booth indefinitely by continuing to buy upgrades.','After cooldown, relink for each new trip.')
  ]),
  phase('survival','Traps, gas crawlers and dog rounds',[
   step('kino-traps','The electric doorway traps and Alley fire trap cost 1,000 points with power on. Lead zombies into the trap and move along a different route; its damage also threatens teammates. The automatic turrets cost 1,500 and can create crossfire, so check everyone’s path before activating one.','Use traps with a clear retreat and warn teammates.'),
   step('kino-nova','Gas crawlers begin appearing after power. Their death clouds can obscure your view and harm you; shoot them outside your immediate escape path. Keep a mobile circle around the stage and leave gaps between teammates so one player does not block another’s train.','Clear crawlers before their gas covers your escape.'),
   step('kino-dogs','Hellhound rounds end with Max Ammo. Find an open firing lane, cover reloads in co-op and reload all weapons before collecting the final drop. Treat the following regular round as a fresh wave rather than staying distracted by the pickup.','Reload before taking the dog-round Max Ammo.')
  ])
 ],[
  phase('music','115: three meteor fragments',[
   step('kino-song','Interact with the fragment in the jar under the lobby stairs near Quick Revive, the fragment by the mannequins behind the Dressing Room MP5K, and the fragment on the letter-filled shelf in the upstairs Alley room. Listen for each activation sound. All three start 115.','Activate the lobby, Dressing Room and upstairs Alley meteors.',{images:photos(k,'song_ee/rock_spawn','song_ee/rock_dressing_room','song_ee/rock_alley')})
  ]),
  phase('films','Three film reels and the projector',[
   step('kino-reels','On return from Pack-a-Punch, quickly search the random room for a flat film reel and press interact to collect it. The visit lasts only a few seconds, so start with the surfaces below. Room selection is random; an empty visit does not mean the secret failed.','Search each brief intermission room for a film reel.',{bullets:['Intact bedroom: check the bed, table and chair area.','Ruined bedroom: check the bed frame, table and window ledge.','Dentist room: check the cart beside the chair and both counters.','Pentagon conference room: check the front table and the TV/projector surfaces.']}),
   step('kino-project','On a later trip, interact with the film projector beside Pack-a-Punch to load your reel and hear the recording. Repeat until you have found and played all three films. These are story clips; they do not open a boss room or award a wonder weapon.','Load each collected reel into the projection-booth projector.',{images:photos(k,'film_reels/projector')})
  ]),
  phase('extras','Rocket model, radios and portraits',[
   step('kino-rocket','With power on, jump five times in front of the left of the two Dressing Room mannequins near the Speed Cola doorway. On a return trip that lands in the Pentagon-style conference room, interact with the small rocket model on the table. Community descriptions also associate this model with completing the film reels; finish those if the model does not respond. Its launch is a small visual secret.','Try the mannequin trigger, then the Pentagon-room rocket.',{images:photos(k,'rocket_launch/mannequins','rocket_launch/rocket')}),
   step('kino-radios','Shoot the radio on the chandelier above the theatre. For the other recording, look out from the Alley toward the distant tower beyond the barrier and shoot its radio with a precise weapon. Let one clip finish before triggering the other or the meteor song.','Shoot the theatre chandelier and distant Alley radios.'),
   step('kino-portraits','In the upstairs lobby portrait gallery, interact with the character portraits for comments; the blank picture also gets a response. These voices, the reels and the radios provide lore without a further quest chain.','Interact with the upstairs portraits for character dialogue.')
  ])
 ],[reddit(k),kennedy(k),'https://www.reddit.com/r/CODZombies/comments/4p0mbg/kino_der_toten_complete_map_breakdown/','https://call-of-duty-nazi-zombies.fandom.com/wiki/Kino_der_Toten/Film_Reels_and_Radios']),
 guide('bo1',f,'Five','Navigate the Pentagon’s three floors, use DEFCON for Pack-a-Punch, stop the Pentagon Thief and restore the electric traps. The original Five has a phone song and equipment secrets, but no main story Easter Egg. This guide describes BO1 rather than Classified’s extra rooms and quests.','power/power_room_outside',[
  phase('setup','Reach the laboratories and switch on power',[
   step('five-power','Open the ground-floor offices and take the first elevator to the War Room. Clear the route to its larger freight elevator and ride to the lowest floor, the laboratories. Coming out of that elevator, the power switch is in the second room on the left, marked with a large 3.','Ride through the War Room to Lab room 3 and switch on power.',{images:photos(f,'power/power_room_outside','power/power_switch')}),
   step('five-teleport','Power activates the red teleporters. Ordinarily they move you among the map’s destinations; do not assume a pad will return you to the floor you just left. Elevators have costs and can separate the team, so announce the trip before closing their doors.','Learn the three floors and expect variable teleporter exits.',{images:photos(f,'teleporters/teleporter')}),
   step('five-loadout','Buy Jugger-Nog in the lower War Room and keep a weapon with ammunition available nearby. The Box supplies the Winter’s Howl, Ray Gun and Monkey Bombs. Upgrading Winter’s Howl produces Winter’s Fury; there is no build or free-weapon quest for it here. Quick Revive gives three solo self-revives, while co-op use speeds up reviving teammates.','Buy Jugger-Nog and prepare a strong Thief-round weapon.')
  ],{group:'Key Features'}),
  phase('pap','DEFCON switches and the Panic Room',[
   step('five-defcon','DEFCON begins at 1. Use the four switches in the War Room, in any order, to reach 5. Two are upstairs on the catwalk and two downstairs. Once DEFCON 5 is active, enter a teleporter to reach the Panic Room.','Flip all four switches; teleport at DEFCON 5.',{bullets:['Upper: to the left as you leave the first elevator.','Upper: at the far end of the catwalk from that elevator.','Lower: near the freight elevator to the laboratories.','Lower: between Jugger-Nog and the later Mule Kick location.'],images:photos(f,'pap/defcon_catwalk_close','pap/defcon_catwalk_far','pap/defcon_lower_elevator','pap/defcon_jug')}),
   step('five-upgrade','Pack-a-Punch costs 5,000 points in the Panic Room. The closed doors give a short window of roughly 30 seconds; finish and collect your weapon before they open and the machine closes. When everyone leaves, the room resets and the switches must be used again for another visit.','Upgrade during the Panic Room window and retrieve your weapon.',{images:photos(f,'pap/pap_machine')})
  ]),
  phase('thief','Pentagon Thief and the Bonfire Sale',[
   step('five-thief','After power, special rounds can bring the Pentagon Thief instead of zombies. He pursues one player at a time. His target and players already targeted can see him; others see a red trail and can still shoot it. If he touches you, he steals the gun currently in your hands and teleports away.','Shoot the Thief while keeping your valuable weapon out of his reach.',{images:photos(f,'thief_round/pentagon_thief')}),
   step('five-thief-tactics','Elevators are disabled during his visit, so use the teleporters and open floor space. Focus damage before he reaches his target. If contact is unavoidable, switch to the less valuable weapon first. Keep firing after a theft to recover the stolen guns before he escapes through enough teleporters.','Coordinate damage; recover stolen guns before he escapes.'),
   step('five-bonfire','Kill him before anyone loses a weapon for Bonfire Sale. While it is active, teleporters go to Pack-a-Punch without the DEFCON setup and upgrades cost 1,000 points. Killing him after a theft instead returns the stolen weapons and gives Fire Sale plus Max Ammo. If he escapes, those stolen weapons are lost.','No theft: Bonfire Sale. After theft: recover guns and take Fire Sale.',{images:photos(f,'thief_round/bonfire_sale_powerup')})
  ])
 ],[
  phase('traps','Repair the two electric traps',[
   step('five-parts','Look for the small red electrical trap boxes on the lower War Room floor and in the laboratory room containing the Bowie Knife. They are separate pickups: take one back to an incomplete metal-detector trap in the ground-floor office corridors and fit it, then fetch the other for the remaining trap. Check the corners, equipment and locker by the Bowie Knife when searching.','Bring each red component back to a ground-floor metal-detector trap.'),
   step('five-traps','With the component fitted and power on, the trap costs 1,000 points. Draw a horde through it while you take a clear alternative path. Tell teammates before activating it; the current is dangerous to players too. Wait for its cooldown before planning another pass.','Activate a repaired trap and lead the horde through.')
  ]),
  phase('music','Won’t Back Down',[
   step('five-song','Interact with three red telephones: on the table left of Quick Revive at Spawn, on the desk facing the power switch in the labs, and on the table beside a barrier inside the Panic Room. Use DEFCON to reach the last one. Listen for the registration sound; the third starts Won’t Back Down.','Use the Quick Revive, power and Panic Room red phones.',{images:photos(f,'song_ee/phone_quick_revive','song_ee/phone_power','song_ee/phone_panic_room')})
  ])
 ],[reddit(f),kennedy(f),'https://www.reddit.com/r/CODZombies/comments/lqmf21/'])
]
