import { coldWarGuides } from './cold-war-guides.mjs'
import { guides as aetherGuides } from './bo4-alpha-tag.mjs'
import { guides as nightGuides } from './bo4-night-classified.mjs'
import { guides as chaosGuides } from './bo4-ix-ancient.mjs'
import { bloodOfTheDead } from './blood-of-the-dead.mjs'
import { voyage } from './bo4-voyage.mjs'
import { bo6Guides } from './bo6-guides.mjs'
// Original concise walkthroughs adapted from the linked research sources.
// Stable phase/step IDs are generated from the explicit keys, never from prose.
const reddit = slug => `https://www.reddit.com/r/CODZombies/wiki/${slug}/`
const phase = (id, title, steps, tools = []) => ({ id, title, steps: steps.map((step, i) => typeof step === 'string' ? { id: `${id}-${i + 1}`, text: step } : { id: `${id}-${i + 1}`, ...step }), tools })
const guide = (id, gameId, name, intro, phases, sources, extra = {}) => ({ id, gameId, name, intro, phases, sources, reviewed: '2026-09-30', ...extra })
export const games = [{ id: 'bo7', name: 'Black Ops 7' }, { id: 'bo6', name: 'Black Ops 6' }, { id: 'cw', name: 'Black Ops Cold War' }, { id: 'bo4', name: 'Black Ops 4' }, { id: 'bo3', name: 'Black Ops 3' }]
export const expansionGuides = [
  ...bo6Guides,
  ...coldWarGuides,
  guide('bo3-origins', 'bo3', 'Origins', 'Zombies Chronicles version. Build and upgrade all four staffs for the main quest. Older Origins pages also contain BO2 material; the source links are references, not a claim that every old weapon or shortcut exists in BO3.', [
    phase('setup', 'Key Features: generators and equipment', [
      'Activate the six generators by staying within their capture areas and defeating the attacking templars. All six must be powered to use Pack-a-Punch.',
      'Collect shield parts around the generator routes and build it at a workbench. Take a shovel from a starting location and dig marked sites for equipment.',
      'Collect the gramophone in the excavation and the black record near the mound. Place the gramophone to open the lower excavation, then retrieve it for the elemental tunnels.',
      'Each staff needs its colored record, three parts and the crystal from its matching Crazy Place portal. Leave the portal open until you return, then recover the gramophone.'
    ]),
    phase('staff-build', 'Build the four staffs', [
      'Ice: dig glowing excavation sites while it is snowing, searching the spawn, middle and church regions for its three parts. Take the blue record from the Tank Station area and obtain the ice crystal through the church tunnel.',
      'Fire: collect the part dropped by a Panzer, shoot down the glowing plane and collect its drop, and take the Generator 6 reward part. Find the red record around the church and obtain the fire crystal.',
      'Wind: enter each giant robot through its lit foot by shooting the panel before it steps down. Collect one part inside each robot, find the yellow record around Generator 5 and obtain the wind crystal.',
      'Lightning: use the tank to reach all three elevated part locations; plan the jump before riding past each platform. Find the purple record near Generator 4 and obtain the lightning crystal.',
      'Return to the excavation pedestals and build each staff. Collect its crystal before trying to assemble it.'
    ]),
    phase('upgrades', 'Upgrade all four staffs', [
      'Ice: match each shown tablet to its ceiling symbol in the Crazy Place. Use the linked source chart when identifying shapes. Back on the map, freeze the three tombstones, then break each with a bullet weapon.',
      'Fire: kill zombies on the Crazy Place grates with the staff until the cauldrons light. Decode the glowing church symbols into torch numbers and light the corresponding torches with the fire staff.',
      'Wind: set the Crazy Place rings to the wind pattern shown in the reference guide, then redirect the three smoking stone balls toward the excavation with the staff.',
      'Lightning: number the seven lower keyboard triangles from left to right. Shoot 1–3–6, wait for the sparks to clear, then 3–5–7, wait, then 2–4–6. Ignore the upper row. Rotate the sparking electrical panel switches around the map until they stop sparking.',
      'For each staff, align the excavation rings to its color, shoot the orb beneath them, then place the staff in its Crazy Place pedestal and feed it kills until charged. Retrieve the upgraded staff.'
    ], ['bo3-origins-ice', 'bo3-origins-fire', 'bo3-origins-staffs']),
    phase('equipment', 'Thunder Fists, G-Strikes and drone', [
      'Fill all four soul chests in the robot footprints without letting a robot reset an unfinished chest. Collect the Thunder Fists from a reward chest.',
      'Take a tablet from the Tank Station to the church water basin. Earn nearby melee kills to clean it, then carry it back without touching mud. If it becomes dirty, return to the basin and try again.',
      'Place the clean tablet back in the Tank Station and earn the required melee kills to unlock G-Strikes. Build the Maxis Drone from its three parts.'
    ]),
    phase('seal', 'Robot pedestals and the seal', [
      'Place upgraded staffs in the quest pedestals: ice in the church robot, wind in the middle robot, lightning in the spawn robot, and fire in the excavation.',
      'After the placement step completes, retrieve the staffs. Press a robot’s red button and quickly throw a G-Strike onto the sealed ground near Generator 5. In co-op, assign the button and throw to separate players.',
      'Once the seal opens, deploy the Maxis Drone into it. Defeat the spawned Panzers before continuing.'
    ]),
    phase('finale', 'Pilot and Crazy Place finale', [
      'Use Zombie Blood to see and shoot the glowing plane, then locate and kill its pilot while the effect is active. Collect the drone it drops.',
      'In the lower excavation, use melee attacks on the special smoke-trailing zombies until the upgraded-fist tablet appears; collect it.',
      'Place all four upgraded staffs in the Crazy Place and feed the final soul requirement. When the portal opens, deploy the upgraded Maxis Drone and use the final interaction to finish the quest.'
    ])
  ], [reddit('origins')], { group: 'chronicles' }),
  nightGuides.find(g => g.id === 'bo4-dead-of-the-night'),
  guide('bo3-der-eisendrache', 'bo3', 'Der Eisendrache', 'Track bow branches independently. Ranked matches require the appropriate bows for the player count; unranked quest runs require all four upgrades.', [
    phase('setup', 'Key Features: power and equipment', ['Open the route to power and turn it on. Activate the courtyard anti-gravity plates and collect shield parts while opening the castle.', 'Interact with the scattered Pack-a-Punch components to assemble the machine. Feed each of the three stone dragons one zombie at a time until it stops eating.', 'Collect Wrath of the Ancients from the knight’s tomb. Gather the Ragnarok DG-4 components from the Panzer, launch-pad drop and rocket-test event.']),
    phase('bows', 'Bow upgrades', ['Choose the required upgrade branches. Lightning uses the weather vane, bonfires, wall-running symbols and electrified shots; Wolf follows its paintings, flag, skull and spirit wolf.', 'Fire uses the clock-tower symbol, rocket-site rock, aerial circle shots and its fireplace route. Void uses the trophy-room floor, skulls, crawlers and spoken names.', 'For Void, record the three spoken names, then the glyph each corresponding knight reveals. Do not assume a fixed name-to-glyph mapping.', 'Complete each branch’s charged soul chest and collect the upgraded bow.'], ['bo3-de-bows', 'bo3-de-void']),
    phase('time', 'Wisps, time travel and safe', ['Start the teleporter wisp sequence with the unupgraded bow. Use an upgraded bow to shoot each active electrical object before the attempt expires; a failed sequence needs a fresh attempt.', 'Teleport to the past and record the safe combination. Collect the required quest items before returning.', 'Set the Death Ray to Protect, enter the observed safe code at the terminal and retrieve the safe contents. Install the fuses and complete the station symbol challenges.'], ['bo3-de-terminals']),
    phase('keeper', 'Keeper and boss preparation', ['Complete the terminal/Death Ray sequence to bring down the pod and collect the tablet. Repeat the time-travel step when required to obtain the remaining quest item.', 'Place the tablet and follow the keeper. Feed its circles with the bow element indicated for that location. Keep the correct bow available to its player.', 'When the keeper returns and the pyramid stage is ready, gather the team with charged Ragnarok DG-4s, upgraded weapons and ammunition.']),
    phase('boss', 'Keeper boss and ending', ['Use Ragnarok DG-4 at the arena center during the keeper’s electrical charge to expose it. Shoot the vulnerable chest and survive the Panzer waves between damage phases.', 'Repeat the opening and damage cycles. After returning to the castle, collect and use the Summoning Key at the terminal to complete the ending.'])
  ], [reddit('der-eisendrache')]),
  guide('bo3-gorod-krovi', 'bo3', 'Gorod Krovi', 'Record SOPHIA’s bomb order before moving. Valve positions and bomb order are separate puzzles and must never share an ordering.', [
    phase('setup', 'Key Features: dragon access', ['Turn on power and collect the three colored code cylinders from enemy drops. Insert each in its matching terminal and defend the dropped Groph module.', 'Collect each module’s part and install the dragon control. Ride the dragon to the hatchery to access Pack-a-Punch and complete the lockdown.', 'Build the Dragon Shield. Obtain and incubate the dragon egg, complete its challenges, then charge it at the hatchery to receive the Gauntlet of Siegfried.']),
    phase('valves', 'Generator and valve network', ['Use a Valkyrie electrical attack to power the generator. Identify the valve with the green light and the valve containing the master cylinder.', 'Enter those two rooms in the valve solver. Set the five connecting valves to its output and collect the cylinder at the endpoint.', 'Take the master cylinder to SOPHIA and enter KRONOS when prompted.'], ['bo3-gorod-valves']),
    phase('trophies', 'Trophies and SOPHIA challenges', ['Collect all six challenge trophies using the map’s shield, equipment and environmental interactions, then place them at the command terminal.', 'Activate each challenge and follow its specific objective: escorts must reach their destination, defense targets must survive and collection tasks need their items returned.', 'For the bomb challenge, record every displayed location before leaving the screen. Defuse all six in exactly that order; a wrong interaction can end the run.'], ['bo3-gorod-bombs']),
    phase('boss', 'Power core and final fights', ['After all challenges, obtain the power core and deliver it to Nikolai using the Gauntlet dragon. Gather the team at the final entrance.', 'Fight the dragon by damaging exposed weak spots between attacks. Then damage the weak points of Nikolai’s mech as they become available.', 'Finish the final interaction after the mech is defeated. Do not assume the dragon fight alone completes the quest.'])
  ], [reddit('gorod-krovi')]),
  chaosGuides.find(g => g.id === 'bo4-ix'),
  voyage,
  bloodOfTheDead,
  guide('bo3-shadows-of-evil', 'bo3', 'Shadows of Evil', 'The final tram/keeper stage requires four players in standard unmodded play. Setup and much of the quest can be practiced solo.', [
    phase('setup', 'Key Features: rituals and Pack-a-Punch', ['Use Beast mode to open each district’s ritual route: shock electrical boxes, break marked doors/crates and grapple to elevated entrances before the transformation ends.', 'Collect the Summoning Key and the four character ritual items. Complete the corresponding rituals at Easy Street, the Canal burlesque area, Waterfront boxing gym and Footlight theater.', 'Take the four gateworms through the rift, place them around the underground ritual room and survive its final ritual to unlock Pack-a-Punch.', 'Build the shield and prepare a strong weapon. The Apothicon Servant requires its three match drops; recommended GobbleGums are optional loadout choices.']),
    phase('swords', 'Apothicon sword and upgrade', ['Ride the tram routes and look through the windows for the three red glyphs. Record them, then enter Beast mode and activate the corresponding symbols on the underground wall.', 'Take the egg and place it at each of the four statues. Fill each placement with nearby kills, return it to the wall and collect the sword.', 'Visit your character’s ritual location for the Arch-Ovum. Complete its summoning-circle encounters across successive rounds, then return to exchange for the upgraded sword.'], ['bo3-shadows-glyphs']),
    phase('flags', 'Book and flag defenses', ['After the swords are ready, activate the book in Nero’s room and obtain the flag. Place it at the indicated defense locations.', 'Protect the flag from incoming enemies and Shadowman attacks. Pick it up when charged and carry it onward, completing each route before returning it to the appropriate ritual keeper.', 'Repeat the available flag routes, respecting their round progression, until the keepers are ready.']),
    phase('finale', 'Shadowman and four-player finale', ['Activate the keepers in the underground ritual chamber. Damage the Shadowman through the vulnerable phases and trap him at the ritual table.', 'Assign three players to the tram stations and one to the central junction. Coordinate Beast-mode electrical interactions, tram movement and keeper shocks for the final gateworm stage.', 'Confirm the final quest reward rather than treating the earlier Shadowman encounter as the complete four-player ending.'], ['bo3-shadows-roles'])
  ], [reddit('shadows-of-evil'), 'https://www.reddit.com/r/CODZombies/comments/1lmuqdx/shadows_of_evil_easter_egg_2025/']),
  guide('bo3-zetsubou-no-shima', 'bo3', 'Zetsubou No Shima', 'Plants have random outcomes. Track watering and KT-4 treatment, but do not assume a recipe guarantees fruit, an imprint or the artillery shell.', [
    phase('setup', 'Key Features: permanent power', ['Collect a bucket and water. Fill the temporary generators in Labs A and B, then open the bunker while both are active.', 'Enter the flooded power room, clear the obstruction and survive the underwater lockdown to activate permanent power. Watch oxygen while fighting.', 'Drain the three Pack-a-Punch areas and collect the machine parts. Build the shield and gas mask from their spawn groups.']),
    phase('equipment', 'Skull, KT-4 and Masamune', ['Match the four skull symbols to their ritual locations and charge each skull with kills. Return them and survive the ritual to obtain the Skull of Nan Sapwe.', 'Collect the KT-4 ingredients from the laboratory spider cage, special zombie and underwater plant route, then build the weapon.', 'Complete the trials and Masamune upgrade requirements. Use the skull to reveal hidden quest surfaces and the electrified shield where specified.'], ['bo3-zetsubou-upgrades']),
    phase('plants', 'Plant rewards and artillery shell', ['Plant a seed and water it once per growth round. Record its treatment; use KT-4 fertilization for recipes that require it.', 'For the artillery task, grow the required reward plant and collect the shell if it appears. If it does not, plant and grow another attempt.', 'Load the shell into the anti-aircraft gun and shoot the passing plane at the correct moment. Collect the dropped cog.'], ['bo3-zetsubou-plants']),
    phase('cogs', 'Elevator cogs', ['Use Anywhere But Here after revealing its hidden room to collect one cog. This quest route requires that GobbleGum interaction.', 'Obtain the zipline cog using the electrified-shield sequence. Solo uses the timed dismount route; co-op can have a teammate electrify the zipline.', 'Install all three cogs at the elevator. Prepare Masamune, shield, mask and ammunition before descending.']),
    phase('boss', 'Boss room', ['Survive the enemies and wait for the boss’s vulnerable spores to open. Shoot the active spores with Masamune.', 'Repeat through the exposed growths, keeping oxygen, space and ammunition available until the final interaction.'])
  ], [reddit('zetsubou-no-shima')]),
  guide('bo3-revelations', 'bo3', 'Revelations', 'Separate the collections in this quest: reels, bones, eggs, runes and Summoning Key targets have different completion conditions.', [
    phase('setup', 'Key Features: engines and equipment', ['Activate the four corruption engines and use Nacht’s control to stun the giant Apothicon. Enter it and shoot the stomach’s yellow sacs to release Pack-a-Punch.', 'Build the shield and Keeper Protector. Obtain Lil Arnies and the Apothicon Servant, then complete their required upgrades.', 'Shoot the opening gravestones in order 2, 3, 1, 4 to begin the main quest.']),
    phase('reels', 'Keeper, Arnies and bones', ['Find the special stone at a jump pad and summon the Keeper Protector there. Protect its ritual, collect the reel and play it at the appropriate recorder.', 'Complete the Lil Arnies hole groups inside the Apothicon and defeat the resulting enemies. Collect and play the next reel.', 'Reveal the six bones around the map, then collect them with the upgraded Apothicon Servant. Reveal Sophia’s skeleton at Nacht, collect the reel and play it at the Origins mound.'], ['bo3-revelations-collections']),
    phase('eggs', 'Sophia, eggs and runes', ['Aim each corruption turret at the reflecting rock until its beam locks toward Sophia. Interact with her and escort her to Kino’s teleporter.', 'Teleport with the team to Samantha’s room and collect the Kronorium. Find the four orange eggs; only one is visible on the map at a time.', 'Charge eggs in the Apothicon pool. The collecting player must supply the souls. Use each hatched gateworm’s sonar to find its placement and obtain a rune.']),
    phase('key', 'Kronorium sequence and Summoning Key', ['Stand on the four runes at Kino to reach the arena. Read the Kronorium’s rune order and activate the floating symbols in that order.', 'Survive the challenge waves and collect the Summoning Key. Hit the required targets in Shangri-La, Nacht, Verrückt, Mob, Origins, Der Eisendrache and Kino.', 'Return through the Kino teleporter when the targets are complete.'], ['bo3-revelations-runes', 'bo3-revelations-collections']),
    phase('boss', 'Shadowman finale', ['Charge the Summoning Key at an arena pedestal, then throw it to Sophia to break the Shadowman’s shield.', 'Damage the Shadowman into the Apothicon’s mouth and interact with the Kronorium. Repeat the charge cycle if the damage window is missed.'])
  ], [reddit('revelations')]),
  chaosGuides.find(g => g.id === 'bo4-ancient-evil'),
  aetherGuides.find(g => g.id === 'bo4-alpha-omega'),
  aetherGuides.find(g => g.id === 'bo4-tag-der-toten'),
  guide('bo3-the-giant', 'bo3', 'The Giant', 'This is the BO3 version of The Giant. Its setup and weapon secrets are short objectives rather than a large boss quest.', [
    phase('setup', 'Key Features: teleporter links', ['Open the route to the power switch and activate it. At each of the three teleporters, start linking and return to the mainframe at spawn within the displayed time.', 'Link all three to open Pack-a-Punch. Upgrade a weapon before starting Fly Trap.']),
    phase('flytrap', 'Fly Trap and Annihilator', ['From the starting area, use a Pack-a-Punched weapon to shoot the control panel outside the map and start the Fly Trap audio.', 'Find and shoot the three hidden toy targets: the furnace area, the teleporter-side vat area and the elevated exterior ledge. Use the source images for the precise sightlines.', 'After the final confirmation, collect the Annihilator from its furnace reward location.']),
    phase('perk', 'Hidden perk', ['Obtain Monkey Bombs and use them for the three teleporter interactions. Complete the associated control activations.', 'Activate the final mainframe control to reveal the hidden perk. Keep these interactions separate from the initial Pack-a-Punch links.'], ['bo3-giant-secrets'])
  ], [reddit('the-giant')], { questLabel: 'Setup and secrets' }),
  nightGuides.find(g => g.id === 'bo4-classified'),
  guide('bo3-ascension', 'bo3', 'Ascension', 'Zombies Chronicles. The unmodded Casimir Mechanism quest requires four players and synchronized actions.', [
    phase('setup', 'Key Features: landers and rocket', ['Turn on power and use all three lunar lander stations. Launch the rocket to reach Pack-a-Punch.', 'Prepare Gersh Devices, Matryoshka Dolls and upgraded high-damage weapons for the final orb stage. Coordinate equipment across the team.']),
    phase('nodes', 'First three Casimir nodes', ['Throw a Gersh Device at the generator outside the playable area near the PhD/Widow’s Wine side, then activate the monitor by the Stamin-Up lander.', 'During a monkey round, assign all four players to the four perk-area buttons and press them together.', 'With Pack-a-Punch open, stand together on the platform beneath the rocket for one full clock rotation without leaving it.']),
    phase('luna', 'LUNA lander route', ['Keep one rider aboard while teammates call the lander: Spawn → Stamin-Up, Stamin-Up → Spawn, Spawn → Speed Cola, Speed Cola → Stamin-Up.', 'Collect the letters along those flights to spell LUNA and activate the fourth node.'], ['bo3-ascension-luna']),
    phase('orb', 'Final orb', ['At the Casimir device near Stamin-Up, use a Gersh Device at the glowing orb and apply the required explosive/wonder-weapon damage as a team.', 'Continue until the orb rises and the quest confirmation plays. This quest has its own reward rather than a conventional boss arena.'])
  ], [reddit('ascension'), 'https://steamcommunity.com/sharedfiles/filedetails?id=2446771284'], { group: 'chronicles' }),
  guide('bo3-shangri-la', 'bo3', 'Shangri-La', 'Zombies Chronicles. Four players are required to activate Eclipse and coordinate the main quest. A failed Eclipse attempt is not necessarily a whole-round failure.', [
    phase('setup', 'Key Features: power and Eclipse', ['Activate both underground power switches. Coordinate the pressure plates for Pack-a-Punch access and obtain the 31-79 JGb215.', 'Assign players to the four spawn buttons and press them together to enter Eclipse. Re-enter Eclipse for stages that require it.']),
    phase('tiles', 'Tile matching and water slide', ['Divide the tile areas between players. Reveal symbols, record positions on both sides and step on matching pairs in coordination.', 'For the water-slide sequence, arrange three players at the bottom while the final player completes the lever/slide interaction. Confirm the step succeeds before moving on.'], ['bo3-shang-tiles']),
    phase('trials', 'Meteor, Napalm and dials', ['Use the baby gun and slide route for the meteor step. Complete the Napalm zombie gas-leak route without killing the required zombie too early.', 'Use Spikemores for the tunnel-hole step, then complete the stone-symbol and mud-dial interactions using their reference patterns.', 'Listen to the gongs and identify the correct resonance before the focusing-stone interaction.']),
    phase('stone', 'Focusing stone', ['Complete the final Eclipse actions and open the route to the focusing stone. Coordinate the team’s positioning before collecting it.', 'A player’s reward and any repeated run for additional rewards should be tracked separately; reset only the relevant quest checklist.'])
  ], [reddit('shangri-la'), 'https://steamcommunity.com/sharedfiles/filedetails/?id=2461194923'], { group: 'chronicles' }),
  guide('bo3-moon', 'bo3', 'Moon', 'Zombies Chronicles supports the full quest solo. Original BO1 prior-quest requirements do not apply to this version. PES and Hacker occupy the same equipment slot.', [
    phase('setup', 'Key Features: oxygen and equipment', ['Escape Area 51 to the Moon, collect a PES and restore power. Use the Hacker carefully: without a PES you need breathable areas.', 'Prepare the Wave Gun, Gersh Devices and QEDs as the quest requires. Keep access to Tunnel 6 for the sphere stage.']),
    phase('simon', 'Samantha Says and terminals', ['Complete the first Samantha Says sequence at the four screens by repeating each display in order.', 'Use the Hacker for the laboratory terminal/button stage and finish its timed interactions.', 'Wait for Excavator Pi to breach Tunnel 6, then stop the excavator with the Hacker when the quest’s tunnel condition has been satisfied.'], ['bo3-moon-simon']),
    phase('sphere', 'Sphere and MPD', ['Follow the sphere through Tunnel 6, using the appropriate weapon interactions and Wave Gun satellite shot to move it onward.', 'Guide the sphere into the MPD, then fill the required soul stage to open the chamber.', 'Return to Area 51 for the plates. Use the Gersh/QED interactions to move them into place and find the cable for the Vril device/computer sequence.']),
    phase('rockets', 'Canisters and rockets', ['Complete the device/computer stage and fill the four soul canisters. Keep the team supplied while moving between the charge areas.', 'Repeat the later Samantha Says sequences, clearing the helper for each attempt. Finish the final sphere/device interactions to launch the rockets.'], ['bo3-moon-simon'])
  ], [reddit('moon'), 'https://steamcommunity.com/sharedfiles/filedetails/?id=2373011651'], { group: 'chronicles' }),
  guide('bo3-nacht-der-untoten', 'bo3', 'Nacht der Untoten', 'Zombies Chronicles setup and secrets. There is no ordinary power switch or Pack-a-Punch quest on this map.', [
    phase('setup', 'Key Features: rooms and equipment', ['Choose which staircase and Help-room routes to open based on the team’s training space. Leaving a route closed changes how zombies reach the upper floor.', 'Use the Mystery Box and Wunderfizz for equipment. The scoped cabinet weapon and perk options differ from the original World at War version.']),
    phase('samantha', 'Samantha secret', ['Find and activate the four small Samantha buttons around the map. Listen for the success cue, then interact with the starting doll.', 'Shoot the appearing dolls through the sequence, following their sound and sightlines. Collect the reward after completion.'], ['bo3-nacht-secrets']),
    phase('extras', 'Useful extras', ['The radio is a separate music interaction. Keep it separate from the Samantha buttons and do not expect it to unlock a main quest.', 'Use the source’s images for small button and doll sightlines; the helper tracks completed stages, not unseen target positions.'])
  ], [reddit('nacht-der-untoten')], { group: 'chronicles', questLabel: 'Setup and secrets' }),
  guide('bo3-verruckt', 'bo3', 'Verrückt', 'Zombies Chronicles. Players can begin on opposite sides of the asylum and remain separated until the power route is opened.', [
    phase('setup', 'Key Features: split spawns', ['Identify whether you started on the Jugger-Nog or Quick Revive side. Open that side’s upstairs route toward the power room.', 'Turn on power to reconnect the starting halves. Coordinate purchases so both sides retain enough space and ammunition.', 'Use the map’s traps and BO3 equipment options. Do not apply the original version’s Mystery Box contents automatically.'], ['bo3-verruckt-setup']),
    phase('secrets', 'Samantha and music secrets', ['Perform the toilet interaction sequence to start the Chronicles Samantha secret, then follow the doll sequence and collect its reward.', 'Use the toilet/music interaction separately when playing the map’s song. Listen for the cue before repeating an interaction.'])
  ], [reddit('verruckt')], { group: 'chronicles', questLabel: 'Setup and secrets' }),
  guide('bo3-shi-no-numa', 'bo3', 'Shi No Numa', 'Zombies Chronicles. This guide does not describe the Vanguard main quest or mobile-only weapon secrets.', [
    phase('setup', 'Key Features: huts and perks', ['Open the central route and choose a hut to explore. Record the perk revealed at each hut; locations are randomized between matches.', 'Use the Flogger and avoid becoming trapped in the slowing water. Keep an escape route when opening a new hut.', 'Obtain the Wunderwaffe from the BO3 weapon pool if desired; there is no Vanguard-style build quest here.'], ['bo3-shi-perks']),
    phase('secrets', 'Samantha and telephone secrets', ['Shoot the four pans for the Chronicles Samantha activation, then follow the bridge/doll sequence and collect the reward.', 'Interact with the telephone for the map’s music secret. This is independent of hut perk assignments.'])
  ], [reddit('shi-no-numa')], { group: 'chronicles', questLabel: 'Setup and secrets' }),
  guide('bo3-kino-der-toten', 'bo3', 'Kino der Toten', 'Zombies Chronicles setup and secrets. The main practical route is power, teleporter linking and Pack-a-Punch.', [
    phase('setup', 'Key Features: stage and teleporter', ['Open a route from the lobby to the stage and switch on power. Link the teleporter at the stage and then the mainframe in the lobby.', 'Use the linked teleporter for the Pack-a-Punch room. Watch the return timing and finish purchases before being moved onward.', 'Collect film reels from the intermission rooms and use the projector when available.']),
    phase('secrets', 'Meteorites and Samantha knocks', ['Interact with the three meteorite fragments to activate the music secret.', 'For the Chronicles Samantha sequence, listen to the three groups of knocks and record each count. Repeat the observed pattern at the interaction point.', 'Continue the resulting doll sequence and collect its reward. Clear the knock recorder for a new attempt rather than appending an old pattern.'], ['bo3-kino-knocks'])
  ], [reddit('kino-der-toten')], { group: 'chronicles', questLabel: 'Setup and secrets' }),
]
