import { guide, phase, step, image } from './remaining-common.mjs'

const photo=(id,alt)=>image(`asset-${String(id).padStart(4,'0')}`,alt)
const pictures=(...items)=>items.map(([id,alt])=>photo(id,alt))
const s=(id,text,quick,items=[],extra={})=>step(id,text,quick,{...(items.length?{images:pictures(...items)}:{}),...extra})
const sources=(slug,path)=>[
  {label:'Illustrated quest and equipment reference · mmmrkennedy',url:`https://mmmrkennedy.com/games/IW/${path}/${path}_guide`},
  {label:'Community guide · r/CODZombies',url:`https://www.reddit.com/r/CODZombies/wiki/${slug}/`},
  {label:'Illustrated main quest · COD Zombies Guides',url:`https://codzombiesguides.com/main-quests/infinite-warfare/${slug}/`}
]
const edition='Infinite Warfare’s original Zombies mode. Scene, symbol, colour and code observations come from your current match. Director’s Cut changes equipment access and ending rewards; its account unlocks are separate from a new map run.'

const spaceland=guide('iw-zombies-in-spaceland','iw','Zombies in Spaceland',`${edition} Restore the park, defend the SETI-COM, repeat the UFO’s speaker sequences, defeat the aliens and finish the UFO laser. A Weapon of Rock is required for the final laser, rather than for every early step.`,[
  phase('setup','Open the park and projector room',[
    s('power','Switch on all five regional supplies: the Spawn employee room by the M1; Journey’s Star Mission/Rover Rampage hallway; Astrocade left of its portal; Polar Peak by Quickies; and Moonlight Cafe upstairs in Kepler. Each switch powers only its own region.','Enable all five power switches.',[[808,'Spawn power'],[809,'Journey power'],[810,'Astrocade power'],[811,'Polar Peak power'],[812,'Kepler power']]),
    s('portals','Activate and travel through Journey, Astrocade, Polar Peak Gift Shop and Kepler’s stair-base portals. The four hub indicators turn blue. Enter Cosmic Way’s central portal to reach the projector; it returns you after its visit window and needs to cool down before reuse.','Use four regional portals, then the Cosmic Way projector gateway.',[[813,'Journey portal'],[814,'Astrocade portal'],[815,'Polar Peak portal'],[816,'Kepler portal'],[817,'Four hub indicators']])
  ]),
  phase('equipment','Prepare equipment and a Weapon of Rock route',[
    s('loadout','Bring an upgraded damage weapon, ammunition and a distraction for the SETI-COM defences. Explosive weapons help keep zombies off the device; Bombstoppers protects against your own explosive splash. Select a Weapon of Rock branch below and save its station-specific coins.','Prepare defence equipment and save the chosen wonder-weapon coins.'),
    s('cores','Buy an Arcane Core for 300 tickets and activate the UFOs on the projector-room table. Charge one trap in a single use until its UFO leaves orbit, then kill with the Arcane Core weapon near it until it drops an elemental orb. Trap/core pairs: Journey Rocket → Electric; Astrocade Disco → Laser; Polar Steel Dragon → Wind; Kepler Chromosphere → Fire.','Release the UFOs; charge a trap, then its UFO with Arcane Core kills.'),
    s('teeth','Buy Golden Teeth for 300 tickets. Lure a Brute into Kepler’s gator mouth so its teeth break, then fit the replacements. Shoot the throat targets with matching elemental cores: left to right Wind, Electric, Laser, Fire. Take the matching crystal for your selected Weapon of Rock.','Break/replace the gator teeth, then shoot the matching crystal target.')
  ],{tools:['iw-spaceland-souvenirs']}),
  phase('seticom','Collect and obtain the SETI-COM',[
    s('calculator','Collect the calculator from the Cosmic Way bench facing the projector, Astrocade upper trashcan by the broken railing, or Kepler’s yellow table above the ERAD. Only one of its three candidates is used in a match.','Find the calculator at one of three sites.',[[886,'Calculator: Cosmic Way bench'],[887,'Calculator: upper Astrocade'],[888,'Calculator: Kepler yellow table']]),
    s('boombox','Collect the quest boombox from the lower spawn bridge, Moonlight Cafe counter beside power, or Underground’s Racin’ Stripes room counter. This pickup is separate from a crafted distraction boombox.','Find the quest boombox.',[[889,'Boombox: lower bridge'],[890,'Boombox: Moonlight Cafe'],[891,'Boombox: Underground counter']]),
    s('umbrella','Collect the umbrella from the bench below Hyper Slopes, Journey’s trap control by the card dealer, or Polar Peak’s Gift Shop counter. After the parts are collected, advance a round and wait for the shaking screen and Polar Peak UFO’s four tones.','Find the umbrella; wait for the next-round UFO event.',[[892,'Umbrella: Hyper Slopes'],[893,'Umbrella: Journey control'],[894,'Umbrella: Polar Peak'],[895,'UFO event landmark']]),
    s('hoff','Speak to Hasselhoff at Cosmic Tunes: Kepler by Octonian Hunter, Kepler by the geysers, or Journey by Mule Munchies. Take his completed SETI-COM.','Receive the device from Hasselhoff.',[[896,'Hasselhoff stand: Octonian Hunter'],[897,'Hasselhoff stand: geysers'],[898,'Hasselhoff stand: Journey']])
  ]),
  phase('defences','Complete three device defences',[
    s('placements','Carry the SETI-COM through its seven candidates: Kepler fountain by Bombstoppers; between Kepler’s purple/orange geysers; Polar Gift Shop; Cosmic Way’s Polar entrance; Journey’s Escape Velocity blood pool; Underground break room; and the Bumper Cars entrance. The correct site shakes the screen and offers placement.','Find the shaking placement prompt.',[[899,'Placement: Kepler fountain'],[900,'Placement: geysers'],[901,'Placement: Polar Gift Shop'],[902,'Placement: Cosmic Way'],[903,'Placement: Escape Velocity'],[904,'Placement: break room'],[905,'Placement: Bumper Cars']]),
    s('defend','Place and protect the device through its displayed countdown: first 60 seconds, next 90, final 120. Recover it after each success and collect the dropped Max Ammo. Advance a round between successful defences. Failure spawns a Brute; take a replacement from Hasselhoff and retry that defence on the same round.','Defend 60 / 90 / 120 seconds; recover the device after each success.'),
    s('return','After the third success, wait one full round before returning the device to Hasselhoff. Collect the four speakers.','Wait a full round, return the SETI-COM and take four speakers.',[[906,'Four speakers']])
  ]),
  phase('speakers','Place and record the speaker layout',[
    s('place','Place speakers on Cosmic Way’s three golden region symbols and in front of the projector gateway. Prepare before interacting with a speaker: activation seals you inside the Cosmic Way/Spawn arena.','Place speakers on three symbols and at the gateway; prepare before activation.',[[907,'Three golden placement symbols'],[908,'Gateway speaker position']]),
    s('layout','Activate a speaker and record each physical position’s Red, Blue, Yellow or Green beam. Assign speaker numbers using the same orientation throughout the attempt; the colours are not permanently assigned to map positions.','Record this match’s four unique speaker colours.')
  ],{tools:['iw-spaceland-speakers']}),
  phase('ufo-sequences','Repeat three UFO colour sequences',[
    s('repeat','Watch every UFO flash, including repeated colours. When the UFO and speakers turn white, enter the full order at the corresponding physical speakers. Complete three successful sequences. Co-op has a shorter response window, so assign positions beforehand.','Repeat the UFO’s flashes three times.'),
    s('retry','If the sequence was missed, let the next display show it again. A wrong or partly entered response can spawn a Brute; clear it and replay the renewed display. Retain the speaker layout and reset only the recorded sequence.','Missed display: observe again. Wrong input: clear the Brute and retry.')
  ],{tools:['iw-spaceland-speakers']}),
  phase('aliens','Break the alien backpack fuses',[
    s('collar','After the clown wave, fight the aliens emerging from the gateway; their number follows player count. Shoot each glowing neck collar. Green/yellow/red are damage-state cues. Keep moving clear of its energy shots and zombies appearing close to you.','Shoot the glowing alien neck collar.',[[909,'Alien encounter'],[910,'Glowing neck collar']]),
    s('fuse-melee','When an alien kneels, reach its backpack and melee the exposed fuse promptly. Confirm the breaking sound and its recovery, then repeat the damage/downing cycle. The last downing kills it without another fuse melee. Finish every alien.','During kneeling windows melee the backpack fuse; finish all aliens.',[[911,'Alien downed backpack window']])
  ]),
  phase('fuses','Upgrade the projector and Weapon of Rock',[
    s('projector-fuses','Take the alien fuses in front of the gateway and install them in the projector. This unlocks the current match’s upgraded projector. Craft your chosen Weapon of Rock if it is still incomplete, then upgrade it here for 5,000 points.','Install alien fuses and Pack-a-Punch a Weapon of Rock.',[[912,'Alien fuses'],[913,'Upgraded projector']])
  ]),
  phase('laser','Destroy the overhead UFO and claim the ending',[
    s('nodes','Shoot four of the five bridge-ring nodes with the upgraded Weapon of Rock. They glow orange. Watch the UFO’s path over the projector and time the fifth node so the charged ring’s upward beam intersects it. A miss requires another charged attempt, not a claimed completion.','Light four ring nodes; time the fifth to hit the UFO.',[[914,'Five Spaceland ring nodes'],[915,'Orange active node']]),
    s('soul-key','After the UFO ignites and explodes, collect the Soul Key in front of the gateway. In Director’s Cut, also take the talisman appearing there after the key. The special final cutscene requires the unlocked Wyler character branch.','Collect the Soul Key; Director’s Cut also grants the talisman.',[[916,'Soul Key'],[917,'Director’s Cut talisman']])
  ])
],[
  phase('head-cutter','Head-Cutter · Wind / yellow crystal',[
    s('battery','Buy Cryo Grenades (350 tickets) and throw one into the Polar entrance yeti’s face. Lure ten zombies through its cold breath and headshot the frozen targets. After the roar, collect the battery from the Gift Shop yeti’s hand.','Freeze and headshot ten zombies; take the yeti battery.',[[840,'Cryo Grenade purchase'],[841,'Polar entrance yeti'],[842,'Battery pickup']]),
    s('plush','Insert three Green coins at Polar Peak’s souvenir station and take the Yeti Plush. Obtain the Wind-core yellow crystal from the gator’s leftmost target, then place all three parts at the Gift Shop Octonian cutout.','Three Green at Polar; Wind crystal; build at Gift Shop cutout.',[[843,'Yeti Plush'],[849,'Head-Cutter assembly cutout']])
  ]),
  phase('face-melter','Face-Melter · Electric / blue crystal',[
    s('battery','With the hub projector open, throw a standard grenade into Journey’s active portal. Relay the returned red grenade toward the hub by picking it up and throwing it before it explodes; each pickup refreshes its fuse. Throw it through the hub gateway and recover the battery where it lands.','Relay Journey’s returned red grenade into the hub portal.',[[850,'Returned red grenade'],[851,'Face-Melter battery']]),
    s('toy','Insert three Blue coins at Journey’s station for the rocket toy. Take the Electric-core crystal from the gator’s second target and assemble at the Escape Velocity cutout.','Three Blue at Journey; Electric crystal; Escape Velocity cutout.',[[852,'Rocket toy'],[853,'Face-Melter cutout']])
  ]),
  phase('dischord','Dischord · Laser / green crystal',[
    s('targets','Pick up zombie-dropped sunglasses and wear them to see five randomly selected targets. Search the Spawn hedge; Cosmic Way ATM, Polar bridge and mountain-mouth sign; Astrocade power, claw machine, Cryptid window, prize floor, Black Hole trashcan and alien cutout; rear store/bumper cars; and the Polar yeti walkway. Shoot all five and collect the battery on the Astrocade dance floor. If hit, recover dropped glasses quickly.','Wear sunglasses, shoot five active targets and take the dance-floor battery.',[[854,'Sunglasses'],[855,'Spawn target'],[857,'Polar bridge target'],[860,'Astrocade power target'],[861,'Claw machine target'],[870,'Dischord battery']]),
    s('disco','Insert one Red, one Green and one Blue coin at the rear Astrocade station. Take its Disco Ball and the Laser-core crystal from the gator’s third target; assemble by the Astrocade prize-counter cutout.','One of each at rear Astrocade; Laser crystal; prize-counter cutout.',[[871,'Disco Ball'],[872,'Dischord cutout']])
  ]),
  phase('shredder','Shredder · Fire / red crystal',[
    s('battery','Shoot the battery on the back-middle of Kepler’s log-ride boat. At the geysers above the river, catch the battery as it shoots upward. Waiting beside one geyser is easier than chasing each burst.','Shoot the log-ride battery and catch it at the geysers.',[[873,'Log-ride battery'],[874,'Geyser battery catch']]),
    s('alien','Insert three Red coins at Kepler’s souvenir station. Take the Alien Souvenir and Fire-core crystal from the gator’s rightmost target; assemble at the Underground/log-ride cutout.','Three Red at Kepler; Fire crystal; Underground cutout.',[[875,'Alien Souvenir'],[876,'Shredder cutout']])
  ]),
  phase('n31l','N31L assistance and K.I.T.T.',[
    s('head','Fit the ice-cream stand’s N31L head below Hyper Slopes onto his Cosmic Way body. Complete his five displayed challenges; interact to summon Hasselhoff. You can pause his current challenge through interaction.','Restore N31L and finish five challenges to summon Hasselhoff.'),
    s('upgrades','After his return, fit the auxiliary battery (check Kepler’s ice-cream cart/bench/trashcan and Polar’s trashcan/cubbies/counter). Finish the next challenge set and summon again. After that return, find the Underground floppy at the HVR workbench, Racin’ Stripes bench or Banshee table. Finish the final set and summon once more; subsequent summons cost 5,000.','Battery set → summon → floppy set → summon; then repeat paid assistance.')
  ]),
  phase('ghosts-n-skulls','Ghosts ’N Skulls · optional permanent-perk route',[
    s('first-skulls','Pop all balloons above Spawn’s Hailstorm. Find successive skulls in sign letters spelling GHOST: G Galaxy Journey/Roller Rampage; H Chromosphere/Hyper Slopes; O Journey Into Space/Cosmic Tunes; S Star Mission/rear Astrocade; T Octonian Hunter/Moonlight Cafe. Stare at each until it breaks. On the dance floor, kill exactly 1 on Green, 9 on Blue, 8 on Pink and 4 on unlit Black in that order; restart at Green after an incorrect count.','Balloons → GHOST sign skulls → dance-floor counts 1,9,8,4.'),
    s('arcade','Complete the skull event on Basketball, Black Hole (50 points), Cryptid Attack, Zombie Zoom and Bowling for Planets. Finish the main quest, keep sunglasses on and use the ring laser to destroy the sky skull over the gateway. Finally bait a Brute’s laser into the upstairs Ghosts ’N Skulls cabinet.','Complete five arcade events; main-quest laser skull; Brute-laser the cabinet.'),
    s('minigame','All players enter the energized cabinet. Entangle floating ghosts and fire them at skulls through three rounds; prioritize escaping red skulls. Three escaped skulls fail a round. Re-energize with the Brute laser to retry. Completion grants permanent perks, with solo Up ’N Atoms excluded.','Clear three cabinet rounds; after failure reapply the Brute laser.')
  ]),
  phase('music-and-characters','Music and character unlocks',[
    s('songs','For the MW1 mix, shoot the teddy pictures on three active Employee of the Month boards. For the MW2 mix, shoot five hidden teddy bears; an absent fifth bear may require a new match. These music hunts are independent of the quest.','Employee-board teddy hunt: three. Hidden-teddy hunt: five.'),
    s('hoff-code','After earning this map’s Soul Key, select it in the lobby and enter Left, Right, Left, Up, Down. Confirm Hasselhoff’s icon before starting; opening another lobby menu can clear the selection.','Hasselhoff lobby code: L R L U D.'),
    s('wyler','After the separate Director’s Cut/Mephistopheles unlock, activate Director’s Cut on Spaceland and enter Left, Left, Down, Up, Up, Right. Completing Spaceland as Wyler after the required finale grants the special ending and Willard’s Test reward.','Unlocked Wyler in Director’s Cut: L L D U U R; finish Spaceland for his ending.')
  ])
],sources('zombies-in-spaceland','zombies_in_spaceland'),{image:photo(808,'Spaceland Spawn power landmark').src})

const rave=guide('iw-rave-in-the-redwoods','iw','Rave in the Redwoods',`${edition} Repair the boat/projector, complete two dismemberment photos and a headshot skull, then enter Turtle Island’s Super Slasher arena. Rave Vision is a consumable view state; the late-round roaming Slasher differs from the killable ritual versions.`,[
  phase('setup','Power and boat repair',[
    s('power','Reach Bear Lodge’s basement through the Mines and switch on power. Collect the handle against the structure near Rave Area Quickies, engine beside Mess Hall’s central pillar, and propeller upstairs in the Lodge’s Tuff ’Nuff room.','Basement power; collect handle, engine and propeller.',[[1008,'Bear Lodge power'],[1009,'Boat handle'],[1010,'Boat engine'],[1011,'Boat propeller']]),
    s('vision','Zombie-dropped pouches are consumed when you interact with a fire to enter Rave Vision. Fairies extend that visit; zombies killed shorten it. Starting at Scene 10, the roaming vision Slasher is dangerous and ordinary weapons cannot kill it. Keep vision hunts distinct from the timed quest rituals.','Use a pouch at a fire; fairies extend Rave Vision.')
  ]),
  phase('projector','Repair the island projector',[
    s('reels','Take the film reel at the docks before boarding the repaired boathouse boat. On Turtle Island collect the reel outside the cabin’s rear door; fit both to the broken projector. Its projected wall portal reaches Pack-a-Punch during the visit window.','Dock reel → boat → rear cabin reel → projector.',[[1012,'Dock film reel'],[1013,'Boathouse'],[1014,'Cabin reel'],[1015,'Broken projector']]),
    s('kevin','Talk to Kevin in the cabin attic. Return by the island’s travel route when you need the main map. Prepare a weapon that removes limbs without instantly killing every target before starting the first ritual.','Speak to Kevin and prepare a controlled limb-damage weapon.',[[1108,'Kevin in the attic']])
  ]),
  phase('bows','Obtain and upgrade Vlad',[
    s('vlad','Take hot dogs from the cabin bathroom bucket. In Rave Vision, throw one at each deer head, then shoot the floating head and collect its glyph: Bear Lodge couch wall, Mess Hall fireplace and Owl Camp’s out-of-bounds cabin. Exit vision and unlock the Lodge crossbow cabinet.','Three hot-dog deer glyphs in Rave Vision; unlock Vlad.',[[1034,'Hot-dog bucket'],[1037,'Lodge deer'],[1038,'Mess Hall deer'],[1039,'Owl Camp deer'],[1040,'Vlad cabinet']]),
    s('statue','Choose the statue for your upgrade: Deer → Whirlwind EF-5, Eagle → Trap-o-Matic, Owl → Acid Rain, Wolf → Ben Franklin. Statue candidates are the obstacle course, climbing wall, Rave trailer, Mines stairs, Owl balcony, Wolf picnic table, Mess/Wolf bench, docks table and beach canoe rack. Place it on the Rave speaker stack and damage nearby zombies until enough turn to red mist; take the charged statue.','Choose a statue; charge it on the Rave speakers.',[[1041,'Obstacle-course statue'],[1043,'Rave trailer statue'],[1044,'Mines statue'],[1048,'Dock statue'],[1049,'Beach statue'],[1050,'Statue charging speakers']]),
    s('ritual','Place the charged statue beside its larger counterpart and kill nearby zombies with an unupgraded Vlad until it is ready. Deer: beach/card dealer or Mess Hall dock. Eagle: Thunderbird wall. Owl: Owl Camp by Mines or the lit sign. Wolf: Wolf Camp by Mines or Mess Hall entrance. Recover the statue to transform Vlad; upgraded bows cannot charge another statue.','Unupgraded Vlad souls at the matching large animal statue.',[[1051,'Deer: Beach'],[1053,'Eagle: Thunderbird'],[1054,'Owl: Mines'],[1056,'Wolf: Mines']])
  ]),
  phase('photo-arms','First photograph · remove arms',[
    s('photo','Take the photo behind Burning Man in the Rave Area. Place it before Thunderbird Amphitheatre’s bonfire. Shoot ten zombie arms off during the timed ritual; ordinary kills alone do not count. Failure removes a random perk and permits another attempt.','Burning Man photo; Thunderbird ritual: remove ten arms.',[[1109,'First photo pickup'],[1110,'Thunderbird placement']]),
    s('slasher','When the photo glows, interact to spawn the killable ritual Slasher. Defeat it, collect the restored photo after the nuke/Max Ammo cue, and speak to Kevin again.','Interact with the glowing photo, kill the ritual Slasher and return to Kevin.',[[1111,'Charged first photograph']])
  ]),
  phase('photo-legs','Second photograph · remove legs',[
    s('photo','Take the next photo by the doorway in Bear Lodge’s upstairs Tuff ’Nuff room. Place it in front of Rave Area Quickies and remove ten legs during the timed ritual. The same failure/retry rule applies.','Lodge photo; Quickies ritual: remove ten legs.',[[1112,'Second photo pickup'],[1113,'Quickies placement']]),
    s('slasher','Interact after the photo glows, kill the ritual Slasher, take the completed photo and speak to Kevin again.','Glowing photo → ritual Slasher → completed photo → Kevin.',[[1114,'Charged second photograph']])
  ]),
  phase('skull','Skull ritual · ten headshots',[
    s('pickup','Take the skull on the Lodge basement floor left of the Magic Wheel. Place it on the beach in front of Slappy Taffy and earn ten headshots in the timed ritual. A failed attempt costs a perk and can be retried.','Basement skull; beach ritual: ten headshots.',[[1115,'Basement skull'],[1116,'Beach placement']]),
    s('complete','Interact with the glowing skull, defeat its Slasher and collect the completed skull. Resupply and finish any upgrades before arming the departure buttons.','Glowing skull → ritual Slasher → completed skull; prepare for departure.',[[1117,'Charged skull']])
  ]),
  phase('departure','Arm the lodge and board together',[
    s('buttons','In the basement, every player uses an unlit button simultaneously. Three are beside the stairs and one by the Magic Wheel; the alarm confirms the activation. The boat now leads to the arena instead of an ordinary island visit.','Use the unlit basement buttons together.',[[1118,'Unlit button indicator'],[1119,'Three staircase buttons'],[1120,'Magic Wheel button']]),
    s('boat','All players board the boat at the same time. This trip commits the match to the Super Slasher encounter.','Board the arena boat together.')
  ]),
  phase('super-slasher','Super Slasher ritual cycles',[
    s('skulls','In Rave Vision, kill near every skull until each rises and shines a beam. Solo uses two, co-op adds more. Recharge falling skulls before their progress resets. Their combined light makes a circle; lure the boss’s walk/slam onto it and shoot the exposed lower torso to exit vision.','Charge every skull, lure the boss into the circle, shoot the glowing torso.',[[1121,'Boss skull'],[1122,'Charged skull'],[1123,'Combined circle'],[1125,'Exposed lower torso']]),
    s('symbols','Shoot each body symbol as it appears until the boss recoils. When it leaps onto the cabin and raises the storm, move behind a rock inside a green circle and defend against skeletons. Follow the safe-circle cue, not a website timer.','Shoot body symbols; shelter in a green-circle rock position.',[[1126,'Body symbol'],[1127,'Storm shelter circle']]),
    s('finish','Repeat the ritual cycles as the dreamcatcher counter falls. Later cycles add arena walls. The third cycle ends with direct damage instead of another storm. Kill the boss and collect the Soul Key to start the ending; in Director’s Cut take the talisman afterwards.','Complete three cycles; final damage; collect Soul Key and applicable talisman.',[[1128,'Dreamcatcher cycle indicators'],[1129,'Soul Key'],[1130,'Director’s Cut talisman']])
  ])
],[
  phase('double-pap-and-smiley','Double Pack-a-Punch and Smiley',[
    s('fuses','If Spaceland’s Soul Key has already unlocked the account benefit, the projector has alien fuses. Otherwise interact with the Spawn computer after power; three rounds later collect the fuses behind it and install them in the projector for this match.','Spawn computer → wait three rounds → install fuses.',[[1016,'Spawn computer'],[1017,'Alien fuses']]),
    s('smiley','After this match’s main quest, or with Director’s Cut equipment access, take Smiley from the Lodge basement rack left of the wheel game. It can kill the otherwise resistant roaming Slasher. Trading it away returns it to the rack.','Main quest / Director’s Cut unlocks the basement Smiley.')
  ]),
  phase('charms','Charm pickups, challenges and effects',[
    s('binoculars','Binoculars: check the Mess Hall path bench or Rave beer boxes. Place them on the Bait & Tackle deck bench. While standing in the card-dealer gazebo, shoot eight eyes: nearby picnic/lakeside rocks, four island totems, cabin attic and Trail Blazers roof. Recover the charm for a close-teammate reload shock effect (co-op).','Binoculars → Bait & Tackle bench → eight eyes from gazebo.'),
    s('shovel','Shovel: Mines cart or archery-side building. Place it at the Mess Hall swamp grave and kill five skeletons; recover it for an explosion when reviving a teammate. Arrowhead: Mess Hall sign or Lodge outside bench. Place it at the archery counter, enter vision and shoot eight successive hay-bale targets; recover it for head aim assistance.','Shovel: grave skeletons. Arrowhead: eight vision archery targets.'),
    s('ring-mask','Ring: Mess Hall stairs or Mines/Bang Bangs stairs. Place it by the Lodge TV and turn both fireplace/stair lamps toward it; recover for melee healing. Bird Mask: dock path or obstacle-course dark corner. Mount it on the Mess Hall frame and shoot the adjacent keys down; it reloads holstered weapons from reserves.','Ring: aim both lamps. Bird Mask: shoot the adjacent keys.'),
    s('ball-fish','8 Ball: upper Mines floor or Rave structure floor. Place on the upstairs Lodge pool table and shoot three white balls; it gives slide contact damage. Fish: Wolf Camp bathroom wall or swamp/beach sewer. Place on the boathouse dock end and grenade the blue water wisp; uninterrupted sprinting builds speed.','8 Ball: three white pool balls. Fish: grenade the blue water wisp.'),
    s('frog-pacifier','Frog: Rave trailer tires or Bait & Tackle chair. Place at the swamp sewer entrance and ground-slam all five spirit frogs in vision (jump and melee at the apex); it enables water sprinting. Pacifier: beach rocks or Owl cabin sink floor. Place on the Mess Hall kitchen counter and finish its zombie lockdown; it damages attackers.','Frog: slam five vision frogs. Pacifier: Mess Hall lockdown.'),
    s('boots','Boots: beach canoe-dock trashcan or Thunderbird beer-box corner. Place at red prints in the Owl/Wolf connecting cabin. Follow the prints there, then Lodge’s Up ’N Atoms doorway and docks/Reaver; return to the original cabin to collect explosive-headshot Boots.','Boots: follow cabin → Lodge → docks prints and recover at the cabin.')
  ]),
  phase('ghosts-n-skulls-2','Ghosts ’N Skulls 2',[
    s('traps','Get exactly 1 Log Swing kill, 9 Woodchipper kills, 9 Rave Stereo kills and 2 Waterfall kills in order. Each trap’s count must come from one activation; redo only a failed trap. Avoid ending the round on the Waterfall’s last targets. Wait a round, read the machine’s vision glyph, exit vision, wait another round and stare at its matching map glyph.','Single trap activations: 1,9,9,2; then machine/map vision-glyph match.'),
    s('glyph-sites','Glyph candidates: island attic, boathouse rafters, beach life buoy, swamp generator, Mess Hall urinal, Owl’s first cabin, Lodge basement window, Rave central tree and archery target. Wrong matching needs the next-round machine read and another round before searching again. Hit the wheel-game skull in the basement; failure waits a round. On a later non-special round, stare at the correct glyphs spelling SKULL.','Use the nine glyph landmarks; knife-wheel skull; spell SKULL in vision.'),
    s('finish','Shoot every boat-gallery skull before it escapes; replay on the next boat ride after failure. Shoot the Lodge cabinet with Ben Franklin to energize it. All players enter and fire matching-colour ghosts at skulls for three rounds. Later rounds hide colours, so remember their actual layout. Three escapes fail; shoot Ben Franklin again to retry.','Boat gallery → Ben Franklin cabinet → three matching-colour rounds.')
  ]),
  phase('music-and-character','Puppet Strings, ammo and Kevin',[
    s('puppet','With power, enter Lodge Rave Vision and aim at ten purple dots until they become symbols: fireplace ceiling beam, computer underside, upstairs blank portrait, pool-table underside, balcony doorway, metal roof over Magic Wheel, bar, Tuff ’Nuff wardrobe shelf, rear boxes and filing cabinets. Multiple vision visits can finish the set.','Aim at ten Lodge vision dots for Puppet Strings.'),
    s('ammo','The basement knife-wheel game has a once-per-round attempt; its regular reward and the Ghosts ’N Skulls skull are separate targets. Director’s Cut’s Scene 1 white mask is another one-attempt lobby-music target.','Keep the wheel-game reward, skull and Director’s Cut mask separate.'),
    s('kevin-code','After completing the main quest at least once, select Rave in the lobby and enter Right, Left, Left, Down, Down, Right. Confirm Kevin’s icon; another lobby menu can clear it.','Kevin lobby code: R L L D D R.')
  ])
],sources('rave-in-the-redwoods','rave_in_the_redwoods'),{image:photo(1008,'Bear Lodge basement power').src})

const shaolin=guide('iw-shaolin-shuffle','iw','Shaolin Shuffle',`${edition} Follow Pam’s rat hunt, collect the Rat King’s eye, brain and heart, then complete their distinct sewer challenges. The phone helper decodes a poster number; the rooftop helper filters possible words without assuming the first candidate is right.`,[
  phase('setup','Power, projector and Shurikens',[
    s('power','Enable power at Spawn subway’s pillar, Disco roof beside Quickies, Park wall left of Deadeye Dewdrops and Main Street subway across from Bang Bangs. Collect a flyer (Dojo trash, Racin’ Stripes chair, Disco roof stool or Pink Cat sidewalk), the coin under sewer Tuff ’Nuff and a film reel (Disco couch, Pink Cat couch, subway boxes, sewer stairs or Rat King’s wall holes).','Four power switches; flyer, sewer coin and film reel.',[[1170,'Main Street subway power'],[1171,'Dojo flyer'],[1172,'Rooftop flyer'],[1173,'Disco flyer'],[1174,'Street flyer'],[1175,'Sewer coin'],[1176,'Disco film reel'],[1178,'Subway film reel']]),
    s('projector','Use the flyer on the Pink Cat front door, the coin on its left private-room door and the reel on the projector. The wall portal reaches Pack-a-Punch during each visit window. On/after Scene 5, speak to Pam in the Dojo, drink a Chi gourd and make fifteen melee kills in that style to unlock Shurikens.','Open the Pink Cat projector; Pam on Scene 5; fifteen Chi melee kills.',[[1181,'Pink Cat entrance'],[1182,'Private room'],[1183,'Projector']])
  ]),
  phase('rats','Follow the rat and earn the key',[
    s('release','Let Pam finish the dialogue that starts the rat hunt. Throw a Shuriken at a cage, then follow the rat and release it from each successive cage. Starting cages include the Dojo ramp and Heebie Geebies hallway. The sixth cage disappears and leaves a yellow circle.','Talk to Pam; release/follow the rat through six cages.',[[1239,'Rat cage: Dojo ramp'],[1240,'Rat cage: Heebie Geebies']]),
    s('key','Kill zombies while they are inside the circle until it vanishes, then defeat the ninjas. Take the gold key at its former center. A player need not count ordinary kills outside the circle as progress.','Circle souls → ninjas → gold key.',[[1241,'Rat defence circle'],[1242,'Gold key']])
  ]),
  phase('soulkey','Open the locker and shoot the four fixed symbols',[
    s('locker','Use the gold key on the symbol-covered locker in the Bang Bangs subway. Shoot the required four symbols in order: left symbol beside the Dojo; second-from-left symbol in the downstairs Disco bathroom; first-from-left beside the Park Volk; then second-from-left at that same Park wall. Wrong order restarts at the first shot.','Locker → Dojo left → bathroom second → Park first → Park second.',[[1243,'Symbol locker'],[1244,'Dojo: first required symbol'],[1245,'Bathroom: second required symbol'],[1246,'Park: third and fourth symbols']])
  ]),
  phase('eye','Collect the eye and find six orange symbols',[
    s('rat-king','Activate the street symbol in front of the Dojo, defeat the Rat King and take his eye. Speak to Pam again and let her finish the next quest dialogue.','Dojo Rat King fight → eye → Pam.',[[1247,'Dojo Rat King marker'],[1248,'Rat King eye']]),
    s('hunt','Scan with the tactical-slot eye and shoot the active orange symbol. Only one exists at a time; after each shot let the eye recharge and search again. Candidates: Spawn train top; barbershop window; Dojo main door; Heebie stage speaker; Bombstoppers police-car door; first uphill spawn window; building by RPR; clothesline near Park wheel; blue Trail Blazers room floor; Disco water tower; skylight air duct; Disco street sign; and behind the Bang Bangs stairs.','Eye-scan and shoot six successive active orange symbols.',[[1250,'Above Spawn train'],[1251,'Barbershop window'],[1252,'Dojo door'],[1253,'Heebie speaker'],[1254,'Police-car door'],[1255,'Uphill spawn'],[1256,'RPR building'],[1257,'Park clothesline'],[1258,'Blue hallway floor'],[1259,'Water tower'],[1260,'Skylight air duct'],[1261,'Disco street sign'],[1262,'Subway stair rear']])
  ]),
  phase('phone','Decode the phone and choose the poster',[
    s('listen','After six symbols, use the ringing non-red phone in either subway. Record its three five-pulse digit groups and let the call finish. Being hit or hanging up early requires another listen. The helper keeps invalid/missed groups in place and preserves leading zeroes.','Listen through the complete phone message; decode three digits.',[[1263,'Phone digit-Morse reference']]),
    s('poster','Collect the Nightmare Summer poster whose lower-left Film Registration matches the decoded number. Candidates: Spawn’s Up ’N Atoms train side, Dojo left, Dojo ramp/wheel, Bombstoppers alley, Disco skylight roof and Main Street subway stair base. A wrong poster restarts the six-symbol hunt and phone observation.','Match the Film Registration number, not poster artwork.',[[1264,'Poster registration close-up'],[1265,'Spawn poster'],[1266,'Dojo poster'],[1267,'Ramp poster'],[1268,'Alley poster'],[1269,'Roof poster'],[1270,'Main Street subway poster']])
  ],{tools:['iw-shaolin-morse']}),
  phase('word','Complete the rooftop word',[
    s('spotlight','Place the poster on the Disco roof spotlight. Explode the projected X window and defeat the spawned ninjas. An initial letter and six shootable Wyler glyphs now appear.','Spotlight poster → explosive X → ninja wave.',[[1271,'Roof spotlight'],[1272,'Projected X window'],[1273,'Initial word letter']]),
    s('letters','Read glyphs with the alphabet reference and record confirmed positional letters. Shoot a candidate next letter only after comparing possible words. Rooftop glyphs are beside the word, behind Quickies’ corner, under wheel scaffolding, beside the clock spawn, back-left wall and the KBS white table. Wrong letters reset the current word; repeated failures can require the next round. A new attempt must clear obsolete mask/rejections while preserving the completed phone stage.','Filter all candidates; shoot confirmed next glyphs; reset only the current word.',[[1274,'Glyph by the word'],[1275,'Quickies corner'],[1276,'Wheel scaffolding'],[1277,'Clock spawn'],[1278,'Back-left wall'],[1279,'White table']]),
    s('complete','The completed word gives a gong and removes the glyphs. Use the next Rat King marker at Park’s RPR Evo wallbuy.','Word completion gong → RPR Rat King marker.',[[1280,'Brain fight marker']])
  ],{tools:['iw-shaolin-word']}),
  phase('brain','Take the brain and start the heart route',[
    s('brain','Defeat the RPR-marked Rat King and take his brain. Return to Pam. Following her next dialogue, watch the cigarette-burn marks over the next three round starts.','Defeat the second Rat King; take brain; Pam; three marked round starts.',[[1281,'Rat King brain'],[1282,'Round-transition cigarette burn']]),
    s('lockdown','The following sequence skips rounds and blocks the Dojo street with fire. Defeat its enemies and take the turnstile piece. The fire clears when the event finishes.','Complete the street lockdown and take the turnstile piece.',[[1283,'Turnstile piece']])
  ]),
  phase('turnstile','Repair the subway and complete the circles',[
    s('gate','Fit the piece to Spawn’s broken turnstile. Climb the Mule Munchies alley ladder and shoot the window glyph; the window closes and creates the first glowing circle.','Repair Spawn turnstile; shoot the ladder-window glyph.',[[1284,'Broken Spawn turnstile'],[1285,'Alley ladder'],[1286,'Window glyph']]),
    s('circles','Kill zombies inside each active circle, then find the next. Candidates: Mule/Bombstoppers alley, private Disco room, Park path, RPR Evo and Spawn’s Hornet area. Continue until the completion gong.','Feed successive circle sites until the gong.',[[1287,'Mule alley circle'],[1288,'Disco private-room circle'],[1289,'Park-path circle'],[1290,'RPR circle'],[1291,'Hornet circle']])
  ]),
  phase('disco','Transfer the disco ball ten times',[
    s('dj','Interact with the upstairs Disco DJ booth. Keep another zombie on the active dance floor before killing the passive zombie carrying the disco ball; it transfers to that waiting target. Repeat ten transfers without ending the round.','DJ booth → ten disco-ball transfers with a receiver on the floor.',[[1292,'Disco DJ booth'],[1293,'Disco-ball zombie']]),
    s('retry','Killing the carrier without another zombie on the floor resets the chain. If it becomes the last zombie of the round, ending the round also resets it. Wait for the replacement carrier and restart a complete chain.','No receiver / round ends: start a new ten-transfer chain.')
  ]),
  phase('heart','Third Rat King and final preparation',[
    s('heart','After the transfer gong, use the Rat King glyph in front of Pink Cat. Defeat him and take the heart. Speak to Pam before entering the sewer lair.','Pink Cat Rat King → heart → Pam.',[[1294,'Heart fight marker'],[1295,'Rat King heart']]),
    s('prepare','Resupply a high-capacity bullet weapon, upgrades and perks before entering. The eye challenge requires many shots before its reward ammo; entering with insufficient ammunition can stop progression. Cards and weapons that help are optional equipment choices.','Enter the sewer with enough bullet ammunition for the eye glyphs.')
  ]),
  phase('finale','Complete the three organ challenges',[
    s('damage','Damage the Rat King until he retreats. Avoid firing continuously into his raised shield; Shurikens can destroy the staff temporarily. Select an organ and then the central floor symbol to start its challenge. Any challenge order is allowed.','Damage until retreat; choose organ + center symbol.'),
    s('eye-challenge','Eye: use scans to reveal pink ceiling/wall glyphs and shoot every revealed mark. Delays allow his shield to add more glyphs. Brain: protect the friendly blue-eyed attackers while they destroy the central brain; do not shoot those allies. Heart: kill a zombie in each acid puddle and clear the entire perimeter before new acid appears.','Eye: revealed glyphs. Brain: protect blue-eyed allies. Heart: clear all acid puddles.'),
    s('finish','Each completed challenge gives a gong and a persistent central Max Ammo. Pick it up when needed, damage the boss into another retreat and start the next organ. After all three, kill the Rat King and collect the central Soul Key after the ending; Director’s Cut also supplies the talisman.','Challenge → ammo → damage → next organ; after three kill and collect the key.',[[1296,'Soul Key'],[1297,'Director’s Cut talisman']])
  ])
],[
  phase('chi-and-travel','Chi styles, travel and double Pack-a-Punch',[
    s('styles','Dragon, Tiger, Crane and Snake have independent upgrade progress. Start with melee kills, then complete the displayed style challenges to unlock Shuriken, special and ultimate tiers. Gourds recharge the ability and eventually respawn; changing style preserves its previous progress. Chi melee/Shurikens break the Torii barriers.','Four independent Chi styles; complete their displayed tier challenges.'),
    s('travel','Break both doors of each travel pair: Racin’ Stripes roof ↔ street right of Blue Bolts; Heebie alley ↔ Main Street subway lower floor. Open the rooftop Torii gates as well. For double Pack-a-Punch, press the projector-room button, exit and take Blue Bolts’ street portal; collect the briefly exposed fuses beside the roof arrival. A miss can be retried after the projector cooldown.','Open paired travel doors; projector button → Blue Bolts portal → fuse pickup.',[[1184,'Projector-room button'],[1185,'Timed fuse box']]),
    s('charge','Put the fuses on the Main Street subway electric rails, let the train run over them, recover and install them in the projector. The upgrade lasts this match.','Train-charge fuses; install in projector.',[[1186,'Fuse charging rails']])
  ]),
  phase('katana-and-nunchakus','Katana and Nunchakus unlocks',[
    s('katana','Completing Pest Control at least once makes the Dojo Katana available in future matches for 10,000 points; it is free in the match where you finish the quest. It can be Pack-a-Punched.','Quest unlocks Dojo Katana.'),
    s('clock-items','For Nunchakus, open both travel pairs and all Torii gates. Take your character’s item at Blue Bolts. Trigger the Disco clock, melee that item, take the portal and melee its second wooden-stack counterpart. Next use the subway clock: portal to the Bombstoppers dumpster script, return and melee the Bang Bangs floor script. Then roof clock: drop through skylight to the Rack-9 book, return and melee the roof ledge book. A failed clock-item stage waits for the next round.','Clock item stages: Blue Bolts pair → scripts → books.'),
    s('tv','Set your character’s TV to its cartoon: Sally Spawn train, Andre Heebie, Poindexter RPR roof, AJ Blue Bolts. Defeat the ninja/zombie wave until colour bars appear. Quickly punch roof clock, Disco clock, then subway clock; the rewarded Fire Sale’s first Wheel draw grants Nunchakus. Timeout in this final clock chain can be retried immediately.','Character TV lockdown → roof/Disco/subway clock punches → first Fire Sale draw.')
  ]),
  phase('mahjong-equipment','Mahjong craftable equipment',[
    s('tables','Find the three missing matching tiles for a named equipment table, carrying one tile at a time. All returned tiles create its pickup, which respawns two rounds after collection. Toy Robot table: Dojo bus (bus roof, Spawn/Dojo stairs, Tuff ’Nuff crate). Boombox table: Racin’ Stripes stair base (Dojo ramp bricks/spool, top stairs, roof chute bucket).','Return three table-matching tiles; one carried at a time.'),
    s('other-tables','Zom-B-Gone: Bombstoppers table and nearby fence/private Disco/portal/pallet/Heebie sites. Lava Lamp: Park wheel table and R-VN table/stairs, Volk garbage and nearby house. Sentry: Disco subway entrance table and entrance, Pink Cat van, wheel pallet, coat-check counter, upstairs pillar or Tuff ’Nuff stairs. These collections are separate from the 14-tile Skullbuster hand.','Zom-B-Gone, Lava Lamp and Sentry use their own three-tile table collections.')
  ]),
  phase('skullbuster','Skullbuster · six skulls and cabinet game',[
    s('clean','Take cleaner (Disco pole table, subway lockers or Heebie stage) and cloth (Disco roof pallets, Rat King throne or Mule ladder scaffold), then clean the upstairs Disco cabinet. On its roof collect/place enough tiles for a fourteen-tile Mahjong hand: four triples (identical or consecutive) and one pair, with no more than four identical tiles. Carry one at a time; swap an unusable extra for another.','Clean cabinet; four triples + one pair in the fourteen-tile roof hand.'),
    s('numbers','Use the source’s candle-marked glass panes to draw 1 on the Disco street window, 9 opposite Racin’ Stripes roof, 7 in Trail Blazers’ hall and 2 beside the Dojo. A wrong pane or timeout retries that number next round. At the start of a round, jump the white-circle path from RPR without overshooting; touch the final skull. A fall waits for the next round.','Glass numbers 1,9,7,2; then RPR white-circle jumps.'),
    s('train-phone','Jump into the skull on the passing Bang Bangs train. This deliberately downs you: prepare a teammate revival or solo Up ’N Atoms first. At an interactable subway phone dial 555-0152 and stay through the completion sound; damage interrupts it.','Prepare a revive; train skull jump; full 555-0152 phone call.'),
    s('game','All players enter Skullbuster. Entangle coloured cubes and colour question-mark cells to form three-skull lines or L shapes. Preserve the possible groups for other colours; three wrong placements fail and require another 555-0152 call. Finish three rounds for permanent perks (solo Up ’N Atoms excluded) and packed Wheel weapons for this match.','Form matching three-skull groups; after three strikes repeat the phone call.')
  ]),
  phase('music-and-pam','Music, Savage calling card and Pam',[
    s('music','Interact with seven active hidden radios for Cats on the Boulevard. Check the Dojo robot-table trash and Heebie entrance pallet, back-room crate, roof tire/wood/chute areas, Park electrical/trash locations, R-VN table, Disco roof/desk trash and sewer pipe. The radio about David Savage also begins a separate calling-card route.','Interact with seven active radios; note the David Savage recording.'),
    s('savage','After the Savage recording, stare at the rooftop Savage Industries clock cipher. Interact with all twelve subway standing trashcans (five Main Street, seven Spawn), then reveal ciphers at the Mule dumpster, street stop sign, inaccessible Trail Blazers staircase ceiling and Spawn bank-side gate. The Tuff ’Nuff wall cipher is source-reported as an online server-time window of midnight–1 a.m. Eastern; changing the local clock is not a reliable method. Finally aim at the Rat King chair for the reward.','Clock → twelve trashcans → four ciphers → timed Tuff ’Nuff cipher → throne.'),
    s('pam-code','After earning this map’s Soul Key, select Shaolin in the lobby and enter Up, Up, Right, Left, Down, Left. Confirm Pam’s icon before starting.','Pam lobby code: U U R L D L.')
  ])
],sources('shaolin-shuffle','shaolin_shuffle'),{image:photo(1243,'Main Street subway symbol locker').src})

const attack=guide('iw-attack-of-the-radioactive-thing','iw','Attack of the Radioactive Thing',`${edition} Assemble the body, open the garage, build the bomb and produce the radio-confirmed chemical. Life-ray order, pressure-gauge values, chemistry calculations and the belly bomb code are separate observations. Prepare those records before the irreversible beach departure.`,[
  phase('setup','Power and Elvira’s projector',[
    s('power','Take the switch handle from the zombie hand on the beach by the OSA. Fit it to the Power Station box near the drive-in. Take Elvira’s book from the Ice Cream Parlour backroom safe and give it to her at the TV Studio.','Beach switch handle → Power Station; Parlour book → Elvira.',[[1364,'Beach switch handle'],[1365,'Power Station box'],[1366,'Elvira book']]),
    s('vial','Take the Market cleaver from behind the Deadeye Dewdrops counter. Fill Elvira’s vial with cleaver kills (read scoreboard progress), then return it to summon her. Lead her to the closed TV Studio portal so she opens it. Later projector entrances alternate behind the Parlour and at the RV Park, marked by a lightning storm.','Cleaver-fill vial; summon Elvira; lead her to the projector portal.',[[1369,'Initial closed portal'],[1370,'Open projector portal'],[1371,'Active portal storm'],[1372,'Parlour portal'],[1373,'RV Park portal']])
  ]),
  phase('equipment','Required tools and Seismic Wave Generator',[
    s('crowbar','Take the crowbar in Motel’s maintenance room. Retain access to the Market cleaver for the radioactive leg and fat ingredients. Repair the Market freezer trap using the part on Gas Station’s left-side boxes.','Crowbar, cleaver and repaired Market freezer trap.'),
    s('seismic','Build the Seismic Wave Generator at the Parlour backroom bench: blueprint at its rear door, coil by the back corner, leg on the outside bench and metal part by the drive-in playground porta-potties. Return parts individually when your carry slot is occupied. It raises the buried beach arm in the next phase.','Four Parlour/playground parts → Seismic Wave Generator.')
  ]),
  phase('body','Assemble six body parts and three mirrors',[
    s('head-torso','In the projector room press the wall button before leaving; the alternate return takes you inside the locked RV. Take the head by its large front window. In Market, activate the repaired freezer trap, crowbar the hanging pig beside the torso during/after freezing, then recover the torso.','Alternate projector exit: RV head. Freezer trap + crowbar: torso.',[[1375,'Alternate exit button'],[1433,'RV head'],[1434,'Hanging pig'],[1435,'Frozen torso']]),
    s('arms','Take the left arm from the RV firepit beside the Volk. Put a Seismic Wave Generator close to the beach arm that held the switch handle; avoid covering the arm itself. Let its pulses raise the arm until it can be collected.','RV firepit arm; Seismic pulses raise the beach arm.',[[1436,'RV firepit arm'],[1437,'Buried beach arm']]),
    s('legs','Cleaver-kill a radioactive soldier zombie, available from Scene 5, for the left leg; if it does not drop, check where the first such kill happened. Cook a standard grenade beneath the hanging leg on the Snack Shack/TV Studio path’s final left tree, then collect it from the ground.','Radioactive cleaver kill: left leg. Tree grenade: right leg.',[[1438,'Radioactive soldier'],[1439,'Dropped leg'],[1440,'Hanging tree leg'],[1441,'Fallen tree leg']]),
    s('mirrors','After summoned Elvira leaves, take her couch mirror. Crowbar the RV bathroom mirror and take the sink fragment. Crowbar the passenger-side mirror from the roofed white car on Main Street. At Spawn, put six body pieces on the upright bed; fit the broken mirror at the pill-bottle table, Elvira’s mirror on the zombie-window crates and car mirror on the crate beside Up ’N Atoms.','Elvira / bathroom / white-car mirrors; fit body and mirrors at Spawn.',[[1442,'Elvira couch mirror'],[1443,'RV bathroom mirror'],[1445,'White car side mirror'],[1447,'Upright body bed'],[1448,'Broken mirror position'],[1449,'Elvira mirror crates'],[1450,'Car mirror crate']])
  ]),
  phase('life-ray','Read the reels, activate life and reverse death',[
    s('punch-card','Take the punch card from the Parlour backroom desk and fit it to Spawn’s machine. At the TV Studio shelf, read five film reels left to right, counting the floor reel as position three. Their digits are a permutation of 3,4,5,6,8. Record the observed order before entering it.','Parlour punch card; read TV Studio reels, floor reel third.',[[1451,'Punch card'],[1452,'Spawn machine'],[1453,'Five film-reel order'],[1454,'Reel number close-up']]),
    s('life','Interact as each required number’s light illuminates; lights count from zero at the left. A wrong sequence/three strikes or damage ejects you, but the correct sequence remains the same and can be retried. After acceptance, activate the machine again to create the zombie.','Enter the five-digit order at lit-number timing; activate life ray.'),
    s('death','Enter the recorded order in reverse, then activate again for the death ray. Collect the resulting key and open the Gas Station garage door. The later safe/bomb code is not reversed.','Reverse only the life-ray order; death ray → key → garage.',[[1455,'Garage key'],[1456,'Garage door']])
  ],{tools:['iw-attack-codes']}),
  phase('nuke','Build chemistry equipment and bomb',[
    s('chemistry-parts','Collect the chemistry tube from the Market backroom couch, gauge from the RV picnic table nearest Mule Munchies and screen from the picnic table on the RV/beach path. Fit them to the empty garage table.','Tube, gauge and screen → chemistry table.',[[1457,'Chemistry tube'],[1458,'Chemistry gauge'],[1459,'Chemistry screen'],[1460,'Garage chemistry table']]),
    s('bomb-parts','Collect three different bomb parts: under the red car on the TV Studio/Motel road, at the stream’s end below the beach wooden bridge and beyond the TV Studio right fence/gate from Snack Shack. Fit all three to the garage nuke.','Red car, beach stream and TV fence parts → garage bomb.',[[1461,'Bomb part: red car'],[1462,'Bomb part: beach stream'],[1463,'Bomb part: TV Studio fence'],[1464,'Assembled nuke']])
  ]),
  phase('safe','Set pressure gauges and save the bomb code',[
    s('desk','Prone at the Market backroom desk’s left side and read its four numbers. With the crowbar, stop each of the four pressure hands on one number: Gas Station rear, Snack Shack right side, Power Station rear and Motel maintenance room. Any number can be assigned to any gauge; use every required desk value. A wrong stop can be reset with another melee.','Read four desk values; stop four gauges with the crowbar.',[[1465,'Desk number landmark'],[1466,'Desk underside viewpoint'],[1467,'Gas Station gauge'],[1468,'Snack Shack gauge'],[1469,'Power Station gauge'],[1470,'Motel gauge']]),
    s('bomb-code','Take the paper from the now-open safe. Read the separate four-digit sequence in the scoreboard and save it outside the game before entering the boss: the arena does not let you consult that menu when needed. Keep any leading zero and use its original order.','Open safe; save the four-digit belly bomb code.',[[1471,'Open Market safe'],[1472,'Scoreboard bomb-code display']])
  ],{tools:['iw-attack-codes']}),
  phase('o-and-filter','Determine O and the reaction filter',[
    s('m','Read M on the Motel office wall beside the window. At the TV Studio control panel, choose Red, then Green and Blue. Inspect the four O markers in each filter: Gas Station front door, Market backroom couch wall, concrete bridge underside and locked RV refrigerator (visible through its front window).','Read M; check all four O markers in Red, Green and Blue.',[[1473,'Motel M number'],[1475,'Colour filter control'],[1486,'Gas Station O marker'],[1487,'Market O marker'],[1488,'Bridge O marker'],[1489,'RV O marker']]),
    s('o','Exclude a candidate wherever its marker shows O ≠ value. The true O remains equal in all three filtered views. Multiply that confirmed O by M, then compare the product with the actual three-colour TV bands beside Elvira; the middle range includes its boundaries. Record the required colour and read all subsequent diamonds in that filter.','O equal in all colours; M × O; compare with observed TV bands.',[[1484,'Equal marker example'],[1485,'Not-equal marker example'],[1474,'Observed TV bands']])
  ],{tools:['iw-attack-chemistry']}),
  phase('radio','Identify the positively endorsed final compound',[
    s('battery','From Scene 10, take a zombie-dropped battery and repair/listen to the radio at Power Station’s porta-potty or the Motel couch. One radio describes manufacturing; the other judges the five candidate compounds. Cycle its recordings, advancing a round when it needs rewind.','Battery → two radio sites; listen to the effectiveness recordings.',[[1478,'Radio battery'],[1479,'Power Station radio'],[1480,'Motel radio']]),
    s('chemical','Choose only the compound explicitly endorsed for the mutated-crab problem. Negative recordings, including the “crude solution” wording, are not the answer. Use the tool’s five named choices; if the finished chemical is refused by the nuke, re-listen rather than choosing by convenience.','Record the affirmative chemical; do not use a negative/crude-solution line.')
  ],{tools:['iw-attack-chemistry']}),
  phase('chemistry','Make the complete dependency route',[
    s('diamonds','In the confirmed reaction colour, read each needed ingredient’s top and left diamond numbers. Boards: Spawn tent hall; TV Studio by Bang Bangs; RV beside Mule Munchies; beach below the RV path; Gas Station garage; dirt path behind Market toward power. The tool lists the needed board for raw and crafted ingredients. Changing the observation filter requires fresh values.','Read needed top/left diamonds in the required filter.',[[1493,'Spawn board'],[1494,'TV Studio board'],[1495,'RV board'],[1496,'Beach board'],[1497,'Gas Station board'],[1498,'Market rear board']]),
    s('route','Use the dependency route from the selected final compound. Collect orange/raw ingredients at their pickup landmarks and manufacture intermediate compounds in order. A crafted intermediate’s own board diamond is different from the keypad code used to create it. The recipe plate is credited to RayPoopertonIII.','Follow only the selected compound’s intermediate reactions.',[[1499,'Recipe and ingredient sheet · RayPoopertonIII'],[1391,'Racing Fuel'],[1394,'Vodka'],[1403,'Insect Repellent'],[1407,'Drain Opener']]),
    s('calculate','For each reaction, place its ingredients on the garage squares and input the sum of every top + left pair minus O once. Press the large button. Gas effects and a new chemical at the garage’s right confirm success; damage/failure means recheck ingredients, colour and numbers. Mark “made” only after this cue, then carry the resulting ingredient into the next reaction.','Each reaction: sum top/left values − O once; confirm successful output.',[[1481,'Ingredient squares'],[1482,'Reaction keypad'],[1483,'Reaction button']]),
    s('load','Take the final radio compound and give it to the assembled bomb. Refusal means the desired compound was misidentified; confirm the radio again before remaking the route.','Load the accepted final compound into the nuke.')
  ],{tools:['iw-attack-chemistry']}),
  phase('departure','Charge and enter the beach arena',[
    s('prepare','Save the four-digit bomb code, refill ammunition and finish upgrades before departure. All players interact with the loaded nuke to charge it, then interact again to commit to Crog-Zilla.','Resupply; save bomb code; synchronize nuke charge and departure.')
  ]),
  phase('crogzilla','Escort, chest damage, acid and belly code',[
    s('escort','Stay near the beach cart to push it into the water. Shoot descending eggs/fireballs before they force you away. The nearby OSA Max Ammo is a resupply landmark. Once the bomb launches into Crog-Zilla, watch for raised-claw slams and glowing-head beam attacks and move clear of their lanes.','Escort the bomb; shoot eggs; avoid raised-claw slams.',[[1500,'Beach bomb cart'],[1501,'Boss ammunition landmark']]),
    s('chest','Shoot the exposed glowing chest using a beach death ray: OSA ledge, RV path, main-street path or concrete bridge. After the first confirmed hit, the Spartan SA3 can also damage that spot. Continue until the chest stops glowing and interact with the empty cart together to begin the next stage.','Death-ray exposed chest; after confirmed hit, Spartan also works.',[[1502,'Exposed chest'],[1503,'Spartan wallbuy'],[1504,'Death ray: OSA'],[1505,'Death ray: RV path'],[1506,'Death ray: main street'],[1507,'Death ray: bridge']]),
    s('lasers','Defend while radiation pushes the team toward the wall below the bridge. When it clears and lasers appear, all players jump/slide through the obstacle route and reach/interact with the cart before its in-game deadline. A missed player sends the team into another acid/laser cycle; prepare for the renewed attempt.','Survive acid; all players cross lasers and interact with the cart.',[[1508,'Empty cart'],[1509,'Radiation phase']]),
    s('belly','Inside the belly, every player enters the original saved four-digit safe code at the illuminated-number machine. Each has their own strikes/time window; one teammate cannot enter it for another. Failure repeats acid and lasers. Complete all entries for the ending; the Soul Key is automatic here, while Director’s Cut’s talisman is collected on the beach.','Every player enters the saved bomb code; failure repeats the obstacle cycle.',[[1510,'Director’s Cut beach talisman']])
  ],{tools:['iw-attack-codes']})
],[
  phase('double-pap','Double Pack-a-Punch and travel pads',[
    s('fuses','Take the crowbar into the alternate locked-RV projector exit. Break the cabinet above its window and recover the fuses before you are returned. Refill Elvira’s vial with the cleaver, place fuses at the shaking Power Station floor spot and electrify them with the repaired power trap. Recover and install them in the projector. A missed RV pickup can be retried on another visit.','Alternate RV exit → crowbar fuses → full vial → power trap → projector.',[[1376,'RV fuse cabinet'],[1377,'Uncharged fuses'],[1378,'Power Station fuse spot']]),
    s('pads','Activate all four travel pads. Their fixed cycle is Power roof → TV Studio → RV Park → Main Street/Gas Station → Power. Each used pad has its own cooldown. The repaired trap parts are in the power-area bus trashcan, Gas Station boxes, RV bathroom picnic table and Motel/TV white truck.','Activate the four travel pads; repair traps with their own parts.')
  ]),
  phase('mad-and-buildables','M.A.D. upgrades and useful craftables',[
    s('mad','Obtain M.A.D. from the Wheel; it does not use Pack-a-Punch. Crowbar open its three upgrade boxes: RV men’s-bathroom wall (grip), TV Studio exterior (crank) and Gas Station rear brick wall (plunger). The crank allows held-aim charging; swapping weapons cancels charge. Plunger refills at radioactive eggs, which take several rounds to return.','Wheel M.A.D.; crowbar grip/crank/plunger boxes.'),
    s('devices','Hypnosis: Market safe-room blueprint plus red-crate bulbs, liquor-shelf cage and produce/bread-floor radio; assemble at its backroom bench. Mind Control: Motel maintenance blueprint, TF-141 ground battery, pool-chair jukebox and office-stair speaker. Violet Ray: power-bus bench blueprint, nearby barrel bulbs, switch-cart lamp and Market-rear dumpster antenna. Each device requires its blueprint and three parts, with one carried part at a time.','Hypnosis / Mind Control / Violet Ray each use blueprint + three parts.'),
    s('elvira-upgrade','Once the garage is open, give Elvira the pages on its shelf. Her subsequent summons gain the lava attack. This upgrade is separate from portal access and the mirror pickup.','Garage pages → Elvira’s later summon attack upgrade.')
  ]),
  phase('skull-hop','Skull Hop · six skulls and spelling',[
    s('skulls','Shoot five active skulls among these candidates: power-room chair, screen-rear dumpster, Market bottom shelf, bridge bus tire, TV window, Snack Shack bathroom, Mason’s sign, Change Chews dumpster, offshore rock and Motel upper-right balcony. A default/variable-scope sniper makes distant sites easier.','Shoot five active skulls, using a scoped weapon for distant sites.'),
    s('container','Put the Gas Station floor canister into the Parlour radiation puddle and stay nearby until its prolonged ready sound (roughly five minutes). Collect promptly; leaving pauses progress and delaying pickup can reset it. Do not replace the scorestreak-slot canister before the next step. Repair the Motel pool trap, place the canister in the pool and kill exactly sixteen zombies in one activation.','Radiation canister charge → collect → one pool-trap activation with sixteen kills.'),
    s('spell','Read the word above the Parlour UDM bench. Translate the four swingset glyphs in physical order from Slappy Taffy toward the Parlour. Use the spelling tool’s shortest position sequences; shoot the top-right screen glyph after each letter to lock it. A mistaken bottom row can be reset by filling four symbols then adding a fifth. Zero remainder wraps to Z.','Wall word + four swingset glyphs; commit each calculated letter.'),
    s('portraits','Melee the RV propane-table “Don’t Blink” paper. Retrieve a canister from the pool, place it before a Wyler portrait, activate the portrait and melee the canister. Stay inside its bubble and shoot at least seven ghosts before it ends. Repeat with fresh canisters at Gas Station rear, Market safe room, Parlour and Motel office. A failed bubble can be retried.','Don’t Blink; four portrait bubbles; at least seven ghosts inside each.'),
    s('cabinet','Confirm the fifth cabinet skull, then shoot the machine with a crank-upgraded charged M.A.D. The source reports a retry-blocking cabinet bug; its Skull Hacker workaround is optional card-dependent recovery, not a main-quest prerequisite. Enter together and use platform colour to match the displayed side bars when firing cubes at skulls. Stop when the bars flash, move to the new colour and clear three rounds. Wrong hits/falls can make red escapees; a red cube can save them before escape.','Charged M.A.D. cabinet; match platform colour to side bars; three rounds.')
  ],{tools:['iw-attack-skull-hop']}),
  phase('music-diaries-and-elvira','Music, diaries, calling cards and Elvira',[
    s('music','Collect five records: power-building sheet-metal side, Market cash register, Snack Shack blue tarp, Motel/Bombstoppers trashcan and open RV table. Brachyura Boogie then plays from jukeboxes. The Director’s Cut Scene 1 TV Studio camera white mask unlocks separate lobby music.','Five records for Brachyura Boogie; DC first-scene camera mask is separate.'),
    s('diary','Use the Motel pool-side diary as an ordinary actor. Before quest completion it has one entry per match; after completing the quest in that same match it permits repeated entries for Dear Diary. The book cannot be used while playing Elvira.','Complete the quest in the same match for repeated diary entries.'),
    s('cards','Message Rerouted: snipe the hillside rock turnstile on the Gas Station/beach path. Make ’Em Squeal: cleaver Market’s leftmost hanging meat for Fat, keep that ingredient, then approach the middle RV toilet already prone. Its first proximity trigger is a single attempt per match; replacing Fat or arriving upright defeats that attempt.','Rerouted: hillside turnstile. Squeal: carry Fat and approach the toilet already prone.'),
    s('elvira-code','After earning this Soul Key, select Attack in the lobby and enter Down, Right, Down, Left, Up, Right. Confirm Elvira’s icon before starting.','Elvira lobby code: D R D L U R.')
  ])
],sources('attack-of-the-radioactive-thing','attack_of_the_radioactive_thing').concat([{label:'Independent chemical reference · Wells Logan',url:'https://wellslogan.com/aotrt/dist/'},{label:'Original Skull Hop spelling reference',url:'https://www.zombieslayamr.com/pages/aotrt/aotrt_spelling_bee.html'}]),{image:photo(1464,'Assembled garage nuke').src})

const dc={branches:['directors-cut']}
const beast=guide('iw-the-beast-from-beyond','iw','The Beast from Beyond',`${edition} Restore N31L, recover four coded disks, hack the handle board and install him in the projector. Survive the cryptid arena and both Mammoths. Select the separate Director’s Cut branch for account preparation and the Mephistopheles finale.`,[
  phase('directors-cut-preparation','Director’s Cut · account prerequisites',[
    s('soul-keys','Earn the five ordinary map Soul Keys. Start a new match and interact with the Soul Jar in any projector room; the lobby now allows Director’s Cut. These are account milestones and must not be erased by resetting the current Beast guide.','Five ordinary Soul Keys → new match → projector Soul Jar → Director’s Cut.'),
    s('talismans','In Director’s Cut, repeat Spaceland, Rave, Shaolin and Attack, explicitly collecting their four ending talismans. With all four owned, complete Beast in Director’s Cut to reach Mephistopheles after the Mammoths. Practice in Boss Battles is optional and does not grant these live progression rewards.','Collect the first four DC talismans; finish Beast in DC for Mephistopheles.'),
    s('loadout','Prepare a reliable damage weapon, ammunition plan and an Entangler for the finale’s soul throws. Helpful variants/cards can shorten encounters, but they are not universal game-entry requirements. Director’s Cut already supplies its projector fuses and enhanced starting equipment.','Prepare damage, ammo and Entangler; optional cards remain optional.')
  ],{...dc,stateScope:'account'}),
  phase('power','Retrieve N31L’s head and restore power',[
    s('head','Drop through the Ops Center’s central hole onto its bottom ledge; do not fall beyond it. Take N31L’s head at the passage end and fit it into Spawn/Staging’s wall slot. Power activates and ordinary zombies replace the initial cryptids on the next round.','Ops hole ledge → N31L head → Spawn wall slot.',[[1559,'Ops Center hole'],[1560,'N31L head'],[1561,'Spawn head slot']])
  ]),
  phase('bridge','Reach the theater and repair the bridge',[
    s('theatre','Activate the upper Cargo Bay catwalk button. Its turret opens the theater portal. In the theater, activate the street and Racin’ Stripes-alley ground symbols for the other facility returns.','Cargo catwalk button opens theater; activate its return portal symbols.',[[1574,'Cargo theater button'],[1575,'Cargo portal'],[1576,'Street return portal'],[1578,'Alley return portal']]),
    s('scrap','Collect scrap from Cargo Bay’s lowest level left of the stairs, Medical Bay right of Blue Bolts and the theater street’s burning car right of the portal. Each pickup can spawn cryptids. Fit three pieces to the Exterior’s broken bridge and enter the projector portal across it. Its first return can spawn the Phantom needed for a disk.','Three scrap pieces → Exterior bridge → projector portal.',[[1562,'Cargo scrap'],[1563,'Medical scrap'],[1564,'Burning-car scrap'],[1565,'Broken Exterior bridge']])
  ]),
  phase('entangler','Earn the Entangler through Skullbreaker’s first two skulls',[
    s('power-box','Grenade the skull power box at one active candidate: Flooded Room above the Medical stairs, Ops above Bombstoppers or Cargo above P-LAW’s stairs. Shoot the revealed skull.','Grenade the active power box, then shoot its skull.'),
    s('lockdown','Stand each player on a different Cargo red X: upper P-LAW catwalk, lower P-LAW stairs, beneath the theater-portal catwalk and near X-Eon. Stay on the resulting circles during lockdown until the central skull rises to the top. Leaving fails and requires the next round. Quickly jump into the moved skull before it disappears; a missed pickup also retries next round. Take the Entangler appearing in the center.','Cargo X lockdown; stay in circles; jump into the raised skull; take Entangler.',[[1650,'Cargo X: upper catwalk'],[1651,'Cargo X: stairs'],[1652,'Cargo X: below theater portal'],[1653,'Cargo X: X-Eon'],[1654,'Rising lockdown skull'],[1655,'Skull pickup after lockdown'],[1656,'Entangler pickup']])
  ]),
  phase('disks','Recover four symbols and insert them in order',[
    s('first-two','Recover the disk from the first killed Phantom after projector access, and the fixed disk in the snow at the pillar left of the projector portal. Only one disk is held at a time; record its visible symbol before carrying it to N31L.','First Phantom disk and snowy projector-pillar disk.',[[1595,'Fixed projector-pillar disk']]),
    s('vent','At the Proteus hallway’s fenced red room, Entangle the floor disk and launch it into the vent while smoke is visible. A miss respawns it for immediate retry. After the successful suction, look at lower vents near Spawn’s Wheel, cafeteria freezer, both Cargo-door hall sides, red-room fence, stair top and Ops door. The relocated disk stays there.','Entangle the red-room disk into the smoking vent; find its exit.',[[1596,'Red-room fence'],[1597,'Vent'],[1598,'Smoke timing'],[1599,'Red-room disk'],[1600,'Exit: Spawn'],[1601,'Exit: cafeteria'],[1602,'Exit: Cargo hall'],[1605,'Exit: stair top'],[1606,'Exit: Ops door']]),
    s('helmet','Entangle a hallway space helmet and shoot it through the Medical forcefield at the active monitor above the microscope. A miss allows another helmet attempt. Take the disk on the table left of the broken monitor.','Space helmet → active Medical monitor → table disk.',[[1607,'Space helmet'],[1608,'Medical forcefield'],[1609,'Target monitor'],[1610,'Medical disk']]),
    s('order','Select all four actual disk glyphs in the helper. Insert its agreed sequence into slots 1–4 in front of N31L. The modern chart is read left to right. Success flashes the HUD yellow/red and makes N31L evil; wrong insertion can return disks with changed glyphs, so clear stale observations and record the new set.','Match four glyphs; insert left-to-right; reobserve after a rejection.',[[1611,'Modern disk reference order']])
  ],{tools:['iw-beast-disks']}),
  phase('handles','Move the button and hack N31L’s board',[
    s('button','Entangle the theater button behind the Brute cutout and fire it into the concession area’s Beast poster. Dropping/missing returns the button to its wall. In the opened Medical room, prone under the disk desk and press the transferred button. The sixteen-handle panel opens in the dead-cryptid room.','Theater button → concession poster → Medical desk button.',[[1612,'Theater button'],[1613,'Beast poster target'],[1614,'Under-desk button']]),
    s('snapshot','Take an initial 4×4 snapshot and freeze it before flipping. Interact with every handle initially horizontal even if it rotates while other handles are used. After completing that set, take a fresh snapshot and repeat for any remaining horizontals until all are vertical. The recorder preserves observations and actions separately; no unverified neighbor-toggle formula is used.','Freeze initial horizontals, flip that set, then reobserve until all vertical.',[[1615,'Physical handle board']])
  ],{tools:['iw-beast-handles']}),
  phase('escort','Carry and install the hacked head',[
    s('carry','N31L’s hacked window is limited; Entangle him and carry him to the projector room. Closed doors follow the direction he is looking; orient the carried head toward a required doorway and continue through the map. If his window expires and he becomes evil again, revisit the handle panel to hack him again.','Carry hacked N31L; point his gaze at blocked doors; re-hack after expiry.'),
    s('install','Shoot him into the computer right of the projector. Prepare and synchronize before interacting with the installed computer: this begins the cryptid arena. Optional source-described movement exploits are not necessary to follow the normal gaze route.','Install at the projector computer; resupply before arena interaction.',[[1616,'Projector-room N31L computer']])
  ]),
  phase('cryptids','Survive the portals and terminal countdown',[
    s('rhinos','In the alternate Cargo arena, identify the unlimited yellow ammo box and the sloped roofed crate before fighting. The laser opens four Rhino crates, followed by alternating portal waves and then all portals. Keep a path to ammo and use solid cover against the targeting laser.','Four Rhinos → portal waves; keep the ammo/crate routes open.',[[1617,'Unlimited ammo box'],[1618,'Sloped roofed crate']]),
    s('terminals','When three monitors illuminate, use all three promptly to shut the portals: behind/left of ammo, behind/right of ammo and below the sloped crate. A reactivated monitor needs another interaction. The laser then opens the opposite crate’s terminal.','Switch off all three monitors before they reactivate.',[[1619,'Left ammo-side terminal'],[1620,'Right ammo-side terminal'],[1621,'Sloped-crate terminal']]),
    s('countdown','Interact with the exposed terminal and survive its displayed countdown from 99. It is not a 99-second stopwatch. When it reaches zero, its display scrambles and sparks; interact again to despawn the wave and expose the Mammoth crate.','Displayed 99 countdown → scrambled/sparking terminal → interact.')
  ]),
  phase('mammoths','Defeat both Mammoths and confirm the ending',[
    s('fight','Attack both blue Mammoths, using the refill box whenever needed. Their charges are severe and their persistent blue fire can block a choke point; avoid damaging them in the only remaining passage. Preserve space to evade instead of anchoring the fight on the ammo doorway. Damage-oriented card/variant combinations are optional.','Kill both Mammoths while preserving safe routes through their blue fire.',[[1622,'Mammoth crate above ammunition']]),
    s('ending','Ordinary completion plays the ending and records the Soul Key automatically; there is no ground key/talisman pickup on Beast. Director’s Cut with the four earlier talismans continues into Mephistopheles. The standard quest itself is complete only after both Mammoths are defeated.','Ordinary: automatic quest reward. Qualified Director’s Cut: Mephistopheles next.')
  ]),
  phase('meph-rituals','Mephistopheles · five rituals and eclipse waves',[
    s('circle','Watch Mephistopheles while standing in a ritual circle to charge it; leaving can regress progress, but surviving takes priority. Read the attack cues before committing to the circle. After charging, use the Entangler to deliver the released souls, then damage the exposed body/talisman symbol. Follow the actual vulnerable cue rather than firing at an invulnerable stage.','Charge circle → Entangler souls → exposed-symbol damage.',[],{links:[{href:'#details-meph-attack-cues',label:'Read the Mephistopheles attack cues'}]}),
    s('eclipse','Survive the eclipse’s enemy set, then use the formed walls for meteor cover. The early sets progress through clowns, Slasher, ninjas, then Rhinos with cryptid/phantom pressure. Clear enemies that trap the circle and repeat the loop for all five rituals. The website does not predict attack timing.','Eclipse enemies → meteor-wall cover → next ritual; five rituals total.'),
    s('talismans','After ritual five, keep damaging Meph while all talismans rise and fill. Interact with each of the five charged talismans to fire its laser. Return to the central boss’s final exposed damage phase and finish him.','Final charge → activate all five talisman lasers → central final damage.')
  ],dc),
  phase('meph-attack-cues','Mephistopheles · read attacks and claim rewards',[
    s('fire-and-skeletons','Aiming hand/fireballs: move off the targeted lane. Raised arms/skeletons: keep distance from their bodies and clear crowding; raised-arm motions can also form a wall, so preserve an escape route. Pulled-back hand with a black center: move away from the black-hole lane. Do not assume a stance makes every attack harmless.','Aiming hand: dodge lane. Raised arms: clear bodies/wall. Black center: leave lane.'),
    s('slam-and-breath','Center teleport/slam: move toward the pillar/edge escape lane and watch the landing. Raised mouth/fire breath: leave its line before the sweep. Clapping hands/wall: move clear of the barrier. Pulled-back hand/huge meteor: immediately leave the impact area. Swirling hands/tornado: spread away from center and teammates’ paths. These are textual animation cues, not frame-accurate countdowns.','Center slam / mouth breath / wall clap / huge meteor / tornado: read cue and evade.'),
    s('reward','Confirm the ending and Demon Slayer/Director’s Cut reward unlocks. Wyler becomes available on Spaceland; completing his Spaceland quest yields the final special ending. Boss Battles practice skips live progression and does not grant these rewards.','Live finale rewards unlock Wyler; complete his Spaceland ending separately.')
  ],dc)
],[
  phase('double-pap','Double Pack-a-Punch',[
    s('fuses','Shoot the power box near Proteus outside Cargo and take its fuses. Place them in the theater Sasquatch cutout’s hand. Take the concession film reel, replace the projector reel so it shows Spaceland, then return to the theater with the Entangler.','Proteus fuses → Sasquatch hand; concession reel → projector.',[[1566,'Fuse power box'],[1567,'Opened fuse box'],[1568,'Sasquatch fuse position'],[1569,'Concession reel'],[1570,'Projector reel']]),
    s('helmet','Activate the Movie Wormhole trap and Entangle the Brute helmet out of its screen vortex. Drop/recover it and fit it to the Brute cutout; its beam charges the Sasquatch fuses. Recover and install them in the projector. Director’s Cut already has its upgraded-projector benefit.','Movie vortex Brute helmet → cutout laser → charged fuses → projector.',[[1571,'Movie Wormhole trap'],[1572,'Screen vortex'],[1573,'Brute cutout']])
  ]),
  phase('venom-x','Venom-X · button and maze apparatus',[
    s('trap-button','Damage a Phantom with the Spawn/Medical electric-water trap. The Ops box below Bang Bangs opens with 3–6 buttons. Record the current round and colours from top to bottom and follow its decision plate; black and blue are different labels. Read each rule in order and use the first true one. Wrong selection spawns a Phantom and changes the box next round. The public reference reports occasional game-variable anomalies, so a rejected plate result needs a newly observed round/board.','Water-trap a Phantom; record round and button colours for the decision plate.',[[1580,'Electric-water trap'],[1581,'Venom button box'],[1582,'Venom-X button decision plate']],{bullets:[
      'On the plate: W is your scene; S is 0 on scenes 1–4, 1 on 5–9, 2 on 10–14, 3 on 15–19 and 4 from 20. Number buttons from the top; “last” means bottom.',
      '3 buttons: no Black → third; otherwise bottom Green → first; otherwise more than one Red → lowest Red; otherwise second.',
      '4 buttons: more than one Yellow and S≥2 → lowest Yellow; otherwise bottom White and no Blue → first; otherwise more than one Black → last; otherwise third.',
      '5 buttons: scene≤3 → first; otherwise exactly one White and more than one Black → second; otherwise no Red, even scene and S<4 → last; otherwise first.',
      '6 buttons: any Yellow → third; otherwise exactly one Black and more than one White → fourth; otherwise S≥1 and more than one Red → fifth; otherwise last.'
    ]}),
    s('chamber','Trap a zombie in the Medical chamber by using the nearby panel while it stands in the floor circle. Its displayed 300-second chamber window starts. At the upper Bombstoppers room, use the middle console to bypass permissions and activate the two maze screens.','Chamber zombie → timed window → middle console bypass.',[[1583,'Containment chamber'],[1584,'Chamber control'],[1585,'Chamber floor circle'],[1587,'Middle console']]),
    s('mazes','Move each red square to the blue diamond while avoiding the maze’s invisible walls, using the supplied maze reference and observed yellow-square/diamond layout. Solve four screens (three on one console, one on the other). Inputs are deliberately paced. PC movement uses bindings for Use Souvenir=Left, Toggle Kung-Fu=Right, Next Card=Up, Previous Card=Down. A failed maze kills the captive and spawns a Phantom; use a fresh captive next round.','Four maze completions before captive timer ends; failure restarts next round.',[[1588,'Maze screen'],[1589,'Venom-X maze path reference'],[1590,'Venom-X pickup']])
  ]),
  phase('venom-upgrades','Venom-Y / Venom-Z · separate Morse reference',[
    s('key','With Venom-X, read the terminal right of Bang Bangs: ARCHER is .- .-. -.-. .... . .-. ; CROSS is -.-. .-. --- ... ... . At the terminal below the Bang Bangs stairs, listen past the key-dependent message opening and identify its encrypted number pattern below. This is a Vigenère message, so ordinary digit Morse does not decode it. Then input the corresponding plain-number Morse at the upper control-room panel (left=short, right=long).','ARCHER/CROSS key → encrypted-number pattern → plain-number input.',[[1591,'ARCHER/CROSS key terminal'],[1592,'Encrypted number terminal'],[1593,'Short/long input panel']],{bullets:[
      'ARCHER opening: -.- --.. -. ... ... -- . .. . Number starts: Fifteen .... .--. ; Eighteen --. .--. ; Thirty ...- --- .',
      'ARCHER Twenty: ...- -.. .. . - .--. . Twenty-Five adds .... .--. --.. ...- after that full pattern.',
      'CROSS opening: -- --.. --.. -.. --. -..- ...- ..-. . Number starts: Fifteen -..- .- ; Eighteen .-- .- ; Thirty .-.. --.. .',
      'CROSS Twenty: .-.. --- --. . .... --.- . Twenty-Five adds -..- -.- -- ... after that full pattern.',
      'Input 15 as ..-. .. ..-. - . . -. .- .-. (FIFTEENAR); 18 as . .. --. .... - . . -. ; 30 as - .... .. .-. - -.-- .',
      'Input 20 or 25 as - .-- . -. - -.-- (TWENTY). If the success cue has not played, append ..-. .. ...- . (FIVE). Failed input is rejected at round end and can be retried.'
    ]}),
    s('kills','After accepted input, kill the indicated number of cryptids using Venom-X; scoreboard progress confirms the route. Projector returns can provide cryptids. At completion, Pack-a-Punch to Venom-Y. For Venom-Z, use the opposite key, repeat the corresponding number/input stage and make the required nonstandard-enemy kills with Venom-Y until the scoreboard stops at 50%.','Accepted code → Venom-X cryptid count → Venom-Y; opposite key for Z.'),
    s('ghosts','At 50%, use the exterior Wheel-side machine until its display reads 195#. Run its floating ghosts toward the projector portal and shoot the decoded number while standing there, all in one round. At 100%, use the upgraded projector to convert Venom-Y to Venom-Z. These observations must not overwrite main-quest disk/handle records.','195# machine → projector ghosts in one round → 100% → Venom-Z.')
  ]),
  phase('skullbreaker','Skullbreaker · remaining skulls and eight queens',[
    s('odd-symbol','After the first two skulls/Entangler, inspect four spawned glyphs and aim at the one from a different reference-sheet row. Candidates: lower Cargo container, cafeteria freezer window, Spawn window, under Medical cryptid, Ops hole top, theater alley window, arcade booth and theater Wheel. Wrong aiming replaces the set next round.','Find four glyphs; aim at the odd reference-row symbol.',[[1657,'Skullbreaker odd-row glyph reference']]),
    s('path','From the Bang Bangs walkway drop toward Spawn’s red X and activate it. Read whether the first skull is pink or green; walk the matching floor symbols without sprinting and watch for swapped colours. The blue progress bar supplies the deadline. Wrong step/timeout retries next round.','Red X → read pink/green → walk matching floor path.'),
    s('queens','On the cafeteria board, preserve its one queen and collect seven more. Candidate pickups: cafeteria couch/freezer counter; Cargo lower stairs; two Proteus hallway sites; Ops pillar, Bombstoppers corner and upper room; Medical cryptid underside/scale; Flooded stairs; Spawn ladder. Use the photographed board orientation and the queen helper, then place its nonattacking completion. Confetti and the sound confirm success.','Keep original queen; collect seven; place a nonattacking completion.',[[1669,'Cafeteria chessboard orientation']]),
    s('paper-code','Find three arrow papers from cafeteria’s freezer-side counter, Medical green-monitor counter, Medical disk room, projector toolbox, theater bathroom sink or concession popcorn. Match each paper’s group on the arrow reference: Group 1 first, Group 2 middle, Group 3 last. At the theater cabinet enter the combined arrows promptly; PC uses the souvenir/Kung-Fu/card direction bindings. A rejected cabinet input can be retried.','Three arrow papers in group 1→2→3 order; input at cabinet.',[[1682,'Skullbreaker arrow-paper groups and order']]),
    s('game','In the cabinet, colour skulls with Entangled cubes so neighboring/diagonal matching skulls connect. Shoot a matching nuke at each group. A wrong nuke makes red escapees; a red nuke can destroy that connected group before escape. Clear three rounds; after failure reuse the same arrow code.','Connect matching skulls; matching-colour nuke; three rounds.')
  ],{tools:['iw-beast-queens']}),
  phase('music-and-message','Scattered Lies and Message Sent',[
    s('astronauts','After opening the theater/projector, shoot fifteen astronaut dolls. Main-map candidates: Flooded stairs/window, Ops stairs/pit, Exterior Change Chews/acid-window/glacier/chasm rock, Proteus floor grate/red room and Cargo ceiling. Theater: alley window, bathroom trash, street booth and upper fire escape. The actor’s celebration and music confirm completion.','Shoot fifteen astronaut dolls across facility, Exterior and theater.'),
    s('message','With the Entangler, interact with the Exterior Wheel-side console until it shows 197# and opens a vortex beside it. Grab the turnstile behind the theater street’s KBS dumpster and carry it back to fire into that vortex. If the vortex closed, select 197# again and retry the throw. Director’s Cut’s Scene 1 shooting-gallery white mask grants separate lobby music and only one attempt per match.','Exterior 197# vortex; theater KBS dumpster turnstile; fire it into the vortex.')
  ])
],sources('the-beast-from-beyond','the_beast_from_beyond').concat([
  {label:'Mephistopheles ritual and encounter guide · DaRkShAdOwYlaf',url:'https://www.reddit.com/r/CODZombies/comments/l2l72v/the_ultimate_iw_easter_egg_guides_mephistopheles/'},
  {label:'Mephistopheles practice encounter reference',url:'https://steamcommunity.com/sharedfiles/filedetails/?id=3617365373'},
  {label:'Written Beast and Mephistopheles encounter reference',url:'https://margwa.net/beast-from-beyond'}
]),{image:photo(1561,'N31L power slot').src,branches:[{id:'standard',label:'Standard quest',description:'Restore N31L and defeat both Mammoths for the ordinary quest reward.'},{id:'directors-cut',label:'Director’s Cut finale',description:'Includes the separate account gates and Mephistopheles after the Beast encounter.'}]})

// Completion and return anchors use map-wide step IDs, including optional routes.
// Prefix the authored local ID with its phase so two "battery" pickups cannot share progress.
export const iwGuides=[spaceland,rave,shaolin,attack,beast].map(map=>({
  ...map,
  phases:map.phases.map(part=>({...part,steps:part.steps.map(item=>({...item,id:`${part.id}-${item.id}`}))})),
  sidePhases:map.sidePhases.map(part=>({...part,steps:part.steps.map(item=>({...item,id:`${part.id}-${item.id}`}))})),
}))
