import fs from 'node:fs'
import { step, phase, guide, image } from './remaining-common.mjs'
const research = JSON.parse(fs.readFileSync(new URL('../docs/remaining-games/puzzle-data.json', import.meta.url), 'utf8'))
const officialMissions = 'https://www.callofduty.com/guides/zombies/call-of-duty-guides-modern-warfare-zombies-missions-and-progression'
const officialEquipment = 'https://www.callofduty.com/guides/zombies/call-of-duty-guides-modern-warfare-zombies-acquisitions'
const officialTactics = 'https://www.callofduty.com/guides/zombies/call-of-duty-guide-modern-warfare-zombies-tactics'
const pic = (id, alt) => ({ images: [image(id, alt)] })
const extra = (cover, name) => ({ mode: 'Open-world deployment', edition: 'Modern Warfare III (2023)', image: image(cover, name).src, defaultView: 'full' })
const seasonalExtra = (cover, name) => ({ ...extra(cover, name), mode: 'Dark Aether' })
const prep = prefix => phase('preparation', 'Before you enter', [
  step(`${prefix}-goal`, 'For your first portal unlock, complete the named story mission for its gold relic, collect the other three relics, upgrade them to gold and perform the four-item pedestal ritual. The sections below follow that order. Once the portal is permanently unlocked, skip to Repeat visits. Joining another squad’s portal does not establish your personal unlock.', 'First unlock: story relic → three extra relics → gold upgrades → pedestal ritual.'),
  step(`${prefix}-loadout`, 'Prepare upgraded rarity AND Pack-a-Punch, armour, useful perks, spare self-revives, ammunition and crowd-control tacticals. Make room for relics/plans before entry. Carry a mask for gas areas and coordinate revive/crowd-control roles. Prepare the next objective rather than relying on a fixed release-era best-gun recommendation.', 'Upgrade damage and armour; carry revives, crowd control and free rucksack slots.'),
  step(`${prefix}-sigils`, `Repeat ordinary entry uses a triangular Sigil and a 30-minute timer; Elder entry uses an Elder Sigil and a 15-minute timer. Find the corresponding interaction side, confirm its variant and accept the squad travel vote. Ordinary rewards are acquisitions/Elder Sigil opportunities; Elder visits provide schematic opportunities; check each Reward Rift for the actual loot. The 2024 temporary ordinary-entry waiver is historical; follow the current item prompt.`, 'Repeat visits: triangular Sigil = ordinary; Elder Sigil = short schematic run.'),
  step(`${prefix}-inventory`, 'You can collect the relics over several deployments. Keep each item in your rucksack through a successful exfil, then bring it back when you are ready to upgrade or place it. Losing carried relics after your permanent portal ritual is complete does not remove the unlock.', 'Exfil with each relic; bring all four gold items for the portal ritual.'),
], { group: 'Key Features' })

const urzikstan = guide('mw3-urzikstan', 'mw3', 'Urzikstan', 'Unlock the seasonal Dark Aether portals, summon and defeat the Red Worm, and complete Urzikstan’s free-perk, chess vault and triangle Easter eggs. Jump to the activity you want, then follow its illustrated steps.', [
  phase('deployment', 'Plan this deployment', [
    step('mw3-loadout', 'Choose a concrete goal before deploying: mission progress, gear, a named portal unlock, a schematic run or Greylorm. Use acquisitions from your stash for this match and retain insured/contraband weapons as appropriate. A crafted acquisition is consumed in a deployment; a schematic unlock remains available for future crafting.', 'Select this deployment’s goal; distinguish consumed acquisitions from schematics.', pic('extra-mw-acquisitions-official-01', 'Official MWZ acquisitions and loadout reference')),
    step('mw3-threat', 'Low, medium and high threat zones increase pressure. Weapon rarity and Pack-a-Punch are separate damage upgrades: an Aether Tool changes rarity, while a crystal or machine raises Pack-a-Punch. Add armour plates/vest, perks and a self-revive before increasing threat; mask protection is needed inside gas nests and the storm.', 'Prepare rarity, Pack-a-Punch, armour, mask and revives for the chosen threat zone.'),
    step('mw3-map-timer', 'Read the Tac-Map’s live contract, ammunition, buy station, portal and exfil markers. Its countdown and actual expanding storm are authoritative. Leave enough time for your return route; a website-open timestamp cannot predict the storm or last extraction.', 'Use the in-game timer, storm boundary and current extraction markers.'),
    step("mw3-field-upgrades", "Aether Shroud helps you reposition, Frenzied Guard supports armour pressure and Healing Aura supports squad recovery. Energy Mine and Frost Blast help manage nearby enemies. Equip the upgrade that fits your loadout and check its charge before a difficult objective.", "Prepare a field upgrade for survival, crowd control or squad recovery."),
  ], { group: 'Key Features' }),
  phase('contracts', 'Eight contract mechanics', [
    step('mw3-bounty', 'Pick up an Eliminate Bounty contract phone. Follow the marked high-value enemy and kill THAT target; incidental specials do not count. Use its actual armour/weakpoint cues and avoid surrounding zombies while damaging it. The contract completion and Reward Rift confirm the target was registered.', 'Bounty: kill the marked HVT and collect its Reward Rift.'),
    step('mw3-outlast', 'Take an Outlast contract and activate the marked PND. Remain inside its highlighted building/zone while defending yourself; leaving the zone stalls/reduces progress. Continue until the displayed analysis bar completes and collect the Reward Rift.', 'Outlast: activate PND and stay in its marked zone until analysis finishes.'),
    step('mw3-spores', 'Take Spore Control and collect inhibitors from its marked toolbox. Place them beside the marked spores to break their protective shells, then shoot the exposed spores. Inhibitors occupy tactical slots; manage them and your usual tacticals deliberately. Destroy every marked spore for completion.', 'Spore Control: collect/place inhibitors, then shoot every exposed spore.'),
    step('mw3-escort', 'Activate Escort’s marked ACV and remain nearby to move it between sites. Protect its health while it collects each anomaly; enemy hits can destroy it and fail the contract. Clear stationary-stop pressure before looting. A packed V-R11 can repair the vehicle if available; it is an optional support route.', 'Escort: move with the ACV and protect its health through every stop.'),
    step('mw3-cargo', 'For Deliver Cargo, clear the marked garage, collect its LTV and drive to the destination. Avoid the pursuing helicopter’s fire and keep the cargo vehicle intact; use the marked delivery point to finish. Reaching a garage without delivering the LTV is not completion.', 'Deliver Cargo: retrieve the LTV and reach its marked drop-off intact.'),
    step('mw3-stash', 'For Raid Weapon Stash, activate the safe drill and defend near the marked stash as drilling progresses. Keep the drill’s objective active rather than chasing enemies far away. When drilling finishes, open/loot the safe and check the contract reward.', 'Raid Weapon Stash: drill and defend the safe, then collect the loot.'),
    step('mw3-extractors', 'Aether Extractors is a mercenary objective. Reach each marked extractor, clear or distract its guards and hold the interaction uninterrupted to plant its shutdown charge. Finish all devices before the contract timer expires; being hit can interrupt the interaction, so protect the player using the panel.', 'Aether Extractors: finish each uninterrupted shutdown interaction before time expires.'),
    step('mw3-ground-station', 'Defend Ground Station begins with the marked seismic data devices. Interact with the required devices, activate the uplink and defend it against attacking mercenaries until the upload finishes. Prioritize enemies damaging the station and keep its health intact; normal zombie kills alone do not finish the upload.', 'Defend Ground Station: gather seismic data, activate uplink and protect its upload.'),
  ]),
  phase('equipment', 'Equipment, keys and local facilities', [
    step('mw3-merc-keys', 'Clear a mercenary camp to find supplies and its Stronghold Keycard, or obtain a keycard through the available buy-station route. Unlock a marked mercenary stronghold, clear its guards and drill its safe while defeating reinforcements. Inspect the resulting fortress keycard’s name before attempting the currently active Warlord fortress.', 'Camp → Stronghold Keycard → stronghold safe → named fortress access.'),
    step('mw3-warlords', 'Use the active fortress marker/keycard for THIS public deployment. Legacy’s hill base, Dokkaebi’s rooftop/drone defenses, Keres’s gas-filled compound and Rainmaker’s trapped island are different Warlord editions. Clear the approach, use the matching access prompt and defeat the named boss; do not expect all editions at once. Carry a durable mask for Keres and watch rooftop movement or traps in the other editions.', 'Check the active Warlord and matching fortress card; prepare for its drones, gas or traps.'),
    step('mw3-nests', 'At Aether Nests and infested strongholds, wear a mask and destroy all glowing cysts, including ones on upper floors and hidden rooms. A completed clear unlocks the facility’s reward containers. Do not confuse these cysts with a Spore Control contract’s inhibitor-protected objectives.', 'Mask up; clear every nest/stronghold cyst for its cache rewards.'),
    step('mw3-orbs', 'Shoot a Harvester Orb and follow it as it moves, then finish it for its dropped resources. For Season 1’s Camera relic, use a Dead Wire-equipped weapon and collect the specific camera drop; an ordinary orb’s resources are not that relic.', 'Track a damaged Harvester Orb; finish it and collect its resources.'),
    step('mw3-dogs', 'Friendly doghouses use Chunks of Flesh: the documented baseline is at least one, two or three chunks for the corresponding threat level. Feed the available house and collect its friendly companion response. Pets can be defeated; plan revives independently. The Season 1 Dog Collar ritual instead adds a Molotov and spawns a HOSTILE quest Hellhound.', 'Friendly dog: appropriate flesh amount; Dog Collar quest: flesh + Molotov, hostile hound.'),
    step('mw3-ammo-mods', 'Keep ammo-mod names tied to their actual effects: Brain Rot turns an enemy ally; Dead Wire applies electricity; Cryo Freeze slows; Napalm Burst burns; Shatter Blast supplies its explosive effect. Mission counters can require a proc on a specified enemy type, rather than merely holding or shooting the mod.', 'Read the required mod effect and enemy type before farming a mission counter.'),
    step('mw3-schematics', 'Exfil with a carried schematic to establish the crafting unlock. Afterward craft through the acquisition menu when its displayed cooldown allows it. Exfil a weapon case as a saved consumable; opening it in the match produces that deployment’s weapon instead. Do not substitute an acquisition or weapon case for a schematic plan.', 'Exfil plans for permanent crafting; distinguish consumables and weapon cases.'),
  ]),
  phase('story', 'Mission actions and the three Act finales', [
    step('mw3-mission-counters', 'Read the selected mission’s exact verb: slowing a Hellhound is different from killing it; a Brain Rot ally’s kills differ from personal shots; extracting a quest item requires it still in the rucksack when extraction registers. Use the game’s counters and current mission availability; the website does not impose release-era Act gates.', 'Follow the exact counted action and retain required items through exfil.'),
    step('mw3-extraction-finale', 'For Extraction, select the available mission and use the special exfil explicitly named for it. After travel, follow the marker to Jansen, clear the local enemies while her upload completes, then escort her to the helicopter and leave with her. Boarding an ordinary exfil or merely entering the mission does not complete this rescue.', 'Extraction: named mission exfil → Jansen upload defense → helicopter escort/exfil.'),
    step('mw3-shepherd-finale', 'For Shepherd, use its named mission exfil. Clear the roof and destroy the marked SAM installations, then clear the neutralizer’s deployment zone. Activate/escort the ACV and protect its health through the test sites. At the final site, activate and defend the neutralizer through its concluding test; manage the Mega Abomination pressure while following the device’s actual objective prompt.', 'Shepherd: SAMs → deployment area → protect ACV → activate/defend final neutralizer test.', { note: 'An ACV destroyed during the mission is a failure. Do not leave it to chase a special away from its route.' }),
    step('mw3-zakhaev-finale', 'For Defeat Zakhaev, enter its named stronghold mission, clear the mercenary route and plant the charge at the marked device. Fight Orcus by damaging exposed glowing mouth/body weakpoints, shooting tracking orbs and moving out of its beam/slam path. If swallowed, fire as appropriate and be ready to open your parachute when spat out. Finish the objective/ending and mission extraction.', 'Defeat Zakhaev: clear stronghold → plant charge → defeat Orcus → finish the ending.'),
    step('mw3-seasonal-story-links', 'Later named missions have dedicated guides: Bad Signal, Countermeasures, Union and Ascension. Choose the actual story portal rather than spending a Sigil on a contract destination with the same setting. Orcus (Zakhaev), Gorm’gant (Bad Signal) and Greylorm (Red Worm) are separate encounters.', 'Use the matching later story guide; distinguish the three Worm encounters.', { links: [{ href: '/guides/mw3-dark-aether-season-1', label: 'Bad Signal and Season 1' }, { href: '/guides/mw3-dark-aether-season-2', label: 'Countermeasures and Season 2' }, { href: '/guides/mw3-dark-aether-season-3', label: 'Union and Season 3' }, { href: '/guides/mw3-dark-aether-season-5', label: 'Ascension and Season 5' }] }),
  ]),
  phase('rune-portals', 'Local rune-doorway travel', [
    step("mw3-rune-method", "Rune doorways provide fast travel inside Urzikstan. Shoot a known exit’s three symbols in order, interact with the opened doorway and pay the displayed Essence cost. These doorways do not unlock a seasonal Dark Aether Rift.", "Rune doorways are local fast travel, separate from seasonal portal unlocks."),
    step("mw3-rune-entry-atlas", "Look for the illuminated glyphs around the doorway. An entrance can send you to different exits depending on the sequence. Use a code you know or consult the original illustrated map reference.", "Find a rune doorway and use the sequence for your intended exit.", { images: [image(research.mwRunePortals.entrances[0].assetIds[0], 'An Urzikstan rune doorway used for local fast travel')], links: [{ href: 'https://wzhub.gg/map/urzikstan/mwz', label: 'Original rune-doorway reference' }] }),
    step("mw3-rune-code-check", "Check all three symbols and their order before paying. A rune-doorway trip stays in Urzikstan. Use the seasonal unlock guides below for permanent Dark Aether access.", "Check the full sequence; use a seasonal guide for Dark Aether access."),
  ]),
  phase('dark-aether-portals', 'Unlock the seasonal Dark Aether portals', [
    step('mw3-portal-unlock-intro', 'Each seasonal portal has its own four-item ritual. Complete its story mission, collect the other three relics, upgrade them to gold, place all four at the matching pedestals and defeat the guardian. The guides below show every collection and upgrade location. You only need the completed permanent ritual once.', 'Follow the four-item ritual for the seasonal portal you want.'),
    step('mw3-portal-season-1', 'Season 1 — Al Bagra Fortress: Bad Signal supplies the gold Locked Diary. Collect the Pill Bottle, Surveillance Camera and Dog Collar, upgrade the three purple items and bring the full gold set to the island pedestals. The fortress guide also covers its optional locked equipment rooms.', 'Al Bagra: Diary, Pill Bottle, Camera and Dog Collar.', { links: [{ href: '/guides/mw3-dark-aether-season-1#details-bad-signal', label: 'Season 1 story and portal-unlock steps' }, { href: '/guides/mw3-dark-aether-season-1#details-locked-rooms', label: 'Fortress keys and secret rooms' }] }),
    step('mw3-portal-season-2', 'Season 2 — Sa’id City: Countermeasures supplies the gold Drum. Collect the Tattered MMA Gloves, Pristine Mirror and Perforated Target from its obelisks, then complete their Urzikstan upgrades before the Nahr hill ritual. The map also has a stadium music Easter egg.', 'Sa’id: Drum, MMA Gloves, Mirror and Target.', { links: [{ href: '/guides/mw3-dark-aether-season-2#details-countermeasures', label: 'Season 2 story and portal-unlock steps' }, { href: '/guides/mw3-dark-aether-season-2#details-music', label: 'Stadium music Easter egg' }] }),
    step('mw3-portal-season-3', 'Season 3 — Zarqwa Hydroelectric: Union supplies the gold Giraffe Toy. Collect the Laptop With Stickers, Science Journal and Imaginary Friend Drawing, then perform their individual Tier 3 summonings. Place the gold set at the northwest island portal. Inside, the optional Gyanxi quest unlocks Smoke Signals.', 'Zarqwa: Giraffe, Laptop, Journal and Drawing.', { links: [{ href: '/guides/mw3-dark-aether-season-3#details-union', label: 'Season 3 story and portal-unlock steps' }, { href: '/guides/mw3-dark-aether-season-3#details-gyanxi', label: 'Gyanxi / Smoke Signals Easter egg' }] }),
    step('mw3-portal-season-5', 'Season 5 — Highrise: finish Ascension for gold Mr. Peeks. Obtain and attune Echo of Locked Diary, Echo of Drum and Echo of Giraffe Toy, then complete the Opal Palace fountain ritual. The Elder-only Infinite Cosmos quest has a separate detector, skull, computer and boss sequence.', 'Highrise: Mr. Peeks and the three gold Echo relics.', { links: [{ href: '/guides/mw3-dark-aether-season-5#details-ascension', label: 'Season 5 story and portal-unlock steps' }, { href: '/guides/mw3-dark-aether-season-5#details-infinite-cosmos', label: 'Infinite Cosmos Easter egg' }] }),
  ], { group: 'Main Quest' }),
  phase('red-worm', 'Red Worm boss fight — Greylorm', [
    step('mw3-worm-preparation', 'Prepare a high-rarity Pack-a-Punch III weapon, armour, a durable gas mask, spare self-revives and useful perks before the storm battle. Sentry Guns can cover zombies while you damage the boss. Agree who carries each USB and who covers revives, leaving rucksack space for the four drives.', 'Bring strong damage, mask protection, revives and crowd control.'),
    step('mw3-clue-walls', 'Visit one of the four clue-photo walls: the upper Kotovo warehouse at C1, Orlov Military Base’s H2 warehouse, Urzikstan University’s E8 dining building, or the unfinished Ah-Dahr building around G7/G8. Record its FOUR pinned photographs for this deployment.', 'Read four photographs from a current C1, H2, E8 or G7/G8 clue wall.', { images: [image('wzhub-m2574-1', 'Kotovo C1 clue-photo room'), image('wzhub-m2583-1', 'Orlov H2 clue-photo room'), image('wzhub-m2637-1', 'University E8 clue-photo room'), image('wzhub-m2623-1', 'Ah-Dahr G7/G8 clue-photo room')] }),
    step("mw3-usb-collect", "Match the wall photographs to the twelve candidate landmarks in the chart. At the four active consoles, interact and collect the USBs labelled Alpha, Bravo, Charlie and Delta. Read each drive’s name in your rucksack: a location does not permanently own one letter. Keep all four different drives between the squad until the summoning step.", "Match the wall photographs and collect four differently named USBs.", pic('reddit-red-worm-chart', 'spaz33g’s twelve USB-landmark and clue-wall reference chart')),
    step('mw3-worm-arena', 'Find the current arena by its TWO nearby ammunition caches and four seismic refractors. Read each refractor’s requested drive. Set up durable mask support, armour, revives, crowd control and sustained damage before the storm reaches it. The USB set does not predict the boss location.', 'Locate paired ammo caches/refractors and prepare the current storm arena.'),
    step('mw3-insert-usbs', 'Once the storm condition allows the refractors, insert each matching drive and confirm every device activates. Check missing items and the actual storm boundary if a prompt refuses. After all four, let the summoning dialogue finish and watch for Greylorm’s emergence; no page timer replaces that cue.', 'In the storm, install all four matching USBs and confirm the summoning cues.'),
    step('mw3-greylorm-fight', 'Damage Greylorm’s exposed glowing weakpoints while clearing its tracking orbs and dangerous adds. Avoid the telegraphed beam and head slam. Replenish ammo/mask support at the arena caches and manage their actual reuse availability. If swallowed, prepare to parachute on release so the landing does not down you. Keep damage on the boss while teammates cover revives and crowd pressure.', 'Attack weakpoints, shoot orbs, maintain mask/ammo and parachute after a swallow.'),
    step("mw3-greylorm-reward", "After Greylorm dies, open the Reward Rift, keep the reward you want in your rucksack and use the spawned exit before the run ends. Keep carried plans through extraction to register their crafting unlocks.", "Claim the boss reward and leave through the spawned exit."),
  ]),
  phase('side-quests', 'Free perk Easter eggs', [
    step('mw3-free-perks', 'Pick the perk you need and follow its landmark challenge below. These activities are independent; they do not unlock a Dark Aether portal. Look for Mister Peeks and the challenge cue first. In a shared match, another player may already have claimed an activity’s reward.', 'Choose any available free-perk activity; the eight challenges are independent.'),
  ], { group: 'Side Quests' }),
  phase('free-juggernog', "Jugger-Nog — campsite fire", [
    step('mw3-free-juggernog', "At C3, find the campsite with Mister Peeks. Throw a Molotov into its fire pit to light it, then claim the free Jugger-Nog reward.", "C3: light the campsite fire with a Molotov.", pic("wzhub-m2268-1", "Jugger-Nog — campsite fire")),
  ]),
  phase('free-speed-cola', "Speed Cola — eagle ramp", [
    step('mw3-free-speed-cola', "Bring a vehicle to the stone eagle ramp around C2/D2. Drive up and launch off its beak, landing below to trigger the reward. Claim the free Speed Cola from the rift.", "C2/D2: launch a vehicle off the eagle ramp.", pic("wzhub-m2267-1", "Speed Cola — eagle ramp")),
  ]),
  phase('free-death-perception', "Death Perception — parachute rings", [
    step('mw3-free-death-perception', "Use the northern tower approach to reach the three sculpture rings around E1/E2. Jump and parachute through all three rings in one flight, then claim the free Death Perception reward.", "E1/E2: parachute through all three sculpture rings.", pic("wzhub-m2269-1", "Death Perception — parachute rings")),
  ]),
  phase('free-deadshot', "Deadshot Daiquiri — church grenade", [
    step('mw3-free-deadshot', "At I3’s church, throw a grenade through the highest opening shown in the reference. Use the nearby ammo cache to replenish your equipment if you miss. Collect the free Deadshot Daiquiri reward after the successful throw.", "I3: throw a grenade through the church’s highest opening.", pic("wzhub-m2270-1", "Deadshot Daiquiri — church grenade")),
  ]),
  phase('free-phd', "PhD Flopper — manor pool dive", [
    step('mw3-free-phd', "Climb onto the H7 manor roof above its swimming pool. Sprint and dolphin-dive from the roof into the pool, then collect the free PhD Flopper reward.", "H7: dolphin-dive from the manor roof into its pool.", pic("wzhub-m2274-1", "PhD Flopper — manor pool dive")),
  ]),
  phase('free-quick-revive', "Quick Revive — highway race", [
    step('mw3-free-quick-revive', "Bring a vehicle beneath the H5 highway sign with Mister Peeks. Wait for the laugh that starts the challenge, then race north to the next sign and claim the Quick Revive reward if you complete the route in time.", "H5: wait for the laugh, then race north to the next sign.", pic("wzhub-m2273-1", "Quick Revive — highway race")),
  ]),
  phase('free-staminup', "Stamin-Up — stairwell sprint", [
    step('mw3-free-staminup', "Find Mister Peeks at the bottom of the D7 stairwell. Sprint up its stairs to the top to complete the challenge, then claim the free Stamin-Up reward.", "D7: sprint from the bottom Peeks to the stairwell’s top.", pic("wzhub-m2272-1", "Stamin-Up — stairwell sprint")),
  ]),
  phase('free-tombstone', "Tombstone — crane sightline", [
    step('mw3-free-tombstone', "At the G7/G8 crane reference, use a scoped weapon to look at the distant Mister Peeks. Hold your breath while keeping it in view until the jumpscare triggers, then claim the free Tombstone reward.", "G7/G8: scope Peeks and hold breath until the jumpscare.", pic("wzhub-m2271-1", "Tombstone — crane sightline")),
  ]),
  phase('vault', 'Chessboard vault — four transmissions', [
    step('mw3-vault-transmissions', 'Send four transmissions to H7 in any order: Pawn’s waterside I1 shack device; Bishop’s D1 rail-tunnel mercenary device; Rook’s trapped/mined C5 Ghalia hotel device; and the Knight’s moving truck device. Defeat the named mercenary where necessary and use Send Transmission to H7. Knight moves, so its pictured grid is not a permanent spawn. Other players may contribute transmissions in this match.', 'Send Pawn, Bishop, Rook and moving Knight transmissions to H7.'),
    step('mw3-vault-open', 'At the H7 manor basement, inspect the chessboard’s four lowered pieces/lights. When all transmissions have registered, open the vault. Deal with the King Mimic before looting; merely reaching the chessboard or defeating one piece does not unlock it.', 'Check four registered pieces at H7; open the vault and defeat its King Mimic.'),
  ]),
  phase('triangles', 'Purple triangle rituals', [
    step('mw3-triangles', 'The high-threat purple triangle activities use three shot runes, a perspective aligning the surrounding markings and kills inside the summoned ring. Complete the displayed reward/ritual cue, then collect its rift. Season 3 relic attunements require the CORRESPONDING carried relic and offer prompt; ordinary triangle loot alone does not upgrade an item.', 'Triangle: activate three runes, align the viewpoint and charge the ring.', { images: [image('wzhub-m3125-1', 'High-threat triangle reference near Opal Palace'), image('wzhub-m3127-1', 'Photographed triangle alignment viewpoint')], links: [{ href: '/guides/mw3-dark-aether-season-3#details-attunement', label: 'Season 3 item-attunement routes' }] }),
  ]),
  phase('other-side-quests', 'Other Urzikstan activities', [
    step('mw3-blood-burner', 'The Blood Burner is a special motorcycle found through its live world spawn or summoned with Blood Burner Keys. Its movement over water matters for Season 5’s Echo of Drum course. A Key acquisition is consumed to summon it; the Season 2 schematic supplies future crafting.', 'Find or summon Blood Burner; use the season-specific Key/Drum route.'),
    step("mw3-portal-overview", "For the stadium music Easter egg, open the Season 2 guide. For a separate five-wave combat challenge, follow the Unstable Rift guide. Their entry and completion steps are explained on those pages.", "Open the stadium music or Unstable Rift instructions.", { links: [{ href: '/guides/mw3-dark-aether-season-2#details-music', label: 'Season 2 stadium music' }, { href: '/guides/mw3-unstable-rift', label: 'Unstable Rift challenge' }] }),
  ]),
  phase('exfil', 'Extract and retain the useful rewards', [
    step('mw3-exfil-call', 'Before the storm closes your route, travel to a valid ordinary exfil, call its helicopter and survive the marked countdown/wave. Board the intended helicopter and stay aboard through extraction. A named story exfil travels to its mission instead; verify the icon/name before calling or boarding.', 'Call the intended exfil, survive its wave and stay aboard until extraction.'),
    step("mw3-exfil-items", "Keep the relics, plans or weapon cases you want in your rucksack until extraction completes. Check the post-match unlock result in-game before your next deployment. A new Red Worm attempt needs new USBs; an already unlocked seasonal portal does not need its four-item ritual again.", "Extract with the items you want to keep; collect new USBs for a new Worm attempt."),
  ]),
], [], [officialMissions, officialEquipment, officialTactics, 'https://wzhub.gg/map/urzikstan/mwz', 'https://www.reddit.com/r/CODZombies/comments/17uvwuc/mwz_rune_portals_guide/', 'https://gameranx.com/features/id/485365/article/modern-warfare-3-zombies-secret-red-worm-boss-fight-greylorm-easter-egg-guide/', 'https://www.reddit.com/r/CODZombies/comments/18yl0fd/my_red_worm_usb_location_cheat_sheet_in_case/', 'https://www.gamepur.com/guides/all-free-perks-in-cod-mw3-zombies', 'https://www.gamerevolution.com/guides/954826-mw3-zombies-easter-egg-solve-chessboard-puzzle-open-vault-unlock-modern-warfare', 'https://www.gameskinny.com/tips/mw3-zombies-shepherd-mission-walkthrough-how-to-deploy-to-neutralizer-test-site/'], { ...extra('extra-mw-tactics-official-01', 'Urzikstan Operation Deadbolt'), aliases: ['MWZ', 'Operation Deadbolt'], questLabel: 'Deployment activities' })

const season1 = guide('mw3-dark-aether-season-1', 'mw3', 'Dark Aether — Season 1', 'Al Bagra Fortress contains Bad Signal’s story route and separate ordinary/Elder contract visits. Obtain the gold Locked Diary, attune the other three relics and complete the island ritual once for personal portal access.', [
  prep('mw1'),
  phase('bad-signal', 'Bad Signal: four seals and Gorm’gant', [
    step('mw1-bad-signal-entry', 'If the gold Locked Diary is already safely owned, skip repeating this mission for the unlock route. Otherwise select Bad Signal and use its NAMED coastal portal beside the seasonal island, then confirm the squad vote. A Sigil contract entry does not run Bad Signal.', 'Use the named Bad Signal story portal; skip if its gold Diary is already owned.'),
    step('mw1-seals', 'Follow the four seal markers. Activate each and kill zombies nearby until its collection bar completes and the seal breaks. The revealed relic imagery previews the later unlock items; it does not provide all four gold items in this mission.', 'Activate and charge all four nearby-kill seals.'),
    step('mw1-gormgant', 'When told to exit, approach the southern beach portal to trigger Gorm’gant. Damage its glowing mouth/body weakpoints, shoot tracking purple orbs before they reach you and sidestep its rising beam and head slam. Maintain armour/ammo with the beach supply and available drops. If swallowed, prepare to parachute as it spits you out.', 'Approach the beach exit, defeat Gorm’gant’s weakpoints and parachute after a swallow.'),
    step('mw1-diary', 'Open the boss Reward Rift, take the GOLD Locked Diary and use the mission exit. The Diary is already attuned. Extracting the mission and keeping this item complete the story/relic goal; starting a seal is insufficient.', 'Collect the gold Locked Diary and finish Bad Signal’s extraction.'),
  ], { group: 'Main Quest' }),
  phase('relics', 'Acquire the three purple Urzikstan relics', [
    step('mw1-pill', 'With Brain Rot equipped, shoot an Aether Nest/infested-stronghold cyst only until it turns green. Interact BEFORE destroying it to recover the purple Pill Bottle. Clear nearby enemies to protect the interaction; a destroyed ordinary cyst cannot be used afterward.', 'Brain Rot a cyst green, then interact for the purple Pill Bottle.'),
    step('mw1-camera', 'Use a Dead Wire-equipped weapon on a Harvester Orb until it changes and is destroyed. Collect the purple Surveillance Camera from its drops. Follow the orb’s movement; an ordinary non-quest orb kill is not the attuned camera.', 'Destroy a Harvester Orb with Dead Wire and collect its purple Camera.'),
    step('mw1-collar', 'Put one Rotten Flesh/Chunk of Flesh and a Molotov into an available doghouse. Defeat the hostile Hellhound it releases and take the purple Dog Collar. This is the quest-hound recipe, distinct from feeding flesh for a friendly pet.', 'Flesh + Molotov in a doghouse → kill hostile Hellhound → purple Collar.'),
  ]),
  phase('attunement', 'Upgrade each purple relic through its sky portal', [
    step('mw1-attune-bottle', 'Carry the purple Pill Bottle through an Aether Tear, parachute into its GREEN floating portal and follow the special purple bounty. Defeat its marked target and collect the gold Bottle from the Reward Rift.', 'Bottle: green sky portal → special bounty → gold Bottle.'),
    step('mw1-attune-camera', 'Repeat with the purple Surveillance Camera, choosing the ORANGE sky portal. Complete its special bounty and take the gold Camera. Do not mark attunement merely for entering the tear.', 'Camera: orange sky portal → special bounty → gold Camera.'),
    step('mw1-attune-collar', 'Repeat with the purple Dog Collar via the RED sky portal into the high-threat bounty. Prepare before this route; kill the marked target and collect the gold Collar. Gold Diary requires no additional upgrade. If a required item is missing, recover/extract it rather than placing a purple substitute.', 'Collar: red sky portal → high-threat bounty → gold Collar.'),
  ]),
  phase('portal', 'Establish personal Al Bagra portal access', [
    step('mw1-pedestals', 'Bring all four GOLD relics to the island tornado near Bad Signal. Match the engraving: Pill Bottle to Brain Rot, Camera to Dead Wire, Dog Collar to Napalm Burst and Locked Diary to Cryo Freeze. Each pedestal must receive its correct gold item.', 'Island pedestals: Bottle/Brain Rot, Camera/Dead Wire, Collar/Napalm, Diary/Cryo.'),
    step('mw1-gate-boss', 'After the portal ritual, defeat its Mega Abomination gate boss and collect the access/Sigil reward. Record permanent access only once the ritual is complete. Later visits use Sigils and do not require re-collecting these four relics.', 'Defeat the ritual Mega Abomination and confirm permanent portal access.'),
  ]),
  phase('contracts', 'Repeat visits: three Mister Peeks contracts', [
    step('mw1-contract-entry', 'Use the prepared Sigil side for ordinary or Elder. Before starting, note the roof and underground exit references below and keep an extraction margin, especially on Elder’s shorter timer. Three Peeks starters correspond to Extractors, Escort and Outlast; contract order can be chosen for the squad.', 'Enter the intended variant and locate all three Peeks starters and exits.'),
    step('mw1-extractor-contract', 'Take the Aether Extractors starter at the east-side rampart/H4 reference. Travel to its marked devices, distract the horde and hold every panel interaction uninterrupted. Move on only after each charge is registered; an interrupted hold does not destroy the device.', 'H4 Extractors starter: finish every timed shutdown panel.', pic('wzhub-season-1-m2612-1', 'Al Bagra Aether Extractors contract starter reference')),
    step('mw1-escort-contract', 'Take Escort’s west-side E4 Peeks starter and reach its ACV. Stay nearby to move it and protect its health at every anomaly stop. Crowd control and an optional packed V-R11 repair can preserve the vehicle; destruction fails the contract.', 'E4 Escort starter: protect the ACV through all anomaly stops.', pic('wzhub-season-1-m2613-1', 'Al Bagra Escort Peeks contract starter')),
    step('mw1-outlast-contract', 'Take the E6 Outlast starter and activate the PND in the fortress interior above Pack-a-Punch. Remain inside its objective area, clear pressure and finish analysis before leaving to claim the rift.', 'E6 Outlast starter: remain in the fortress analysis room until complete.', pic('wzhub-season-1-m2620-1', 'Al Bagra Outlast Peeks starter')),
    step('mw1-contract-rewards', 'Loot each completed contract. Ordinary runs offer acquisitions and possible Elder Sigils. In Elder, Season 1’s schematic progression follows contracts completed: Dog Bone first, Golden Armor Plate second and Aether Blade third. Completing all three in Elder also supplies the Geode MCW blueprint objective. Check each actual reward and carry plans to extraction; later seasons use different/random schematic behavior.', 'Elder: finish 1/2/3 contracts for Dog Bone/Golden Armor/Aether Blade progression.'),
  ]),
  phase('locked-rooms', 'Optional fortress keys and equipment rooms', [
    step('mw1-keys-officers', 'Officers Quarters keys: inspect the right-hand ticket booth at the main gate/F4; then reach the tower key via the floating excavator route. The two Quarters doors are above the Outlast hall: take its stairs up to the higher walkway. Each door consumes its own matching key.', 'Officers: gate ticket booth and excavator-route tower keys → upper Outlast walkway.', { images: [image('wzhub-season-1-m2580-1', 'Gate-side Officers Quarters key'), image('wzhub-season-1-m2630-1', 'Elevated Officers Quarters key candidate'), image('wzhub-season-1-m2566-1', 'Officers Quarters locked-room reference')] }),
    step('mw1-keys-munitions', 'Munitions keys: inspect the desk in the small western B4 building beside the warehouse/ACV area; and continue the floating-vehicle route over the ambulance/flatbed to its tower key. Match them to the two ground-floor Munitions doors around E5. A found weapon case is loot, not a guaranteed Scorcher.', 'Munitions: B4 desk and floating-vehicle tower keys → E5 storeroom doors.', { images: [image('wzhub-season-1-m2622-1', 'Western building Munitions key'), image('wzhub-season-1-m2629-1', 'Elevated Munitions key reference'), image('wzhub-season-1-m2621-1', 'Munitions storeroom door reference')] }),
    step('mw1-keys-barracks-antiquities', 'Barracks: inspect the H5 apartment dining/kitchen table and use the matching key at its fortress-side Barracks door. Antiquities: descend via the south gate/rope beneath the fortress and inspect the box at the rope’s bottom; its office door lies up the stairs on the Outlast hall’s side opposite Pack-a-Punch.', 'Barracks: apartment table key. Antiquities: underground rope-bottom box key.', { images: [image('wzhub-season-1-m2618-1', 'Apartment Barracks key'), image('wzhub-season-1-m2581-1', 'Barracks door'), image('wzhub-season-1-m2571-1', 'Underground Antiquities key'), image('wzhub-season-1-m2567-1', 'Antiquities office door')] }),
    step('mw1-conditional-keys', 'Two further key opportunities are conditional: feed at least three flesh chunks to the C3 dock doghouse, and clear the underground courtyard/F4 infested nest’s cysts. Inspect the actual dropped key name. The release-era reference reported variable/broken labels here; do not promise a specific bedroom key. If you obtain South Al Bagra Top Floor Bedroom access, use its named third-floor eastern apartment door.', 'Check doghouse rubble and cleared courtyard nest; match the actual key label.', { images: [image('wzhub-season-1-m2628-1', 'Courtyard/nest key reference'), image('wzhub-season-1-m2619-1', 'South Al Bagra Top Floor Bedroom locked-door reference')], note: 'Optional loot route: prioritize a safe exit over unfinished key searches on Elder’s short timer.' }),
  ], { note: 'Eight documented key opportunities lead to named rooms. Inspect each actual key and visible door; loot contents are variable.' }),
  phase('exfil', 'Use the appropriate exit and retain plans', [
    step('mw1-exfil', 'Story runs leave through the post-Gorm’gant mission exit. Contract visits can use the photographed fortress-roof F5 or lower/underground E4 exit. Navigate to an available red exit, interact before the timer expires and confirm extraction with your carried plans/relics.', 'Take the story exit or the roof/underground contract exit before time expires.', { images: [image('wzhub-season-1-m2563-1', 'Fortress roof exit reference'), image('wzhub-season-1-m2617-1', 'Lower fortress exit reference')] }),
  ]),
], [], [officialMissions, 'https://gameranx.com/features/id/484752/article/modern-warfare-3-zombies-how-to-enter-the-dark-aether-rift-act-4-boss-fight-easter-egg-and-schematics-guide/', 'https://gameranx.com/features/id/485266/article/modern-warfare-3-zombies-how-to-open-the-dark-aether-locked-doors-all-dark-aether-key-locations/', 'https://wzhub.gg/map/dark-aether/mwz'], { ...seasonalExtra('wzhub-season-1-m2611-1', 'Al Bagra fortress Pack-a-Punch'), aliases: ['Al Bagra Fortress', 'Bad Signal'], questLabel: 'Bad Signal / Al Bagra routes' })

const season2 = guide('mw3-dark-aether-season-2', 'mw3', 'Dark Aether — Season 2', 'Countermeasures supplies the gold Drum and three hidden purple offerings. Attune them in Urzikstan for Sa’id City portal access; repeat visits contain Bounty, Outlast and Extractors, with random Elder schematic rewards.', [
  prep('mw2'),
  phase('countermeasures', 'Countermeasures: story vehicle, mall and Krawvir', [
    step('mw2-mission-entry', 'Use the named Countermeasures mission portal and confirm the squad vote. If the gold Drum is already owned, only repeat the mission for missing purple offerings. The three hidden obelisks are available in this STORY version, not ordinary/Elder contract visits.', 'Enter named Countermeasures; its hidden offerings belong to the story version.'),
    step('mw2-ship-detour', 'For first unlock, collect the ship-deck MMA Gloves near spawn before leaving: climb around the back of the ship onto its deck, start the obelisk and use its supplied Insta-Kill to make fist/melee kills INSIDE the ritual circle. Stow the purple Gloves from the Reward Rift. Skip this detour if you already own them.', 'Unlock detour: ship obelisk, fist kills in its circle, purple MMA Gloves.', { images: [image('wzhub-season-2-m2939-1', 'Ship-deck MMA Gloves ritual location'), image('wzhub-season-2-m2939-2', 'MMA Gloves obelisk interaction reference')] }),
    step('mw2-soldiers-acv', 'Meet the nearby soldiers in the warehouse and return to the story ACV. Stay near it to advance the route. This mission vehicle has no ordinary Escort health meter to protect; defend yourself and the squad while it moves. At the gas-station/carnival halt, kill the EMP Mimic blocking progress, then stay near the vehicle through its neutralizer-part pickup.', 'Meet the soldiers, advance the ACV and defeat its EMP Mimic blocker.'),
    step('mw2-mirror-detour', 'During the part-retrieval pause, first-unlock players can collect the I8 foggy riverbed Mirror. Start its obelisk, read the element on the ritual circle’s BOUNDARY, equip the supplied matching mod and make the requested kills inside it. Complete each element and stow the purple Mirror. Wrong mod: leave until the ritual is abandoned, then retry. If loose loot covers a mod, stow/move it to reveal the prompt.', 'Unlock detour: riverbed circle, match each boundary element, purple Mirror.', pic('wzhub-season-2-m2938-1', 'Foggy riverbed Pristine Mirror obelisk')),
    step('mw2-mall', 'At the mall stop, enter and destroy all cysts across its lower wings and upper rooms. Use the gas-mask/ammo supplies and clear one section at a time. When the final cyst registers, regroup at the ACV and follow it toward the stadium stage.', 'Clear every mall cyst, regroup at the ACV and continue to the stadium.'),
    step('mw2-target-detour', 'Before starting the final stadium defense, first-unlock players can visit the E3/E4 crossroads Target obelisk. Make headshot/critical kills within its ritual area and collect the purple Perforated Target. Skip an already-owned offering and return to the story vehicle/stage.', 'Unlock detour: crossroads headshot obelisk → purple Target.', pic('wzhub-season-2-m2937-1', 'Crossroads Perforated Target obelisk')),
    step('mw2-stadium-boss', 'Activate and finish the stadium Outlast defense. After the betrayal/portal event, defeat Krawvir, the EMP Mangler: avoid its cannon, manage the EMP disruption and damage its exposed head. Open the reward for the GOLD Drum, verify carried purple offerings if unlocking, then use the story exit.', 'Finish stadium Outlast, defeat Krawvir and extract the gold Drum.'),
  ], { group: 'Main Quest' }),
  phase('relic-obelisks', 'Check or recover missing story offerings', [
    step('mw2-offering-check', 'Before leaving Countermeasures, verify the three optional obelisk rewards are carried: Tattered MMA Gloves, Pristine Mirror and Perforated Target. Their conditions are fist kills, matching boundary-element kills and headshots respectively. The gold Drum comes from Krawvir’s reward. If one is missing after extraction, repeat only the required story collection; already-gold items need no repeat attunement.', 'Check Gloves, Mirror, Target and gold Drum; replay only a missing story offering.'),
  ]),
  phase('attunement', 'Upgrade Mirror, Gloves and Target in Urzikstan', [
    step('mw2-gold-mirror', 'Carry the purple Mirror to I3’s graveyard offering pedestal. Offer it, identify the spawned zombie’s element and take the matching mod from the nearby rooftop tower. Kill the marked elemental zombie(s) with that mod and collect the GOLD Mirror; co-op can require multiple marked spawns.', 'I3 graveyard: offer Mirror, kill its matching-element spawn(s), collect gold.'),
    step('mw2-gold-gloves', 'At F8’s boxing gym, offer the purple Gloves in the ring. Melee the three punching bags LEFT to RIGHT, then melee-kill the marked spawned zombie. Collect the gold Gloves before leaving.', 'F8 gym: offer Gloves, punch bags left→right, melee the marked zombie.'),
    step('mw2-gold-target', 'Offer the purple Target at H8’s firing range. Shoot all eight appearing targets, then headshot the marked zombie that spawns. Take the gold Target from its reward. An ordinary bodyshot kill is not the requested critical-hit finish.', 'H8 range: offer Target, shoot eight targets, headshot the marked zombie.'),
  ]),
  phase('portal', 'Unlock the Nahr hill portal once', [
    step('mw2-pedestals', 'Bring the GOLD Drum, Mirror, Gloves and Target to the hill/tower tornado above Nahr Bathhouse. Match their pedestal engravings, including the pedestal set slightly away from the others. Do not substitute a purple item.', 'Place all four gold offerings at the Nahr hill/tower pedestals.'),
    step('mw2-gate-mimic', 'Defeat the gate EMP Mimic and take the access reward. This establishes the personal portal; later trips use the intended Sigil prompt. If the interaction seems absent, clear nearby enemies and inspect both sides/positions for its small prompt before assuming the ritual failed.', 'Defeat the gate EMP Mimic and confirm access; locate the actual Sigil prompt.'),
  ]),
  phase('contracts', 'Repeat visits: Bounty, Outlast and Extractors', [
    step('mw2-bounty', 'Near the northwest spawn ship/C5 reference, take the Bounty starter and kill the marked special. Its identity can vary, including a Mega Abomination; read the actual target. Keep adds occupied, use its critical areas and check the reward safely. If desired, do Extractors first and leave this combat-heavy target last.', 'Northwest ship Bounty: kill its actual marked special and collect the rift.'),
    step('mw2-outlast', 'Take the restaurant-area Outlast starter around E7 and activate its marked PND. Stay in the restaurant objective, manage Manglers/hellhounds and keep analysis progressing. Mantle counters/barriers if you need room; return inside after repositioning.', 'Restaurant Outlast: stay in its analysis zone until complete.', pic('wzhub-season-2-m2928-1', 'Sa’id City Outlast starter at the restaurant area')),
    step('mw2-extractors', 'Reach the Extractors starter on the mall’s highest roof/I6 reference. Use the external staircase/nearby mantle ledge or loading-dock crates and shelving rather than spending unnecessary time in gas. Follow the marked devices, distract enemies BEFORE entering the tight alley and finish uninterrupted panel holds; the last western site is more open.', 'Mall-roof Extractors: reach the roof and finish all marked shutdown panels.'),
    step('mw2-random-rewards', 'There is no seasonal Escort contract here. Ordinary rewards include acquisitions/Elder Sigil opportunities. Elder contracts can award Mags of Holding, Blood Burner Keys and V-R11 plans, but duplicates can occur and completing all three does not guarantee the whole set. Retain obtained plans through extraction.', 'Elder rewards are random: Mags of Holding, Blood Burner Keys, V-R11.'),
  ]),
  phase('music', 'Optional stadium music and navigation', [
    step('mw2-song', 'Interact with three song stones around the stadium: the southern opening with no stands, the field a little east of centre, and the announcer booth in the northernmost stands. This optional music route is separate from a contract reward or portal unlock.', 'Activate the south opening, east-centre field and north announcer-booth stones.'),
    step('mw2-wunderfizz', 'Wunderfizz floats above the restaurant. Use an available Aether Tear (the source references G6 and I7) or your own safe movement equipment to reach it. Pack-a-Punch can occupy several documented sites; look for its current marker instead of relying on one guaranteed location.', 'Use tears to reach elevated Wunderfizz; check the current Pack-a-Punch marker.', pic('wzhub-season-2-m2948-1', 'One documented Sa’id City Pack-a-Punch position')),
  ], { note: 'Optional detour: keep the current objective/timer in view before crossing to the stadium or floating vendor.' }),
  phase('exfil', 'Choose one of the four contract exits', [
    step('mw2-exits', 'Story runs leave through the mission’s final portal after Krawvir. Repeat visits have documented exits at I7, G4, D9 and C6; choose a reachable currently available exit before the timer runs low. Use the actual portal prompt and verify the post-match retained plans.', 'Take the mission exit or a repeat-visit I7/G4/D9/C6 exit before time expires.', pic('wzhub-season-2-m2949-1', 'Sa’id City southern D9 exit reference')),
  ]),
], [], [officialMissions, 'https://www.reddit.com/r/MWZombies/comments/1b9x24h/detailed_video_text_guide_to_unlocking_the_season/', 'https://www.reddit.com/r/MWZombies/comments/1btflqa/text_video_guide_to_mastering_the_season_2/', 'https://www.gamespot.com/articles/call-of-duty-mw3-zombies-how-to-unlock-season-2-dark-aether-rifts-and-new-schematics/1100-6521677/', 'https://wzhub.gg/map/dark-aether-s2r/mwz'], { ...seasonalExtra('wzhub-season-2-m2939-1', 'Sa’id City ship ritual'), aliases: ['Sa’id City', 'Said City', 'Countermeasures'], questLabel: 'Countermeasures / Sa’id routes' })

const season3 = guide('mw3-dark-aether-season-3', 'mw3', 'Dark Aether — Season 3', 'Union’s two rune crystals lead to Taoxla and the gold Giraffe Toy. Upgrade three Urzikstan relics for Zarqwa portal access, then choose acquisitions, Elder schematics or the optional Smoke Signals boss.', [
  prep('mw3s', 'Dead Wire Detonators, Golden Mask Filter and Sergeant’s Beret'),
  phase('union', 'Union: follow Ava and stop the two orbs', [
    step('mw3s-union-entry', 'Select Union and use its named high-threat island story portal. If you already own the gold Giraffe Toy, skip repeating the story for first unlock. Follow Ava/Ravenov until Ava enters the tornado and the two orb markers appear.', 'Use named Union, follow Ava and locate its two marked orbs.'),
    step('mw3s-orbs', 'Shoot each floating orb until it reaches its crystal site. One site is by the water tower/warehouses, the other among apartment buildings. Interact with a formed crystal to release its three white wisps and reveal its ordered rune display.', 'Shoot both orbs to their crystal sites and activate each crystal’s wisps.'),
  ], { group: 'Main Quest' }),
  phase('crystals', 'Read and shoot both three-rune sequences', [
    step('mw3s-crystal-a', 'Record Crystal A’s three displayed shapes LEFT to RIGHT. Follow its wisps and listen for the rune audio in the nearby warehouse/water-tower area. Find each matching wall sign and shoot them in the DISPLAYED order. A correctly completed crystal turns red and becomes destructible; break it.', 'Crystal A: record three runes, find the signs by wisps/audio and shoot in order.'),
    step('mw3s-crystal-b', 'Keep Crystal B’s apartment-site record separate. Search its building floors and surrounding signs while listening for the same audio cues, then shoot its displayed three shapes in order. Preserve/correct your observations after a wrong shot; do not reuse Crystal A’s order. Break B once it turns red.', 'Crystal B: record its independent apartment-site rune order and break the red crystal.'),
    step('mw3s-cleanse', 'Return to the tornado and interact with Ava’s unconscious body. Activate the three marked cleansing obelisks and feed each nearby zombie kills until its bar fills and the relic is released. Their revealed items preview the later unlock route. Once all three are cleansed, use the final obelisk before the Entity to start Taoxla.', 'Return to Ava, cleanse three obelisks and activate the final boss obelisk.'),
    step('mw3s-taoxla', 'Taoxla is a powerful Disciple. When its health bar is grey, kill its marked elite Minions first; they protect it from damage. Avoid its drain beam, clear adds and damage its head weakpoint during each vulnerable period. Repeat as new minions appear.', 'Kill Taoxla’s protective minions, then damage its head during vulnerability.'),
    step('mw3s-giraffe-story', 'Take the GOLD Giraffe Toy from Taoxla’s Reward Rift. Wake Ava, escort her to the marked exit and defend until it opens/she leaves; then extract. A defeated boss without the escort/exfil is not a finished Union mission.', 'Collect gold Giraffe, wake/escort Ava and finish the mission extraction.'),
  ]),
  phase('relics', 'Collect the three purple Urzikstan relics', [
    step('mw3s-laptop', 'Summon a friendly Hellhound through a normal flesh-fed doghouse or an available Dog Bone. Let that dog kill a mercenary SERGEANT, identified by the red beret, at a camp/stronghold or relevant mercenary objective. The dog must make the qualifying kill. Collect the purple Laptop With Stickers from the resulting rift.', 'Friendly dog kills a mercenary Sergeant → purple Laptop With Stickers.'),
    step('mw3s-journal', 'Enter this deployment’s Aether Storm with mask, damage and crowd-control preparation. Kill the required storm zombies (the documented route specifies fifty) and collect the purple Science Journal when its Reward Rift appears. Watch the Stormcaller and boosted enemies; killing the Stormcaller is not the journal requirement.', 'Kill storm zombies until the Science Journal rift appears; keep mask protection.'),
    step('mw3s-drawing', 'At Zohoor Ranch around I7, enter the main building, go upstairs and interact with the container UNDER the bed. Wait for the voice line and collect the purple Imaginary Friend Drawing from the bed’s reward rift.', 'I7 Zohoor Ranch: interact under the upstairs bed for the purple Drawing.'),
  ]),
  phase('attunement', 'Perform each item’s Tier 3 summoning', [
    step('mw3s-attunement-rule', 'Carry the item being upgraded. At its matching triangle, shoot the three nearby runes, stand at the viewpoint that aligns the glowing fragments into a triangle and use PERFORM THE SUMMONING. Kill glowing enemies within the resulting ring, defeat its special HVT and take the gold item. An ordinary triangle loot reward is not an item upgrade.', 'For each relic: three runes → alignment viewpoint → item summoning → ring kills → HVT → gold.'),
    step('mw3s-laptop-gold', 'Laptop: use the alley northwest of Opal Palace’s crumbling walls/F5 reference. The runes face the surrounding roof/wall/scaffolding. From the roof at the foot of the Palace stairs, stand in its stairwell doorway and face the alley to align the markings. Offer the Laptop, charge its ring and defeat the Mimic for the GOLD Laptop.', 'Laptop: northwest Palace alley; roof stairwell viewpoint; defeat its Mimic.', pic('wzhub-m3127-1', 'Opal Palace-side triangle alignment viewpoint reference')),
    step('mw3s-drawing-gold', 'Drawing: use the triangle by the destroyed northeast-facing Palace wall, above the stairway. Activate the surrounding wall runes, climb the broken wall and cross its gap for the alignment viewpoint. Perform its Drawing summoning, finish ring kills and defeat the Mangler for the GOLD Drawing.', 'Drawing: northeast broken Palace wall; wall-gap viewpoint; defeat its Mangler.'),
    step('mw3s-journal-gold', 'Journal: use the triangle near the northwest island/portal circle, by the east-facing bridge. Its runes are beside the bridge, on the southern building wall and on the circle’s arch. Align from the northeast end of the arch in front of Nahr Bathhouse, offer the Journal, charge the ring and defeat the enhanced Hellhound for the GOLD Journal.', 'Journal: island-bridge triangle; Nahr arch viewpoint; defeat its Hellhound.'),
  ]),
  phase('portal', 'Unlock the northwest island portal', [
    step('mw3s-pedestals', 'Bring the GOLD Giraffe Toy, Laptop, Drawing and Journal to the tornado on Tier 3’s northwest island. Match each pedestal engraving to its relic. Source grids straddle E3/E4; use the island circle and marked interaction rather than treating one grid label as an exact pin.', 'Place all four gold relics at the northwest island circle.'),
    step('mw3s-gate-disciple', 'Defeat the gate Disciple by eliminating its protective Minions when its bar is invulnerable, then damaging the main target. Collect the access/Sigil reward and record the completed permanent portal ritual. Future trips use ordinary or Elder entry items.', 'Defeat the gate Disciple/minions and confirm permanent access.'),
  ]),
  phase('contracts', 'Three obelisks and carried temporary buffs', [
    step('mw3s-escort', 'Find the gold beam to the G6 roof Escort obelisk. Take Atomic Hunter and keep it carried: marked green special enemies can provide a Nuke when killed by its carrier. Protect the ACV at all four stops and use crowd control or optional packed V-R11 repairs to preserve its health.', 'G6 roof Escort: carry Atomic Hunter and protect every ACV stop.'),
    step('mw3s-outlast', 'At the I3 Outlast obelisk, collect Numb Foot and keep it carried for its movement boost. Activate the PND and remain in the analysis zone until complete. Use the extra movement to escape pressure, then return to the zone rather than letting analysis stall.', 'I3 Outlast: carry Numb Foot and finish analysis inside the zone.'),
    step('mw3s-bounty', 'At the northern F1 Bounty obelisk, collect Mind-Blowing Revelation: headshot-marked enemies can explode on death while the item is carried. Fight the marked bounty using its critical areas and clear surrounding pressure. Contract order is flexible; Escort → Outlast → Bounty is one useful route for obtaining the buffs in that order.', 'F1 Bounty: carry Mind-Blowing Revelation and kill the marked HVT.'),
    step('mw3s-buff-rewards', 'These three buffs occupy rucksack slots and are temporary, not permanent account perks. Ordinary visits offer acquisitions/Elder Sigil opportunities. Elder rewards can include Dead Wire Detonators, Golden Mask Filter and Sergeant’s Beret schematics; they may repeat. Claim the rifts and preserve the actual plans until extraction.', 'Keep temporary buffs carried; Elder rewards are the three Season 3 schematic opportunities.'),
  ]),
  phase('gyanxi', 'Optional Gyanxi and Smoke Signals blueprint', [
    step('mw3s-gyanxi-gate', 'Complete ALL THREE contracts in this visit before this optional boss. Reserve enough time, damage, revives and an exit margin. Both ordinary and Elder variants can award Smoke Signals; ordinary provides the longer window and the blueprint is distinct from Elder schematic rewards.', 'Finish all three contracts in this visit before attempting Gyanxi.'),
    step('mw3s-spores', 'Go to the central island and destroy its WEST, NORTH and EAST spores. After all three, destroy the large central Rift Heart to summon Gyanxi. These island boss spores are separate from a Spore Control contract.', 'Destroy west, north and east island spores, then the central Rift Heart.', pic('wzhub-season-3-m3107-1', 'One island boss-spore reference; destroy the three outer spores before the central Heart')),
    step('mw3s-gyanxi-fight', 'Gyanxi is protected whenever its elite Minions are alive. Remove them first, then damage its head while vulnerability returns; repeat each new wave of protective minions. Claim the Smoke Signals RAM-7 unlock cue, loot safely and use the available exit before the visit’s timer ends.', 'Kill Gyanxi’s minions, damage the boss and confirm Smoke Signals before exiting.'),
  ], { note: 'Optional boss commitment: do not start the Rift Heart with too little time to fight and extract.' }),
  phase('exfil', 'Leave with the current rewards', [
    step('mw3s-exfil', 'Union uses Ava’s mission exit after the story escort. Repeat visits use the red portal near the southeast end of the central island (the source references G4/G5). Locate its actual marker/prompt before the timer runs low. Confirm your retained relics/plans and separate the optional blueprint unlock from owned schematics.', 'Take Ava’s story exit or the southeast island repeat-visit portal before time expires.'),
  ]),
], [], [officialMissions, 'https://gameranx.com/features/id/497551/article/modern-warfare-zombies-how-to-complete-the-union-story-mission/', 'https://gameranx.com/features/id/497546/article/modern-warfare-zombies-how-to-open-the-season-3-reloaded-dark-aether-rift/', 'https://gameranx.com/features/id/498663/article/cod-zombies-smoke-signals-blueprint/', 'https://detonated.com/mw3-zombies-secret-dark-aether-boss-fight-free-smoke-signals-blueprint-unlock-season-3-reloaded-quest/', 'https://wzhub.gg/map/dark-aether-s3r/mwz'], { ...seasonalExtra('wzhub-season-3-m3092-1', 'Zarqwa Dark Aether landmark'), aliases: ['Zarqwa Hydroelectric', 'Union'], questLabel: 'Union / Zarqwa routes' })

const unstable = guide('mw3-unstable-rift', 'mw3', 'Unstable Rift', 'Activate three ammo-mod obelisks in the current Urzikstan deployment, enter the public Rift and survive its five escalating arena phases. Final completion awards Mark of the Survivor and resets crafting cooldowns; the arena’s temporary boosts are not permanent schematic unlocks.', [
  phase('preparation', 'Prepare for a five-phase combat commitment', [
    step('unstable-kit', 'Prepare crowd-control and boss damage, self-revives and a coordinated squad recovery plan. Acquire the ammo mods needed for the obelisks and leave inventory room for arena supplies. Choose equipment that supports repeated waves rather than a fixed 2024 weapon-meta claim.', 'Prepare crowd control, boss damage, revives and the obelisks’ ammo mods.'),
    step('unstable-run-type', 'This is a wave arena, not a conventional thirty-minute seasonal contract visit. Entering commits the squad to five phases. Watch the in-game phase counter and objective prompts; do not start a separate countdown based on this page.', 'Treat entry as a five-phase arena commitment; follow the game’s phase counter.'),
  ], { group: 'Key Features' }),
  phase('obelisks', 'Complete three current ammo-mod obelisks', [
    step('unstable-find-obelisks', 'Search for currently spawned Urzikstan obelisks. Their possible sites vary and a photographed candidate does not guarantee a live altar. Read the sculpted ammo icon before spending the activation.', 'Find a live obelisk and read its required ammo-mod icon.', pic('wzhub-m3267-1', 'One possible Urzikstan Unstable Rift obelisk site; not a guaranteed live spawn')),
    step('unstable-mod-rings', 'Equip the displayed mod and activate the obelisk. Make its required zombie kills INSIDE the circle until the collection/success cue registers. Repeat at three completed altars, reading each current icon rather than assuming one fixed order.', 'Match each icon, kill within its ring and complete three altars.', { bullets: ['Flame icon: Napalm Burst.', 'Frost/snowflake icon: Cryo Freeze.', 'Electrical icon: Dead Wire.', 'Toxic/skull icon: Brain Rot.'] }),
  ], { group: 'Main Quest' }),
  phase('rift-entry', 'Use the spawned public Rift', [
    step('unstable-public-rift', 'After the required altar completions, locate the spawned Rift’s actual Tac-Map marker and interaction. Its position can vary and another squad can claim a public Rift; three website checks do not reserve it. Regroup and accept the travel vote only when ready.', 'Locate the live public Rift, regroup and confirm arena entry.'),
    step('unstable-temporary-kit', 'On arrival, check the supplied weapon upgrades, perk effects, regenerating armour/ammunition support and Mags of Holding-style temporary boosts. They help this arena and do not grant the corresponding crafting plans. Tombstone protection is disabled here; survive and extract rather than relying on a carried-item fallback.', 'Check arena-granted temporary boosts; they are not permanent plans.'),
  ]),
  phase('phase-1', 'Phase 1: establish the arena route', [
    step('unstable-wave1', 'Find a safe movement loop and cover each other’s approach lanes while clearing the first wave. Keep a clear path to a downed teammate and watch the phase counter for its ending HVT. Kill that marked boss, then claim the phase Reward Rift and replenish before the next counter begins.', 'Clear phase 1 and its ending HVT; resupply from the phase reward.'),
  ]),
  phase('phase-2', 'Phase 2: maintain crowd control and resupply', [
    step('unstable-wave2', 'As pressure increases, use the equipment gained from the prior phase rather than hoarding it through a down. Keep enemies away from revives, pick up needed armour/ammunition and focus the ending HVT when its marker appears. Confirm Phase Complete and claim the next reward before advancing.', 'Maintain crowd control, defeat phase 2’s HVT and claim the resupply reward.'),
  ]),
  phase('phase-3', 'Phase 3: balance specials with the wave', [
    step('unstable-wave3', 'Prioritize specials disrupting your movement or draining health while retaining a safe loop for the normal horde. Split boss damage and crowd-control roles when the phase-ending HVT appears. Finish the displayed objective, revive/reload and inspect its reward before the fourth phase.', 'Control the specials, kill phase 3’s marked HVT and prepare the squad again.'),
  ]),
  phase('phase-4', 'Phase 4: preserve the final-fight reserve', [
    step('unstable-wave4', 'Expect heavier pressure and protect a safe revive lane rather than spreading across the arena. Use available support against the ending HVT while another player covers its adds. After completion, equip the reward supplies and check every player’s revival capacity before the last phase.', 'Survive phase 4, defeat its HVT and prepare everyone for the final phase.'),
  ]),
  phase('phase-5', 'Phase 5: finish the final HVT', [
    step('unstable-wave5', 'Clear the final wave and defeat its elite Disciple/HVT objective. Remove protective elite minions if the main target becomes invulnerable, then focus its exposed critical area; cover revives and keep the horde occupied. Wait for the final completion/reward cue rather than treating the first boss damage window as victory.', 'Finish phase 5’s final boss and wait for the arena completion cue.'),
  ]),
  phase('rewards', 'Claim Mark of the Survivor and leave', [
    step('unstable-reward', 'After all five phases, confirm the Mark of the Survivor unlock and cooldown-reset reward. Use the red exit portal to finish extraction; it ends the deployment. Check the actual crafting menu afterward for the reset state. Entry or an early phase reward alone grants neither final completion nor a completed cooldown reset.', 'Confirm the camo/cooldown reward and use the final red exit.'),
  ]),
], [], ['https://www.callofduty.com/blog/2024/06/call-of-duty-modern-warfare-iii-warzone-wzm-season-4-reloaded-maps-modes-zombies-announcement', 'https://primagames.com/featured/modern-warfare-zombies-mwz-unstable-rift-guide-how-to-unlock-locations-and-all-easter-eggs', 'https://www.reddit.com/r/CODZombies/comments/1dpzk3c', 'https://www.charlieintel.com/call-of-duty/how-to-complete-mw3-zombies-unstable-rift-easter-egg-unlock-mark-of-the-survivor-camo-330822/'], { ...extra('wzhub-m3267-1', 'Unstable Rift candidate obelisk'), mode: 'Five-phase arena', questLabel: 'Unstable Rift challenge' })

const season5 = guide('mw3-dark-aether-season-5', 'mw3', 'Dark Aether — Season 5', 'Ascension’s true Entity ending supplies gold Mr. Peeks. Attune three Echo relics for the Opal Palace portal, then choose ordinary acquisitions, Elder schematics or the Elder-only Infinite Cosmos STG44 blueprint route.', [
  prep('mw5'),
  phase('ascension', 'Ascension: weaken the Entity and finish its true ending', [
    step('mw5-ascension-entry', 'Use the named Ascension story portal in the gazebo at the northeast side of Opal Palace’s fountain square. Confirm its mission name and squad vote. If gold Mr. Peeks is already safely owned, first-unlock players can skip repeating this story.', 'Enter Ascension’s Opal Palace gazebo portal; skip a previously owned gold Peeks.', pic('mw-s5-story-03', 'Ascension story portal entrance beside Opal Palace')),
    step('mw5-first-obelisk', 'At the F6 story obelisk, interact with four nearby relics to send them to Ava: Gloves northeast of the obelisk, Drum in the western floating train car, Target on its connected flatbed and Mirror to the south. Activate the obelisk and make zombie kills close to Ava until she destroys it.', 'F6: send Gloves, Drum, Target and Mirror; charge Ava with nearby kills.', { images: [image('mw-s5-story-04', 'First obelisk Gloves location'), image('mw-s5-story-05', 'First obelisk Drum in the train'), image('mw-s5-story-06', 'First obelisk Target on the connected platform'), image('mw-s5-story-07', 'First obelisk Mirror location')] }),
    step('mw5-second-obelisk', 'At E5’s next obelisk, send Journal from eastern rubble, Giraffe beside the stone tower, Drawing on the floating truck and Laptop on the road beneath it. Charge Ava with kills. When the Entity scatters these relics, follow their markers and send them back so charging can resume.', 'E5: send Journal, Giraffe, Drawing and Laptop; recover the scattered items.', { images: [image('mw-s5-story-08', 'Second obelisk Journal'), image('mw-s5-story-09', 'Second obelisk Giraffe'), image('mw-s5-story-10', 'Second obelisk Drawing'), image('mw-s5-story-11', 'Second obelisk Laptop')] }),
    step('mw5-tower-climb', 'Follow the objective to Ava/Ravenov at the tower. Ride a floating train to the raised island, then the orbiting boats/cars to the roof while avoiding window Manglers. Break the red crystal on the NORTH roof and use the opened launch pad/Aether Rift. Follow the connected platforms and pads to the arena; a Scorcher is optional movement support, not a quest prerequisite.', 'Ride the floating vehicles up the tower; break its north crystal and follow pads/Rifts.'),
    step('mw5-entity-first', 'Meet Ava/Ravenov at the altar and damage the Entity by shooting the glowing orbs on its body. Avoid its beam and shoot the tracking purple orbs released as it changes platforms. Repeat until the first health bar empties; the apparent first Reward Rift is a FAKE ending.', 'Shoot body orbs, evade beams and clear tracking orbs; expect the fake ending.', pic('mw-s5-story-12', 'The Entity’s visible body-orb damage targets')),
    step('mw5-entity-final', 'In the real final phase, the Entity is initially invulnerable. Join Ava on the boss’s current platform and kill zombies nearby to charge her attack. Once she opens vulnerability, destroy the exposed body orbs. Use launch pads to escape the all-platform lightning; clearing the full orb set can interrupt it. Each relocation requires another Ava charge and vulnerable damage cycle.', 'Charge Ava near the current boss platform; destroy exposed orbs and escape lightning.', pic('mw-s5-story-13', 'Second-phase Entity arena and platform movement')),
    step('mw5-peeks-story', 'After the true defeat, collect GOLD Mr. Peeks from the real Reward Rift. Let the dialogue finish, then use Ava’s opened exit to complete Ascension and keep the item. Neither the false first defeat nor three ordinary contracts supply this story relic.', 'Take gold Mr. Peeks from the true reward and use Ava’s exit.', pic('mw-s5-story-14', 'Ascension’s concluding reward/exit scene')),
  ], { group: 'Main Quest' }),
  phase('echo-relics', 'Obtain the three purple Echo relics', [
    step('mw5-echo-diary', 'Use an Aether Blade on grouped Special zombies until the Echo of Locked Diary reward appears. The G6 submerged triangle/Mimic activity provides a practical cluster: find its three water runes by audio, shoot them, align its triangle from the dock and work the spawned Mimics. Bounce the blade through grouped Specials rather than promising a fixed five-kill rule; collect the actual purple Echo Diary rift.', 'Cluster Specials at G6 and use blade bounces until the Echo Diary rift appears.', { images: [image('mw-s5-unlock-04', 'G6 waterway rune example'), image('mw-s5-unlock-05', 'Submerged triangle alignment'), image('mw-s5-unlock-06', 'Aether Blade special-enemy action'), image('mw-s5-unlock-07', 'Echo of Locked Diary reward item')] }),
    step('mw5-echo-drum', 'Find or summon a Blood Burner and reach the canal around F4/G4 beside its Peeks cue. Drive on the water following the WHITE arrows: down the canal, right into the river, onto land before the bridge, then along the road past the wrecked car. Collect the purple Echo of Drum from the course Reward Rift.', 'Blood Burner: follow the F4/G4 white-arrow canal course for Echo Drum.', { images: [image('mw-s5-unlock-12', 'Blood Burner canal-course map reference'), image('mw-s5-unlock-13', 'Blood Burner course starting/arrow cue'), image('mw-s5-unlock-14', 'Echo of Drum reward')] }),
    step('mw5-echo-giraffe', 'Activate Sergeant’s Beret to disguise yourself. At a mercenary camp, approach the relevant guard from behind and hold the melee control for an EXECUTION, rather than an ordinary punch or firearm kill. Collect purple Echo of Giraffe Toy from its Reward Rift.', 'With Sergeant’s Beret disguise, execute a mercenary from behind for Echo Giraffe.', { images: [image('mw-s5-unlock-19', 'Disguised rear execution for Echo Giraffe'), image('mw-s5-unlock-20', 'Echo of Giraffe Toy reward')] }),
  ]),
  phase('attunement', 'Attune each Echo through its meteor event', [
    step('mw5-diary-gold', 'Carry Echo Diary to the D2 eagle-ramp statue and interact with its corpse/meteor. Take/activate the supplied PhD Flopper if needed. Use the golden portal to the Popov power chimney, then dolphin-dive onto the BLUE container’s Phoenix marking below. A missed landing can be retried through the portal beneath the tower. Claim GOLD Echo Diary from the successful landing rift.', 'D2 eagle meteor → PhD → Popov chimney → dive onto Phoenix blue container.', { images: [image('mw-s5-unlock-09', 'Eagle corpse/meteor attunement interaction'), image('mw-s5-unlock-10', 'Phoenix-marked blue container landing target'), image('mw-s5-unlock-11', 'Gold Echo Diary reward')] }),
    step('mw5-drum-gold', 'Carry Echo Drum to the four-pillar square east of F7 Shorok Opera House. Use a vehicle to reach the central corpse/meteor pillar and begin its ritual. Interact with the surrounding pillars to take the requested mods, then kill each coloured zombie with its MATCHING element: green Brain Rot, blue Dead Wire, white Cryo Freeze and red Napalm Burst. Collect GOLD Echo Drum when all required kills register.', 'F7 Opera meteor: match green/blue/white/red enemies to Brain Rot/Dead Wire/Cryo/Napalm.', { images: [image('mw-s5-unlock-16', 'Opera House central meteor interaction'), image('mw-s5-unlock-17', 'Coloured elemental-zombie ritual'), image('mw-s5-unlock-18', 'Gold Echo Drum reward')] }),
    step('mw5-giraffe-gold', 'At the square east of F4 Nahr Bathhouse, crouch into the wrecked van to use its corpse/meteor with Echo Giraffe carried. Defeat the chain: Mega Abomination, EMP Mimic, then Disciple. Kill the Disciple’s marked minions whenever they protect it, and finish the main target for GOLD Echo Giraffe.', 'F4 Nahr van meteor: Mega → EMP Mimic → Disciple/minions → gold Echo Giraffe.', { images: [image('mw-s5-unlock-22', 'Nahr wrecked-van meteor interaction'), image('mw-s5-unlock-23', 'Echo Giraffe elite chain'), image('mw-s5-unlock-24', 'Gold Echo Giraffe reward')] }),
  ]),
  phase('portal', 'Complete the Opal Palace gold-relic ritual', [
    step('mw5-gold-pedestals', 'Bring GOLD Mr. Peeks and all three GOLD Echo relics to the F5 Opal Palace fountain inside its tornado. Match each pedestal engraving. Earlier seasons’ ordinary Diary, Drum and Giraffe are not their Echo versions and do not substitute.', 'Place gold Peeks and gold Echo Diary/Drum/Giraffe at the fountain pedestals.', pic('mw-s5-unlock-26', 'Opal Palace fountain pedestal interaction')),
    step('mw5-gate-mega', 'Defeat the spawned Mega Abomination and collect its access/Sigil reward. Confirm personal permanent access, then prepare the correct ordinary/Elder interaction for future trips. No repeated relic ritual is required after the unlock is complete.', 'Defeat the fountain Mega Abomination and confirm personal access.'),
  ]),
  phase('contracts', 'Navigate three floating contract starters', [
    step('mw5-movement', 'Use the map’s launch pads and Aether Tears to move between rooftops/floating structures. Follow each gold beam/Peeks cue and identify a reachable exit first. You can move without a Scorcher; recover a missed jump through the available lower route/pad rather than abandoning a carried key or contract.', 'Use pads/Tears and gold beams; locate an exit before starting contracts.'),
    step('mw5-outlast', 'Reach the north/lower Highrise roof at G2 and take its Outlast Peeks on the box. Go to the marked ground-floor PND and remain inside its analysis room until complete. Keep your return route to the roof and exit in mind.', 'G2 north Highrise roof Outlast → ground-floor PND analysis.', { images: [image('mw-s5-unlock-28', 'North Highrise Outlast Peeks starter'), image('mw-s5-unlock-29', 'Highrise ground-floor Outlast objective')] }),
    step('mw5-spore-contract', 'Reach the floating D3 crane’s Spore Control Peeks. Collect the inhibitors and use them at each marked spore before shooting it. Some objectives sit on floating islands; check a safe pad/Tear approach and retrieve needed inhibitors deliberately. These contract spores are separate from the hidden R4D spore below Highrise.', 'D3 floating-crane Spore Control: place inhibitors and destroy all marked spores.', { images: [image('mw-s5-unlock-31', 'Floating-crane Spore Control Peeks'), image('mw-s5-unlock-32', 'Floating Spore Control objective reference')] }),
    step('mw5-escort', 'Reach the E5 broken billboard Peeks for Escort and follow the ACV’s long route. Protect all four stops, using crowd-control equipment and optional packed V-R11 repair. The final stop can benefit from an available turret circuit; no turret spawn is guaranteed. A destroyed ACV fails this contract.', 'E5 billboard Escort: protect the ACV through all four stops.', { images: [image('mw-s5-unlock-34', 'Billboard Escort Peeks starter'), image('mw-s5-unlock-35', 'Season 5 ACV Escort objective')] }),
    step('mw5-contract-rewards', 'Ordinary contract rewards can provide Disciple Bottle or Grenade Bandolier acquisitions and possible Elder Sigils. Elder is the schematic route for those two items and Stash Increase, with possible duplicate rewards. Stash Increase is an account/storage benefit, not an equipment bottle consumed during combat. Carry plans to extraction and confirm the actual unlock.', 'Elder opportunities: Disciple Bottle, Grenade Bandolier and Stash Increase.'),
  ]),
  phase('infinite-cosmos', 'Optional Elder-only Infinite Cosmos blueprint', [
    step('mw5-cosmos-spore', 'For the Infinite Cosmos STG44 blueprint, enter with an ELDER Sigil. Under the main Highrise building, place an inhibitor by the unmarked central-room spore and shoot it after its shell opens. Take the dropped R4D detector; this spore is separate from the ordinary contract objectives.', 'Elder: inhibitor/shoot the hidden Highrise spore and collect R4D.'),
    step('mw5-cosmos-skull', 'Use R4D to reveal/follow the room’s arrows through the maze in sequence. At the yellow glow stick, look through the detector to reveal and stow the Damp Gold Skull. Have a teammate cover the reader; a missed jump does not remove the clue sequence.', 'Follow R4D arrows to the yellow glow stick; reveal/stow Damp Gold Skull.'),
    step('mw5-cosmos-trade', 'Return to the Golden Whale lobby across from the R4D building. Reach the whale’s head and trade the skull for the IT Thumb Drive. Its serial clue points to C3’s Spec Electronics; confirm the drive is carried before leaving.', 'Trade the Skull at Golden Whale for the IT Thumb Drive.'),
    step('mw5-cosmos-key', 'At Spec Electronics in C3, use the second-floor error-screen computer with the drive. Defeat the marked Keyholder Mangler and collect the Maintenance Tower Key from its drop. A normal Mangler kill without this interaction is not the key step.', 'Use the C3 second-floor computer; defeat Keyholder and collect Maintenance Tower Key.'),
    step('mw5-cosmos-door', 'Return to the Highrise roof/exfil level by the floating-train route or available movement equipment. Unlock the maintenance door with the key. Bring EVERY squad member inside: the portal changes from red to purple when the squad is present. Finish other desired activities before entering.', 'Open the Highrise maintenance door; assemble the whole squad for the purple portal.', { note: 'Squad commitment: entering this portal starts Entity’s Echo. Three completed contracts alone do not trigger this blueprint route.' }),
    step('mw5-cosmos-echo', 'Fight Entity’s Echo by damaging its visible body orbs, moving between pads to avoid beams and clearing tracking orbs/adds. Assign crowd control and boss damage as needed. Confirm the Infinite Cosmos STG44 unlock after the Elder defeat and use the ending/exit cue. An ordinary version of this secret fight does not award the blueprint.', 'Defeat Entity’s Echo in Elder and confirm the Infinite Cosmos unlock.'),
  ], { note: 'Optional separate quest: the blueprint requires Elder. Preserve the carried Skull/Drive/Key and reserve enough time for the squad portal and boss.' }),
  phase('exfil', 'Use the story or contract exit', [
    step('mw5-exfil', 'Ascension leaves through Ava’s portal after the true Entity ending. Repeat visits have photographed Highrise/roof and lower E7 exit options; use the actual available red portal before the run expires. Keep acquired relics/plans in your rucksack and verify the post-match rewards. Infinite Cosmos has its own boss ending/exit commitment.', 'Take Ava’s story exit or a safe repeat-visit portal with your carried rewards.', { images: [image('wzhub-season-5-m3223-1', 'Highrise/upper exit reference'), image('wzhub-season-5-m3223-2', 'Upper exit approach'), image('wzhub-season-5-m3241-1', 'Lower E7 exit reference')] }),
  ]),
], [], ['https://gameranx.com/features/id/506621/article/modern-warfare-zombies-how-to-complete-the-final-story-mission-ascension-story-mission-walkthrough/', 'https://gameranx.com/features/id/506654/article/modern-warfare-zombies-how-to-get-all-4-relics-and-enter-the-final-dark-aether-rift/', 'https://detonated.com/mw3-zombies-infinite-cosmos-blueprint-easter-egg-guide-season-5-reloaded/', 'https://www.callofduty.com/uk/en/blog/2024/08/call-of-duty-modern-warfare-iii-warzone-wzm-season-5-reloaded-maps-modes-zombies-announcement', 'https://wzhub.gg/map/dark-aether-s5r/mwz'], { ...seasonalExtra('mw-s5-story-01', 'Ascension and Highrise Dark Aether'), aliases: ['Highrise', 'Al Mazrah City', 'Ascension'], questLabel: 'Ascension / Highrise routes' })

const urzikstanOrder = ['deployment', 'dark-aether-portals', 'red-worm', 'side-quests', ...["free-juggernog","free-speed-cola","free-death-perception","free-deadshot","free-phd","free-quick-revive","free-staminup","free-tombstone"], 'vault', 'triangles', 'other-side-quests', 'contracts', 'equipment', 'story', 'rune-portals', 'exfil']
urzikstan.phases.sort((a, b) => urzikstanOrder.indexOf(a.id) - urzikstanOrder.indexOf(b.id))
urzikstan.phases.find(phase => phase.id === 'contracts').group = 'Deployment Reference'
urzikstan.aliases.push('Red Worm', 'Greylorm', 'free perks', 'chess vault', 'Dark Aether portals')
urzikstan.sectionLinks = [{ id: 'details-dark-aether-portals', text: 'Unlock a Dark Aether portal' }, { id: 'details-red-worm', text: 'Red Worm boss fight' }, { id: 'details-side-quests', text: 'Free perks' }, { id: 'details-vault', text: 'Chess vault' }]
season1.sectionLinks = [{ id: 'details-bad-signal', text: 'Bad Signal' }, { id: 'details-relics', text: 'Collect relics' }, { id: 'details-attunement', text: 'Gold upgrades' }, { id: 'details-portal', text: 'Open the portal' }, { id: 'details-locked-rooms', text: 'Secret rooms' }]
season2.sectionLinks = [{ id: 'details-countermeasures', text: 'Countermeasures' }, { id: 'details-attunement', text: 'Gold upgrades' }, { id: 'details-portal', text: 'Open the portal' }, { id: 'details-music', text: 'Stadium music' }]
season3.sectionLinks = [{ id: 'details-union', text: 'Union' }, { id: 'details-relics', text: 'Collect relics' }, { id: 'details-attunement', text: 'Gold upgrades' }, { id: 'details-portal', text: 'Open the portal' }, { id: 'details-gyanxi', text: 'Smoke Signals boss' }]
season5.sectionLinks = [{ id: 'details-ascension', text: 'Ascension' }, { id: 'details-echo-relics', text: 'Echo relics' }, { id: 'details-attunement', text: 'Gold upgrades' }, { id: 'details-portal', text: 'Open the portal' }, { id: 'details-infinite-cosmos', text: 'Infinite Cosmos' }]
unstable.sectionLinks = [{ id: 'details-obelisks', text: 'Activate obelisks' }, { id: 'details-rift-entry', text: 'Enter the Rift' }, { id: 'details-phase-1', text: 'Five-wave challenge' }]

export const mw3Guides = [urzikstan, season1, season2, season3, unstable, season5]
const urzikstanMapLinks = {
  'mw1-bad-signal-entry': ['season-1-portal', 'Find the island portal area'],
  'mw1-pedestals': ['season-1-portal', 'Find the Season 1 pedestals'],
  'mw2-mission-entry': ['season-2-portal', 'Find the Nahr portal area'],
  'mw2-pedestals': ['season-2-portal', 'Find the Season 2 pedestals'],
  'mw2-gold-mirror': ['s2-mirror-upgrade', 'Find the Mirror graveyard area'],
  'mw2-gold-gloves': ['s2-gloves-upgrade', 'Find the boxing gym area'],
  'mw2-gold-target': ['s2-target-upgrade', 'Find the firing range area'],
  'mw3s-union-entry': ['season-3-portal', 'Find the northwest island portal'],
  'mw3s-pedestals': ['season-3-portal', 'Find the Season 3 pedestals'],
  'mw3s-laptop-gold': ['s3-laptop-upgrade', 'Find the Laptop triangle'],
  'mw3s-drawing-gold': ['s3-drawing-upgrade', 'Find the Drawing triangle'],
  'mw3s-journal-gold': ['s3-journal-upgrade', 'Find the Journal triangle'],
  'mw5-ascension-entry': ['season-5-portal', 'Find the Opal Palace portal area'],
  'mw5-gold-pedestals': ['season-5-portal', 'Find the Season 5 fountain area'],
  'mw5-echo-drum': ['s5-drum-course', 'Find the Blood Burner course start'],
  'mw5-diary-gold': ['s5-diary-upgrade', 'Find the eagle-ramp meteor'],
  'mw5-drum-gold': ['s5-drum-upgrade', 'Find the four-pillar square area'],
  'mw5-giraffe-gold': ['s5-giraffe-upgrade', 'Find the wrecked-van area'],
  'unstable-find-obelisks': ['unstable-obelisks', 'Browse possible Urzikstan obelisks'],
}
for (const guide of mw3Guides) {
  if (guide !== unstable) guide.aliases = [...(guide.aliases || []), 'interactive map']
  for (const phase of guide.phases) for (const entry of phase.steps) {
    const link = urzikstanMapLinks[entry.id]
    if (link) entry.links = [...(entry.links || []), { href: `/guides/mw3-urzikstan#map:${link[0]}`, label: link[1] + ' on the Urzikstan map' }]
  }
}
for (const guide of mw3Guides) guide.reviewNote = 'Illustrated instructions from the references below, source-reviewed on 8 October 2026 and reorganized on 9 October 2026. The guide links, saved-progress compatibility and page behavior have software checks. These walkthroughs have not been verified in a complete in-game playthrough. Gameplay-image and chart creators are credited with each illustration.'
