import fs from 'node:fs'
import { tool, field, image } from './remaining-common.mjs'
const { mwRunePortals: portals, redWorm, mwRifts } = JSON.parse(fs.readFileSync(new URL('../docs/remaining-games/puzzle-data.json', import.meta.url), 'utf8'))
const glyphImages = Object.fromEntries(portals.glyphs.map(g => [g.id, { ...image(g.referenceAssetId, g.memoryLabel), crop: { columns: 3, column: g.panelIndex } }]))
const glyphLabels = Object.fromEntries(portals.glyphs.map((g, i) => [g.id, `${i + 1} · ${g.memoryLabel}`]))
const portalImages = Object.fromEntries(portals.destinations.map(d => [d.id, [image(d.codeAssetId, `Shoot these three glyphs left to right for ${d.grid} · ${d.id}`), image(d.contextAssetId, `Exit landmark at ${d.grid} · ${d.id}`)]]))
const usbFields = Array.from({ length: 4 }, (_, i) => [field(`photo-${i}`, `Photo ${i + 1}: matched location`, redWorm.candidateLocations.map(l => l.id), { optionLabels: Object.fromEntries(redWorm.candidateLocations.map(l => [l.id, `${l.grid} · ${l.landmark}`])) }), field(`drive-${i}`, `Photo ${i + 1}: USB obtained`, redWorm.driveIdentities), field(`carried-${i}`, `Photo ${i + 1}: drive currently carried`, null, { type: 'check' })]).flat()
const runeFields = ['a', 'b'].flatMap(crystal => [...Array.from({ length: 3 }, (_, i) => [field(`${crystal}-rune-${i}`, `Crystal ${crystal.toUpperCase()} · glyph ${i + 1} description`, null, { maxLength: 80 }), field(`${crystal}-place-${i}`, `Glyph ${i + 1} location / landmark`, null, { maxLength: 120 })]).flat(), field(`${crystal}-done`, `Crystal ${crystal.toUpperCase()} accepted all three shots and broke`, null, { type: 'check' })])
export const mw3Tools = [
  tool('mw3-rune-portals', 'mw3-urzikstan', 'Rune portal destination codes', 'Choose an exit to see its photographed code, or match three observed glyphs in order. Grid squares can contain several exits; each marker remains separate.', [field('mode', 'Lookup method', ['Destination', 'Read code']), field('destination', 'Exit destination', portals.destinations.map(d => d.id), { optionLabels: Object.fromEntries(portals.destinations.map(d => [d.id, `${d.grid} · ${d.id}`])) }), ...Array.from({ length: 3 }, (_, i) => field(`glyph-${i}`, `Shot ${i + 1}`, portals.glyphs.map(g => g.id), { optionImages: glyphImages, optionLabels: glyphLabels }))], { kind: 'lookup', groups: [{ id: 'method', title: 'Choose a lookup', fields: ['mode'] }, { id: 'destination', title: 'Exit', fields: ['destination'], showWhen: { field: 'mode', value: 'Destination' } }, { id: 'code', title: 'Observed code · left to right', fields: ['glyph-0', 'glyph-1', 'glyph-2'], showWhen: { field: 'mode', value: 'Read code' } }], portalImages, reference: 'https://wzhub.gg/map/urzikstan/mwz' }),
  tool('mw3-red-worm-usbs', 'mw3-urzikstan', 'Red Worm USB records', 'Match this deployment’s four wall photographs to the chart, then record each console’s actual drive identity. A landmark does not have a permanent Alpha/Bravo/Charlie/Delta assignment.', [...usbFields, field('arena', 'Paired ammo-cache / refractor arena landmark', null, { maxLength: 120 }), field('caches', 'Both ammunition caches and refractors found', null, { type: 'check' })], { groups: [...Array.from({ length: 4 }, (_, i) => ({ id: `photo-${i}`, title: `Clue photo ${i + 1}`, fields: [`photo-${i}`, `drive-${i}`, `carried-${i}`] })), { id: 'arena', title: 'This run’s boss arena', fields: ['arena', 'caches'] }], images: [image(redWorm.chartAssetId, 'spaz33g’s clue-wall and twelve USB-location chart; use the landmark photographs')], resetScopes: [{ id: 'deployment', label: 'New deployment', fields: [...usbFields.map(f => f.id), 'arena', 'caches'] }], reference: 'https://gameranx.com/features/id/485365/article/modern-warfare-3-zombies-secret-red-worm-boss-fight-greylorm-easter-egg-guide/' }),
  tool('mw3-dark-aether-reference', 'mw3-urzikstan', 'Dark Aether entry and rewards', 'Find the destination and entry variant for your objective. Record permanent access and schematics separately in the MWZ milestones panel.', [field('goal', 'Objective', ['Story', 'First portal unlock', 'Acquisitions', 'Schematics', 'Blueprint']), field('season', 'Destination season', mwRifts.map(r => String(r.season))), field('reward', 'Desired schematic (optional)', mwRifts.flatMap(r => r.schematics))], { kind: 'reference' }),
  tool('mw3-union-runes', 'mw3-dark-aether-season-3', 'Union crystal rune records', 'Record each crystal’s three symbols in displayed order. Follow its wisps and audio to matching nearby wall glyphs. Keep A and B separate; do not substitute the Urzikstan portal alphabet.', runeFields, { groups: ['a', 'b'].map(c => ({ id: c, title: `Crystal ${c.toUpperCase()}`, fields: runeFields.filter(f => f.id.startsWith(`${c}-`)).map(f => f.id) })), resetScopes: ['a', 'b'].map(c => ({ id: c, label: `Clear crystal ${c.toUpperCase()}`, fields: runeFields.filter(f => f.id.startsWith(`${c}-`)).map(f => f.id) })) }),
]
for (const definition of mw3Tools) definition.guidePhase = ({ 'mw3-rune-portals': 'rune-portals', 'mw3-red-worm-usbs': 'red-worm', 'mw3-dark-aether-reference': 'side-quests', 'mw3-union-runes': 'crystals' })[definition.id]
mw3Tools.find(definition => definition.id === 'mw3-dark-aether-reference').sharedMaps = mwRifts.map(rift => rift.mapId)
