import { step, phase, guide, image } from './remaining-common.mjs'
const k = slug => `https://mmmrkennedy.com/games/VG/${slug}/${slug}_guide`
const czg = slug => `https://www.codzombieguides.com/${slug}`
const pic = (id, alt) => ({ images: [image(id, alt)] })
const side = (id, title, steps, extra = {}) => phase(id, title, steps, { group: 'Side Quests', ...extra })
const officialSystems = 'https://www.treyarch.com/game-intel/2021/11/Your_Gameplay_Guide_to_Vanguard_Zombies'
const perks = ['Fiendish Fortitude: health; the Jugger-Nog counterpart.', 'Venomous Vigor: recovery/revive support; the Quick Revive counterpart.', 'Demonic Frenzy: reload speed; the Speed Cola counterpart.', 'Aethereal Haste: movement; the Stamin-Up counterpart.', 'Diabolical Damage: precision/critical damage; the Deadshot counterpart.']

const derAnfang = guide('vanguard-der-anfang', 'vanguard', 'Der Anfang', 'Open Stalingrad’s objective routes, explore Von List’s Office and follow the short narrative bridge into Terra Maledicta. Its final dialogue is the story endpoint; continued objectives, Void survival and ordinary exfil remain available.', [
  phase('systems', 'Prepare the Stalingrad objective hub', [
    step('anfang-objectives', 'Choose a portal for the district you need to open and complete its objective. Read its on-screen condition: survival, enemy-drop deposits, escort/capture and defense tasks use different completion rules. Returning to Stalingrad opens that route and rewards a Sacrificial Heart. Spend Essence between objectives and recheck the refreshed Covenant offerings.', 'Complete district portals to open the hub and earn Sacrificial Hearts.'),
    step('anfang-pap', 'Pack-a-Punch is already in Stalingrad’s starting hub. Its upgrade tiers cost 7,500, 15,000 and 30,000 Essence. Ammo-mod effects come through Covenants rather than a Pack-a-Punch ammo-mod menu. These are Vanguard’s source-documented prices, not Cold War’s price schedule.', 'Use hub Pack-a-Punch; buy ammo effects through Covenants.', pic('extra-czg-der-anfang-02', 'Der Anfang hub Pack-a-Punch and its upgrade tiers')),
    step('anfang-perks', 'Find the opened districts’ perk fountains. The first drink at each is free; later tiers cost 2,500, 5,000 and 7,500 Essence. A down removes upgraded tiers while retaining the free first tier. Select health, mobility, reload and precision support for your task rather than assuming one fountain supplies every effect.', 'Take the free first tier at each fountain, then upgrade useful perks.', { bullets: perks }),
    step('anfang-hearts', 'Use Sacrificial Hearts at the Altar of Covenants for available combat effects or at the Tome of Rituals to strengthen your artifact. Covenants refresh after objectives and become stronger at later rarity; inspect the actual offers. Brain Rot supplies temporary allies, melee bonuses help close fighting, and damage/reload bonuses suit different weapons.', 'Spend Hearts on current Covenant offers or artifact upgrades.', pic('extra-czg-der-anfang-03', 'Altar of Covenants in Stalingrad')),
    step('anfang-artifacts', 'Choose an artifact to fit the objective: Aether Shroud gives a brief escape/repositioning window; Frost Blast slows nearby pressure; Energy Mine damages a prepared enemy cluster; Ring of Fire supports damage while holding an area. Upgrade it with the Tome of Rituals and use the game’s charge indicator instead of a website countdown.', 'Choose escape, crowd control or held-area damage to suit your objective.'),
    step('anfang-crafting', 'Collect the single green salvage type and use the crafting table for armour, equipment and support. Repair armour before another portal or Void session. A Heart, salvage and Essence are different resources; buying a Covenant does not upgrade your weapon.', 'Use salvage for armour/equipment; keep Hearts and Essence separate.'),
  ], { group: 'Key Features' }),
  phase('command-post', 'Open Command Post and Von List’s Office', [
    step('anfang-east', 'Complete the objective portal leading to Panzer Column East. Then complete the Store portal objective to open Command Post. Enter the building and reach Von List’s Office on its upper floor.', 'Open Panzer Column East, then Store, and enter the upper Office.'),
  ], { group: 'Main Quest' }),
  phase('void', 'Return from the Office’s Void portal', [
    step('anfang-void-enter', 'Use the Void portal inside Von List’s Office. Survive three full rounds in its Shi No Numa area. This opens the return portal near Flinger Gate; you may stay for further survival, but take the return portal for the narrative route.', 'Enter Office Void, survive three rounds and return near Flinger Gate.'),
    step('anfang-void-return', 'Watch the return scene and wait until control/dialogue is available in Stalingrad before the next door interaction.', 'Let the return scene finish before following Krafft’s dialogue.'),
  ]),
  phase('kraft', 'Speak through Command Post’s marked door', [
    step('anfang-kraft-door', 'Go back up Command Post’s stairs and interact with the white door bearing the magical symbol. Let Krafft and the Dark Aether entities finish their conversation.', 'Use the marked white Command Post door and let the conversation finish.'),
  ]),
  phase('apartments', 'Activate the Apartments rune and final portal event', [
    step('anfang-apartments-rune', 'Complete the remaining portal objectives needed to open Apartments. On its top floor, find the room with a floor ritual and interact with the rune stone. Wait for the conversation and Krafft’s cue about Command Post.', 'Open Apartments and interact with its upstairs ritual rune.'),
    step('anfang-final-portal', 'Return to the top of the Command Post stairs, turn to the opposite wall and observe the newly formed green portal. Let the final conversation finish. This is Der Anfang’s narrative endpoint; there is no additional boss arena in this short quest.', 'Return to Command Post’s green portal and finish the final dialogue.'),
  ]),
], [
  side('exfil', 'Ordinary objective-map exfil', [
    step('anfang-exfil', 'Once the hub offers Exfil after the early objective progression, interact with the Exfil marker and confirm with your squad. Complete its marked elimination task, then reach/use the escape portal before the displayed timer expires. This ends your match; the short Office story does not automatically exfil you.', 'Use the hub’s Exfil option, clear its enemies and reach its portal before time expires.'),
  ]),
  side('story-records', 'Radios and ancient tablets', [
    step('anfang-records', 'Interact with the radios and rune tablets in the opened hub districts to hear their story segments. You can listen again in the same match; these are in-world recordings rather than Cold War inventory intel. Use the illustrated source’s radio/tablet section for individual sightlines.', 'Listen to the opened districts’ radios and ancient rune tablets.', { links: [{ href: czg('der-anfang'), label: 'Illustrated radio and ancient-tablet reference' }] }),
  ]),
], [czg('der-anfang'), officialSystems, 'https://www.callofduty.com/ca/en/blog/2021/11/call-of-duty-vanguard-zombies-der-anfang-20-tips'], { mode: 'Objective-based', questLabel: 'Office story progression', image: image('extra-czg-der-anfang-01', 'Vanguard undead artwork').src })

const terra = guide('vanguard-terra-maledicta', 'vanguard', 'Terra Maledicta', 'Complete Eastern Desert’s objective portals to free the Decimator Shield, then release the Dark Aether Tome Page. Side dig quests have their own random rewards and the page-door order changes every game.', [
  phase('setup', 'Open the Eastern Desert objective hub', [
    step('terra-setup', 'Use portal objectives to remove barriers into Merchant Road, East Spring, West Spring and Debris Field. Collect free first-tier perk drinks and prepare weapon, armour and artifact upgrades between objectives. This objective-based map opens areas through portals; The Archon uses a different round-based progression.', 'Complete portals to open Merchant Road, both Springs and Debris Field.'),
    step('terra-shovel', 'For optional dig quests, collect a shovel from Debris Field, Market Storage, Outpost Courtyard or Derailment. Check available pickups and dig mounds throughout Eastern Desert; digging can supply the pages, antenna, corrupted heart and red orb.', 'Optional digs: find a shovel at one of the four hub pickup areas.', pic('extra-czg-terra-02', 'Eastern Desert dig mound: interact after collecting a shovel')),
  ], { group: 'Key Features' }),
  phase('decimator', 'Begin freeing the Decimator Shield', [
    step('terra-shield-talk', 'After opening Merchant Road, approach the trapped Decimator Shield to begin its conversation. Open East Spring, then use the rune stone in the Tents area by Demonic Frenzy. Wait for the dialogue to finish and the portal to appear behind the stone.', 'Speak to the Merchant Road shield; use the Tents rune by Demonic Frenzy.', { images: [image('asset-0002', 'Decimator Shield held behind Merchant Road’s barrier'), image('asset-0004', 'Tents rune stone near Demonic Frenzy')] }),
    step('terra-augmentor-enter', 'Enter that new portal and complete the Augmentor task shown in the Dark Aether. Its rune/capture prompts are the objective; returning to the hub enables the crystal stage.', 'Enter the Tents portal and finish the Augmentor objective.', pic('asset-0006', 'Tents prerequisite portal')),
  ], { group: 'Main Quest' }),
  phase('augmentor', 'Destroy the four hub crystals', [
    step('terra-crystals', 'After returning, shoot the four glowing crystals: East Spring’s building wall, West Spring’s building wall, the Temple above spawn, and the Temple wall behind the Altar of Covenants. All four are required, in any order.', 'Destroy the East Spring, West Spring and two Temple crystals.', { images: [image('asset-0007', 'East Spring crystal'), image('asset-0008', 'West Spring crystal'), image('asset-0009', 'Temple crystal above spawn'), image('asset-0010', 'Temple crystal beyond the Covenant altar wall')] }),
  ]),
  phase('sacrifice', 'Finish Sacrifice and collect the shield', [
    step('terra-second-rune', 'Return to the shield for its next conversation. Open West Spring and use the Bazaar rune stone below Diabolical Damage. Wait for the new portal beside it, then enter.', 'Return to the shield; use Bazaar’s rune below Diabolical Damage.', pic('asset-0012', 'Bazaar rune stone below Diabolical Damage')),
    step('terra-sacrifice', 'Complete the portal’s Sacrifice defense objective and return to Eastern Desert. Let the shield dialogue/release finish; collect it once it breaks free and lands. It cannot be Pack-a-Punched.', 'Complete Sacrifice; return and collect the released Decimator Shield.'),
  ]),
  phase('tome-page', 'Enter Debris Field’s Void route', [
    step('terra-debris-portal', 'Open Debris Field and use its rune stone near Venomous Vigor. Wait for the conversation and enter THIS new Void portal; it is separate from the earlier shield portals.', 'Use Debris Field’s Venomous Vigor rune and enter its Void portal.', { images: [image('asset-0015', 'Debris Field rune stone near Venomous Vigor'), image('asset-0016', 'Debris Field Void portal')] }),
  ]),
  phase('arms', 'Break the four Tome Page seals', [
    step('terra-sealing-arms', 'Find the suspended Tome Page and follow each energy beam to its wall arm. Use the Decimator’s charged special slam on all four arms. Wait for the shield’s actual readiness cue between attacks; an uncharged hit does not remove a seal.', 'Follow the Tome Page’s four beams and Decimator-slam each sealing arm.', { bullets: ['Stygian Heights arm.', 'Vercanna’s Home Soil arm.', 'The Shattered Land arm.', 'Isle of Blight arm.'], images: [image('asset-0018', 'Stygian Heights sealing arm'), image('asset-0019', 'Vercanna’s Home Soil sealing arm'), image('asset-0020', 'Shattered Land sealing arm'), image('asset-0021', 'Isle of Blight sealing arm')] }),
  ]),
  phase('ending', 'Take the Tome Page and return', [
    step('terra-tome-reward', 'After all four arms break, collect the released Tome Page and use the portal to its right. Back in Eastern Desert, collect the quest’s points, loot and chests. The Void portal remains usable; ordinary play continues until you choose to leave or the match ends.', 'Collect the released Tome Page and use the portal to its right.', pic('asset-0022', 'Released Tome Page on the ground')),
  ]),
], [
  side('lost-pages', 'Lost Tome page door and Death Machine', [
    step('terra-lost-pages-dig', 'Dig up four Lost Tome pages in Eastern Desert. Take them to the magical barrier on the small Outpost Courtyard building. Its four attachment positions are Top, Bottom, Left and Right.', 'Dig four Lost Tome pages; go to the Outpost Courtyard barrier.', { images: [image('extra-czg-terra-03', 'Lost Tome page found by digging'), image('asset-0025', 'Outpost Courtyard page barrier with Top, Bottom, Left and Right attachment points')] }),
    step('terra-page-order', 'Place pages one at a time. A correct placement stays attached; a wrong placement makes the attached pages disappear and resets the physical attempt. Record accepted prefixes and each failed next choice in the helper, then replay the learned prefix after a reset. The completed door grants a Death Machine.', 'Find the changing Top/Bottom/Left/Right order; correct pages remain attached.'),
    step('terra-ray-variant', 'The modern reference documents an extra Ray Gun reward if the corrupted Ray Gun was first dug up before opening this room. Treat that separate random dig condition as a bonus; ordinary completion of the four-page door guarantees the Death Machine route, not both weapons.', 'Optional: the separate prior Ray Gun dig can add a Ray Gun reward.'),
  ], { tools: ['vanguard-terra-pages'] }),
  side('antenna', 'Radio antenna and random loot', [
    step('terra-antenna-radio', 'Dig up a radio antenna and install it on Merchant Road’s radio beside the armoured vehicle. Defeat the spawned Boom-Schreiers. Continue through the two intermediate radios: Bazaar’s Diabolical Damage room and the radio beside Venomous Vigor. The sources list these two in opposite orders; follow whichever is currently interactable, finish its enemies, then check the other.', 'Fit the antenna at Merchant Road; clear the available Bazaar/Venomous Vigor radios.', { note: 'The observed radio interaction and spawned enemy wave are the progression cues. Do not repeatedly force an inactive radio based on the source-order difference.' }),
    step('terra-antenna-finish', 'After both intermediate stages, use the Market Storage radio by its wooden rug rack. Defeat the Sturmkriegers and open the dropped loot chest for the random reward.', 'Finish Market Storage’s Sturmkriegers and collect the dropped loot chest.'),
  ]),
  side('corrupted-heart', 'Bury the corrupted heart', [
    step('terra-heart', 'Dig up the purple corrupted heart. Carrying it reduces your health; find a highlighted/rune-marked dig spot and use its Bury Corrupted Heart prompt to receive a Sacrificial Heart. Spend that currency at the Covenants or Tome of Rituals.', 'Take the purple heart to a marked burial dig and collect its Sacrificial Heart.'),
  ]),
  side('red-orb', 'Chase the red points orb', [
    step('terra-points-orb', 'When a dig releases a red orb, follow it to its stop, shoot it until it lowers and interact to collect the points. Further red-orb digs can repeat this side route; an ordinary dig’s contents are random.', 'Follow a dug-up red orb, shoot it down and collect its points.'),
  ]),
], [k('terra_maledicta'), czg('terra-maledicta')], { mode: 'Objective-based', questLabel: 'Decimator and Tome Page', image: image('asset-0002', 'Decimator Shield').src })

const shi = guide('vanguard-shi-no-numa', 'vanguard', 'Shi No Numa', 'Use Vanguard’s Wunderwaffe and blood vision to restore the mirror and defeat the Echo. This version’s monolith, weapon build and artifacts differ from World at War and Zombies Chronicles.', [
  phase('setup', 'Open the swamp and weapon routes', [
    step('vshi-open', 'Open Doctor’s Quarters, Dig Site and the Fishing, Comms and Storage huts. Locate Dig Site Pack-a-Punch and plan armour/perk upgrades before the ceremony. Use water paths and the zipline to reach the huts; the free Wunderwaffe’s last tube needs Zaballa’s round-15 arrival.', 'Open the required huts, Doctor’s Quarters and Dig Site.'),
  ], { group: 'Key Features' }),
  phase('wunderwaffe', 'Build or obtain the Wunderwaffe DG-2', [
    step('vshi-barrel', 'Take the weapon barrel from Fishing Hut’s shelf near its door. Put it on the radio tower outside Comms. At the NEXT round’s start, defend the tower after its lightning strike. Retrieve the charged barrel and take the first charged vacuum tube from the radio inside Comms.', 'Fishing Hut barrel → Comms tower defense → barrel and first tube.', { images: [image('asset-0043', 'Fishing Hut weapon-barrel pickup'), image('asset-0044', 'Comms radio tower receiving the barrel'), image('asset-0046', 'Charged first tube at the Comms radio')] }),
    step('vshi-fuse', 'Collect the electrical fuse from Comms’ table. Activate Storage’s trap and let it short out; when its red box opens, fit the fuse and restart it. Feed the repaired trap zombie kills until the tube on the Storage workbench lights, then collect it.', 'Fit the Comms fuse into Storage’s broken trap and charge tube 2 with trap kills.', { images: [image('asset-0047', 'Comms electrical-fuse pickup'), image('asset-0050', 'Opened Storage trap fuse box'), image('asset-0051', 'Second charged vacuum tube')] }),
    step('vshi-zaballa-tube', 'From round 15, lure Zaballa into the Excavation/War Room and stand by its Tesla coil to bait her energy mines into it. After the coil has received enough hits (the reference specifies five), take the charged tube from the adjacent table.', 'Bait Zaballa’s mines onto the Excavation Tesla coil; take tube 3.', { images: [image('asset-0052', 'Tesla coil in Excavation/War Room'), image('asset-0054', 'Third vacuum tube beside the charged coil')] }),
    step('vshi-craft', 'With the barrel and all three charged tubes, craft the Wunderwaffe at Storage’s workbench. A mystery-box Wunderwaffe is an alternative acquisition and satisfies the weapon need without these build tasks. Upgrade it and keep ammunition ready before the ceremony.', 'Craft at Storage, or obtain the Wunderwaffe from the box; prepare it for the ceremony.', pic('asset-0055', 'Storage Wunderwaffe crafting workbench')),
  ]),
  phase('monolith', 'Clear the monolith and read the three papers', [
    step('vshi-vines', 'At Doctor’s Quarters Exterior, lure three Boom-Schreier explosions next to the vine-covered monolith. Clear the vines before interacting with its wheel assembly.', 'Explode three Boom-Schreiers beside the monolith to remove its vines.', pic('asset-0056', 'Vine-covered Doctor’s Quarters monolith')),
    step('vshi-wheels', 'Collect the three wheel PARTS: Dormitory’s table to the right of M1 Garand, Doctor’s Quarters’ room to the right of its Demonic Fountain, and Dig Site’s table in front of Pack-a-Punch. Install them on the cleared monolith. These parts are not the answer papers.', 'Collect Dormitory, Doctor’s Quarters and Dig Site wheel parts; install them.', { images: [image('asset-0057', 'Dormitory cipher-wheel part'), image('asset-0058', 'Doctor’s Quarters cipher-wheel part'), image('asset-0059', 'Dig Site cipher-wheel part')] }),
    step('vshi-papers', 'Read the three variable paper glyphs: Excavation/War Room’s table (shoot away covering books if needed), the Dig Site workbench, and Comms’ table to the left of its connecting doorway. Keep each observation labelled by location.', 'Read the Excavation, Dig Site and Comms paper glyphs.', { images: [image('asset-0060', 'Excavation paper beneath destructible books'), image('asset-0061', 'Dig Site workbench paper'), image('asset-0062', 'Comms table paper')] }),
    step('vshi-translate', 'Use the paired reference plate below, or reveal the complete in-game Doctor’s Quarters translation sheet with a Molotov/thermite. Translate each PAPER glyph to its paired wheel marking. Align the three required markings at the top of the wheel and lock it; red lighting and the appearing ceremony stones confirm acceptance. Do not assume hut visit order supplies ring order.', 'Translate the papers, align their wheel markings at the top and lock the monolith.', pic('asset-0063', 'All fifteen paper-to-wheel pairs; each cell has paper left and wheel marking right')),
  ], { group: 'Main Quest', tools: ['vanguard-shi-no-numa-cipher'] }),
  phase('souls', 'Complete the Wunderwaffe ceremony', [
    step('vshi-ceremony', 'Have a Wunderwaffe ready. All players interact with their glowing stones together to start the lockdown. Kill blue-mist enemies near the shrine with the Wunderwaffe before the event ends. A blue orb and conversation indicate success; if collection fails, start another attempt next round.', 'All players start the stones; Wunderwaffe-kill blue-mist enemies near the shrine.', { images: [image('asset-0065', 'Ceremony start stone'), image('asset-0066', 'Blue-mist enemy requiring a Wunderwaffe kill')] }),
  ]),
  phase('blood', 'Fill and drink the blood fountain', [
    step('vshi-flogger-blood', 'Use Flogger kills in its Courtyard to fill the empty Demonic Fountain. Once filled, drink for the temporary Zombie Blood vision. Zombies still see and attack you during this effect; refill/drink again when you need another clue window.', 'Flogger-kill zombies to fill the fountain; drink for clue vision.', pic('asset-0067', 'Blood fountain in Flogger Courtyard')),
  ]),
  phase('mirror-parts', 'Find both mirror fragments in vision', [
    step('vshi-map-x', 'While in vision, read War Room’s map for the red X. Go to its indicated hut, shoot the fragment in the ceiling to drop it and collect it. The X varies; use the map actually shown, not a fixed hut choice.', 'In blood vision, read War Room’s X and shoot down that hut’s mirror fragment.', { images: [image('asset-0068', 'War Room map carrying the current red X'), image('asset-0069', 'Elevated mirror fragment to shoot down')] }),
    step('vshi-red-orb', 'Find the red orb in the main building during vision and approach to start it moving. Its start identifies the eventual fragment location below; it can finish without a continuous escort. If vision expires, drink again and search its endpoint.', 'Activate the red orb and recover the fragment at its endpoint.', { bullets: ['Upper floor beside SVT-50 → trees left of Doctor’s Quarters.', 'Lower floor by the box → Fishing Hut’s back room.', 'Lower floor near the Storage door → central Dig Site by the ammo crate.'], images: [image('asset-0070', 'Red orb visible in blood vision'), image('asset-0072', 'Doctor’s Quarters endpoint'), image('asset-0074', 'Fishing Hut endpoint'), image('asset-0076', 'Dig Site endpoint')] }),
  ]),
  phase('orbs', 'Restore the mirror and return blue orbs', [
    step('vshi-place-mirror', 'Install both fragments on Dig Site’s central pedestal. Interact with your blue orb’s stone; its position identifies the hut-side orb route. Find the orb and shoot its successive positions until it returns to Dig Site. The route uses three shots; an expired attempt respawns at its start stone for another try.', 'Place both mirror pieces; activate and follow each blue orb’s three-shot route.', { bullets: ['Stone nearest Combat Shotgun → Fishing Hut Exterior tree left of the Tome.', 'Stone nearest Pack-a-Punch → Comms back-room ceiling.', 'Stone west of the mirror → bushes left of Doctor’s Quarters.', 'Stone north of the mirror → Storage window right of the ammo crate.'], images: [image('asset-0078', 'Central Dig Site mirror pedestal'), image('asset-0081', 'Fishing Hut Exterior blue orb'), image('asset-0083', 'Comms back-room blue orb'), image('asset-0085', 'Doctor’s Quarters blue orb'), image('asset-0087', 'Storage window blue orb')] }),
  ]),
  phase('echo', 'Defeat the Echo’s three masks', [
    step('vshi-enter-echo', 'Prepare upgrades, armour, Wunderwaffe ammo and your damage weapon. All players interact with the returned blue orbs to summon the Echo, then allow its introductory dialogue to finish.', 'Prepare, then all players use the returned blue orbs to summon Echo.'),
    step('vshi-echo-loop', 'Charge the mirror by Wunderwaffe-killing the required marked enemies near it. When the large blue dome forms, bring the Echo INSIDE it and damage its mask before it recovers. Insufficient damage resets that mask’s damage window; recharge and repeat.', 'Wunderwaffe-kill the marked enemies; damage Echo’s mask only inside the blue dome.', { bullets: ['Mask 1 collection: blue-mist zombies.', 'Mask 2 collection: Boom-Schreiers.', 'Mask 3 collection: Sturmkriegers.'], note: 'Choose an artifact for the damage window and survival. A source’s high-tier Energy Mine strategy is an option, not a guaranteed one-hit promise or a game prerequisite.' }),
  ]),
  phase('mirror', 'Collect the restored relic', [
    step('vshi-mirror-finish', 'After all three masks are destroyed, let the concluding story events finish and collect the repaired mirror relic and rewards. The first weakened mask is not quest completion.', 'Destroy all three masks and collect the repaired mirror relic.'),
  ]),
], [
  side('rampage', 'Rampage Inducer', [
    step('vshi-rampage', 'From the main building, quickly shoot five outside lanterns in order: left of SVT-50, right of SVT-50, behind the stairs, the right side of the window left of G-43, then the left side of that window. Successful hits flash orange; a sound and tablet indicate the inducer is available.', 'Shoot the five spawn lanterns in order; use the appeared inducer tablet.'),
  ]),
  side('bunny', 'Blood-vision Mister Peeks reward', [
    step('vshi-bunny', 'First unlock the blood-fountain vision in the main quest. While in vision, collect three bunny parts: under the zipline platform; in water outside Fishing Hut; and at the former box position WHILE the box is moving. All three produce bonus points and a Fire Sale. These items are not visible as a fresh-spawn route.', 'In blood vision, collect zipline, Fishing Hut water and moving-box bunny parts.'),
  ]),
  side('samantha', 'Samantha’s Sorrow and Max Ammo', [
    step('vshi-samantha', 'Shoot four silver plates on Fishing Hut’s walls, then interact with the Samantha doll on the side-room floor. Shoot the dolls appearing one at a time along the bridge outside. Return to the starting doll and interact again for the song and Max Ammo.', 'Shoot four Fishing Hut plates; start the doll, shoot its bridge sequence and return.'),
  ]),
  side('telephone-music', 'The One instrumental', [
    step('vshi-phone', 'Interact with the black telephone inside Comms to start The One’s instrumental track.', 'Use the Comms telephone for the instrumental song.'),
  ]),
], [k('shi_no_numa_reborn'), czg('shi-no-numa')], { mode: 'Round-based', aliases: ['Shi No Numa Reborn', 'SNN'], questLabel: 'Mirror and Echo', image: image('asset-0056', 'Vanguard monolith').src })

const archon = guide('vanguard-the-archon', 'vanguard', 'The Archon', 'Restore Pack-a-Punch and complete all three trials before confronting Kortifex. Mindfulness, Resilience and Sacrifice can be completed in any order; each has different preparation and failure rules.', [
  phase('setup', 'Assemble Temple Pack-a-Punch', [
    step('archon-pap-parts', 'Collect the two ghostly Pack-a-Punch parts: one on a rail cart in Derailment and one on the plane wing in Spike. Return to the ghostly machine at Temple and install them.', 'Collect Derailment rail-cart and Spike plane-wing parts; install at Temple.'),
    step('archon-pap-souls', 'The surrounding ghost zombies become active. Kill them near the machine to charge it until Pack-a-Punch becomes solid and usable. Prepare upgrades and armour; this round-based map does not use Terra’s objective portals to open the same setting.', 'Charge Temple Pack-a-Punch with its spawned ghost-zombie kills.'),
  ], { group: 'Key Features' }),
  phase('relic', 'Place the relic and survive the introduction', [
    step('archon-relic-place', 'Place the relic on the stone in front of Temple Pack-a-Punch. Watch the scene, then interact with the new nearby Dark Aether portal.', 'Place the Temple relic and enter its new Dark Aether portal.', { images: [image('asset-0105', 'Relic stone in front of Temple Pack-a-Punch'), image('asset-0106', 'Introductory Dark Aether portal')] }),
    step('archon-intro-return', 'Survive the introductory Dark Aether event. Its scripted downing/return sends the squad back to Eastern Desert and enables the trial preparation; it is not an instruction to deliberately fail an ordinary round.', 'Survive the Dark Aether introduction through its scripted return.'),
  ], { group: 'Main Quest' }),
  phase('shovel', 'Collect a shovel and choose a trial', [
    step('archon-shovel', 'Take a shovel from an available pickup at Derailment, Bazaar, Debris Field or Tents. All three following trials are required, and their order is your choice. Prepare a spare Pack-a-Punched weapon for Sacrifice before surrendering your only useful gun.', 'Get a shovel; complete all three trials in your preferred order.', { images: [image('asset-0107', 'Derailment shovel'), image('asset-0108', 'Bazaar shovel'), image('asset-0109', 'Debris Field shovel'), image('asset-0110', 'Tents shovel')] }),
  ]),
  phase('mindfulness', 'Trial of Mindfulness', [
    step('archon-mindfulness-orb', 'Dig around the Merchant Road obelisk until you find the red orb. Activate it and record the wall’s displayed symbols and their matching ground-rune landmarks before moving. Step on the matching runes in the displayed order.', 'Dig Merchant Road’s red orb; record and traverse its rune order.', { images: [image('asset-0111', 'Merchant Road Mindfulness obelisk'), image('asset-0112', 'Mindfulness red orb'), image('asset-0113', 'Displayed Mindfulness symbols')] }),
    step('archon-preparation-rounds', 'Finish the resulting timed challenge. Repeat the preparation for three sequences: 3 symbols, then 4, then 5, each followed by its challenge. Keep earlier observations separate from the new display; no fixed glyph count or map mapping is inferred by the notebook.', 'Complete the 3-, 4- and 5-symbol preparations and their challenges.'),
    step('archon-no-kill-capture', 'After all three preparations, interact with the obelisk for the formal trial. Capture its runes WITHOUT killing zombies. Evade or control pressure while avoiding accidental damage/kills from your equipment. A failed capture trial can be retried next round; the reward drops confirm completion.', 'Start the formal trial and capture its runes without zombie kills.'),
  ], { tools: ['vanguard-archon-runes'], note: 'Use short names for shapes you personally observed. The source-linked preparation chart’s original pixels were unavailable; this helper makes no invented automatic glyph-to-floor assignments.' }),
  phase('resilience', 'Trial of Resilience and Decimator Shield', [
    step('archon-resilience-orb', 'At Debris Field, shoot the three external Dark Aether crystal candidates until one releases the red orb. Follow it to the wall near the Decimator Shield.', 'Shoot Debris Field’s external crystals until the Resilience orb appears.', { images: [image('asset-0115', 'First external crystal candidate'), image('asset-0116', 'Second external crystal candidate'), image('asset-0117', 'Third external crystal candidate')] }),
    step('archon-cursed-items', 'Return three cursed objects to that orb: Officer’s Hat at Tents, Skull on Bazaar’s second floor and the dug-up Femur in Derailment. Carry each separately and complete the challenge attached to its pickup. Sprint is disabled while carrying; use the in-game objective cue and return without failing.', 'Return the Tents hat, upper Bazaar skull and dug-up Derailment femur.', { images: [image('asset-0118', 'Cursed Officer’s Hat in Tents'), image('asset-0119', 'Cursed Skull upstairs in Bazaar'), image('asset-0120', 'Cursed Femur dug up at Derailment')] }),
    step('archon-shield-pickup', 'After all three deliveries, collect the released Decimator Shield. Its special slam is required for the shielded Syphoncores; the shield cannot be Pack-a-Punched.', 'Collect the freed Decimator Shield after all three cursed deliveries.'),
    step('archon-resilience-trial', 'Start the Resilience obelisk. Use charged Decimator slams to destroy the Syphoncores near the shield, Venomous Vigor and Fiendish Fortitude. Collect Demon Blood from each destroyed core and deliver it to the empty Demonic Fountain. Wait for the shield’s readiness cue between slams. Full reward drops indicate the fountain/trial is finished.', 'Destroy the three Syphoncores and deliver their Demon Blood to the fountain.', { images: [image('asset-0124', 'Syphoncore near the shield'), image('asset-0125', 'Syphoncore near Venomous Vigor'), image('asset-0126', 'Syphoncore near Fiendish Fortitude'), image('asset-0123', 'Empty Demonic Fountain receiving Demon Blood')] }),
  ]),
  phase('sacrifice', 'Trial of Sacrifice and Ring of Fire', [
    step('archon-torches', 'Get three Molotovs from Merchant Road West or crafting. At Derailment, light the three torches in quick succession so all remain lit together: the entry boxcar, the right side of Derailment and behind that second torch. The red orb appears near the third.', 'Light all three Derailment torches together with Molotovs.', { images: [image('asset-0128', 'Derailment boxcar torch'), image('asset-0129', 'Right-side Derailment torch'), image('asset-0130', 'Torch behind the second position')] }),
    step('archon-sacrifice-weapon', 'Offer a Pack-a-Punched weapon to the orb. It is permanently surrendered and your armour is removed; prepare a spare weapon and an escape plan first. Defeat the spawned Uberkrieger so the orb moves to the obelisk.', 'Surrender a spare packed weapon, survive armour loss and defeat the Uberkrieger.', { ...pic('asset-0131', 'Sacrifice orb requesting a packed weapon'), note: 'Permanent loss: the surrendered weapon is not returned after the trial.' }),
    step('archon-ring-of-fire', 'Use the nearby artifact-changing stone if needed to equip Ring of Fire IN THE GAME. Then start the Sacrifice obelisk. Five kills near the central obelisk can create Full Power; use Ring of Fire to make the required kills around each surrounding obelisk (the reference specifies six per obelisk). A beam joins each charged obelisk to the centre.', 'Equip Ring of Fire; charge each trial obelisk with nearby kills while inside the Ring.', { images: [image('asset-0133', 'Stone that changes the artifact to Ring of Fire'), image('asset-0134', 'Beam from a charged trial obelisk')] }),
    step('archon-sacrifice-complete', 'Charge every surrounding obelisk and collect the completion rewards. The website’s artifact note does not equip Ring of Fire and ordinary kills made outside its area do not satisfy this trial condition.', 'Finish every charged obelisk and confirm the reward drops.'),
  ]),
  phase('departure', 'Prepare for the final portal', [
    step('archon-final-ready', 'Confirm Mindfulness, Resilience AND Sacrifice are complete. Refill ammo, repair armour and upgrade your damage weapon. Keep the Decimator for defense, then use the portal near Temple Pack-a-Punch when the squad is ready.', 'After all three trials, prepare the squad and enter the Temple boss portal.', { note: 'Point of no return: entering commits you to Kortifex. Finish optional map tasks first.' }),
  ]),
  phase('kortifex', 'Defeat Kortifex’s three eyes', [
    step('archon-eye-one', 'In the first area, damage Kortifex’s upper exposed eye while evading his attacks and the enemy adds. Destroying that eye moves the fight to the next arena.', 'Destroy the first upper eye and move to the next arena.'),
    step('archon-convert-shards', 'In the later arenas, shoot ground Dark Aether crystals to obtain RED shards. Throw a red shard into a PURPLE pod and wait for its conversion cue; retrieve the BLUE corrupted shard. A normal red shard is not the shield-breaking projectile.', 'Ground crystal → red shard → purple pod → wait → blue shard.', { images: [image('asset-0136', 'Red shard from a broken ground crystal'), image('asset-0137', 'Purple conversion pod'), image('asset-0138', 'Converted blue corrupted shard')] }),
    step('archon-sky-pillars', 'Throw the blue shard at a floating sky pillar. Its impact on the Construct disables Kortifex’s bubble so you can damage the next eye. Repeat conversions/pillar strikes whenever protection returns. Destroying the second eye starts the final arena.', 'Use blue shards on sky pillars to expose and destroy the next eye.', pic('asset-0139', 'Floating sky pillar targeted with a converted blue shard')),
    step('archon-last-eye', 'Repeat the shard/pod/pillar cycle for the final eye. In this phase Kortifex can heal: interrupt that healing by sending more sky pillars into him. Destroy the last eye, then let the closing conversation/rewards complete.', 'Repeat for the final eye; strike pillars to interrupt healing.'),
    step('archon-ending', 'Collect the concluding rewards: the There Archon Be Only One calling card, Wunderwaffe, Sacrificial Hearts and the fight’s held-perk tier reward. Completion follows the final eye and dialogue, not the first shield break.', 'After the final eye, receive the ending and quest rewards.'),
  ]),
], [
  side('rampage', 'Rampage Inducer skull order', [
    step('archon-rampage', 'Shoot five stag skulls in this order from the spawn-facing landmarks: left of spawn; directly ahead; right above SVT; the Temple middle section left of that third skull; and above Pack-a-Punch. Correct shots turn their eyes red; the completion sound creates the inducer tablet.', 'Shoot left → ahead → right/SVT → middle Temple → above PaP skulls.'),
  ]),
  side('bunny', 'Mister Peeks free Ray Gun', [
    step('archon-bunny', 'First activate the Rampage Inducer and get a shovel. A periodic scream (the references describe every five rounds) signals a bunny part at a dark dig mound. Search and dig the signaled parts; collecting all three awards a Ray Gun and bonus points. The sound is your search cue, not a guaranteed drop from every mound.', 'After activating Rampage, dig three scream-signaled bunny parts for a Ray Gun.'),
  ]),
  side('music', 'Vanishing Shore music', [
    step('archon-song', 'Go upstairs in Radio Outpost, left of Temple, and interact three times with the guitar-like instrument leaning there. This starts Vanishing Shore.', 'Interact three times with Radio Outpost’s upstairs instrument.'),
  ]),
], [k('the_archon'), czg('the-archon'), 'https://www.charlieintel.com/call-of-duty-vanguard/how-to-complete-vanguard-zombies-the-archon-easter-egg-main-quest-guide-194570/', 'https://www.youtube.com/watch?v=JA7Ihp-GtxU'], { mode: 'Round-based', questLabel: 'Trials and Kortifex', image: image('extra-czg-archon-01', 'Kortifex artwork').src })

export const vanguardGuides = [derAnfang, terra, shi, archon]
