import { field as f, tool as t, image, numbers } from './remaining-common.mjs'
import { ww2References as refs } from './ww2-references.mjs'
const source = slug => `https://mmmrkennedy.com/games/WW2/${slug}/${slug}_guide`
const group = (id, title, fields, help) => ({ id, title, fields, ...(help ? { help } : {}) })
const groups = (prefix, n, fields) => Array.from({ length: n }, (_, index) => group(`${prefix}-${index}`, `${prefix} ${index + 1}`, fields(index)))
const reference = (id, alt) => image(id, alt)
const text = (id, label, length = 40) => f(id, label, null, { maxLength: length })
const check = (id, label) => f(id, label, null, { type: 'check' })
const options = (id, label, values, optionLabels) => f(id, label, values, { ...(optionLabels ? { optionLabels } : {}) })
const digits = numbers(10)
const arrowLabels = { '0': 'Up / back ↑', '1': 'Right →', '2': 'Down / facing you ↓', '3': 'Left ←' }
const hammerLabels = { '0': 'Front / toward bowl ↓', '1': 'Right →', '2': 'Back ↑', '3': 'Left ←' }
const clownLocations = ['Church drop-pod door', 'Plaza BAR hole', 'Plaza Double Tap', 'Cabaret backstage', 'Museum chandelier', 'Main Street Stamin-Up hole', 'Apartments elevator', 'Wunderbuss room', 'Underbelly shotgun', 'Destroyed Building armour']

export const ww2Tools = [
  t('ww2-final-reich-grid', 'ww2-the-final-reich', 'Power-grid route', 'Read the four columns left to right; box locations stay fixed, colours come from your match.', Array.from({ length: 4 }, (_, index) => f(`grid-${index}`, `Column ${index + 1}`, ['Red', 'Green', 'Blue'])), {
    kind: 'lookup', guidePhase: 'right-hand', reference: [reference('asset-0222', 'Grid columns to read left to right'), ...['asset-0223', 'asset-0224', 'asset-0225', 'asset-0226'].map((id, index) => reference(id, `Power box ${index + 1} in route order`))], source: source('the_final_reich'),
  }),
  t('ww2-final-reich-voice', 'ww2-the-final-reich', 'Bird numerals & second voices', 'Match each painting to the actual bird on the machine. Green-flash groups belong to the separate hardcore record sequence.', [f('stage', 'Voice stage', ['paintings', 'flashes'], { optionLabels: { paintings: 'Painting numerals', flashes: 'Gramophone green flashes' } }), ...Array.from({ length: 4 }, (_, index) => f(`bird-${index}`, `Pictured bird ${index + 1}: painting numeral`, numbers(5, 1))), ...Array.from({ length: 4 }, (_, index) => f(`flash-${index}`, `Green-flash group ${index + 1}`, numbers(12, 1)))], {
    guidePhase: 'voice-of-god', groups: [group('stage', 'Stage', ['stage']), group('paintings', 'Painting observations by matching bird', numbers(4).map(index => `bird-${index}`), 'Use the numbered bird strip to identify the same symbol on the machine. Painting visit order is irrelevant.'), group('flashes', 'Hardcore second voices', numbers(4).map(index => `flash-${index}`), 'The strip numbers identify the order for the gramophone groups. Preserve painting values while recording a new flash attempt.')], resetScopes: [{ label: 'New flash attempt', fields: numbers(4).map(index => `flash-${index}`) }], reference: [reference('asset-0268', 'Numbered machine birds for second-voice order'), reference('asset-0237', 'Voice of God machine dials'), reference('asset-0267', 'Gramophone light: green flashes and red repeat cue')], source: source('the_final_reich'),
  }),
  t('ww2-darkest-artillery', 'ww2-the-darkest-shore', 'Cannon coordinates & destroyer chart', 'Keep the six fuse characters independent from the moving-ship aiming examples.', [f('stage', 'Cannon task', ['fuse', 'ships']), ...Array.from({ length: 6 }, (_, index) => f(`dial-${index}`, `Physical dial position ${index + 1}`, [0, 3].includes(index) ? ['+', '-'] : digits)), f('ship', 'Pictured ship example', numbers(11, 1), { optionLabels: { '1': 'Far upper left · +07 / −50', '2': 'Far upper right · +08 / −00', '3': 'Upper left by rock · +05 / −30', '4': 'Upper right by rock · +06 / +20', '5': 'Middle far left · +03 / −50', '6': 'Middle left above rock · +03 / −30', '7': 'Middle far right · +04 / +25', '8': 'Centre left · −00 / −15', '9': 'Centre right · −01 / −00', '10': 'Near lower left · −02 / −30', '11': 'Near lower right · −02 / +40' } }), check('ship-1-done', 'First destroyer sunk'), check('ship-2-done', 'Second destroyer sunk')], {
    guidePhase: 'artillery', groups: [group('stage', 'Task', ['stage']), group('fuse', 'R.I.P. Saw fuse: physical dial positions', numbers(6).map(index => `dial-${index}`)), group('ships', 'Destroyers: match the aiming photograph', ['ship', 'ship-1-done', 'ship-2-done'])], reference: [reference('asset-0403', 'NinjaNationGaming destroyer aiming sheet: eleven ship examples'), ...['asset-0328', 'asset-0329', 'asset-0330', 'asset-0332', 'asset-0333', 'asset-0334'].map((id, index) => reference(id, `Coordinate machine candidate ${index + 1}; read its actual dial position`)), reference('asset-0335', 'Left cannon panel: elevation'), reference('asset-0336', 'Right cannon panel: angle')], source: source('the_darkest_shore'),
  }),
  t('ww2-shadowed-radio', 'ww2-the-shadowed-throne', 'Church radio-frequency lookup', 'Choose the pinned region and the code printed on the Main Street radio.', [f('region', 'Pinned region', refs.shadowedRadio.regions.map(row => row.name)), f('series', 'Radio letters', refs.shadowedRadio.series), f('model', 'Radio number', refs.shadowedRadio.modelNumbers)], { kind: 'lookup', guidePhase: 'wunderbuss', reference: [reference('asset-0438', 'Full church radio-frequency chart'), reference('asset-0437', 'Find the pinned region on the church map'), reference('asset-0435', 'Radio code printed above the Main Street radio')], source: source('the_shadowed_throne') }),
  t('ww2-shadowed-statues', 'ww2-the-shadowed-throne', 'Raven statue wall solver', 'Walls are counterclockwise from the three-statue wall left of the stairs. Down means facing you. Record observations before shooting.', [f('wall', 'Wall number', numbers(4, 1)), ...Array.from({ length: 4 }, (_, index) => options(`statue-${index}`, `Statue ${String.fromCharCode(65 + index)}: facing`, numbers(4), arrowLabels))], { kind: 'solver', guidePhase: 'raven-statues', layout: { type: 'row', fields: numbers(4).map(index => `statue-${index}`), note: 'Wall 1 has A–C only; D is ignored.' }, resetScopes: [{ label: 'New wall observations', fields: numbers(4).map(index => `statue-${index}`) }], reference: [reference('asset-0492', 'Wall 1 left of the stairs, with three statues'), reference('asset-0493', 'Raven pickup after completing a wall')], source: source('the_shadowed_throne') }),
  t('ww2-shadowed-safe', 'ww2-the-shadowed-throne', 'Clown counts → safe directions', 'Count each active clown until it stops accepting kills, then confirm. Store activation order even if a location repeats.', Array.from({ length: 4 }, (_, index) => [f(`location-${index}`, `Clown ${index + 1} location`, clownLocations), f(`count-${index}`, `Clown ${index + 1} kills`, numbers(9, 1)), check(`confirmed-${index}`, `Count ${index + 1} confirmed`)]).flat(), { kind: 'recorder', guidePhase: 'dancers-dagger', groups: groups('Clown', 4, index => [`location-${index}`, `count-${index}`, `confirmed-${index}`]), reference: [reference('asset-0462', 'Projector map shows the currently active clown'), reference('asset-0473', 'Apartments safe: reset clockwise and alternate directions')], source: source('the_shadowed_throne') }),
  t('ww2-shadowed-axe', 'ww2-the-shadowed-throne', 'Axe Morse decoder & map', 'Short beep = dot, long beep = dash. Separate the two five-signal digits with a space or /. Keep the etched tuning frequencies separate.', [text('message', 'Two digit Morse groups', 30)], { kind: 'solver', guidePhase: 'nazi-axe', reference: [reference('asset-0484', 'Church axe map clue positions'), reference('asset-0483', 'Use the magnifying glass on this church map'), reference('asset-0482', 'Magnifying glass in Cabaret')], source: source('the_shadowed_throne') }),
  t('ww2-frozen-hammer', 'ww2-the-frozen-dawn', 'Base Hammer pillar solver', 'Four separate pillars; A is top and D is bottom. Front points toward the bowl where the Hammer appeared. The upgrade apparatus has different rules.', [f('pillar', 'Observed pillar', numbers(4, 1)), ...numbers(4, 1).flatMap(pillar => numbers(4).map(index => options(`pillar-${pillar}-${index}`, `Pillar ${pillar}, block ${String.fromCharCode(65 + index)}`, numbers(4), hammerLabels)))], { kind: 'solver', guidePhase: 'hammer', groups: [group('pillar', 'Choose the pillar', ['pillar']), ...numbers(4, 1).map(pillar => group(`pillar-${pillar}`, `Pillar ${pillar}: top to bottom`, numbers(4).map(index => `pillar-${pillar}-${index}`)))], layout: { type: 'column', selected: 'pillar', prefix: 'pillar-' }, reference: [reference('asset-0699', 'Base Hammer pillar orientation and shooting reference'), reference('asset-0698', 'Four pillars surrounding the Overlook bowl')], source: source('the_frozen_dawn') }),
  t('ww2-frozen-shield', 'ww2-the-frozen-dawn', 'Shield pool pattern memory', 'Record first, second and third activation, including which pool produced each of the seven pictured patterns.', Array.from({ length: 3 }, (_, index) => [f(`pool-${index}`, `Activated pool ${index + 1}`, ['Ice Caves', 'Morgue', 'Overlook']), f(`pattern-${index}`, `Pattern ${index + 1}`, numbers(7, 1)), check(`confirmed-${index}`, `Activation ${index + 1} confirmed`)]).flat(), { guidePhase: 'shield-upgrade', groups: groups('Activation', 3, index => [`pool-${index}`, `pattern-${index}`, `confirmed-${index}`]), reference: [reference('asset-0719', 'Seven numbered Blood Pool patterns'), reference('asset-0714', 'Red smoke identifies the next Shield pool'), reference('asset-0717', 'Blood Altar radio pattern control')], source: source('the_frozen_dawn') }),
  t('ww2-frozen-orrery', 'ww2-the-frozen-dawn', 'Orrery target memory', 'Record targets as seen on the Cypher Room wall, using the top-of-reference Schnellblitz landmark for orientation. This records positions; it cannot time moving orbs.', [check('perspective', 'I matched the wall perspective to the landmark chart'), ...['red', 'green', 'purple'].map(colour => f(colour, `${colour[0].toUpperCase() + colour.slice(1)} orb target`, ['12 o’clock', '1:30', '3 o’clock', '4:30', '6 o’clock', '7:30', '9 o’clock', '10:30']))], { guidePhase: 'flail', reference: [reference('asset-0736', 'Cypher Room wall compared with Orrery landmarks'), reference('asset-0735', 'Observe your match’s orb positions on the wall'), reference('asset-0734', 'Moving Orrery and its stop controls')], source: source('the_frozen_dawn') }),
  t('ww2-tortured-runes', 'ww2-beneath-the-ice', 'Three-stage rune code memory', 'Keep fresh sequences after each inserted rune. Describe the observed shapes or enter numbered wall positions. Old clues remain visible.', [f('stage', 'Current rune-wall stage', ['1', '2', '3'], { optionLabels: { '1': 'Initial wall (wave 2)', '2': 'After flare rune (wave 4)', '3': 'After pool rune (wave 5)' } }), ...numbers(3, 1).flatMap(stage => [...numbers(8).map(index => text(`stage-${stage}-${index}`, `Stage ${stage}, rune ${index + 1}`, 30)), text(`stage-${stage}-location`, `Stage ${stage}, clue landmark`, 80), check(`stage-${stage}-confirmed`, `Stage ${stage}: complete sequence confirmed`)])], { guidePhase: 'rune-wall', groups: [group('stage', 'Stage', ['stage']), ...numbers(3, 1).map(stage => group(`stage-${stage}`, `Stage ${stage}: left-to-right observation`, [...numbers(8).map(index => `stage-${stage}-${index}`), `stage-${stage}-location`, `stage-${stage}-confirmed`]))], resetScopes: numbers(3, 1).map(stage => ({ label: `Clear stage ${stage} only`, fields: [...numbers(8).map(index => `stage-${stage}-${index}`), `stage-${stage}-location`, `stage-${stage}-confirmed`] })), reference: [reference('asset-0614', 'Rune wall: retain the physical position and shape order'), ...numbers(14, 600).map(number => reference(`asset-${String(number).padStart(4, '0')}`, `Rune clue search location ${number - 599}`))], source: source('the_tortured_path') }),
  t('ww2-shadowed-hangman', 'ww2-the-shadowed-throne', 'Cabaret Hangman candidates', 'Filter all seven reviewed reward words; unknown positions stay _ and confirmed wrong letters eliminate words.', [text('mask', 'Sign pattern (e.g. R_A_ER)', 15), text('rejected', 'Confirmed wrong letters', 26)], { kind: 'solver', guidePhase: 'hangman', source: source('the_shadowed_throne') }),
]

// Keep the selected task's controls in view while preserving the other stages' observations.
for (const definition of ww2Tools) {
  if (definition.id === 'ww2-final-reich-voice') {
    definition.groups.find(group => group.id === 'paintings').showWhen = { field: 'stage', value: 'paintings' }
    definition.groups.find(group => group.id === 'flashes').showWhen = { field: 'stage', value: 'flashes' }
  }
  if (definition.id === 'ww2-darkest-artillery') {
    for (const id of ['fuse', 'ships']) definition.groups.find(group => group.id === id).showWhen = { field: 'stage', value: id }
  }
  if (definition.id === 'ww2-frozen-hammer') {
    for (const pillar of numbers(4, 1)) definition.groups.find(group => group.id === `pillar-${pillar}`).showWhen = { field: 'pillar', value: pillar }
  }
  if (definition.id === 'ww2-tortured-runes') {
    for (const stage of numbers(3, 1)) definition.groups.find(group => group.id === `stage-${stage}`).showWhen = { field: 'stage', value: stage }
  }
  if (definition.id === 'ww2-shadowed-axe') definition.layout = { type: 'morse', field: 'message' }
  if (definition.id === 'ww2-shadowed-statues') {
    definition.groups = [group('wall', 'Which wall?', ['wall']), group('statues', 'Facing directions: left to right', ['statue-0', 'statue-1', 'statue-2'], 'Down means facing you. Wall 1 has three statues; walls 2–4 add D.'), ...numbers(3, 2).map(wall => ({ ...group(`statue-d-${wall}`, 'Fourth statue', ['statue-3']), showWhen: { field: 'wall', value: wall } }))]
    definition.invalidates = [{ field: 'wall', fields: ['statue-0', 'statue-1', 'statue-2', 'statue-3'] }]
    definition.spatial = { fields: ['statue-0', 'statue-1', 'statue-2'] }
  }
  if (['ww2-shadowed-safe', 'ww2-frozen-shield'].includes(definition.id)) {
    const slots = definition.id === 'ww2-shadowed-safe' ? 4 : 3
    const dependencies = definition.id === 'ww2-shadowed-safe' ? ['count', 'location'] : ['pool', 'pattern']
    definition.invalidates = Array.from({ length: slots }, (_, index) => dependencies.map(prefix => ({ field: `${prefix}-${index}`, fields: [`confirmed-${index}`] }))).flat()
  }
  if (definition.id === 'ww2-tortured-runes') {
    definition.invalidates = numbers(3, 1).flatMap(stage => numbers(8).map(index => ({ field: `stage-${stage}-${index}`, fields: [`stage-${stage}-confirmed`] })))
  }
}
