<script setup lang="ts">
import {straussReadings,straussRoute,aetherellaFigures,aetherellaProgress} from '~/utils/bo6Launch.mjs'
const props=defineProps<{tool:string}>()
const {state,change,undo,reset,canUndo,saveError}=usePuzzleState(props.tool)
const isStrauss=computed(()=>props.tool==='bo6-liberty-strauss')
const projectors=computed(()=>straussRoute(state.value))
const progress=computed(()=>aetherellaProgress(state.value))
const confirmReset=ref(false)
function update(key:string,value:any){change({...state.value,[key]:value})}
function read(key:string,value:string){change({...state.value,[key]:value,[`${key}-done`]:false})}
</script>
<template>
 <div class="puzzle bo6-liberty">
  <template v-if="isStrauss">
   <p>Take the Strauss Counter after returning your first charged canister. Stand beside each projector, hold the tactical button to read the counter, then choose its reading here. The target below is the <strong>projector’s light</strong>.</p>
   <section v-for="projector in projectors" :key="projector.id" class="projector"><h3>{{projector.name}}</h3><p>{{projector.location}}</p><GuideIllustrations :images="[{src:projector.image,alt:projector.name+' projector location'}]" /><div class="reading-buttons" :aria-label="projector.name+' counter reading'" role="group"><button v-for="reading in straussReadings" :key="reading.value" :aria-pressed="state[projector.id]===reading.value" @click="read(projector.id,reading.value)"><span :class="['swatch',reading.value]" aria-hidden="true"></span>{{reading.name}}</button></div><div class="setting" role="status" aria-live="polite"><template v-if="projector.target"><span>Set this projector to</span><strong><span :class="['swatch',projector.target]" aria-hidden="true"></span>{{projector.target.toUpperCase()}}</strong><label><input type="checkbox" :checked="projector.done" @change="update(`${projector.id}-done`,($event.target as HTMLInputElement).checked)" />Confirmed in game</label></template><p v-else>Choose the counter reading to see the target.</p></div></section>
   <p class="result" role="status">{{projectors.filter(p=>p.done).length}} / 3 projectors confirmed. {{projectors.every(p=>p.done)?'Wait for all three beams to meet at Pump & Pay, then collect the second canister.':'Red / High → Green. Green / Low → Red. Yellow / Medium stays Yellow.'}}</p><p class="muted">Projector interactions cycle Green → Yellow → Red. Changing a reading clears that projector’s confirmation.</p>
  </template>
  <template v-else>
   <p>Use the Jet Gun’s <strong>suction</strong> on all nine figures. Select “Collected” only after the figure disappears into the gun. Collecting the ninth transforms you immediately, so leave a convenient final figure until you are ready.</p><p class="result" role="status" aria-live="polite">{{progress.collected}} / 9 collected · {{progress.complete?'Transformation triggered. This helper does not control its duration.':`${progress.remaining} remaining`}}</p>
   <div class="figure-grid"><section v-for="figure in aetherellaFigures" :key="figure.id" :class="{collected:state[figure.id]}"><h3>{{figure.name}}</h3><GuideIllustrations :images="[{src:figure.image,alt:figure.location}]" /><p>{{figure.location}}</p><label><input type="checkbox" :checked="state[figure.id]" @change="update(figure.id,($event.target as HTMLInputElement).checked)" />Collected</label></section></div><p class="muted">Photographed sightlines: <a href="https://www.reddit.com/r/CODZombies/wiki/liberty-falls/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide</a>. Select any photo to enlarge it.</p>
  </template>
  <div class="actions"><button :disabled="!canUndo" @click="undo">Undo last change</button><button @click="confirmReset=!confirmReset">Reset helper</button></div><div v-if="confirmReset" class="result"><p>Clear this helper’s saved observations?</p><div class="actions"><button @click="reset();confirmReset=false">Clear observations</button><button @click="confirmReset=false">Keep observations</button></div></div><p v-if="saveError" role="alert">Your browser could not save these observations. Keep this page open.</p><p class="muted">Saved on this device; inline and full-page helpers share progress.</p>
 </div>
</template>
<style scoped>
.bo6-liberty{line-height:1.6;color:var(--text);min-width:0}.bo6-liberty p{margin:.7rem 0}.bo6-liberty h3{font-size:1rem;margin:.2rem 0}.bo6-liberty button{min-height:44px;padding:.55rem .75rem;font:inherit;color:var(--text);background:var(--surface-2);border:1px solid var(--line);border-radius:7px;cursor:pointer}.bo6-liberty button[aria-pressed=true],.bo6-liberty button:hover:not(:disabled){border-color:var(--gold);background:var(--gold-dim)}.bo6-liberty button:disabled{opacity:.45;cursor:default}.bo6-liberty :focus-visible{outline:2px solid var(--gold);outline-offset:3px}.projector{margin:1.4rem 0;padding-top:1rem;border-top:1px solid var(--line)}.projector :deep(.guide-illustrations){max-width:560px}.reading-buttons{display:flex;gap:.5rem;flex-wrap:wrap;margin:1rem 0}.swatch{display:inline-block;width:14px;height:14px;border-radius:50%;margin-right:.45rem;vertical-align:middle;border:1px solid #ffffff66}.swatch.red{background:#dd706a}.swatch.yellow{background:#efcf6b}.swatch.green{background:#78b68b}.setting,.result{padding:.85rem 1rem;border:1px solid var(--line);background:var(--surface-2);border-radius:8px}.setting>span{font-size:.78rem}.setting strong{display:block;color:var(--gold);font-size:1.4rem;margin:.25rem 0}.bo6-liberty label{display:flex;gap:.5rem;align-items:center;min-height:44px;font-size:.85rem}.bo6-liberty input[type=checkbox]{width:18px;height:18px;accent-color:var(--gold)}.figure-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,260px),1fr));gap:1.4rem 1rem;margin:1.4rem 0}.figure-grid section{border-top:1px solid var(--line);padding-top:.75rem;min-width:0}.figure-grid section.collected{border-top-color:var(--gold)}.figure-grid section>p{font-size:.83rem}.actions{display:flex;gap:.5rem;flex-wrap:wrap;margin-top:1rem}.muted{font-size:.78rem;color:var(--muted)}.bo6-liberty a{color:var(--gold)}
</style>
