<script setup lang="ts">
import {terminusSymbols,terminusLabResult} from '~/utils/bo6Launch.mjs'
const props=defineProps<{tool:string}>()
const {state,change,undo,reset,canUndo,saveError}=usePuzzleState(props.tool)
const result=computed(()=>terminusLabResult(state.value))
const confirmReset=ref(false)
const cropId=useId()
const croppedSymbols=terminusSymbols.map(symbol=>{const [x,y,width,height]=symbol.viewBox.split(' ').map(Number);return {...symbol,crop:{x,y,width,height}}})
const slots=[{key:'x',label:'X · Docks below Sea Tower'},{key:'y',label:'Y · Storage outside Interrogation'},{key:'z',label:'Z · outside Communications'}]
function select(key:string,value:string){change({...state.value,[key]:state.value[key]===value?'':value})}
</script>
<template>
  <div class="puzzle bo6-lab">
    <p>Activate all three laptops, then interact with the Research Office terminal to reveal its sticky notes. Match each note’s <strong>letter and symbol</strong> below. Their assignments change each match.</p>
    <fieldset v-for="slot in slots" :key="slot.key"><legend>{{slot.label}}</legend><div class="symbol-row"><button v-for="symbol in croppedSymbols" :key="symbol.value" :aria-pressed="state[slot.key]===symbol.value" :aria-label="`${slot.key.toUpperCase()}: ${symbol.label}, value ${symbol.value}`" @click="select(slot.key,symbol.value)"><svg :viewBox="symbol.viewBox" aria-hidden="true" focusable="false"><defs><clipPath :id="`${cropId}-${slot.key}-${symbol.value}`" clipPathUnits="userSpaceOnUse"><rect v-bind="symbol.crop" /></clipPath></defs><image href="/images/bo6-terminus/terminus-beamsmasher-diagrams.webp" width="1164" height="633" :clip-path="`url(#${cropId}-${slot.key}-${symbol.value})`" /></svg><span>{{symbol.value}}</span><span class="selection">{{state[slot.key]===symbol.value?'Selected':'Choose'}}</span></button></div></fieldset>
    <div class="lab-result" :class="result.status" role="status" aria-live="polite"><p>{{result.message}}</p><ol v-if="result.status==='ready'" class="code"><li v-for="(value,i) in result.code" :key="i"><span>Entry {{i+1}}</span><strong>{{value}}</strong></li></ol><p v-if="result.status==='ready'">These are three separate entries. Confirm the code at the terminal, then advance rounds until the island scan finishes and take the Resonator back.</p></div>
    <details v-if="result.status==='ready'"><summary>Show the calculation</summary><ol><li v-for="equation in result.equations" :key="equation"><code>{{equation}}</code></li></ol><p>Only the third equation uses absolute value: a negative result there becomes positive. A selected 0 is a real value, not an empty field.</p></details>
    <details><summary>Show the full symbol key and laptop locations</summary><GuideIllustrations :images="[{src:'/images/bo6-terminus/terminus-beamsmasher-diagrams.webp',alt:'Verified six-symbol reference with values 11, 10, 0, 22, 21 and 20'},{src:'/images/bo6-terminus/terminus-final-laptop.webp',alt:'X laptop: Docks, below Sea Tower'},{src:'/images/bo6-terminus/terminus-second-laptop.webp',alt:'Y laptop: Storage Area'},{src:'/images/bo6-terminus/terminus-first-laptop.webp',alt:'Z laptop: outside Communications'}]" /><p class="muted">Symbol pixels and gameplay references: <a href="https://www.codzombiesguides.com/main-quests/black-ops-6/terminus/" target="_blank" rel="noopener noreferrer">COD Zombies Guides</a>. Use the X, Y and Z labels on your terminal as the final authority.</p></details>
    <div class="actions"><button :disabled="!canUndo" @click="undo">Undo last change</button><button @click="confirmReset=!confirmReset">Reset helper</button></div><div v-if="confirmReset" class="lab-result"><p>Clear all three saved symbols for a new match?</p><div class="actions"><button @click="reset();confirmReset=false">Clear symbols</button><button @click="confirmReset=false">Keep symbols</button></div></div><p v-if="saveError" role="alert">Your browser could not save these symbols. Keep this page open.</p><p class="muted">Saved on this device; the inline and full-page helper share your selections.</p>
  </div>
</template>
<style scoped>
.bo6-lab{line-height:1.6;min-width:0;color:var(--text)}.bo6-lab p{margin:.8rem 0}.bo6-lab fieldset{border:0;border-top:1px solid var(--line);padding:1rem 0;margin:1.25rem 0}.bo6-lab legend{font-weight:700;padding-right:.7rem}.symbol-row{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:.45rem}.bo6-lab button{font:inherit;min-height:44px;border:1px solid var(--line);border-radius:7px;background:var(--surface-2);color:var(--text);padding:.55rem .7rem;cursor:pointer}.symbol-row button{padding:.45rem .2rem;display:flex;align-items:center;flex-direction:column;gap:.2rem;min-width:0}.symbol-row svg{width:100%;height:90px;background:#111}.symbol-row button[aria-pressed=true]{background:var(--gold-dim);border-color:var(--gold)}.symbol-row button>span:first-of-type{font-size:1.1rem;font-variant-numeric:tabular-nums;font-weight:700}.selection{font-size:.68rem;color:var(--muted)}.symbol-row button[aria-pressed=true] .selection{color:var(--gold)}.bo6-lab button:hover:not(:disabled){border-color:var(--gold)}.bo6-lab :focus-visible{outline:2px solid var(--gold);outline-offset:3px}.bo6-lab button:disabled{opacity:.45;cursor:default}.lab-result{padding:1rem;background:var(--surface-2);border:1px solid var(--line);border-radius:8px;margin:1rem 0}.lab-result.invalid{border-color:#db9275}.code{display:flex;list-style:none;gap:1rem;margin:.75rem 0;padding:0;flex-wrap:wrap}.code li{min-width:80px;flex:1}.code span{font-size:.75rem;color:var(--muted)}.code strong{display:block;font-size:2.6rem;line-height:1.1;font-variant-numeric:tabular-nums;color:var(--gold)}.bo6-lab summary{cursor:pointer;min-height:44px;padding:.65rem 0;color:var(--gold)}.actions{display:flex;gap:.5rem;flex-wrap:wrap;margin-top:.8rem}.muted{font-size:.78rem;color:var(--muted)}.bo6-lab a{color:var(--gold)}@media(max-width:560px){.symbol-row{grid-template-columns:repeat(3,minmax(0,1fr))}.symbol-row svg{height:82px}}
</style>
