<script setup lang="ts">
import { solveFlags } from '~/utils/puzzles.mjs'
const {state,change,undo,reset,canUndo,saveError}=usePuzzleState('flags')
const areas=['一 · Stables','二 · Flower Garden','三 · Central Courtyard','四 · Outer Ward']
const solutions=computed(()=>solveFlags(state.value.targets,state.value.inventory))
function set(field:string,i:number,value:string) { const values=state.value[field].slice(); values[i]=value===''?null:Number(value); change({...state.value,[field]:values}) }
const leftover=computed(()=>{const inv=state.value.inventory.slice(); solutions.value?.[0]?.flat().forEach((n:number)=>inv[n-1]--);return inv.map((n:number,i:number)=>n?`${n} × ${i+1}-symbol`:null).filter(Boolean).join(' · ')||'None'})
</script>
<template><div class="puzzle"><p>Enter the four clock numbers in order, then count your available flags. Each area holds <strong>at most two flags</strong>.</p><div class="p-grid"><label v-for="(area,i) in areas" :key="area">{{ area }}<input type="number" min="1" max="12" inputmode="numeric" :value="state.targets[i] ?? ''" @input="set('targets',i,($event.target as HTMLInputElement).value)"></label></div><p><strong>Flag inventory</strong> · how many of each value?</p><div class="p-grid"><label v-for="n in 6" :key="n">{{ n }}-symbol flags<input type="number" min="0" max="8" inputmode="numeric" :value="state.inventory[n-1]" @input="set('inventory',n-1,($event.target as HTMLInputElement).value)"></label></div><div class="p-result" aria-live="polite"><p v-if="!solutions">Record all four clock numbers (1–12).</p><p v-else-if="!state.inventory.some((n:number)=>n>0)">Add the flags you found to see placements.</p><p v-else-if="!solutions.length">These flags cannot fill all four areas. Recheck the numbers and inventory; no area can use more than two flags.</p><template v-else><strong>Place these flags</strong><table class="p-table"><thead><tr><th>Area</th><th>Target</th><th>Flag values</th></tr></thead><tbody><tr v-for="(flags,i) in solutions[0]" :key="i"><td>{{ areas[i] }}</td><td>{{ state.targets[i] }}</td><td><strong>{{ flags.join(' + ') }}</strong></td></tr></tbody></table><p class="p-muted">Unused: {{ leftover }}. Return to the clock after placing all flags.</p><details v-if="solutions.length>1"><summary>Alternative placements</summary><p v-for="(option,i) in solutions.slice(1,4)" :key="i">{{ option.map((flags:number[],n:number)=>`${areas[n]}: ${flags.join(' + ')}`).join(' · ') }}</p></details></template></div><PuzzleActions :can-undo="canUndo" :save-error="saveError" @undo="undo" @reset="reset" /></div></template>
