<script setup lang="ts">
const {state,change,undo,reset,canUndo,saveError}=usePuzzleState('house')
const spots=[{name:'Left wing · inner edge',x:33,y:60},{name:'Center · above lower windows',x:43,y:59},{name:'Right · above upstairs window',x:75.5,y:44.5},{name:'Far right · lower wall',x:83.5,y:66}]
const slot=ref(0)
const oldPoints=ref<{x:number,y:number}[]>([])
onMounted(()=>{try{const value=JSON.parse(localStorage.getItem('cw-rex-house-symbols')||'[]');if(Array.isArray(value))oldPoints.value=value.filter(p=>Number.isFinite(p?.x)&&Number.isFinite(p?.y)&&p.x>=0&&p.x<=100&&p.y>=0&&p.y<=100).slice(0,4)}catch{}})
function pick(id:number) {const order=state.value.order.slice(); const previous=order.indexOf(id); if(previous>=0&&previous!==slot.value) {const old=order[slot.value]; order[previous]=old; }order[Math.min(slot.value,order.length)]=id;change({order});slot.value=Math.min(order.length,3)}
</script>
<template><div class="puzzle"><p>After obtaining Warden’s Blight, shoot the basketball in the broken roof from Nexus Forge. Advance a round for the first symbol, then three more rounds for the others.</p><p>Choose a slot, then the location where its symbol appeared.</p><div class="p-row"><button v-for="n in 4" :key="n" :aria-pressed="slot===n-1" :disabled="n-1>state.order.length" @click="slot=n-1">{{ n }} · {{ state.order[n-1]===undefined?'Empty':spots[state.order[n-1]].name }}</button></div><div class="house-image"><img src="/tools/rex-infernus-house-symbols.jpg" alt="Spawn house viewed from Nexus Forge"><button v-for="(spot,i) in spots" :key="spot.name" :style="{left:spot.x+'%',top:spot.y+'%'}" :aria-label="spot.name" @click="pick(i)">{{ state.order.includes(i)?state.order.indexOf(i)+1:String.fromCharCode(65+i) }}</button></div><div class="p-grid"><button v-for="(spot,i) in spots" :key="spot.name" @click="pick(i)">{{ String.fromCharCode(65+i) }} · {{ spot.name }}</button></div><div class="p-result" aria-live="polite"><strong>{{ state.order.length===4?'Shoot in this order during an Exfil round':'Appearance order · '+state.order.length+'/4' }}</strong><ol style="list-style:decimal;padding-left:1.4rem"><li v-for="id in state.order" :key="id">{{ spots[id].name }}</li></ol></div><p class="p-muted">Then activate Exfil, kill the HVT and take the portal into the house. The letters here identify locations, not in-game symbols.</p><details v-if="oldPoints.length"><summary>Your previous freeform markers</summary><p class="p-muted">Use these as a reference to record named locations above. They have not been snapped to a different position.</p><div class="house-image"><img src="/tools/rex-infernus-house-symbols.jpg" alt="Your previously marked house"><span v-for="(point,i) in oldPoints" :key="i" class="old-marker" :style="{left:point.x+'%',top:point.y+'%'}">{{ i+1 }}</span></div></details><PuzzleActions :can-undo="canUndo" :save-error="saveError" @undo="undo" @reset="reset();slot=0" /></div></template>
<style scoped>.old-marker{position:absolute;transform:translate(-50%,-50%);border:2px solid var(--wp-gold);border-radius:50%;padding:.3rem;background:#171717;color:white}.house-image{position:relative;margin:.8rem 0}.house-image img{display:block;width:100%;border-radius:8px}.house-image button{position:absolute;transform:translate(-50%,-50%);border:2px solid var(--wp-gold);border-radius:50%;background:#171717;color:#fff;width:44px;height:44px;padding:0;font-weight:800}</style>
