<script setup lang="ts">
import { solveUranium } from '~/utils/puzzles.mjs'
const {state,change,undo,reset,canUndo,saveError}=usePuzzleState('uranium')
const index=ref(0)
const solutions=computed(()=>solveUranium(state.value.existing))
const solution=computed(()=>solutions.value[index.value] || solutions.value[0])
watch(()=>state.value.existing,()=>index.value=0,{deep:true})
function tap(n:number) { const existing=state.value.existing; if(existing.includes(n)) change({existing:existing.filter((v:number)=>v!==n)}); else if(existing.length<6) change({existing:[...existing,n]}) }
</script>
<template><div class="puzzle"><p>Facing the machine, mark the <strong>six existing tubes</strong>. Suggested uranium placements appear as numbered circles.</p><div class="p-board" style="grid-template-columns:repeat(4,1fr)"><button v-for="n in 16" :key="n" :aria-label="`Row ${Math.ceil(n/4)}, column ${(n-1)%4+1}: ${state.existing.includes(n-1)?'existing tube':solution?.added.includes(n-1)?'add uranium':'empty'}`" :aria-pressed="state.existing.includes(n-1)" :disabled="state.existing.length===6 && !state.existing.includes(n-1)" @click="tap(n-1)"><strong>{{ state.existing.includes(n-1)?'■':solution?.added.includes(n-1)?'◉':'·' }}</strong><small>{{ solution?.added.includes(n-1)?`Add ${solution.added.indexOf(n-1)+1}`:`${Math.ceil(n/4)},${(n-1)%4+1}` }}</small></button></div><div class="p-result" aria-live="polite"><p v-if="state.existing.length<6">{{ state.existing.length }} / 6 tubes recorded.</p><template v-else-if="solution"><strong>Add the three uranium tubes</strong><p>{{ solution.added.map((n:number)=>`row ${Math.floor(n/4)+1}, column ${n%4+1}`).join(' · ') }}</p><p class="p-muted">Activated groups: {{ solution.groups.join(' + ') }}.</p><div class="p-row"><button :disabled="index===0" @click="index--">Previous layout</button><span>{{ index+1 }} / {{ solutions.length }}</span><button :disabled="index>=solutions.length-1" @click="index++">Next layout</button></div></template><p v-else>No placement matches the documented patterns. Recheck the six existing tubes and compare the in-game gauge.</p></div><details><summary>How these suggestions are checked</summary><p>Only connected groups containing uranium are activated; diagonal neighbours do not connect. Uses the community-tested patterns 7, 8, 7+1, 7+2, 6+3 and 7+1+1. This is a community model; use the machine’s gauge to confirm.</p><a href="https://www.reddit.com/r/CODZombies/comments/1t6u85o/totenreich_claw_machine_can_actually_be/" target="_blank" rel="noopener noreferrer">Scoring research</a></details><PuzzleActions :can-undo="canUndo" :save-error="saveError" @undo="undo" @reset="reset" /></div></template>
