// Generated from shared/catalogue.json; run node scripts/generate-catalogue.mjs.
const NAV = [
  {
    "id": "ashes-of-the-damned",
    "map": "ashes-of-the-damned",
    "game": "bo7",
    "gameName": "Black Ops 7",
    "group": "",
    "status": "available",
    "keywords": "Black Ops VII  ",
    "kind": "guide",
    "section": "Ashes of the Damned",
    "label": "Guide",
    "url": "/guides/ashes-of-the-damned",
    "accel": "Ctrl+2",
    "icon": "◇"
  },
  {
    "id": "ashes-rocket-launch",
    "map": "ashes-of-the-damned",
    "game": "bo7",
    "gameName": "Black Ops 7",
    "kind": "tool",
    "section": "Ashes of the Damned",
    "label": "Rocket Launch Codes",
    "url": "/tools/ashes-rocket-launch",
    "accel": "Ctrl+Shift+6",
    "icon": "↗"
  },
  {
    "id": "ashes-serum",
    "map": "ashes-of-the-damned",
    "game": "bo7",
    "gameName": "Black Ops 7",
    "kind": "tool",
    "section": "Ashes of the Damned",
    "label": "Serum Ingredient Order",
    "url": "/tools/ashes-serum",
    "accel": "Ctrl+Shift+7",
    "icon": "↗"
  },
  {
    "id": "astra-malorum",
    "map": "astra-malorum",
    "game": "bo7",
    "gameName": "Black Ops 7",
    "group": "",
    "status": "available",
    "keywords": "Black Ops VII  ",
    "kind": "guide",
    "section": "Astra Malorum",
    "label": "Guide",
    "url": "/guides/astra-malorum",
    "accel": "Ctrl+3",
    "icon": "◇"
  },
  {
    "id": "astra-mars-code",
    "map": "astra-malorum",
    "game": "bo7",
    "gameName": "Black Ops 7",
    "kind": "tool",
    "section": "Astra Malorum",
    "label": "Mars Code",
    "url": "/tools/astra-mars-code",
    "accel": "Ctrl+Shift+8",
    "icon": "↗"
  },
  {
    "id": "astra-organ",
    "map": "astra-malorum",
    "game": "bo7",
    "gameName": "Black Ops 7",
    "kind": "tool",
    "section": "Astra Malorum",
    "label": "Harmonic Organ Order",
    "url": "/tools/astra-harmonic-organ",
    "accel": "Ctrl+Shift+9",
    "icon": "↗"
  },
  {
    "id": "astra-planets",
    "map": "astra-malorum",
    "game": "bo7",
    "gameName": "Black Ops 7",
    "kind": "tool",
    "section": "Astra Malorum",
    "label": "Planet Sheets Map",
    "url": "/tools/astra-planet-sheets",
    "accel": "Ctrl+Shift+0",
    "icon": "↗"
  },
  {
    "id": "paradox-junction",
    "map": "paradox-junction",
    "game": "bo7",
    "gameName": "Black Ops 7",
    "group": "",
    "status": "available",
    "keywords": "Black Ops VII  ",
    "kind": "guide",
    "section": "Paradox Junction",
    "label": "Guide",
    "url": "/guides/paradox-junction",
    "accel": "Ctrl+4",
    "icon": "◇"
  },
  {
    "id": "paradox-notes",
    "map": "paradox-junction",
    "game": "bo7",
    "gameName": "Black Ops 7",
    "kind": "tool",
    "section": "Paradox Junction",
    "label": "Note Order & Piano",
    "url": "/tools/paradox-note-order",
    "accel": "Ctrl+Alt+1",
    "icon": "↗"
  },
  {
    "id": "totenreich",
    "map": "totenreich",
    "game": "bo7",
    "gameName": "Black Ops 7",
    "group": "",
    "status": "available",
    "keywords": "Black Ops VII  ",
    "kind": "guide",
    "section": "Totenreich",
    "label": "Guide",
    "url": "/guides/totenreich",
    "accel": "Ctrl+5",
    "icon": "◇"
  },
  {
    "id": "totenreich-uranium",
    "map": "totenreich",
    "game": "bo7",
    "gameName": "Black Ops 7",
    "kind": "tool",
    "section": "Totenreich",
    "label": "Uranium Pincers Solver",
    "url": "/tools/totenreich-uranium-pincers",
    "accel": "Ctrl+Shift+4",
    "icon": "↗"
  },
  {
    "id": "totenreich-wunderbarrage",
    "map": "totenreich",
    "game": "bo7",
    "gameName": "Black Ops 7",
    "kind": "tool",
    "section": "Totenreich",
    "label": "Wunderbarrage Codes",
    "url": "/tools/totenreich-wunderbarrage",
    "accel": "Ctrl+Shift+5",
    "icon": "↗"
  },
  {
    "id": "kowakujo",
    "map": "kowakujo",
    "game": "bo7",
    "gameName": "Black Ops 7",
    "group": "",
    "status": "available",
    "keywords": "Black Ops VII  ",
    "kind": "guide",
    "section": "Kowakujō",
    "label": "Guide",
    "url": "/guides/kowakujo",
    "accel": "Ctrl+6",
    "icon": "◇"
  },
  {
    "id": "kowakujo-pestle",
    "map": "kowakujo",
    "game": "bo7",
    "gameName": "Black Ops 7",
    "kind": "tool",
    "section": "Kowakujō",
    "label": "Pestle Scroll Solver",
    "url": "/tools/kowakujo-pestle-solver",
    "accel": "Ctrl+7",
    "icon": "↗"
  },
  {
    "id": "kowakujo-clock",
    "map": "kowakujo",
    "game": "bo7",
    "gameName": "Black Ops 7",
    "kind": "tool",
    "section": "Kowakujō",
    "label": "Clock & Flags Solver",
    "url": "/tools/kowakujo-clock-solver",
    "accel": "Ctrl+8",
    "icon": "↗"
  },
  {
    "id": "kowakujo-murder",
    "map": "kowakujo",
    "game": "bo7",
    "gameName": "Black Ops 7",
    "kind": "tool",
    "section": "Kowakujō",
    "label": "Murder Mystery Solver",
    "url": "/tools/kowakujo-murder-solver",
    "accel": "Ctrl+Shift+1",
    "icon": "↗"
  },
  {
    "id": "rex-infernus",
    "map": "rex-infernus",
    "game": "bo7",
    "gameName": "Black Ops 7",
    "group": "",
    "status": "available",
    "keywords": "Black Ops VII  ",
    "kind": "guide",
    "section": "Rex Infernus",
    "label": "Guide",
    "url": "/guides/rex-infernus",
    "accel": "Ctrl+1",
    "icon": "◇"
  },
  {
    "id": "rex-ring",
    "map": "rex-infernus",
    "game": "bo7",
    "gameName": "Black Ops 7",
    "kind": "tool",
    "section": "Rex Infernus",
    "label": "Temple Ring Solver",
    "url": "/tools/rex-infernus-ring-solver",
    "accel": "Ctrl+9",
    "icon": "↗"
  },
  {
    "id": "rex-pillars",
    "map": "rex-infernus",
    "game": "bo7",
    "gameName": "Black Ops 7",
    "kind": "tool",
    "section": "Rex Infernus",
    "label": "Pillars & Levers",
    "url": "/tools/rex-infernus-pillars",
    "accel": "Ctrl+Shift+2",
    "icon": "↗"
  },
  {
    "id": "rex-house-symbols",
    "map": "rex-infernus",
    "game": "bo7",
    "gameName": "Black Ops 7",
    "kind": "tool",
    "section": "Rex Infernus",
    "label": "House Symbols Tracker",
    "url": "/tools/rex-infernus-house-symbols",
    "accel": "Ctrl+Shift+3",
    "icon": "↗"
  },
  {
    "id": "bo6-liberty-falls",
    "map": "bo6-liberty-falls",
    "game": "bo6",
    "gameName": "Black Ops 6",
    "group": "",
    "status": "available",
    "keywords": "Black Ops VI  ",
    "kind": "guide",
    "section": "Liberty Falls",
    "label": "Guide",
    "url": "/guides/bo6-liberty-falls",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo6-liberty-strauss",
    "map": "bo6-liberty-falls",
    "game": "bo6",
    "gameName": "Black Ops 6",
    "kind": "tool",
    "section": "Liberty Falls",
    "label": "Strauss Counter & projector helper",
    "url": "/tools/bo6-liberty-strauss",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo6-terminus",
    "map": "bo6-terminus",
    "game": "bo6",
    "gameName": "Black Ops 6",
    "group": "",
    "status": "available",
    "keywords": "Black Ops VI  ",
    "kind": "guide",
    "section": "Terminus",
    "label": "Guide",
    "url": "/guides/bo6-terminus",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo6-terminus-lab",
    "map": "bo6-terminus",
    "game": "bo6",
    "gameName": "Black Ops 6",
    "kind": "tool",
    "section": "Terminus",
    "label": "Beamsmasher visual lab solver",
    "url": "/tools/bo6-terminus-lab",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo6-citadelle-des-morts",
    "map": "bo6-citadelle-des-morts",
    "game": "bo6",
    "gameName": "Black Ops 6",
    "group": "",
    "status": "available",
    "keywords": "Black Ops VI  ",
    "kind": "guide",
    "section": "Citadelle des Morts",
    "label": "Guide",
    "url": "/guides/bo6-citadelle-des-morts",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo6-citadelle-raven",
    "map": "bo6-citadelle-des-morts",
    "game": "bo6",
    "gameName": "Black Ops 6",
    "kind": "tool",
    "section": "Citadelle des Morts",
    "label": "Raven sword — visual ring solution",
    "url": "/tools/bo6-citadelle-raven",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo6-citadelle-symbols",
    "map": "bo6-citadelle-des-morts",
    "game": "bo6",
    "gameName": "Black Ops 6",
    "kind": "tool",
    "section": "Citadelle des Morts",
    "label": "Tavern runes & book trap sequence",
    "url": "/tools/bo6-citadelle-symbols",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo6-the-tomb",
    "map": "bo6-the-tomb",
    "game": "bo6",
    "gameName": "Black Ops 6",
    "group": "",
    "status": "available",
    "keywords": "Black Ops VI  ",
    "kind": "guide",
    "section": "The Tomb",
    "label": "Guide",
    "url": "/guides/bo6-the-tomb",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo6-tomb-symbols",
    "map": "bo6-the-tomb",
    "game": "bo6",
    "gameName": "Black Ops 6",
    "kind": "tool",
    "section": "The Tomb",
    "label": "Ice Staff — rock glyphs to gateway",
    "url": "/tools/bo6-tomb-symbols",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo6-shattered-veil",
    "map": "bo6-shattered-veil",
    "game": "bo6",
    "gameName": "Black Ops 6",
    "group": "",
    "status": "available",
    "keywords": "Black Ops VI  ",
    "kind": "guide",
    "section": "Shattered Veil",
    "label": "Guide",
    "url": "/guides/bo6-shattered-veil",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo6-shattered-cipher",
    "map": "bo6-shattered-veil",
    "game": "bo6",
    "gameName": "Black Ops 6",
    "kind": "tool",
    "section": "Shattered Veil",
    "label": "Nursery cipher decoder",
    "url": "/tools/bo6-shattered-cipher",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo6-reckoning",
    "map": "bo6-reckoning",
    "game": "bo6",
    "gameName": "Black Ops 6",
    "group": "",
    "status": "available",
    "keywords": "Black Ops VI  ",
    "kind": "guide",
    "section": "Reckoning",
    "label": "Guide",
    "url": "/guides/bo6-reckoning",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo6-reckoning-element",
    "map": "bo6-reckoning",
    "game": "bo6",
    "gameName": "Black Ops 6",
    "kind": "tool",
    "section": "Reckoning",
    "label": "Gorgofex monitor code",
    "url": "/tools/bo6-reckoning-element",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo6-reckoning-files",
    "map": "bo6-reckoning",
    "game": "bo6",
    "gameName": "Black Ops 6",
    "kind": "tool",
    "section": "Reckoning",
    "label": "S.A.M. archive order",
    "url": "/tools/bo6-reckoning-files",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "cw-die-maschine",
    "map": "cw-die-maschine",
    "game": "cw",
    "gameName": "Black Ops Cold War",
    "group": "",
    "status": "available",
    "keywords": "BOCW  ",
    "kind": "guide",
    "section": "Die Maschine",
    "label": "Guide",
    "url": "/guides/cw-die-maschine",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "cw-die-variants",
    "map": "cw-die-maschine",
    "game": "cw",
    "gameName": "Black Ops Cold War",
    "kind": "tool",
    "section": "Die Maschine",
    "label": "D.I.E. port and upgrade reference",
    "url": "/tools/cw-die-variants",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "cw-firebase-z",
    "map": "cw-firebase-z",
    "game": "cw",
    "gameName": "Black Ops Cold War",
    "group": "",
    "status": "available",
    "keywords": "BOCW  ",
    "kind": "guide",
    "section": "Firebase Z",
    "label": "Guide",
    "url": "/guides/cw-firebase-z",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "cw-firebase-darts",
    "map": "cw-firebase-z",
    "game": "cw",
    "gameName": "Black Ops Cold War",
    "kind": "tool",
    "section": "Firebase Z",
    "label": "RAI K-84 visual dartboard",
    "url": "/tools/cw-firebase-darts",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "cw-mauer-der-toten",
    "map": "cw-mauer-der-toten",
    "game": "cw",
    "gameName": "Black Ops Cold War",
    "group": "",
    "status": "available",
    "keywords": "BOCW  ",
    "kind": "guide",
    "section": "Mauer der Toten",
    "label": "Guide",
    "url": "/guides/cw-mauer-der-toten",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "cw-mauer-safe",
    "map": "cw-mauer-der-toten",
    "game": "cw",
    "gameName": "Black Ops Cold War",
    "kind": "tool",
    "section": "Mauer der Toten",
    "label": "CRBR-S safe and blacklight locations",
    "url": "/tools/cw-mauer-safe",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "cw-forsaken",
    "map": "cw-forsaken",
    "game": "cw",
    "gameName": "Black Ops Cold War",
    "group": "",
    "status": "available",
    "keywords": "BOCW  ",
    "kind": "guide",
    "section": "Forsaken",
    "label": "Guide",
    "url": "/guides/cw-forsaken",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "cw-forsaken-tvs",
    "map": "cw-forsaken",
    "game": "cw",
    "gameName": "Black Ops Cold War",
    "kind": "tool",
    "section": "Forsaken",
    "label": "Perkaholic TV sequence",
    "url": "/tools/cw-forsaken-tvs",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "cw-outbreak",
    "map": "cw-outbreak",
    "game": "cw",
    "gameName": "Black Ops Cold War",
    "group": "",
    "status": "available",
    "keywords": "BOCW  ",
    "kind": "guide",
    "section": "Outbreak",
    "label": "Guide",
    "url": "/guides/cw-outbreak",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "cw-outbreak-ravenov",
    "map": "cw-outbreak",
    "game": "cw",
    "gameName": "Black Ops Cold War",
    "kind": "quest",
    "section": "Outbreak",
    "label": "Ravenov Implications",
    "url": "/guides/cw-outbreak-ravenov",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "cw-outbreak-excision",
    "map": "cw-outbreak",
    "game": "cw",
    "gameName": "Black Ops Cold War",
    "kind": "quest",
    "section": "Outbreak",
    "label": "Operation Excision",
    "url": "/guides/cw-outbreak-excision",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "cw-outbreak-regions",
    "map": "cw-outbreak",
    "game": "cw",
    "gameName": "Black Ops Cold War",
    "kind": "tool",
    "section": "Outbreak",
    "label": "Outbreak quest location finder",
    "url": "/tools/cw-outbreak-regions",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "cw-outbreak-launch",
    "map": "cw-outbreak",
    "game": "cw",
    "gameName": "Black Ops Cold War",
    "kind": "tool",
    "section": "Outbreak",
    "label": "Outbreak launch-light solver",
    "url": "/tools/cw-outbreak-launch",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo4-dead-of-the-night",
    "map": "bo4-dead-of-the-night",
    "game": "bo4",
    "gameName": "Black Ops 4",
    "group": "",
    "status": "available",
    "keywords": "Black Ops IV  ",
    "kind": "guide",
    "section": "Dead of the Night",
    "label": "Guide",
    "url": "/guides/bo4-dead-of-the-night",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo4-dead-of-the-night-alistair",
    "map": "bo4-dead-of-the-night",
    "game": "bo4",
    "gameName": "Black Ops 4",
    "kind": "tool",
    "section": "Dead of the Night",
    "label": "Alistair’s visual lock",
    "url": "/tools/bo4-dead-of-the-night-alistair",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo4-dead-of-the-night-zodiac",
    "map": "bo4-dead-of-the-night",
    "game": "bo4",
    "gameName": "Black Ops 4",
    "kind": "tool",
    "section": "Dead of the Night",
    "label": "Visual zodiac & scratch solver",
    "url": "/tools/bo4-dead-of-the-night-zodiac",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo4-dead-of-the-night-stake",
    "map": "bo4-dead-of-the-night",
    "game": "bo4",
    "gameName": "Black Ops 4",
    "kind": "tool",
    "section": "Dead of the Night",
    "label": "Stake Knife shape-to-location solver",
    "url": "/tools/bo4-dead-of-the-night-stake",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo4-ix",
    "map": "bo4-ix",
    "game": "bo4",
    "gameName": "Black Ops 4",
    "group": "",
    "status": "available",
    "keywords": "Black Ops IV  ",
    "kind": "guide",
    "section": "IX",
    "label": "Guide",
    "url": "/guides/bo4-ix",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo4-ix-ra",
    "map": "bo4-ix",
    "game": "bo4",
    "gameName": "Black Ops 4",
    "kind": "tool",
    "section": "IX",
    "label": "Ra visual kill order",
    "url": "/tools/bo4-ix-ra",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo4-voyage-of-despair",
    "map": "bo4-voyage-of-despair",
    "game": "bo4",
    "gameName": "Black Ops 4",
    "group": "",
    "status": "available",
    "keywords": "Black Ops IV  ",
    "kind": "guide",
    "section": "Voyage of Despair",
    "label": "Guide",
    "url": "/guides/bo4-voyage-of-despair",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo4-voyage-clocks",
    "map": "bo4-voyage-of-despair",
    "game": "bo4",
    "gameName": "Black Ops 4",
    "kind": "tool",
    "section": "Voyage of Despair",
    "label": "Clock symbols → lever settings",
    "url": "/tools/bo4-voyage-clocks",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo4-voyage-outlets",
    "map": "bo4-voyage-of-despair",
    "game": "bo4",
    "gameName": "Black Ops 4",
    "kind": "tool",
    "section": "Voyage of Despair",
    "label": "Element → outlet route",
    "url": "/tools/bo4-voyage-outlets",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo4-voyage-sky",
    "map": "bo4-voyage-of-despair",
    "game": "bo4",
    "gameName": "Black Ops 4",
    "kind": "tool",
    "section": "Voyage of Despair",
    "label": "Planet order & orb route",
    "url": "/tools/bo4-voyage-sky",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo4-blood-of-the-dead",
    "map": "bo4-blood-of-the-dead",
    "game": "bo4",
    "gameName": "Black Ops 4",
    "group": "",
    "status": "available",
    "keywords": "Black Ops IV  ",
    "kind": "guide",
    "section": "Blood of the Dead",
    "label": "Guide",
    "url": "/guides/bo4-blood-of-the-dead",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo4-blood-morse",
    "map": "bo4-blood-of-the-dead",
    "game": "bo4",
    "gameName": "Black Ops 4",
    "kind": "tool",
    "section": "Blood of the Dead",
    "label": "Buoy Morse calculator",
    "url": "/tools/bo4-blood-morse",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo4-blood-powerhouse",
    "map": "bo4-blood-of-the-dead",
    "game": "bo4",
    "gameName": "Black Ops 4",
    "kind": "tool",
    "section": "Blood of the Dead",
    "label": "Simon Says room map & symbol matcher",
    "url": "/tools/bo4-blood-powerhouse",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo4-ancient-evil",
    "map": "bo4-ancient-evil",
    "game": "bo4",
    "gameName": "Black Ops 4",
    "group": "",
    "status": "available",
    "keywords": "Black Ops IV  ",
    "kind": "guide",
    "section": "Ancient Evil",
    "label": "Guide",
    "url": "/guides/bo4-ancient-evil",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo4-ancient-hands",
    "map": "bo4-ancient-evil",
    "game": "bo4",
    "gameName": "Black Ops 4",
    "kind": "tool",
    "section": "Ancient Evil",
    "label": "Oracle hand location finder",
    "url": "/tools/bo4-ancient-hands",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo4-ancient-tribute",
    "map": "bo4-ancient-evil",
    "game": "bo4",
    "gameName": "Black Ops 4",
    "kind": "tool",
    "section": "Ancient Evil",
    "label": "Eternal Flame tribute calculator",
    "url": "/tools/bo4-ancient-tribute",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo4-alpha-omega",
    "map": "bo4-alpha-omega",
    "game": "bo4",
    "gameName": "Black Ops 4",
    "group": "",
    "status": "available",
    "keywords": "Black Ops IV  ",
    "kind": "guide",
    "section": "Alpha Omega",
    "label": "Guide",
    "url": "/guides/bo4-alpha-omega",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo4-alpha-clocks",
    "map": "bo4-alpha-omega",
    "game": "bo4",
    "gameName": "Black Ops 4",
    "kind": "tool",
    "section": "Alpha Omega",
    "label": "Rushmore visual clock route",
    "url": "/tools/bo4-alpha-clocks",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo4-alpha-rushmore",
    "map": "bo4-alpha-omega",
    "game": "bo4",
    "gameName": "Black Ops 4",
    "kind": "tool",
    "section": "Alpha Omega",
    "label": "Rushmore code reference & observations",
    "url": "/tools/bo4-alpha-rushmore",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo4-tag-der-toten",
    "map": "bo4-tag-der-toten",
    "game": "bo4",
    "gameName": "Black Ops 4",
    "group": "",
    "status": "available",
    "keywords": "Black Ops IV  ",
    "kind": "guide",
    "section": "Tag der Toten",
    "label": "Guide",
    "url": "/guides/bo4-tag-der-toten",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo4-tag-riddles",
    "map": "bo4-tag-der-toten",
    "game": "bo4",
    "gameName": "Black Ops 4",
    "kind": "tool",
    "section": "Tag der Toten",
    "label": "Offering & Seal photo finder",
    "url": "/tools/bo4-tag-riddles",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo4-classified",
    "map": "bo4-classified",
    "game": "bo4",
    "gameName": "Black Ops 4",
    "group": "",
    "status": "available",
    "keywords": "Black Ops IV  ",
    "kind": "guide",
    "section": "Classified",
    "label": "Guide",
    "url": "/guides/bo4-classified",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo4-classified-codes",
    "map": "bo4-classified",
    "game": "bo4",
    "gameName": "Black Ops 4",
    "kind": "tool",
    "section": "Classified",
    "label": "Project Skadi photo codes",
    "url": "/tools/bo4-classified-codes",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo3-shadows-of-evil",
    "map": "bo3-shadows-of-evil",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "group": "",
    "status": "available",
    "keywords": "Black Ops III  ",
    "kind": "guide",
    "section": "Shadows of Evil",
    "label": "Guide",
    "url": "/guides/bo3-shadows-of-evil",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo3-shadows-glyphs",
    "map": "bo3-shadows-of-evil",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "kind": "tool",
    "section": "Shadows of Evil",
    "label": "Train symbol matcher",
    "url": "/tools/bo3-shadows-glyphs",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo3-the-giant",
    "map": "bo3-the-giant",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "group": "",
    "status": "available",
    "keywords": "Black Ops III  ",
    "kind": "guide",
    "section": "The Giant",
    "label": "Guide",
    "url": "/guides/bo3-the-giant",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo3-der-eisendrache",
    "map": "bo3-der-eisendrache",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "group": "",
    "status": "available",
    "keywords": "Black Ops III  ",
    "kind": "guide",
    "section": "Der Eisendrache",
    "label": "Guide",
    "url": "/guides/bo3-der-eisendrache",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo3-de-void",
    "map": "bo3-der-eisendrache",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "kind": "tool",
    "section": "Der Eisendrache",
    "label": "Void Bow name → symbol matcher",
    "url": "/tools/bo3-de-void",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo3-de-terminals",
    "map": "bo3-der-eisendrache",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "kind": "tool",
    "section": "Der Eisendrache",
    "label": "Safe code & terminal memory",
    "url": "/tools/bo3-de-terminals",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo3-zetsubou-no-shima",
    "map": "bo3-zetsubou-no-shima",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "group": "",
    "status": "available",
    "keywords": "Black Ops III  ",
    "kind": "guide",
    "section": "Zetsubou No Shima",
    "label": "Guide",
    "url": "/guides/bo3-zetsubou-no-shima",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo3-zetsubou-plants",
    "map": "bo3-zetsubou-no-shima",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "kind": "tool",
    "section": "Zetsubou No Shima",
    "label": "Plant recipes & water locations",
    "url": "/tools/bo3-zetsubou-plants",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo3-gorod-krovi",
    "map": "bo3-gorod-krovi",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "group": "",
    "status": "available",
    "keywords": "Black Ops III  ",
    "kind": "guide",
    "section": "Gorod Krovi",
    "label": "Guide",
    "url": "/guides/bo3-gorod-krovi",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo3-gorod-valves",
    "map": "bo3-gorod-krovi",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "kind": "tool",
    "section": "Gorod Krovi",
    "label": "Valve solver with room photos",
    "url": "/tools/bo3-gorod-valves",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo3-gorod-bombs",
    "map": "bo3-gorod-krovi",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "kind": "tool",
    "section": "Gorod Krovi",
    "label": "Bomb order & location cards",
    "url": "/tools/bo3-gorod-bombs",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo3-revelations",
    "map": "bo3-revelations",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "group": "",
    "status": "available",
    "keywords": "Black Ops III  ",
    "kind": "guide",
    "section": "Revelations",
    "label": "Guide",
    "url": "/guides/bo3-revelations",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo3-revelations-runes",
    "map": "bo3-revelations",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "kind": "tool",
    "section": "Revelations",
    "label": "Kronorium order recorder",
    "url": "/tools/bo3-revelations-runes",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo3-revelations-collections",
    "map": "bo3-revelations",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "kind": "tool",
    "section": "Revelations",
    "label": "Egg, rune, bone & relic finder",
    "url": "/tools/bo3-revelations-collections",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo3-nacht-der-untoten",
    "map": "bo3-nacht-der-untoten",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "group": "chronicles",
    "status": "available",
    "keywords": "Black Ops III  ",
    "kind": "guide",
    "section": "Nacht der Untoten",
    "label": "Guide",
    "url": "/guides/bo3-nacht-der-untoten",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo3-nacht-secrets",
    "map": "bo3-nacht-der-untoten",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "kind": "tool",
    "section": "Nacht der Untoten",
    "label": "Samantha buttons & doll finder",
    "url": "/tools/bo3-nacht-secrets",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo3-verruckt",
    "map": "bo3-verruckt",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "group": "chronicles",
    "status": "available",
    "keywords": "Black Ops III  ",
    "kind": "guide",
    "section": "Verrückt",
    "label": "Guide",
    "url": "/guides/bo3-verruckt",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo3-verruckt-dolls",
    "map": "bo3-verruckt",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "kind": "tool",
    "section": "Verrückt",
    "label": "Samantha doll location finder",
    "url": "/tools/bo3-verruckt-dolls",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo3-shi-no-numa",
    "map": "bo3-shi-no-numa",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "group": "chronicles",
    "status": "available",
    "keywords": "Black Ops III  ",
    "kind": "guide",
    "section": "Shi No Numa",
    "label": "Guide",
    "url": "/guides/bo3-shi-no-numa",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo3-shi-perks",
    "map": "bo3-shi-no-numa",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "kind": "tool",
    "section": "Shi No Numa",
    "label": "Hut perk notebook",
    "url": "/tools/bo3-shi-perks",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo3-kino-der-toten",
    "map": "bo3-kino-der-toten",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "group": "chronicles",
    "status": "available",
    "keywords": "Black Ops III  ",
    "kind": "guide",
    "section": "Kino der Toten",
    "label": "Guide",
    "url": "/guides/bo3-kino-der-toten",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo3-kino-dolls",
    "map": "bo3-kino-der-toten",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "kind": "tool",
    "section": "Kino der Toten",
    "label": "Samantha doll location finder",
    "url": "/tools/bo3-kino-dolls",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo3-kino-knocks",
    "map": "bo3-kino-der-toten",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "kind": "tool",
    "section": "Kino der Toten",
    "label": "Alley knock recorder",
    "url": "/tools/bo3-kino-knocks",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo3-ascension",
    "map": "bo3-ascension",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "group": "chronicles",
    "status": "available",
    "keywords": "Black Ops III  ",
    "kind": "guide",
    "section": "Ascension",
    "label": "Guide",
    "url": "/guides/bo3-ascension",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo3-ascension-dolls",
    "map": "bo3-ascension",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "kind": "tool",
    "section": "Ascension",
    "label": "Samantha captures & target order",
    "url": "/tools/bo3-ascension-dolls",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo3-shangri-la",
    "map": "bo3-shangri-la",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "group": "chronicles",
    "status": "available",
    "keywords": "Black Ops III  ",
    "kind": "guide",
    "section": "Shangri-La",
    "label": "Guide",
    "url": "/guides/bo3-shangri-la",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo3-shang-tiles",
    "map": "bo3-shangri-la",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "kind": "tool",
    "section": "Shangri-La",
    "label": "Matching tile symbol notebook",
    "url": "/tools/bo3-shang-tiles",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo3-shang-gongs",
    "map": "bo3-shangri-la",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "kind": "tool",
    "section": "Shangri-La",
    "label": "Gong locations & match notes",
    "url": "/tools/bo3-shang-gongs",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo3-moon",
    "map": "bo3-moon",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "group": "chronicles",
    "status": "available",
    "keywords": "Black Ops III  ",
    "kind": "guide",
    "section": "Moon",
    "label": "Guide",
    "url": "/guides/bo3-moon",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo3-moon-labs",
    "map": "bo3-moon",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "kind": "tool",
    "section": "Moon",
    "label": "Hacker panel & cable finder",
    "url": "/tools/bo3-moon-labs",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo3-moon-simon",
    "map": "bo3-moon",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "kind": "tool",
    "section": "Moon",
    "label": "Samantha Says sequence recorder",
    "url": "/tools/bo3-moon-simon",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo3-origins",
    "map": "bo3-origins",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "group": "chronicles",
    "status": "available",
    "keywords": "Black Ops III  ",
    "kind": "guide",
    "section": "Origins",
    "label": "Guide",
    "url": "/guides/bo3-origins",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo3-origins-locations",
    "map": "bo3-origins",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "kind": "tool",
    "section": "Origins",
    "label": "Staff parts & secret locations",
    "url": "/tools/bo3-origins-locations",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo3-origins-ice",
    "map": "bo3-origins",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "kind": "tool",
    "section": "Origins",
    "label": "Ice staff symbol matcher",
    "url": "/tools/bo3-origins-ice",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo3-origins-fire",
    "map": "bo3-origins",
    "game": "bo3",
    "gameName": "Black Ops 3",
    "kind": "tool",
    "section": "Origins",
    "label": "Fire staff torch decoder",
    "url": "/tools/bo3-origins-fire",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo2-tranzit",
    "map": "bo2-tranzit",
    "game": "bo2",
    "gameName": "Black Ops 2",
    "group": "",
    "status": "available",
    "keywords": "Black Ops II  ",
    "kind": "guide",
    "section": "TranZit",
    "label": "Guide",
    "url": "/guides/bo2-tranzit",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo2-bus-depot",
    "map": "bo2-bus-depot",
    "game": "bo2",
    "gameName": "Black Ops 2",
    "group": "survival",
    "status": "available",
    "keywords": "Black Ops II  Survival",
    "kind": "guide",
    "section": "Bus Depot",
    "label": "Guide",
    "url": "/guides/bo2-bus-depot",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo2-town",
    "map": "bo2-town",
    "game": "bo2",
    "gameName": "Black Ops 2",
    "group": "survival",
    "status": "available",
    "keywords": "Black Ops II  Survival / Grief",
    "kind": "guide",
    "section": "Town",
    "label": "Guide",
    "url": "/guides/bo2-town",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo2-farm",
    "map": "bo2-farm",
    "game": "bo2",
    "gameName": "Black Ops 2",
    "group": "survival",
    "status": "available",
    "keywords": "Black Ops II  Survival / Grief",
    "kind": "guide",
    "section": "Farm",
    "label": "Guide",
    "url": "/guides/bo2-farm",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo2-diner",
    "map": "bo2-diner",
    "game": "bo2",
    "gameName": "Black Ops 2",
    "group": "survival",
    "status": "available",
    "keywords": "Black Ops II  Turned",
    "kind": "guide",
    "section": "Diner",
    "label": "Guide",
    "url": "/guides/bo2-diner",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo2-nuketown-zombies",
    "map": "bo2-nuketown-zombies",
    "game": "bo2",
    "gameName": "Black Ops 2",
    "group": "survival",
    "status": "available",
    "keywords": "Black Ops II  Survival",
    "kind": "guide",
    "section": "Nuketown Zombies",
    "label": "Guide",
    "url": "/guides/bo2-nuketown-zombies",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo2-die-rise",
    "map": "bo2-die-rise",
    "game": "bo2",
    "gameName": "Black Ops 2",
    "group": "",
    "status": "available",
    "keywords": "Black Ops II  ",
    "kind": "guide",
    "section": "Die Rise",
    "label": "Guide",
    "url": "/guides/bo2-die-rise",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo2-die-rise-mahjong",
    "map": "bo2-die-rise",
    "game": "bo2",
    "gameName": "Black Ops 2",
    "kind": "tool",
    "section": "Die Rise",
    "label": "Mahjong tower order",
    "url": "/tools/bo2-die-rise-mahjong",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo2-mob-of-the-dead",
    "map": "bo2-mob-of-the-dead",
    "game": "bo2",
    "gameName": "Black Ops 2",
    "group": "",
    "status": "available",
    "keywords": "Black Ops II  ",
    "kind": "guide",
    "section": "Mob of the Dead",
    "label": "Guide",
    "url": "/guides/bo2-mob-of-the-dead",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo2-cell-block",
    "map": "bo2-cell-block",
    "game": "bo2",
    "gameName": "Black Ops 2",
    "group": "survival",
    "status": "available",
    "keywords": "Black Ops II  Grief",
    "kind": "guide",
    "section": "Cell Block",
    "label": "Guide",
    "url": "/guides/bo2-cell-block",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo2-buried",
    "map": "bo2-buried",
    "game": "bo2",
    "gameName": "Black Ops 2",
    "group": "",
    "status": "available",
    "keywords": "Black Ops II  ",
    "kind": "guide",
    "section": "Buried",
    "label": "Guide",
    "url": "/guides/bo2-buried",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo2-buried-signs",
    "map": "bo2-buried",
    "game": "bo2",
    "gameName": "Black Ops 2",
    "kind": "tool",
    "section": "Buried",
    "label": "Mine sign cipher matcher",
    "url": "/tools/bo2-buried-signs",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo2-buried-levers",
    "map": "bo2-buried",
    "game": "bo2",
    "gameName": "Black Ops 2",
    "kind": "tool",
    "section": "Buried",
    "label": "Maze lever order solver",
    "url": "/tools/bo2-buried-levers",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo2-buried-bells",
    "map": "bo2-buried",
    "game": "bo2",
    "gameName": "Black Ops 2",
    "kind": "tool",
    "section": "Buried",
    "label": "Mansion bell callouts",
    "url": "/tools/bo2-buried-bells",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo2-borough",
    "map": "bo2-borough",
    "game": "bo2",
    "gameName": "Black Ops 2",
    "group": "survival",
    "status": "available",
    "keywords": "Black Ops II  Grief / Turned",
    "kind": "guide",
    "section": "Borough",
    "label": "Guide",
    "url": "/guides/bo2-borough",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo2-origins",
    "map": "bo2-origins",
    "game": "bo2",
    "gameName": "Black Ops 2",
    "group": "",
    "status": "available",
    "keywords": "Black Ops II  ",
    "kind": "guide",
    "section": "Origins",
    "label": "Guide",
    "url": "/guides/bo2-origins",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo2-origins-ice",
    "map": "bo2-origins",
    "game": "bo2",
    "gameName": "Black Ops 2",
    "kind": "tool",
    "section": "Origins",
    "label": "Ice staff symbol matcher",
    "url": "/tools/bo2-origins-ice",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo2-origins-fire",
    "map": "bo2-origins",
    "game": "bo2",
    "gameName": "Black Ops 2",
    "kind": "tool",
    "section": "Origins",
    "label": "Fire staff torch decoder",
    "url": "/tools/bo2-origins-fire",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "waw-nacht-der-untoten",
    "map": "waw-nacht-der-untoten",
    "game": "waw",
    "gameName": "World at War",
    "group": "",
    "status": "available",
    "keywords": " Survival",
    "kind": "guide",
    "section": "Nacht der Untoten",
    "label": "Guide",
    "url": "/guides/waw-nacht-der-untoten",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "waw-verruckt",
    "map": "waw-verruckt",
    "game": "waw",
    "gameName": "World at War",
    "group": "",
    "status": "available",
    "keywords": " Survival",
    "kind": "guide",
    "section": "Verrückt",
    "label": "Guide",
    "url": "/guides/waw-verruckt",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "waw-shi-no-numa",
    "map": "waw-shi-no-numa",
    "game": "waw",
    "gameName": "World at War",
    "group": "",
    "status": "available",
    "keywords": " Survival",
    "kind": "guide",
    "section": "Shi No Numa",
    "label": "Guide",
    "url": "/guides/waw-shi-no-numa",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "waw-der-riese",
    "map": "waw-der-riese",
    "game": "waw",
    "gameName": "World at War",
    "group": "",
    "status": "available",
    "keywords": " Survival",
    "kind": "guide",
    "section": "Der Riese",
    "label": "Guide",
    "url": "/guides/waw-der-riese",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo1-nacht-der-untoten",
    "map": "bo1-nacht-der-untoten",
    "game": "bo1",
    "gameName": "Black Ops",
    "group": "",
    "status": "available",
    "keywords": "Black Ops 1  Survival",
    "kind": "guide",
    "section": "Nacht der Untoten",
    "label": "Guide",
    "url": "/guides/bo1-nacht-der-untoten",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo1-verruckt",
    "map": "bo1-verruckt",
    "game": "bo1",
    "gameName": "Black Ops",
    "group": "",
    "status": "available",
    "keywords": "Black Ops 1  Survival",
    "kind": "guide",
    "section": "Verrückt",
    "label": "Guide",
    "url": "/guides/bo1-verruckt",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo1-shi-no-numa",
    "map": "bo1-shi-no-numa",
    "game": "bo1",
    "gameName": "Black Ops",
    "group": "",
    "status": "available",
    "keywords": "Black Ops 1  Survival",
    "kind": "guide",
    "section": "Shi No Numa",
    "label": "Guide",
    "url": "/guides/bo1-shi-no-numa",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo1-der-riese",
    "map": "bo1-der-riese",
    "game": "bo1",
    "gameName": "Black Ops",
    "group": "",
    "status": "available",
    "keywords": "Black Ops 1  Survival",
    "kind": "guide",
    "section": "Der Riese",
    "label": "Guide",
    "url": "/guides/bo1-der-riese",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo1-kino-der-toten",
    "map": "bo1-kino-der-toten",
    "game": "bo1",
    "gameName": "Black Ops",
    "group": "",
    "status": "available",
    "keywords": "Black Ops 1  ",
    "kind": "guide",
    "section": "Kino der Toten",
    "label": "Guide",
    "url": "/guides/bo1-kino-der-toten",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo1-five",
    "map": "bo1-five",
    "game": "bo1",
    "gameName": "Black Ops",
    "group": "",
    "status": "available",
    "keywords": "Black Ops 1  ",
    "kind": "guide",
    "section": "Five",
    "label": "Guide",
    "url": "/guides/bo1-five",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo1-ascension",
    "map": "bo1-ascension",
    "game": "bo1",
    "gameName": "Black Ops",
    "group": "",
    "status": "available",
    "keywords": "Black Ops 1  ",
    "kind": "guide",
    "section": "Ascension",
    "label": "Guide",
    "url": "/guides/bo1-ascension",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo1-shangri-la",
    "map": "bo1-shangri-la",
    "game": "bo1",
    "gameName": "Black Ops",
    "group": "",
    "status": "available",
    "keywords": "Black Ops 1  ",
    "kind": "guide",
    "section": "Shangri-La",
    "label": "Guide",
    "url": "/guides/bo1-shangri-la",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo1-shang-locations",
    "map": "bo1-shangri-la",
    "game": "bo1",
    "gameName": "Black Ops",
    "kind": "tool",
    "section": "Shangri-La",
    "label": "Wall tile & mud-dial finder",
    "url": "/tools/bo1-shang-locations",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo1-shang-tiles",
    "map": "bo1-shangri-la",
    "game": "bo1",
    "gameName": "Black Ops",
    "kind": "tool",
    "section": "Shangri-La",
    "label": "Matching tile symbol notebook",
    "url": "/tools/bo1-shang-tiles",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo1-shang-gongs",
    "map": "bo1-shangri-la",
    "game": "bo1",
    "gameName": "Black Ops",
    "kind": "tool",
    "section": "Shangri-La",
    "label": "Gong locations & match notes",
    "url": "/tools/bo1-shang-gongs",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo1-moon",
    "map": "bo1-moon",
    "game": "bo1",
    "gameName": "Black Ops",
    "group": "",
    "status": "available",
    "keywords": "Black Ops 1  ",
    "kind": "guide",
    "section": "Moon",
    "label": "Guide",
    "url": "/guides/bo1-moon",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo1-moon-labs",
    "map": "bo1-moon",
    "game": "bo1",
    "gameName": "Black Ops",
    "kind": "tool",
    "section": "Moon",
    "label": "Hacker panel & cable finder",
    "url": "/tools/bo1-moon-labs",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo1-moon-simon",
    "map": "bo1-moon",
    "game": "bo1",
    "gameName": "Black Ops",
    "kind": "tool",
    "section": "Moon",
    "label": "Samantha Says sequence recorder",
    "url": "/tools/bo1-moon-simon",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo1-call-of-the-dead",
    "map": "bo1-call-of-the-dead",
    "game": "bo1",
    "gameName": "Black Ops",
    "group": "",
    "status": "available",
    "keywords": "Black Ops 1  ",
    "kind": "guide",
    "section": "Call of the Dead",
    "label": "Guide",
    "url": "/guides/bo1-call-of-the-dead",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "bo1-cotd-dials",
    "map": "bo1-call-of-the-dead",
    "game": "bo1",
    "gameName": "Black Ops",
    "kind": "tool",
    "section": "Call of the Dead",
    "label": "Lighthouse dial solver",
    "url": "/tools/bo1-cotd-dials",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo1-cotd-locations",
    "map": "bo1-call-of-the-dead",
    "game": "bo1",
    "gameName": "Black Ops",
    "kind": "tool",
    "section": "Call of the Dead",
    "label": "Quest item & location finder",
    "url": "/tools/bo1-cotd-locations",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "bo1-dead-ops-arcade",
    "map": "bo1-dead-ops-arcade",
    "game": "bo1",
    "gameName": "Black Ops",
    "group": "",
    "status": "available",
    "keywords": "Black Ops 1  Arcade",
    "kind": "guide",
    "section": "Dead Ops Arcade",
    "label": "Guide",
    "url": "/guides/bo1-dead-ops-arcade",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "iw-zombies-in-spaceland",
    "map": "iw-zombies-in-spaceland",
    "game": "iw",
    "gameName": "Infinite Warfare",
    "group": "",
    "status": "available",
    "keywords": "Launch map Round-based Zombies",
    "kind": "guide",
    "section": "Zombies in Spaceland",
    "label": "Guide",
    "url": "/guides/iw-zombies-in-spaceland",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "iw-spaceland-speakers",
    "map": "iw-zombies-in-spaceland",
    "game": "iw",
    "gameName": "Infinite Warfare",
    "kind": "tool",
    "section": "Zombies in Spaceland",
    "label": "Spaceland speaker sequence",
    "url": "/tools/iw-spaceland-speakers",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "iw-spaceland-souvenirs",
    "map": "iw-zombies-in-spaceland",
    "game": "iw",
    "gameName": "Infinite Warfare",
    "kind": "tool",
    "section": "Zombies in Spaceland",
    "label": "Souvenir recipe lookup",
    "url": "/tools/iw-spaceland-souvenirs",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "iw-rave-in-the-redwoods",
    "map": "iw-rave-in-the-redwoods",
    "game": "iw",
    "gameName": "Infinite Warfare",
    "group": "",
    "status": "available",
    "keywords": "Sabotage Round-based Zombies",
    "kind": "guide",
    "section": "Rave in the Redwoods",
    "label": "Guide",
    "url": "/guides/iw-rave-in-the-redwoods",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "iw-shaolin-shuffle",
    "map": "iw-shaolin-shuffle",
    "game": "iw",
    "gameName": "Infinite Warfare",
    "group": "",
    "status": "available",
    "keywords": "Continuum Round-based Zombies",
    "kind": "guide",
    "section": "Shaolin Shuffle",
    "label": "Guide",
    "url": "/guides/iw-shaolin-shuffle",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "iw-shaolin-morse",
    "map": "iw-shaolin-shuffle",
    "game": "iw",
    "gameName": "Infinite Warfare",
    "kind": "tool",
    "section": "Shaolin Shuffle",
    "label": "Nightmare Summer phone Morse",
    "url": "/tools/iw-shaolin-morse",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "iw-shaolin-word",
    "map": "iw-shaolin-shuffle",
    "game": "iw",
    "gameName": "Infinite Warfare",
    "kind": "tool",
    "section": "Shaolin Shuffle",
    "label": "Rooftop word candidates",
    "url": "/tools/iw-shaolin-word",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "iw-attack-of-the-radioactive-thing",
    "map": "iw-attack-of-the-radioactive-thing",
    "game": "iw",
    "gameName": "Infinite Warfare",
    "group": "",
    "status": "available",
    "keywords": "Absolution Round-based Zombies",
    "kind": "guide",
    "section": "Attack of the Radioactive Thing",
    "label": "Guide",
    "url": "/guides/iw-attack-of-the-radioactive-thing",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "iw-attack-chemistry",
    "map": "iw-attack-of-the-radioactive-thing",
    "game": "iw",
    "gameName": "Infinite Warfare",
    "kind": "tool",
    "section": "Attack of the Radioactive Thing",
    "label": "Radioactive Thing chemistry",
    "url": "/tools/iw-attack-chemistry",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "iw-attack-codes",
    "map": "iw-attack-of-the-radioactive-thing",
    "game": "iw",
    "gameName": "Infinite Warfare",
    "kind": "tool",
    "section": "Attack of the Radioactive Thing",
    "label": "Life ray, pressure and bomb memory",
    "url": "/tools/iw-attack-codes",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "iw-attack-skull-hop",
    "map": "iw-attack-of-the-radioactive-thing",
    "game": "iw",
    "gameName": "Infinite Warfare",
    "kind": "tool",
    "section": "Attack of the Radioactive Thing",
    "label": "Skull Hop spelling solver",
    "url": "/tools/iw-attack-skull-hop",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "iw-the-beast-from-beyond",
    "map": "iw-the-beast-from-beyond",
    "game": "iw",
    "gameName": "Infinite Warfare",
    "group": "",
    "status": "available",
    "keywords": "Mephistopheles Directors Cut super easter egg Retribution Round-based Zombies",
    "kind": "guide",
    "section": "The Beast from Beyond",
    "label": "Guide",
    "url": "/guides/iw-the-beast-from-beyond",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "iw-beast-disks",
    "map": "iw-the-beast-from-beyond",
    "game": "iw",
    "gameName": "Infinite Warfare",
    "kind": "tool",
    "section": "The Beast from Beyond",
    "label": "N31L disk order",
    "url": "/tools/iw-beast-disks",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "iw-beast-handles",
    "map": "iw-the-beast-from-beyond",
    "game": "iw",
    "gameName": "Infinite Warfare",
    "kind": "tool",
    "section": "The Beast from Beyond",
    "label": "N31L handle snapshots",
    "url": "/tools/iw-beast-handles",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "iw-beast-queens",
    "map": "iw-the-beast-from-beyond",
    "game": "iw",
    "gameName": "Infinite Warfare",
    "kind": "tool",
    "section": "The Beast from Beyond",
    "label": "Skullbreaker eight queens",
    "url": "/tools/iw-beast-queens",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "ww2-the-final-reich",
    "map": "ww2-the-final-reich",
    "game": "ww2",
    "gameName": "WWII",
    "group": "",
    "status": "available",
    "keywords": "WW2 World War II World War 2 Launch map Round-based Zombies",
    "kind": "guide",
    "section": "The Final Reich",
    "label": "Guide",
    "url": "/guides/ww2-the-final-reich",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "ww2-final-reich-grid",
    "map": "ww2-the-final-reich",
    "game": "ww2",
    "gameName": "WWII",
    "kind": "tool",
    "section": "The Final Reich",
    "label": "Power-grid route",
    "url": "/tools/ww2-final-reich-grid",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "ww2-final-reich-voice",
    "map": "ww2-the-final-reich",
    "game": "ww2",
    "gameName": "WWII",
    "kind": "tool",
    "section": "The Final Reich",
    "label": "Bird numerals & second voices",
    "url": "/tools/ww2-final-reich-voice",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "ww2-groesten-haus",
    "map": "ww2-groesten-haus",
    "game": "ww2",
    "gameName": "WWII",
    "group": "",
    "status": "available",
    "keywords": "WW2 World War II World War 2 Groesten Haus Grosten Haus Prologue Bonus map Survival",
    "kind": "guide",
    "section": "Groesten Haus",
    "label": "Guide",
    "url": "/guides/ww2-groesten-haus",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "ww2-the-darkest-shore",
    "map": "ww2-the-darkest-shore",
    "game": "ww2",
    "gameName": "WWII",
    "group": "",
    "status": "available",
    "keywords": "WW2 World War II World War 2 The Resistance Round-based Zombies",
    "kind": "guide",
    "section": "The Darkest Shore",
    "label": "Guide",
    "url": "/guides/ww2-the-darkest-shore",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "ww2-darkest-artillery",
    "map": "ww2-the-darkest-shore",
    "game": "ww2",
    "gameName": "WWII",
    "kind": "tool",
    "section": "The Darkest Shore",
    "label": "Cannon coordinates & destroyer chart",
    "url": "/tools/ww2-darkest-artillery",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "ww2-the-shadowed-throne",
    "map": "ww2-the-shadowed-throne",
    "game": "ww2",
    "gameName": "WWII",
    "group": "",
    "status": "available",
    "keywords": "WW2 World War II World War 2 The War Machine Round-based Zombies",
    "kind": "guide",
    "section": "The Shadowed Throne",
    "label": "Guide",
    "url": "/guides/ww2-the-shadowed-throne",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "ww2-shadowed-radio",
    "map": "ww2-the-shadowed-throne",
    "game": "ww2",
    "gameName": "WWII",
    "kind": "tool",
    "section": "The Shadowed Throne",
    "label": "Church radio-frequency lookup",
    "url": "/tools/ww2-shadowed-radio",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "ww2-shadowed-statues",
    "map": "ww2-the-shadowed-throne",
    "game": "ww2",
    "gameName": "WWII",
    "kind": "tool",
    "section": "The Shadowed Throne",
    "label": "Raven statue wall solver",
    "url": "/tools/ww2-shadowed-statues",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "ww2-shadowed-safe",
    "map": "ww2-the-shadowed-throne",
    "game": "ww2",
    "gameName": "WWII",
    "kind": "tool",
    "section": "The Shadowed Throne",
    "label": "Clown counts → safe directions",
    "url": "/tools/ww2-shadowed-safe",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "ww2-shadowed-axe",
    "map": "ww2-the-shadowed-throne",
    "game": "ww2",
    "gameName": "WWII",
    "kind": "tool",
    "section": "The Shadowed Throne",
    "label": "Axe Morse decoder & map",
    "url": "/tools/ww2-shadowed-axe",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "ww2-shadowed-hangman",
    "map": "ww2-the-shadowed-throne",
    "game": "ww2",
    "gameName": "WWII",
    "kind": "tool",
    "section": "The Shadowed Throne",
    "label": "Cabaret Hangman candidates",
    "url": "/tools/ww2-shadowed-hangman",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "ww2-into-the-storm",
    "map": "ww2-into-the-storm",
    "game": "ww2",
    "gameName": "WWII",
    "group": "",
    "status": "available",
    "keywords": "WW2 World War II World War 2 Bodega Cervantes Tortured Path story chapter Objective-based chapter",
    "kind": "guide",
    "section": "Into the Storm",
    "label": "Guide",
    "url": "/guides/ww2-into-the-storm",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "ww2-across-the-depths",
    "map": "ww2-across-the-depths",
    "game": "ww2",
    "gameName": "WWII",
    "group": "",
    "status": "available",
    "keywords": "WW2 World War II World War 2 USS Mount Olympus Tortured Path story chapter Objective-based chapter",
    "kind": "guide",
    "section": "Across the Depths",
    "label": "Guide",
    "url": "/guides/ww2-across-the-depths",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "ww2-beneath-the-ice",
    "map": "ww2-beneath-the-ice",
    "game": "ww2",
    "gameName": "WWII",
    "group": "",
    "status": "available",
    "keywords": "WW2 World War II World War 2 Altar of Blood Tortured Path story chapter Objective-based chapter",
    "kind": "guide",
    "section": "Beneath the Ice",
    "label": "Guide",
    "url": "/guides/ww2-beneath-the-ice",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "ww2-tortured-runes",
    "map": "ww2-beneath-the-ice",
    "game": "ww2",
    "gameName": "WWII",
    "kind": "tool",
    "section": "Beneath the Ice",
    "label": "Three-stage rune code memory",
    "url": "/tools/ww2-tortured-runes",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "ww2-bodega-cervantes",
    "map": "ww2-bodega-cervantes",
    "game": "ww2",
    "gameName": "WWII",
    "group": "",
    "status": "available",
    "keywords": "WW2 World War II World War 2 Into the Storm Tortured Path survival Survival",
    "kind": "guide",
    "section": "Bodega Cervantes",
    "label": "Guide",
    "url": "/guides/ww2-bodega-cervantes",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "ww2-uss-mount-olympus",
    "map": "ww2-uss-mount-olympus",
    "game": "ww2",
    "gameName": "WWII",
    "group": "",
    "status": "available",
    "keywords": "WW2 World War II World War 2 USS Mount Olympus Across the Depths Tortured Path survival Survival",
    "kind": "guide",
    "section": "U.S.S. Mount Olympus",
    "label": "Guide",
    "url": "/guides/ww2-uss-mount-olympus",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "ww2-altar-of-blood",
    "map": "ww2-altar-of-blood",
    "game": "ww2",
    "gameName": "WWII",
    "group": "",
    "status": "available",
    "keywords": "WW2 World War II World War 2 Beneath the Ice Tortured Path survival Survival",
    "kind": "guide",
    "section": "Altar of Blood",
    "label": "Guide",
    "url": "/guides/ww2-altar-of-blood",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "ww2-the-frozen-dawn",
    "map": "ww2-the-frozen-dawn",
    "game": "ww2",
    "gameName": "WWII",
    "group": "",
    "status": "available",
    "keywords": "WW2 World War II World War 2 Shadow War Round-based Zombies",
    "kind": "guide",
    "section": "The Frozen Dawn",
    "label": "Guide",
    "url": "/guides/ww2-the-frozen-dawn",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "ww2-frozen-hammer",
    "map": "ww2-the-frozen-dawn",
    "game": "ww2",
    "gameName": "WWII",
    "kind": "tool",
    "section": "The Frozen Dawn",
    "label": "Base Hammer pillar solver",
    "url": "/tools/ww2-frozen-hammer",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "ww2-frozen-shield",
    "map": "ww2-the-frozen-dawn",
    "game": "ww2",
    "gameName": "WWII",
    "kind": "tool",
    "section": "The Frozen Dawn",
    "label": "Shield pool pattern memory",
    "url": "/tools/ww2-frozen-shield",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "ww2-frozen-orrery",
    "map": "ww2-the-frozen-dawn",
    "game": "ww2",
    "gameName": "WWII",
    "kind": "tool",
    "section": "The Frozen Dawn",
    "label": "Orrery target memory",
    "url": "/tools/ww2-frozen-orrery",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "aw-outbreak",
    "map": "aw-outbreak",
    "game": "aw",
    "gameName": "Advanced Warfare",
    "group": "",
    "status": "available",
    "keywords": "Exo Zombies Havoc Exo Zombies",
    "kind": "guide",
    "section": "Outbreak",
    "label": "Guide",
    "url": "/guides/aw-outbreak",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "aw-infection",
    "map": "aw-infection",
    "game": "aw",
    "gameName": "Advanced Warfare",
    "group": "",
    "status": "available",
    "keywords": "Exo Zombies Burger Town Ascendance Exo Zombies",
    "kind": "guide",
    "section": "Infection",
    "label": "Guide",
    "url": "/guides/aw-infection",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "aw-carrier",
    "map": "aw-carrier",
    "game": "aw",
    "gameName": "Advanced Warfare",
    "group": "",
    "status": "available",
    "keywords": "Exo Zombies Supremacy Exo Zombies",
    "kind": "guide",
    "section": "Carrier",
    "label": "Guide",
    "url": "/guides/aw-carrier",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "aw-descent",
    "map": "aw-descent",
    "game": "aw",
    "gameName": "Advanced Warfare",
    "group": "",
    "status": "available",
    "keywords": "Exo Zombies Reckoning Exo Zombies",
    "kind": "guide",
    "section": "Descent",
    "label": "Guide",
    "url": "/guides/aw-descent",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "aw-descent-simon",
    "map": "aw-descent",
    "game": "aw",
    "gameName": "Advanced Warfare",
    "kind": "tool",
    "section": "Descent",
    "label": "Reception Simon Says",
    "url": "/tools/aw-descent-simon",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "aw-descent-numbers",
    "map": "aw-descent",
    "game": "aw",
    "gameName": "Advanced Warfare",
    "kind": "tool",
    "section": "Descent",
    "label": "Number panel action planner",
    "url": "/tools/aw-descent-numbers",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "vanguard-der-anfang",
    "map": "vanguard-der-anfang",
    "game": "vanguard",
    "gameName": "Vanguard",
    "group": "",
    "status": "available",
    "keywords": "VG Launch map Objective-based",
    "kind": "guide",
    "section": "Der Anfang",
    "label": "Guide",
    "url": "/guides/vanguard-der-anfang",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "vanguard-terra-maledicta",
    "map": "vanguard-terra-maledicta",
    "game": "vanguard",
    "gameName": "Vanguard",
    "group": "",
    "status": "available",
    "keywords": "VG Season 2 Objective-based",
    "kind": "guide",
    "section": "Terra Maledicta",
    "label": "Guide",
    "url": "/guides/vanguard-terra-maledicta",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "vanguard-terra-pages",
    "map": "vanguard-terra-maledicta",
    "game": "vanguard",
    "gameName": "Vanguard",
    "kind": "tool",
    "section": "Terra Maledicta",
    "label": "Lost Tome page order",
    "url": "/tools/vanguard-terra-pages",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "vanguard-shi-no-numa",
    "map": "vanguard-shi-no-numa",
    "game": "vanguard",
    "gameName": "Vanguard",
    "group": "",
    "status": "available",
    "keywords": "VG Shi No Numa Reborn SNN Season 4 Round-based",
    "kind": "guide",
    "section": "Shi No Numa",
    "label": "Guide",
    "url": "/guides/vanguard-shi-no-numa",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "vanguard-shi-no-numa-cipher",
    "map": "vanguard-shi-no-numa",
    "game": "vanguard",
    "gameName": "Vanguard",
    "kind": "tool",
    "section": "Shi No Numa",
    "label": "Monolith paper translator",
    "url": "/tools/vanguard-shi-no-numa-cipher",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "vanguard-the-archon",
    "map": "vanguard-the-archon",
    "game": "vanguard",
    "gameName": "Vanguard",
    "group": "",
    "status": "available",
    "keywords": "VG Season 5 Round-based",
    "kind": "guide",
    "section": "The Archon",
    "label": "Guide",
    "url": "/guides/vanguard-the-archon",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "vanguard-archon-runes",
    "map": "vanguard-the-archon",
    "game": "vanguard",
    "gameName": "Vanguard",
    "kind": "tool",
    "section": "The Archon",
    "label": "Mindfulness rune sequence",
    "url": "/tools/vanguard-archon-runes",
    "accel": null,
    "icon": "↗"
  },
  {
    "id": "mw3-urzikstan",
    "map": "mw3-urzikstan",
    "game": "mw3",
    "gameName": "Modern Warfare III (2023)",
    "group": "",
    "status": "available",
    "keywords": "MW3 MWIII MWZ Modern Warfare 3 Operation Deadbolt MWZ Operation Deadbolt Red Worm Greylorm free perks chess vault Dark Aether portals interactive map Modern Warfare III (2023) Open-world deployment",
    "kind": "guide",
    "section": "Urzikstan",
    "label": "Guide",
    "url": "/guides/mw3-urzikstan",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "mw3-dark-aether-season-1",
    "map": "mw3-dark-aether-season-1",
    "game": "mw3",
    "gameName": "Modern Warfare III (2023)",
    "group": "",
    "status": "available",
    "keywords": "MW3 MWIII MWZ Modern Warfare 3 Operation Deadbolt Al Bagra Fortress Bad Signal interactive map Modern Warfare III (2023) Dark Aether",
    "kind": "guide",
    "section": "Dark Aether — Season 1",
    "label": "Guide",
    "url": "/guides/mw3-dark-aether-season-1",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "mw3-dark-aether-season-2",
    "map": "mw3-dark-aether-season-2",
    "game": "mw3",
    "gameName": "Modern Warfare III (2023)",
    "group": "",
    "status": "available",
    "keywords": "MW3 MWIII MWZ Modern Warfare 3 Operation Deadbolt Sa’id City Said City Countermeasures interactive map Modern Warfare III (2023) Dark Aether",
    "kind": "guide",
    "section": "Dark Aether — Season 2",
    "label": "Guide",
    "url": "/guides/mw3-dark-aether-season-2",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "mw3-dark-aether-season-3",
    "map": "mw3-dark-aether-season-3",
    "game": "mw3",
    "gameName": "Modern Warfare III (2023)",
    "group": "",
    "status": "available",
    "keywords": "MW3 MWIII MWZ Modern Warfare 3 Operation Deadbolt Zarqwa Hydroelectric Union interactive map Modern Warfare III (2023) Dark Aether",
    "kind": "guide",
    "section": "Dark Aether — Season 3",
    "label": "Guide",
    "url": "/guides/mw3-dark-aether-season-3",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "mw3-unstable-rift",
    "map": "mw3-unstable-rift",
    "game": "mw3",
    "gameName": "Modern Warfare III (2023)",
    "group": "",
    "status": "available",
    "keywords": "MW3 MWIII MWZ Modern Warfare 3 Operation Deadbolt Modern Warfare III (2023) Five-phase arena",
    "kind": "guide",
    "section": "Unstable Rift",
    "label": "Guide",
    "url": "/guides/mw3-unstable-rift",
    "accel": null,
    "icon": "◇"
  },
  {
    "id": "mw3-dark-aether-season-5",
    "map": "mw3-dark-aether-season-5",
    "game": "mw3",
    "gameName": "Modern Warfare III (2023)",
    "group": "",
    "status": "available",
    "keywords": "MW3 MWIII MWZ Modern Warfare 3 Operation Deadbolt Highrise Al Mazrah City Ascension interactive map Modern Warfare III (2023) Dark Aether",
    "kind": "guide",
    "section": "Dark Aether — Season 5",
    "label": "Guide",
    "url": "/guides/mw3-dark-aether-season-5",
    "accel": null,
    "icon": "◇"
  }
]
const NAV_GAMES = [
  {
    "id": "bo7",
    "name": "Black Ops 7",
    "shortName": "BO7",
    "aliases": [
      "Black Ops VII"
    ],
    "planned": false
  },
  {
    "id": "bo6",
    "name": "Black Ops 6",
    "shortName": "BO6",
    "aliases": [
      "Black Ops VI"
    ],
    "planned": false
  },
  {
    "id": "cw",
    "name": "Black Ops Cold War",
    "shortName": "Cold War",
    "aliases": [
      "BOCW"
    ],
    "planned": false
  },
  {
    "id": "bo4",
    "name": "Black Ops 4",
    "shortName": "BO4",
    "aliases": [
      "Black Ops IV"
    ],
    "planned": false
  },
  {
    "id": "bo3",
    "name": "Black Ops 3",
    "shortName": "BO3",
    "aliases": [
      "Black Ops III"
    ],
    "planned": false
  },
  {
    "id": "bo2",
    "name": "Black Ops 2",
    "shortName": "BO2",
    "aliases": [
      "Black Ops II"
    ],
    "planned": false
  },
  {
    "id": "bo1",
    "name": "Black Ops",
    "shortName": "BO1",
    "aliases": [
      "Black Ops 1"
    ],
    "planned": false
  },
  {
    "id": "waw",
    "name": "World at War",
    "shortName": "WaW",
    "aliases": [],
    "planned": false
  },
  {
    "id": "iw",
    "name": "Infinite Warfare",
    "shortName": "IW",
    "aliases": [],
    "planned": false
  },
  {
    "id": "ww2",
    "name": "WWII",
    "shortName": "WWII",
    "aliases": [
      "WW2",
      "World War II",
      "World War 2"
    ],
    "planned": false
  },
  {
    "id": "aw",
    "name": "Advanced Warfare",
    "shortName": "AW",
    "aliases": [
      "Exo Zombies"
    ],
    "planned": false
  },
  {
    "id": "vanguard",
    "name": "Vanguard",
    "shortName": "Vanguard",
    "aliases": [
      "VG"
    ],
    "planned": false
  },
  {
    "id": "mw3",
    "name": "Modern Warfare III (2023)",
    "shortName": "MWIII",
    "aliases": [
      "MW3",
      "MWIII",
      "MWZ",
      "Modern Warfare 3",
      "Operation Deadbolt"
    ],
    "planned": false
  }
]
const SYSTEM_ACTIONS = [
  {
    "id": "sys-settings",
    "label": "Open Settings",
    "accel": "Ctrl+,"
  },
  {
    "id": "sys-home",
    "label": "Go Home",
    "accel": "Ctrl+H"
  },
  {
    "id": "sys-reload",
    "label": "Reload Page",
    "accel": "F5"
  },
  {
    "id": "sys-back",
    "label": "Back",
    "accel": "Alt+ArrowLeft"
  },
  {
    "id": "sys-forward",
    "label": "Forward",
    "accel": "Alt+ArrowRight"
  },
  {
    "id": "sys-zoom-in",
    "label": "Zoom In",
    "accel": "Ctrl+="
  },
  {
    "id": "sys-zoom-out",
    "label": "Zoom Out",
    "accel": "Ctrl+-"
  },
  {
    "id": "sys-zoom-reset",
    "label": "Zoom Reset",
    "accel": "Ctrl+0"
  },
  {
    "id": "sys-devtools",
    "label": "Toggle DevTools",
    "accel": "F12"
  }
]
if (typeof window !== 'undefined') { window.NAV = NAV; window.NAV_GAMES = NAV_GAMES; window.SYSTEM_ACTIONS = SYSTEM_ACTIONS }
if (typeof module !== 'undefined') { module.exports = NAV; module.exports.games = NAV_GAMES; module.exports.SYSTEM_ACTIONS = SYSTEM_ACTIONS }
