<!-- AUTO-GENERATED by scripts/convert-guides.mjs from public/guides/astra-malorum.html -->
<template>
<p class="g-hint">💡 Tap a section title to collapse or expand it.</p>



<h1 id="wiki_astra_malorum_.7C_complete_map_breakdown">Astra Malorum | Complete Map Breakdown</h1>
<p>This guide is broken down into <strong>Chapters</strong> and <strong>Topics</strong>, a Chapter defines the content of the Topics to make all of the guides easier to navigate and read.</p>
<p>On PC, there is a list of all the <strong>Chapters</strong> on the right. Just click on the text and the site will take you there. Alternatively, to find specific information, press <strong>CTRL + F</strong> and type the information you want to find. On mobile, the list of all the <strong>Chapters and Topics</strong> is at the top of the page.</p>
<p style="text-align: center;"><strong><img alt="" class="wiki-img-none wiki-img-no-wrap wiki-img-in-table" data-height="1080" data-media-id="vrzo1oc0lu2g1" data-width="1920" height="1080" width="1920" src="https://preview.redd.it/vrzo1oc0lu2g1.png?width=1920&height=1080&format=png&auto=webp&s=e145b9a50f89d4e6bd00fe457ab19f394af88af5"></strong></p>
<p style="text-align: center;"><strong><em>In the cold depths of space, a century-old observatory guards a gateway to a dead world. Awaken the astronomer, defeat the mechanical guard, and liberate the celestial Shadowsmith!</em></strong></p>
<hr>
<h1 id="wiki_key_features">Key Features</h1>
<p>This is a walkthrough of the key features of the map, such as Pack-a-Punch, Wonder Weapons, etc.</p>
<div class="glass-card glass-gold"><h2 id="wiki_pack.2Da.2Dpunch"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Pack-a-Punch<span class="g-tag">🌀 Pack-a-Punch</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<ol>
<li>TBD</li>
</ol></div>
<div class="glass-card glass-amber"><h2 id="wiki_lgm.2D1"><label class="g-toggle"><input type="checkbox" class="g-cb" checked><span class="g-title">LGM-1<span class="g-tag">🔫 LGM-1</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<ol>
<li>Collect several items:
<ol>
<li>Destroy one of O.S.C.A.R. flying drones to obtain the Damaged Drone.</li>
<li>Find a blinking lamp post around the map and shoot it to drop the Aberrant Wiring.</li>
<li>Equipped with a Pack-a-Punched gun, shoot the gearbox of Ol' Tessie in Crash Site to collect the Car Battery.</li>
<li>With Cryofreeze equipped, find and shoot an Aether Crystal around the map to drop an Absolute Zero Shard. You need to collect a total of 3 shards.</li>
</ol>
</li>
<li>Kill O.S.C.A.R. using three different traps. <strong>This can be done in any order, but only one can be done per round.</strong>
<ol>
<li>Place the Absolute Zero Shard inside the rocket thrusters in Museum Infinitum. If done correctly, a countdown will be heard. Activate the trap and bring O.S.C.A.R. to the rocket thrusters to kill it.<img alt="" class="wiki-img-right wiki-img-with-wrap wiki-img-in-table" data-height="930" data-media-id="zpff20px6g5g1" data-width="855" height="256" width="235" src="https://preview.redd.it/zpff20px6g5g1.png?width=320&height=348&format=png&auto=webp&s=41036b5a09afab96e073db914c3f7a10488cc958"></li>
<li>Place the Damaged Drone, Car Battery and Aberrant Wiring inside the trap at the Luminarium to enable the Electro-Volt Projector. Bring O.S.C.A.R. inside the room and interact with the trap to kill it. Players have to hold O.S.C.A.R. within the room until it overheats and explodes. Purple-eyed zombies will also spawn during this step.</li>
<li>Inside the Observatory Dome, find and shoot at 5 fuming valves around the room within a limited time. If done correctly, the telescope will start moving.
<ul>
<li>Two are located above the telescope.</li>
<li>Two are located under the telescope.</li>
<li>Three are located on the walls inside the room.</li>
<li>One is located on a pillar behind a sparking box.</li>
<li>One is located in the small room when coming from Machina Astralis</li>
</ul>
</li>
<li>Bring O.S.C.A.R. beneath the telescope and interact with the organ in front of the Pack-a-Punch machine. A screen will appear and you'll need to place the cursor on the Sun to activate the trap. Make sure O.S.C.A.R. stays within the laser beam to kill it.</li>
</ol>
</li>
</ol>
<ol>
<li>Once all three traps are done, the final O.S.C.A.R. killed will drop the LGM-1.</li>
</ol>
<hr>
</div><h1 id="wiki_leads">Leads</h1>
<ul>
<li>The Stellar Dissector can be found next to the trap in Luminarium</li>
<li>5 Grandfather clocks can be meleed to pixelate your vision and slow down time.</li>
</ul>
<hr>
<h1 id="wiki_main_quest">Main Quest</h1>
<p><em>Full walkthrough of the Astra Malorum main quest. For a condensed step-by-step version, see the <a href="#wiki_main_quest_cheat_sheet">Main Quest Cheat Sheet</a> below.</em></p>
<ol>
<li><strong>Acquire the LGM-1</strong> (see Key Features for the full trap sequence).</li>
<li><strong>Starting at Round 10</strong>, stay behind O.S.C.A.R. and follow it until it plays a recording, during which Dr. Thurston will recite the name of three planets. Turn the planets into numbers based on their distance from the Sun (Mercury = 1, Venus = 2, ... Neptune = 8). <a href="/tools/astra-mars-code" target="_blank" rel="noopener" style="color:#fcd34d;font-weight:700">🧮 code solver</a></li>
<li>Travel to the Observatory Dome and enter the 3-digit code into the terminal. If done correctly, a lift will drop down next to the Pack-a-Punch.</li>
<li>Retrieve the key from the corpse on the lift, then travel to Machina Astralis and interact with the cryopod located in the adjacent room leading to Scholar&rsquo;s Way. The pod will open, revealing Dr. Thurston&rsquo;s corpse. <strong>Note that this will summon O.S.C.A.R. and spawn several zombies to your location.</strong></li>
<li>Travel to Museum Infinitum and find the Rock Saw located behind a glass display; shoot the glass to pick it up. Return to the cryopod and interact with the corpse to collect Thurston&rsquo;s brain. <strong>You can pick up the Rock Saw before Step 4. Once the cryopod is opened, hold interact on Thurston&rsquo;s head to collect his brain &mdash; you will be immune to damage during the process.</strong></li>
<li>Travel to The Luminarium and interact with the brain jar on the table to replace the monkey brain with Thurston&rsquo;s brain. Interact once more, and this will trigger a short lockdown where you need to defend the brain.</li>
<li>Pick the brain jar up and place it in the machine near the portal in Machina Astralis. <strong>Holding the jar will slow you down.</strong> Hold interact on the machine to connect the jar to it. If done correctly, the machine will power up and display a list of book titles on the left screen (9 possible titles).</li>
<li>Go to the Archive of Orbis. Inside the room there are three busts, each with a set of 3 bookshelves beside it. Interacting with each bookshelf displays one of the book titles. Find the book titles shown by the machine, then <strong>as fast as possible</strong>, interact with each bust as many times as the number of matching titles found in its set of shelves. <em>Example: if the machine shows The Black Veil, Echoes of Andromeda, Witchlight Codex, Silence at Singularity, interact with bust 1 once, bust 2 once, bust 3 twice.</em></li>
<li>If done correctly, a panel will open above the ladder in the room. Climb it to retrieve the Neptune model and place it in the display at the top of Machina Astralis.</li>
<li>Find three pages around the map; each page shows a random planet (e.g. Mars) and a random direction (e.g. NE): one on a table in The Luminarium (same room as the Stellar Dissector trap), one on a desk in Machina Astralis, one on the large table in Archive of Orbis.</li>
<li>Shoot the corresponding planets (Mars, Saturn, Neptune) on the model display to align each in the direction from the notes. <strong>The compass showing the directions is below the Sun model.</strong> <a href="/tools/astra-planet-sheets" target="_blank" rel="noopener" style="color:#fcd34d;font-weight:700">🧮 compass solver</a></li>
<li>Travel to the Observatory Dome and interact with the telescope. Look for Mars and note its declination (DEC) &mdash; this corresponds to a 4-digit code.</li>
<li>On the second floor of Machina Astralis, enter the code into the machine. If done correctly, Thurston will acknowledge the successful code input.</li>
<li>Interact with the machine to reboot the portal. This spawns O.S.C.A.R., who constantly launches flying saucers at the portal to damage it. Destroy the saucers and defend the portal until it finishes rebooting &mdash; if it takes too much damage before the timer runs out, the step fails. If done correctly, you will be teleported to Mars automatically.</li>
<li>While on Mars, pick up Thurston&rsquo;s brain jar in the center of the arena and place it in the machine at the top of the stairs. Interact with it to create a portal. (Step 6 of the cheat sheet can be done as you create the portal.)</li>
<li>Interact with the machine to play music (once per round). When the music plays, the Ascendant Eye will be seen flying near the giant head outside the map.</li>
<li>Shoot the four pylons outside the map in order: <strong>Back Right, Back Left, Front Right, Front Left</strong>, then the pylon above the machine on top of the temple to bring the Ascendant Eye into the arena. <strong>Shooting the temple pylon repeatedly keeps the music playing, forcing the Ascendant Eye to stay.</strong></li>
<li>Wait for the Ascendant Eye to fly low in the arena, then jump and interact to grab it. <strong>Easier with low gravity enabled.</strong></li>
<li>Place the Ascendant Eye in the device on the right side of the arena. With the LGM-1, shoot the antennas on the five pillars around the arena &mdash; each plays a note and displays a symbol on its pillar.</li>
<li>Back in the Observatory Dome, interact with the organ. The screen on the right displays the five symbols in order, with one hidden behind distorted wave lines. <strong>This step can be done immediately after unlocking Pack-a-Punch.</strong></li>
<li>Return to Mars and interact with the pillars in the order shown on the organ&rsquo;s screen, inserting the missing symbol where indicated. If done correctly, the screen brightens and a quote from Thurston plays.</li>
<li>Interact with the machine at the top of the stairs to start the fight against <strong>Caltheris</strong>.</li>
</ol>
<div class="glass-card glass-red glass-boss"><h2 id="wiki_caltheris_boss_fight"><label class="g-toggle"><input type="checkbox" class="g-cb" checked><span class="g-title">Caltheris Boss Fight<span class="g-tag">⚔️ BOSS</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<ol>
<li><strong>Phase 1</strong> &mdash; Kill zombies while dodging Caltheris&rsquo;s lasers to charge the Tesla coil on the right side of the arena. Once fully charged, interact with the machine at the top of the stairs to fire a beam, instantly draining 1/3 of her health bar. Repeat two more times. After each successful attack, Caltheris gains a new attack: meteors covering an area in flames, or toxic gas on the lower area (draining health to exactly 175 HP) while summoning toxic zombies.</li>
<li><strong>Phase 2</strong> &mdash; Caltheris reforms into a smaller rock golem and chases you around the arena, slapping you into the air and throwing rocks. Damage her until a glowing blue weak point appears, then hit it for critical damage.</li>
<li><strong>Phase 3</strong> &mdash; Caltheris Ascendant. She has an immunity period during which armored zombies spawn (restock on armor plates). Plays like phase 2 but adds a slam attack &mdash; jump into the air to avoid damage.</li>
<li><strong>Phase 4</strong> &mdash; Caltheris the Needle. All attacks are empowered: rock throws create purple pools of electricity that deal heavy damage, movement speed increases exponentially, and the slam hits harder, stuns longer, and covers a wider area. Deplete her health bar to win.
<ul>
<li>If you have completed the Ashes of the Damned main quest, <strong>Veytharion&rsquo;s Blessing</strong> spawns at the top of the arena during this phase &mdash; it refills ammo/armor and grants infinite ammo and equipment for a limited duration.</li>
</ul>
</li>
</ol>
<hr>
</div><h1 id="wiki_main_quest_cheat_sheet">Main Quest Cheat Sheet</h1>
<p><em>Quick reference for players who already know the quest. Full details are in the <a href="#wiki_main_quest">Main Quest</a> walkthrough above.</em></p>
<div class="quest-grid">
  <div class="quest-block phase1" id="wiki_main_quest_awaken_astronomer">
    <h2>Awaken the astronomer</h2>
    <ol>
      <li>Acquire the LGM-1 (see Key Features).</li>
      <li><strong>Starting at Round 10</strong>, follow O.S.C.A.R. until it calls out three planets. Convert planets to numbers by their distance from the Sun (Mercury = 1, Neptune = 8).</li>
      <li>Enter the 3-digit code at the Observatory Dome terminal; a lift drops with a corpse and a key.</li>
      <li>Go to Machina Astralis, open the cryopod with the key to reveal a corpse.</li>
      <li>Shoot the glass at Museum Infinitum to grab the Saw, return to the pod, and take the brain.</li>
      <li>Place the brain on the table in the Luminarium and defend during the short lockdown.</li>
      <li>Bring the brain to the machine near the teleporter in Machina Astralis to power it; it will list book titles.</li>
    </ol>
  </div>
  <div class="quest-block phase2" id="wiki_main_quest_portal_to_mars">
    <h2>Power and align the observatory</h2>
    <ol>
      <li>Use the Observatory Dome telescope (requires trap activation or LGM-1) to find Mars coordinates (4-digit code).</li>
      <li>Enter the code at the Machina Astralis machine; it confirms Mars.</li>
      <li>In Archive of Orbis, match the three busts to the counted book titles from their shelves (do this at round start for time).</li>
      <li>When correct, climb the opened panel to grab the Neptune model and place it atop Machina Astralis.</li>
      <li>Collect three planet notes (directions + planet): Luminarium desk, Machina Astralis table, Archive of Orbis table.</li>
      <li>Align the planets on the model display to the noted directions (compass around the Sun model).</li>
      <li>Return to Machina Astralis, interact with the brain to reboot the portal, defend against O.S.C.A.R.; you will be sent to Mars.</li>
    </ol>
  </div>
  <div class="quest-block phase3" id="wiki_main_quest_mars_sequence">
    <h2>Mars sequence</h2>
    <ol>
      <li>Pick up the brain at the arena center, place it in the machine up the stairs, and create the portal.</li>
      <li>Each round, play the machine sound to spot the ascendant eye; while it flies, shoot pylons: Back Right > Back Left > Front Right > Front Left > temple pylon above the machine. Grab the eye when it dives.</li>
      <li>Place the ascendant eye in the device on the right side of the arena (facing where you shot pylons).</li>
      <li>With the LGM-1, shoot the antennas of the five arena pillars until each shows a symbol and a song plays.</li>
      <li>Back in Observatory Dome, read the organ screen: it shows the five symbols in order with one missing (denoted by wavy lines). Note the missing symbol and its position.</li>
      <li>Return to Mars and interact with the pillars in that exact order, inserting the missing symbol where indicated.</li>
      <li>Interact with the machine atop the stairs to start the fight against Caltheris.</li>
    </ol>
  </div>
</div>

<div class="helper-row">
  <AstraBustHelper />

  <AstraPlanetCodeHelper />
</div>
</template>
