<!-- AUTO-GENERATED by scripts/convert-guides.mjs from public/guides/astra-malorum.html -->
<template>




<span id="wiki_astra_malorum_.7C_complete_map_breakdown" class="legacy-anchor" aria-hidden="true"></span>


<img class="guide-cover" src="/images/astra-thumb.jpg" alt="Astra Malorum" />
<p style="text-align: center;"><strong><em>In the cold depths of space, a century-old observatory guards a gateway to a dead world. Awaken the astronomer, defeat the mechanical guard, and liberate the celestial Shadowsmith!</em></strong></p>
<hr>
<h1 id="wiki_key_features">Key Features</h1>
<p>This is a walkthrough of the key features of the map, such as Pack-a-Punch, Wonder Weapons, etc.</p>
<div class="glass-card glass-gold"><h2 id="wiki_pack.2Da.2Dpunch"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Pack-a-Punch<span class="g-tag">🌀 Pack-a-Punch</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<ol>
<li>TBD</li>
</ol></div>
<div class="glass-card glass-amber"><h2 id="wiki_lgm.2D1"><label class="g-toggle"><input type="checkbox" class="g-cb" checked><span class="g-title">LGM-1<span class="g-tag">🔫 LGM-1</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<ol>
<li>Collect several items:
<ol>
<li>Destroy one of O.S.C.A.R. flying drones to obtain the Damaged Drone.</li>
<li>Find a blinking lamp post around the map and shoot it to drop the Aberrant Wiring.</li>
<li id="guide-step-crash-1" data-guide-step>Equipped with a Pack-a-Punched gun, shoot the gearbox of Ol' Tessie in Crash Site to collect the Car Battery. <ShowOnMap target="step-crash-1" /></li>
<li>With Cryofreeze equipped, find and shoot an Aether Crystal around the map to drop an Absolute Zero Shard. You need to collect a total of 3 shards.</li>
</ol>
</li>
<li>Kill O.S.C.A.R. using three different traps. <strong>This can be done in any order, but only one can be done per round.</strong>
<ol>
<li id="guide-step-museum-1" data-guide-step>Place the Absolute Zero Shard inside the rocket thrusters in Museum Infinitum. If done correctly, a countdown will be heard. Activate the trap and bring O.S.C.A.R. to the rocket thrusters to kill it.<img alt="" class="wiki-img-right wiki-img-with-wrap wiki-img-in-table" data-height="930" data-media-id="zpff20px6g5g1" data-width="855" height="256" width="235" src="https://preview.redd.it/zpff20px6g5g1.png?width=320&height=348&format=png&auto=webp&s=41036b5a09afab96e073db914c3f7a10488cc958"> <ShowOnMap target="step-museum-1" /></li>
<li id="guide-step-luminarium-1" data-guide-step>Place the Damaged Drone, Car Battery and Aberrant Wiring inside the trap at the Luminarium to enable the Electro-Volt Projector. Bring O.S.C.A.R. inside the room and interact with the trap to kill it. Players have to hold O.S.C.A.R. within the room until it overheats and explodes. Purple-eyed zombies will also spawn during this step. <ShowOnMap target="step-luminarium-1" /></li>
<li id="guide-step-locations-step-dome-1" data-guide-step>Inside the Observatory Dome, find and shoot at 5 fuming valves around the room within a limited time. If done correctly, the telescope will start moving.
 <ShowOnMap target="locations-step-dome-1" label="Show lgm-1 locations on map" />
<ul>
<li id="guide-step-dome-1" data-guide-step>Two are located above the telescope.</li>
<li id="guide-step-dome-2" data-guide-step>Two are located under the telescope.</li>
<li id="guide-step-dome-3" data-guide-step>Three are located on the walls inside the room.</li>
<li id="guide-step-dome-4" data-guide-step>One is located on a pillar behind a sparking box.</li>
<li id="guide-step-dome-5" data-guide-step>One is located in the small room when coming from Machina Astralis</li>
</ul>
</li>
<li id="guide-step-dome-6" data-guide-step>Bring O.S.C.A.R. beneath the telescope and interact with the organ in front of the Pack-a-Punch machine. A screen will appear and you'll need to place the cursor on the Sun to activate the trap. Make sure O.S.C.A.R. stays within the laser beam to kill it. <ShowOnMap target="step-dome-6" /></li>
</ol>
</li>
</ol>
<ol>
<li>Once all three traps are done, the final O.S.C.A.R. killed will drop the LGM-1.</li>
</ol>
<hr>
</div><h1 id="wiki_leads">Leads</h1>
<ul>
<li id="guide-step-luminarium-2" data-guide-step>The Stellar Dissector can be found next to the trap in Luminarium <ShowOnMap target="step-luminarium-2" /></li>
<li>5 Grandfather clocks can be meleed to pixelate your vision and slow down time.</li>
</ul>
<hr>
<h1 id="wiki_main_quest">Main Quest</h1>

<ol>
<li id="wiki_main_quest_awaken_astronomer" style="scroll-margin-top:8rem"><span id="guide-step-museum-luminarium-dome-1" class="legacy-anchor" aria-hidden="true"></span><strong>Acquire the LGM-1</strong> (see Key Features for the full trap sequence). <ShowOnMap target="step-museum-luminarium-dome-1" /></li>
<li><strong>Starting at Round 10</strong>, stay behind O.S.C.A.R. and follow it until it plays a recording, during which Dr. Thurston will recite the name of three planets. Turn the planets into numbers based on their distance from the Sun (Mercury = 1, Venus = 2, ... Neptune = 8). <InlineTool tool="astra-mars-code" /></li>
<li id="guide-step-dome-7" data-guide-step>Travel to the Observatory Dome and enter the 3-digit code into the terminal. If done correctly, a lift will drop down next to the Pack-a-Punch.  <ShowOnMap target="step-dome-7" /></li>
<li id="guide-step-cryopod-1" data-guide-step>Retrieve the key from the corpse on the lift, then travel to Machina Astralis and interact with the cryopod located in the adjacent room leading to Scholar&rsquo;s Way. The pod will open, revealing Dr. Thurston&rsquo;s corpse. <strong>Note that this will summon O.S.C.A.R. and spawn several zombies to your location.</strong> <ShowOnMap target="step-cryopod-1" /></li>
<li id="guide-step-museum-cryopod-1" data-guide-step>Travel to Museum Infinitum and find the Rock Saw located behind a glass display; shoot the glass to pick it up. Return to the cryopod and interact with the corpse to collect Thurston&rsquo;s brain. <strong>You can pick up the Rock Saw before Step 4. Once the cryopod is opened, hold interact on Thurston&rsquo;s head to collect his brain &mdash; you will be immune to damage during the process.</strong> <ShowOnMap target="step-museum-cryopod-1" /></li>
<li id="guide-step-luminarium-3" data-guide-step>Travel to The Luminarium and interact with the brain jar on the table to replace the monkey brain with Thurston&rsquo;s brain. Interact once more, and this will trigger a short lockdown where you need to defend the brain. <ShowOnMap target="step-luminarium-3" /></li>
<li id="guide-step-machina-1" data-guide-step>Pick the brain jar up and place it in the machine near the portal in Machina Astralis. <strong>Holding the jar will slow you down.</strong> Hold interact on the machine to connect the jar to it. If done correctly, the machine will power up and display a list of book titles on the left screen (9 possible titles). <ShowOnMap target="step-machina-1" /></li>
<li id="wiki_main_quest_portal_to_mars" style="scroll-margin-top:8rem"><span id="guide-step-archive-1" class="legacy-anchor" aria-hidden="true"></span>Go to the Archive of Orbis. Inside the room there are three busts, each with a set of 3 bookshelves beside it. Interacting with each bookshelf displays one of the book titles. Find the book titles shown by the machine, then <strong>as fast as possible</strong>, interact with each bust as many times as the number of matching titles found in its set of shelves. <em>Example: if the machine shows The Black Veil, Echoes of Andromeda, Witchlight Codex, Silence at Singularity, interact with bust 1 once, bust 2 once, bust 3 twice.</em><InlineTool tool="astra-books" /> <ShowOnMap target="step-archive-1" /></li>
<li id="guide-step-archive-machina-upper-1" data-guide-step>If done correctly, a panel will open above the ladder in the room. Climb it to retrieve the Neptune model and place it in the display at the top of Machina Astralis. <ShowOnMap target="step-archive-machina-upper-1" /></li>
<li id="guide-step-luminarium-machina-upper-archive-1" data-guide-step>Find three pages around the map; each page shows a random planet (e.g. Mars) and a random direction (e.g. NE): one on a table in The Luminarium (same room as the Stellar Dissector trap), one on a desk in Machina Astralis, one on the large table in Archive of Orbis. <ShowOnMap target="step-luminarium-machina-upper-archive-1" /></li>
<li id="guide-step-machina-upper-1" data-guide-step>Shoot the corresponding planets (Mars, Saturn, Neptune) on the model display to align each in the direction from the notes. <strong>The compass showing the directions is below the Sun model.</strong> <InlineTool tool="astra-planets" /> <ShowOnMap target="step-machina-upper-1" label="Show Machina Astralis planet display on map" /></li>
<li id="guide-step-dome-8" data-guide-step>Travel to the Observatory Dome and interact with the telescope. Look for Mars and note its declination (DEC) &mdash; this corresponds to a 4-digit code. <ShowOnMap target="step-dome-8" /></li>
<li id="guide-step-machina-upper-2" data-guide-step>On the second floor of Machina Astralis, enter the code into the machine. If done correctly, Thurston will acknowledge the successful code input. <ShowOnMap target="step-machina-upper-2" /></li>
<li id="guide-step-machina-mars-center-1" data-guide-step>Interact with the machine to reboot the portal. This spawns O.S.C.A.R., who constantly launches flying saucers at the portal to damage it. Destroy the saucers and defend the portal until it finishes rebooting &mdash; if it takes too much damage before the timer runs out, the step fails. If done correctly, you will be teleported to Mars automatically. <ShowOnMap target="step-machina-mars-center-1" /></li>
<li id="wiki_main_quest_mars_sequence" style="scroll-margin-top:8rem"><span id="guide-step-mars-center-mars-machine-1" class="legacy-anchor" aria-hidden="true"></span>While on Mars, pick up Thurston&rsquo;s brain jar in the center of the arena and place it in the machine at the top of the stairs. Interact with it to create a portal. (Step 6 of the cheat sheet can be done as you create the portal.) <ShowOnMap target="step-mars-center-mars-machine-1" /></li>
<li id="guide-step-mars-machine-1" data-guide-step>Interact with the machine to play music (once per round). When the music plays, the Ascendant Eye will be seen flying near the giant head outside the map.</li>
<li id="guide-step-mars-back-right-mars-back-left-mars-front-right-mars-front-left-mars-tem-1" data-guide-step>Shoot the four pylons outside the map in order: <strong>Back Right, Back Left, Front Right, Front Left</strong>, then the pylon above the machine on top of the temple to bring the Ascendant Eye into the arena. <strong>Shooting the temple pylon repeatedly keeps the music playing, forcing the Ascendant Eye to stay.</strong> <ShowOnMap target="step-mars-back-right-mars-back-left-mars-front-right-mars-front-left-mars-tem-1" /></li>
<li id="guide-step-mars-center-1" data-guide-step>Wait for the Ascendant Eye to fly low in the arena, then jump and interact to grab it. <strong>Easier with low gravity enabled.</strong> <ShowOnMap target="step-mars-center-1" /></li>
<li id="guide-step-mars-eye-mars-center-1" data-guide-step>Place the Ascendant Eye in the device on the right side of the arena. With the LGM-1, shoot the antennas on the five pillars around the arena &mdash; each plays a note and displays a symbol on its pillar. <ShowOnMap target="step-mars-eye-mars-center-1" /></li>
<li id="guide-step-dome-9" data-guide-step>Back in the Observatory Dome, interact with the organ. The screen on the right displays the five symbols in order, with one hidden behind distorted wave lines. <strong>This step can be done immediately after unlocking Pack-a-Punch.</strong><InlineTool tool="astra-organ" /> <ShowOnMap target="step-dome-9" /></li>
<li id="guide-step-mars-center-2" data-guide-step>Return to Mars and interact with the pillars in the order shown on the organ&rsquo;s screen, inserting the missing symbol where indicated. If done correctly, the screen brightens and a quote from Thurston plays. <ShowOnMap target="step-mars-center-2" /></li>
<li id="guide-step-mars-machine-2" data-guide-step>Interact with the machine at the top of the stairs to start the fight against <strong>Caltheris</strong>. <ShowOnMap target="step-mars-machine-2" /></li>
</ol>
<div class="glass-card glass-red glass-boss"><h2 id="wiki_caltheris_boss_fight"><label class="g-toggle"><input type="checkbox" class="g-cb" checked><span class="g-title">Caltheris Boss Fight<span class="g-tag">⚔️ BOSS</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<ol>
<li id="guide-step-mars-eye-mars-machine-1" data-guide-step><strong>Phase 1</strong> &mdash; Kill zombies while dodging Caltheris&rsquo;s lasers to charge the Tesla coil on the right side of the arena. Once fully charged, interact with the machine at the top of the stairs to fire a beam, instantly draining 1/3 of her health bar. Repeat two more times. After each successful attack, Caltheris gains a new attack: meteors covering an area in flames, or toxic gas on the lower area (draining health to exactly 175 HP) while summoning toxic zombies. <ShowOnMap target="step-mars-eye-mars-machine-1" /></li>
<li><strong>Phase 2</strong> &mdash; Caltheris reforms into a smaller rock golem and chases you around the arena, slapping you into the air and throwing rocks. Damage her until a glowing blue weak point appears, then hit it for critical damage.</li>
<li><strong>Phase 3</strong> &mdash; Caltheris Ascendant. She has an immunity period during which armored zombies spawn (restock on armor plates). Plays like phase 2 but adds a slam attack &mdash; jump into the air to avoid damage.</li>
<li><strong>Phase 4</strong> &mdash; Caltheris the Needle. All attacks are empowered: rock throws create purple pools of electricity that deal heavy damage, movement speed increases exponentially, and the slam hits harder, stuns longer, and covers a wider area. Deplete her health bar to win.
<ul>
<li>If you have completed the Ashes of the Damned main quest, <strong>Veytharion&rsquo;s Blessing</strong> spawns at the top of the arena during this phase &mdash; it refills ammo/armor and grants infinite ammo and equipment for a limited duration.</li>
</ul>
</li>
</ol>
<hr>
</div><span id="wiki_main_quest_cheat_sheet" class="legacy-anchor"></span>

<div class="quest-grid">
  <div class="quest-block phase1">
    <h2>Awaken the astronomer</h2>
    <ol>
      <li>Acquire the LGM-1 (see Key Features).</li>
      <li><strong>Starting at Round 10</strong>, follow O.S.C.A.R. until it calls out three planets. Convert planets to numbers by their distance from the Sun (Mercury = 1, Neptune = 8).<InlineTool tool="astra-mars-code" /></li>
      <li>Enter the 3-digit code at the Observatory Dome terminal; a lift drops with a corpse and a key.</li>
      <li>Go to Machina Astralis, open the cryopod with the key to reveal a corpse.</li>
      <li>Shoot the glass at Museum Infinitum to grab the Saw, return to the pod, and take the brain.</li>
      <li>Place the brain on the table in the Luminarium and defend during the short lockdown.</li>
      <li>Bring the brain to the machine near the teleporter in Machina Astralis to power it; it will list book titles.</li>
    </ol>
  </div>
  <div class="quest-block phase2">
    <h2>Power and align the observatory</h2>
    <ol>
      <li>Use the Observatory Dome telescope (requires trap activation or LGM-1) to find Mars coordinates (4-digit code).</li>
      <li>Enter the code at the Machina Astralis machine; it confirms Mars.</li>
      <li>In Archive of Orbis, match the three busts to the counted book titles from their shelves (do this at round start for time).<InlineTool tool="astra-books" /></li>
      <li>When correct, climb the opened panel to grab the Neptune model and place it atop Machina Astralis.</li>
      <li>Collect three planet notes (directions + planet): Luminarium desk, Machina Astralis table, Archive of Orbis table.</li>
      <li>Align the planets on the model display to the noted directions (compass around the Sun model).<InlineTool tool="astra-planets" /></li>
      <li>Return to Machina Astralis, interact with the brain to reboot the portal, defend against O.S.C.A.R.; you will be sent to Mars.</li>
    </ol>
  </div>
  <div class="quest-block phase3">
    <h2>Mars sequence</h2>
    <ol>
      <li>Pick up the brain at the arena center, place it in the machine up the stairs, and create the portal.</li>
      <li>Each round, play the machine sound to spot the ascendant eye; while it flies, shoot pylons: Back Right > Back Left > Front Right > Front Left > temple pylon above the machine. Grab the eye when it dives.</li>
      <li>Place the ascendant eye in the device on the right side of the arena (facing where you shot pylons).</li>
      <li>With the LGM-1, shoot the antennas of the five arena pillars until each shows a symbol and a song plays.</li>
      <li>Back in Observatory Dome, read the organ screen: it shows the five symbols in order with one missing (denoted by wavy lines). Note the missing symbol and its position.<InlineTool tool="astra-organ" /></li>
      <li>Return to Mars and interact with the pillars in that exact order, inserting the missing symbol where indicated.</li>
      <li>Interact with the machine atop the stairs to start the fight against Caltheris.</li>
    </ol>
  </div>
</div>


<h1 id="wiki_caltheris_boss_fight_overview">Caltheris Boss Fight — Overview</h1>
<div class="boss-phases">
  <div class="boss-card phase1">
    <div class="boss-title">Phase 1 · Lasers and lava orbs</div>
    <ul class="boss-points">
      <li id="guide-step-mars-eye-mars-left-mars-machine-1" data-guide-step>Kill zombies while dodging lasers to charge the Tesla coil on the right side of the arena. <ShowOnMap target="step-mars-eye-mars-left-mars-machine-1" /></li>
      <li id="guide-step-mars-machine-4" data-guide-step>Once charged, interact with the machine at the top of the stairs to fire a beam that drains <strong>1/3 of her health bar</strong>.</li>
      <li>Repeat on the left side. Lava orbs leave burning pools on the floor.</li>
      <li>Each successful beam adds a new attack: meteor strikes that set an area on fire, or toxic gas on the lower area (drains you to exactly 175 HP) plus toxic zombies.</li>
    </ul>
  </div>
  <div class="boss-card phase2">
    <div class="boss-title">Phase 2 · Small golem</div>
    <ul class="boss-points">
      <li>Caltheris reforms into a smaller rock golem that chases you, slaps you into the air, and throws rocks.</li>
      <li>Damage her until a glowing blue weak point appears, then hit it for critical damage.</li>
      <li>Keep kiting zombies while bursting the weak point.</li>
    </ul>
  </div>
  <div class="boss-card phase3">
    <div class="boss-title">Phase 3 · Caltheris Ascendant</div>
    <ul class="boss-points">
      <li>She gains an immunity period during which armored zombies spawn — restock on armor plates.</li>
      <li>Plays like phase 2, with a slam attack added: jump as the slam lands to avoid the shockwave.</li>
    </ul>
  </div>
  <div class="boss-card phase4">
    <div class="boss-title">Phase 4 · Caltheris the Needle</div>
    <ul class="boss-points">
      <li>All attacks are empowered. Rock throws leave purple pools of electricity that deal heavy damage.</li>
      <li>Movement speed increases exponentially; the slam hits harder, stuns longer, and covers a wider area.</li>
      <li>Deplete her health bar to finish the fight.</li>
      <li>If you completed the Ashes of the Damned main quest, <strong>Veytharion's Blessing</strong> spawns at the top of the arena — it refills ammo/armor and grants infinite ammo and equipment for a limited time.</li>
    </ul>
  </div>
</div>
<hr>
<h1 id="wiki_side_quests_and_easter_eggs">Side Quests and Easter Eggs</h1>
<div class="glass-card glass-violet"><h2 id="wiki_secret_song"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Secret song<span class="g-tag">🎵 Song</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<p id="guide-step-locations-step-luminarium-5" data-guide-step>Find three Mr Peeks headphones around the map: <ShowOnMap target="locations-step-luminarium-5" label="Show secret song locations on map" /></p>
<ul>
<li id="guide-step-luminarium-5" data-guide-step>At the bottom shelf, left of the exit door in Luminarium</li>
<li id="guide-step-machina-3" data-guide-step>On a display case in Machina Astralis</li>
<li id="guide-step-mars-center-5" data-guide-step>On the ground next to a wall in Mars</li>
</ul>
<p>By Avenged Sevenfold</p></div>
<div class="glass-card glass-violet"><h2 id="wiki_alpha_omega_game_over_song"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Alpha Omega Game Over Song<span class="g-tag">🎵 Song</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<p id="guide-step-locations-step-machina-4" data-guide-step>Find three records: <ShowOnMap target="locations-step-machina-4" label="Show alpha omega game over song locations on map" /></p>
<ul>
<li id="guide-step-machina-4" data-guide-step>Inside a wooden box in Machina Astralis in a box on the middle floor</li>
<li id="guide-step-luminarium-6" data-guide-step>At the top of a bookshelf in the Luminarium</li>
<li id="guide-step-museum-2" data-guide-step>On a wooden sil above a zombie spawner in the Museum</li>
</ul>
<p id="guide-step-luminarium-7" data-guide-step>Bring the records to gramophone in the Luminarium and it will play the Game Over song from Alpha Omega. <ShowOnMap target="step-luminarium-7" /></p></div>
<div class="glass-card glass-amber"><h2 id="wiki_friendly_ravager"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title"> Friendly Ravager<span class="g-tag">🦖 Ravager</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<p>Look for glowing eyes in zombie spawners around the map and throw a shiny trinket at them; the Ravager will eat the trinket and later reappear in another zombie spawn. Repeat this process twice more, and on the third time he will jump out, clap his cymbals together, and become a temporary friendly Ravager.</p>
<hr>

</div><div class="glass-card glass-violet"><h2 class="" id="wiki_magic_secret_song"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">"Magic" Secret Song<span class="g-tag">🎵 Song</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<p id="guide-step-locations-step-luminarium-rim-1" data-guide-step>Find three Mr Peeks headphones around the map: <ShowOnMap target="locations-step-luminarium-rim-1" label="Show &quot;magic&quot; secret song locations on map" /></p>
<ul>
<li id="guide-step-luminarium-rim-1" data-guide-step>At the bottom of the bookshelf, left of the door in The Luminarium going to Abyssal Rim.</li>
<li id="guide-step-machina-5" data-guide-step>In a display case in Machina Astralis.</li>
<li id="guide-step-dome-13" data-guide-step>On a chair in Observatory Dome.</li>
</ul>
<p>"Magic" by Avenged Sevenfold</p></div>

<div class="glass-card glass-red"><h2 class="" id="wiki_echoes_of_the_damned_nikolai"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Echoes of the Damned (Nikolai's Side Quest)<span class="g-tag">⚔️ Quest</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<ol>
<li>Play as Nikolai Belinski.</li>
<li id="guide-step-rim-1" data-guide-step>Travel to the lower part of Abyssal Rim, and throw a Molotov Cocktail on the ground near the Ammo Cache. This will create fiery footprints forming a trail. Throw additional Molotov Cocktails and follow the footprints until they reach an inaccessible cave. <ShowOnMap target="step-rim-1" /></li>
<li>Interact with the toy near the cave to trigger a cutscene.</li>
<li>After the cutscene, you will be teleported into the cave. Travel through the cave until you find an altar. Interacting with the altar will spawn Ravagers. Kill all the Ravagers until another cutscene is played.</li>
<li>Once done, you will be back into the map. Loot will drop on the ground including a Molotov Cocktail and a Legendary Echo 12. Completing the side quest also rewards the "Echoes of the Damned" Dark Ops Calling Card.</li>
</ol></div>

<div class="glass-card glass-green"><h2 class="" id="wiki_the_five_skulls"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">The Five Skulls (Free Random Perk)<span class="g-tag">💀 Skulls</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<ol>
<li>Get a Pack-a-Punched Weapon.</li>
<li id="guide-step-locations-step-luminarium-crash-1" data-guide-step>Find 5 skulls around the map and shoot each one to light the eye sockets, then interact to pick them up:
 <ShowOnMap target="locations-step-luminarium-crash-1" label="Show the five skulls (free random perk) locations on map" />
<ul>
<li id="guide-step-luminarium-crash-1" data-guide-step>In the courtyard between Crash Site and The Luminarium.</li>
<li id="guide-step-museum-3" data-guide-step>In one of the displays in Museum Infinitum.</li>
<li id="guide-step-courtyard-1" data-guide-step>In a zombie spawn hole next to the Ammo Cache in Stargazer's Courtyard.</li>
<li id="guide-step-machina-courtyard-1" data-guide-step>In a display case in Machina Astralis on the left side when coming from Stargazer's Courtyard.</li>
<li id="guide-step-archive-veilwalk-1" data-guide-step>In a corner behind the brick wall in The Veilwalk on the right side when coming from Archive of Orbis.</li>
</ul>
</li>
<li id="guide-step-machina-6" data-guide-step>Once all the skulls are collected, place them on the cabinet with the large mirror in Machina Astralis. <ShowOnMap target="step-machina-6" /></li>
<li>All the skulls' eye sockets will shine and activate a Simon Says mini-game. Shoot the skulls in the correct order.</li>
<li>If done correctly, all the skulls will float and merge into a Random Perk Power-Up.</li>
</ol></div>

<div class="glass-card glass-amber"><h2 class="" id="wiki_bongo_friendly_ravager"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">"Bongo" The Friendly Ravager<span class="g-tag">🦖 Bongo</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<ol>
<li>When defeating O.S.C.A.R., it will drop a toy robot called "Shiny Trinket" which will replace your Tactical when picked up.</li>
<li>Find a white dot on the minimap, located outside the playable area and usually a place where zombies will spawn.</li>
<li>Travel to that location, and you should find a green-eyed Ravager. Throw the Shiny Trinket at it. The Ravager will eat it and hide away.</li>
<li>Repeat the process two more times.</li>
<li>On the third time, the Ravager will jump into the map as "Bongo" and play with cymbals before attacking enemies for a few rounds.</li>
</ol></div>

<div class="glass-card glass-orange"><h2 class="" id="wiki_gramophones_challenges"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Gramophones Challenges (Free Mystery Perks)<span class="g-tag">🎶 Gramophones</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<p id="guide-step-locations-step-machina-archive-1" data-guide-step>Three gramophones can be found around the map. Each gramophone needs a corresponding vinyl record. While the records are playing, you need to complete a challenge. <ShowOnMap target="locations-step-machina-archive-1" label="Show gramophones challenges (free mystery perks) locations on map" /></p>
<ul>
<li id="guide-step-machina-archive-1" data-guide-step><strong>Archive of Orbis</strong> (near Stamin-Up): The record can be found inside a wooden box in the middle floor of Machina Astralis. While the song is playing, kill 5 zombies with equipment. Once the music stops, Equipment and a Mystery Perk can will drop.</li>
<li id="guide-step-luminarium-8" data-guide-step><strong>The Luminarium</strong> (near Mr Peeks headphone): The record can be found at the top of a bookshelf, next to one of the grandfather clocks. While the song is playing, kill 15 zombies with Field Upgrades. Once the music stops, Essence and a Mystery Perk can will drop.</li>
<li id="guide-step-museum-4" data-guide-step><strong>Museum Infinitum</strong> (near Speed Cola): The record can be found on the capital of the wooden pillar above a zombie window. While the song is playing, kill 5 zombies with melee weapons. Once the music stops, Salvage and a Mystery Perk can will drop.</li>
</ul></div>

<div class="glass-card glass-green"><h2 class="" id="wiki_the_twins"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">The Twins (Free Cryo Freeze and loot)<span class="g-tag">🧊 Twins</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<ol>
<li id="guide-step-museum-5" data-guide-step>During a special round, travel to Museum Infinitum and interact with the left-most display cabinet beneath the painting of a mansion/castle. <ShowOnMap target="step-museum-5" /></li>
<li id="guide-step-museum-6" data-guide-step>During the next rounds, weird noises will play from one of the displays in the museum, one per round and four times in total. Interact with each display.</li>
<li id="guide-step-locations-step-crash-2" data-guide-step>If done correctly, the ghost twins will appear somewhere around the map. They can be found in three states: dancing which plays music; drawing with chalk on the ground; standing holding hands. The Twins can appear in:
 <ShowOnMap target="locations-step-crash-2" label="Show the twins (free cryo freeze and loot) locations on map" />
<ul>
<li id="guide-step-crash-2" data-guide-step>Crash Site: Behind Ol' Tessie.</li>
<li id="guide-step-luminarium-rim-2" data-guide-step>The Luminarium: Inside the Stellar Dissector or in a corner outside on the Abyssal Rim side.</li>
<li id="guide-step-rim-2" data-guide-step>Abyssal Rim: Next to Wisp Tea.</li>
<li id="guide-step-dome-14" data-guide-step>Observatory Dome: In a corner near the X9 Maverick wall-buy.</li>
<li id="guide-step-dome-veilwalk-1" data-guide-step>The Veilwalk: Next to the door leading to Observatory Dome.</li>
<li id="guide-step-machina-upper-scholar-1" data-guide-step>Machina Astralis: On the upper floor or in a corner near the door leading to Scholar's Way.</li>
<li id="guide-step-museum-scholar-1" data-guide-step>Museum Infinitum: In a corner near the door leading to Scholar's Way.</li>
</ul>
</li>
<li>Once you come across the Twins, they will disappear leaving loot behind including Salvage and Equipment and a free Cryo Freeze Ammo Mod the first time they are encountered. The Twins will reappear every subsequent round giving additional loot.</li>
</ol></div>

<div class="glass-card glass-gold"><h2 class="" id="wiki_time_dilation"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Time Dilation<span class="g-tag">⏳ Dilation</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<ol>
<li id="guide-step-locations-step-luminarium-9" data-guide-step>Rapidly melee 5 grandfather clocks found around the map:
 <ShowOnMap target="locations-step-luminarium-9" label="Show time dilation locations on map" />
<ul>
<li id="guide-step-luminarium-9" data-guide-step>One in The Luminarium, next to the bookshelves.</li>
<li id="guide-step-museum-7" data-guide-step>One in Museum Infinitum, near Speed Cola.</li>
<li id="guide-step-machina-7" data-guide-step>Two in Machina Astralis: one on the bottom floor, one on the middle floor.</li>
<li id="guide-step-archive-3" data-guide-step>One in Archive of Orbis, next to Stamin-Up.</li>
</ul>
</li>
<li>If done correctly, all the enemies will move slowly for 60 seconds. This can be repeated once per round.</li>
</ol></div>

<div class="glass-card glass-green"><h2 class="" id="wiki_wisp_orbs"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Wisp Orbs (Free Ray Gun)<span class="g-tag">🟢 Wisp Orbs</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<ol>
<li id="guide-step-locations-step-crash-3" data-guide-step>There are 9 lanterns against walls around the map:
 <ShowOnMap target="locations-step-crash-3" label="Show wisp orbs (free ray gun) locations on map" />
<ul>
<li id="guide-step-crash-3" data-guide-step>Two in Crash Site.</li>
<li id="guide-step-luminarium-10" data-guide-step>Three in the courtyard in front of The Luminarium.</li>
<li id="guide-step-luminarium-11" data-guide-step>Two in the back of The Luminarium.</li>
<li id="guide-step-scholar-1" data-guide-step>Two in Scholar's Way.</li>
</ul>
</li>
<li>Find the lantern that is shining with a white wisp. Aim at the lantern to obtain the wisp inside. The wisp will now orbit around you. Using your melee button will throw the wisp before it comes back to you. When thrown at zombies, the wisp will usually kill 1 or 2 zombies. Killing zombies with the wisp does not give any Essence.</li>
<li>To upgrade the wisp, place it inside all the 9 lanterns by throwing it then getting it back by aiming at the lantern.</li>
<li>Once the wisp is in the last lantern, pass the round. If done correctly, the wisp will now turn yellow/orange. The wisps will also be available from any lantern.</li>
<li>You can collect up to 5 wisps at a time, which will orbit around you. Each upgraded wisp can kill about 5 zombies.</li>
<li>Starting at Round 16, the rocket from Ashes of the Damned will be seen floating in front of Saturn. Hit the rocket by throwing an upgraded wisp. If done correctly, the wisp will come back and drop a Ray Gun.</li>
<li>Additionally, aiming at the rocket long enough will play the song "Once In A Blown Up Moon" by Brian Tuey.</li>
</ol></div>

<div class="glass-card glass-orange"><h2 class="" id="wiki_dg2_turret_upgrade"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">DG-2 Turret Upgrade<span class="g-tag">🔫 DG-2</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<ol>
<li id="guide-step-official-1835-1" data-guide-step>In the area near Wisp Tea machine, an asteroid can be located nearby. Throw a grenade at the asteroid so that its explosion will knock the asteroid closer to you. <ShowOnMap target="step-official-1835-1" /></li>
<li id="guide-step-crash-4" data-guide-step>Sprint and wall jump to the left side of the asteroid. If done correctly, you will float into space and travel back to the Crash Site. As you travel, the DG-2 Turret will spawn; interact with it as you pass to grab it. While you travel a new mix of "Pareidolia" by Brian Tuey will play. <ShowOnMap target="step-crash-4" /></li>
<li id="guide-step-crash-5" data-guide-step>Once back at the Crash Site, install the turret onto Ol' Tessie. The turret can be used freely and is effective against O.S.C.A.R.</li>
</ol></div>

<div class="glass-card glass-violet"><h2 class="" id="wiki_pareidolia_secret_song"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Pareidolia Secret Song<span class="g-tag">🎵 Song</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<ol>
<li id="guide-step-mars-center-6" data-guide-step>Reach Mars and activate the portal. <ShowOnMap target="step-mars-center-6" /></li>
<li id="guide-step-mars-center-7" data-guide-step>Aim at the giant statue head on the right side of the stairs, when viewed from the portal entrance.</li>
</ol>
<p>This will play a remastered version of Pareidolia.</p></div>

<div class="glass-card glass-red"><h2 class="" id="wiki_skull_jumpscare"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Skull Jumpscare<span class="g-tag">💀 Jumpscare</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<ol>
<li id="guide-step-dome-15" data-guide-step>Move the telescope as part of the steps to unlock the LGM-1. <ShowOnMap target="step-dome-15" /></li>
<li id="guide-step-dome-16" data-guide-step>Interact with the binoculars on the left side of the organ and bring the cursor to the small-sized skull located at RA 2h 23m and DEC 42° 21'.</li>
<li id="guide-step-dome-17" data-guide-step>If done correctly, a short skull jumpscare should be triggered before forcing you out of the screen. The skull is gone afterwards.</li>
</ol></div>

<div class="glass-card glass-gold"><h2 id="wiki_relics"><label class="g-toggle"><input type="checkbox" class="g-cb" checked><span class="g-title">Relics<span class="g-tag">💎 Relics</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<p>Six Relics modify Cursed Mode in Astra Malorum (two per tier). Effects and unlock steps are still undiscovered; use the placeholders below until they are found.</p>
<p>The Relics are divided into three groups: <strong>Grim</strong>, <strong>Sinister</strong>, and <strong>Wicked</strong>. Each fills the Cursed Tier bar differently (Grim ≈ 1, Sinister ≈ 2, Wicked ≈ 3). Mix combinations to reach the tier you want:</p>
<ul class="relic-tiers">
<li><strong>Tier I</strong>: Any 3 <span class="relic-chip grim">Grim</span> — Unlocks Golden Armor (45,000 Essence)</li>
<li><strong>Tier II</strong>: 2 <span class="relic-chip sinister">Sinister</span> + 2 <span class="relic-chip grim">Grim</span> (example) — Unlocks Ultra Rarity</li>
<li><strong>Tier III</strong>: 3 <span class="relic-chip grim">Grim</span> + 2 <span class="relic-chip sinister">Sinister</span> + 1 <span class="relic-chip wicked">Wicked</span> (example) — Unlocks Pack-a-Punch IV (100,000 Essence)</li>
</ul>
<p class="relic-note">Higher tiers just need the total difficulty value to match the target fill; swap relics as you discover them.</p>
<div class="relic-grid">
  <div class="relic-section">
    <h2 class="relic-heading grim">Grim Relics</h2>
    <div class="relic-cards">
      <div class="relic-card grim">
        <div class="relic-title">GONG</div>
        <p class="relic-meta"><b>Effect:</b> Field Upgrade starts charged, but can only be charged by full power.</p>
        <ol class="steps">
          <li>Have <strong>Tesla Storm</strong> as your Field Upgrade, and at least one weapon with <strong>Dead Wire</strong>.</li>
          <li>Starting at Round 20, and every round afterwards, a zombie will spawn with a lightning rod embedded into its body.</li>
          <li id="guide-step-archive-dome-luminarium-1" data-guide-step>Around the map, there will be three doorways with a light bulb above them: The Luminarium (near the brain jar), Observatory Dome (near the room with the portal), and Archive of Orbis (next to the portal room). <ShowOnMap target="step-archive-dome-luminarium-1" /></li>
          <li>Bring the zombie with the lightning rod below the bulb and activate Tesla Storm. Then shoot the zombie to electrocute it with Dead Wire. If done correctly, the electricity will travel to the light bulb.</li>
          <li id="guide-step-dome-courtyard-1" data-guide-step>Once all three are done, look for the green portal outside between Observatory Dome and Stargazer's Courtyard. <ShowOnMap target="step-dome-courtyard-1" /></li>
          <li>Survive 4 waves where zombies can only be damaged with electric damage. Klaus Cores will also spawn there.</li>
        </ol>
      </div>
      <div class="relic-card grim">
        <div class="relic-title">SEED</div>
        <p class="relic-meta"><b>Effect:</b> Mystery Box is disabled.</p>
        <ol class="steps">
          <li>Reach Round 20.</li>
          <li>A pistol will spawn on the ground somewhere on the map.</li>
          <li>Pick the pistol and kill the exact number of enemies as the round you are in (Round 21 = 21 kills, etc). Once it is done, pass the round using any other weapon. Otherwise, start again the next round. The pistol can be Pack-a-Punched and its rarity can be upgraded.</li>
          <li id="guide-step-dome-18" data-guide-step>Travel to Observatory Dome and interact with the green portal to start the Relic Trial. <ShowOnMap target="step-dome-18" /></li>
          <li>Survive 4 waves with only a Pack-a-Punched pistol.</li>
        </ol>
      </div>
    </div>
  </div>
  <div class="relic-section">
    <h2 class="relic-heading sinister">Sinister Relics</h2>
    <div class="relic-cards">
      <div class="relic-card sinister">
        <div class="relic-title">SPIDER FANG</div>
        <p class="relic-meta"><b>Effect:</b> Perk costs at machines never decrease.</p>
        <ol class="steps">
          <li>Activate Cursed Mode Tier I.</li>
          <li>Reach Round 40 and defeat O.S.C.A.R. with a melee weapon while Wisp Tea spirit is attacking it. O.S.C.A.R. can be damaged with other way but the killing blow needs to be done with a melee.</li>
          <li id="guide-step-archive-4" data-guide-step>Travel to Archive of Orbis and interact with the yellow portal to start the Relic Trial. <ShowOnMap target="step-archive-4" /></li>
          <li>Survive 5 waves while all perks are disabled.</li>
        </ol>
      </div>
      <div class="relic-card sinister">
        <div class="relic-title">MATRYOSHKA DOLL</div>
        <p class="relic-meta"><b>Effect:</b> Salvage drop rate is halved.</p>
        <ol class="steps">
          <li>Activate Cursed Mode Tier I.</li>
          <li id="guide-step-mars-center-8" data-guide-step>Open the portal to Mars and reach Round 40. <ShowOnMap target="step-mars-center-8" /></li>
          <li id="guide-step-mars-center-9" data-guide-step>Place a C4 on each of the three gut piles found on the central platform on Mars.</li>
          <li id="guide-step-mars-center-10" data-guide-step>Gather a group of zombies in the middle of the platform and detonate the C4. If done correctly, Mr Peeks will be heard laughing.</li>
          <li id="guide-step-cryopod-3" data-guide-step>Travel to the side room of Machina Astralis and interact with the yellow portal to start the Relic Trial. <ShowOnMap target="step-cryopod-3" /></li>
          <li>Survive 5 waves while zombies and HVTs can only be killed with Field Upgrades.</li>
        </ol>
      </div>
    </div>
  </div>
  <div class="relic-section">
    <h2 class="relic-heading wicked">Wicked Relics</h2>
    <div class="relic-cards">
      <div class="relic-card wicked">
        <div class="relic-title">GOLDEN SPORK</div>
        <p class="relic-meta"><b>Effect:</b> Enemies deal double damage.</p>
        <ol class="steps">
          <li>Activate Cursed Mode Tier II.</li>
          <li id="guide-step-mars-center-11" data-guide-step>Open the portal to Mars and reach Round 60. <ShowOnMap target="step-mars-center-11" /></li>
          <li id="guide-step-mars-machine-cryopod-1" data-guide-step>Get a Mangler Cannon and travel to Mars. Shoot the portal with the Mangler Cannon, then teleport back to Machina Astralis. <ShowOnMap target="step-mars-machine-cryopod-1" /></li>
          <li id="guide-step-cryopod-4" data-guide-step>After a few seconds, the shot from the Mangler Cannon will leave the portal going towards Archive of Orbis. You need to gather a group of zombies inside the red circle on the ground near the portal, using Decoys for example.</li>
          <li id="guide-step-crash-6" data-guide-step>If enough zombies were killed, a red portal will appear on a wall at Crash Site. Interact with it to start the Relic Trial. <ShowOnMap target="step-crash-6" /></li>
          <li>Survive 6 waves while zombies and HVTs only take damage from hip-fire.</li>
        </ol>
      </div>
      <div class="relic-card wicked">
        <div class="relic-title">CIVIL PROTECTOR HEAD</div>
        <p class="relic-meta"><b>Effect:</b> Perk decay — every 100 kills you lose a perk.</p>
        <ol class="steps">
          <li>Activate Cursed Mode Tier II.</li>
          <li>Reach Round 60 and make sure to have PhD Flopper.</li>
          <li id="guide-step-crash-museum-1" data-guide-step>Get Energy Mine and trigger a mine next to Ol' Tessie. If done correctly, the headlights will flash three times signaling the start of a sequence. Afterwards each of the headlights and brake lights will light up. This will be the order for the chandeliers in Museum Infinitum. <ShowOnMap target="step-crash-museum-1" /></li>
          <li id="guide-step-museum-8" data-guide-step>The two chandeliers near the doorway to Stargazer's Courtyard are the headlights, while the two chandeliers near the doorway to Crash Site are the brake lights.</li>
          <li id="guide-step-museum-9" data-guide-step>Wall jump to reach the chandeliers to put out the candles, in the order shown by Ol' Tessie. <ShowOnMap target="step-museum-9" label="Show Museum Infinitum chandeliers on map" /></li>
          <li id="guide-step-crash-7" data-guide-step>Travel to Crash Site and interact with the red portal to start the Relic Trial.  <ShowOnMap target="step-crash-7" /></li>
          <li>Survive 6 waves by killing HVTs while all zombies are turned into sprinters.</li>
        </ol>
      </div>
    </div>
  </div>
</div>
<hr>
</div><h1 id="wiki_wall.2Dbuys_and_perk.2Da.2Dcolas">Wall-Buys and Perk-a-Colas</h1>
<div class="glass-card glass-gold"><h2 data-guide-step id="wiki_wall.2Dbuys_locations"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Wall-Buys Locations<span class="g-tag">🔫 Wall-Buys</span></span><span class="g-chev" aria-hidden="true"></span></label> <ShowOnMap target="locations-wall-2-buys-locations" label="Show wall-buys locations on map" /></h2>
<div class="table-container"><table style="width: 421px; table-layout: fixed; border-width: 1px;" border="1"><colgroup><col><col></colgroup>
<tbody>
<tr id="guide-step-official-1798-1" data-guide-step style="height: 37.8px;"><td style="width: 124px; border-width: 1px;">Jäger 45</td><td style="text-align: center; border-width: 1px; width: 189px;">Crash Site</td></tr> <tr id="guide-step-official-1806-1" data-guide-step style="height: 37.8px;"><td style="width: 124px; border-width: 1px;">M34 Novaline</td><td style="text-align: center; border-width: 1px; width: 189px;">The Luminarium</td></tr> <tr id="guide-step-official-1810-1" data-guide-step style="height: 37.8px;"><td style="width: 124px; border-width: 1px;">Carbon 57</td><td style="text-align: center; border-width: 1px; width: 189px;">Museum Infinitum</td></tr> <tr id="guide-step-official-1829-1" data-guide-step style="height: 37.8px;"><td style="width: 124px; border-width: 1px;">Akita</td><td style="text-align: center; border-width: 1px; width: 189px;">Machina Astralis</td></tr> <tr id="guide-step-official-1833-1" data-guide-step style="height: 37.8px;"><td style="width: 124px; border-width: 1px;">Shadow SK</td><td style="text-align: center; border-width: 1px; width: 189px;">Abyssal Rim</td></tr> <tr id="guide-step-official-1821-1" data-guide-step style="height: 37.8px;"><td style="width: 124px; border-width: 1px;">XM325</td><td style="text-align: center; border-width: 1px; width: 189px;">Stargazer's Courtyard</td></tr> <tr id="guide-step-official-1843-1" data-guide-step style="height: 37.8px;"><td style="width: 124px; border-width: 1px;">X9 Maverick</td><td style="text-align: center; border-width: 1px; width: 189px;">Observatory Dome</td></tr>
</tbody>
</table></div></div>
<div class="glass-card glass-green"><h2 data-guide-step id="wiki_perks_locations"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Perks Locations<span class="g-tag">🥤 Perks</span></span><span class="g-chev" aria-hidden="true"></span></label> <ShowOnMap target="locations-perks-locations" label="Show perks locations on map" /></h2>
<p id="wiki_cursed_mister_peeks" data-guide-step><strong>Mister Peeks · Cursed mode:</strong> Check his possible spawn locations. Shoot him when he appears to drop an egg that can contain perks and other loot. <ShowOnMap target="cursed-mister-peeks" label="Show Mister Peeks Cursed-mode spawn locations on map" /></p>
<p><em>Note: Der Wunderfizz appears after purchasing or acquiring 4 Perk-a-Colas.</em></p>
<div class="table-container"><table style="width: 136px; border-width: 1px; table-layout: fixed;" border="1"><colgroup><col><col></colgroup>
<tbody>
<tr id="guide-step-official-1803-1" data-guide-step style="height: 37.8px;"><td style="width: 124px; border-width: 1px;">Juggernog</td><td style="text-align: center; border-width: 1px; width: 189px;">The Luminarium</td></tr> <tr id="guide-step-official-1799-1" data-guide-step style="height: 37.8px;"><td style="width: 124px; border-width: 1px;">Quick Revive</td><td style="text-align: center; border-width: 1px; width: 189px;">Crash Site</td></tr> <tr id="guide-step-official-1839-1" data-guide-step style="height: 37.8px;"><td style="width: 124px; border-width: 1px;">Mule Kick</td><td style="text-align: center; border-width: 1px; width: 189px;">The Veilwalk</td></tr> <tr id="guide-step-official-1835-2" data-guide-step style="height: 37.8px;"><td style="width: 124px; border-width: 1px;">Wisp Tea</td><td style="text-align: center; border-width: 1px; width: 189px;">Abyssal Rim</td></tr> <tr id="guide-step-official-1811-1" data-guide-step style="height: 37.8px;"><td style="width: 124px; border-width: 1px;">Speed Cola</td><td style="text-align: center; border-width: 1px; width: 189px;">Museum Infinitum</td></tr> <tr id="guide-step-official-1830-1" data-guide-step style="height: 37.8px;"><td style="width: 124px; border-width: 1px;">Stamin-Up</td><td style="text-align: center; border-width: 1px; width: 189px;">Archive of Orbis</td></tr> <tr id="guide-step-courtyard-2" data-guide-step style="height: 37.8px;"><td style="width: 124px; border-width: 1px;">Der Wunderfizz</td><td style="text-align: center; border-width: 1px; width: 189px;">Stargazer's Courtyard</td></tr>
</tbody>
</table></div>
<hr>
</div><h1 id="wiki_miscellaneous_features">Miscellaneous Features</h1>
<div class="glass-card glass-amber"><h2 data-guide-step id="wiki_armor_vests_locations"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Armor Vests Locations<span class="g-tag">🦺 Armor</span></span><span class="g-chev" aria-hidden="true"></span></label> <ShowOnMap target="locations-armor-vests-locations" label="Show armor vests locations on map" /></h2>
<ul>
<li id="guide-step-machina-8" data-guide-step>Machina Astralis</li>
<li id="guide-step-rim-3" data-guide-step>Abyssal Rim</li>
<li id="guide-step-courtyard-3" data-guide-step>Stargazer's Courtyard</li>
</ul></div>
<div class="glass-card glass-amber"><h2 id="wiki_chompy_locations"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Chompy Locations<span class="g-tag">🧟 Chompy</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<ul>
<li>TBD</li>
</ul></div>
<div class="glass-card glass-red"><h2 data-guide-step id="wiki_traps_locations"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Traps Locations<span class="g-tag">🪤 Traps</span></span><span class="g-chev" aria-hidden="true"></span></label> <ShowOnMap target="locations-traps-locations" label="Show traps locations on map" /></h2>
<ul>
<li id="guide-step-luminarium-12" data-guide-step><strong>Stellar Dissector</strong> — The Luminarium</li>
<li id="guide-step-courtyard-4" data-guide-step><strong>Apogee Annihilator</strong> — Stargazer's Courtyard</li>
</ul></div>
<div class="glass-card glass-orange"><h2 data-guide-step id="wiki_arsenal_locations"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Arsenal Locations<span class="g-tag">🎯 Arsenal</span></span><span class="g-chev" aria-hidden="true"></span></label> <ShowOnMap target="locations-arsenal-locations" label="Show arsenal locations on map" /></h2>
<ul>
<li id="guide-step-luminarium-13" data-guide-step>The Luminarium</li>
<li id="guide-step-machina-9" data-guide-step>Machina Astralis</li>
</ul></div>
<div class="glass-card glass-amber"><h2 data-guide-step id="wiki_crafting_table_locations"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title"> Crafting Table Locations<span class="g-tag">🔨 Crafting</span></span><span class="g-chev" aria-hidden="true"></span></label> <ShowOnMap target="locations-crafting-table-locations" label="Show crafting table locations on map" /></h2>
<ul>
<li id="guide-step-museum-10" data-guide-step>Museum Infinitum</li>
<li id="guide-step-rim-4" data-guide-step>Abyssal Rim</li>
</ul></div>
</template>
