<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><h1 id="wiki_key_features">Key Features</h1><section><h2 id="details-setup">Open the four huts and locate your perks</h2><ol><li id="guide-step-shi-open" data-guide-step>From the upper starting floor, buy either the stairs or the hanging-body-room debris to reach the ground floor. Four paths lead outward to Doctor’s Quarters, Fishing Hut, Storage and the Comm Room. Check the destination sign before opening a path so your team can call locations consistently.</li>
<li id="guide-step-shi-perks" data-guide-step>Opening a hut reveals one of four random perks: Jugger-Nog, Speed Cola, Double Tap or Quick Revive. Search the other huts if the first one does not contain the perk you need. There is no power switch. In solo, Quick Revive costs 500 and provides up to three self-revives. In co-op it speeds up revives instead. Double Tap increases fire rate; it is not Double Tap II. Mule Kick is available with the BO1 title update.</li>
<li id="guide-step-shi-box" data-guide-step>The Mystery Box starts upstairs in the main building and can move to the huts after the teddy bear. Its beam helps locate it. The Wunderwaffe DG-2 chains electricity through a group; the Ray Gun supplies a different ranged option. Neither has a build quest here, and there is no normal upgrade machine.</li>
<li id="guide-step-shi-dogs" data-guide-step>Hellhound rounds replace the ordinary wave and finish with Max Ammo. Hold a position with room to back away and reload before taking the last dog’s drop. Keep a close-range weapon ready when travelling through swamp water.</li></ol></section>
<section><h2 id="details-routes">Flogger, electric traps and the Doctor’s zipline</h2><ol><li id="guide-step-shi-flogger" data-guide-step>The Flogger stands outside the main building on the Fishing Hut side. Activate it for 750 points when the horde is approaching, then stay clear of its rotating arms. Both zombies and players can be struck; cross only after it stops.</li>
<li id="guide-step-shi-hut-traps" data-guide-step>Hut electric traps cost 1,000 points. Leave enough space to retreat instead of entering a dead-end hut while a trap is active. Swamp water slows movement: use boardwalks to move between areas and keep the next dry exit in view.</li>
<li id="guide-step-shi-zipline" data-guide-step>Doctor’s Quarters connects to the main building by a zipline. Use its control to position the carrier before boarding, and keep points available for the trip. It is an escape/transport option, not a quest requirement.</li></ol></section>
<h1 id="wiki_side_quests">Side Quests</h1><section><h2 id="details-music">The One</h2><ol><li id="guide-step-shi-song" data-guide-step>Inside the Comm Room hut, face the black telephone and interact three times. Listen for each response; after the final interaction, The One begins. This is the Dead Air musical secret.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/shi-no-numa/song_ee/phone.webp&quot;,&quot;alt&quot;:&quot;phone&quot;}]' /></li></ol></section>
<section><h2 id="details-story">Starting-room radios and the Element 115 clues</h2><ol><li id="guide-step-shi-radio" data-guide-step>Activate the three small radios around the upstairs starting building: one by the Arisaka wall buy, one on the shelf beside the blocked staircase and one near the Gewehr wall buy. Once all register, the coded transmission plays. Keep the last zombie away so you can listen.</li>
<li id="guide-step-shi-meteor" data-guide-step>On the Storage route, inspect the large Element 115 meteor outside the playable path. A shot or interaction can prompt a character remark. The hanging body in the starting building and the writing around the huts are story details; they do not lead to a console/PC free-Wunderwaffe reward.</li>
<li id="guide-step-shi-hut-radios" data-guide-step>For the whispered recording, enter the room to the left of the Doctor’s Quarters entrance and activate its radio. In Storage, the radio beside the Mystery Box plays audio from the Verrückt trailer. Interacting with the Doctor’s Quarters bookcase also triggers a laugh; the large Comm Room radio equipment and Fishing Hut provide additional ambient sounds.</li>
<li id="guide-step-shi-future" data-guide-step>For the BO1 time-travel conversation, activate three more radios in any order: on a crate in Storage’s right-hand room; on the corner shelf in the right half of the Comm Room; and on a crate in the outside shelter immediately before the Doctor’s Quarters door. The first two play static; the third plays the full Ultimis exchange. Finish at Doctor’s Quarters for less background noise.</li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Written for Black Ops (2010), with its title updates; mobile editions and modded maps can differ. Community guides and illustrated references were cross-checked on 3 October 2026. Gameplay: Activision / Treyarch; photographs: the credited community authors below. Reused photographs may show a remaster of the same location; the instructions describe this edition. Source review and software checks are not an in-game playthrough.</p><ul><li><a href="https://www.reddit.com/r/CODZombies/wiki/shi-no-numa/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide ↗</a></li>
<li><a href="https://mmmrkennedy.com/games/WAW/shi_no_numa/shi_no_numa_guide" target="_blank" rel="noopener noreferrer">mmmrkennedy illustrated guide (2) ↗</a></li>
<li><a href="https://strategywiki.org/wiki/Call_of_Duty%3A_World_at_War/Nazi_Zombies" target="_blank" rel="noopener noreferrer">strategywiki.org reference (3) ↗</a></li>
<li><a href="https://callofduty.fandom.com/wiki/Shi_No_Numa/Radio_Messages" target="_blank" rel="noopener noreferrer">callofduty.fandom.com reference (4) ↗</a></li></ul><p>Select any reference image to enlarge it. Screenshot and symbol sources are credited in the linked walkthroughs; this guide uses local copies for reliable access.</p></section></div></template>
