<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><h1 id="wiki_key_features">Key Features</h1><section><h2 id="details-setup">Power and the stage route</h2><ol><li id="guide-step-kino-power" data-guide-step>From the lobby, buy the upstairs route through the rooms, Speed Cola area and Dressing Room to the stage, or take the lower Alley route around the other side. Switch on power at the side of the stage to lift the curtain and open the central theatre loop.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/kino-der-toten/power/power.webp&quot;,&quot;alt&quot;:&quot;on the stage&quot;}]' /></li>
<li id="guide-step-kino-perks" data-guide-step>Jugger-Nog is beside the theatre’s rear seating; Quick Revive is in the lobby, Speed Cola on the upper indoor route and Double Tap in the Alley. In solo, Quick Revive provides up to three self-revives. Updated BO1 also adds Mule Kick, but no Wunderfizz. Double Tap is the original fire-rate version.</li>
<li id="guide-step-kino-kit" data-guide-step>The Mystery Box can give the Thundergun, Ray Gun and Monkey Bombs. Save the Thundergun for clearing a blocked route; it does not refill from ordinary wall ammunition. Use a replenishable wall gun to earn points, and keep explosive Ray Gun shots away from your feet because this map has no PhD Flopper.</li></ol></section>
<section><h2 id="details-pap">Link the teleporter and use Pack-a-Punch</h2><ol><li id="guide-step-kino-link" data-guide-step>Interact with the teleporter pad on the stage to begin a link. Run to the circular mainframe pad in the lobby and interact again to finish it. Gather everyone who wants to upgrade inside the stage teleporter before activating it.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/kino-der-toten/pap/teleporter_pad.webp&quot;,&quot;alt&quot;:&quot;teleporter pad in the spawn room&quot;},{&quot;src&quot;:&quot;/images/chronicles/kino-der-toten/pap/mainframe.webp&quot;,&quot;alt&quot;:&quot;teleporter mainframe on the stage&quot;}]' /></li>
<li id="guide-step-kino-upgrade" data-guide-step>The teleporter sends its occupants to the projection booth for about 30 seconds. Pack-a-Punch costs 5,000 points. Retrieve your gun before the forced return; the clock over the machine shows the remaining window. A random intermission room may appear before you return to the lobby.</li>
<li id="guide-step-kino-relink" data-guide-step>Wait about a minute for the teleporter to cool down, then repeat the stage-to-lobby link for another trip. Use a final zombie to make film-reel trips safer. You cannot stay in the booth indefinitely by continuing to buy upgrades.</li></ol></section>
<section><h2 id="details-survival">Traps, gas crawlers and dog rounds</h2><ol><li id="guide-step-kino-traps" data-guide-step>The electric doorway traps and Alley fire trap cost 1,000 points with power on. Lead zombies into the trap and move along a different route; its damage also threatens teammates. The automatic turrets cost 1,500 and can create crossfire, so check everyone’s path before activating one.</li>
<li id="guide-step-kino-nova" data-guide-step>Gas crawlers begin appearing after power. Their death clouds can obscure your view and harm you; shoot them outside your immediate escape path. Keep a mobile circle around the stage and leave gaps between teammates so one player does not block another’s train.</li>
<li id="guide-step-kino-dogs" data-guide-step>Hellhound rounds end with Max Ammo. Find an open firing lane, cover reloads in co-op and reload all weapons before collecting the final drop. Treat the following regular round as a fresh wave rather than staying distracted by the pickup.</li></ol></section>
<h1 id="wiki_side_quests">Side Quests</h1><section><h2 id="details-music">115: three meteor fragments</h2><ol><li id="guide-step-kino-song" data-guide-step>Interact with the fragment in the jar under the lobby stairs near Quick Revive, the fragment by the mannequins behind the Dressing Room MP5K, and the fragment on the letter-filled shelf in the upstairs Alley room. Listen for each activation sound. All three start 115.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/kino-der-toten/song_ee/rock_spawn.webp&quot;,&quot;alt&quot;:&quot;Spawn Room - In a jar near a Zombie barrier, \&quot;below\&quot; the stairs closest to Quick Revive&quot;},{&quot;src&quot;:&quot;/images/chronicles/kino-der-toten/song_ee/rock_dressing_room.webp&quot;,&quot;alt&quot;:&quot;Dressing Room - On a stand by some mannequins, behind the MP5K/KN-44 wallbuy&quot;},{&quot;src&quot;:&quot;/images/chronicles/kino-der-toten/song_ee/rock_alley.webp&quot;,&quot;alt&quot;:&quot;Upstairs Alley Room - On a shelf with the letters, right of a zombie spawn&quot;}]' /></li></ol></section>
<section><h2 id="details-films">Three film reels and the projector</h2><ol><li id="guide-step-kino-reels" data-guide-step>On return from Pack-a-Punch, quickly search the random room for a flat film reel and press interact to collect it. The visit lasts only a few seconds, so start with the surfaces below. Room selection is random; an empty visit does not mean the secret failed.<ul><li>Intact bedroom: check the bed, table and chair area.</li><li>Ruined bedroom: check the bed frame, table and window ledge.</li><li>Dentist room: check the cart beside the chair and both counters.</li><li>Pentagon conference room: check the front table and the TV/projector surfaces.</li></ul></li>
<li id="guide-step-kino-project" data-guide-step>On a later trip, interact with the film projector beside Pack-a-Punch to load your reel and hear the recording. Repeat until you have found and played all three films. These are story clips; they do not open a boss room or award a wonder weapon.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/kino-der-toten/film_reels/projector.webp&quot;,&quot;alt&quot;:&quot;Projector in the Pack-a-Punch room&quot;}]' /></li></ol></section>
<section><h2 id="details-extras">Rocket model, radios and portraits</h2><ol><li id="guide-step-kino-rocket" data-guide-step>With power on, jump five times in front of the left of the two Dressing Room mannequins near the Speed Cola doorway. On a return trip that lands in the Pentagon-style conference room, interact with the small rocket model on the table. Community descriptions also associate this model with completing the film reels; finish those if the model does not respond. Its launch is a small visual secret.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/kino-der-toten/rocket_launch/mannequins.webp&quot;,&quot;alt&quot;:&quot;two mannequins&quot;},{&quot;src&quot;:&quot;/images/chronicles/kino-der-toten/rocket_launch/rocket.webp&quot;,&quot;alt&quot;:&quot;Rocket model&quot;}]' /></li>
<li id="guide-step-kino-radios" data-guide-step>Shoot the radio on the chandelier above the theatre. For the other recording, look out from the Alley toward the distant tower beyond the barrier and shoot its radio with a precise weapon. Let one clip finish before triggering the other or the meteor song.</li>
<li id="guide-step-kino-portraits" data-guide-step>In the upstairs lobby portrait gallery, interact with the character portraits for comments; the blank picture also gets a response. These voices, the reels and the radios provide lore without a further quest chain.</li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Written for Black Ops (2010), with its title updates; mobile editions and modded maps can differ. Community guides and illustrated references were cross-checked on 3 October 2026. Gameplay: Activision / Treyarch; photographs: the credited community authors below. Reused photographs may show a remaster of the same location; the instructions describe this edition. Source review and software checks are not an in-game playthrough.</p><ul><li><a href="https://www.reddit.com/r/CODZombies/wiki/kino-der-toten/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide ↗</a></li>
<li><a href="https://mmmrkennedy.com/games/BO1/kino_der_toten/kino_der_toten_guide" target="_blank" rel="noopener noreferrer">mmmrkennedy illustrated guide (2) ↗</a></li>
<li><a href="https://www.reddit.com/r/CODZombies/comments/4p0mbg/kino_der_toten_complete_map_breakdown/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide (3) ↗</a></li>
<li><a href="https://call-of-duty-nazi-zombies.fandom.com/wiki/Kino_der_Toten/Film_Reels_and_Radios" target="_blank" rel="noopener noreferrer">call-of-duty-nazi-zombies.fandom.com reference (4) ↗</a></li></ul><p>Select any reference image to enlarge it. Screenshot and symbol sources are credited in the linked walkthroughs; this guide uses local copies for reliable access.</p></section></div></template>
