<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><h1 id="wiki_key_features">Key Features</h1><section><h2 id="details-setup">House, barn and four perks</h2><ol><li id="guide-step-setup-house" data-guide-step>Open the farmhouse, take an MP5 when you can afford it and work toward Jugger-Nog upstairs. Speed Cola is downstairs; the Box sits on the upper balcony. Learn the balcony drop before you use it under pressure, then move away from its landing point.</li>
<li id="guide-step-setup-barn" data-guide-step>Quick Revive is outside near the barn and Double Tap is upstairs in the barn. Perks already have power. Use the barn doorway and upper opening as two different exits, checking the ground before dropping. The photographed barn is a shared TranZit layout reference; this standalone mode has different equipment.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/bo2/farm/farm.png&quot;,&quot;alt&quot;:&quot;Farm barn exterior and upper escape opening. Shared TranZit layout reference by art director Daniel Romeo Padilla; Survival equipment differs.&quot;}]' /></li>
<li id="guide-step-setup-gear" data-guide-step>There is no Pack-a-Punch machine or way to build one in this arena. A wall weapon with refillable ammo is therefore valuable even beside a stronger Box gun. In Survival, Galvaknuckles in the small shed cost 6,000 and help early melee point building; do not rely on one-hit melee indefinitely.</li></ol></section>
<section><h2 id="details-survive">Control the yard</h2><ol><li id="guide-step-survive-yard" data-guide-step>Gather zombies in the yard with a wide loop and leave room around the central obstacles. Watch spawns from both buildings before cutting across. When the yard becomes crowded, use a building route only if you can see its exit; narrow stairs are poor places to turn around.</li>
<li id="guide-step-survive-coop" data-guide-step>Assign the house and barn sides to different players and call out a balcony drop. Two independent trains crossing the middle can trap both players. Clear zombies away from a downed teammate before attempting the revive, and keep one player free to rescue the rescuer.</li>
<li id="guide-step-survive-rebuild" data-guide-step>After a down, take a nearby wall gun before gambling on the Box, then recover Jugger-Nog. Solo Quick Revive supplies limited self-revives; co-op Quick Revive speeds teammate revives. The farmhouse fridge is not a working TranZit weapon locker in standalone Farm.</li></ol></section>
<section><h2 id="details-grief">Farm in Grief</h2><ol><li id="guide-step-grief-layout" data-guide-step>The house balcony and barn stairs are the main pressure points. Avoid waiting behind an opponent at the Box; they can hold the doorway while fresh zombies arrive. Pay for a usable escape route when it is needed rather than losing the team while waiting for the opposition to open it.</li>
<li id="guide-step-grief-win" data-guide-step>Grief pits two teams against the zombies. You cannot kill an opponent directly with bullets, but shots slow them and melee can push them. When the other team is completely down, your team still has to survive the remaining zombies to win. If both teams fail, the round can restart. Guard teammates and preserve an escape route instead of chasing an opponent into a corner.</li>
<li id="guide-step-grief-drops" data-guide-step>Most pickups benefit the team that collects them. Call out Max Ammo before anyone spends their last magazine; coordinate revives around Insta-Kill or a Nuke. The meat pickup attracts zombies to its landing point or the player it hits. Use it to redirect a crowd away from a revive. A Fire Sale opens Box opportunities for both teams, so check who controls each approach.</li>
<li id="guide-step-grief-revive" data-guide-step>Clear the approach before reviving. Opponents can obstruct the doorway or push an upright reviver; crouching makes you harder to displace. Do not dive onto a prone player: the collision can down both of you. Keep one teammate outside the rescue so a failed revive does not end your team.</li></ol></section>
<h1 id="wiki_side_quests">Side Quests</h1><section><h2 id="details-secrets">Mode boundaries</h2><ol><li id="guide-step-secrets-scope" data-guide-step>Farm has no separate main Easter egg, buildable quest or complete music activation. Turbine doors, bus parts, weapon storage and the teddy sequence belong to full TranZit. They are covered in that guide so you do not spend a Survival run chasing unavailable interactions.<p><a href="/guides/bo2-tranzit">TranZit equipment and side secrets ↗</a></p></li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Written for the original Black Ops II release, on Original difficulty unless a mode is specified. Instructions were cross-checked against the linked community sources on 3 October 2026. Gameplay: Activision / Treyarch; photographs and charts: COD Zombies Guides, its credited contributors, mmmrkennedy and other sources named below. Shared-layout images may show another edition; follow the BO2 instructions. Source review and website checks are not an in-game playthrough.</p><ul><li><a href="https://callofduty.fandom.com/wiki/Farm" target="_blank" rel="noopener noreferrer">callofduty.fandom.com reference ↗</a></li>
<li><a href="https://gamefaqs.gamespot.com/ps3/669288-call-of-duty-black-ops-ii/faqs/65280" target="_blank" rel="noopener noreferrer">GameFAQs original BO2 walkthrough (2) ↗</a></li>
<li><a href="https://www.callofduty.com/content/dam/atvi/callofduty/blackops2/cod-bo2/manuals/Manual_WiiU_EN.pdf" target="_blank" rel="noopener noreferrer">Official Call of Duty guide (3) ↗</a></li></ul><p>Select any reference image to enlarge it. Screenshot and symbol sources are credited in the linked walkthroughs; this guide uses local copies for reliable access.</p></section></div></template>
