<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><h1 id="wiki_key_features">Key Features</h1><section><h2 id="details-setup">Open the forecourt and secure ammunition</h2><ol><li id="guide-step-setup-door" data-guide-step>Use the starting M14 or Olympia to earn the 750 points needed for the depot exit. Avoid committing to a knife lunge after taking a hit. Open the exit before several windows are overwhelmed; the terminal has too little space to recover from a blocked doorway.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/bo2/bus-depot/bus-depot.webp&quot;,&quot;alt&quot;:&quot;Bus Depot exterior in TranZit. The standalone Survival mode removes bus travel and perks.&quot;}]' /></li>
<li id="guide-step-setup-weapons" data-guide-step>Outside, use the MP5 or Remington 870 MCS wall purchase for a weapon with a dependable ammo supply. The Mystery Box sits in the forecourt; take a spin only with a clear approach and enough ammunition to recover from a poor result. There is no upgrade machine to rescue a weak weapon later.</li>
<li id="guide-step-setup-limits" data-guide-step>You cannot obtain Jugger-Nog, Quick Revive or Pack-a-Punch in this mode. In solo a down ends the run. In co-op a teammate must revive you. Do not spend a round searching the terminal for Turbine parts or trying to call the TranZit bus.</li></ol></section>
<section><h2 id="details-survive">A repeatable survival route</h2><ol><li id="guide-step-survive-circle" data-guide-step>Gather zombies around the open forecourt, keeping the pillars and wreckage on a consistent side. Look ahead at fresh spawns rather than watching only the train behind you. Cut to a wider line when a zombie crosses the route; reversing into the following horde is usually fatal.</li>
<li id="guide-step-survive-fire" data-guide-step>Hop over lava cracks and allow your health to recover before passing a zombie. Fire and an immediate melee hit can combine into a down. Burning zombies explode when killed: fire at the head of the train from a distance, then run past the cleared space.</li>
<li id="guide-step-survive-team" data-guide-step>In co-op, agree on one direction of travel and avoid dragging two trains into the depot door at once. Keep one manageable zombie while players buy ammo. For a rescue, pull the crowd away first, then have another player revive; there is no Quick Revive shortcut here.</li></ol></section>
<h1 id="wiki_side_quests">Side Quests</h1><section><h2 id="details-scope">Secrets and mode boundaries</h2><ol><li id="guide-step-scope-secrets" data-guide-step>There is no main quest, song activation sequence or buildable reward in the standalone Bus Depot Survival arena. The teddy, workbench and bus-related activities seen in full TranZit walkthroughs do not make a completable quest here. Use the TranZit guide for those systems.<p><a href="/guides/bo2-tranzit">Full TranZit map guide ↗</a></p></li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Written for the original Black Ops II release, on Original difficulty unless a mode is specified. Instructions were cross-checked against the linked community sources on 3 October 2026. Gameplay: Activision / Treyarch; photographs and charts: COD Zombies Guides, its credited contributors, mmmrkennedy and other sources named below. Shared-layout images may show another edition; follow the BO2 instructions. Source review and website checks are not an in-game playthrough.</p><ul><li><a href="https://www.callofduty.com/content/dam/atvi/callofduty/blackops2/cod-bo2/manuals/Manual_WiiU_EN.pdf" target="_blank" rel="noopener noreferrer">Official Call of Duty guide ↗</a></li>
<li><a href="https://callofduty.fandom.com/wiki/Bus_Depot" target="_blank" rel="noopener noreferrer">callofduty.fandom.com reference (2) ↗</a></li>
<li><a href="https://discover.hubpages.com/games-hobbies/Black-Ops-2-Zombies-Bus-Depot-on-Survival-Mode-Strategy-Tips" target="_blank" rel="noopener noreferrer">Edward D. Saterstad illustrated reference (3) ↗</a></li></ul><p>Select any reference image to enlarge it. Screenshot and symbol sources are credited in the linked walkthroughs; this guide uses local copies for reliable access.</p></section></div></template>
