<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><h1 id="wiki_key_features">Key Features</h1><section><h2 id="details-setup">Arthur, weapon chalk and the town</h2><ol><li id="guide-step-setup-drop" data-guide-step>Before dropping from the starting processing platform, decide whether to save 2,000 points for the LSAT above spawn. Jump and climb onto its short ledge to buy it before the platform gives way. Once below, take Quick Revive if playing solo, use the tunnels to reach town and look for the jail beside the initial Mystery Box. The LSAT is optional; falling into town does not block the quest.</li>
<li id="guide-step-setup-arthur" data-guide-step>Enter the jail from above and take the key on the wall to open Arthur’s cell. Give him the bottle of booze from inside. He charges away from the player who hands it over, so position his back toward the barrier you want broken. Free the Jugger-Nog alley and the approach to the mansion early. If you shoot him, he retreats to his cell; search the jail, courthouse judge’s bench, upstairs saloon or bank for the key to release him again.</li>
<li id="guide-step-setup-chalk" data-guide-step>Take a chalk weapon outline from the gunsmith and draw it at a question-mark wall. Each placement awards points, with a larger reward for the last one. Put a weapon you can refill on a route you actually use, such as the AN-94 near the main street. Chalk, booze and candy share a carried-item slot; finish a delivery before collecting another item.</li>
<li id="guide-step-setup-perks" data-guide-step>There is no central power switch. Jugger-Nog is at the end of the blocked alley by the jail; Speed Cola is upstairs in General Store; Mule Kick is upstairs in the gunsmith; Stamin-Up is in the courthouse; Double Tap is at the mansion entrance; Vulture Aid is in Church; Quick Revive is near the starting drop. Vulture Aid highlights useful objects and creates occasional ammunition/point drops and green hiding clouds.</li></ol></section>
<section><h2 id="details-pack-a-punch">Mansion, maze and Pack-a-Punch</h2><ol><li id="guide-step-pap-mansion" data-guide-step>Have Arthur break the mansion barrier, then enter with a loaded weapon. Ghost women take 2,000 points per hit, so move together, check behind you and kill them before contact. Follow the entry rooms through the moving bookcase, upstairs and out the rear into the maze. Do not stop at the entrance to fight an endless flow while teammates remain in the house.</li>
<li id="guide-step-pap-maze" data-guide-step>Navigate the hedge maze from the mansion’s rear to the gazebo, checking the metal gates for the current route. Its configuration can change between rounds. At the gazebo, descend the spiral stairway for Pack-a-Punch and pay 5,000 points. Stop on each stair segment: there are gaps that can kill you if you rush or backpedal. Keep a teammate watching the approach while a weapon is inside the machine.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/bo2/buried/maze.webp&quot;,&quot;alt&quot;:&quot;maze&quot;}]' /></li>
<li id="guide-step-pap-return" data-guide-step>For a shortcut back to the surface starting area, first have Arthur smash the town fountain and destroy the maze fountain with explosives. Only jump into the maze fountain when the portal is visibly active. An unprepared fountain is a lethal hole. The return route lets you revisit upper processing; it does not give a second chance at the collapsed LSAT ledge.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/bo2/buried/fountain.webp&quot;,&quot;alt&quot;:&quot;fountain&quot;}]' /></li></ol></section>
<section><h2 id="details-equipment">Buildables, Paralyzer and Time Bomb</h2><ol><li id="guide-step-store-parts" data-guide-step>Use the General Store’s ground floor and upstairs landing to collect the trap parts. Deliver each piece before picking up another; a character can carry only one buildable part. If you want Arthur to help, install the first piece of the desired device at the chosen bench before giving him candy there.<ul><li>Turbine: tail fin on the ground-floor corner bookshelf; mannequin in the back-room corner; fan on an upstairs shelf.</li><li>Resonator: roulette wheel/speaker by the weapon-locker counter; turntable on the ground floor near the locker; wooden base at the rear passage; motor at the top of the stairs.</li><li>Head Chopper: crank on the centre shelf; hinge on the front counter’s right; saw in the barrel behind the counter’s left; stand in the rear room.</li><li>Trample Steam: collect the mesh screen, motor, bellows and flag from the General Store; its workbench does not supply parts from Die Rise.</li></ul></li>
<li id="guide-step-buildables" data-guide-step>All ordinary buildable parts are in the General Store. Carry one at a time to a bench in the courthouse, saloon, upstairs building beside the jail or Church. Turbine: mannequin, fan and tail; Trample Steam: mesh, flag, compressor and bellows; Head Chopper: saw, crank, hinge and stand; Subsurface Resonator: roulette wheel/speaker, turntable, wooden mount and motor. Decide the first item at a bench before adding an incompatible part.</li>
<li id="guide-step-resonator" data-guide-step>A Subsurface Resonator fires only while a Turbine powers it; face its dish at the target and keep the Turbine nearby. Maxis needs this pair to destroy the four crystal orbs. A Trample Steam offers roof access without needing the Paralyzer. Replace broken equipment at its original bench.</li>
<li id="guide-step-paralyzer" data-guide-step>The Paralyzer and Time Bomb come from the Mystery Box. The Paralyzer has a heat meter instead of ammunition; let it cool when near its limit. Aim at the ground while jumping to lift yourself, then feather the beam on descent to avoid falling damage. Pack-a-Punch turns it into the slower-heating Petrifier. The Time Bomb records the match at placement and rewinds when triggered; tell your team before using it because it can undo purchases and positions.</li></ol></section>
<h1 id="wiki_main_quest">Main Quest</h1><section><h2 id="details-choose-route">Mined Games — choose a route and charge the lantern</h2><ol><li id="guide-step-quest-requirements" data-guide-step>Use four players and Original difficulty. Richtofen requires a Paralyzer, Vulture Aid, Time Bomb and Bowie Knife or Galvaknuckles. Maxis requires a Turbine/Resonator pair, Time Bomb and Bowie Knife or Galvaknuckles; the Paralyzer is useful for travel but is not his orb weapon. Choose your structure before building: the two branches share the wire and antenna.</li>
<li id="guide-step-quest-structure" data-guide-step>Richtofen: build the Guillotine beside the saloon using the dish on its upstairs balcony, wire spool downstairs in the gunsmith, crystal in the upper tunnels near Lunger Undermines and antenna in the barn’s lower stable. Maxis: build the Gallows near the courthouse with that wire and antenna, the bulb above the jail and the battery behind Church’s pulpit.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/bo2/buried/satellite-dish-top-balcony-of-saloon.webp&quot;,&quot;alt&quot;:&quot;satellite dish top balcony of saloon&quot;},{&quot;src&quot;:&quot;/images/bo2/buried/spool-of-wire-corner-of-the-gunsmith.webp&quot;,&quot;alt&quot;:&quot;spool of wire corner of the gunsmith&quot;},{&quot;src&quot;:&quot;/images/bo2/buried/crystal-near-lunger-undermines.webp&quot;,&quot;alt&quot;:&quot;crystal near lunger undermines&quot;},{&quot;src&quot;:&quot;/images/bo2/buried/antennae-bottom-of-the-barn-in-a-far-stable-on-the-right.webp&quot;,&quot;alt&quot;:&quot;antennae bottom of the barn in a far stable on the right&quot;},{&quot;src&quot;:&quot;/images/bo2/buried/bulbs-above-jail-cell.webp&quot;,&quot;alt&quot;:&quot;bulbs above jail cell&quot;},{&quot;src&quot;:&quot;/images/bo2/buried/battery-behind-chruch-podium.webp&quot;,&quot;alt&quot;:&quot;battery behind chruch podium&quot;}]' /></li>
<li id="guide-step-quest-orbs" data-guide-step>Find the four red orbs: saloon/candy-store alley, rock left of Church, upper tunnels near Lunger Undermines, and foliage at the mansion’s rear maze entrance. For Richtofen, hold the Paralyzer on each until it turns white and chimes. For Maxis, destroy each with a Turbine-powered Subsurface Resonator. Confirm all four before looking for the lantern.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/bo2/buried/orb-between-candy-store-and-saloon.webp&quot;,&quot;alt&quot;:&quot;orb between candy store and saloon&quot;},{&quot;src&quot;:&quot;/images/bo2/buried/orb-graveyard-left-of-church.webp&quot;,&quot;alt&quot;:&quot;orb graveyard left of church&quot;},{&quot;src&quot;:&quot;/images/bo2/buried/orb-near-lunger-undermines.webp&quot;,&quot;alt&quot;:&quot;orb near lunger undermines&quot;},{&quot;src&quot;:&quot;/images/bo2/buried/orb-behind-the-witches-mansion.webp&quot;,&quot;alt&quot;:&quot;orb behind the witches mansion&quot;}]' /></li>
<li id="guide-step-quest-lantern" data-guide-step>After the dialogue, knock down the floating purple lantern with a cooked grenade or explosive and collect it. Richtofen: its carrier kills ghost women in the mansion until the charge cue. Maxis: keep the carrier near zombies killed by Arthur, traps or a Nuke until charged; ordinary gun kills do not substitute. Let Maxis finish speaking before picking it up. If downed, recover the lantern where you lost it.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/bo2/buried/glowing-lantern.webp&quot;,&quot;alt&quot;:&quot;glowing lantern&quot;}]' /></li>
<li id="guide-step-quest-roof" data-guide-step>Reach the gunsmith roof by Paralyzer, Trample Steam or the connected roof route and place the charged lantern on its chalk mark. Three encoded lines appear on the wall. The following sign helper applies to both branches; the wisp behavior afterwards is different.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/bo2/buried/lantern-symbol-atop-the-gunsmith-roof.webp&quot;,&quot;alt&quot;:&quot;lantern symbol atop the gunsmith roof&quot;}]' /></li></ol></section>
<section><h2 id="details-cipher">Read the three mine signs</h2><ol><li id="guide-step-cipher-read" data-guide-step>Each wall line names one mine sign. Match its first two shapes in the helper, preserving both the white outline and which side contains the red stroke. Confirm against the full pictured line if two corners look alike. The five names are Dry Gulcher Shaft, Bone Orchard Vein, Lunger Undermines, Ground Biter Pits and Consumption Cross. You need three distinct names, not every sign.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/bo2/buried/cipher-key.webp&quot;,&quot;alt&quot;:&quot;cipher key&quot;}]' /></li>
<li id="guide-step-cipher-melee" data-guide-step>Find the named wooden signs along the upper mine tunnels and strike only those three with the Bowie Knife or Galvaknuckles. There is no universal wall-line strike order; the last sign struck determines where the wisp begins. Before the final hit, position the team for the correct branch below. For Maxis, place your Time Bomb first.</li></ol><InlineTool tool="bo2-buried-signs" /></section>
<section><h2 id="details-richtofen-wisp">Richtofen — wisp and Round Infinity</h2><ol><li id="guide-step-richtofen-wisp" data-guide-step>A player with Vulture Aid must touch the newly spawned wisp and follow its hops toward the Guillotine. Look along the barn upper floor, jail upper floor, General Store upper floor and candy store as it moves. A roughly fifteen-second gap without contact makes it disappear; hit the same three signs again to restart. Other players should hold zombies away from the runner.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/bo2/buried/richtofen-wisp.webp&quot;,&quot;alt&quot;:&quot;richtofen wisp&quot;}]' /></li>
<li id="guide-step-richtofen-souls" data-guide-step>At the Guillotine, let the wisp enter nearby zombies, then kill those glowing zombies near the structure one at a time. Continue until Richtofen requests the Time Bomb. Normal zombies killed before receiving the glow do not count.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/bo2/buried/glowing-zombie.webp&quot;,&quot;alt&quot;:&quot;glowing zombie&quot;}]' /></li>
<li id="guide-step-richtofen-infinity" data-guide-step>Put a Time Bomb on the Guillotine bench. Gather all four players around it and detonate to enter Round Infinity. Zombies are invulnerable here; avoid fighting and split the search for four fallen crew bodies. Interact with each body to find the switch. Search the main streets around the saloon/Guillotine, gunsmith and barn gap, jail, General Store/Box, candy-store entrance and arrow sign, Church rock/workbench and mansion barrier.<p class="guide-callout">The search window is brief. Sources disagree on its exact duration, so follow the in-game transition and do not rely on a web timer.</p></li>
<li id="guide-step-richtofen-switch" data-guide-step>After the game automatically returns to your original round, fit the recovered switch to the Guillotine. If you ran out of time without finding it, obtain another Time Bomb and repeat the search. Protect the carrier until the part is installed. Now continue to the maze levers.</li></ol></section>
<section><h2 id="details-levers">Richtofen — solve the maze lever order</h2><ol><li id="guide-step-lever-test" data-guide-step>Locate the red, green, blue and yellow levers on the maze gates. Flip each once in a chosen order, then inspect all four: feedback appears after the fourth lever. A spark means that colour was in its correct position in the sequence. A non-sparking lever was in the wrong position. Record both observations in the helper after every complete attempt.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/bo2/buried/maze.webp&quot;,&quot;alt&quot;:&quot;maze&quot;}]' /></li>
<li id="guide-step-lever-repeat" data-guide-step>Everyone must leave the maze to reset the levers after an unsuccessful attempt. Return and try the helper’s suggested order; the helper retains positions proved right and eliminates positions proved wrong. If it reports no possible order, correct the recorded attempt or spark feedback rather than forcing another guess. Candy jar colours are not a reliable solution.</li>
<li id="guide-step-lever-finish" data-guide-step>All four levers sparkling in the same attempt completes this branch. Continue to the shared sharpshooter finale. You do not need the Maxis bell step.</li></ol><InlineTool tool="bo2-buried-levers" /></section>
<section><h2 id="details-maxis-wisp">Maxis — escort the wisp twice</h2><ol><li id="guide-step-maxis-prep" data-guide-step>Place a Time Bomb before hitting the final decoded sign. Leave enough live zombies positioned along the wisp’s path: it must pass near them to stay alive. Its path depends on the last sign hit. If Consumption Cross is in your set, hit it last for a route via the barn and saloon; put at least two zombies upstairs in the barn and three in front of the saloon before starting.</li>
<li id="guide-step-maxis-escort" data-guide-step>Follow the orange wisp to the Gallows, keeping zombies close enough for it to draw energy. Do not clear the entire route with weapons. If it fades, strike your sign set again and reposition the zombies. Once it reaches the Gallows, detonate the previously placed Time Bomb. Hit the signs again as needed to respawn it, then escort it successfully a second time. Maxis’s next instruction confirms acceptance.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/bo2/buried/maxis-wisp.webp&quot;,&quot;alt&quot;:&quot;maxis wisp&quot;}]' /></li></ol></section>
<section><h2 id="details-bells">Maxis — the mansion’s nine-light bell puzzle</h2><ol><li id="guide-step-bells-calibrate" data-guide-step>Put one player at the switchboard on the mansion couch beyond the moving bookcase. Put the other three at the upstairs candy-store bells, upstairs barn bells and downstairs courthouse bells. Facing the board, its columns are Candy Store, Barn, Courthouse from left to right. Before activating the sequence, ring each bell and let the board player report which row lights. Save those observed correspondences in the helper.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/bo2/buried/switchboard.webp&quot;,&quot;alt&quot;:&quot;switchboard&quot;}]' /></li>
<li id="guide-step-bells-locations" data-guide-step>Candy Store: square table by the wall, table with two pots by the couch barrier, and chair beside the stair doorway. Barn: hay bale by the wall opening, hay bale by the railing gap, and hay bale near the drop toward jail. Courthouse: corner just inside the entrance, judge’s bench, and table to the right of the bench. These landmark names are the helper’s callouts.</li>
<li id="guide-step-bells-play" data-guide-step>When everyone is ready, the mansion player interacts with the board. Select the currently lit bulb in the helper and call its displayed room and landmark; the assigned teammate rings that bell immediately. Continue following the live board until the bulbs are green and it shuts off. A wrong bell or slow response resets the sequence; restart at the board using the same tested mapping.<p class="guide-callout">The helper does not run the game timer or invent a sequence. Test the mapping before starting the timed puzzle.</p></li></ol><InlineTool tool="bo2-buried-bells" /></section>
<section><h2 id="details-sharpshooter">Both routes — Make a Wish and shoot the targets</h2><ol><li id="guide-step-targets-prep" data-guide-step>Have Arthur break the fountain outside the mansion if it is still covered. Assign one player to each target area: candy store/courthouse street, mansion windows, saloon interior and jail street. Use a full magazine, fast reload and a weapon whose shots you can place accurately. Walk the lanes together before triggering the challenge.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/bo2/buried/fountain.webp&quot;,&quot;alt&quot;:&quot;fountain&quot;},{&quot;src&quot;:&quot;/images/bo2/buried/cowboy-target.webp&quot;,&quot;alt&quot;:&quot;cowboy target&quot;}]' /></li>
<li id="guide-step-targets-fire" data-guide-step>Interact with the fountain to Make a Wish. Shoot every cowboy target in your lane before it disappears; they arrive in waves, so keep sweeping the entire view. One missed target anywhere fails the attempt. Practice the missed lane, reload and trigger the fountain again. All perks and the quest completion cue confirm success. Optional three-map activation below is separate from Mined Games.</li></ol></section>
<h1 id="wiki_side_quests">Side Quests</h1><section><h2 id="details-arthur">Arthur’s candy jobs and the bank</h2><ol><li id="guide-step-arthur-candy" data-guide-step>Free candy appears in the candy shop each round; extra candy or booze costs 1,000 at the appropriate shop counter. Give candy near a crawler so Arthur carries it while you solve puzzles. Do not hit him while he holds it. At a workbench, candy makes him gather parts and finish a buildable; place one desired part first to choose what he builds.</li>
<li id="guide-step-arthur-box" data-guide-step>Candy by an idle Mystery Box makes Arthur lock it at that location; candy while a rolled weapon is still offered rerolls it; candy at an empty Box spawn can make him fetch it. A locked Box cannot be moved this way. Candy near a power-up changes the drop. Keep these jobs distinct from giving candy with no nearby object, which sends him after zombies.</li>
<li id="guide-step-bank" data-guide-step>Deposit/withdraw with the bank keys and use the General Store weapon locker to share eligible saved equipment with TranZit and Die Rise on supported profiles. Withdrawals cost a fee. Avoid activating a casual Time Bomb while teammates spend saved funds; agree on the rewind before purchases.</li></ol></section>
<section><h2 id="details-free-perks">Ghost rewards, double bottles and the piano</h2><ol><li id="guide-step-perks-mansion" data-guide-step>When the mansion’s lights are on, cross it, get everyone out and kill the pursuing ghosts. The last ghost drops a team perk bottle. The reward recharges after several rounds; lights are the practical availability cue. A dark-house trip still risks losing points without granting another bottle.</li>
<li id="guide-step-perks-bomb" data-guide-step>For the Time Bomb double-bottle trick, place a bomb before killing the final reward ghost. Kill her but leave the bottle on the ground, then rewind. Collect the retained bottle and kill the restored final ghost for the second drop. Coordinate before anyone picks up the first bottle; taking it before the rewind spoils this method.</li>
<li id="guide-step-perks-piano" data-guide-step>Obtain the Ballistic Knife from the Box. Stand behind the white floor line in the saloon and fire a blade into the dartboard bullseye. The saloon piano starts playing. Travel through the mansion to the maze, then promptly re-enter from the rear to find a ghost playing the piano. Interact and pay 10 points for a random perk. This is separate from the nine-bell Maxis puzzle.</li></ol></section>
<section><h2 id="details-persistent">Hidden PhD and sniper point bonuses</h2><ol><li id="guide-step-persistent-phd" data-guide-step>Buried’s persistent PhD is earned by repeatedly taking survivable fall damage. Use a short ledge near the jail stairs and recover fully between falls until the green flash. Once acquired, dolphin-diving from a height creates an explosion and protects that dive; an ordinary fall that deals damage removes it. It is a hidden bonus, not a purchasable machine, and belongs to supported persistent-profile modes.</li>
<li id="guide-step-persistent-sniper" data-guide-step>Long-range sniper kills can award a green-flash bonus that adds points to later sniper kills. The SVU-AS is convenient for earning money while keeping a refillable weapon. Maintain accuracy: repeated missed shots can remove the bonus. Persistent upgrades can carry between supported TranZit, Die Rise and Buried matches, but are not available in Borough.<p><a href="https://www.reddit.com/r/CODZombies/comments/1i19a7/official_permapersistent_perks_thread/" target="_blank" rel="noopener noreferrer">Community persistent-upgrade research and loss conditions ↗</a></p></li></ol></section>
<section><h2 id="details-music">Always Running and the saloon piano</h2><ol><li id="guide-step-music-bears" data-guide-step>Interact with three teddy bears: beside Quick Revive after the initial drop, inside a barrel in the candy shop, and beside the bookcase in the mansion’s Double Tap entry room. The third starts Always Running. Use a loaded weapon before entering the house to reach its bear.</li>
<li id="guide-step-music-piano" data-guide-step>After the dartboard/piano secret, interact with the saloon piano to play it. The mansion also contains a Michael Faraday portrait, and books throughout town reference other works. These are optional environmental details, separate from Mined Games.</li></ol></section>
<section><h2 id="details-endgame">Navcards and the optional Victis endgame</h2><ol><li id="guide-step-endgame-nav" data-guide-step>Build Buried’s Navcard table back at upper Processing. Take the board, radio and electrical box from the passage beside the barn, carrying each through the mansion and prepared maze-fountain portal to Processing. The purple meteorite is already beside the table’s build location there. Insert Die Rise’s card. Buried’s card is on a small piece of furniture just outside the mansion’s rear exit and belongs in TranZit. The cycle is TranZit card → Die Rise, Die Rise card → Buried, Buried card → TranZit.</li>
<li id="guide-step-endgame-grid" data-guide-step>For the final activation, all four players must have all three Victis quests saved for the same allegiance and all tables/card links must be complete. Check the 3-by-4 light display at the back of the courthouse: each player’s row should show the same colour for TranZit, Die Rise and Buried. Blue is Richtofen; orange is Maxis. Mob of the Dead and Origins do not contribute.</li>
<li id="guide-step-endgame-button" data-guide-step>When the team is ready, shoot/open the courthouse box and interact with its revealed button. This consumes/resets the saved Victis quest progress. Richtofen’s ending supplies permanent Fire Sale and a four-weapon bonus for that match; Maxis changes control of the zombies and introduces the blue-eyed Richtofen zombie. The story choice is optional after completing the map.<p class="guide-callout">This is an in-game irreversible choice for your saved quest flags. Completing Mined Games does not require pressing it.</p></li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Written for the original Black Ops II release, on Original difficulty unless a mode is specified. Instructions were cross-checked against the linked community sources on 3 October 2026. Gameplay: Activision / Treyarch; photographs and charts: COD Zombies Guides, its credited contributors, mmmrkennedy and other sources named below. Shared-layout images may show another edition; follow the BO2 instructions. Source review and website checks are not an in-game playthrough.</p><ul><li><a href="https://www.reddit.com/r/CODZombies/wiki/buried/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide ↗</a></li>
<li><a href="https://www.codzombiesguides.com/main-quests/black-ops-2/buried/" target="_blank" rel="noopener noreferrer">COD Zombies Guides illustrated walkthrough (2) ↗</a></li>
<li><a href="https://www.codzombieguides.com/buried" target="_blank" rel="noopener noreferrer">JokerAlex21 illustrated guide (3) ↗</a></li>
<li><a href="https://www.reddit.com/r/CODZombies/comments/1i19a7/official_permapersistent_perks_thread/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide (4) ↗</a></li>
<li><a href="https://margwa.net/buried" target="_blank" rel="noopener noreferrer">margwa.net reference (5) ↗</a></li>
<li><a href="https://www.playstationtrophies.org/forum/topic/192628-call-of-duty-black-ops-ii-vengeance-dlc-trophy-guide-and-road-map/" target="_blank" rel="noopener noreferrer">playstationtrophies.org reference (6) ↗</a></li>
<li><a href="https://steamcommunity.com/sharedfiles/filedetails/?id=269864761" target="_blank" rel="noopener noreferrer">Steam Community walkthrough (7) ↗</a></li>
<li><a href="https://www.callofdutyzombies.com/zombie-library/zombies-library/black-ops_ii/buried/nav-card-nav-card-table-r374/" target="_blank" rel="noopener noreferrer">Call of Duty Zombies community research (8) ↗</a></li></ul><p>Select any reference image to enlarge it. Screenshot and symbol sources are credited in the linked walkthroughs; this guide uses local copies for reliable access.</p></section></div></template>
