<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><h1 id="wiki_key_features">Key Features</h1><section><h2 id="details-setup">An opening that survives without Jugger-Nog</h2><ol><li id="guide-step-setup-gun" data-guide-step>Secure the MP5 near the Cafeteria approach for 1,000 points and keep enough money for ammo. With no Jugger-Nog, avoid trading a hit for a knife kill once the crowd grows. Look up as well as forward: zombies enter from the upper walkways and cell openings.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/bo2/mob-of-the-dead/hells_retriever/dog_b23r.webp&quot;,&quot;alt&quot;:&quot;Cell Block layout beneath the catwalks in Mob of the Dead. Grief uses different perk and dog rewards.&quot;}]' /></li>
<li id="guide-step-setup-pap" data-guide-step>Open the upper Cell Block route to Pack-a-Punch; its access door costs 2,000 and the upgrade costs 5,000. Double Tap is nearby. There is no plane flight, bridge trip or power-meter task. Crouch while using the machine to make it harder for opponents to push you off the walkway.</li>
<li id="guide-step-setup-perks" data-guide-step>Double Tap is by Pack-a-Punch, Speed Cola in Warden’s Office, Deadshot in Cafeteria, and PhD Flopper plus Mule Kick in the original Mob spawn room. Jugger-Nog, Quick Revive and Electric Cherry are absent. Double Tap and Speed Cola support a wall-gun setup; PhD supports explosive weapons and safe drops.</li>
<li id="guide-step-setup-explosives" data-guide-step>One alternative is to keep your M1911, upgrade it to Mustang &amp; Sally and buy PhD Flopper. Obtain PhD before firing explosives close to yourself. A third upgraded gun with Mule Kick is expensive to lose, so reserve that investment until ammo and your core setup are secure.</li></ol></section>
<section><h2 id="details-traps">Traps, Box rooms and Brutus</h2><ol><li id="guide-step-traps-rooms" data-guide-step>The Box can be in Cafeteria or Warden’s Office. Acid Sprayers guard the Cafeteria entry; the Fan Trap guards the Office entry. An opponent can switch on a trap while you are buying. Check the room’s exit, keep teammates out of the trap lane and leave promptly after a purchase.</li>
<li id="guide-step-traps-brutus" data-guide-step>Brutus can enter Grief and disrupt the fight. Focus headshots and avoid letting him pin you against an opponent or a trap entrance. If a machine is locked, clear the area before paying to unlock it. A protected ammo purchase is usually more useful than a risky extra Box roll.</li>
<li id="guide-step-traps-movement" data-guide-step>Travel from the upper walkway through the intermediate ledges instead of blindly jumping the full height without PhD. At ground level, watch the narrow Cell Walkway between the main cells and Cafeteria cells. Do not begin a revive where the only exit can be blocked by one opponent.</li></ol></section>
<section><h2 id="details-grief">Win the round</h2><ol><li id="guide-step-grief-win" data-guide-step>Grief pits two teams against the zombies. You cannot kill an opponent directly with bullets, but shots slow them and melee can push them. When the other team is completely down, your team still has to survive the remaining zombies to win. If both teams fail, the round can restart. Guard teammates and preserve an escape route instead of chasing an opponent into a corner.</li>
<li id="guide-step-grief-drops" data-guide-step>Most pickups benefit the team that collects them. Call out Max Ammo before anyone spends their last magazine; coordinate revives around Insta-Kill or a Nuke. The meat pickup attracts zombies to its landing point or the player it hits. Use it to redirect a crowd away from a revive. A Fire Sale opens Box opportunities for both teams, so check who controls each approach.</li>
<li id="guide-step-grief-revive" data-guide-step>Clear the approach before reviving. Opponents can obstruct the doorway or push an upright reviver; crouching makes you harder to displace. Do not dive onto a prone player: the collision can down both of you. Keep one teammate outside the rescue so a failed revive does not end your team.</li></ol></section>
<h1 id="wiki_side_quests">Side Quests</h1><section><h2 id="details-cerberus">Cerberus gives a pickup</h2><ol><li id="guide-step-cerberus-feed" data-guide-step>Feed the Cell Block dog one nearby corpse at a time, allowing it to finish each eating animation. After six fed zombies it produces a pickup at the hell portal area. This reward belongs to Cell Block’s Grief rules; it does not open Hell’s Retriever or lead to the Mob quest.</li>
<li id="guide-step-cerberus-scope" data-guide-step>The prison layout resembles Mob, but Afterlife, the plane, Acid Gat crafting, Retriever, Redeemer and Golden Spork quests are not Cell Block activities. For those, use the full Mob of the Dead map guide.<p><a href="/guides/bo2-mob-of-the-dead">Mob of the Dead full guide ↗</a></p></li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Written for the original Black Ops II release, on Original difficulty unless a mode is specified. Instructions were cross-checked against the linked community sources on 3 October 2026. Gameplay: Activision / Treyarch; photographs and charts: COD Zombies Guides, its credited contributors, mmmrkennedy and other sources named below. Shared-layout images may show another edition; follow the BO2 instructions. Source review and website checks are not an in-game playthrough.</p><ul><li><a href="https://www.callofdutyzombies.com/topic/156717-the-full-cell-block-grief-guide/" target="_blank" rel="noopener noreferrer">Call of Duty Zombies community research ↗</a></li>
<li><a href="https://callofduty.fandom.com/wiki/Cell_Block" target="_blank" rel="noopener noreferrer">callofduty.fandom.com reference (2) ↗</a></li>
<li><a href="https://www.callofduty.com/content/dam/atvi/callofduty/blackops2/cod-bo2/manuals/Manual_WiiU_EN.pdf" target="_blank" rel="noopener noreferrer">Official Call of Duty guide (3) ↗</a></li></ul><p>Select any reference image to enlarge it. Screenshot and symbol sources are credited in the linked walkthroughs; this guide uses local copies for reliable access.</p></section></div></template>
