<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><section><h2 id="details-setup">Key Features: generators and equipment</h2><ol><li id="guide-step-setup-1" data-guide-step>Activate the six generators by staying within their capture areas and defeating the attacking templars. All six must be powered to use Pack-a-Punch.</li>
<li id="guide-step-setup-2" data-guide-step>Collect shield parts around the generator routes and build it at a workbench. Take a shovel from a starting location and dig marked sites for equipment.</li>
<li id="guide-step-setup-3" data-guide-step>Collect the gramophone in the excavation and the black record near the mound. Place the gramophone to open the lower excavation, then retrieve it for the elemental tunnels.</li>
<li id="guide-step-setup-4" data-guide-step>Each staff needs its colored record, three parts and the crystal from its matching Crazy Place portal. Leave the portal open until you return, then recover the gramophone.</li></ol></section>
<section><h2 id="details-staff-build">Build the four staffs</h2><ol><li id="guide-step-staff-build-1" data-guide-step>Ice: dig glowing excavation sites while it is snowing, searching the spawn, middle and church regions for its three parts. Take the blue record from the Tank Station area and obtain the ice crystal through the church tunnel.</li>
<li id="guide-step-staff-build-2" data-guide-step>Fire: collect the part dropped by a Panzer, shoot down the glowing plane and collect its drop, and take the Generator 6 reward part. Find the red record around the church and obtain the fire crystal.</li>
<li id="guide-step-staff-build-3" data-guide-step>Wind: enter each giant robot through its lit foot by shooting the panel before it steps down. Collect one part inside each robot, find the yellow record around Generator 5 and obtain the wind crystal.</li>
<li id="guide-step-staff-build-4" data-guide-step>Lightning: use the tank to reach all three elevated part locations; plan the jump before riding past each platform. Find the purple record near Generator 4 and obtain the lightning crystal.</li>
<li id="guide-step-staff-build-5" data-guide-step>Return to the excavation pedestals and build each staff. Collect its crystal before trying to assemble it.</li></ol></section>
<section><h2 id="details-upgrades">Upgrade all four staffs</h2><ol><li id="guide-step-upgrades-1" data-guide-step>Ice: match each shown tablet to its ceiling symbol in the Crazy Place. Use the linked source chart when identifying shapes. Back on the map, freeze the three tombstones, then break each with a bullet weapon.</li>
<li id="guide-step-upgrades-2" data-guide-step>Fire: kill zombies on the Crazy Place grates with the staff until the cauldrons light. Decode the glowing church symbols into torch numbers and light the corresponding torches with the fire staff.</li>
<li id="guide-step-upgrades-3" data-guide-step>Wind: set the Crazy Place rings to the wind pattern shown in the reference guide, then redirect the three smoking stone balls toward the excavation with the staff.</li>
<li id="guide-step-upgrades-4" data-guide-step>Lightning: number the seven lower keyboard triangles from left to right. Shoot 1–3–6, wait for the sparks to clear, then 3–5–7, wait, then 2–4–6. Ignore the upper row. Rotate the sparking electrical panel switches around the map until they stop sparking.</li>
<li id="guide-step-upgrades-5" data-guide-step>For each staff, align the excavation rings to its color, shoot the orb beneath them, then place the staff in its Crazy Place pedestal and feed it kills until charged. Retrieve the upgraded staff.</li></ol><InlineTool tool="bo3-origins-ice" />
<InlineTool tool="bo3-origins-fire" />
<InlineTool tool="bo3-origins-staffs" /></section>
<section><h2 id="details-equipment">Thunder Fists, G-Strikes and drone</h2><ol><li id="guide-step-equipment-1" data-guide-step>Fill all four soul chests in the robot footprints without letting a robot reset an unfinished chest. Collect the Thunder Fists from a reward chest.</li>
<li id="guide-step-equipment-2" data-guide-step>Take a tablet from the Tank Station to the church water basin. Earn nearby melee kills to clean it, then carry it back without touching mud. If it becomes dirty, return to the basin and try again.</li>
<li id="guide-step-equipment-3" data-guide-step>Place the clean tablet back in the Tank Station and earn the required melee kills to unlock G-Strikes. Build the Maxis Drone from its three parts.</li></ol></section>
<section><h2 id="details-seal">Robot pedestals and the seal</h2><ol><li id="guide-step-seal-1" data-guide-step>Place upgraded staffs in the quest pedestals: ice in the church robot, wind in the middle robot, lightning in the spawn robot, and fire in the excavation.</li>
<li id="guide-step-seal-2" data-guide-step>After the placement step completes, retrieve the staffs. Press a robot’s red button and quickly throw a G-Strike onto the sealed ground near Generator 5. In co-op, assign the button and throw to separate players.</li>
<li id="guide-step-seal-3" data-guide-step>Once the seal opens, deploy the Maxis Drone into it. Defeat the spawned Panzers before continuing.</li></ol></section>
<section><h2 id="details-finale">Pilot and Crazy Place finale</h2><ol><li id="guide-step-finale-1" data-guide-step>Use Zombie Blood to see and shoot the glowing plane, then locate and kill its pilot while the effect is active. Collect the drone it drops.</li>
<li id="guide-step-finale-2" data-guide-step>In the lower excavation, use melee attacks on the special smoke-trailing zombies until the upgraded-fist tablet appears; collect it.</li>
<li id="guide-step-finale-3" data-guide-step>Place all four upgraded staffs in the Crazy Place and feed the final soul requirement. When the portal opens, deploy the upgraded Maxis Drone and use the final interaction to finish the quest.</li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Original concise walkthrough adapted from the sources below. Research reviewed 2026-09-30. Use their illustrated references for exact object sightlines. Gameplay verification is ongoing.</p><ul><li><a href="https://www.reddit.com/r/CODZombies/wiki/origins/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide ↗</a></li></ul></section></div></template>
