<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><h1 id="wiki_key_features">Key Features</h1><section><h2 id="details-setup">Power and all three teleporter links</h2><ol><li id="guide-step-setup-1" data-guide-step>Open a route from the mainframe through the laboratories to the rear courtyard and turn on the switch under the catwalk. The bridge lowers, joining both sides. Locate Juggernog by checking the perk machines: the five normal machines shuffle each game. Keep points for doors before spending heavily on the box.</li>
<li id="guide-step-setup-2" data-guide-step>At each of the three teleporters, start the link and return to the mainframe in spawn before the countdown expires. Interact with the mainframe to confirm it; in co-op, leave a teammate there to finish links quickly. Repeat for all three teleporter rooms. The gate in front of Pack-a-Punch lowers after the third successful link. Upgrade a normal bullet weapon for 5,000 points.<p class="guide-callout">Linking is a timed interaction, not a paid teleport ride. If a link expires, start it again at that teleporter.</p></li></ol></section>
<h1 id="wiki_main_quest">Main Quest</h1><section><h2 id="details-flytrap">Fly Trap: activate the beacon and earn the Annihilator</h2><ol><li id="guide-step-flytrap-1" data-guide-step>Near the L-CAR 9 side of spawn, look through the barrier toward a concrete pillar outside the map. Shoot the small control panel with your Pack-a-Punched weapon. Green objects rise into the air and Maxis speaks when the shot registers.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/bo3-the-giant/the-giant-control-panel.webp&quot;,&quot;alt&quot;:&quot;The Fly Trap activation panel outside the playable area.&quot;}]' /></li>
<li id="guide-step-flytrap-2" data-guide-step>Shoot the three hidden targets in any order and listen for an audio response after each. Use the photographs and room landmarks: community guides disagree on the teleporter letters for these objects.<ul><li>Monkey Bomb: far-right corner inside an open incinerator beneath the teleporter laboratory.</li><li>Teddy bear: the high exterior balcony to the right when looking out from the power switch.</li><li>Teddy bear: inside the left vat/well of liquid in the other laboratory; jump for the downward sightline.</li></ul><GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/bo3-the-giant/the-giant-cymbal-monkey.webp&quot;,&quot;alt&quot;:&quot;Monkey in the open incinerator.&quot;},{&quot;src&quot;:&quot;/images/bo3-the-giant/the-giant-balcony-teddy-bear.webp&quot;,&quot;alt&quot;:&quot;Bear high on the balcony beyond power.&quot;},{&quot;src&quot;:&quot;/images/bo3-the-giant/the-giant-well-teddy-bear.webp&quot;,&quot;alt&quot;:&quot;Look down into the left liquid vat for this bear.&quot;}]' /></li>
<li id="guide-step-flytrap-3" data-guide-step>After all three confirmations, visit the furnace in the room behind the VMP route and interact with the glowing Annihilator. This specialist pistol recharges from kills rather than replacing a normal gun. The beacon dialogue and reward complete Paradoxical Prologue; there is no additional boss encounter.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/bo3-the-giant/the-giant-annhilator.webp&quot;,&quot;alt&quot;:&quot;The Annihilator pickup inside the furnace.&quot;}]' /></li></ol></section>
<section><h2 id="details-perk">Optional hidden sixth perk</h2><ol><li id="guide-step-perk-1" data-guide-step>Obtain Monkey Bombs from the Mystery Box and finish linking the teleporters. Throw a monkey onto a teleporter pad and activate the paid teleport before it explodes. Repeat once at each of the three teleporters. Check the three lamps on the mainframe control panel; each valid monkey teleport turns another lamp green.</li>
<li id="guide-step-perk-2" data-guide-step>When all three lamps are green, interact with the mainframe panel. The giant robot head fires a laser that melts the snow near the L-CAR 9 route. The uncovered machine is randomly Stamin-Up or Deadshot Daiquiri. You still pay for the perk and the normal perk limit still applies.</li></ol></section>
<h1 id="wiki_side_quests">Side Quests</h1><section><h2 id="details-song">Beauty of Annihilation remix and small secrets</h2><ol><li id="guide-step-song-jars" data-guide-step>Interact with three glowing spine/brain jars: two are in the Kuda laboratory, one on its shelf and one on the opposite table; the third is on a table near the HVK-30 and grenade wallbuy in the other teleporter room. Listen for each activation. The third starts the Beauty of Annihilation remix, once per match.</li>
<li id="guide-step-teleport-secret" data-guide-step>The Monkey Bomb teleporter sequence also exposes a brief teleportation jumpscare. It is a visual secret, not another quest requirement.</li>
<li id="guide-step-radios" data-guide-step>Interact with scattered radios to hear the Maxis recordings; inspect the signs and papers for the map’s five ciphers. These are story references and do not unlock another Fly Trap step. The community source includes the radio transcripts and cipher images.<p><a href="https://www.reddit.com/r/CODZombies/wiki/the-giant/#wiki_radios" target="_blank" rel="noopener noreferrer">Radio transcripts and cipher reference ↗</a></p></li></ol></section>
<section><h2 id="details-survival">Wunderwaffe, ammunition and escape routes</h2><ol><li id="guide-step-weapons" data-guide-step>The Wunderwaffe DG-2 and Monkey Bombs come from the Mystery Box. Upgrade the Wunderwaffe at Pack-a-Punch; avoid spending its scarce ammunition on isolated zombies. A second Pack-a-Punch on an eligible bullet weapon adds an alternate ammo effect. The Annihilator remains a separate specialist ability.</li>
<li id="guide-step-training" data-guide-step>The rear catwalk funnels enemies for a team, but needs a clear escape before ammunition runs out. The power courtyard gives more room to train. Use electric traps for high-round damage and paid teleporters to escape to spawn. Hellhound rounds end with Max Ammo: reload before taking it. A teleporter cooldown can prevent an immediate second escape, so do not wait until cornered to move.</li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Original instructions cross-checked against Reddit community guides and the illustrated references below on 3 October 2026. Gameplay images: mmmrkennedy, COD Zombies Guides and their credited community creators; game: Activision / Treyarch. Symbols and sequences marked as observations must come from your match. Source and software checks do not replace an in-game playthrough.</p><ul><li><a href="https://www.reddit.com/r/CODZombies/wiki/the-giant/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide ↗</a></li>
<li><a href="https://www.codzombiesguides.com/main-quests/black-ops-3/the-giant/" target="_blank" rel="noopener noreferrer">COD Zombies Guides illustrated walkthrough (2) ↗</a></li>
<li><a href="https://gamingaroundtheclock.com/the-giant/" target="_blank" rel="noopener noreferrer">gamingaroundtheclock.com reference (3) ↗</a></li></ul><p>Select any reference image to enlarge it. Screenshot and symbol sources are credited in the linked walkthroughs; this guide uses local copies for reliable access.</p></section></div></template>
