<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><section><h2 id="details-setup">Key Features: power and Eclipse</h2><ol><li id="guide-step-setup-1" data-guide-step>Activate both underground power switches. Coordinate the pressure plates for Pack-a-Punch access and obtain the 31-79 JGb215.</li>
<li id="guide-step-setup-2" data-guide-step>Assign players to the four spawn buttons and press them together to enter Eclipse. Re-enter Eclipse for stages that require it.</li></ol></section>
<section><h2 id="details-tiles">Tile matching and water slide</h2><ol><li id="guide-step-tiles-1" data-guide-step>Divide the tile areas between players. Reveal symbols, record positions on both sides and step on matching pairs in coordination.</li>
<li id="guide-step-tiles-2" data-guide-step>For the water-slide sequence, arrange three players at the bottom while the final player completes the lever/slide interaction. Confirm the step succeeds before moving on.</li></ol><InlineTool tool="bo3-shang-tiles" /></section>
<section><h2 id="details-trials">Meteor, Napalm and dials</h2><ol><li id="guide-step-trials-1" data-guide-step>Use the baby gun and slide route for the meteor step. Complete the Napalm zombie gas-leak route without killing the required zombie too early.</li>
<li id="guide-step-trials-2" data-guide-step>Use Spikemores for the tunnel-hole step, then complete the stone-symbol and mud-dial interactions using their reference patterns.</li>
<li id="guide-step-trials-3" data-guide-step>Listen to the gongs and identify the correct resonance before the focusing-stone interaction.</li></ol></section>
<section><h2 id="details-stone">Focusing stone</h2><ol><li id="guide-step-stone-1" data-guide-step>Complete the final Eclipse actions and open the route to the focusing stone. Coordinate the team’s positioning before collecting it.</li>
<li id="guide-step-stone-2" data-guide-step>A player’s reward and any repeated run for additional rewards should be tracked separately; reset only the relevant quest checklist.</li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Original concise walkthrough adapted from the sources below. Research reviewed 2026-09-30. Use their illustrated references for exact object sightlines. Gameplay verification is ongoing.</p><ul><li><a href="https://www.reddit.com/r/CODZombies/wiki/shangri-la/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide ↗</a></li>
<li><a href="https://steamcommunity.com/sharedfiles/filedetails/?id=2461194923" target="_blank" rel="noopener noreferrer">Steam Community walkthrough (2) ↗</a></li></ul></section></div></template>
