<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><h1 id="wiki_key_features">Key Features</h1><section><h2 id="details-setup">Survive Area 51 and equip your P.E.S.</h2><ol><li id="guide-step-setup-1" data-guide-step>At Area 51, the alarm opens the teleporter cage. Move all players onto the pad to escape. On arrival at Griffin Station, immediately take a P.E.S. from the locker and equip it before going outside. Open either Tunnel 6 or Tunnel 11 to reach the pyramid room and flip the power switch.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/moon/moon-power-switch-next-to-mpd.webp&quot;,&quot;alt&quot;:&quot;Power Switch Next to M.P.D.&quot;}]' /></li>
<li id="guide-step-setup-2" data-guide-step>Open the laboratories and outside teleporter route. All players stand on the Moon teleporter when its lights are green to revisit Area 51 for Pack-a-Punch. Jugger-Nog and Speed Cola alternate there between visits. Obtain the Wave Gun, Gersh Devices and Q.E.D.s from the Box for the quest; Gersh and Q.E.D. occupy the same slot, so plan to obtain Gersh again for the ending.</li></ol></section>
<section><h2 id="details-hacker">Find the Hacker and protect your air</h2><ol><li id="guide-step-hacker-find" data-guide-step>The Hacker is a small brown device on a yellow pad in the three-floor laboratory. Search two spots per floor. Picking it up replaces your P.E.S.; swapping back to P.E.S. drops the Hacker. Use pressurised routes and return for a suit before a long trip through a breached area.<ul><li>Floor 1: shelf near the stairs; shelf near the doorway from the MPD room.</li><li>Floor 2: electrical box beside the stairs; blue structural railing on the opposite side.</li><li>Floor 3: metal tanks beside Deadshot; shelf left of the Biodome doorway.</li></ul><GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/moon/hacker-reference.png&quot;,&quot;alt&quot;:&quot;Hacker reference&quot;}]' /></li>
<li id="guide-step-hacker-excavators" data-guide-step>Listen to the excavator announcement: Pi breaches Tunnel 6, Omicron Tunnel 11, Epsilon the Biodome. Hack the matching active console in the Receiving Bay to stop/retract it. For the main quest, Pi must actually breach Tunnel 6 once before you retract it. Retraction clears the machinery but does not restore the lost atmosphere.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/moon/moon-excavator-pi-breaching-tunnel-6.webp&quot;,&quot;alt&quot;:&quot;Excavator Pi breaching Tunnel 6&quot;}]' /></li></ol></section>
<h1 id="wiki_main_quest">Main Quest</h1><section><h2 id="details-simon">Samantha Says and the timed laboratory panels</h2><ol><li id="guide-step-simon-1" data-guide-step>After power is on, interact with the four computers outside the Receiving Bay near Tunnel 6. Facing them, the physical order from left to right is Red, Green, Blue, Yellow. Watch the flashing sequence, then interact with the matching computers in that order. Complete the initial set of increasingly long sequences. Red failure feedback means replay the attempt.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/moon/moon-simon-says-computers.webp&quot;,&quot;alt&quot;:&quot;Simon Says Computers&quot;}]' /></li>
<li id="guide-step-simon-2" data-guide-step>Take the Hacker to floor 2 of the laboratories. Hack the far-left button on the four-button wall for 500 points. A roughly 60-second timer starts: locate and hack the four green-lit panel boxes among the eight possible boxes across the three floors. Ordinary unlit boxes do not count.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/moon/moon-button-wall.webp&quot;,&quot;alt&quot;:&quot;Button Wall&quot;}]' /></li>
<li id="guide-step-simon-3" data-guide-step>Return to the four-button wall and quickly interact with all four buttons normally, rather than hacking them. The illuminated wall confirms success. If the timed attempt failed, restart at the initial button and search again; the selected green boxes may differ.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/moon/moon-glowing-button-wall.webp&quot;,&quot;alt&quot;:&quot;Buttons glowing on button wall&quot;}]' /></li></ol><InlineTool tool="bo3-moon-simon" />
<InlineTool tool="bo3-moon-labs" /></section>
<section><h2 id="details-sphere">Tunnel 6, the sphere and the first soul tube</h2><ol><li id="guide-step-sphere-1" data-guide-step>Wait for Excavator Pi to breach Tunnel 6, then retract it with the Hacker at the Receiving Bay. Equip a P.E.S. for the now-depressurised tunnel. Find the black Vril Sphere on the Tunnel 6 floor and melee it to start it moving toward spawn.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/moon/moon-vril-sphere.webp&quot;,&quot;alt&quot;:&quot;Vril Sphere&quot;}]' /></li>
<li id="guide-step-sphere-2" data-guide-step>Follow the sphere. When it lodges on the satellite dish above the Receiving Bay, shoot it with the Wave Gun in its combined mode. Follow it into Tunnel 11, opening doors and shooting or using an explosive when it sticks out of reach near the ceiling. Guide it to the socket in front of the pyramid.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/moon/moon-satellite-dish-above-spawn.webp&quot;,&quot;alt&quot;:&quot;Satellite Dish Above Spawn&quot;},{&quot;src&quot;:&quot;/images/chronicles/moon/moon-vril-sphere-entering-vril-interface.webp&quot;,&quot;alt&quot;:&quot;Vril Sphere entering Vril Interface&quot;}]' /></li>
<li id="guide-step-sphere-3" data-guide-step>Kill 25 zombies close to the newly exposed MPD tube so their souls enter it. When it is full, use the nearby lever to open the pyramid and reveal Samantha. Cryogenic Slumber Party and its temporary Death Machine mark the first milestone; continue below for the full ending.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/moon/moon-power-switch-next-to-mpd.webp&quot;,&quot;alt&quot;:&quot;Power Switch Next to M.P.D.&quot;}]' /></li></ol></section>
<section><h2 id="details-device">Bring back the plates and charge the Golden Rod</h2><ol><li id="guide-step-device-plates" data-guide-step>Bring a Gersh Device to Area 51. Throw a grenade at the hexagonal plates on the shelf to the right of the teleporter, knocking them down. Throw a Gersh close enough to pull the plates onto the teleporter, then return to the Moon.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/moon/moon-hex-plates-shelf.webp&quot;,&quot;alt&quot;:&quot;Hexagonal Plates on Shelf&quot;}]' /></li>
<li id="guide-step-device-qed" data-guide-step>The plates now lie beside Quick Revive. Throw a Q.E.D. at them to move them to the computer in the opposite corner of the Receiving Bay. Keep Q.E.D.s until the later sphere-transfer step.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/moon/moon-hex-plates-near-quick-revive.webp&quot;,&quot;alt&quot;:&quot;Hexagonal Plates near Quick Revive&quot;},{&quot;src&quot;:&quot;/images/chronicles/moon/moon-computer-in-spawn.webp&quot;,&quot;alt&quot;:&quot;Computer in Spawn&quot;}]' /></li>
<li id="guide-step-device-cable" data-guide-step>Pick up the silver S-shaped cable in or just outside the laboratories. Sweep shelves, floors and corners on all three levels, then the outside area near Mule Kick. The photographs show its appearance and outside search area, not every possible spawn. Connect it between the Receiving Bay computer and plates.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/moon/moon-s-cable.webp&quot;,&quot;alt&quot;:&quot;S shaped cable appearance (location in the image is stairs leading to the third floor of the lab)&quot;},{&quot;src&quot;:&quot;/images/chronicles/moon/moon-s-cables-outside-spawn.webp&quot;,&quot;alt&quot;:&quot;S Cables Outside the Laboratory&quot;},{&quot;src&quot;:&quot;/images/chronicles/moon/moon-s-cable-connected-to-machine.webp&quot;,&quot;alt&quot;:&quot;S shaped cable connected to computer&quot;}]' /></li>
<li id="guide-step-device-charge" data-guide-step>Richtofen places his Golden Rod/Vril Device between the plates. Keep interacting with the computer through Maxis’s dialogue until the charge completes and the device glows. Pick the charged device back up before leaving.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/moon/moon-vril-device-glowing.webp&quot;,&quot;alt&quot;:&quot;Vril Device fully powered&quot;}]' /></li></ol></section>
<section><h2 id="details-rockets">Soul transfer and Earth’s destruction</h2><ol><li id="guide-step-rockets-1" data-guide-step>At the MPD, fill all four exposed tubes with 25 nearby zombie souls apiece. Richtofen inserts the charged device at the front of the pyramid, triggering the body swap and his permanent perks. After the dialogue, throw a Q.E.D. at the sphere in front of the MPD to send it back toward the computers.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/moon/moon-filled-soul-containers.webp&quot;,&quot;alt&quot;:&quot;Filled Souls Containers&quot;}]' /></li>
<li id="guide-step-rockets-2" data-guide-step>Complete three more Samantha Says games at the outside computers. Replace Q.E.D.s with Gersh Devices and throw a Gersh beside the sphere lying to the right of the computers. The countdown and three rockets striking Earth confirm the full ending. BO3 includes this ending even though its BO1 “Big Bang Theory” achievement is absent.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/moon/moon-vril-sphere-next-to-computers.webp&quot;,&quot;alt&quot;:&quot;Vril Sphere next to computers&quot;},{&quot;src&quot;:&quot;/images/chronicles/moon/moon-earth-destroyed.webp&quot;,&quot;alt&quot;:&quot;Earth Destroyed&quot;}]' /></li></ol></section>
<h1 id="wiki_side_quests">Side Quests</h1><section><h2 id="details-hacker-uses">Useful Hacker interactions</h2><ol><li id="guide-step-hack-powerups" data-guide-step>Hack a power-up for 5,000 points to convert it into Max Ammo. Protect the player while the hack completes; do not pick up the drop first.</li>
<li id="guide-step-hack-box" data-guide-step>Hack an unclaimed Box weapon to reroll it for 600 points. Hacking the rerolled result lets a teammate take it and refunds points to the hacker. Hacking a perk machine for a perk you own removes that perk and refunds its purchase price.</li>
<li id="guide-step-hack-sharing" data-guide-step>Hack a teammate to transfer 500 of your points to them. This is useful when a teammate needs a door or perk; it does not generate free points.</li></ol></section>
<section><h2 id="details-samantha">Samantha side quest: the fifteen speaker presses</h2><ol><li id="guide-step-moon-sam-code" data-guide-step>In the power/MPD room, face the back-to-back computer bank exactly as in the photo. Label its positions near-left, far-left, near-right and far-right. Press: far-right, near-left, near-left, near-right, near-right, near-left, near-right, far-left, near-right, far-left, near-right, near-left, near-left, far-left, far-right. These are fifteen interactions, independent of the outside colour computers.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/moon/samantha-code.jpg&quot;,&quot;alt&quot;:&quot;Power-room speaker order for the Samantha side quest&quot;}]' /></li>
<li id="guide-step-moon-sam-dolls" data-guide-step>Interact with the doll left of the MPD. Shoot the dolls that appear in front of the pyramid with a bullet weapon, then interact with the original doll again after the sequence. This awards Max Ammo and the Chronicles Samantha theme.</li></ol></section>
<section><h2 id="details-space-dog">Space Dog</h2><ol><li id="guide-step-space-dog-items" data-guide-step>Using the combined Wave Gun, shoot three hidden objects: the dog toy near a truck tyre at Area 51, the teddy on the outer Biodome ledge, and the bone among the rocks near the Moon teleporter. Each collected object appears by the dog bowls on laboratory floor 2.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/moon/space-dog-toy.png&quot;,&quot;alt&quot;:&quot;Space Dog: toy by the Area 51 truck tyre&quot;},{&quot;src&quot;:&quot;/images/chronicles/moon/space-dog-teddy.png&quot;,&quot;alt&quot;:&quot;Space Dog: teddy on the Biodome ledge&quot;}]' /></li>
<li id="guide-step-space-dog-souls" data-guide-step>Hack the dog bowls on lab floor 2, then kill 50 zombies close to them. A bark confirms completion. From the outside teleporter area, look toward the landscape in the direction of spawn for the dog bounding in space. Its route can vary.</li></ol></section>
<section><h2 id="details-music">Coming Home, electronic songs and Nightmare</h2><ol><li id="guide-step-moon-coming-home" data-guide-step>Interact with three helmet-wearing teddy bears: on the crates below the Receiving Bay, in the airlock between Tunnel 6 and power, and in the broken wall near Stamin-Up. The third starts Coming Home.</li>
<li id="guide-step-moon-electronic" data-guide-step>For the short electronic tracks, interact with the lab computers by the upper-floor weapon wall/Deadshot (Damned), the consoles by the Tunnel 11 door to power (Coming Home), and the floor-2 lab computers by the window crates (Pareidolia). These do not advance the main quest.</li>
<li id="guide-step-moon-nightmare" data-guide-step>Nightmare is tied to the One Giant Leap setup in co-op: both tunnels must be breached, one player on the Receiving Bay side bleeds out, and the surviving player across the blocked routes finishes the round to respawn them. This deliberately costs a life; attempt it only when the team is ready for that optional challenge.</li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Written for Black Ops III: Zombies Chronicles. Community instructions and illustrated references were cross-checked on 3 October 2026. Gameplay: Activision / Treyarch; photographs and charts: the credited community sources below. Some shared-layout references show the original release; follow the BO3 instructions in the text. Source review and website checks do not replace an in-game playthrough.</p><ul><li><a href="https://www.reddit.com/r/CODZombies/wiki/moon/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide ↗</a></li>
<li><a href="https://www.codzombiesguides.com/main-quests/black-ops-1/moon/" target="_blank" rel="noopener noreferrer">COD Zombies Guides illustrated walkthrough (2) ↗</a></li>
<li><a href="https://steamcommunity.com/sharedfiles/filedetails/?id=2373011651" target="_blank" rel="noopener noreferrer">Steam Community walkthrough (3) ↗</a></li></ul><p>Select any reference image to enlarge it. Screenshot and symbol sources are credited in the linked walkthroughs; this guide uses local copies for reliable access.</p></section></div></template>
