<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><section><h2 id="details-setup">Key Features: landers and rocket</h2><ol><li id="guide-step-setup-1" data-guide-step>Turn on power and use all three lunar lander stations. Launch the rocket to reach Pack-a-Punch.</li>
<li id="guide-step-setup-2" data-guide-step>Prepare Gersh Devices, Matryoshka Dolls and upgraded high-damage weapons for the final orb stage. Coordinate equipment across the team.</li></ol></section>
<section><h2 id="details-nodes">First three Casimir nodes</h2><ol><li id="guide-step-nodes-1" data-guide-step>Throw a Gersh Device at the generator outside the playable area near the PhD/Widow’s Wine side, then activate the monitor by the Stamin-Up lander.</li>
<li id="guide-step-nodes-2" data-guide-step>During a monkey round, assign all four players to the four perk-area buttons and press them together.</li>
<li id="guide-step-nodes-3" data-guide-step>With Pack-a-Punch open, stand together on the platform beneath the rocket for one full clock rotation without leaving it.</li></ol></section>
<section><h2 id="details-luna">LUNA lander route</h2><ol><li id="guide-step-luna-1" data-guide-step>Keep one rider aboard while teammates call the lander: Spawn → Stamin-Up, Stamin-Up → Spawn, Spawn → Speed Cola, Speed Cola → Stamin-Up.</li>
<li id="guide-step-luna-2" data-guide-step>Collect the letters along those flights to spell LUNA and activate the fourth node.</li></ol><InlineTool tool="bo3-ascension-luna" /></section>
<section><h2 id="details-orb">Final orb</h2><ol><li id="guide-step-orb-1" data-guide-step>At the Casimir device near Stamin-Up, use a Gersh Device at the glowing orb and apply the required explosive/wonder-weapon damage as a team.</li>
<li id="guide-step-orb-2" data-guide-step>Continue until the orb rises and the quest confirmation plays. This quest has its own reward rather than a conventional boss arena.</li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Original concise walkthrough adapted from the sources below. Research reviewed 2026-09-30. Use their illustrated references for exact object sightlines. Gameplay verification is ongoing.</p><ul><li><a href="https://www.reddit.com/r/CODZombies/wiki/ascension/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide ↗</a></li>
<li><a href="https://steamcommunity.com/sharedfiles/filedetails?id=2446771284" target="_blank" rel="noopener noreferrer">Steam Community walkthrough (2) ↗</a></li></ul></section></div></template>
