<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><section><h2 id="details-setup">Key Features: oxygen and equipment</h2><ol><li id="guide-step-setup-1" data-guide-step>Escape Area 51 to the Moon, collect a PES and restore power. Use the Hacker carefully: without a PES you need breathable areas.</li>
<li id="guide-step-setup-2" data-guide-step>Prepare the Wave Gun, Gersh Devices and QEDs as the quest requires. Keep access to Tunnel 6 for the sphere stage.</li></ol></section>
<section><h2 id="details-simon">Samantha Says and terminals</h2><ol><li id="guide-step-simon-1" data-guide-step>Complete the first Samantha Says sequence at the four screens by repeating each display in order.</li>
<li id="guide-step-simon-2" data-guide-step>Use the Hacker for the laboratory terminal/button stage and finish its timed interactions.</li>
<li id="guide-step-simon-3" data-guide-step>Wait for Excavator Pi to breach Tunnel 6, then stop the excavator with the Hacker when the quest’s tunnel condition has been satisfied.</li></ol><InlineTool tool="bo3-moon-simon" /></section>
<section><h2 id="details-sphere">Sphere and MPD</h2><ol><li id="guide-step-sphere-1" data-guide-step>Follow the sphere through Tunnel 6, using the appropriate weapon interactions and Wave Gun satellite shot to move it onward.</li>
<li id="guide-step-sphere-2" data-guide-step>Guide the sphere into the MPD, then fill the required soul stage to open the chamber.</li>
<li id="guide-step-sphere-3" data-guide-step>Return to Area 51 for the plates. Use the Gersh/QED interactions to move them into place and find the cable for the Vril device/computer sequence.</li></ol></section>
<section><h2 id="details-rockets">Canisters and rockets</h2><ol><li id="guide-step-rockets-1" data-guide-step>Complete the device/computer stage and fill the four soul canisters. Keep the team supplied while moving between the charge areas.</li>
<li id="guide-step-rockets-2" data-guide-step>Repeat the later Samantha Says sequences, clearing the helper for each attempt. Finish the final sphere/device interactions to launch the rockets.</li></ol><InlineTool tool="bo3-moon-simon" /></section><section><h2 id="guide-sources">Sources and review</h2><p>Original concise walkthrough adapted from the sources below. Research reviewed 2026-09-30. Use their illustrated references for exact object sightlines. Gameplay verification is ongoing.</p><ul><li><a href="https://www.reddit.com/r/CODZombies/wiki/moon/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide ↗</a></li>
<li><a href="https://steamcommunity.com/sharedfiles/filedetails/?id=2373011651" target="_blank" rel="noopener noreferrer">Steam Community walkthrough (2) ↗</a></li></ul></section></div></template>
