<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><section><h2 id="details-setup">Key Features: power and equipment</h2><ol><li id="guide-step-setup-1" data-guide-step>Open the route to power and turn it on. Activate the courtyard anti-gravity plates and collect shield parts while opening the castle.</li>
<li id="guide-step-setup-2" data-guide-step>Interact with the scattered Pack-a-Punch components to assemble the machine. Feed each of the three stone dragons one zombie at a time until it stops eating.</li>
<li id="guide-step-setup-3" data-guide-step>Collect Wrath of the Ancients from the knight’s tomb. Gather the Ragnarok DG-4 components from the Panzer, launch-pad drop and rocket-test event.</li></ol></section>
<section><h2 id="details-bows">Bow upgrades</h2><ol><li id="guide-step-bows-1" data-guide-step>Choose the required upgrade branches. Lightning uses the weather vane, bonfires, wall-running symbols and electrified shots; Wolf follows its paintings, flag, skull and spirit wolf.</li>
<li id="guide-step-bows-2" data-guide-step>Fire uses the clock-tower symbol, rocket-site rock, aerial circle shots and its fireplace route. Void uses the trophy-room floor, skulls, crawlers and spoken names.</li>
<li id="guide-step-bows-3" data-guide-step>For Void, record the three spoken names, then the glyph each corresponding knight reveals. Do not assume a fixed name-to-glyph mapping.</li>
<li id="guide-step-bows-4" data-guide-step>Complete each branch’s charged soul chest and collect the upgraded bow.</li></ol><InlineTool tool="bo3-de-bows" />
<InlineTool tool="bo3-de-void" /></section>
<section><h2 id="details-time">Wisps, time travel and safe</h2><ol><li id="guide-step-time-1" data-guide-step>Start the teleporter wisp sequence with the unupgraded bow. Use an upgraded bow to shoot each active electrical object before the attempt expires; a failed sequence needs a fresh attempt.</li>
<li id="guide-step-time-2" data-guide-step>Teleport to the past and record the safe combination. Collect the required quest items before returning.</li>
<li id="guide-step-time-3" data-guide-step>Set the Death Ray to Protect, enter the observed safe code at the terminal and retrieve the safe contents. Install the fuses and complete the station symbol challenges.</li></ol><InlineTool tool="bo3-de-terminals" /></section>
<section><h2 id="details-keeper">Keeper and boss preparation</h2><ol><li id="guide-step-keeper-1" data-guide-step>Complete the terminal/Death Ray sequence to bring down the pod and collect the tablet. Repeat the time-travel step when required to obtain the remaining quest item.</li>
<li id="guide-step-keeper-2" data-guide-step>Place the tablet and follow the keeper. Feed its circles with the bow element indicated for that location. Keep the correct bow available to its player.</li>
<li id="guide-step-keeper-3" data-guide-step>When the keeper returns and the pyramid stage is ready, gather the team with charged Ragnarok DG-4s, upgraded weapons and ammunition.</li></ol></section>
<section><h2 id="details-boss">Keeper boss and ending</h2><ol><li id="guide-step-boss-1" data-guide-step>Use Ragnarok DG-4 at the arena center during the keeper’s electrical charge to expose it. Shoot the vulnerable chest and survive the Panzer waves between damage phases.</li>
<li id="guide-step-boss-2" data-guide-step>Repeat the opening and damage cycles. After returning to the castle, collect and use the Summoning Key at the terminal to complete the ending.</li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Original concise walkthrough adapted from the sources below. Research reviewed 2026-09-30. Use their illustrated references for exact object sightlines. Gameplay verification is ongoing.</p><ul><li><a href="https://www.reddit.com/r/CODZombies/wiki/der-eisendrache/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide ↗</a></li></ul></section></div></template>
