<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><section><h2 id="details-setup">Key Features: permanent power</h2><ol><li id="guide-step-setup-1" data-guide-step>Collect a bucket and water. Fill the temporary generators in Labs A and B, then open the bunker while both are active.</li>
<li id="guide-step-setup-2" data-guide-step>Enter the flooded power room, clear the obstruction and survive the underwater lockdown to activate permanent power. Watch oxygen while fighting.</li>
<li id="guide-step-setup-3" data-guide-step>Drain the three Pack-a-Punch areas and collect the machine parts. Build the shield and gas mask from their spawn groups.</li></ol></section>
<section><h2 id="details-equipment">Skull, KT-4 and Masamune</h2><ol><li id="guide-step-equipment-1" data-guide-step>Match the four skull symbols to their ritual locations and charge each skull with kills. Return them and survive the ritual to obtain the Skull of Nan Sapwe.</li>
<li id="guide-step-equipment-2" data-guide-step>Collect the KT-4 ingredients from the laboratory spider cage, special zombie and underwater plant route, then build the weapon.</li>
<li id="guide-step-equipment-3" data-guide-step>Complete the trials and Masamune upgrade requirements. Use the skull to reveal hidden quest surfaces and the electrified shield where specified.</li></ol><InlineTool tool="bo3-zetsubou-upgrades" /></section>
<section><h2 id="details-plants">Plant rewards and artillery shell</h2><ol><li id="guide-step-plants-1" data-guide-step>Plant a seed and water it once per growth round. Record its treatment; use KT-4 fertilization for recipes that require it.</li>
<li id="guide-step-plants-2" data-guide-step>For the artillery task, grow the required reward plant and collect the shell if it appears. If it does not, plant and grow another attempt.</li>
<li id="guide-step-plants-3" data-guide-step>Load the shell into the anti-aircraft gun and shoot the passing plane at the correct moment. Collect the dropped cog.</li></ol><InlineTool tool="bo3-zetsubou-plants" /></section>
<section><h2 id="details-cogs">Elevator cogs</h2><ol><li id="guide-step-cogs-1" data-guide-step>Use Anywhere But Here after revealing its hidden room to collect one cog. This quest route requires that GobbleGum interaction.</li>
<li id="guide-step-cogs-2" data-guide-step>Obtain the zipline cog using the electrified-shield sequence. Solo uses the timed dismount route; co-op can have a teammate electrify the zipline.</li>
<li id="guide-step-cogs-3" data-guide-step>Install all three cogs at the elevator. Prepare Masamune, shield, mask and ammunition before descending.</li></ol></section>
<section><h2 id="details-boss">Boss room</h2><ol><li id="guide-step-boss-1" data-guide-step>Survive the enemies and wait for the boss’s vulnerable spores to open. Shoot the active spores with Masamune.</li>
<li id="guide-step-boss-2" data-guide-step>Repeat through the exposed growths, keeping oxygen, space and ammunition available until the final interaction.</li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Original concise walkthrough adapted from the sources below. Research reviewed 2026-09-30. Use their illustrated references for exact object sightlines. Gameplay verification is ongoing.</p><ul><li><a href="https://www.reddit.com/r/CODZombies/wiki/zetsubou-no-shima/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide ↗</a></li></ul></section></div></template>
