<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><section><h2 id="details-setup">Key Features: rituals and Pack-a-Punch</h2><ol><li id="guide-step-setup-1" data-guide-step>Use Beast mode to open each district’s ritual route: shock electrical boxes, break marked doors/crates and grapple to elevated entrances before the transformation ends.</li>
<li id="guide-step-setup-2" data-guide-step>Collect the Summoning Key and the four character ritual items. Complete the corresponding rituals at Easy Street, the Canal burlesque area, Waterfront boxing gym and Footlight theater.</li>
<li id="guide-step-setup-3" data-guide-step>Take the four gateworms through the rift, place them around the underground ritual room and survive its final ritual to unlock Pack-a-Punch.</li>
<li id="guide-step-setup-4" data-guide-step>Build the shield and prepare a strong weapon. The Apothicon Servant requires its three match drops; recommended GobbleGums are optional loadout choices.</li></ol></section>
<section><h2 id="details-swords">Apothicon sword and upgrade</h2><ol><li id="guide-step-swords-1" data-guide-step>Ride the tram routes and look through the windows for the three red glyphs. Record them, then enter Beast mode and activate the corresponding symbols on the underground wall.</li>
<li id="guide-step-swords-2" data-guide-step>Take the egg and place it at each of the four statues. Fill each placement with nearby kills, return it to the wall and collect the sword.</li>
<li id="guide-step-swords-3" data-guide-step>Visit your character’s ritual location for the Arch-Ovum. Complete its summoning-circle encounters across successive rounds, then return to exchange for the upgraded sword.</li></ol><InlineTool tool="bo3-shadows-glyphs" /></section>
<section><h2 id="details-flags">Book and flag defenses</h2><ol><li id="guide-step-flags-1" data-guide-step>After the swords are ready, activate the book in Nero’s room and obtain the flag. Place it at the indicated defense locations.</li>
<li id="guide-step-flags-2" data-guide-step>Protect the flag from incoming enemies and Shadowman attacks. Pick it up when charged and carry it onward, completing each route before returning it to the appropriate ritual keeper.</li>
<li id="guide-step-flags-3" data-guide-step>Repeat the available flag routes, respecting their round progression, until the keepers are ready.</li></ol></section>
<section><h2 id="details-finale">Shadowman and four-player finale</h2><ol><li id="guide-step-finale-1" data-guide-step>Activate the keepers in the underground ritual chamber. Damage the Shadowman through the vulnerable phases and trap him at the ritual table.</li>
<li id="guide-step-finale-2" data-guide-step>Assign three players to the tram stations and one to the central junction. Coordinate Beast-mode electrical interactions, tram movement and keeper shocks for the final gateworm stage.</li>
<li id="guide-step-finale-3" data-guide-step>Confirm the final quest reward rather than treating the earlier Shadowman encounter as the complete four-player ending.</li></ol><InlineTool tool="bo3-shadows-roles" /></section><section><h2 id="guide-sources">Sources and review</h2><p>Original concise walkthrough adapted from the sources below. Research reviewed 2026-09-30. Use their illustrated references for exact object sightlines. Gameplay verification is ongoing.</p><ul><li><a href="https://www.reddit.com/r/CODZombies/wiki/shadows-of-evil/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide ↗</a></li>
<li><a href="https://www.reddit.com/r/CODZombies/comments/1lmuqdx/shadows_of_evil_easter_egg_2025/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide (2) ↗</a></li></ul></section></div></template>
