<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><section><h2 id="details-setup">Key Features: engines and equipment</h2><ol><li id="guide-step-setup-1" data-guide-step>Activate the four corruption engines and use Nacht’s control to stun the giant Apothicon. Enter it and shoot the stomach’s yellow sacs to release Pack-a-Punch.</li>
<li id="guide-step-setup-2" data-guide-step>Build the shield and Keeper Protector. Obtain Lil Arnies and the Apothicon Servant, then complete their required upgrades.</li>
<li id="guide-step-setup-3" data-guide-step>Shoot the opening gravestones in order 2, 3, 1, 4 to begin the main quest.</li></ol></section>
<section><h2 id="details-reels">Keeper, Arnies and bones</h2><ol><li id="guide-step-reels-1" data-guide-step>Find the special stone at a jump pad and summon the Keeper Protector there. Protect its ritual, collect the reel and play it at the appropriate recorder.</li>
<li id="guide-step-reels-2" data-guide-step>Complete the Lil Arnies hole groups inside the Apothicon and defeat the resulting enemies. Collect and play the next reel.</li>
<li id="guide-step-reels-3" data-guide-step>Reveal the six bones around the map, then collect them with the upgraded Apothicon Servant. Reveal Sophia’s skeleton at Nacht, collect the reel and play it at the Origins mound.</li></ol><InlineTool tool="bo3-revelations-collections" /></section>
<section><h2 id="details-eggs">Sophia, eggs and runes</h2><ol><li id="guide-step-eggs-1" data-guide-step>Aim each corruption turret at the reflecting rock until its beam locks toward Sophia. Interact with her and escort her to Kino’s teleporter.</li>
<li id="guide-step-eggs-2" data-guide-step>Teleport with the team to Samantha’s room and collect the Kronorium. Find the four orange eggs; only one is visible on the map at a time.</li>
<li id="guide-step-eggs-3" data-guide-step>Charge eggs in the Apothicon pool. The collecting player must supply the souls. Use each hatched gateworm’s sonar to find its placement and obtain a rune.</li></ol></section>
<section><h2 id="details-key">Kronorium sequence and Summoning Key</h2><ol><li id="guide-step-key-1" data-guide-step>Stand on the four runes at Kino to reach the arena. Read the Kronorium’s rune order and activate the floating symbols in that order.</li>
<li id="guide-step-key-2" data-guide-step>Survive the challenge waves and collect the Summoning Key. Hit the required targets in Shangri-La, Nacht, Verrückt, Mob, Origins, Der Eisendrache and Kino.</li>
<li id="guide-step-key-3" data-guide-step>Return through the Kino teleporter when the targets are complete.</li></ol><InlineTool tool="bo3-revelations-runes" />
<InlineTool tool="bo3-revelations-collections" /></section>
<section><h2 id="details-boss">Shadowman finale</h2><ol><li id="guide-step-boss-1" data-guide-step>Charge the Summoning Key at an arena pedestal, then throw it to Sophia to break the Shadowman’s shield.</li>
<li id="guide-step-boss-2" data-guide-step>Damage the Shadowman into the Apothicon’s mouth and interact with the Kronorium. Repeat the charge cycle if the damage window is missed.</li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Original concise walkthrough adapted from the sources below. Research reviewed 2026-09-30. Use their illustrated references for exact object sightlines. Gameplay verification is ongoing.</p><ul><li><a href="https://www.reddit.com/r/CODZombies/wiki/revelations/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide ↗</a></li></ul></section></div></template>
