<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><section><h2 id="details-setup">Key Features: dragon access</h2><ol><li id="guide-step-setup-1" data-guide-step>Turn on power and collect the three colored code cylinders from enemy drops. Insert each in its matching terminal and defend the dropped Groph module.</li>
<li id="guide-step-setup-2" data-guide-step>Collect each module’s part and install the dragon control. Ride the dragon to the hatchery to access Pack-a-Punch and complete the lockdown.</li>
<li id="guide-step-setup-3" data-guide-step>Build the Dragon Shield. Obtain and incubate the dragon egg, complete its challenges, then charge it at the hatchery to receive the Gauntlet of Siegfried.</li></ol></section>
<section><h2 id="details-valves">Generator and valve network</h2><ol><li id="guide-step-valves-1" data-guide-step>Use a Valkyrie electrical attack to power the generator. Identify the valve with the green light and the valve containing the master cylinder.</li>
<li id="guide-step-valves-2" data-guide-step>Enter those two rooms in the valve solver. Set the five connecting valves to its output and collect the cylinder at the endpoint.</li>
<li id="guide-step-valves-3" data-guide-step>Take the master cylinder to SOPHIA and enter KRONOS when prompted.</li></ol><InlineTool tool="bo3-gorod-valves" /></section>
<section><h2 id="details-trophies">Trophies and SOPHIA challenges</h2><ol><li id="guide-step-trophies-1" data-guide-step>Collect all six challenge trophies using the map’s shield, equipment and environmental interactions, then place them at the command terminal.</li>
<li id="guide-step-trophies-2" data-guide-step>Activate each challenge and follow its specific objective: escorts must reach their destination, defense targets must survive and collection tasks need their items returned.</li>
<li id="guide-step-trophies-3" data-guide-step>For the bomb challenge, record every displayed location before leaving the screen. Defuse all six in exactly that order; a wrong interaction can end the run.</li></ol><InlineTool tool="bo3-gorod-bombs" /></section>
<section><h2 id="details-boss">Power core and final fights</h2><ol><li id="guide-step-boss-1" data-guide-step>After all challenges, obtain the power core and deliver it to Nikolai using the Gauntlet dragon. Gather the team at the final entrance.</li>
<li id="guide-step-boss-2" data-guide-step>Fight the dragon by damaging exposed weak spots between attacks. Then damage the weak points of Nikolai’s mech as they become available.</li>
<li id="guide-step-boss-3" data-guide-step>Finish the final interaction after the mech is defeated. Do not assume the dragon fight alone completes the quest.</li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Original concise walkthrough adapted from the sources below. Research reviewed 2026-09-30. Use their illustrated references for exact object sightlines. Gameplay verification is ongoing.</p><ul><li><a href="https://www.reddit.com/r/CODZombies/wiki/gorod-krovi/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide ↗</a></li></ul></section></div></template>
