<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><h1 id="wiki_key_features">Key Features</h1><section><h2 id="details-setup">Get equipped and learn the two floors</h2><ol><li id="guide-step-setup-1" data-guide-step>Open the Help door to the Mystery Box room, then choose a staircase to reach the upper floor. Keep a route between the rooms clear before starting a timed secret. This map has no power switch; you do not need to search for one.</li>
<li id="guide-step-setup-2" data-guide-step>Use the Mystery Box for stronger weapons, including the Thundergun. Mule Kick is downstairs and Der Wunderfizz is upstairs. The upstairs cabinet sells a Locus for 5,000 points in BO3; buying it does not unlock a quest. There is no normal Pack-a-Punch route.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/nacht-der-untoten/sniper_cabinet.webp&quot;,&quot;alt&quot;:&quot;cabinet on the second floor&quot;}]' /></li></ol></section>
<h1 id="wiki_side_quests">Side Quests</h1><section><h2 id="details-samantha">Samantha: four buttons, then five hidden dolls</h2><ol><li id="guide-step-samantha-1" data-guide-step>Interact with all four small wall buttons in any order. Check the pillar left of Mule Kick, beneath the shelf at the bottom of the Box-room stairs, the upper-room wall opposite the window across from Wunderfizz, and the ceiling above the spawn stairs. Listen for confirmation after pressing each.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/nacht-der-untoten/free_max_ammo/button_mule.webp&quot;,&quot;alt&quot;:&quot;Ground Floor - On the side of a pillar, left of Mule Kick&quot;},{&quot;src&quot;:&quot;/images/chronicles/nacht-der-untoten/free_max_ammo/button_shelf.webp&quot;,&quot;alt&quot;:&quot;Ground Floor - Under the shelf at the bottom of the stairs in the Mystery Box Room&quot;},{&quot;src&quot;:&quot;/images/chronicles/nacht-der-untoten/free_max_ammo/button_cabinet.webp&quot;,&quot;alt&quot;:&quot;Second Floor - In the Wunderfizz room, on the other side of the room, on the wall across from the Zombie spawn window&quot;},{&quot;src&quot;:&quot;/images/chronicles/nacht-der-untoten/free_max_ammo/button_stairs.webp&quot;,&quot;alt&quot;:&quot;Second Floor - On the ceiling above the stairs in spawn&quot;}]' /></li>
<li id="guide-step-samantha-2" data-guide-step>Interact with the doll on the floor in front of the RK5 wall buy. Now find and shoot five dolls, one at a time, from the eight possible locations. Listen for music near the active doll and use a bullet weapon. A laugh after taking too long means you must restart from the RK5 doll.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/nacht-der-untoten/free_max_ammo/sam_doll_rk5.webp&quot;,&quot;alt&quot;:&quot;floor in front of the RK5 wallbuy&quot;}]' /></li>
<li id="guide-step-samantha-reward" data-guide-step>After the fifth target, return to the original doll. Interact with it again to finish the sequence, collect the Max Ammo and play Samantha’s Sorrow. The search photographs show possibilities, not a guaranteed spawn order.</li></ol><InlineTool tool="bo3-nacht-secrets" /></section>
<section><h2 id="details-extras">Undone and the radio</h2><ol><li id="guide-step-extras-barrels" data-guide-step>For Undone in Zombies Chronicles, shoot all 30 explosive barrels visible outside the building. Sweep the ground-floor windows and then the upstairs windows and broken walls. Destroying only the three commonly pictured BO1 barrels is not enough in BO3.</li>
<li id="guide-step-extras-1" data-guide-step>Shoot or melee the radio on the table beside the Mystery Box to cycle its music. This is independent of the barrels and the Samantha hunt. Pause other music before starting a song if you want to hear it clearly.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/nacht-der-untoten/radio.webp&quot;,&quot;alt&quot;:&quot;radio on the table&quot;}]' /></li>
<li id="guide-step-extras-2" data-guide-step>Use the photographed button and doll finder from the Samantha section to check unfamiliar sightlines. Select an image to enlarge it; the photographs do not reveal which random target is active in your match.</li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Written for Black Ops III: Zombies Chronicles. Community instructions and illustrated references were cross-checked on 3 October 2026. Gameplay: Activision / Treyarch; photographs and charts: the credited community sources below. Some shared-layout references show the original release; follow the BO3 instructions in the text. Source review and website checks do not replace an in-game playthrough.</p><ul><li><a href="https://www.reddit.com/r/CODZombies/wiki/nacht-der-untoten/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide ↗</a></li>
<li><a href="https://mmmrkennedy.com/games/WAW/nacht_der_untoten/nacht_der_untoten_guide" target="_blank" rel="noopener noreferrer">mmmrkennedy illustrated guide (2) ↗</a></li></ul><p>Select any reference image to enlarge it. Screenshot and symbol sources are credited in the linked walkthroughs; this guide uses local copies for reliable access.</p></section></div></template>
