<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><h1 id="wiki_key_features">Key Features</h1><section><h2 id="details-setup">Open the huts and find your perks</h2><ol><li id="guide-step-setup-1" data-guide-step>Leave the upstairs spawn through either purchasable route into the main building. Open paths to Doctor’s Quarters, Fishing Hut, Storage and the Comm Room. Slow swamp water can trap you; learn the boardwalks before moving a horde.</li>
<li id="guide-step-setup-2" data-guide-step>Open each hut to reveal its random perk machine. Jugger-Nog, Speed Cola, Double Tap and Quick Revive move between the four huts each match. There is no central power switch to activate. The notebook is optional if your team keeps forgetting which hut has which perk.</li>
<li id="guide-step-setup-3" data-guide-step>The Mystery Box can provide the Wunderwaffe DG-2; the Flogger outside the main building and hut traps give additional crowd control. Keep a starting pistol if you want the pan secret below. There is no ordinary Pack-a-Punch machine.</li></ol><InlineTool tool="bo3-shi-perks" /></section>
<h1 id="wiki_side_quests">Side Quests</h1><section><h2 id="details-secrets">The One and the Fishing Hut doll hunt</h2><ol><li id="guide-step-secrets-2" data-guide-step>At the Comm Room, interact with the black telephone three times. You will hear the call and The One will play. This does not start the Samantha hunt.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/shi-no-numa/song_ee/phone.webp&quot;,&quot;alt&quot;:&quot;phone&quot;}]' /></li>
<li id="guide-step-secrets-1" data-guide-step>Inside Fishing Hut, quickly shoot the four hanging pans that have a silver band using your starting pistol. Use the four photographs to distinguish them from the other pans. A sound confirms all four have registered.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/shi-no-numa/free_max_ammo/plate_1.webp&quot;,&quot;alt&quot;:&quot;Plate 1&quot;},{&quot;src&quot;:&quot;/images/chronicles/shi-no-numa/free_max_ammo/plate_2.webp&quot;,&quot;alt&quot;:&quot;Plate 2&quot;},{&quot;src&quot;:&quot;/images/chronicles/shi-no-numa/free_max_ammo/plate_3.webp&quot;,&quot;alt&quot;:&quot;Plate 3&quot;},{&quot;src&quot;:&quot;/images/chronicles/shi-no-numa/free_max_ammo/plate_4.webp&quot;,&quot;alt&quot;:&quot;Plate 4&quot;}]' /></li>
<li id="guide-step-secrets-dolls" data-guide-step>Interact with the doll on the ground beside the rubbish near Fishing Hut. Turn toward the bridge outside the hut and shoot each doll as it appears on the bridge supports. The targets appear in succession; keep watching until the sequence finishes.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/shi-no-numa/free_max_ammo/doll.webp&quot;,&quot;alt&quot;:&quot;Samantha Doll&quot;},{&quot;src&quot;:&quot;/images/chronicles/shi-no-numa/free_max_ammo/doll_bridge.webp&quot;,&quot;alt&quot;:&quot;bridge outside the Fishing Hut&quot;}]' /></li>
<li id="guide-step-secrets-finish" data-guide-step>Return to the original doll and interact to receive a Max Ammo and play Samantha’s Sorrow. If the hunt stops before completion, use that same starter doll to try again.</li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Written for Black Ops III: Zombies Chronicles. Community instructions and illustrated references were cross-checked on 3 October 2026. Gameplay: Activision / Treyarch; photographs and charts: the credited community sources below. Some shared-layout references show the original release; follow the BO3 instructions in the text. Source review and website checks do not replace an in-game playthrough.</p><ul><li><a href="https://www.reddit.com/r/CODZombies/wiki/shi-no-numa/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide ↗</a></li>
<li><a href="https://mmmrkennedy.com/games/WAW/shi_no_numa/shi_no_numa_guide" target="_blank" rel="noopener noreferrer">mmmrkennedy illustrated guide (2) ↗</a></li></ul><p>Select any reference image to enlarge it. Screenshot and symbol sources are credited in the linked walkthroughs; this guide uses local copies for reliable access.</p></section></div></template>
