<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><h1 id="wiki_key_features">Key Features</h1><section><h2 id="details-setup">Power and Pack-a-Punch</h2><ol><li id="guide-step-setup-1" data-guide-step>Open a route from the lobby to the stage through either side of the theatre. Flip the power switch on the stage to open the curtain and connect the stage to the seating area and lobby.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/kino-der-toten/power/power.webp&quot;,&quot;alt&quot;:&quot;on the stage&quot;}]' /></li>
<li id="guide-step-setup-link" data-guide-step>Interact with the teleporter on the stage to begin linking, then run to the circular pad in the lobby and interact there to finish the link. Both parts are required before the stage teleporter will take you to Pack-a-Punch.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/kino-der-toten/pap/mainframe.webp&quot;,&quot;alt&quot;:&quot;teleporter mainframe on the stage&quot;},{&quot;src&quot;:&quot;/images/chronicles/kino-der-toten/pap/teleporter_pad.webp&quot;,&quot;alt&quot;:&quot;teleporter pad in the spawn room&quot;}]' /></li>
<li id="guide-step-setup-2" data-guide-step>Return to the stage teleporter and activate it. In the projector room, spend 5,000 points at Pack-a-Punch and collect your gun before the roughly 30-second visit ends. After returning and the cooldown finishing, link the two pads again for another trip.</li>
<li id="guide-step-setup-3" data-guide-step>Teleporter returns can briefly send you through small side rooms. Search those rooms for a film reel and pick it up before the return completes. On your next Pack-a-Punch trip, interact with the projector to play the reel. Repeat trips to find the other reels; the room order is random.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/kino-der-toten/film_reels/projector.webp&quot;,&quot;alt&quot;:&quot;Projector in the Pack-a-Punch room&quot;}]' /></li></ol></section>
<h1 id="wiki_side_quests">Side Quests</h1><section><h2 id="details-secrets">115, film reels and Samantha knocks</h2><ol><li id="guide-step-secrets-1" data-guide-step>Interact with three red meteor fragments to play 115: the jar under the lobby stairs by Quick Revive, the stand near the dressing-room mannequins behind the KN-44 wall buy, and the shelf with letters in the upstairs room on the Alley side.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/kino-der-toten/song_ee/rock_spawn.webp&quot;,&quot;alt&quot;:&quot;Spawn Room - In a jar near a Zombie barrier, \&quot;below\&quot; the stairs closest to Quick Revive&quot;},{&quot;src&quot;:&quot;/images/chronicles/kino-der-toten/song_ee/rock_dressing_room.webp&quot;,&quot;alt&quot;:&quot;Dressing Room - On a stand by some mannequins, behind the MP5K/KN-44 wallbuy&quot;},{&quot;src&quot;:&quot;/images/chronicles/kino-der-toten/song_ee/rock_alley.webp&quot;,&quot;alt&quot;:&quot;Upstairs Alley Room - On a shelf with the letters, right of a zombie spawn&quot;}]' /></li>
<li id="guide-step-secrets-2" data-guide-step>At the blue door in the Alley, listen to the three groups of knocks. Melee the door with the same number of hits per group, leaving a short pause between groups. After it accepts the answer, listen again: you must answer three different patterns in total.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/kino-der-toten/free_max_ammo/blue_door.webp&quot;,&quot;alt&quot;:&quot;blue door in the Alley&quot;}]' /></li>
<li id="guide-step-secrets-3" data-guide-step>After the third accepted knock pattern, start the doll at the stage. Complete the five-target hunt described in the Samantha section below, then return to its starter for the Max Ammo and song.</li></ol><InlineTool tool="bo3-kino-knocks" /></section>
<section><h2 id="details-samantha">Find the five active dolls</h2><ol><li id="guide-step-kino-doll-start" data-guide-step>After all three knock responses are accepted, interact with the doll at the front-right of the stage. Shoot five targets, one at a time, from the ten possible locations. Use the photographs below and follow the sound near the active target.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/kino-der-toten/free_max_ammo/doll_init_loc.webp&quot;,&quot;alt&quot;:&quot;Samantha Doll&quot;}]' /></li>
<li id="guide-step-kino-doll-finish" data-guide-step>If a laugh interrupts the hunt, return to the stage starter doll and try again. Once all five are shot, interact with the original doll to collect a Max Ammo and play Samantha’s Sorrow.</li></ol><InlineTool tool="bo3-kino-dolls" /></section>
<section><h2 id="details-rocket">Launch the model rocket</h2><ol><li id="guide-step-kino-rocket" data-guide-step>With power on, stand beside the left of the two dressing-room mannequins near the door toward Speed Cola and jump five times. During later teleporter trips, if you land in the Pentagon side room, interact with the small rocket model to launch it. Getting that room is random.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/chronicles/kino-der-toten/rocket_launch/mannequins.webp&quot;,&quot;alt&quot;:&quot;two mannequins&quot;},{&quot;src&quot;:&quot;/images/chronicles/kino-der-toten/rocket_launch/rocket.webp&quot;,&quot;alt&quot;:&quot;Rocket model&quot;}]' /></li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Written for Black Ops III: Zombies Chronicles. Community instructions and illustrated references were cross-checked on 3 October 2026. Gameplay: Activision / Treyarch; photographs and charts: the credited community sources below. Some shared-layout references show the original release; follow the BO3 instructions in the text. Source review and website checks do not replace an in-game playthrough.</p><ul><li><a href="https://www.reddit.com/r/CODZombies/wiki/kino-der-toten/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide ↗</a></li>
<li><a href="https://mmmrkennedy.com/games/BO1/kino_der_toten/kino_der_toten_guide" target="_blank" rel="noopener noreferrer">mmmrkennedy illustrated guide (2) ↗</a></li></ul><p>Select any reference image to enlarge it. Screenshot and symbol sources are credited in the linked walkthroughs; this guide uses local copies for reliable access.</p></section></div></template>
