<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><section><h2 id="details-setup">Key Features: Pegasus and hands</h2><ol><li id="guide-step-setup-1" data-guide-step>Activate the Sentinel Artifact, obtain the Golden Bridle and survive the Pegasus route into the second map area. Free the eagles and complete the Pack-a-Punch defense.</li>
<li id="guide-step-setup-2" data-guide-step>Build Apollo’s Will and locate dormant hands using the Oracle’s location hints. Bring each to its god shrine and complete its acquisition trial.</li>
<li id="guide-step-setup-3" data-guide-step>Upgrade the four hands to their required stages. Keep Gaia, Hemera, Charon and Ouranos progress separate.</li></ol><InlineTool tool="bo4-ancient-hands" /></section>
<section><h2 id="details-flame">Flame, statues and mechanisms</h2><ol><li id="guide-step-flame-1" data-guide-step>Complete the challenge sequence needed to obtain the Eternal Flame. Use the shield and oil locations to carry out the flame step.</li>
<li id="guide-step-flame-2" data-guide-step>Use Charon’s hand for the statue sequence and the shield for the cog interactions. Follow the quest’s revealed order rather than marking all statues by sight alone.</li>
<li id="guide-step-flame-3" data-guide-step>Obtain the Ankh and use Hemera with the Ra mechanism. Defend the beam sequence and collect the scepter.</li></ol></section>
<section><h2 id="details-theater">Sundial and theater</h2><ol><li id="guide-step-theater-1" data-guide-step>At the sundial, stop each rotating ring as its blue section passes beneath the beam. This is a live timing action, not a fixed numeric code.</li>
<li id="guide-step-theater-2" data-guide-step>Assign players to their hands for the theater performance. Watch the active cue and respond with the matching hand during each round of the performance.</li></ol><InlineTool tool="bo4-ancient-theater" /></section>
<section><h2 id="details-boss">Ballista and final arena</h2><ol><li id="guide-step-boss-1" data-guide-step>Complete the ballista sequence using the required Pegasus Strike, Ouranos and venom/fire interactions, then prepare the team before entering the final area.</li>
<li id="guide-step-boss-2" data-guide-step>Damage Pegasus during the exposed windows while avoiding its attacks. Continue into the Perseus encounter and exploit its vulnerable windows until the ending.</li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Original concise walkthrough adapted from the sources below. Research reviewed 2026-09-30. Use their illustrated references for exact object sightlines. Gameplay verification is ongoing.</p><ul><li><a href="https://www.reddit.com/r/CODZombies/wiki/ancient-evil/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide ↗</a></li></ul></section></div></template>
