<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><section><h2 id="details-setup">Key Features: transport and Pack-a-Punch</h2><ol><li id="guide-step-setup-1" data-guide-step>Restore power across the ship and facility routes, activate transport and unlock Pack-a-Punch access. Build the shield and prepare a strong weapon.</li>
<li id="guide-step-setup-2" data-guide-step>Speak with the Hermit and complete the two required challenge-totem rewards. Return to him when the rewards are confirmed.</li></ol></section>
<section><h2 id="details-offerings">Offerings and Seal</h2><ol><li id="guide-step-offerings-1" data-guide-step>Complete the dial interaction, then listen to each offering riddle. Identify the landmark and collect its offering before requesting or completing the next clue.</li>
<li id="guide-step-offerings-2" data-guide-step>Use the separate Seal riddle to identify its safe. Obtain dynamite and open the correct target rather than treating it as another ordinary offering.</li>
<li id="guide-step-offerings-3" data-guide-step>Bring the quest items back through the Hermit sequence.</li></ol><InlineTool tool="bo4-tag-riddles" />
<InlineTool tool="bo4-tag-challenges" /></section>
<section><h2 id="details-orbs">Orbs, campfire and soapstones</h2><ol><li id="guide-step-orbs-1" data-guide-step>Follow the orb sequence, using snowballs/freezing interactions where required. Complete the campfire/music-box step and watch for the next success cue.</li>
<li id="guide-step-orbs-2" data-guide-step>Heat the soapstones and cool them through the correct route. Do not substitute immersion in water for the instructed cooling action.</li>
<li id="guide-step-orbs-3" data-guide-step>Obtain the fuse and charged Wunderwaffe battery, then complete the generator tasks.</li></ol></section>
<section><h2 id="details-finale">Lighthouse and final charges</h2><ol><li id="guide-step-finale-1" data-guide-step>Repeat the required orb/campfire sequence and survive the lighthouse lockdown. Replenish before beginning the final charging route.</li>
<li id="guide-step-finale-2" data-guide-step>Complete all four Pack-a-Punch charges and the Golden Pack-a-Punch stage. Track each separately.</li>
<li id="guide-step-finale-3" data-guide-step>Stay with the final escort and finish the ending interaction after the charges are complete.</li></ol><InlineTool tool="bo4-tag-challenges" /></section><section><h2 id="guide-sources">Sources and review</h2><p>Original concise walkthrough adapted from the sources below. Research reviewed 2026-09-30. Use their illustrated references for exact object sightlines. Gameplay verification is ongoing.</p><ul><li><a href="https://www.reddit.com/r/CODZombies/wiki/tag-der-toten/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide ↗</a></li></ul></section></div></template>
