<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><h1 id="wiki_key_features">Key Features</h1><section><h2 id="details-setup">Power, shield &amp; quest equipment</h2><p class="guide-callout">For a first clear, choose survivability and movement perks, keep a strong upgraded weapon, and use the Magmagat to pull crowds away from interactions. The main quest needs the Spoon and Retriever; their upgrades are optional.</p><ol><li id="guide-step-setup-1" data-guide-step>Turn on power in the Power House on the spawn side, then cross the Catwalk and work through the prison to Building 64 for the second switch. Kill the first Warden and collect his key. Build the Spectral Shield, open Pack-a-Punch and feed the three wall dogs before starting the quest.<ul><li>Shield essence: check the blue electrical boxes in Library, Michigan Avenue and Times Square. Only one holds the part.</li><li>Shield door: check the Citadel Tunnels staircase, its lower section and China Alley. Add the key dropped by the Warden, then build at a workbench, such as Cell Block 3rd Floor or Docks.</li><li>With the shield equipped, drain three zombie souls using the key to earn a Spirit Blast. Aim and fire at the Roof voltmeter to reveal Pack-a-Punch. Later, check Roof, Power House and Building 64 when it moves.</li><li>Feed the dog heads at New Industries, Cell Block 2nd Floor and Eagle Plaza. Kill one zombie at a time and wait for the chewing animation. When all three disappear, take the Warden’s House ↔ Showers fast travel and hold interact as you pass the floating Retriever.</li></ul></li>
<li id="guide-step-setup-spoon" data-guide-step>Read the three pillar numbers in the Warden’s Office through the shield. Spirit Blast the Citadel Tunnels number pad and enter that code. After the elevator falls, Spirit Blast the Docks voltmeter to move the crane. Throw the Retriever at the skeleton in the raised net, then collect the Spoon from the crate below.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/blood-of-the-dead/spoon-code.webp&quot;,&quot;alt&quot;:&quot;The three spectral digits on the Warden’s Office pillars&quot;}]' /></li>
<li id="guide-step-setup-monkeys" data-guide-step>Get Monkey Bombs from the Mystery Box or use the free quest below: reach Specialist level 2, feed the C-D Street monkey statue with Specialist kills, shoot it when its hat glows red, then collect the bombs in Richtofen’s Laboratory. Save one for the hidden room.<p><a href="#details-monkeys">Free Monkey Bombs: location and steps ↗</a></p></li>
<li id="guide-step-setup-2" data-guide-step>Prepare a Blundergat or Magmagat for crowd control, then open the Warden’s hidden room. At the top of the Warden’s House stairs, hit the left wall with the Spoon to scratch it. Bring Brutus upstairs and throw a Monkey Bomb directly below that wall; move away and let his electrical slam break it.<ul><li>Enter 666 at the charged Citadel pad if you need to summon Brutus. This summon is a once-per-game resource; keep him alive until the wall is open.</li><li>The Monkey Bomb route avoids waiting for his later-round electrical slam. Keep other players away from the wall so he targets the bomb.</li><li>Inside the Ritual Room, pull the lever beside the electric chair and collect the red stone from the opposite table.</li></ul><p><a href="#details-blundergat">Free Blundergat and skull locations ↗</a> · <a href="#details-magmagat">Magmagat upgrade route ↗</a></p><GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/blood-of-the-dead/ritual-wall.webp&quot;,&quot;alt&quot;:&quot;The wall to scratch at the top of the Warden’s House staircase&quot;}]' /></li>
<li id="guide-step-setup-3" data-guide-step>Place the red stone on the map in Richtofen’s Laboratory. Interact with the Kronorium on the floor to release the bird. Keep the shield repaired and charged: looking through it reveals clues, but Spirit Blasting spends a charge.</li></ol></section>
<h1 id="wiki_main_quest">Main Quest</h1><section><h2 id="details-birds">Find the bird &amp; recover the Kronorium</h2><ol><li id="guide-step-birds-1" data-guide-step>Listen for the bird’s cry, then look through the Spectral Shield to see its perch. Spirit Blast it once. Advance a round and repeat, for three successful blasts on three separate rounds. Search shelves, railings and ledges; hearing it narrows the search, but the shield confirms the actual perch.<ul><li>Do not waste blasts shooting an ordinary-looking location without first confirming the bird in shield vision.</li><li>After a successful blast, prepare your gear before ending the round; the next bird is round-gated.</li></ul><p><a href="https://www.youtube.com/watch?v=Fem_C1VLsfY" target="_blank" rel="noopener noreferrer">Video reference: all 38 bird perches ↗</a></p></li>
<li id="guide-step-birds-2" data-guide-step>On the next round, listen for crying as well as the bird. The final target looks like a faint sparkling orb through the shield. Locate it before collecting Zombie Blood. Enter 872 at the Citadel pad, collect the power-up and return quickly. Look at the orb through the shield to reveal the bird sitting on the book; lower the shield and throw the Retriever to retrieve the Kronorium, then pick it up from the ground.<p class="guide-callout">Do not Spirit Blast the final bird. In co-op, leave only the Zombie Blood player in its room during the retrieval; the community guide reports problems when teammates crowd it.</p></li>
<li id="guide-step-birds-3" data-guide-step>Put the Kronorium on the corpse in the Ritual Room’s electric chair. Interact to stop the pages, read the three digits through the shield, and enter them at the Citadel pad. Follow the lighthouse beam, reveal the red portal with shield vision, then Spirit Blast it to activate the assigned challenge.<p class="guide-callout">The five challenges arrive in a random order. Choose the branch named by your portal below. After success, collect its red stone and return to the book. After a failure, advance a round and read the new code; you may receive another unfinished branch.</p></li></ol><InlineTool tool="bo4-blood-trials" /></section>
<section><h2 id="details-challenges">Power House — Simon, symbols &amp; levers</h2><ol><li id="guide-step-challenges-1" data-guide-step>After activating the Power House portal, travel to Building 64 and interact with the sparking generator. Repeat the panel sequence in its displayed order for five Simon rounds. At the end, record the symbols beside the three lights that stay on. Ignore the flashing decoy.<p class="guide-callout">Use the sequence recorder while watching the panels. Its labels are your own position names, not an assumed room layout. The symbol picker below uses the same 1–6 labels as the community reference sheet.</p></li>
<li id="guide-step-powerhouse-card" data-guide-step>Pick up the punch card from the shelf in the middle of Building 64. Insert it into the computer in Model Industries. Find the three monitors showing your recorded generator symbols and interact with each one. Record the new symbol each monitor displays beside its original.<p class="guide-callout">Do not assume that symbol 1 turns into A, 2 into B, and so on. The two columns on the reference image are separate alphabets. Read and save the actual replacement shown by each monitor.</p><GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/blood-of-the-dead/punchcard.webp&quot;,&quot;alt&quot;:&quot;The punch card on the shelf inside Building 64&quot;}]' /></li>
<li id="guide-step-powerhouse-levers" data-guide-step>Return to the Power House. Look through the shield to find the spirit moving between levers. Match each lever’s symbol to one of your three replacements. Spirit Blast the ghost as it attempts to pull a matching lever, allowing it to pull successfully. Repeat for all three targets, then collect the red stone.</li>
<li id="guide-step-challenges-2" data-guide-step>If the book sends you elsewhere, use the Docks, Showers, New Industries or Michigan Avenue instructions below. Each branch has its own objective; finishing one does not start the others automatically.</li>
<li id="guide-step-challenges-3" data-guide-step>Refill Spirit Blasts between interactions and collect the actual reward stone before marking a trial complete. Seeing a clue or saving a symbol in a helper does not finish the in-game challenge.</li></ol><InlineTool tool="bo4-blood-powerhouse" /></section>
<section><h2 id="details-morse">Docks — Morse code &amp; spirit escort</h2><ol><li id="guide-step-morse-1" data-guide-step>After activating the Docks portal, look through your shield at the three offshore buoys. Each flashes one five-pulse Morse digit. Record each as a digit or tap its short and long flashes into the helper.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/blood-of-the-dead/buoy-gondola.webp&quot;,&quot;alt&quot;:&quot;Upper Gondola platform: look out over the water&quot;},{&quot;src&quot;:&quot;/images/blood-of-the-dead/buoy-yard.webp&quot;,&quot;alt&quot;:&quot;Recreation Yard: look out near the Swordfish wallbuy&quot;},{&quot;src&quot;:&quot;/images/blood-of-the-dead/buoy-model.webp&quot;,&quot;alt&quot;:&quot;Model Industries: look out through the barrier toward the water&quot;}]' /></li>
<li id="guide-step-morse-2" data-guide-step>Add the three decoded digits. At the telegraph in the Sally Port cage, enter that total as Morse, one decimal digit at a time. Tap interact for a dot and hold for about 2–3 seconds for a dash. For example, 4 + 7 + 2 = 13: enter .---- then ...--. A laugh means the attempt failed; check the clues and restart the input.<p class="guide-callout">Recommended: read the buoys for a known answer. Alternative: the older trial-and-error method builds a correct prefix from short/long attempts and the Warden’s laugh. It is harder to track; use it only if you cannot read a buoy. Never use the unrelated Warden’s House lamp as your clue.</p></li>
<li id="guide-step-morse-3" data-guide-step>After the success quote, go to the Infirmary and kill a zombie in the room with the spirit on a stretcher. Reveal the ghost with shield vision and Spirit Blast it. Interact if it does not start following, then kill zombies close to it to keep it moving. Escort it to the spectral boat at the Docks and collect the red stone.</li></ol><InlineTool tool="bo4-blood-morse" /></section>
<section><h2 id="details-showers">Showers — banjo defense</h2><ol><li id="guide-step-showers-banjo" data-guide-step>Activate the Showers portal and interact with the banjo-playing ghost to take its instrument. Stand in the blue circle and kill zombies to feed it. Leaving the safe circle while carrying the banjo hurts you, so clear threats before moving.</li>
<li id="guide-step-showers-return" data-guide-step>After a circle finishes, return the banjo to the ghost and take it again for the next defense. Keep repeating until no more circles appear. Return the instrument and collect the red stone.</li></ol></section>
<section><h2 id="details-new-industries">New Industries — drain &amp; trap the ghost</h2><ol><li id="guide-step-industries-reveal" data-guide-step>With the New Industries portal active, kill a zombie in the Library. Look through the shield and Spirit Blast the revealed ghost. Follow it and continuously drain it with the shield’s key attack. If it becomes invisible again, spend another Spirit Blast and resume draining.</li>
<li id="guide-step-industries-trap" data-guide-step>Keep draining until the ghost is bright red with raised arms. Get ahead of it and switch on the New Industries blade trap before it arrives. It must be fully drained and caught in the running trap; if it reaches and kills the other ghost, the attempt has failed. Collect the red stone after a successful trap kill.<p class="guide-callout">Prepare shield charges and trap points before starting. In co-op, assign one player to drain and another to prepare the trap so nobody loses the moving target.</p></li></ol></section>
<section><h2 id="details-michigan">Michigan Avenue — protect the escort</h2><ol><li id="guide-step-michigan-reveal" data-guide-step>Activate the Michigan Avenue portal, then kill a zombie in the Cafeteria. Reveal the spirit with the shield and Spirit Blast it to start the escort. Bring the whole team to the spirit.</li>
<li id="guide-step-michigan-escort" data-guide-step>Stay with the spirit and kill the zombies attacking it all the way to the Michigan Avenue portal. Use crowd control to keep the route open and avoid firing through the spirit. When it reaches the portal, collect the red stone and return to the Kronorium.</li></ol></section>
<section><h2 id="details-finale">Prison escape &amp; the Warden</h2><ol><li id="guide-step-finale-1" data-guide-step>Once all five stones are collected, place them on the lab map. Take the Summoning Key to the Ritual Room corpse and place it in its chest. Gather all players around the chair to trigger the prison sequence. After the bird opens your cell, equip a shield, recover your weapons from the bag and follow it back to the lab.</li>
<li id="guide-step-finale-door" data-guide-step>Watch the spirits confront the Warden in the lab. Collect the orb left behind and put it on the map. Prepare ammunition, perks and shield charges before committing to the arena. Gather everyone on the illuminated floor positions at the top of the newly opened stairs and hold interact to enter.</li>
<li id="guide-step-finale-2" data-guide-step>In the arena, keep at least one Spirit Blast available. Kill the supporting enemies until the Warden’s red protective zone appears; get inside it. Shoot the glowing orbs above him, then Spirit Blast the exposed orb above the central Dark Mechanism. Repeat the enemy wave, safe-zone and orb sequence for three cycles.<p class="guide-callout">Use the red zone when it appears. Do not spend your last Spirit Blast on an ordinary enemy just before the central mechanism opens.</p></li>
<li id="guide-step-finale-3" data-guide-step>During the third stage, Richtofen interacts with the central machine and sits in the chair. Follow that character’s sequence back from the cryostasis chamber to the arena; the Fire Staff crystal enables the finish. Defeat the giant Warden to complete Most Escape Alive. In solo, the game supplies the needed Richtofen interaction when applicable.</li></ol></section>
<h1 id="wiki_side_quests">Side Quests</h1><section><h2 id="details-blundergat">Free Blundergat — five skulls</h2><p class="guide-callout">The free quest gives you a dependable route to the weapon. A Mystery Box Blundergat is an alternative; either can be upgraded.</p><ol><li id="guide-step-side-skulls" data-guide-step>Use shield vision to spot each skull and throw the Retriever to collect it. Check West Grounds outside Model Industries, the C-D Street cell toilet, the Roof crate, a Docks wooden pillar and the Eagle Plaza power pole. After all five, collect the Blundergat from the Warden’s Office desk.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/blood-of-the-dead/skull-west.webp&quot;,&quot;alt&quot;:&quot;West Grounds: outside the Model Industries stairs&quot;},{&quot;src&quot;:&quot;/images/blood-of-the-dead/skull-cell.webp&quot;,&quot;alt&quot;:&quot;C-D Street: skull in the cell toilet&quot;},{&quot;src&quot;:&quot;/images/blood-of-the-dead/skull-roof.webp&quot;,&quot;alt&quot;:&quot;Roof: crate beside the Pack-a-Punch area&quot;},{&quot;src&quot;:&quot;/images/blood-of-the-dead/skull-docks.webp&quot;,&quot;alt&quot;:&quot;Docks: skull on a wooden pillar&quot;},{&quot;src&quot;:&quot;/images/blood-of-the-dead/skull-eagle.webp&quot;,&quot;alt&quot;:&quot;Eagle Plaza: skull on the power pole&quot;}]' /></li></ol><InlineTool tool="bo4-blood-skulls" /></section>
<section><h2 id="details-magmagat">Magmagat — fireplace &amp; barrel run</h2><ol><li id="guide-step-side-magma-fill" data-guide-step>Put the Blundergat in the Warden’s House fireplace. Stay inside, kill zombies and collect their essence. When all three fireplace skulls are lit, deposit the essence and take the Tempered Blundergat from the blue fire.</li>
<li id="guide-step-side-magma-route" data-guide-step>Carry it toward New Industries, refreshing its heat at the blue barrels: Eagle Plaza → Michigan Avenue → Cell Block Entrance → Recreation Yard → West Grounds. Keep the weapon unfired and avoid fast travel. At New Industries, place it in the press and collect the forged Magmagat.<p class="guide-callout">Walk the route and open its doors before taking the tempered weapon. After the first Magmagat is made, teammates can put normal Blundergats straight into the press.</p></li></ol></section>
<section><h2 id="details-acidgat">Acidgat — an alternative upgrade</h2><ol><li id="guide-step-side-acidgat" data-guide-step>Collect the case in Transverse Tunnel, the motor behind the locked Sally Port door and the acid bottle in the locked Infirmary cage. Use the Warden’s Key for the locks. Build the kit at a workbench, insert a Blundergat and collect the Acidgat after the conversion. Its lingering shots can attract zombies, but watch the splash damage.</li></ol></section>
<section><h2 id="details-monkeys">Free Monkey Bombs</h2><ol><li id="guide-step-side-monkey" data-guide-step>Level your Specialist weapon to level 2. At the monkey statue outside the playable area in C-D Street, get Specialist kills nearby until the hat glows red. Shoot the statue so it floats away, then collect Monkey Bombs from the small teleporter pad on a table in Richtofen’s Laboratory.<p class="guide-callout">Useful for opening the Ritual Room early. The Mystery Box is the alternative if you already have the points.</p><GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/blood-of-the-dead/monkey.webp&quot;,&quot;alt&quot;:&quot;The monkey statue outside the C-D Street cell area&quot;}]' /></li></ol></section>
<section><h2 id="details-shield-upgrade">Attuned Shield &amp; free charges</h2><ol><li id="guide-step-side-attuned" data-guide-step>When a used Mystery Box displays its departing lock, drain the lock with the shield’s key until the keyhole turns blue. Throw the Retriever at it to collect it. The Attuned Spectral Shield holds two additional Spirit Blasts and takes more damage before breaking.</li>
<li id="guide-step-side-charge" data-guide-step>Once per round, look for a sparking electrical box and interact while holding the shield for a free charge refill. Check boxes along your route, including Library, Michigan Avenue, Times Square, Citadel Tunnels, Showers, Infirmary, Power House, New Industries, Docks Bridge and Cell Block 3rd Floor. An inactive box will not refill it.</li></ol></section>
<section><h2 id="details-spork">Golden Spork</h2><ol><li id="guide-step-side-spork" data-guide-step>Put the Spoon in the Infirmary bathtub. Get Acidgat or Magmagat kills on the Roof until the bath fills with blood, then interact to drain it. Shoot the yellow supports on the water tower near the Catwalk until it collapses. Throw the Retriever at the branch in front of the fallen tower to collect the Golden Spork. This upgrade is optional for the main quest.</li></ol></section>
<section><h2 id="details-redeemer">Hell’s Redeemer</h2><ol><li id="guide-step-side-redeemer-kills" data-guide-step>In Recreation Yard, find a position where your thrown Retriever glows blue, such as near the flaming barrel. Keep getting Retriever kills from that position until you hear a howl and it stops glowing blue.</li>
<li id="guide-step-side-redeemer-mark" data-guide-step>Search with shield vision for the blue dog mark, checking Recreation Yard, Eagle Plaza and Citadel. Throw the Retriever into it; the mark disappears and your Retriever is removed.<p><a href="https://www.reddit.com/r/CODZombies/wiki/blood-of-the-dead/#wiki_hell.27s_redeemer" target="_blank" rel="noopener noreferrer">Community screenshots of possible dog marks ↗</a></p></li>
<li id="guide-step-side-redeemer-dog" data-guide-step>On a later dog-only round, track the ghost dog using its pawprints and shield vision. Spirit Blast it, then take the Warden’s House ↔ Showers fast travel and collect the Redeemer from the same rock as the original Retriever.</li></ol></section>
<section><h2 id="details-scalpel">Golden Scalpel &amp; Sporknife</h2><p class="guide-callout">A long optional project, best saved for a separate run. It is not required to finish Most Escape Alive.</p><ol><li id="guide-step-side-scalpel" data-guide-step>After obtaining the Redeemer, get 100 Golden Spork kills, then place the Spork in the dark-red New Industries tub. Retrieve three rocks: green outside D-Block, blue in the Docks crane net, red on the Warden’s House roof corner. Place green at the Cafeteria acid trap, blue at the Office fan trap and red at the New Industries blade trap. Get 100 trap kills at each and retrieve the shiny gems.</li>
<li id="guide-step-side-scalpel-forge" data-guide-step>Take Cafeteria fast travel to Transverse Tunnel. Turn back and throw the Redeemer into the closing exit to retrieve the gold nugget. Pick it up and use the New Industries press with the collected gems to obtain the Golden Scalpel.</li>
<li id="guide-step-side-sporknife" data-guide-step>Put the Scalpel in the New Industries tub. At the Catwalk knife-and-cloth sign, finish a Warden with a regular melee attack; Path of Sorrows does not count. When the cloth disappears, return to the tub for the Golden Sporknife.<p><a href="https://mmmrkennedy.com/games/BO4/blood_of_the_dead/blood_of_the_dead_guide" target="_blank" rel="noopener noreferrer">Illustrated advanced melee-upgrade locations ↗</a></p></li></ol></section>
<section><h2 id="details-secrets">Music, power-ups &amp; small secrets</h2><ol><li id="guide-step-side-song" data-guide-step>Music: Spirit Blast the Citadel Tunnels number pad and enter 115 to activate the song Easter egg. This is separate from 872 for Zombie Blood and the random codes read from the Office or Kronorium.</li>
<li id="guide-step-side-powerups" data-guide-step>Free power-ups: look for prison cells with a power-up inside at Times Square and Michigan Avenue. Spirit Blast the nearby voltmeter to open the cell.</li>
<li id="guide-step-side-sketch" data-guide-step>Richtofen sketch: with the Golden Spork equipped, melee the DEAL WITH IT sign in Michigan Avenue beside the Warden’s Office entrance. Look below it for the revealed sketch.</li>
<li id="guide-step-side-jumpscare" data-guide-step>Shadowman jumpscare: use a sniper scope from Recreation Yard to look into the marked prison window. Use the screenshot reference to line up the sightline.<p><a href="https://www.reddit.com/r/CODZombies/wiki/blood-of-the-dead/#wiki_shadowman_jumpscare" target="_blank" rel="noopener noreferrer">Exact jumpscare window reference ↗</a></p></li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Researched against the r/CODZombies community walkthrough, with the newer buoy Morse method cross-checked separately. Symbol images are visual references: monitor replacements must be read in your own game. This revision has not yet been verified in a complete in-game run.</p><ul><li><a href="https://www.reddit.com/r/CODZombies/wiki/blood-of-the-dead/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide ↗</a></li>
<li><a href="https://www.codzombiesguides.com/main-quests/black-ops-4/blood-of-the-dead/" target="_blank" rel="noopener noreferrer">Supplementary walkthrough (2) ↗</a></li>
<li><a href="https://mmmrkennedy.com/games/BO4/blood_of_the_dead/blood_of_the_dead_guide" target="_blank" rel="noopener noreferrer">Supplementary walkthrough (3) ↗</a></li>
<li><a href="https://www.reddit.com/r/CODZombies/comments/xbnzvw/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide (4) ↗</a></li></ul><p>Location screenshots: COD Zombies Guides. Symbol reference: r/CODZombies community sheet. Select a location image to enlarge it.</p></section></div></template>
