<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><section><h2 id="details-setup">Key Features: Sentinel and Pack-a-Punch</h2><ol><li id="guide-step-setup-1" data-guide-step>Activate the Sentinel Artifact at the Grand Staircase. Find the three crystal/gazing-stone locations and charge them with nearby kills.</li>
<li id="guide-step-setup-2" data-guide-step>Look into each charged stone and identify its vision. Follow the corresponding clock defense, ghost escort or perk-machine enemy task to earn the tuning forks.</li>
<li id="guide-step-setup-3" data-guide-step>Use the tuning forks to clear the forest barrier, defeat the werewolf and reach Pack-a-Punch. Build the shield from its parts around the mansion.</li></ol></section>
<section><h2 id="details-weapons">Silver bullets and Alistair upgrades</h2><ol><li id="guide-step-weapons-1" data-guide-step>Collect the silver objects and smelt them in the Wine Cellar, then combine the silver with the bullet ingredients at the Library workbench. Silver ammunition is important for werewolves.</li>
<li id="guide-step-weapons-2" data-guide-step>Find the four colored glyphs around the grounds and mansion. Record each glyph under its color and set the Library lock to obtain Alistair’s Folly.</li>
<li id="guide-step-weapons-3" data-guide-step>Obtain the upgrade ingredients, including the silver-bullet werewolf material and the hidden Library component, and craft Chaos Theory at the Greenhouse workbench.</li>
<li id="guide-step-weapons-4" data-guide-step>For Alistair’s Annihilator, shoot the orange Mausoleum lamps with Chaos Theory as they light in sequence. Kill the bat released by the final lamp and collect its material.</li>
<li id="guide-step-weapons-5" data-guide-step>Kill vampires with Chaos Theory’s tornado charge and collect four bile drops. Interact with the red coffin in the cemetery, defeat the Crimson Nosferatu and collect its material.</li>
<li id="guide-step-weapons-6" data-guide-step>In the forest, look for three dirt mounds topped with blue mushrooms. Hit an enemy directly with the green charged shot near a mound so it digs; collect the part from the correct mound.</li>
<li id="guide-step-weapons-7" data-guide-step>Process the bat and Nosferatu materials separately in the Greenhouse machine, collecting each output. Build Alistair’s Annihilator at the rear workbench.</li></ol><InlineTool tool="bo4-dead-of-the-night-alistair" /></section>
<section><h2 id="details-telescope">Telescope and zodiac</h2><ol><li id="guide-step-telescope-1" data-guide-step>Revisit the three charged gazing stones after Pack-a-Punch. Their knight, circular-object and twig visions activate three independent quest branches.</li>
<li id="guide-step-telescope-2" data-guide-step>Have all players shoot the rod above the Mausoleum together using silver bullets. At the North Atrium Bridge panel, align Atlas’s rings: middle wheel to green, left to blue, right to red; repeat until the beam links to the telescope.</li>
<li id="guide-step-telescope-3" data-guide-step>Find the three zodiac observations. Each room has a sign and three scratch groups. Record all counts, including confirmed zeros, then total each room.</li>
<li id="guide-step-telescope-4" data-guide-step>Enter the telescope signs from lowest scratch total to highest. If an entry fails, the clues reroll: clear the helper and collect all signs and scratches again.</li>
<li id="guide-step-telescope-5" data-guide-step>With the shield out, hold interact at the dome crank until the roof opens, then shield-melee the crank to lock it. Activate the Greenhouse electric trap and have everyone run through it with shields out.</li>
<li id="guide-step-telescope-6" data-guide-step>Bring the electrified shields upstairs and bash the telescope together. Interact with the revealed slab as a team, survive the lockdown and collect the slab.</li></ol><InlineTool tool="bo4-dead-of-the-night-zodiac" /></section>
<section><h2 id="details-knights">Knight branch</h2><ol><li id="guide-step-knights-1" data-guide-step>Install a fire core at the Library fire trap. Activate it and shoot its flames with a charged Annihilator shot to turn them blue. Run through with the shield out, then shield-melee the fireplaces in the required order.</li>
<li id="guide-step-knights-2" data-guide-step>First fireplace run: Smoking Room → Library fireplace right of trap → Library fireplace left of trap → Billiards Room. Collect the crystal at the final fireplace.</li>
<li id="guide-step-knights-3" data-guide-step>Second run: Main Hall left → East Gallery → Main Hall right → West Gallery. Third run: Trophy Room → Master Bedroom → Music Room → Dining Room. Collect each run’s crystal.</li>
<li id="guide-step-knights-4" data-guide-step>Interact with the knights at Main Hall, Greenhouse Terrace and Graveyard. Stay close while leading their crystals to matching colored ground circles in the forest.</li>
<li id="guide-step-knights-5" data-guide-step>Kill zombies beside the ghost knights to move them toward Pack-a-Punch. Kill a werewolf inside their final triangle. Interact with the slab together, survive the lockdown and collect it.</li></ol></section>
<section><h2 id="details-effigy">Effigy branch</h2><ol><li id="guide-step-effigy-1" data-guide-step>Shoot and collect five branches from the white birch trees shedding leaves in the graveyard. Build the effigy using the collected branches.</li>
<li id="guide-step-effigy-2" data-guide-step>Find the gravestone with death date 1912. The eligible player interacts to enter spirit mode. Ignite the ground before the effigy with the Annihilator’s fireball charge, then have that player interact with the burning effigy.</li>
<li id="guide-step-effigy-3" data-guide-step>The player in afterlife searches the mansion for the female ghost, checking perk machines and barriers. Enemies still attack that player. Escort her back to the graveyard until she creates the flame column.</li>
<li id="guide-step-effigy-4" data-guide-step>Interact with the slab together, survive the defense and collect it. With all three slabs collected, use the forest door to enter the boss arena.</li></ol></section>
<section><h2 id="details-boss">Werewolf encounter</h2><ol><li id="guide-step-boss-1" data-guide-step>With all three branch slabs complete, replenish silver ammunition, armor and perks before starting the boss interaction.</li>
<li id="guide-step-boss-2" data-guide-step>Align the arena beams using the statues to reveal the target area. Lure the werewolf into the lit zone, then damage it during the vulnerable window.</li>
<li id="guide-step-boss-3" data-guide-step>Survive the intervening enemy wave. In the final phase the target square starts invisible: rotate statues until their beams turn green, then lure the werewolf into the revealed trap and repeat damage windows.</li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Original concise walkthrough adapted from the sources below. Research reviewed 2026-09-30. Use their illustrated references for exact object sightlines. Gameplay verification is ongoing.</p><ul><li><a href="https://www.reddit.com/r/CODZombies/wiki/dead-of-the-night/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide ↗</a></li></ul></section></div></template>
