<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><section><h2 id="details-setup">Key Features: shield and prison access</h2><ol><li id="guide-step-setup-1" data-guide-step>Turn on both power switches, build the Spectral Shield and unlock Pack-a-Punch using its spirit blast. Feed the three dog heads to obtain Hell’s Retriever.</li>
<li id="guide-step-setup-2" data-guide-step>Obtain the Blundergat/Magmagat and spoon as needed for the quest route. Open the Warden’s hidden room using the required weapon/Brutus interaction.</li>
<li id="guide-step-setup-3" data-guide-step>Start the main quest sequence, collect the Kronorium and follow the spectral clues.</li></ol></section>
<section><h2 id="details-birds">Bird hunt and Kronorium</h2><ol><li id="guide-step-birds-1" data-guide-step>Use the shield to find and blast the hidden bird through its successive round-gated appearances. Search again after each successful stage.</li>
<li id="guide-step-birds-2" data-guide-step>For the final bird stage, use the Zombie Blood route and code 872 as directed; collect the dropped quest item.</li>
<li id="guide-step-birds-3" data-guide-step>Read the Kronorium and use its clue to activate the next challenge location. Do not assume a fixed challenge order.</li></ol></section>
<section><h2 id="details-morse">Docks Morse challenge</h2><ol><li id="guide-step-morse-1" data-guide-step>View the three buoys through the shield from Gondola, Recreation Yard and Model Industries. Each buoy gives a Morse digit.</li>
<li id="guide-step-morse-2" data-guide-step>Decode and sum the three digits, then enter the sum as decimal Morse at the challenge input. A space in the helper separates digits; it is not another pulse.</li>
<li id="guide-step-morse-3" data-guide-step>Finish the spectral escort/actions for the challenge before returning to the Kronorium.</li></ol><InlineTool tool="bo4-blood-morse" /></section>
<section><h2 id="details-challenges">Power House and remaining challenges</h2><ol><li id="guide-step-challenges-1" data-guide-step>Power House: complete the Simon rounds, identify the three steady generator lights and record their symbols/numbers. Match each number to its monitor and record the replacement symbol.</li>
<li id="guide-step-challenges-2" data-guide-step>Complete the assigned New Industries, Showers and Citadel challenges using their spectral targets and escort/defense requirements. Re-read the Kronorium after each completed branch.</li>
<li id="guide-step-challenges-3" data-guide-step>Keep the shield charged for spirit interactions. A notebook entry records a clue; it does not mean the challenge is finished.</li></ol><InlineTool tool="bo4-blood-powerhouse" /></section>
<section><h2 id="details-finale">Warden finale</h2><ol><li id="guide-step-finale-1" data-guide-step>After all challenge branches, complete the Warden’s room and prison escape sequence. Regroup and resupply before the final arena.</li>
<li id="guide-step-finale-2" data-guide-step>Use shield/spirit interactions to expose the boss sequence, clear supporting enemies and damage the vulnerable target when the arena allows it.</li>
<li id="guide-step-finale-3" data-guide-step>Follow the final character interaction to complete the ending.</li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Original concise walkthrough adapted from the sources below. Research reviewed 2026-09-30. Use their illustrated references for exact object sightlines. Gameplay verification is ongoing.</p><ul><li><a href="https://www.reddit.com/r/CODZombies/wiki/blood-of-the-dead/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide ↗</a></li>
<li><a href="https://www.codzombiesguides.com/main-quests/black-ops-4/blood-of-the-dead/" target="_blank" rel="noopener noreferrer">Supplementary walkthrough (2) ↗</a></li></ul></section></div></template>
