<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><section><h2 id="details-setup">Key Features: access and Chrysalax</h2><ol><li id="guide-step-setup-1" data-guide-step>Follow the teleporter repair objectives through the facility, defeat the Abomination blocking progress and reach the Observation Tower to unlock Pack-a-Punch.</li>
<li id="guide-step-setup-2" data-guide-step>Press the quest button in the Observation Tower. For a free Chrysalax, collect an Energetic Geode by having an Abomination beam a crystal, the defended crystal at Jim’s Donuts, and a Tempered Crystal Heart from a Tormentor killed with a flamethrower.</li>
<li id="guide-step-setup-3" data-guide-step>Place the three items in the Particle Accelerator tub, then supply nearby melee kills and collect Chrysalax. Box and trial acquisition also work.</li></ol></section>
<section><h2 id="details-parts">Neutralizer components</h2><ol><li id="guide-step-parts-1" data-guide-step>At Fuel Processing, coordinate the tank buttons with the players in the match. Survive the lockdown and collect the fuel tank; a failed lockdown can be retried next round.</li>
<li id="guide-step-parts-2" data-guide-step>At Staging Area, Amplifier and Storage Zone 5 Rooftops, shoot each growth’s orbiting orbs. Break the growth with Chrysalax, throw its shard into an Abomination’s mouth and kill it for the catalyzed shard.</li>
<li id="guide-step-parts-3" data-guide-step>Use Dead Wire by the Grand Prix arcade machine, activate its ARC-XD, drive through the TV Store vent and detonate by the shelves. Return as a player to collect the monitoring device.</li>
<li id="guide-step-parts-4" data-guide-step>Lure an Abomination charge into the Board Room housing unit to knock it from the ceiling. Collect it and assemble the neutralizer on Main Street.</li></ol><InlineTool tool="cw-forsaken-neutralizer" /></section>
<section><h2 id="details-escort">Neutralizer escort</h2><ol><li id="guide-step-escort-1" data-guide-step>Resupply before activation. Stay inside the protective field while escorting the neutralizer through the dangerous area.</li>
<li id="guide-step-escort-2" data-guide-step>When fuel is needed, collect catalyzed shards from the surrounding crystals and deposit them. Continue to the Containment Door and interact to enter the boss arena.</li></ol></section>
<section><h2 id="details-boss">The Forsaken</h2><ol><li id="guide-step-boss-1" data-guide-step>Kill enemies beneath Maxis to fill her essence and charge a laser cannon. Break the boss’s exposed armor/shield at the active body part.</li>
<li id="guide-step-boss-2" data-guide-step>Use a charged cannon on the vulnerable body part. Repeat through shoulders, lower torso and head until all damage stages are complete.</li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Original concise walkthrough adapted from the sources below. Research reviewed 2026-09-30. Use their illustrated references for exact object sightlines. Gameplay verification is ongoing.</p><ul><li><a href="https://tracker.gg/cold-war/articles/black-ops-cold-war-zombies-forsaken-pyrrhic-victory-main-quest-guide" target="_blank" rel="noopener noreferrer">COD Tracker walkthrough ↗</a></li>
<li><a href="https://tracker.gg/cold-war/articles/black-ops-cold-war-zombies-forsaken-free-chrysalax-guide" target="_blank" rel="noopener noreferrer">COD Tracker walkthrough (2) ↗</a></li></ul></section></div></template>
