<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><section><h2 id="details-setup">Key Features: reactors and RAI K-84</h2><ol><li id="guide-step-setup-1" data-guide-step>Speak to Ravenov, reach the rooftop teleporter and enter the outpost. Activate and defend all three Aether Reactors to restore power and Pack-a-Punch in the village.</li>
<li id="guide-step-setup-2" data-guide-step>For the free RAI K-84, collect the blueprint and Kuhlklay’s eye, scan it in the Weapons Lab and take the locker key. Search the Barracks lockers and defeat spawned Mimics for the barrel.</li>
<li id="guide-step-setup-3" data-guide-step>Record the three sectors shown by the Weapons Lab computer. Shoot their matching numbers on the village dartboard, then the bullseye, to release the component.</li>
<li id="guide-step-setup-4" data-guide-step>Collect the Mangler power cell, charge it in the Weapons Lab through the required round progression, and assemble the RAI K-84.</li></ol><InlineTool tool="cw-firebase-darts" /></section>
<section><h2 id="details-serum">Serum and memory trap</h2><ol><li id="guide-step-serum-1" data-guide-step>Speak with Peck and Ravenov. Use Ravenov’s badge to open the lockers in Equipment Storage, Engineering and the Colonel’s Office.</li>
<li id="guide-step-serum-2" data-guide-step>Combine their compounds in the Field Hospital mixer, survive the Hellhounds, collect the delivery device and attach it to the OPC air conditioner.</li>
<li id="guide-step-serum-3" data-guide-step>Speak with Peck again, then obtain an Essence Trap at the Data Center Memory Transference Station.</li></ol></section>
<section><h2 id="details-memories">Accepted Mimic memories</h2><ol><li id="guide-step-memories-1" data-guide-step>Find Mimics disguised as loot, weaken one and trap it at low health. Return the trap to the memory station and listen to the result.</li>
<li id="guide-step-memories-2" data-guide-step>Repeat until Sokolov, Brahms and Zhabin have been accepted. Record accepted names, not the number of traps used.</li>
<li id="guide-step-memories-3" data-guide-step>Collect the floppy disk and insert it at Planning Offices. Follow the dialogue to acquire the Aethermeter and take the shovel from Scorched Defense.</li></ol><InlineTool tool="cw-firebase-memories" /></section>
<section><h2 id="details-crystals">Three Aether crystals</h2><ol><li id="guide-step-crystals-1" data-guide-step>Open Lot: dig the container and inspect the copies. Choose the one without black particles; a wrong choice spawns Mimics and requires a later-round retry.</li>
<li id="guide-step-crystals-2" data-guide-step>Jungle Defense: dig the container, survive inside its dome and collect the crystal when the defense ends.</li>
<li id="guide-step-crystals-3" data-guide-step>Barracks: dig the container near Field Hospital. Stop the moving container with the RAI K-84 alternate fire, then approach and collect it.</li>
<li id="guide-step-crystals-4" data-guide-step>Install the three crystals at the reactors and return to the OPC.</li></ol></section>
<section><h2 id="details-boss">Satellite and Orda</h2><ol><li id="guide-step-boss-1" data-guide-step>Use the Planning Offices computer to inspect the satellites. Select the Requiem satellite indicated by a question mark.</li>
<li id="guide-step-boss-2" data-guide-step>Prepare the team before the final OPC interaction, which leads into the boss sequence.</li>
<li id="guide-step-boss-3" data-guide-step>Damage Orda, target its exposed critical area and keep distance from its slam. Replenish ammunition and survive until it falls.</li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Original concise walkthrough adapted from the sources below. Research reviewed 2026-09-30. Use their illustrated references for exact object sightlines. Gameplay verification is ongoing.</p><ul><li><a href="https://tracker.gg/cold-war/articles/black-ops-cold-war-zombies-firebase-z-main-quest-guide" target="_blank" rel="noopener noreferrer">COD Tracker walkthrough ↗</a></li>
<li><a href="https://tracker.gg/cold-war/articles/black-ops-cold-war-zombies-firebase-z-free-rai-k-94" target="_blank" rel="noopener noreferrer">COD Tracker walkthrough (2) ↗</a></li></ul></section></div></template>
