<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><section><h2 id="details-setup">Key Features: power and Pack-a-Punch</h2><ol><li id="guide-step-setup-1" data-guide-step>Follow the objective markers down to the subway power switch. Activate it to start the fuse objective.</li>
<li id="guide-step-setup-2" data-guide-step>Kill the marked Tempests, collect both electrical fuses and return them to the power panel. Turn on power again.</li>
<li id="guide-step-setup-3" data-guide-step>Reach Pack-a-Punch at Checkpoint Charlie. Approach it to begin the Disciple encounter, defeat the enemies and use the machine once the barrier clears.</li></ol></section>
<section><h2 id="details-klaus">Build and upgrade Klaus</h2><ol><li id="guide-step-klaus-1" data-guide-step>Apply Brain Rot to a weapon and turn a zombie inside Hotel Room 305. Let it break the barricaded door, then take the robotic hands from the body.</li>
<li id="guide-step-klaus-2" data-guide-step>Collect the battery dropped by the Krasny Soldat that appears from round 10 onward. Install battery and hands on Klaus in the Safe House and take his remote.</li>
<li id="guide-step-klaus-3" data-guide-step>Command Klaus to break the locker in the Switch Control Room and collect the blacklight. Search the debris piles around the Death Strip for the microwave dish and attach it to the upgrade station in the Garment Factory.</li>
<li id="guide-step-klaus-4" data-guide-step>Let Klaus get kills until the upgrade station is ready, command him into it and defend the upgrade. Further cosmetic upgrades are separate from the upgrade needed for the quest.</li></ol></section>
<section><h2 id="details-safe">Free CRBR-S and secret lab</h2><ol><li id="guide-step-safe-1" data-guide-step>Use the blacklight in the Garment Factory, Service Passage and Grocery Store. Each clue has a printed position (1–3) and a hidden two-digit value. Record the value under its printed position, not the order you found it.</li>
<li id="guide-step-safe-2" data-guide-step>Return to the safe in Hotel Room 305 and enter the three values in printed order. Collect the CRBR-S. A CRBR-S obtained from trials or the box can also be used.</li>
<li id="guide-step-safe-3" data-guide-step>Obtain the Blazer mod dropped by enemies while using the CRBR-S. Command Klaus to break the wall at Sewer Access, then use the Blazer to melt the metal door behind it.</li>
<li id="guide-step-safe-4" data-guide-step>Enter the Secret Lab. Wait for the protective field to clear on the following round, then shoot the canister device with the CRBR-S to release the empty canisters.</li></ol><InlineTool tool="cw-mauer-safe" /></section>
<section><h2 id="details-canisters">Fill the conversion unit</h2><ol><li id="guide-step-canisters-1" data-guide-step>Shoot the essence-trap dispenser in the Secret Lab with the CRBR-S and collect an Endstation Lure. Place an empty canister at an essence harvester around the map.</li>
<li id="guide-step-canisters-2" data-guide-step>Throw the lure beside the harvester and kill the summoned Tempests near it. When charged, carry the canister back to the conversion unit in the lab. Repeat until all three canisters are installed.</li>
<li id="guide-step-canisters-3" data-guide-step>Build Klaus’s hacking headgear from the antenna on the Apartment Rooftop, the electronics in the Radio Store and the boards in the station ticket machines, using the CRBR-S to reveal the components. Install them on Klaus.</li></ol></section>
<section><h2 id="details-train">Stop the train</h2><ol><li id="guide-step-train-1" data-guide-step>Deploy upgraded Klaus. Use the railway switch in the Switch Control Room, then command Klaus onto the track furthest from Mule Kick.</li>
<li id="guide-step-train-2" data-guide-step>When Klaus stops the train, enter it and collect the bomb and Rico’s keycard. If the attempt fails, the railway switch can only be tried again next round.</li>
<li id="guide-step-train-3" data-guide-step>Install the warhead at the conversion unit. Use the keycard at the computer and browse files until the Disruptor Satellite option becomes available.</li></ol></section>
<section><h2 id="details-uranium">Two uranium cycles</h2><ol><li id="guide-step-uranium-1" data-guide-step>Activate the satellite to spawn the HVT Megaton. Defeat its split forms and collect both uranium rocks. The HUD timer is the authoritative time limit.</li>
<li id="guide-step-uranium-2" data-guide-step>Craft a uranium device from each rock at a marked workbench. Place one at the Destroyed Penthouse zipline and the other at the Korber Rooftops end; activate the collision.</li>
<li id="guide-step-uranium-3" data-guide-step>Collect the cleansed rock from East Berlin Streets and place it in the lab warhead. Advance a round and repeat the satellite/uranium sequence for a second rock.</li>
<li id="guide-step-uranium-4" data-guide-step>Finish upgrading, replenish armor and ammunition, and coordinate the team before depositing the second cleansed rock: this starts Valentina.</li></ol></section>
<section><h2 id="details-finale">Valentina and final defense</h2><ol><li id="guide-step-finale-1" data-guide-step>Break Valentina’s shield, then damage her exposed health. Kill the floating zombies she uses to heal. Take cover when the screen signals her wipe attack.</li>
<li id="guide-step-finale-2" data-guide-step>Use the pauses between arena moves to repair and resupply. After defeating her, defend Klaus while he carries the warhead into the portal.</li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Original concise walkthrough adapted from the sources below. Research reviewed 2026-09-30. Use their illustrated references for exact object sightlines. Gameplay verification is ongoing.</p><ul><li><a href="https://tracker.gg/cold-war/articles/black-ops-cold-war-zombies-mauer-der-toten-tin-man-heart-main-quest-guide" target="_blank" rel="noopener noreferrer">COD Tracker walkthrough ↗</a></li>
<li><a href="https://tracker.gg/cold-war/articles/black-ops-cold-war-zombies-mauer-der-toten-free-crbr-s-guide" target="_blank" rel="noopener noreferrer">COD Tracker walkthrough (2) ↗</a></li>
<li><a href="https://tracker.gg/cold-war/articles/black-ops-cold-war-zombies-mauer-der-toten-klaus-upgrade-guide" target="_blank" rel="noopener noreferrer">COD Tracker walkthrough (3) ↗</a></li></ul></section></div></template>
