<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><section><h2 id="details-rifts">Rifts and Ravenov contact</h2><ol><li id="guide-step-rifts-1" data-guide-step>Enter the red rift in the starting quest region. While falling, parachute into each subsequent rift until a beam drops to the ground.</li>
<li id="guide-step-rifts-2" data-guide-step>Collect the beacon listening device at the beam’s landing point. If the starting region is Sanatorium, warp onward to find a rift.</li>
<li id="guide-step-rifts-3" data-guide-step>Complete the region objective and select Respond at the beacon to contact Ravenov and warp to Sanatorium.</li></ol><InlineTool tool="cw-outbreak-regions" /></section>
<section><h2 id="details-rover">Crash site and modified rover</h2><ol><li id="guide-step-rover-1" data-guide-step>Approach the crashed helicopter in Carved Hills, defeat its enemy wave and play the recording inside.</li>
<li id="guide-step-rover-2" data-guide-step>Find the red Aethereal Orb and shoot it along its route until it reaches the neutralizer rover on the bridge.</li>
<li id="guide-step-rover-3" data-guide-step>Find the broken Mystery Box with the Aether Bunny. Interact, survive the defense and collect the bunny, replacing your field upgrade. Install it on the rover.</li></ol></section>
<section><h2 id="details-exfil">Escort and Orda exfil</h2><ol><li id="guide-step-exfil-1" data-guide-step>Activate the modified rover and remain in its safe field while escorting it to Monument Walk.</li>
<li id="guide-step-exfil-2" data-guide-step>Reach the monument rooftop and play the recording to begin the final narrative. Prepare for the six-minute exfil timer.</li>
<li id="guide-step-exfil-3" data-guide-step>Travel to East Gardens and eliminate the hostiles, including Orda, to finish the quest.</li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Original concise walkthrough adapted from the sources below. Research reviewed 2026-09-30. Use their illustrated references for exact object sightlines. Gameplay verification is ongoing.</p><ul><li><a href="https://tracker.gg/cold-war/articles/black-ops-cold-war-zombies-outbreak-main-quest-operation-excision-entrapment-guide" target="_blank" rel="noopener noreferrer">COD Tracker walkthrough ↗</a></li></ul></section></div></template>
