<!-- AUTO-GENERATED by scripts/convert-guides.mjs from public/guides/totenreich.html -->
<template>





<span id="wiki_totenreich_.7C_complete_map_breakdown" class="legacy-anchor" aria-hidden="true"></span>


<img class="guide-cover" src="/images/totenreich-thumb.jpg" alt="Totenreich" />
<p style="text-align: center;"><em><strong>In the frozen birthplace of nuclear fire, a Group 935 research base hides sinister secrets. Awaken the steel colossus, ignite the flame of vengeance, and free the giant Shadowsmith from the Warden's icy grip!</strong></em></p>
<hr>
<h1 id="wiki_key_features">Key Features</h1>
<p>This is a walkthrough of the key features of the map, such as Pack-a-Punch, Wonder Weapons, etc.</p>
<div class="glass-card glass-gold"><h2 id="wiki_jotunn_star"><label class="g-toggle"><input type="checkbox" class="g-cb" checked><span class="g-title">Jotunn Star<span class="g-tag">⭐ Wonder Weapon</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<ol>
<li id="guide-step-map-get-3-items">Get 3 items:

<ol>
<li id="guide-step-map-chilly-chunks-back-of-a-truck-next-to-deadshot-daiquiri-in-storm-bridg"><strong>Chilly Chunks</strong> - Back of a truck next to Deadshot Daiquiri in Storm Bridge. <ShowOnMap target="storm-bridge" /></li>
<li id="guide-step-map-lantern-place-the-chilly-chunks-on-the-table-in-the-center-of-skallen-"><strong>Lantern</strong> - Place the Chilly Chunks on the table in the center of Skallen Market. <strong>Starting with the 2nd Special Round</strong>, a named Zursa will spawn and will drop the Lantern after being killed. <ShowOnMap target="skallen-market" /></li>
<li id="guide-step-map-chain-links-interact-with-the-button-in-titan-crane-to-lower-a-wooden-"><strong>Chain Links</strong> - Interact with the button in Titan Crane to lower a wooden slab in front of the ship. Wall jump towards the bow of the ship and interact to get the chains.
 <ShowOnMap target="titan-crane" />
<ul>
<li><em>Note: the slab will only stay down for 30 seconds, but the button can be interacted as many times as needed.</em></li>
</ul>
</li>
</ol>
</li>
<li id="guide-step-map-reach-the-burial-grounds-and-interact-with-the-door-to-put-the-chain-l">Reach the Burial Grounds and interact with the door to put the chain links in, then hold interact to repair the door.  <ShowOnMap target="burial-grounds" /></li>
<li id="guide-step-map-place-the-lantern-on-the-shrine-in-burial-grounds-the-lantern-will-emi">Place the Lantern on the shrine in Burial Grounds. The lantern will emit lights on the wall, revealing constellations that rotate.</li>
<li id="guide-step-map-interact-with-the-constellation-symbols-on-the-wall-based-on-the-ones-">Interact with the constellation symbols on the wall, based on the ones on the shrine at Burial Grounds

<ul>
<li>The order is Left, Right, Back, Front when looking at the shrine from the stairs.</li>
</ul>
</li>
<li>If done correctly, the ghost of Astrid will appear above the shrine.</li>
<li id="guide-step-map-follow-astrid-she-will-move-toward-the-market-then-stop-kill-frost-zom">Follow Astrid. She will move toward the market, then stop. Kill Frost zombies that spawn to charge her energy bar until it is filled. <ShowOnMap target="skallen-market" /></li>
<li id="guide-step-map-once-astrid-is-near-the-lighthouse-repeat-the-energy-charging-process-">Once Astrid is near the lighthouse, repeat the energy charging process once more. Once done, floating platforms will appear. Climb the platforms and reach the lighthouse. <ShowOnMap target="lighthouse" /></li>
<li id="guide-step-map-continue-to-climb-the-lighthouse-with-the-stairs-and-the-outside-platf">Continue to climb the lighthouse with the stairs and the outside platforms.</li>
<li id="guide-step-map-interact-with-the-ladder-on-top-of-the-lighthouse-to-enter-the-top-cha">Interact with the ladder on top of the lighthouse to enter the top chamber, where the Jotunn Star will be available for pickup.</li>
</ol>
<hr>
</div><h1 id="wiki_main_quest">Main Quest</h1>


<div class="cheat-grid">
  <div class="cheat-block phase1">
    <h2>① Setup</h2>
    <ol>
      <li>Obtain the <strong>Jotunn Star</strong> (wonder weapon).</li>
    </ol>
  </div>
  <div class="cheat-block phase1">
    <h2>② Wundersignal</h2>
    <ol>
      <li><strong>Crowbar</strong> in Lighthouse; find the note (Dry Dock / Tyr's Foot) → read the crate code: <strong>III-6, V-7, X-9, or IV-3</strong>.</li>
      <li>Open the matching crate → <strong>Flak Gun Round</strong>. (Wrong crate = 30s penalty.)</li>
      <li>Load the flak gun near the Lighthouse, shoot the <strong>Riese head</strong> in spawn.</li>
      <li>Take <strong>Transmitter</strong> from Riese head → place in Tyr's head (2nd floor).</li>
      <li>Count the 2 sets of blinking lights → <strong>2×2-digit numbers</strong>.</li>
      <li>Core Foundry Ascender (Molotov) → console: calibrate <strong>Amplitude + Frequency</strong> → fire both sets → <strong>Wunderbarrage Controller</strong>.</li>
    </ol>
  </div>
  <div class="cheat-block phase2">
    <h2>③ Atomkraft Core — 3 Uraniums</h2>
    <ol>
      <li><strong>U-1:</strong> Fishing Rod → glowing green fish → Irradiated Ravager next round → kill for Uranium.</li>
      <li><strong>U-2:</strong> ARC-XD melee vent → secret room → head jars A–E + radioactive symbols → Necrospike lockpick → Uranium.</li>
      <li><strong>U-3:</strong> Glocke Drop → shoot floating zombies, light 3 green lights → Uranium.</li>
      <li>Clear debris (Wunderbarrage) → Machine Workshop → claw machine: <strong>6&amp;3 / 7&amp;2 / 7&amp;1&amp;1</strong> → <strong>Atomkraft Core</strong>.</li>
      <li>Defend generator (Quick Revive pallets) → Charged Core to Storm Bridge barrel → <strong>Dravakar Shard</strong>.</li>
    </ol>
  </div>
  <div class="cheat-block phase3">
    <h2>④ Vegvisir</h2>
    <ol>
      <li>Place shard on Blodheim Hall bonfire → light with Jotunn Star ranged attack.</li>
      <li>Disciple Injection → throw zombies into fire → lockdown → kill <strong>Necropincer HVT</strong> → <strong>Sunstone</strong>.</li>
      <li>Sunstone in Eidskallen Stave Church center → giant arrow circle → shoot rune wood piles in order (arrow count = order).</li>
      <li>Return to Tyr's Head console → <strong>boss fight</strong>.</li>
    </ol>
  </div>
  <div class="cheat-block phase4">
    <h2>⑤ Dravakar Boss</h2>
    <ol>
      <li>Shoot red weak spots while Tyr wrestles; ice attacks freeze areas → use 3 Flammenfalle traps.</li>
      <li>Tyr disabled → <strong>Gjallarfrost heads</strong>: grenade in mouth or Jotunn Star ranged to stun → destroy; dodge ice shard runes, shoot random weak spots.</li>
      <li>More Gjallarfrost heads; middle area locked, no cover — keep DPS on weak spots until health bar empties.</li>
    </ol>
    <p class="cheat-note">Astra Malorum done? <strong>Caltheris's Blessing</strong> revives a downed player when all players are down with no revives.</p>
  </div>
</div>

<ol>
<li>Obtain the Jotunn Star</li>
</ol>
<div class="glass-card glass-amber"><h2 class="" id="wiki_wundersignal"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Wundersignal<span class="g-tag">📡 Signal</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<ol>
<li id="guide-step-map-get-the-crowbar-from-a-shelf-inside-the-lighthouse">Get the Crowbar from a shelf inside the Lighthouse. <ShowOnMap target="lighthouse" /></li>
<li id="guide-step-map-find-a-note-on-the-ground-in-either-dry-dock-in-the-room-with-the-inte">Find a note on the ground, in either Dry Dock in the room with the interactable button, or at Tyr's Foot near a corpse. The note will display a message that will determine which crate to open:
 <ShowOnMap target="areas-dry-dock--tyrs-foot" />
<ul>
<li><em>"I replaced the PzGR shipment with parts from the lab [...]</em>" means it's the crate marked <strong>III-6</strong></li>
<li><em>"I couldn’t tamper with the PzGR shipment [...]" </em>means it's the crate marked<em> </em><strong>V-7</strong></li>
<li><em>"The PzGR shells are gone and now carry robot parts instead [...]"</em> means it's the crate marked <strong>X-9</strong></li>
<li><em>"The switch is done, PzGR shells out, chemical bomb in [...]" </em>means it's the crate marked&nbsp;<strong>IV-3</strong></li>
</ul>
</li>
<li data-guide-step id="guide-step-map-find-the-corresponding-crate-in-one-of-the-possible-spawn-location-if-">Find the corresponding crate in one of the possible spawn location. If done correctly, the Flak Gun Round will drop from the crate. However, opening&nbsp;the wrong crate will trigger an effect for about 30 seconds, either repeated electrical shots, suffered from gas exposure, or experiencing hallucination similarly to Psych Grenades.

 <ShowOnMap target="locations-map-find-the-corresponding-crate-in-one-of-the-possible-spawn-loc" label="Show wundersignal locations on map" />
<ul>
<li id="guide-step-map-war-factory-in-a-corner-near-the-admin-room"><strong>War Factory</strong>, in a corner near the Admin room.</li>
<li id="guide-step-map-dry-dock-behind-the-boat-opposite-of-phd-flopper"><strong>Dry Dock</strong>, behind the boat opposite of PhD Flopper.</li>
<li id="guide-step-map-core-foundry-next-to-the-vs-recon-wall-buy"><strong>Core Foundry</strong>, next to the VS Recon wall buy.</li>
<li id="guide-step-map-fjord-road-next-to-the-flammefalle-trap"><strong>Fjord Road</strong>, next to the Flammefalle Trap.</li>
</ul>
</li>
<li id="guide-step-map-reach-the-flak-gun-near-the-lighthouse-facing-spawn-area-and-place-the">Reach the flak gun near the Lighthouse facing spawn area, and place the Flak Gun Round inside then hit it with the Jotunn Star. If done correctly, the gun should shoot at the Riese robot head in spawn. <ShowOnMap target="areas-lighthouse--eidskallen-landing" /></li>
<li id="guide-step-map-go-to-the-riese-robot-head-in-spawn-and-hold-interact-with-it-to-get-t">Go to the Riese robot head in spawn and hold interact with it to get the Transmitter. Place the Transmitter inside Tyr's head on the second floor. <ShowOnMap target="areas-eidskallen-landing--tyrs-head" /></li>
<li id="guide-step-map-check-the-two-blinking-lights-inside-tyr-s-head-the-two-lights-will-bl">Check the two blinking lights inside Tyr's head. The two lights will blink at the same time, then reset, and blink again. Count the number of blinks each time for each light. This will be 2 sets of 2-digit numbers.</li>
<li id="guide-step-map-travel-to-core-foundry-and-unlock-the-ascender-with-a-molotov-use-the-">Travel to Core Foundry and unlock the Ascender with a Molotov. Use the Ascender and enter the console to calibrate the Amplitude (right) and Frequency (left) using the numbers from the blinking lights. Enter the first set of numbers which will launch a barrage strike somewhere on the map, then enter the second set of numbers. <ShowOnMap target="core-foundry" /></li>
<li id="guide-step-map-if-done-correctly-a-free-wunderbarrage-controller-will-spawn-in-the-ro">If done correctly, a free Wunderbarrage Controller will spawn in the room next to the radio tower. The controller will also become available at crafting tables.</li><li><InlineTool tool="totenreich-wunderbarrage" /> — count the light blinks, keep the pairs on screen.</li>
</ol></div>
<div class="glass-card glass-orange"><h2 class="" id="wiki_atomkraft_core"><label class="g-toggle"><input type="checkbox" class="g-cb" checked><span class="g-title">Atomkraft Core<span class="g-tag">☢️ Core</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<ol>
<li>Obtain three Uraniums, which can be done in any order:
<ul>
<li>Uranium 1
<ol>
<li id="guide-step-map-find-a-fishing-rod-dry-dock-storm-bridge-fishery-island-beacon-island">Find a Fishing Rod (Dry Dock, Storm Bridge, Fishery Island, Beacon Island) <ShowOnMap target="areas-dry-dock--storm-bridge--fishery-island--beacon-island" /></li>
<li id="guide-step-map-find-a-glowing-green-fish-jumping-in-the-water-at-one-of-the-fishing-l">Find a glowing green fish jumping in the water at one of the fishing location and use the Fishing Rod. Catching the fish will spawn an Irradiated Ravager. <ShowOnMap target="fishing" /></li>
<li>Wait for the next round, and it will appear somewhere on the map, alongside a horde of regular Ravagers. Killing the Irradiated Ravager will drop the Uranium.</li>
</ol>
</li>
<li>Uranium 2
<ol>
<li id="guide-step-map-get-an-arc-xd-and-melee-the-vent-near-stairs-and-zipline-in-core-found">Get an ARC-XD and melee the vent near stairs and Zipline in Core Foundry. With the ARC-XD jump on the boat on the other side and enter the secret room to destroy the barrels and open the Group 935 Genetic Lab.
 <ShowOnMap target="areas-core-foundry--genetic-lab" />
<ul>
<li><em>Note: a free ARC-XD can be picked up in the Eidskallen Square, and it can also be acquired randomly from fishing.</em></li>
</ul>
</li>
<li id="guide-step-map-there-will-be-5-head-jars-marked-a-to-e-around-the-room-look-at-the-co">There will be 5 head jars marked A to E around the room. Look at the corridor next to the locked cell door and note the radioactive symbols beneath the numbers (1 to 5). The numbers match the letter on the jars (A=1 ... E=5) and the radioactive symbols show which jar is needed. Pick up the corresponding jars and place them in the machine next to the cell to get the glowing purple jar.</li>
<li id="guide-step-map-interact-with-the-crab-arm-on-the-table-to-pick-up-the-necrospike-use-">Interact with the crab arm on the table to pick up the Necrospike. Use the Necrospike on the cell door to trigger a lockpicking mini-game.</li>
<li id="guide-step-map-if-done-correctly-the-cell-door-will-open-and-the-uranium-can-be-picke">If done correctly, the cell door will open and the Uranium can be picked up. <em>Note: a radio can also be picked up on the ground beneath the bench for a Relic.</em></li>
</ol>
</li>
<li>Uranium 3 - <em>Note: This Uranium can be acquired without the need to build the Jotunn Star or start the main quest.</em>
<ol>
<li>Obtain the Glocke Drop and activate it.
<ul>
<li><em>Note: a free drop is available as part of the beginning steps of the main quest, and it can also be acquired randomly from fishing.</em></li>
</ul>
</li>
<li>While active, shoot all the floating zombies to turn on the green light. Keep doing it until all 3 green lights are lit. If done correctly, the Glocke will drop the Uranium.</li>
</ol>
</li>
</ul>
</li>
<li id="guide-step-map-use-the-wunderbarrage-controller-to-clear-the-debris-on-the-stairs-out">Use the Wunderbarrage Controller to clear the debris on the stairs outside of 02 Building in Dry Dock. Climb the stairs and enter the Machine Workshop. The door to the other side will then automatically open. <ShowOnMap target="areas-dry-dock--machine-workshop" /></li>
<li id="guide-step-map-place-all-3-uraniums-inside-the-claw-machine-and-interact-with-it">Place all 3 Uraniums inside the claw machine and interact with it.</li>
<li id="guide-step-map-record-the-six-existing-tubes-and-choose-three-uranium-placements-that">Record the six existing tubes and choose three Uranium placements that keep the gauge in its target range. Groups connected to Uranium activate; the helper offers layouts from the documented community model. <InlineTool tool="totenreich-uranium" />.</li>
<li id="guide-step-map-if-done-correctly-the-atomkraft-core-will-drop">If done correctly, the Atomkraft Core will drop.

<ul>
<li><em>Note that you cannot sprint while holding the Atomkraft Core and using a zipline or entering Tyr will drop it on the ground.</em></li>
</ul>
</li>
<li id="guide-step-map-place-the-atomkraft-core-on-pallets-next-to-quick-revive-then-turn-on-">Place the Atomkraft Core on pallets next to Quick Revive then turn on the generator in the shed behind the perk. You will need to defend the Atomkraft Core. During the defense, the generator will occasionally require rebooting to progress. <ShowOnMap target="eidskallen-landing" /></li>
<li id="guide-step-map-once-done-bring-the-charged-atomkraft-core-to-storm-bridge-and-place-i">Once done, bring the Charged Atomkraft Core to Storm Bridge and place it on a barrel. If done correctly, a cutscene will play and the Dravakar Shard will drop next to Tyr's Foot. <ShowOnMap target="areas-storm-bridge--tyrs-foot" /></li>
</ol></div>
<div class="glass-card glass-green"><h2 class="" id="wiki_vegvisir"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Vegvisir<span class="g-tag">🧭 Vegvisir</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<ol>
<li id="guide-step-map-bring-the-shard-inside-the-blodheim-hall-and-place-it-on-the-bonfire-l">Bring the shard inside the Blodheim Hall and place it on the bonfire. Lit the bonfire with the ranged attack of the Jotunn Star. <ShowOnMap target="blodheim-hall" /></li>
<li id="guide-step-map-get-a-disciple-injection-and-throw-zombies-inside-the-bonfire-note-a-f">Get a Disciple Injection and throw zombies inside the bonfire. <em>Note: a free Disciple Injection can be found in the Eidskallen Stave Church.</em></li>
<li id="guide-step-map-if-done-correctly-this-should-trigger-a-lockdown-and-spawn-an-necropin">If done correctly, this should trigger a lockdown and spawn an Necropincer HVT.</li>
<li id="guide-step-map-after-killing-the-hvt-the-sunstone-can-be-picked-up">After killing the HVT, the Sunstone can be picked up.</li>
<li id="guide-step-map-place-the-sunstone-in-the-center-of-eidskallen-stave-church-and-use-th">Place the Sunstone in the center of Eidskallen Stave Church and use the Jotunn Star's range attack on it. A giant circle will spawn above the church with arrows pointing at different runes. <ShowOnMap target="stave-church" /></li>
<li>Runes will spawn around the map, shoot the wooden pile below each rune with the range attack of the Jotunn Star in the order shown in the giant circle, based on the number of arrow points per rune.</li>
<li id="guide-step-map-once-done-return-to-tyr-s-head-and-interact-with-the-console-to-start-">Once done, return to Tyr's Head and interact with the console to start the boss fight <ShowOnMap target="tyrs-head" /></li>
</ol></div>
<div class="glass-card glass-red glass-boss"><h2 class="" id="wiki_dravakar_boss_fight"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Dravakar Boss Fight<span class="g-tag">🐉 BOSS</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<p><em>Note: Throughout the duration of this fight, if players have completed the Astra Malorum main quest, a power-up called Caltheris's Blessing will drop when all players go down and have no revives left. It will revive the downed player who picks it up.</em></p>
<ol>
<li id="guide-step-map-at-the-start-of-the-fight-dravakar-will-wrestle-with-tyr-in-the-backgr">At the start of the fight, Dravakar will wrestle with Tyr in the background. At certain points, red weak spots will glow on Dravakar; deal damage to these weak spots until they break, which will allow Tyr to gain the upper hand. Otherwise, Dravakar will focus on the players and release an ice attack to one of the three areas in the arena, causing it to freeze temporarily. Three Flammenfalle traps are placed around the arena, which can be used to counter the effects of the ice attacks. <ShowOnMap target="boss-arena" /></li>
<li id="guide-step-map-after-dealing-enough-damage-to-dravakar-he-will-disable-tyr-for-the-re">After dealing enough damage to Dravakar, he will disable Tyr for the rest of the fight. A Gjallarfrost head will spawn in the middle area, which will attack players when spotted. Stun the Gjallarfrost by throwing a grenade in its mouth, or using the ranged attack of the Jotunn Star, then deal damage with any weapon until it is destroyed. Dravakar will then appear and summon ice shards in rune patterns and shoot them at the players; hide behind covers to avoid the shards, or study the rune patterns to dodge them. During this phase, Dravakar's body will have random red glowing weak spots that can be shot at.</li>
<li id="guide-step-map-in-later-phases-dravakar-will-summon-additional-gjallarfrost-heads-on-">In later phases, Dravakar will summon additional Gjallarfrost heads on other sides of the arena. Eventually he will also block off access to the other areas, forcing the player to stay in the middle area with no cover from the ice shard attacks. Continue dealing damage to Dravakar's weak spots until his health bar is depleted.</li>
</ol></div>

<hr>
<h1 id="wiki_side_quests_and_easter_eggs">Side Quests and Easter Eggs</h1>
<div class="glass-card glass-violet"><h2 id="wiki_.22no_one_there.22_secret_song"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">"No One There" Secret Song<span class="g-tag">🎵 Song</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<p id="guide-step-locations-dry-dock" data-guide-step>Find three Mr Peeks headphones around the map: <ShowOnMap target="locations-dry-dock" label="Show &quot;no one there&quot; secret song locations on map" /></p>
<ul>
<li id="guide-step-map-on-boxes-near-phd-flopper-at-dry-dock">On boxes near PhD Flopper at Dry Dock</li>
<li id="guide-step-map-near-double-tap-root-beer-at-core-foundry">Near Double Tap Root Beer at Core Foundry</li>
<li id="guide-step-map-bottom-of-a-shelf-next-to-a-plate-at-loven-s-antiquities">Bottom of a shelf, next to a plate, at Loven's Antiquities</li>
</ul>
<p><a href="https://www.youtube.com/watch?v=g_AlO2pmAjE" rel="nofollow noopener" target="_blank">"No One There" by Kevin Sherwood and Vicky Psarakis</a></p></div>
<div class="glass-card glass-red"><h2 id="wiki_.22echoes_of_the_damned.22_richtofen_quest"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">"Echoes of the Damned" Richtofen Quest<span class="g-tag">⚔️ Quest</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<ol>
<li>Equip Melee Macchiato</li>
<li id="guide-step-map-starting-on-round-15-and-every-subsequent-rounds-ending-on-5-or-0-and-">Starting on Round 15 (and every subsequent rounds ending on 5 or 0) and hit the barrel near the doorway in the courtyard of Core Foundry. <ShowOnMap target="core-foundry" /></li>
<li>Dig inside the barrel and retrieve the Iron Cross to trigger the quest.</li>
</ol></div>
<div class="glass-card glass-amber"><h2 class="" id="wiki_fishing"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Fishing<img alt="" class="wiki-img-right wiki-img-with-wrap wiki-img-in-table" data-height="2175" data-media-id="4yzta00n5yzg1" data-width="2560" height="217" width="256" src="https://preview.redd.it/4yzta00n5yzg1.jpeg?width=320&amp;height=271&amp;format=pjpg&amp;auto=webp&amp;s=99001d9572499fd8c8e4601aa55b71db37a8a7f1"><span class="g-tag">🎣 Fishing</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<p>There are several fishing rods, called Olaf's Cod Cranker, that can be found around the maps. Those fishing rods can be used at specific spot to catch loot such as Essence, Salvage, Equipment, Killstreaks, etc. Sometimes one or more boots will appear, turning into zombies.</p>
<ul>
<li>The Olaf's Cod Cranker fishing rods (Green) can be found in:
<ul>
<li id="guide-step-map-blodheim-hall-dry-dock-fishery-island-storm-bridge-beacon-island">Blodheim Hall, Dry Dock, Fishery Island, Storm Bridge, Beacon Island <ShowOnMap target="areas-blodheim-hall--dry-dock--fishery-island--storm-bridge--beacon-island" /></li>
</ul>
</li>
<li>There are 11 fishing spots (Red) around the map:
<ul>
<li id="guide-step-map-eidskallen-landing-x2-eidskallen-square-x2-dry-dock-beacon-island-x2-f">Eidskallen Landing (x2), Eidskallen Square (x2), Dry Dock, Beacon Island (x2), Fishery Island (x2), Tyr's Foot, Tyr's Shoulder. <ShowOnMap target="areas-eidskallen-landing--eidskallen-square--dry-dock--beacon-island--fishery-island--tyrs-foot--tyrs-shoulder" /></li>
</ul>
</li>
</ul></div>
<div class="glass-card glass-green"><h2 id="wiki_tyr.27s_power.2Dups"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Tyr's Power-Ups<span class="g-tag">⚡ Power-Ups</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<p id="guide-step-map-inside-tyr-s-head-several-lightbubs-can-be-found-above-the-robot-s-mon">Inside Tyr's Head, several lightbubs can be found above the robot's monitor. The lightbubs will display coordinates (such as F 8 or E 2, etc) and the number 75. That number indicates how many zombies need to be killed while being within the coordinates. <ShowOnMap target="tyrs-head" /></p>
<p id="guide-step-map-if-done-correctly-tyr-s-head-will-flash-green-when-seen-from-the-outsi">If done correctly, Tyr's head will flash green when seen from the outside, and a random Power-Up will spawn inside the head. This can be done once per round.</p></div>
<div class="glass-card glass-gold"><h2 class="" id="wiki_helmets"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Helmets<span class="g-tag">🪖 Helmets</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<p><strong>Golden Tide Helm (Blue; Fishing)</strong></p>
<ol>
<li id="guide-step-map-get-the-olaf-s-cod-cranker-fishing-rod">Get the Olaf's Cod Cranker fishing rod. <ShowOnMap target="fishing" /></li>
<li id="guide-step-map-use-it-at-the-fishing-locations-until-a-special-zombie-called-olaf-cra">Use it at the fishing locations until a special zombie called Olaf, Cranker of Cod spawn wearing a helmet.</li>
<li>Kill the zombie to drop the helmet and pick it up.</li>
</ol>
<p>While wearing the helmet, it should take less time before catching something when fishing, and there will be more chances for better loot like increased Salvage or even Power-Ups. The Golden Tide Helm can be picked up again at Blodheim Hall at no cost.</p>
<p class=""><strong>Kneehigh Helm (Orange; Gnome)</strong></p>
<ol>
<li>Obtain Shadow Rift on your weapon.</li>
<li data-guide-step id="guide-step-map-shoot-four-gnome-statues-around-the-map-note-shooting-at-the-statues-s">Shoot four Gnome statues around the map. <strong>Note: shooting at the statues should show a hitmarker and/or a shield icon.</strong>

 <ShowOnMap target="locations-map-shoot-four-gnome-statues-around-the-map-note-shooting-at-the-" label="Show helmets locations on map" />
<ul>
<li id="guide-step-map-between-two-wooden-sheets-next-to-the-catwalk-of-machine-workshop">Between two wooden sheets next to the catwalk of Machine Workshop.</li>
<li id="guide-step-map-next-to-a-search-light-on-top-of-a-concrete-building-far-outside-of-ty">Next to a search light on top of a concrete building far outside of Tyr's Foot.</li>
<li id="guide-step-map-below-the-painting-on-the-altar-of-eidskallen-stave-church">Below the painting on the altar of Eidskallen Stave Church.</li>
<li id="guide-step-map-on-the-catwalk-at-the-top-of-the-lighthouse-when-looking-at-it-from-th">On the catwalk at the top of the lighthouse when looking at it from the Flak gun facing away from the lighthouse.&nbsp;</li>
</ul>
</li>
<li id="guide-step-map-travel-to-loven-s-antiquities-and-pick-up-the-kneehigh-helm-from-the-c">Travel to Loven's Antiquities and pick up the Kneehigh Helm from the counter. <ShowOnMap target="lovens-antiquities" /></li>
</ol>
<p id="guide-step-map-whenever-you-will-crouch-while-wearing-the-kneehigh-helm-you-will-be-t">Whenever you will crouch while wearing the Kneehigh Helm, you will be turned into a Gnome statue. The Kneehigh Helm can be bought up again at Bloodheim Hall for 6000 Essence. <ShowOnMap target="blodheim-hall" /></p>
<div>
<div><strong>Cointoss Helm (Yellow; Power-Up)</strong>
</div>
<ol>
<li>Complete the Tyr's Power-Ups about 15 times (to be confirmed).</li>
<li id="guide-step-map-if-done-correctly-the-cointoss-helm-should-be-available-within-tyr-s-h">If done correctly, the Cointoss Helm should be available within Tyr's Head. <ShowOnMap target="tyrs-head" /></li>
</ol>
<p>The helmet seemingly increases the frequency of Power-Ups spawn. The Cointoss Helm can be picked up again at Bloodheim Hall at no cost.</p>
<p class=""><strong>Icebane Helm (White; Freeze immunity)</strong></p>
<ol>
<li>Get kills with the Flammenfalle trap:
<ul>
<li>Get 250 kills with the trap itself.</li>
<li>Kill 50 Frost Zombies while inside the trap area of effect with a bullet weapon.</li>
</ul>
</li>
<li>If done correctly, the Icebane Helm should drop on the ground.</li>
</ol>
<p>The helmet will prevent getting frozen during the Special Rounds. When sliding into zombies while wearing the helmet, any zombies hit will be frozen. The Icebane Helm can be picked up again at Bloodheim Hall at no cost.</p>
</div></div>

<div class="glass-card glass-orange"><h2 class="" id="wiki_fishy_fish_bot_trap"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Fishy Fish Bot Trap<span class="g-tag">🤖 Trap</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<ol>
<li id="guide-step-map-get-the-fish-from-the-bucket-located-on-a-shelf-inside-the-shed-next-t">Get the fish from the bucket located on a shelf inside the shed next to the Arsenal at Beacon Island. <ShowOnMap target="beacon-island" /></li>
<li>Get a Shock Charge and wait for a T.E.D.D. Task to spawn.</li>
<li>Place the fish on the T.E.D.D. Task machine and throw the Shock Charge at it then complete the T.E.D.D. Task to the maximum reward.</li>
<li>If done correctly, the fish will drop along aside a piece of the machine.</li>
<li id="guide-step-map-bring-both-items-to-the-mount-on-the-wall-across-the-arsenal-in-eidska">Bring both items to the mount on the wall across the Arsenal in Eidskallen Square and hold to build the trap. <ShowOnMap target="eidskallen-square" /></li>
</ol>
<p>The trap costs 2000 Essence and when activated T.E.D.D. will attract the zombies before turning a handful of them into brain-rotted zombies.</p></div>

<div class="glass-card glass-green"><h2 class="" id="wiki_power.2Dup_statues"><label class="g-toggle"><input type="checkbox" class="g-cb" checked><span class="g-title">Power-Up Statues<span class="g-tag">⚡ Statues</span></span><span class="g-chev" aria-hidden="true"></span></label></h2>
<p>There are 7 Power-Up statues around Totenreich giving out the corresponding Power-Ups when shooting them, with two additional statues appearing after the first 7 are activated.</p>
<ul>
<li id="guide-step-map-bonus-point-outside-beacon-island-between-two-wooden-walls"><strong>Bonus Point</strong>: Outside Beacon Island, between two wooden walls. <ShowOnMap target="beacon-island" /></li>
<li id="guide-step-map-insta-kill-on-a-tombstone-outside-burial-grounds"><strong>Insta-Kill</strong>: On a tombstone outside Burial Grounds. <ShowOnMap target="burial-grounds" /></li>
<li><strong>Double Points</strong>: TBD.</li>
<li id="guide-step-map-nuke-behind-the-riese-robot-head-in-war-factory"><strong>Nuke</strong>: Behind the Riese robot head in War Factory. <ShowOnMap target="war-factory" /></li>
<li id="guide-step-map-full-power-boat-window-inside-dry-dock"><strong>Full Power</strong>: Boat window inside Dry Dock. <ShowOnMap target="dry-dock" /></li>
<li><strong>Max Armor</strong>: TBD.</li>
<li><strong>Max Ammo</strong>: TBD.</li>
<li><strong>Fire Sale</strong>: TBD. <strong>Only available after all the others have been activated.</strong></li>
<li><strong>Random Perk</strong>: TBD. <strong>Only available after all the others have been activated.</strong></li>
</ul></div>

<h1 class="" id="wiki_relics">Relics</h1>
<p>There are 6 Relics that can be unlocked from playing Totenreich, those Relics are then used as gameplay modifiers for Cursed mode.</p>
<p>The Relics are divided into three groups: <strong>Grim</strong>, <strong>Sinister</strong>, and <strong>Wicked</strong>. Each group fill the Cursed Tier bar differently with the Grim Relics filling up a third of the bar, the Sinister Relics filling up two thirds, and the Wicked Relics filling up the entire bar. As such you will need to apply different Relics to reach the desired Tier level.</p>
<ul class="relic-tiers">
  <li><strong>Tier I</strong>: Any 3 <span class="relic-chip grim">Grim</span> — Unlocks Golden Armor (45,000 Essence)</li>
  <li><strong>Tier II</strong>: 2 <span class="relic-chip sinister">Sinister</span> + 2 <span class="relic-chip grim">Grim</span> (example loadout) — Unlocks Ultra Rarity (8,000 Salvage or 17,500 Salvage from default rarity)</li>
  <li><strong>Tier III</strong>: 3 <span class="relic-chip grim">Grim</span> + 2 <span class="relic-chip sinister">Sinister</span> + 1 <span class="relic-chip wicked">Wicked</span> (example) — Unlocks Pack-a-Punch IV (100,000 Essence)</li>
</ul>
<p class="relic-note">Make sure to scroll sideways to see the steps. Higher tiers just need the total difficulty value to match the target fill; swap relics as you discover them.</p>
<div class="relic-grid">
  <div class="relic-section">
    <h2 class="relic-heading grim">Grim Relics</h2>
    <div class="relic-cards">
      <div class="relic-card grim">
        <div class="relic-title">POWER SWITCH <span class="mini-tag">Tactical and lethal equipment randomizes each round</span></div>
        <ol class="steps">
          <li>Start a game in Cursed Mode</li>
          <li id="guide-step-map-find-4-wooden-structures-outside-the-map-and-count-the-number-of-deer-">Find 4 wooden structures outside the map and count the number of deer heads for each of them. A scoped weapon makes it easier to spot the structures.  Outside of Eidskallen Landing, when looking at the opening opposite of the Rampage Inducer. <ShowOnMap target="eidskallen-landing" /></li>
          <li id="guide-step-map-outside-of-burial-grounds-right-of-a-mystery-box-spawn-location">Outside of Burial Grounds, right of a Mystery Box spawn location. <ShowOnMap target="burial-grounds" /></li>
          <li id="guide-step-map-outside-of-core-foundry-on-the-left-most-mountain-top-when-looking-fro">Outside of Core Foundry, on the left-most mountain top when looking from the left side of the piled up crates. <ShowOnMap target="core-foundry" /></li>
          <li id="guide-step-map-outside-of-tyr-s-foot-left-of-the-road">Outside of Tyr's Foot, left of the road. <ShowOnMap target="tyrs-foot" /></li>
          <li id="guide-step-map-get-a-combat-axe-and-throw-it-at-a-specific-bear-pelt-hanging-on-the-w">Get a Combat Axe and throw it at a specific bear pelt hanging on the walls of Blodheim Hall in an order based on the number of deer heads (from 1 to 4)  Eidskallen Landing => Pelt surrounded by 3 round shields with another shield on the ground. <ShowOnMap target="blodheim-hall" /></li>
          <li id="guide-step-map-burial-grounds-pelt-with-only-1-shield-on-its-left">Burial Grounds => Pelt with only 1 shield on its left.</li>
          <li id="guide-step-map-core-foundry-pelt-surrounded-by-4-round-shields">Core Foundry => Pelt surrounded by 4 round shields.</li>
          <li id="guide-step-map-tyr-s-foot-pelt-surrounded-by-1-shield-on-both-sides">Tyr's Foot => Pelt surrounded by 1 shield on both sides.</li>
          <li>If done correctly, a green portal will spawn on the pelt surrounded by the 4 shields.</li>
          <li>Survive 3 waves as zombies can only be killed with traps.</li>
        </ol>
      </div>
      <div class="relic-card grim">
        <div class="relic-title">??? <span class="mini-tag">TBD</span></div>
        <ol class="steps">
          <li>Reach Round 20</li>
          <li>TBD</li>
        </ol>
      </div>
    </div>
  </div>
  <div class="relic-section">
    <h2 class="relic-heading sinister">Sinister Relics</h2>
    <div class="relic-cards">
      <div class="relic-card sinister">
        <div class="relic-title">STUFFED ELEPHANT <span class="mini-tag">Health regen delay is increased</span></div>
        <ol class="steps">
          <li>Activate Cursed Mode Tier I</li>
          <li>Reach Round 40 without buying or getting any Perks.</li>
          <li id="guide-step-map-if-done-correctly-a-yellow-portal-will-spawn-on-a-wall-behind-juggerno">If done correctly, a yellow portal will spawn on a wall behind Juggernog in Fishery Island. <ShowOnMap target="fishery-island" /></li>
          <li id="guide-step-map-shoot-at-4-mr-peeks-eggs-located-around-the-map-and-defeat-the-hvt-tha">Shoot at 4 Mr. Peeks Eggs located around the map and defeat the HVT that will spawn.  On the lower catwalk at the lighthouse in Beacon Island. <ShowOnMap target="areas-lighthouse--beacon-island" /></li>
          <li id="guide-step-map-on-a-window-corner-at-the-house-behind-mule-kick-in-skallen-market">On a window corner at the house behind Mule Kick in Skallen Market. <ShowOnMap target="skallen-market" /></li>
          <li id="guide-step-map-near-tyr-s-foot-outside-of-storm-bridge">Near Tyr's Foot outside of Storm Bridge. <ShowOnMap target="areas-tyrs-foot--storm-bridge" /></li>
          <li id="guide-step-map-on-a-steel-beam-next-to-the-roof-opening-in-the-rk-9-room-at-dry-dock">On a steel beam next to the roof opening in the RK-9 room at Dry Dock. <ShowOnMap target="dry-dock" /></li>
        </ol>
      </div>
      <div class="relic-card sinister">
        <div class="relic-title">DANCING ARNIE <span class="mini-tag">All Perk-a-Cola machines have been cursed and now give out random Perk-a-Colas</span></div>
        <ol class="steps">
          <li>Activate Cursed Mode Tier I. Do not build the Jotunn Star before Step 4.</li>
          <li id="guide-step-map-get-the-pot-located-on-the-ground-below-a-wooden-table-behind-mule-kic">Get the pot located on the ground below a wooden table behind Mule Kick in Skallen Market and place it on the fire at the center of Blodheim Hall. <ShowOnMap target="areas-skallen-market--blodheim-hall" /></li>
          <li id="guide-step-map-get-2-items-and-place-them-inside-the-pot-in-blodheim-hall-the-beer-mu">Get 2 items and place them inside the pot in Blodheim Hall:  The beer mug located on a wooden barrel near the barge between Loven's Antiquities and the Arsenal in Eidskallen Square. Return to Blodheim Hall and pour the beer into the pot. <ShowOnMap target="areas-blodheim-hall--lovens-antiquities--eidskallen-square" /></li>
          <li id="guide-step-map-the-chilly-chunks-from-storm-bridge">The Chilly Chunks from Storm Bridge. <ShowOnMap target="storm-bridge" /></li>
          <li id="guide-step-map-with-an-explosive-weapon-shoot-at-the-truck-in-storm-bridge-to-get-a-n">With an explosive weapon shoot at the truck in Storm Bridge to get a new fish can and build the Jotunn Star.</li>
          <li>Get 2 more items to be placed inside the pot:  The red lobster dropped by killing a Necropincer with the Flammenfalle Trap only.</li>
          <li>Round 41+ — Wait for a Special Round and use the fishing spots to catch a unique fish item.</li>
          <li id="guide-step-map-if-done-correctly-mr-peeks-will-appear-above-the-pot-in-blodheim-hall">If done correctly, Mr. Peeks will appear above the pot in Blodheim Hall. <ShowOnMap target="blodheim-hall" /></li>
          <li>Kill 100 zombies with the Jotunn Star around Mr. Peeks.</li>
          <li id="guide-step-map-a-yellow-portal-will-spawn-on-a-wall-above-pack-a-punch-in-fishery-isl">A yellow portal will spawn on a wall above Pack-a-Punch in Fishery Island. <ShowOnMap target="fishery-island" /></li>
          <li>Survive 5 waves while the zombies and HVTs can only take melee damage.</li>
        </ol>
      </div>
    </div>
  </div>
  <div class="relic-section">
    <h2 class="relic-heading wicked">Wicked Relics</h2>
    <div class="relic-cards">
      <div class="relic-card wicked">
        <div class="relic-title">AGARTHAN DEVICE <span class="mini-tag">Each round, a different type of zombie will spawn</span></div>
        <ol class="steps">
          <li>Activate Cursed Mode Tier II and one player HAS TO be playing as Richtofen.</li>
          <li id="guide-step-map-reach-the-urzikstan-and-liberty-falls-room-when-ejecting-from-tyr-s-he">Reach the Urzikstan and Liberty Falls room when ejecting from Tyr's head. <ShowOnMap target="tyrs-head" /></li>
          <li>Urzikstan: Pick the military helmet located on a crate at the bottom of the shelves.</li>
          <li>Liberty Falls: Grab Mr. Peeks from under the bed.</li>
          <li id="guide-step-map-open-the-cell-in-group-935-genetic-lab-and-pick-up-the-radio-on-the-gr">Open the cell in Group 935 Genetic Lab and pick up the radio on the ground under the bench. <ShowOnMap target="genetic-lab" /></li>
          <li>Activate the Richtofen's Echo of the Damned quest (Round 15+).</li>
          <li id="guide-step-map-once-the-echo-of-von-list-has-left-place-the-items-on-the-seat">Once the echo of Von List has left, place the items on the seat. <ShowOnMap target="core-foundry" /></li>
          <li id="guide-step-map-if-done-correctly-a-red-portal-will-spawn-at-dry-dock">If done correctly, a red portal will spawn at Dry Dock. <ShowOnMap target="dry-dock" /></li>
          <li>Survive 6 waves while the zombies can only be damaged while the players are indoors.</li>
        </ol>
      </div>
      <div class="relic-card wicked">
        <div class="relic-title">MUSIC BOX <span class="mini-tag">Enemies only take critical damage</span></div>
        <ol class="steps">
          <li>Activate Cursed Mode Tier II</li>
          <li id="guide-step-map-reach-round-60-and-enter-tyr-s-head">Reach Round 60 and enter Tyr's Head. <ShowOnMap target="tyrs-head" /></li>
          <li id="guide-step-map-from-tyr-s-head-window-get-5-critical-kills">From Tyr's Head window, get 5 Critical Kills.</li>
          <li id="guide-step-map-if-done-correctly-mr-peeks-will-laugh-and-a-red-portal-will-spawn-on-a">If done correctly, Mr. Peeks will laugh and a red portal will spawn on a wall in Dry Dock near the Melee Macchiato machine. <ShowOnMap target="dry-dock" /></li>
          <li>Survive 6 waves by holding out lockdowns at specific locations on the map.</li>
        </ol>
      </div>
    </div>
  </div>
</div>
<h1 class="" id="wiki_wall_buys_and_perk_a_colas">Wall-Buys and Perk-a-Colas</h1>
<div class="glass-card glass-gold"><h2 data-guide-step class="" id="wiki_wall_buys_locations"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Wall-Buys Locations<span class="g-tag">🔫 Wall-Buys</span></span><span class="g-chev" aria-hidden="true"></span></label> <ShowOnMap target="locations-wall-buys-locations" label="Show wall-buys locations on map" /></h2>
<ul>
<li id="guide-step-map-coda-9-eidskallen-landing"><strong>CODA 9</strong> — Eidskallen Landing</li>
<li id="guide-step-map-echo-12-eidskallen-landing"><strong>Echo 12</strong> — Eidskallen Landing</li>
<li id="guide-step-map-rk-9-dry-dock"><strong>RK-9</strong> — Dry Dock</li>
<li id="guide-step-map-x9-maverick-dry-dock"><strong>X9 Maverick</strong> — Dry Dock</li>
<li id="guide-step-map-vs-recon-core-foundry"><strong>VS Recon</strong> — Core Foundry</li>
<li id="guide-step-map-ds20-mirage-war-factory"><strong>DS20 Mirage</strong> — War Factory</li>
<li id="guide-step-map-mxr-17-fishery-island"><strong>MXR-17</strong> — Fishery Island</li>
<li id="guide-step-map-warden-308-tyr-s-foot"><strong>Warden 308</strong> — Tyr's Foot</li>
<li id="guide-step-map-shadow-sk-tyr-s-shoulder"><strong>Shadow SK</strong> — Tyr's Shoulder</li>
<li id="guide-step-map-m34-novaline-tyr-s-head-ejection-knights-room"><strong>M34 Novaline</strong> — Tyr's Head Ejection - Knights Room</li>
<li id="guide-step-map-dravec-45-tyr-s-head-ejection-urzikstan-room"><strong>Dravec 45</strong> — Tyr's Head Ejection - Urzikstan Room</li>
<li id="guide-step-map-ak-27-tyr-s-head-ejection-liberty-falls-room"><strong>AK-27</strong> — Tyr's Head Ejection - Liberty Falls Room</li>
<li id="guide-step-map-m8a1-eidskallen-stave-church"><strong>M8A1</strong> — Eidskallen Stave Church</li>
<li id="guide-step-map-peacekeeper-mk1-skallen-market"><strong>Peacekeeper Mk1</strong> — Skallen Market</li>
<li id="guide-step-map-m10-breacher-blodheim-hall"><strong>M10 Breacher</strong> — Blodheim Hall</li>
<li id="guide-step-map-mpc-25-eidskallen-square"><strong>MPC-25</strong> — Eidskallen Square</li>
<li id="guide-step-map-xm325-beacon-island"><strong>XM325</strong> — Beacon Island</li>
</ul></div>
<div class="glass-card glass-green"><h2 data-guide-step class="" id="wiki_perks_locations"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Perks Locations<span class="g-tag">🥤 Perks</span></span><span class="g-chev" aria-hidden="true"></span></label> <ShowOnMap target="locations-perks-locations" label="Show perks locations on map" /></h2>
<p id="wiki_cursed_mister_peeks" data-guide-step><strong>Mister Peeks · Cursed mode:</strong> Check his possible spawn locations. Shoot him when he appears to drop an egg that can contain perks and other loot. <ShowOnMap target="cursed-mister-peeks" label="Show Mister Peeks Cursed-mode spawn locations on map" /></p>
<p><em>Note: Der Wunderfizz appears after purchasing 4 Perk-a-Colas or after reaching Round 20.</em></p>
<ul>
<li id="guide-step-map-quick-revive-eidskallen-landing"><strong>Quick Revive</strong> — Eidskallen Landing</li>
<li id="guide-step-map-melee-macchiato-dry-dock"><strong>Melee Macchiato</strong> — Dry Dock</li>
<li id="guide-step-map-stamin-up-eidskallen-square"><strong>Stamin-Up</strong> — Eidskallen Square</li>
<li id="guide-step-map-speed-cola-dry-dock"><strong>Speed Cola</strong> — Dry Dock</li>
<li id="guide-step-map-phd-flopper-dry-dock"><strong>PhD Flopper</strong> — Dry Dock</li>
<li id="guide-step-map-vulture-aid-blodheim-hall"><strong>Vulture Aid</strong> — Blodheim Hall</li>
<li id="guide-step-map-juggernog-fishery-island"><strong>Juggernog</strong> — Fishery Island</li>
<li id="guide-step-map-mule-kick-skallen-market"><strong>Mule Kick</strong> — Skallen Market</li>
<li id="guide-step-map-double-tap-root-beer-core-foundry"><strong>Double Tap Root Beer</strong> — Core Foundry</li>
<li id="guide-step-map-deadshot-daiquiri-storm-bridge"><strong>Deadshot Daiquiri</strong> — Storm Bridge</li>
<li id="guide-step-map-der-wunderfizz-beacon-island"><strong>Der Wunderfizz</strong> — Beacon Island</li>
</ul></div>
<h1 class="" id="wiki_miscellaneous_features">Miscellaneous Features</h1>
<div class="glass-card glass-amber"><h2 data-guide-step class="" id="wiki_armor_vests_locations"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Armor Vests Locations<span class="g-tag">🦺 Armor</span></span><span class="g-chev" aria-hidden="true"></span></label> <ShowOnMap target="locations-armor-vests-locations" label="Show armor vests locations on map" /></h2>
<ul>
<li id="guide-step-map-eidskallen-square">Eidskallen Square</li>
<li id="guide-step-map-dry-dock">Dry Dock</li>
</ul></div>
<div class="glass-card glass-red"><h2 data-guide-step class="" id="wiki_traps_locations"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Traps Locations<span class="g-tag">🪤 Traps</span></span><span class="g-chev" aria-hidden="true"></span></label> <ShowOnMap target="locations-traps-locations" label="Show traps locations on map" /></h2>
<ul>
<li id="guide-step-map-flammenfalle-fjord-road-beacon-island-eidskallen-square-core-foundry"><strong>Flammenfalle</strong>: Fjord Road, Beacon Island, Eidskallen Square, Core Foundry</li>
<li id="guide-step-map-fishy-fish-bot-eidskallen-square"><strong>Fishy Fish Bot</strong>: Eidskallen Square</li>
</ul></div>
<div class="glass-card glass-orange"><h2 data-guide-step class="" id="wiki_arsenal_locations"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Arsenal Locations<span class="g-tag">🎯 Arsenal</span></span><span class="g-chev" aria-hidden="true"></span></label> <ShowOnMap target="locations-arsenal-locations" label="Show arsenal locations on map" /></h2>
<ul>
<li id="guide-step-map-eidskallen-square-2">Eidskallen Square</li>
<li id="guide-step-map-beacon-island">Beacon Island</li>
</ul></div>
<div class="glass-card glass-amber"><h2 data-guide-step class="" id="wiki_crafting_table_locations"><label class="g-toggle"><input type="checkbox" class="g-cb"><span class="g-title">Crafting Table Locations<span class="g-tag">🔨 Crafting</span></span><span class="g-chev" aria-hidden="true"></span></label> <ShowOnMap target="locations-crafting-table-locations" label="Show crafting table locations on map" /></h2>
<ul>
<li id="guide-step-map-dry-dock-2">Dry Dock</li>
<li id="guide-step-map-eidskallen-stave-church">Eidskallen Stave Church</li>
</ul></div>
</template>
