<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><h1 id="wiki_key_features">Key Features</h1><section><h2 id="details-systems">Prepare the Stalingrad objective hub</h2><ol><li id="guide-step-anfang-objectives" data-guide-step>Choose a portal for the district you need to open and complete its objective. Read its on-screen condition: survival, enemy-drop deposits, escort/capture and defense tasks use different completion rules. Returning to Stalingrad opens that route and rewards a Sacrificial Heart. Spend Essence between objectives and recheck the refreshed Covenant offerings.</li>
<li id="guide-step-anfang-pap" data-guide-step>Pack-a-Punch is already in Stalingrad’s starting hub. Its upgrade tiers cost 7,500, 15,000 and 30,000 Essence. Ammo-mod effects come through Covenants rather than a Pack-a-Punch ammo-mod menu. These are Vanguard’s source-documented prices, not Cold War’s price schedule.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/remaining/extra-czg-der-anfang-02.png&quot;,&quot;previewSrc&quot;:&quot;/images/remaining/preview/extra-czg-der-anfang-02.webp&quot;,&quot;alt&quot;:&quot;Der Anfang hub Pack-a-Punch and its upgrade tiers&quot;,&quot;caption&quot;:&quot;Der Anfang hub Pack-a-Punch and its upgrade tiers&quot;,&quot;credit&quot;:&quot;COD Zombies Guides; game imagery Activision&quot;,&quot;width&quot;:970,&quot;height&quot;:720,&quot;source&quot;:&quot;https://www.codzombieguides.com/der-anfang&quot;,&quot;assetId&quot;:&quot;extra-czg-der-anfang-02&quot;}]' /></li>
<li id="guide-step-anfang-perks" data-guide-step>Find the opened districts’ perk fountains. The first drink at each is free; later tiers cost 2,500, 5,000 and 7,500 Essence. A down removes upgraded tiers while retaining the free first tier. Select health, mobility, reload and precision support for your task rather than assuming one fountain supplies every effect.<ul><li>Fiendish Fortitude: health; the Jugger-Nog counterpart.</li><li>Venomous Vigor: recovery/revive support; the Quick Revive counterpart.</li><li>Demonic Frenzy: reload speed; the Speed Cola counterpart.</li><li>Aethereal Haste: movement; the Stamin-Up counterpart.</li><li>Diabolical Damage: precision/critical damage; the Deadshot counterpart.</li></ul></li>
<li id="guide-step-anfang-hearts" data-guide-step>Use Sacrificial Hearts at the Altar of Covenants for available combat effects or at the Tome of Rituals to strengthen your artifact. Covenants refresh after objectives and become stronger at later rarity; inspect the actual offers. Brain Rot supplies temporary allies, melee bonuses help close fighting, and damage/reload bonuses suit different weapons.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/remaining/extra-czg-der-anfang-03.png&quot;,&quot;previewSrc&quot;:&quot;/images/remaining/preview/extra-czg-der-anfang-03.webp&quot;,&quot;alt&quot;:&quot;Altar of Covenants in Stalingrad&quot;,&quot;caption&quot;:&quot;Altar of Covenants in Stalingrad&quot;,&quot;credit&quot;:&quot;COD Zombies Guides; game imagery Activision&quot;,&quot;width&quot;:632,&quot;height&quot;:556,&quot;source&quot;:&quot;https://www.codzombieguides.com/der-anfang&quot;,&quot;assetId&quot;:&quot;extra-czg-der-anfang-03&quot;}]' /></li>
<li id="guide-step-anfang-artifacts" data-guide-step>Choose an artifact to fit the objective: Aether Shroud gives a brief escape/repositioning window; Frost Blast slows nearby pressure; Energy Mine damages a prepared enemy cluster; Ring of Fire supports damage while holding an area. Upgrade it with the Tome of Rituals and use the game’s charge indicator instead of a website countdown.</li>
<li id="guide-step-anfang-crafting" data-guide-step>Collect the single green salvage type and use the crafting table for armour, equipment and support. Repair armour before another portal or Void session. A Heart, salvage and Essence are different resources; buying a Covenant does not upgrade your weapon.</li></ol></section>
<h1 id="wiki_main_quest">Main Quest</h1><section><h2 id="details-command-post">Open Command Post and Von List’s Office</h2><ol><li id="guide-step-anfang-east" data-guide-step>Complete the objective portal leading to Panzer Column East. Then complete the Store portal objective to open Command Post. Enter the building and reach Von List’s Office on its upper floor.</li></ol></section>
<section><h2 id="details-void">Return from the Office’s Void portal</h2><ol><li id="guide-step-anfang-void-enter" data-guide-step>Use the Void portal inside Von List’s Office. Survive three full rounds in its Shi No Numa area. This opens the return portal near Flinger Gate; you may stay for further survival, but take the return portal for the narrative route.</li>
<li id="guide-step-anfang-void-return" data-guide-step>Watch the return scene and wait until control/dialogue is available in Stalingrad before the next door interaction.</li></ol></section>
<section><h2 id="details-kraft">Speak through Command Post’s marked door</h2><ol><li id="guide-step-anfang-kraft-door" data-guide-step>Go back up Command Post’s stairs and interact with the white door bearing the magical symbol. Let Krafft and the Dark Aether entities finish their conversation.</li></ol></section>
<section><h2 id="details-apartments">Activate the Apartments rune and final portal event</h2><ol><li id="guide-step-anfang-apartments-rune" data-guide-step>Complete the remaining portal objectives needed to open Apartments. On its top floor, find the room with a floor ritual and interact with the rune stone. Wait for the conversation and Krafft’s cue about Command Post.</li>
<li id="guide-step-anfang-final-portal" data-guide-step>Return to the top of the Command Post stairs, turn to the opposite wall and observe the newly formed green portal. Let the final conversation finish. This is Der Anfang’s narrative endpoint; there is no additional boss arena in this short quest.</li></ol></section>
<h1 id="wiki_side_quests">Side Quests</h1><section><h2 id="details-exfil">Ordinary objective-map exfil</h2><ol><li id="guide-step-anfang-exfil" data-guide-step>Once the hub offers Exfil after the early objective progression, interact with the Exfil marker and confirm with your squad. Complete its marked elimination task, then reach/use the escape portal before the displayed timer expires. This ends your match; the short Office story does not automatically exfil you.</li></ol></section>
<section><h2 id="details-story-records">Radios and ancient tablets</h2><ol><li id="guide-step-anfang-records" data-guide-step>Interact with the radios and rune tablets in the opened hub districts to hear their story segments. You can listen again in the same match; these are in-world recordings rather than Cold War inventory intel. Use the illustrated source’s radio/tablet section for individual sightlines.<p><a href="https://www.codzombieguides.com/der-anfang" target="_blank" rel="noopener noreferrer">Illustrated radio and ancient-tablet reference ↗</a></p></li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Source-reviewed on 8 October 2026, using the references below and the research handoff. These instructions and puzzle calculations have software checks; they have not been verified in a complete in-game playthrough. Record symbols, sequences and completion cues from your match. Screenshot and community-chart creators are credited with each illustration.</p><ul><li><a href="https://www.codzombieguides.com/der-anfang" target="_blank" rel="noopener noreferrer">codzombieguides.com reference ↗</a></li>
<li><a href="https://www.treyarch.com/game-intel/2021/11/Your_Gameplay_Guide_to_Vanguard_Zombies" target="_blank" rel="noopener noreferrer">treyarch.com reference (2) ↗</a></li>
<li><a href="https://www.callofduty.com/ca/en/blog/2021/11/call-of-duty-vanguard-zombies-der-anfang-20-tips" target="_blank" rel="noopener noreferrer">Official Call of Duty guide (3) ↗</a></li></ul><p>Select any reference image to enlarge it. Screenshot and symbol sources are credited in the linked walkthroughs; this guide uses local copies for reliable access.</p></section></div></template>
