<!-- Generated from shared/expansion-guides.mjs; edit the authored data. -->
<template><div><h1 id="wiki_key_features">Key Features</h1><section><h2 id="details-setup">Power and the three teleporter routes</h2><ol><li id="guide-step-der-power" data-guide-step>Open either side from the mainframe at Spawn and work toward the rear central courtyard. Activate the power switch beside the original Box location; the bridge lowers and the perk machines and electric traps become available.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/classic/der-riese/pap/power_switch.webp&quot;,&quot;alt&quot;:&quot;Power Switch&quot;}]' /></li>
<li id="guide-step-der-links" data-guide-step>Find Teleporter A through Animal Testing on the left route, B through the Thompson/Automobile Garage route on the right, and C at the back by the catwalk/Bowie Knife area. At each teleporter, hold interact to start a link, then reach the mainframe in Spawn and interact within 30 seconds. A teammate may finish the link for you.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/classic/der-riese/pap/tele_a.webp&quot;,&quot;alt&quot;:&quot;Teleporter A - Left of spawn&quot;},{&quot;src&quot;:&quot;/images/classic/der-riese/pap/tele_b.webp&quot;,&quot;alt&quot;:&quot;Teleporter B - Right of spawn&quot;},{&quot;src&quot;:&quot;/images/classic/der-riese/pap/tele_c.webp&quot;,&quot;alt&quot;:&quot;Teleporter C - Power Switch Area&quot;},{&quot;src&quot;:&quot;/images/classic/der-riese/pap/mainframe.webp&quot;,&quot;alt&quot;:&quot;mainframe&quot;}]' /></li>
<li id="guide-step-der-pap" data-guide-step>Every successful link lowers the barrier around the Pack-a-Punch machine. After all three, upgrade a gun at Spawn for 5,000 points. Linked teleporters can return you to the mainframe for 1,500 points, but check the pad is clear before arriving.</li>
<li id="guide-step-der-perks" data-guide-step>The key purchases are Jugger-Nog on the raised Animal Testing side, Speed Cola near the courtyard, Double Tap above the Thompson route and Quick Revive by the catwalk area. Quick Revive speeds up reviving a teammate; it does not provide BO1-style solo self-revives in World at War. Double Tap is the original fire-rate perk, not Double Tap II.</li></ol></section>
<section><h2 id="details-equipment">Wunderwaffe, Monkey Bombs and factory survival</h2><ol><li id="guide-step-der-weapons" data-guide-step>The Box can supply the Wunderwaffe DG-2, Ray Gun and Monkey Bombs. Avoid self-zapping with the Wunderwaffe: in original World at War Der Riese, its splash can break your health/Jugger-Nog protection while the perk icon remains. Shoot at a compact horde from a clear distance.</li>
<li id="guide-step-der-survival" data-guide-step>The rear catwalk makes a straightforward co-op hold when each player has ammunition and an assigned lane. At higher rounds, prepare the courtyard/trap route before the hold collapses. Monkey Bombs give time to revive or leave, but throw onto reachable floor and allow the lure to start.</li>
<li id="guide-step-der-dogs" data-guide-step>Hellhound rounds finish with Max Ammo; dogs later join ordinary waves. Reload before the final dog dies and announce the pickup. Bouncing Betties and a loaded secondary help cover the time spent reloading a heavy weapon.</li></ol></section>
<h1 id="wiki_side_quests">Side Quests</h1><section><h2 id="details-fly-trap">Fly Trap: original three-target hunt</h2><ol><li id="guide-step-der-panel" data-guide-step>Bring a Pack-a-Punched bullet weapon to the zombie window beside the M1 Carbine near Spawn. Aim through it at the distant control panel on the concrete pillar and shoot. Green objects rise and Samantha speaks when the shot registers.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/classic/der-riese/main_ee/panel.webp&quot;,&quot;alt&quot;:&quot;control panel&quot;},{&quot;src&quot;:&quot;/images/classic/der-riese/main_ee/panel_zoomed_out.webp&quot;,&quot;alt&quot;:&quot;zoomed-out view&quot;}]' /></li>
<li id="guide-step-der-targets" data-guide-step>Damage all three original-version targets in any order. Listen for Samantha after each hit. Use these photographs rather than The Giant’s different hiding places.<ul><li>Thompson/Teleporter B route: the monkey in the open furnace beneath the stairs.</li><li>Spawn: the teddy in the broken upper window above the M1 Carbine, toward Teleporter A.</li><li>Teleporter A/Animal Testing: the teddy inside the lower-left cage beside the Trench Gun area.</li></ul><GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/classic/der-riese/main_ee/toy_furnace_waw.webp&quot;,&quot;alt&quot;:&quot;Teleporter B Thompson Room - In the furnace below the stairs&quot;},{&quot;src&quot;:&quot;/images/classic/der-riese/main_ee/toy_spawn_waw.webp&quot;,&quot;alt&quot;:&quot;Spawn - In a broken window above the M1 Carbine wallbuy (toward Tele A)&quot;},{&quot;src&quot;:&quot;/images/classic/der-riese/main_ee/toy_tele_a_waw.webp&quot;,&quot;alt&quot;:&quot;Teleporter A - In the bottom left cage, right of the M1897 Trench Gun wallbuy&quot;}]' /></li>
<li id="guide-step-der-reward" data-guide-step>Samantha’s final scream confirms that all targets were found. In World at War this also earns Elevate Your Senses. The original hunt provides no weapon pickup or permanent perks; the Annihilator reward belongs to BO3’s The Giant.</li></ol></section>
<section><h2 id="details-music">Beauty of Annihilation</h2><ol><li id="guide-step-der-song" data-guide-step>Interact with three jars containing nervous tissue. Two sit opposite one another in Animal Testing near the stairs toward Jugger-Nog; the third is on a table by the chalkboard in the side room beside Teleporter B. Stand close and face each jar. After all three register, Beauty of Annihilation plays.<GuideIllustrations :images='[{&quot;src&quot;:&quot;/images/classic/der-riese/song_ee/jar_shelf.webp&quot;,&quot;alt&quot;:&quot;Animal Testing (left side) - On a shelf near the bottom of the stairs to Jug&quot;},{&quot;src&quot;:&quot;/images/classic/der-riese/song_ee/jar_stairs.webp&quot;,&quot;alt&quot;:&quot;Animal Testing (left side) - Across from the previous locations, directly to the right of the stairs to Jug&quot;},{&quot;src&quot;:&quot;/images/classic/der-riese/song_ee/jar_tele_b.webp&quot;,&quot;alt&quot;:&quot;Teleporter B - In the side room, right of the teleporter, on a table beside the chalkboard&quot;}]' /></li></ol></section>
<section><h2 id="details-recordings">Factory recordings and environmental secrets</h2><ol><li id="guide-step-der-radios" data-guide-step>There are four handheld radios and three larger recording devices. Activate one at a time and let its clip finish. The larger devices play the experiments in narrative order regardless of which physical unit you use first. These recordings have no combat reward.<ul><li>Spawn: beside the barrels to the right of the stairs descending from the mainframe.</li><li>Animal Testing: above the cabinet/door opposite the Trench Gun, near its Box location.</li><li>Teleporter C: at the closed end of the low tunnel beneath Quick Revive, behind the boards.</li><li>Teleporter B: low down on the ladder of the first large tank; look down into it.</li><li>Large device: on the shelf at the foot of the Teleporter C catwalk stairs.</li><li>Large device: on the tilted filing cabinet above the main furnace, before the bridge.</li><li>Large device: inside the open furnace/recess beneath Teleporter A, beside the stairs.</li></ul><p><a href="https://gamefaqs.gamespot.com/boards/944199-call-of-duty-world-at-war/50828245" target="_blank" rel="noopener noreferrer">Original radio-location discussion ↗</a></p></li>
<li id="guide-step-der-brick" data-guide-step>Beside the Thompson wall buy, inspect the brickwork just to its right. Interact with the small differently coloured brick to slide it and reveal the note beneath. It is a story clue; no further weapon-upgrade recipe follows from it.</li>
<li id="guide-step-der-monkey" data-guide-step>Throw a Monkey Bomb into the open furnace below the nearby stairs for the special burning-monkey reaction and Samantha’s response. This consumes a bomb and gives no confirmed damage upgrade. The book visible through the vent near Double Tap is another environmental detail.</li></ol></section><section><h2 id="guide-sources">Sources and review</h2><p>Written for the original World at War PC/console maps; mobile editions and modded maps can differ. Community guides and illustrated references were cross-checked on 3 October 2026. Gameplay: Activision / Treyarch; photographs: the credited community authors below. Reused photographs may show a remaster of the same location; the instructions describe this edition. Source review and software checks are not an in-game playthrough.</p><ul><li><a href="https://www.reddit.com/r/CODZombies/wiki/der-riese/" target="_blank" rel="noopener noreferrer">r/CODZombies community guide ↗</a></li>
<li><a href="https://mmmrkennedy.com/games/WAW/der_riese/der_riese_guide" target="_blank" rel="noopener noreferrer">mmmrkennedy illustrated guide (2) ↗</a></li>
<li><a href="https://strategywiki.org/wiki/Call_of_Duty%3A_World_at_War/Nazi_Zombies" target="_blank" rel="noopener noreferrer">strategywiki.org reference (3) ↗</a></li>
<li><a href="https://gamefaqs.gamespot.com/boards/944199-call-of-duty-world-at-war/50828245" target="_blank" rel="noopener noreferrer">GameFAQs original-game walkthrough and community research (4) ↗</a></li>
<li><a href="https://eeggs.com/items/57607.html" target="_blank" rel="noopener noreferrer">eeggs.com reference (5) ↗</a></li>
<li><a href="https://www.jeuxvideo.com/wikis-soluce-astuces/localisation-des-radios-dans-der-riese/228246" target="_blank" rel="noopener noreferrer">jeuxvideo.com reference (6) ↗</a></li></ul><p>Select any reference image to enlarge it. Screenshot and symbol sources are credited in the linked walkthroughs; this guide uses local copies for reliable access.</p></section></div></template>
